### PR TITLE
Allow ec2_vol to pick a free non-root /dev/* slot

### PR DESCRIPTION
**Pull request by 399a36c3b7**
##### Issue Type:
- Feature Pull Request
##### Plugin Name:

ec2_vol
##### Ansible Version:

```
ansible 2.1.0 (devel 03c33053aa) last updated 2016/02/24 11:07:49 (GMT -400)
```
##### Summary:

ec2_vol requires the user to specify an explicit device_name. It can be improved by allowing an option to allow ebs volumes to be attached to a free non-root device rather than to have to know it in advance, making ec2_vol more useful for reusable ansible snippets, especially when finding and re-attaching volumes by Name.
##### Example usage:

```
- ec2_vol:
    instance: "i-aaaaaaaaa"
    name: "some-existing-vol-name"
    device_name: "/dev/xvd{}"
```
##### Example output:

```
<127.0.0.1> REMOTE_MODULE ec2_vol snapshot='' volume_size=2 device_name='/dev/xvd{}' region=us-east-1 instance=i-aaaaaaaa zone=us-east-1b name=my-named-volume
changed: [test_host -> 127.0.0.1] => {"changed": true, "device": "/dev/xvdf", "volume": {"attachment_set": {"attach_time": "2016-02-24T15:01:19.000Z", "deleteOnTermination": "false", "device": "/dev/xvdf", "instance_id": "i-aaaaaaaa", "status": "attached"}, "create_time": "2016-02-24T15:01:10.890Z", "encrypted": true, "id": "vol-80eac85f", "iops": null, "size": 2, "snapshot_id": "", "status": "in-use", "tags": {"Name": "my-named-volume"}, "type": "standard", "zone": "us-east-1b"}, "volume_id": "vol-bbbbbbbb", "volume_type": "standard"}
```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @alxnov for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

**Comment by gregdek** [comment]
Thanks @alxnov for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@alxnov A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@alxnov Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@alxnov A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@alxnov Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@alxnov A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@alxnov Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@alxnov A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@alxnov Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@alxnov A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by morokin** [comment]
Hi guys, any news on this issue? I just checked this with Ansible 2.2, nothing has been changed, in the massive deployment this feature will be useful. Maybe I can help somehow?

**Comment by gregdek** [comment]
@alxnov Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@alxnov A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
