### PR TITLE
Add umask option to pip module

### PR DESCRIPTION
**Pull request by joelthompson**
On systems with restrictive umasks, the pip module won't allow you to
install pip packages that are usable by everyone on the system. This
commit adds a umask option to optionally override the umask on a
per-package basis.

### CODE REVIEW

**Comment by joelthompson** [comment]
I'll refactor to make compatible with Python 2.4, but really, Python 2.4? Is there a plan to deprecate it?

Separately, there's no mention in [the documentation](http://docs.ansible.com/ansible/developing_modules.html) that modules should be compatible with a python as ancient as 2.4. If that's truly a requirement (or even just a base expectation), it should be in the documentation.

**Comment by bcoca** [comment]
We mention it when setting the target node requirements http://docs.ansible.com/ansible/intro_installation.html#managed-node-requirements

This is not something we chose arbitrarily, the fact is that many users have a fleet of older OS versions that have Python 2.4 as the installed Python. 
Once these are phased out we will probably drop the requirement also.

**Comment by gregdek** [comment]
Thanks @joelthompson. @mattupstate please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by robynbergeron** [comment]
Thanks @joelthompson for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

**Comment by joelthompson** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @joelthompson. @mattupstate please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
Thanks @joelthompson. @mattupstate please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
@mattupstate This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by mattupstate** [comment]
I don't believe I'm the best person to review this change at this time. There's a significant contribution of code here that appears to use some module internals that I've never familiarized myself with.

**Comment by joelthompson** [comment]
@mattupstate -- there's not really a lot of code here. It _appears_ to be a large diff because I had to add a level of indentation to a large block and GitHub's differ isn't handling that whitespace change well :/ If, for the purposes of review, you unindent the try block starting on line 305, it should (I believe) produce a much cleaner diff view.

**Comment by mattupstate** [comment]
@joelthompson Ah, apologies. shipit !

**Comment by nnutter** [comment]
@mattupstate, @joelthompson GitHub tip: add `?w=1` to URL for `git diff -w` equivalent.

**Comment by robynbergeron** [comment]
Thanks again to @joelthompson for this PR, and thanks @mattupstate for reviewing. Marking for inclusion.

**Pull request merged**
