### PR TITLE
Backport #4626 to stable-2.1

### PR DESCRIPTION
**Pull request by dagwieers**
##### ISSUE TYPE

- Bugfix Pull Request
##### COMPONENT NAME

unarchive
##### ANSIBLE VERSION

v2.1.2.0
##### SUMMARY

This was requested in #4626 by @resmo.

### CODE REVIEW

**Comment by dagwieers** [comment]
shipit

**Comment by dagwieers** [comment]
@resmo I would prefer to also backport #4131 to stable-2.1 as it fixes a few known issues.

**Comment by dagwieers** [comment]
Also I am not sure why Shippable fails, the output does not show any error (or at least it is not obvious from the overview).

**Comment by gregdek** [comment]
Thanks @dagwieers for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by mattclay** [comment]
@dagwieers I've fixed CI on stable-2.1. You'll need to rebase your branch to pick up the fix.

**Comment by perzizzle** [comment]
@gregdek @dagwieers +1 for the backpatch, I've been manually patching this on our control servers so that unarchive works.

**Pull request merged**
