### PR TITLE
Missing documentation fix

### PR DESCRIPTION
**Pull request by Petrox**
Extending the documentation to state, that this module does not handle externals well.

### CODE REVIEW

**Comment by gregdek** [comment]
@dsummersl Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

(I know this is a pretty simple PR, but would be nice to get validation that this new assertion in the docs is correct and useful.)

**Comment by dsummersl** [comment]
The change in this PR looks fine WRT the module checklist.

I did notice one additional change that should probably happen though:
- `For password / secret arguments no_log=True should be set`: This isn't set for the `password` documentation section.
- `Requirements should be documented, using the requirements=[] field`: The `svn` requirement is documented under `notes`, but it looks like that should migrate to `requirements`.
- `Does module use check_mode? Could it be modified to use it? Document it`: It does, its not documented.

Open a separate issues for these?

**Comment by gregdek** [comment]
Missed this. @dsummersl I would say open a separate issue for the others; we'll just put this one into shipit per your advice. Thanks @Petrox for the PR.

**Comment by dsummersl** [comment]
will do.

**Comment by Petrox** [comment]
@gregdek Although correct docs are important, but I believe implementing the handling of externals would be a better solution, as the current subversion module is just half-working. And the funnyest bug existing is that ansible hits me with warnings for using shell: svn :) :beetle: 

Maybe in a later release module svn gets a little treatment. :+1:

**Pull request merged**
