### PR TITLE
Fix status after pip installations with VCS urls

### PR DESCRIPTION
**Pull request by dvarrazzo**
This is a rebase of pull request #1881 (where I mistakenly submitted the devel branch so I prefer to make a new one).

### CODE REVIEW

**Comment by dvarrazzo** [comment]
ready_for_review

**Comment by dvarrazzo** [comment]
Tests for this pull request have been submitted in ansible/ansible#13016

**Comment by gregdek** [comment]
Thanks @dvarrazzo. 

@mattupstate Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by gregdek** [comment]
@mattupstate This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by mattupstate** [comment]
shipit

**Comment by gregdek** [comment]
Thanks again to @dvarrazzo for this PR, and thanks @mattupstate for reviewing. Marking for inclusion.

**Comment by abadger** [comment]
Thanks for the work here!  merged.

**Pull request merged**
