### PR TITLE
Allow for non-standard DB schema

### PR DESCRIPTION
**Pull request by hhsnow**
MySQL-compatible servers (such as Clustrix) can use non-standard database schema for user storage. For example, Clustrix, uses the database `system`, the table `users`, and `username` for the user column  name. This pull request adds user parameters to override the defaults.

### CODE REVIEW

**Comment by Jmainguy** [comment]
@hhsnow So is this mainly to support Clusterix,? Would this work in mysql as well?

**Comment by hhsnow** [comment]
@Jmainguy Yeah, it works with mysql still if you take the default values. I'm just adding in optional values to support Clustrix's differing database + table names.

**Comment by robynbergeron** [comment]
Thanks @hhsnow. @Jmainguy please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
@Jmainguy This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by Jmainguy** [comment]
```
[root@phy01 test]# cat roles/mysqlu/tasks/main.yml
---


- name: add user jon
  mysql_user: name=jon state=present password=jon

- name: change jons password
  mysql_user: name=jon password=jon2

- name: remove jon
  mysql_user: name=jon state=absent

- name: make sure bob still doesnt exist
  mysql_user: name=bob state=absent

- name: userdb_db=neat
  mysql_user: name=jon state=present password=jon userdb_db=neat
  ignore_errors: true

- name: userdb_table=neat
  mysql_user: name=jon state=present password=jon userdb_table=neat
  ignore_errors: true

- name: userdb_table=neat
  mysql_user: name=jon state=present password=jon userdb_col_user=neat
  ignore_errors: true
[root@phy01 test]# ansible-playbook -i hosts  site.yml 

PLAY [Test] ********************************************************************

TASK [mysqlu : add user jon] ***************************************************
changed: [centos7.soh.re]

TASK [mysqlu : change jons password] *******************************************
changed: [centos7.soh.re]

TASK [mysqlu : remove jon] *****************************************************
changed: [centos7.soh.re]

TASK [mysqlu : make sure bob still doesnt exist] *******************************
ok: [centos7.soh.re]

TASK [mysqlu : userdb_db=neat] *************************************************
fatal: [centos7.soh.re]: FAILED! => {"changed": false, "failed": true, "msg": "unable to connect to database, check login_user and login_password are correct or /root/.my.cnf has the credentials. Exception message: (1049, \"Unknown database 'neat'\")"}
...ignoring

TASK [mysqlu : userdb_table=neat] **********************************************
fatal: [centos7.soh.re]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "Traceback (most recent call last):\r\n  File \"/root/.ansible/tmp/ansible-tmp-1457831587.83-122057599202384/mysql_user\", line 2831, in <module>\r\n    main()\r\n  File \"/root/.ansible/tmp/ansible-tmp-1457831587.83-122057599202384/mysql_user\", line 562, in main\r\n    if user_exists(cursor, user, host, host_all, schema):\r\n  File \"/root/.ansible/tmp/ansible-tmp-1457831587.83-122057599202384/mysql_user\", line 226, in user_exists\r\n    schema['table'], schema['col_user'], user, host))\r\n  File \"/usr/lib64/python2.7/site-packages/MySQLdb/cursors.py\", line 174, in execute\r\n    self.errorhandler(self, exc, value)\r\n  File \"/usr/lib64/python2.7/site-packages/MySQLdb/connections.py\", line 36, in defaulterrorhandler\r\n    raise errorclass, errorvalue\r\n_mysql_exceptions.ProgrammingError: (1146, \"Table 'mysql.neat' doesn't exist\")\r\n", "msg": "MODULE FAILURE", "parsed": false}
...ignoring

TASK [mysqlu : userdb_table=neat] **********************************************
fatal: [centos7.soh.re]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "Traceback (most recent call last):\r\n  File \"/root/.ansible/tmp/ansible-tmp-1457831587.96-72587271033568/mysql_user\", line 2831, in <module>\r\n    main()\r\n  File \"/root/.ansible/tmp/ansible-tmp-1457831587.96-72587271033568/mysql_user\", line 562, in main\r\n    if user_exists(cursor, user, host, host_all, schema):\r\n  File \"/root/.ansible/tmp/ansible-tmp-1457831587.96-72587271033568/mysql_user\", line 226, in user_exists\r\n    schema['table'], schema['col_user'], user, host))\r\n  File \"/usr/lib64/python2.7/site-packages/MySQLdb/cursors.py\", line 174, in execute\r\n    self.errorhandler(self, exc, value)\r\n  File \"/usr/lib64/python2.7/site-packages/MySQLdb/connections.py\", line 36, in defaulterrorhandler\r\n    raise errorclass, errorvalue\r\n_mysql_exceptions.OperationalError: (1054, \"Unknown column 'neat' in 'where clause'\")\r\n", "msg": "MODULE FAILURE", "parsed": false}
...ignoring

PLAY RECAP *********************************************************************
centos7.soh.re             : ok=7    changed=3    unreachable=0    failed=0   
```

@hhsnow I really do apologize for the delay in reviewing this. Thank you for working on it.

Looks like userdb_col_user and userdb_table throw a traceback if used with a random incorrect value on traditional mariadb server. See if you can get it to not traceback (add a try: except: block to catch the error). 

Add version_added: "2.1" to all 3 in the doc sections. Also add an example for each one in the example section.

See if you can squash all the commits down into one commit.

**Comment by gregdek** [comment]
Thanks @hhsnow for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

**Comment by gregdek** [comment]
@hhsnow A friendly reminder: this pull request has been marked as needing your action, and it hasn't been updated in the last two weeks. 

If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we'll keep it open pending your changes.

If we receive no indication from you within two more weeks, we will close this pull request.

**Comment by gregdek** [comment]
Thanks @hhsnow for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@hhsnow A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@hhsnow Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@hhsnow A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@hhsnow Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@hhsnow A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@hhsnow Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@hhsnow A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@hhsnow Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@hhsnow A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@hhsnow Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@hhsnow A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@hhsnow Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@hhsnow A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@hhsnow Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
