### PR TITLE
Fix resource_pool search in vsphere_client.get_resource_pool

### PR DESCRIPTION
**Pull request by miticojo**
In current version, if **resource_pool** is defined and you don't add prefix "/Resources/" to resource pool name, you get every time following error:

```
Cannot find Resource Pool named: <resource_pool>
```

For more details refer to [VMware SDK](https://www.vmware.com/support/developer/vc-sdk)

Note: if you want to avoid this fixed string in the code, I suggest to modify module documentation specifying the need of "/Resources/" prefix.

### CODE REVIEW

**Comment by bcoca** [comment]
to avoid breaking playbooks of those specifying /Resources, make it conditional on startswith()

**Comment by miticojo** [comment]
done as suggested! Tnx

**Comment by bcoca** [comment]
better but ternary statements are frowned upon

**Comment by miticojo** [comment]
Sorry Brian, do you mean that ternary statement (that I've used) is not frowned upon? so I've to use a standard if ...else... ?

**Comment by bcoca** [comment]
they ARE frowned upon, please change it or I will be yelled at if I merge it

**Comment by gregdek** [comment]
Hi @miticojo -- thanks for submitting this pull request. Please accept our apologies for taking so long to review it.

Unfortunately, due to this delay, it appears that the underlying code has changed, and this PR needs to be rebased. If you believe that this PR still applies, please rebase and we will then put it into our (new, faster) community review process as soon as possible.  Again, apologies for the delay and the extra work.

**Comment by gregdek** [comment]
@miticojo A friendly reminder: this pull request has been marked as needing your action, and it hasn't been updated in the last month. 

If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we'll keep it open pending your changes.

If we receive no indication from you within a week, we will close this pull request.

**Comment by gregdek** [comment]
Closed due to inactivity.

**Pull request closed without merging**
