### PR TITLE
Add Heat stack ansible module to be able to Create and delete stack

### PR DESCRIPTION
**Pull request by matbu**

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @matbu for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

**Comment by matbu** [comment]
Thanks @gregdek for the response, this module depend on a patch submitted into shade :
https://review.openstack.org/254337
I hit this bug when I developed the heat ansible module, just to let you know in case of ...

**Comment by matbu** [comment]
Thanks Pilou for the review, I addressed your comments.

**Comment by steveb** [comment]
I'm a core heat developer and ansible user, so I have opinions on os_stack ;)

Let me know if there is any way I can help with this, including coding if necessary.

**Comment by gregdek** [comment]
@Shrews does this belong here or in Extras?

**Comment by Shrews** [comment]
@gregdek New modules go into extras.

**Comment by gregdek** [comment]
@matbu thanks for this PR, but it's in the wrong place. Sorry for taking a while to make this decision. We still welcome the module, but as @Shrews says, new modules now go into ansible-modules-extras; please feel free to reopen this PR there. Thanks!

**Pull request closed without merging**
