### PR TITLE
cloud - azure affinity groups (new feature)

### PR DESCRIPTION
**Pull request by lander2k2**
Allows creation and deletion of Azure affinity groups.

### CODE REVIEW

**Comment by gregdek** [comment]
@jwhitbeck can you please review this new module? If you give it a +1 we will consider for inclusion.

**Comment by jwhitbeck** [comment]
@gregdek  I'm afraid I no longer actively use azure, and my knowledge of the API is quite rusty at this point. I don't think I'm in the best position to review this module.

**Comment by gregdek** [comment]
Thanks @jwhitbeck.

@bennojoy can you take a look?

**Comment by gregdek** [comment]
Ping to core team for potential review here -- or deferral to extras.

**Comment by gregdek** [comment]
@ansible/core ping

**Comment by bennojoy** [comment]
@jwhitbeck  looks good, could you please add the version_added to 2.0 and also maybe do a version check of the azure module done below  
https://github.com/ansible/ansible-modules-core/blob/devel/cloud/azure/azure.py#L542

**Comment by bennojoy** [comment]
@jwhitbeck  might be a bit late for 2.0.. please make the version_added as 2.1

**Comment by bennojoy** [comment]
@lander2k2 the comments were  for you.. :)  @jwhitbeck  sorry..

**Comment by gregdek** [comment]
Pinging the @ansible/core team to find out why this shouldn't be in Extras. Do we need to create a new Azure directory for these?

**Comment by gregdek** [comment]
ping @nitzmahone -- will this still be relevant in the new world of Azure modules?

**Comment by nitzmahone** [comment]
Thanks for the submission. Given that Microsoft is in the process of deprecating both the ServiceManagement API and affinity groups for Azure, we're going to respectfully decline this PR. (see https://azure.microsoft.com/en-us/documentation/articles/virtual-networks-migrate-to-regional-vnet/ for more details on affinity group deprecation).

We'll soon be shipping a whole suite of modules written against the new Azure Resource Manager that will enable the use of regional VNets as suggested by the article above.

**Pull request closed without merging**
