### PR TITLE
Add ec2_vpc_route_table and ec2_vpc_subnet modules.

### PR DESCRIPTION
**Pull request by dopry**
As discussed in #322, this is the ec2_vpc_route_table and and ec2_vpc_subnet module written by @erydo without the modifications to ec2_vpc. 

I also included patch from @herbygillot, https://github.com/ansible/ansible-modules-core/commit/5fd1aa6e646071f0dd6a515a2d6fc0ce809c9b54, that adds support for specifying the gateway_id as 'igw'. I switched from INTERNET_GATEWAY to confirm with how you specify it in the AWS managment console.

### CODE REVIEW

**Comment by dopry** [comment]
@defionscode,  I pushed the result of an interactive rebase of @erydo and @herbygillot   work on #322  that preserves their names on the commit history and excludes any changes to ec2_vpc. I haven't tested these exact files.

**Comment by juliedavila** [comment]
Awesome. Only issue, which I should have mentioned earlier, is that this is all a single pull request. The changes to ec2_vpc, and the creation of the route_table and subnet modules should all be in separate pull requests.

**Comment by dopry** [comment]
Oh, I thought I had skipped all the changes to ec2_py... I guess I missed on. Let me find it and rebase again.

**Comment by dopry** [comment]
@defionscode, all better now.

**Comment by juliedavila** [comment]
@dopry Good that the original module is still untouched but I wasn't clear enough. I meant to say that the two modules (route table and subnet) should also each be their own pull request. Would it be too painful to ask you to rebase this again with just a single module then make a new pr with the second?

**Comment by juliedavila** [comment]
@dopry friendly ping

**Comment by dopry** [comment]
@defionscode, sorry take it as is or not at all. I'm using this code in my own modules and have nothing to gain investing more of my time in this. you're paid to maintain the product, re-base it yourself if you want to be so particular.

**Comment by juliedavila** [comment]
@dopry, sorry for your frustration. It's a guideline we have internally, not one I decided arbitrarily. I'll shoot to do the rebase myself. Thanks for helping to the extent that you did.

**Comment by wimnat** [comment]
@defionscode did you rebase this yourself in the end? I'm keen to see the new vpc module and these two in v2 so I'm happy to rebase for you if it helps. I wouldn't like to see @dopry work go unloved!

**Comment by juliedavila** [comment]
@wimnat I have not yet, I've finished the new vpc module (no pr yet) but still need the subnet and route table modules. I've just been super consumed with other work, if you are willing to rebase definitely do so, I would greatly appreciate it, just be sure to mention me in the PRs for each one.

**Comment by wimnat** [comment]
@defionscode should these modules have PRs against ansible-modules-extras rather than core?

**Comment by juliedavila** [comment]
Yes

**Comment by wimnat** [comment]
@defionscode before I rebase, should I submit these new module PRs against core or extras?

**Comment by juliedavila** [comment]
To extras please

**Comment by wimnat** [comment]
All done.
https://github.com/ansible/ansible-modules-extras/pull/597
https://github.com/ansible/ansible-modules-extras/pull/598

**Pull request closed without merging**
