### PR TITLE
Added filename option to apt_repository module.

### PR DESCRIPTION
**Pull request by mattclay**
Resolves issue #14.

/cc @nitzmahone

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @mattclay. @sashka please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by robynbergeron** [comment]
@sashka This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by cloudnull** [comment]
:+1: this is a great change. Thank you @mattclay .

**Comment by bjoernt** [comment]
:+1:  from my side, waiting to get it merged

**Comment by spotzz** [comment]
Looks good to me too!

**Comment by odyssey4me** [comment]
Fantastic option which really helps when needing to clean up after yourself!

**Comment by sashka** [comment]
@robynbergeron: code looks OK.

**Pull request merged**
