### PR TITLE
route53_health_check: new module

### PR DESCRIPTION
**Pull request by zimbatm**
Complements #1257 by adding a module that manages the Route53 health checks.

The module is still having a couple of issues that I need to fix:
- [x] Make the `present` state idempotent
- [x] Add support for updating existing health-checks (boto doesn't implement the underlying API call)
- ~~[ ] Tagging~~ (not going to implement that as boto doesn't support it either)

### CODE REVIEW

**Comment by zimbatm** [comment]
Alright, this is stable now

**Comment by bennojoy** [comment]
@zimbatm looks good, just that empty alias[] is not required and when required: true default: null is not required

**Comment by zimbatm** [comment]
@bennojoy fixed

Do I also need a version_added on the whole module or something ?

**Comment by zimbatm** [comment]
Just added the `version_added: "2.0"` on the top-level

**Comment by bennojoy** [comment]
@zimbatm  yes please, Also as per current policies all new modules go into the module_extras repo first. let me check with team , since this was added a month ago. will udpate .. thanks

**Comment by zimbatm** [comment]
Ok keep me posted. Thanks for looking into this.

**Comment by gregdek** [comment]
Some new modules can go directly into core, but it's a much easier process if we go through extras; to be approved as a new module in core, the Ansible team must review it much more closely, and that takes longer.  

I would recommend resubmitting as an Extras module, where we have a community of AWS module maintainers who are very good about reviewing new modules in a timely manner.

**Comment by zimbatm** [comment]
Thanks

**Pull request closed without merging**
