### PR TITLE
ec2_vpc module: add support for route table propagation

### PR DESCRIPTION
**Pull request by bretmartin**
An important feature of AWS VPC routing is the ability to propagate BGP-advertised routes from the virtual gateway into routing tables. This allows for automatic routing of networks advertised by a customer to their VPC's virtual gateway, rather than explicit static routes in all their route tables. This adds a propagating_vgws parameter to allow propagation to be enabled using Ansible.

### CODE REVIEW

**Comment by juliedavila** [comment]
@bretmartin I'm going to ask for you to resubmit against the  proposed vpc route table module  once the VPC module has been split up. I want to keep this PR open for now as a reminder.

**Comment by gregdek** [comment]
@defionscode has the VPC module now been split up enough for @bretmartin to resubmit?

**Comment by juliedavila** [comment]
@gregdek and @bretmartin this should go to the `ec2_vpc_route_table` module, but has not been merged yet, it is here https://github.com/ansible/ansible-modules-extras/pull/597

**Comment by gregdek** [comment]
OK. I'm going to go ahead and close this one, since we know the old VPC module is going to be deprecated. 

@bretmartin thanks for your patience here.  Please wait for extras#597 to land, and then file this PR in extras against the new module.

**Pull request closed without merging**
