### PR TITLE
Fix and add more error handling for role policies

### PR DESCRIPTION
**Pull request by waky79**
In case role policy was deleted, we did not handle at all if there
was authorization issue to do the deletion. Also add message when
role is not found and the policy is skipped.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @waky79. @defionscode please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by waky79** [comment]
@defionscode any feedback?

**Comment by gregdek** [comment]
Thanks @waky79 for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

**Comment by juliedavila** [comment]
shipit

**Comment by waky79** [comment]
@gregdek can this be merged now?

**Comment by juliedavila** [comment]
Sorry for the delay.

**Pull request merged**
