### PR TITLE
Fix crontab argument order for writing

### PR DESCRIPTION
**Pull request by AMDmi3**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

cron module
##### ANSIBLE VERSION

```
ansible 2.0.2.0
  config file = /home/amdmi3/.ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

Currently, when writing user's crontab, ansible calls

```
crontab <file> -u <user>
```

This is incorrect according to crontab(1) on both FreeBSD and Linux,
which suggest that file argument should be the last.

At least on FreeBSD, this leads to incorrect cron module bahavior which
writes to root's crontab instead of users's

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @AMDmi3. To the current maintainers, @dsummersl, @EvanK please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by EvanK** [comment]
shipit

**Comment by gregdek** [comment]
Thanks again to @AMDmi3 for this PR, and thanks @dsummersl, @EvanK for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gtrafimenkov** [comment]
This change reverts https://github.com/ansible/ansible-modules-core/commit/7a0b4882449f1c9730425f0055f9a1e664e7d13b

I guess check of `platform.system()` is required.

**Comment by AMDmi3** [comment]
See #2807 (summary: 7a0b488 was probably bogus, crontab always works with `-u <user> <file>`, including busybox).

**Pull request merged**
