### PR TITLE
Improve EC2 ELB lookup filtering

### PR DESCRIPTION
**Pull request by tpounds**
This improves the get_all_load_balancers lookup if an optional list of ELB names is specified. The original lookup can be costly if the associated AWS account contains hundreds of ELBs.

### CODE REVIEW

**Comment by gregdek** [comment]
@tpounds looks like we never pinged the maintainer of this module -- sorry about that!

@jarv Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by wimnat** [comment]
I'd prefer to see a new ec2_elb_facts module that follows a similar pattern to other facts modules with a filter parameter.  For example, http://docs.ansible.com/ansible/ec2_eni_facts_module.html

**Comment by gregdek** [comment]
Thanks @tpounds for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

**Comment by tpounds** [comment]
@gregdek, Thanks for the poke. I've rebased the pull request against latest devel branch. It is ready_for_review.

**Comment by wimnat** [comment]
@tpounds any thoughts on the _facts module?

**Comment by gregdek** [comment]
Thanks @tpounds. @jarv please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
Thanks @tpounds. @jarv please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by tpounds** [comment]
@wimnat I think adding this to an "ec2_asg_facts" module makes sense too. It could return all of the load balancers associated with the auto scaling group in a variable (e.g. ec2_asg_elbs).

**Comment by gregdek** [comment]
Kicking this one to get it moving again.

**Comment by gregdek** [comment]
Thanks @tpounds. To the current maintainers, @jarv please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
