### PR TITLE
add support for auth_socket

### LINKED ISSUE #3003: Add plugin as parameter for mysql_user
##### Issue Type:

Feature Idea
##### Ansible Version:

```
$ ansible --version
ansible 2.0.0.0
  config file = 
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

Default configuration.
##### Environment:

N/A
##### Summary:

From the MySQL 5.7 what's new page:

> The server now requires account rows in the mysql.user table to have a nonempty plugin column value and disables accounts with an empty value.

On a fresh installation of MySQL 5.7 the `root` user for host `localhost` is now configured with a plugin value of `auth_socket`. This prevents users other then root to connect as root using the `mysql` client utility:

```
user@server$ mysql -u root -pP4ssw0rd -h localhost
ERROR 1698 (28000): Access denied for user 'root'@'localhost'
```

While as root this works:

```
root@server# mysql -u root -pP4ssw0rd -h localhost
```

Currently I can't change this configuration with Ansible.
##### Steps To Reproduce:

It would be nice to introduce a new parameter to this module which accepts all possible plugin values (defaulting to mysql_native_password) , e.g.:

``` yaml
mysql_user: name=root password=abc123 plugin=mysql_native_password
mysql_user: name=root password=abc123 plugin=auth_socket
```
##### Expected Results:

N/A
##### Actual Results:

N/A

### PR DESCRIPTION
**Pull request by verwilst**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

database/mysql/mysql_user
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel c42501cfe7) last updated 2016/05/03 09:13:13 (GMT +000)
  lib/ansible/modules/core: (detached HEAD b6ad3b6773) last updated 2016/05/02 14:18:29 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD 1846de2809) last updated 2016/05/02 14:18:33 (GMT +000)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

Add support for plugins ( auth_socket ) for authentication in MySQL. Fixes #3003

```
root@ansible:/tmp# ansible debian8 -m mysql_user -a "user=bob plugin=auth_socket" --forks 1
debian8 | SUCCESS => {
    "changed": true, 
    "user": "bob"
}
root@ansible:/tmp# ansible debian8 -m mysql_user -a "user=bob plugin=auth_socket" --forks 1
debian8 | SUCCESS => {
    "changed": false, 
    "user": "bob"
}

mysql> select User,Host,plugin from user where User like 'bob';
+------+-----------+-------------+
| User | Host      | plugin      |
+------+-----------+-------------+
| bob  | localhost | auth_socket |
+------+-----------+-------------+
1 row in set (0.00 sec)

```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @verwilst. All backport requests must be reviewed by the core team, and this can take time. We appreciate your patience. 

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @verwilst for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by verwilst** [comment]
ready_for_review

**Comment by damienwebdev** [comment]
Looks like this is still failing due to some python syntax. @verwilst Do you want me to clean up your syntax here?

**Pull request closed without merging**
