### PR TITLE
Make is so that the params param truly isn't required (fix for #3860)

### PR DESCRIPTION
**Pull request by washingtoneg**
This change provides a fix for #3860 (complete bug report provided in the issue) as well as the bug reported in #1340, and adds support in `cloud/amazon/rds_param_group.py` to allow for the creation of RDS parameter groups when the `params` option is null (as originally intended).

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @washingtoneg. To the current maintainers, @tastychutney, @scottanderson42 please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by scottanderson42** [comment]
shipit

**Comment by gregdek** [comment]
Thanks again to @washingtoneg for this PR, and thanks @tastychutney, @scottanderson42 for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by washingtoneg** [comment]
Hey @scottanderson42, is there any reason this hasn't been merged in yet? Just curious. Ultimately, I'm just trying to get https://github.com/ansible/ansible-modules-core/issues/3860 closed so @ansibot will stop pinging me. :)

Thanks!

**Comment by scottanderson42** [comment]
@washingtoneg I don't have merge permissions, sorry. :-) Nothing I can do.

**Pull request merged**
