### PR TITLE
added user_data_json to deliver valid json onto aws ec2 user_data

### PR DESCRIPTION
**Pull request by raben2**
ansible was automatically escaping double quotes on user_data strings.
Now you can put valid json into user_data for post processing.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @raben2. @garethr please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by raben2** [comment]
ship_it

**Comment by gregdek** [comment]
Thanks @raben2 for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

**Comment by gregdek** [comment]
Hi @raben -- this needs rebasing. Can you please rebase? When you've done so, please enter a comment with "ready_for_review" and we'll put it back into community review. 

If no response in two weeks, we'll close this PR.

**Comment by raben2** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @raben2 for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by sivel** [comment]
It appears as though this PR needs to be rebased against the current state of devel.  At the moment, this PR is showing that there are 561 commits to be merged.

needs_rebase

**Comment by gregdek** [comment]
Thanks @raben2 for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @raben2 for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@raben2 A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by raben2** [comment]
ready_for_review

**Comment by bcoca** [comment]
looks like a bad merge, rebase please

**Pull request closed without merging**
