### PR TITLE
Refactor domain/project handling on os_user module

### PR DESCRIPTION
**Pull request by rcarrillocruz**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

os_user
##### ANSIBLE VERSION

```
ansible 2.3.0 (devel 03765ba65e) last updated 2016/10/10 09:43:51 (GMT +000)
  lib/ansible/modules/core: (fix_os_user_idempotency_changed_status ba4533d0d4) last updated 2016/10/10 13:34:53 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD 734aa8f8e9) last updated 2016/10/10 09:44:04 (GMT +000)
  config file = 
  configured module search path = Default w/o overrides
```
##### SUMMARY

The keys returned by user objects for default domain and
default project are respectively default_domain_id and
default_project_id.
We need to gather those IDs in case the user passed names, so we
can then compare with the user object on the needs_update helper
function.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks again to @rcarrillocruz. This module is going into community review.

We notice that you are one of the maintainers (@emonty, @shrews, @juliakreger, @j2sol, @rcarrillocruz) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by omgjlk** [comment]
This code looks solid. I'm going to test it, and then test my PR on top of it.

**Review by omgjlk — COMMENTED** [review]
Testing works.

However, I feel that you're grabbing an operator cloud numerous times, both before checking for update and during checking for update. Seems like we could create the opcloud object once, fetch domain_id, default_project_id if either are supplied, and then use those during the update check instead of fetching that information a second time.

The _needs_update function, instead of just being passed in the module object, could be passed in a dict of the actual values we're going to check against, where domain/project has already been sorted out.

Does that make sense?

**Comment by rcarrillocruz** [comment]
Yeah, let me push a new patch, thanks.

**Review by omgjlk — APPROVED** [review]
Looks better, thanks!

**Comment by omgjlk** [comment]
shipit

**Comment by gregdek** [comment]
Thanks again to @rcarrillocruz for this PR, and thanks @emonty, @shrews, @juliakreger, @j2sol, @rcarrillocruz for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request merged**
