### PR TITLE
Update win_get_url.ps1

### PR DESCRIPTION
**Pull request by Plork**
fixed wrong variable naming

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @Plork. @angstwad please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by jhawkesworth** [comment]
See https://github.com/ansible/ansible-modules-core/issues/2146
In the comments for above ticket there is a version that avoids actually downloading the entire file (provided the web server tells the truth about last write time (which in my experience nginx does)).

**Comment by jhawkesworth** [comment]
Hi, been catching up with PRs and I think https://github.com/ansible/ansible-modules-core/pull/2644 is addressing the same problem but is closer to being able to be merged so I think this needs_revision right now.

**Comment by robynbergeron** [comment]
@angstwad This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
@angstwad still waiting on your review.  Please comment with text 'shipit' or 'needs_revision' as appropriate. If we don't hear from you within 14 days, we will start to look for additional maintainers for this module.

**Comment by nitzmahone** [comment]
Already addressed in another PR- thanks!

**Pull request closed without merging**
