### PR TITLE
Add the keyid_ppa argument for removing ppa-repo key

### PR DESCRIPTION
**Pull request by evverx**
**Issue Type:**
Feature Pull Request

**Ansible Version:**
 `ansible 2.0.0 (devel 37e38924de) last updated 2015/08/05 18:33:07 (GMT +000)`

**Environment**:

> Description:  Ubuntu 14.04.3 LTS
> Release:    14.04

**Summary:**
Add the `keyid_ppa` argument for removing ppa-repo key.
Similar to Saltstack's [keyid_ppa](http://docs.saltstack.com/en/develop/ref/states/all/salt.states.pkgrepo.html#salt.states.pkgrepo.absent):

> keyid_ppa : False
> If set to True, the GPG key's ID will be looked up from ppa.launchpad.net and removed, and the keyid argument will be ignored.

With `keyid_ppa=no` (default):

``` bash
# add ppa, add key
$ ansible all -m apt_repository -a 'repo=ppa:saltstack/salt state=present' --sudo
127.0.0.1 | SUCCESS => {
    "changed": true,
    "repo": "ppa:saltstack/salt",
    "state": "present"
}

# remove ppa
$ ansible all -m apt_repository -a 'repo=ppa:saltstack/salt state=absent' --sudo
127.0.0.1 | SUCCESS => {
    "changed": true,
    "repo": "ppa:saltstack/salt",
    "state": "absent"
}

# key is here
$ apt-key export 0E27C0A6
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v1
....
```

With `keyid_ppa=yes`:

``` bash
$ ansible all -m apt_repository -a 'repo=ppa:saltstack/salt state=present' --sudo
$ ansible all -m apt_repository -a 'repo=ppa:saltstack/salt state=absent keyid_ppa=yes' --sudo
$ apt-key export 0E27C0A6
gpg: WARNING: nothing exported
```

### CODE REVIEW

**Comment by gregdek** [comment]
@sashka Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by sashka** [comment]
@gregdek Sorry, I'm extremely busy these days, so I can't go on with this code review now. I'm terribly sorry.

**Comment by gregdek** [comment]
@evverx A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes.

**Comment by gregdek** [comment]
@evverx Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If we don't hear from you within another 14 days, we will close this pull request.

**Comment by robynbergeron** [comment]
@evverx A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes.

**Pull request closed without merging**
