### PR TITLE
#362: support --master-data=

### PR DESCRIPTION
**Pull request by ecv**
Supports inline replication-master info; avoid bin_log + position fuss.

### CODE REVIEW

**Comment by gregdek** [comment]
Hi @ecv. Thanks for submitting this pull request. Please accept our apologies for taking so long to review it.

Unfortunately, due to this delay, it appears that the underlying code has changed, and this PR needs to be rebased. If you believe that this PR still applies, please rebase and we will then put it into our (new, faster) community review process as soon as possible.  Again, apologies for the delay and the extra work.

**Comment by gregdek** [comment]
@ecv A friendly reminder: this pull request has been marked as needing your action, and it hasn't been updated in the last month. 

If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we'll keep it open pending your changes.

If we receive no indication from you within a week, we will close this pull request.

**Comment by gregdek** [comment]
Closing due to inactivity.

**Comment by ecv** [comment]
Totally useless. Amazing. You guys. Hats off.

**Comment by ecv** [comment]
I do all the work for you, and then you close my patch because you took too long to merge it and wanted me to do more work. Spectacular. Nice job. 

I admin postgres these days anyway, so don't care if you support this.

**Pull request closed without merging**
