### PR TITLE
Cloud Modules STS Support Redux

### PR DESCRIPTION
**Pull request by semifocused**
Add support for AWS Security Token Service (temporary credentials) to all AWS cloud modules.

Rationalize sources and ordering of security credentials for consistency across modules.

Update documentation to use shared doc fragment and consistent usage information across modules.

### CODE REVIEW

**Comment by volkhin** [comment]
Hi. Got into same issue with route53 (https://github.com/ansible/ansible/issues/10533) and looks like this fix my problem. Any idea how soon can we get it merged?

**Comment by bcoca** [comment]
this needs a rebase first

**Comment by volkhin** [comment]
It got stuck for 3 months. If rebase is the only stopper I can help with that.

**Comment by semifocused** [comment]
Go for it volkhin, or LMK and I can take that on later tonight...

**Comment by volkhin** [comment]
@semifocused great! Yeah, if you have time for it, please.

**Comment by haraldsk** [comment]
It would be awesome if this could be merged. We're running our own fork because of this.

**Comment by semifocused** [comment]
OK @bcoca @haraldsk @volkhin I have taken a swing at the rebase and have done my best to reconcile correctly with 3 months of activity, but this could use some QA from each of you.  Please pull and LMK if you see any issues.

@bcoca - also bear in mind that this PR goes hand in hand with https://github.com/ansible/ansible/pull/9894, they will need to be integrated simultaneously.

Finally, can I make a plug for closing https://github.com/ansible/ansible-modules-core/pull/569 at the same time - we're currrently still forked because this retry issue remains open.

Thx and please provide feedback.
- Mick

**Comment by smiller171** [comment]
@bcoca am I correct that this made it into Ansible 2.0? If so, should be able to close #1699

**Pull request merged**
