### PR TITLE
Added better region handling and enabled eu-central-1

### PR DESCRIPTION
**Pull request by willthames**
Make use of improved connect_to_aws that throws an exception
if a region can't be connected to (e.g. eu-central-1 requires
boto 2.34 onwards)

Add eu-central-1 to the two modules that hardcode their regions

This pull request makes use of the changes in ansible/ansible#9419

### CODE REVIEW

**Comment by jjshoe** [comment]
@willthames - You've got merge conflicts :\

**Comment by simao** [comment]
Any chance we get this soon? Thanks!

**Comment by willthames** [comment]
@jjshoe - module conflicts resolved, thanks for the notification.

**Comment by bcoca** [comment]
so 2 things, 1 i would separate the regions from the error handling, 2 I would change the modules that still use their own region list to use the common one in ansible.module_utils.ec2 and do any pertinent modifications there.

**Comment by willthames** [comment]
@bcoca, I state quite clearly why the error handling is needed for the region changing - because if not, anyone using an older version of boto with the new region will have their code fail in a nasty way. 

I think the two remaining modules wouldn't benefit that much from the common code. Either way, I'd recommend separating _that_ change from this one.

**Comment by willthames** [comment]
@bcoca, it's worth taking a look at the related change  ansible/ansible#9419 where I mention the remaining two modules.

**Pull request merged**
