### PR TITLE
Win async

### PR DESCRIPTION
**Pull request by nitzmahone**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

async_wrapper.ps1
async_status.ps1
##### SUMMARY

adds module support for Windows async_wrapper/async_status

### CODE REVIEW

**Comment by nitzmahone** [comment]
cc @mattclay

**Comment by mattclay** [comment]
@nitzmahone Tests on Travis are failing due to lack of a Python documentation file for the async_status module.

**Comment by gregdek** [comment]
Thanks @nitzmahone for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by nitzmahone** [comment]
Hrm, wonder what we need to do about that. This is one of those weird ones like setup where the powershell and python are the same (sans extension)- it doesn't gripe about setup.ps1, but I don't see an exclusion anywhere obvious.

**Comment by mattclay** [comment]
Looks good.

**Pull request merged**
