### PR TITLE
Update async_wrapper.py to remove own temp dir.

### PR DESCRIPTION
**Pull request by mattclay**
##### ISSUE TYPE

Bugfix Pull Request

##### COMPONENT NAME

async_wrapper.py

##### ANSIBLE VERSION

```
ansible 2.3.0 (devel d90638ad40) last updated 2016/11/21 16:18:31 (GMT -700)
  lib/ansible/modules/core: (detached HEAD 5c986306be) last updated 2016/11/23 22:40:42 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD 9511de1e3d) last updated 2016/11/23 22:40:42 (GMT -700)
  config file = 
  configured module search path = Default w/o overrides
```

##### SUMMARY

Update async_wrapper.py to remove its own temporary directory. This prevents async race conditions where the controller removes the temporary directory before the module has been executed.

### CODE REVIEW

**Comment by mattclay** [comment]
The `async` action should be updated to pass an additional argument to `async_wrapper` that indicates if the temporary directory should be removed. This would be used to maintain existing behavior for preserving temporary directories. Doing so will also require a small update to `async_wrapper`.

**Comment by mattclay** [comment]
Added temp preservation support. The `async` action already passes `-preserve_tmp` as needed.

**Comment by gregdek** [comment]
Thanks @mattclay for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Review by nitzmahone — APPROVED** [review]
LGTM

**Pull request merged**
