### PR TITLE
Ability to specify new SSD EBS option

### PR DESCRIPTION
**Pull request by philm**
AWS [rolled out general purpose SSD volumes](http://aws.amazon.com/blogs/aws/new-ssd-backed-elastic-block-storage/) in June 2014 as the default storage volume type for EBS. This PR keeps the previous default ("standard" magnetic drives) but it also exposes volume_type as an option, allowing the selection of the SSD (i.e. "gp2") volume type.

### CODE REVIEW

**Comment by dragon3** [comment]
This PR is almost the same as ansible/ansible#8028
I want it. :+1:

**Comment by dowens** [comment]
This is a needed enhancement. I prefer the error feedback in ansible/ansible#8028 when selecting provisioned iops together with gp2 rather than the silent default to use iops.

**Comment by sampierson** [comment]
We have tested this code (we use it every day) and it works great.
Using volume_type gp2 in this play (which has been simplified):

```
 - name: Create EBS volume
   sudo: false
   local_action:
     module: ec2_vol
     volume_type: "gp2"
     device_name: "/dev/sdp"
     encrypted: "yes"
     instance: "{{ ansible_ec2_instance_id }}"
     volume_size: "50"
     region: "{{ ec2_region }}"
     state: present
```

Here is the output when a new volume is created:

```
 ok: [restore-test.omadahealth.net -> 127.0.0.1] => (item={'encrypted': True, 'size_gb': 50,
 'mount_point': '/var/lib/postgresql', 'device_letter': 'p', 'volume_type': 'gp2'}) =>
 {"changed": false, "device": "/dev/sdp", "item": {"device_letter": "p", "encrypted": true,
 "mount_point": "/var/lib/postgresql", "size_gb": 50, "volume_type": "gp2"},
 "volume_id": "vol-abcd1234", "volume_type": "gp2"}
```

**Comment by mtpereira** [comment]
I've just hit on this issue as well. :+1:

**Comment by charlesmims** [comment]
I'm also using this.  Works fine.

**Comment by Jonnymcc** [comment]
+1 would like this feature.

**Comment by jrhe** [comment]
+1

**Comment by jassinm** [comment]
I would really need this feature. Thanks for merging

**Comment by bcoca** [comment]
# Rebase Request

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us. 

It looks like the code underneath has changed since this was submitted.  Can you take care of rebasing this for us?
- You should be able to run "git rebase" against this branch to bring it up to date
- Resolve any merge conflicts and test changes
- Push to the same branch and github should update the pull request automatically.

Just as a quick reminder of things, this is a really busy project.  We have over 800 contributors and to manage the queue effectively
we assign things a priority between P1 (highest) and P5.  We'd like to thank you very much for your time!  
We'll work things in priority order, so just wanted you to be aware of the queue and know we haven't forgotten about you!

We will definitely see your comments on this issue when reading this ticket, but may not be able to reply promptly.  You may also wish to join one of our two mailing lists
which are very active:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Thank you once again for this and your interest in Ansible!

**Comment by philm** [comment]
@bcoca, rebased.

**Comment by kalefranz** [comment]
I've reviewed this pull request, along with #166. To me, they appear to serve the same functional purpose. #3 better conforms to ansible conventions.

+1 for merging!

**Comment by wgregorian** [comment]
+1 please merge we kinda needs this to be operationally effective.

**Pull request merged**
