### PR TITLE
update quantum modules for non-admin users

### PR DESCRIPTION
**Pull request by bregman-arie**
Not every tenant allowed to use tenant-list
which may result in long wait time and an
failure at the end.

This change allows regular user to run the
module without waiting for timeout because
of using tenant-list.

It also support insecure connections in case
resolving SSL certificate not working.

### CODE REVIEW

**Comment by robynbergeron** [comment]
Hi, @bregman-arie -- thanks for the PR.

**Comment by robynbergeron** [comment]
Greetings, lovely openstack smart folks, @emonty @shrews @dguerri @juliakreger @j2sol @rcarrillocruz -- 

Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

Thanks!

**Comment by omgjlk** [comment]
This adds new options to these modules, but does not update the documentation for them. Is this the intention, to add a hidden option?

Also this PR is against `stable-1.9`, and the change isn't on master yet.

Otherwise, this looks okay.

**Comment by gregdek** [comment]
I think our practice here is to put new PRs into devel, and then the Ansible team makes the decision to backport as needed. So seems like, at the very least, we should be seeing this PR against devel first -- since it would still apply there, right? Pinging @ansible/core for confirmation.

**Comment by bregman-arie** [comment]
Hmm so what I need to do? =)

**Comment by Shrews** [comment]
@gregdek It's worth pointing out that all of these modules are deprecated in 2.0. Not sure what your policy is on that.

**Comment by bregman-arie** [comment]
FYI I'm aware those deprecated in Ansible 2.0
But atm we are using ansible 1.9.x

**Comment by gregdek** [comment]
Thanks @bregman-arie. All backport requests must be reviewed by the core team, and this can take time. We appreciate your patience.

**Pull request closed without merging**
