### PR TITLE
Update mount.py documentation

### PR DESCRIPTION
**Pull request by asolano**
##### ISSUE TYPE

Docs Pull Request
##### COMPONENT NAME

mount.py
##### ANSIBLE VERSION

N/A
##### SUMMARY

Use full YAML syntax in the examples.

### CODE REVIEW

**Review by robinro — APPROVED** [review]
LGTM

**Comment by gregdek** [comment]
Thanks @asolano. To the current maintainers, @grossws please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @asolano for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by asolano** [comment]
Unneeded, HEAD version is fine.

**Pull request closed without merging**
