### PR TITLE
Mysql vars port definition

### PR DESCRIPTION
**Pull request by acaveroc**
Add "login_port" variable to allow connection to a port other than default MySQL installations

### CODE REVIEW

**Comment by bennojoy** [comment]
@acaveroc  can you please add version_added  to the new paramter and also we can specifty the type of the parameter in argument spec so that we dont have to cast it .
login_port=dict(default="3306",type='int')

**Comment by acaveroc** [comment]
@bennojoy I've just added this modifications, thank you for your advice

**Comment by gregdek** [comment]
@banyek Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please give it a +1; at that point, we will add the “priority_reviewed” flag to this PR, which will move it to the top of our queue for potential inclusion.

**Comment by banyek** [comment]
LGTM
+1

**Comment by gregdek** [comment]
Thanks @banyek. Promoting to priority_reviewed.

**Pull request merged**
