### PR TITLE
apt_key: fix spurious failure to import a subkey

### LINKED ISSUE #4365: apt_key always fails to import a subkey
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

apt_key
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```
##### OS / ENVIRONMENT

host OS: Ubuntu 14.04
controlled nodes' OS: Ubuntu 14.04
##### SUMMARY

Importing a (sign only) subkey with apt_key always fails, however the actual keyring gets created and contains the correct (sub)key.
##### STEPS TO REPRODUCE

```
 $ cat >> aptrepo.yml <<EOF
    ---

    - hosts: all
      become: True
      tasks:
        - name: import custom repo keyring
          apt_key: >
            id=A254F5F0
            keyserver=keyserver.ubuntu.com
 EOF

$ ansible-playbook aptrepo.yml

```

##### EXPECTED RESULTS

The specified (sub)key gets successfuly imported, ansible returns exit code 0 (success)
##### ACTUAL RESULTS

```
   fatal: [saceph-osd2.maas]: FAILED! => {"changed": false, "failed": true, "id": "A254F5F0", "msg": "key does not seem to have been added"}
   fatal: [saceph-osd1.maas]: FAILED! => {"changed": false, "failed": true, "id": "A254F5F0", "msg": "key does not seem to have been added"}
   fatal: [saceph-osd3.maas]: FAILED! => {"changed": false, "failed": true, "id": "A254F5F0", "msg": "key does not seem to have been added"}

However the key has been successfully imported:

$ ansible all -m shell -a 'apt-key --keyring /etc/apt/trusted.gpg.d/ceph.gpg adv --list-public-keys | grep -e A254F5F0'

    saceph-osd2.maas | SUCCESS | rc=0 >>
    sub   4096R/A254F5F0 2016-07-29 [expires: 2026-07-27]

    saceph-osd1.maas | SUCCESS | rc=0 >>
    sub   4096R/A254F5F0 2016-07-29 [expires: 2026-07-27]

    saceph-osd3.maas | SUCCESS | rc=0 >>
    sub   4096R/A254F5F0 2016-07-29 [expires: 2026-07-27]

```

### PR DESCRIPTION
**Pull request by asheplyakov**
##### ISSUE TYPE

- Bugfix Pull Request
##### COMPONENT NAME

packaging/os/apt_keys
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```
##### SUMMARY

```

```

Importing a (sign only) subkey with apt_key module always fails,
however the actual keyring gets created and contains the correct keys.
Apparently the all_keys function skips the subkeys, hence the problem.

Fixes #4365

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @asheplyakov for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by asheplyakov** [comment]
@gregdek: The failure was caused by mysql module (except stanza incompatible with python 3.x). That problem has been fixed recently. I've rebased my patch, and CI seems to be happy about it now.

**Comment by gregdek** [comment]
Thanks @asheplyakov. Kicking this PR.

**Comment by gregdek** [comment]
Thanks @asheplyakov. To the current maintainers, @jvantuyl please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by jvantuyl** [comment]
shipit

**Comment by gregdek** [comment]
Thanks again to @asheplyakov for this PR, and thanks @jvantuyl for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request merged**
