### PR TITLE
Adds alias record support to route53 (migrated from https://github.com/ansible/ansible/pull/8974)

### PR DESCRIPTION
**Pull request by jmound**
...new module repo layout. The actual code changes are copied from https://github.com/tepwil/ansible/commit/260ab8
- I saw the [PR](https://github.com/ansible/ansible/pull/8974) in ansible, and mpdehaan's comment, and thought I'd do the work to get the changes over in to the core modules.
- I forked tepwil's fork, made the change, committed it to my fork, and put that in this pull request.

```
 cp ansible-tepwil/ansible/library/cloud/ec2_elb_lb mindelini-ansible-core/ansible-modules-core/cloud/ec2_elb_lb.py 
  cp ansible-tepwil/ansible/library/cloud/route53 mindelini-ansible-core/ansible-modules-core/cloud/route53.py
```

### CODE REVIEW

**Comment by jmound** [comment]
I thought a more descriptive title might make it easier on the project admins.

**Comment by jwerak** [comment]
Hi, 

I have troubles to delete alias A record to load balancer dns record when using this version of route63. 
The DNS record of load balancer to which A record is pointing does not exists (might be what was not tested...?)

**EDIT**
not the cause, just tested it even with existing ELB record and result is the same.

I am getting ansible error:

```
failed: [local] => {"failed": true}
msg: Tried to delete resource record set [name='<record>', type='A'] but the values provided do not match the current values
```

I have no issues when deleting records manually via route53 web.

Here are my ansible tasks.
- name: "Get DNS record for {{ app_dns }}"
  route53: >
    command=get
    zone={{ aws_route53.zone_name }}
    record={{ app_dns }}
    type=A
  register: actual_dns_rec
- name: "Delete DNS record for {{ app_dns }}"
  route53: >
    command=delete
    zone={{ actual_dns_rec.set.zone }}
    record={{ actual_dns_rec.set.record }}
    type={{ actual_dns_rec.set.type }}
    value={{ actual_dns_rec.set.value }}
  when: marathon_apps[app_name].createdns | bool

**EDIT2**
btw I wouldn't need to use it, but unfortunately option overwrite doesn't work for me either. 
Is it known issue?

**Comment by thekindofme** [comment]
Waiting for this to get merged. Anyway I can help speed things up?

Cheers

**Comment by bcoca** [comment]
# Rebase Request

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us. 

It looks like the code underneath has changed since this was submitted.  Can you take care of rebasing this for us?
- You should be able to run "git rebase" against this branch to bring it up to date
- Resolve any merge conflicts and test changes
- Push to the same branch and github should update the pull request automatically.

Just as a quick reminder of things, this is a really busy project.  We have over 800 contributors and to manage the queue effectively
we assign things a priority between P1 (highest) and P5.  We'd like to thank you very much for your time!  
We'll work things in priority order, so just wanted you to be aware of the queue and know we haven't forgotten about you!

We will definitely see your comments on this issue when reading this ticket, but may not be able to reply promptly.  You may also wish to join one of our two mailing lists
which are very active:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Thank you once again for this and your interest in Ansible!

**Comment by thekindofme** [comment]
Thank you for the reply. Will take a crack at it.

Cheers!

**Comment by jimbydamonk** [comment]
I am planning on updating an old pull request https://github.com/ansible/ansible/pull/7116
with this as well. @jmound, this needs to be rebased. 
I can incorporate your changes and create a new PR or I can wait till you rebase and it gets merged.
Thoughts?

**Comment by jmound** [comment]
As I mentioned at the top, the code isn't even written by me. [This](https://github.com/tepwil/ansible/commit/260ab8) is the original. I saw a pull request on ansible/ansible [here](https://github.com/ansible/ansible/pull/8974) and thought I could help by putting it into a pull request over here.
As far as I am concerned, feel free to do whatever it takes to get that code merged in.

**Comment by saden1** [comment]
Any status update on this issue?

**Comment by Coderah** [comment]
as is referenced above https://github.com/ansible/ansible-modules-core/pull/758 I've created the needed changes to the latest devel branch (rebase). Was in need of this feature and already had a fork going it'd be great to get it merged in for future folks ease of use.

**Comment by jimsmith** [comment]
+1 for this.
I'm found that I hit a wall for the apex zone and have to manually go into route53 web console and change it to Alias.

Does this also include Routing Policy as well ?

**Comment by Coderah** [comment]
@jimsmith #758 got merged which is effectively the same thing.

Only answer I can give to your second question is that this adds support specifically for Alias and nothing else.

**Comment by juliedavila** [comment]
This should be closed. Fixed by https://github.com/ansible/ansible-modules-core/pull/758

**Comment by bcoca** [comment]
closed per #758 as mentioned above

**Pull request closed without merging**
