### PR TITLE
OpenStack keystone_user, make tenant deletion to work

### PR DESCRIPTION
**Pull request by toddnni**

### CODE REVIEW

**Comment by emonty** [comment]
This seems like a fine patch to land in general - could you please rebase it to be current?

**Comment by omgjlk** [comment]
This module is getting replaced in https://github.com/ansible/ansible-modules-core/pull/1598 so lets make sure we have the functionality there instead of adding it here.

**Comment by omgjlk** [comment]
Well, specifically the project/tenant stuff is in https://github.com/ansible/ansible-modules-core/pull/1597

**Comment by gregdek** [comment]
Closing this PR as obsolete in favor of #1597 per @j2sol.

**Pull request closed without merging**
