### PR TITLE
os_server: Add some error checking for the 'nics' parameter

### PR DESCRIPTION
**Pull request by ghost**
If this parameter was not of the right type, the module would fail with a
traceback, with a "AttributeError: 'str' object has no attribute 'get'"
exception.

It now gives a proper error message on type errors.

### CODE REVIEW

**Comment by gregdek** [comment]
@emonty Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please give it a +1; at that point, we will add the “priority_reviewed” flag to this PR, which will move it to the top of our queue for potential inclusion.

**Comment by gregdek** [comment]
ping @emonty and friends

**Comment by gregdek** [comment]
Thanks @ssssam for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

**Comment by ghost** [comment]
Done, sorry for the delay

**Comment by ghost** [comment]
ready_for_review

**Comment by emonty** [comment]
shipit

**Pull request merged**
