### PR TITLE
Metadata for core modules

### PR DESCRIPTION
**Pull request by abadger**
##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME
metadata for all modules

##### ANSIBLE VERSION

```
devel
```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @abadger for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@abadger A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by abadger** [comment]
Refreshed the metadata with the latest list of modules, support-owner, and status.

The following module was not listed in the list and therefore received the default metadata:
```
'/srv/ansible/vanilla/lib/ansible/modules/core/utilities/logic/async_wrapper.py',
```

This is async_wrapper which is not a standard module.  It's okay that it did not receive metadata in this iteration.

The following modules did not have support-ownership listed in the file and so had the default of community assigned:
```
Module _ec2_ami_search has no supported_by field.  Using community
Module _docker has no supported_by field.  Using community
Module _glance_image has no supported_by field.  Using community
Module _keystone_user has no supported_by field.  Using community
Module _nova_compute has no supported_by field.  Using community
Module _nova_keypair has no supported_by field.  Using community
Module _quantum_floating_ip has no supported_by field.  Using community
Module _quantum_floating_ip_associate has no supported_by field.  Using community
Module _quantum_network has no supported_by field.  Using community
Module _quantum_router has no supported_by field.  Using community
Module _quantum_router_gateway has no supported_by field.  Using community
Module _quantum_router_interface has no supported_by field.  Using community
Module _quantum_subnet has no supported_by field.  Using community
Module vsphere_guest has no supported_by field.  Using community
Module replace has no supported_by field.  Using community
Module _eos_template has no supported_by field.  Using community
Module _ios_template has no supported_by field.  Using community
Module _iosxr_template has no supported_by field.  Using community
Module _iosxr_template has no supported_by field.  Using community
Module _junos_template has no supported_by field.  Using community
Module _junos_template has no supported_by field.  Using community
Module _nxos_template has no supported_by field.  Using community
Module _ops_template has no supported_by field.  Using community
Module _ops_template has no supported_by field.  Using community
Module _accelerate has no supported_by field.  Using community
Module _fireball has no supported_by field.  Using community
```
Those modules are all deprecated so I'm not especially bothered by them having no owner but core team should think about whether they want to remove ownership from their modules when a module is deprecated or when it is removed.

**Comment by abadger** [comment]
Merged to devel

**Pull request merged**
