### PR TITLE
Added new instance sizes

### PR DESCRIPTION
**Pull request by smereczynski**
Added new instance sizes (Premium Storage) and case-related documentation clarification.

### CODE REVIEW

**Comment by dirtyharrycallahan** [comment]
Could you update the title to something other than "devel?"

**Comment by smereczynski** [comment]
Sorry - PyCahrm did that and I have not noticed.

**Comment by gregdek** [comment]
@jwhitbeck please review; if you approve, give it a +1 and we will flag as "P1_reviewed" for faster inclusion.

**Comment by jwhitbeck** [comment]
+1

**Comment by gregdek** [comment]
Thanks @jwhitbeck!

**Comment by abadger** [comment]
Thanks @smereczynski !Thanks @jwhitbeck !

# Merged

Hi!

This has been merged in, and will also be included in the next major release.

If you or anyone else has any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Pull request merged**
