### PR TITLE
Add OpenStack Volume module

### PR DESCRIPTION
**Pull request by emonty**

### CODE REVIEW

**Comment by ibratoev** [comment]
I have an issue with this module. I am trying to use it without defining clouds in a config file or in env_vars. So I have something like that:

``` yaml
      x_os_volume:
        state: present
        auth:
          username: "{{ openstack_login_username }}"
          password: "{{ openstack_login_password }}"
          auth_url: "{{ openstack_auth_url }}"
          project_name: "{{ openstack_tenant_name }}"
        size: 80
        ...
```

This fails with the following stack trace:

```
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1431343781.42-98259549774465/x_os_server_volume", line 1974, in <module>
    main()
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1431343781.42-98259549774465/x_os_server_volume", line 255, in main
    module.params['volume_name'])
  File "/usr/local/lib/python2.7/dist-packages/shade/__init__.py", line 1383, in get_volume_id
    volume = self.get_volume(name_or_id)
  File "/usr/local/lib/python2.7/dist-packages/shade/__init__.py", line 918, in get_volume
    return self._get_entity(self.search_volumes, name_or_id, filters)
  File "/usr/local/lib/python2.7/dist-packages/shade/__init__.py", line 840, in _get_entity
    entities = func(name_or_id, filters)
  File "/usr/local/lib/python2.7/dist-packages/shade/__init__.py", line 861, in search_volumes
    volumes = self.list_volumes()
  File "/usr/local/lib/python2.7/dist-packages/shade/__init__.py", line 148, in _cache_decorator
    return the_method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/dogpile/cache/region.py", line 1032, in decorate
    key = key_generator(*arg, **kw)
  File "/usr/local/lib/python2.7/dist-packages/shade/__init__.py", line 307, in generate_key
    [name_key, fname, arg_key, kwargs_key])
TypeError: sequence item 0: expected string, NoneType found
```

Looking into the code, I found a workaround: setting **cloud** to **openstack**. I traced the issue to the get_one_cloud func here: https://github.com/openstack/os-client-config/blob/df6c73f1f1b1e703f1526d813759638320ee17e6/os_client_config/config.py#L337 

It seems that cloud should be somehow set to 'openstack' by default if there are no envvars starting with OS_ and no **new style** config file.

**Comment by emonty** [comment]
@ibratoev Totally agree - I fixed a bug related to this this weekend, and will be pushing up a patch to ansible in a few minutes so that it will work as expected.

**Comment by emonty** [comment]
Have pushed up ansible/ansible#10977 and https://review.openstack.org/#/c/181645/ to address the issue.

**Comment by ibratoev** [comment]
Great! I will test it again when the fixes make it to the 'official' releases and remove my workarounds ;)

**Pull request merged**
