### PR TITLE
Fix compatibility issues with python-apt < 0.7.9

### PR DESCRIPTION
**Pull request by FabioBatSilva**
### This patch fix the apt module using python-apt 0.7.4 (ubutun 8.04 - hardy)

When installing a specific package version ansible will fail while try to access `apt.package.Package#versions` witch is only available after 0.7.9.

see :
http://apt.alioth.debian.org/python-apt-doc/library/apt.package.html#apt.package.Package.versions
#### apt: name=foo=1.00 state=present

```
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1419437723.99-201671988715310/apt", line 2167, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1419437723.99-201671988715310/apt", line 586, in main
    dpkg_options=dpkg_options)
  File "/root/.ansible/tmp/ansible-tmp-1419437723.99-201671988715310/apt", line 283, in install
    installed, upgradable, has_files = package_status(m, name, version, cache, state='install')
  File "/root/.ansible/tmp/ansible-tmp-1419437723.99-201671988715310/apt", line 209, in package_status
    avail_upgrades = fnmatch.filter((p.version for p in pkg.versions), version)
AttributeError: 'Package' object has no attribute 'versions'
```
#### lsb_release -a

```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 8.04
Release:    8.04
Codename:   hardy
```
#### dpkg -l | grep python

```
ii  python                 2.5.2-0ubuntu1
ii  python-apt             0.7.4ubuntu7
ii  python-central         0.6.5ubuntu1
ii  python-gdbm            2.5.2-0ubuntu2
ii  python-gnupginterface  0.3.2-9ubuntu1
ii  python-minimal         2.5.2-0ubuntu1
ii  python-simplejson      1.7.3-1
ii  python-support         0.7.5ubuntu1
ii  python2.5              2.5.2-2ubuntu4
ii  python2.5-minimal      2.5.2-2ubuntu4
```

### CODE REVIEW

**Comment by abadger** [comment]
This appears to just disable the ability to check rather than actually fixing the functionality on older python-apt versions.  Is that correct?

Perhaps there's a method that can be used with the underlying _cache object instead?

**Comment by FabioBatSilva** [comment]
@abadger yes, that is correct.
I did a couple of changes, now it grabs the version list for low-level lib

**Comment by abadger** [comment]
Looks good! Merging.  Note that we don't test with Ubuntu-8.04 so you may run into other places where there needs to be come compat code added to make things work.  I'll be happy to review changes if you find such issues, though.  Thanks!

# Merged

Hi!

This has been merged in, and will also be included in the next major release.

If you or anyone else has any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Comment by abadger** [comment]
@FabioBatSilva Just letting you know I committed some cleanups to your code https://github.com/ansible/ansible-modules-core/commit/170457413dd179c3154a4184cbe12ad1ab14c86e  I tried not to change any of the logic, just make the code cleaner.  If you'd like to test to be sure I didn't break anything on Ubuntu8.04 that would be great!  Thanks.

**Comment by FabioBatSilva** [comment]
Thanks for the quick feedback @abadger,
Please see : https://github.com/ansible/ansible-modules-core/pull/567

**Pull request merged**
