### PR TITLE
Absent Function was not working on user with login profile

### PR DESCRIPTION
**Pull request by raben2**
User can now be deleted with our without password (login_profile)

### CODE REVIEW

**Comment by gregdek** [comment]
@defionscode Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by juliedavila** [comment]
@raben2  can you please squash the commits into one?

**Comment by raben2** [comment]
@defionscode hope this is helpful.

**Comment by raben2** [comment]
ship_it

**Comment by juliedavila** [comment]
ship_it

**Pull request merged**
