### PR TITLE
Added optional parameter scheduler_hints.

### PR DESCRIPTION
**Pull request by Jorge-Rodriguez**
This is the same as accidentally closed PR #653 
Allows passing scheduler_hints to nova boot.

### CODE REVIEW

**Comment by bcoca** [comment]
needs rebasing.

**Comment by Jorge-Rodriguez** [comment]
Hmmm, I'm quite ham fisted with rebasing. Where does it need to be debased to?

**Comment by bcoca** [comment]
mostly you 'git pull --rebase' assuming your origin is the devel branch,
deal with any conflicts and then push again against your own branch (might
need --force). If you cannot push against the branch (others might be
using) you can create a new branch and submit a new PR.

## 

Brian Coca

**Comment by Jorge-Rodriguez** [comment]
Right, will do.

Question about the documentation, do I add anything regarding the version where the new parameters were added?

**Comment by bcoca** [comment]
i was going to correct it to 1.9 myself, but if you do it will save me time :-)

**Comment by Jorge-Rodriguez** [comment]
Sure, no problem

**Comment by Jorge-Rodriguez** [comment]
I hope I did it right.

**Pull request merged**
