### PR TITLE
Revert "escapeds changes"

### PR DESCRIPTION
**Pull request by ghost**
While this change doesn't break the creation, it does break
idempotency. This change will convert '*.*' to '`*`.*' which is
functionally the same, however when the user_mod() function looks up
the current privileges with privileges_get() it will read '*.*'

Since '*.*' != '`*`.*' it will go through the process of updating the
privleges always resulting in a 'changed' result.

This reverts commit db9ab9b2629f00350a743a4eca72fb5ee8dc8c77.

### CODE REVIEW

**Comment by Jmainguy** [comment]
Some relevent info - This change is to fix the commit in https://github.com/ansible/ansible-modules-core/pull/1358. That commit was introduced to observe ` in privlege unpack. Which allows user to to adjust privs on DB with dots in name.

**Comment by ghost** [comment]
This revert would reintroduce that bug, but this change could be still implemented in a different way. I will submit a new patch for that

**Comment by Jmainguy** [comment]
Can confirm, the commit I created is not working right.

```
[root@phy01 ansible]# ansible -i hosts all -m mysql_user -a "name=bob password=12345 priv=*.*:ALL state=present"
centos7.soh.re | success >> {
    "changed": true,
    "user": "bob"
}

[root@phy01 ansible]# ansible -i hosts all -m mysql_user -a "name=bob password=12345 priv=*.*:ALL state=present"
centos7.soh.re | success >> {
    "changed": true,
    "user": "bob"
}

[root@phy01 ansible]# ansible -i hosts all -m mysql_user -a "name=bob password=12345 priv=*.*:ALL state=present"
centos7.soh.re | success >> {
    "changed": true,
    "user": "bob"
}
```

**Comment by abadger** [comment]
@SamYaple Do we want something like this?

``` python
dbpriv = pieces[0].rsplit(".", 1)
if dbpriv[0].strip('`') != '*':
    pieces[0] = "`%s`.%s" % (dbpriv[0].strip('`'), dbpriv[1])
```

**Comment by ghost** [comment]
Since this got merged rather quickly, here is the new PR that fixes both the dot issue and the '*' issue. Tested and working.

https://github.com/ansible/ansible-modules-core/pull/1934

**Pull request merged**
