### PR TITLE
Add capability for stat module to use more hash algorithms

### PR DESCRIPTION
**Pull request by ryansydnor**
Specifically, the stat module now has a checksum_algorithm parameter.
This lets the module utilize one of the hash algorithms available on the host
to return the checksum of the file.

This change is backwards compatible. The checksum_algorithm defaults to
sha1 and still returns its result to the stat.checksum property.

I contemplated using the "get_checksum" parameter to specify the algorithm used, but opted to be explicit rather than overload an existing interface.

### CODE REVIEW

**Comment by ryansydnor** [comment]
related issue: https://github.com/ansible/ansible-modules-core/issues/2260

**Comment by gregdek** [comment]
@bpennypacker Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by tima** [comment]
I'm not @bpennypacker, but for what it's worth I think this is a useful function worth inclusion. 

I spoke to @ryansydnor about this offline. I'm wondering if `checksum_algorithm` should be folded in to `get_checksum` where the latter takes non-boolean values like "sha512" etc while a "yes" (true) value == "sha1" and "no" still means don't return a checksum. In some ways I see that streamlining the use of the module and in others I see it complicating it's code. 

Food for thought on this PR. Thanks for submitting.

**Comment by bpennypacker** [comment]
Sorry, been very busy of late.  This looks good to me.  shipit.

**Comment by tima** [comment]
@bpennypacker: Any thoughts on folding the `checksum_algorithm` in? @bcoca? @abadger?

**Comment by bcoca** [comment]
i like as is, making a boolean into a enum/boolean is error prone and turns ugly fast

**Comment by tima** [comment]
fair enough @bcoca.

**Pull request merged**
