### PR TITLE
Issue #489: s3 should not fail on checksum mismtach when overwrite=no

### PR DESCRIPTION
**Pull request by pgehres**

### CODE REVIEW

**Comment by jcassee** [comment]
@pgehres Would you consider growing the scope to include something like https://github.com/ansible/ansible/pull/7797? I have not had time to redo that PR.

**Comment by pgehres** [comment]
@jcassee I'm not a huge fan of combining features and bug fixes. IIUC, some of your pull request has already been added to the module as it was the diffing of md5s that caused my issue to become apparent.  Have you tested lately?

**Comment by jcassee** [comment]
@pgehres I understand. I think it is still not possible to avoid redownloading a file when the md5 hashes match, which was the goal of my PR. But I'll rebase it when I find the time.

**Comment by abadger** [comment]
Simple patch.  I'm going to touch it up to not set failed at all (which is the strategy taken by copy) and propose it for 1.9rc2 as well.

**Comment by abadger** [comment]
# Merged

Hi!

This has been merged in, and will also be included in the next major release.

If you or anyone else has any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Comment by bennojoy** [comment]
@jcassee can you please give #1326 a try

**Comment by jcassee** [comment]
@bennojoy Maybe someone already did this, but how do I try out Ansible 2 modules?

**Comment by bennojoy** [comment]
@jcassee just create a directory "library" in the same level as your playbook and place the module https://raw.githubusercontent.com/ansible/ansible-modules-core/devel/cloud/amazon/s3.py there and the playbook should pick up the new module.

**Comment by jcassee** [comment]
Thanks, I'll have a look.

**Comment by jcassee** [comment]
@bennojoy It works. Thanks, Benno!

**Pull request merged**
