### PR TITLE
os_orchestration_stack module for managing Openstack's Heat stacks

### PR DESCRIPTION
**Pull request by rosmo**
This doesn't use shade, because shade doesn't have support for heatclient.

### CODE REVIEW

**Comment by bcoca** [comment]
cc @emonty  @Shrews @lorin @j2sol

**Comment by emonty** [comment]
@Shrews @bcoca the UI looks good except for auth. I do not want to bring in another module with old broken auth. Just adding support to shade for creating a heat client object from auth params that matches the other modules should be about 20 minutes of effort on shade side - let me do that real quick and cut a release so that we can replace the "get a Client object" with the common code. @rosmo I'll send you a patch in just a few

**Comment by rosmo** [comment]
@emonty, awesome! Thanks.

**Comment by emonty** [comment]
I've put up a branch in my repo: emonty/ansible-modules-core@67bba3745b479413f57e929cce788046e661605a - it depends on https://review.openstack.org/#/c/222854/ and https://review.openstack.org/#/c/222856/ . I'll ping again when both land.

**Comment by caphrim007** [comment]
@emonty I see one dep was merged, the other is still under review. Is there anything we can do to assist in it getting merged? I'd love to use this module. Thanks!

**Comment by Shrews** [comment]
FYI: Heat support has landed in shade.

**Comment by caphrim007** [comment]
@Shrews shade 1.0? (or what will be 1.0). /me is definitely interested in this.

**Comment by Shrews** [comment]
Will be in 1.0, to be released hopefully this week.

**Comment by emonty** [comment]
Shade has been released - we should now rewrite this to consume that interface.

**Comment by gregdek** [comment]
Thanks @rosmo for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

**Comment by gregdek** [comment]
@emonty @Shrews what's up with this one? Should it be in core or extras? It's been sitting for a while -- what should we do with it?

**Comment by Shrews** [comment]
@gregdek It should be in extras as it is a new module and not replacing any existing, deprecated one. It still needs to be modified by the author to use shade.

**Comment by gregdek** [comment]
Thanks @Shrews.

@rosmo per comments, I'm going to close this PR and ask that you reopen it in Ansible Extras.

**Pull request closed without merging**
