### PR TITLE
Mysql hash

### PR DESCRIPTION
**Pull request by Jmainguy**

### CODE REVIEW

**Comment by Jmainguy** [comment]
Notes. 
@trevoro added the encrypted support
@clok added support for mysql 5.7
@Jmainguy added a one line change to make it only change if hash is different, and added himself as Author. (For maintainer purposes, he did not originally author this module)

**Comment by chrrrles** [comment]
Hi @Jmainguy, thanks for the PR- it would be good to see a description of what this code does (even if referencing the other PR).

**Comment by Jmainguy** [comment]
@chrrrles My bad. This PR adds two separate things. 
1. It adds support for Mysql 5.7
2. it adds a encrypted=yes/no feature. Which let let the admin set a users password to a hash. This allows the Admin set the password without ever knowing what it really is. (assuming the user gave the admin the hashed version of their password)

**Comment by gregdek** [comment]
Thanks @Jmainguy. Since you are a maintainer of this module, we are marking this PR for inclusion.

**Comment by Oneiroi** [comment]
Noting previous PR's for linking for when they appear in search results: ansible/ansible#5633 -> ansible/ansible#6049 -> #130 -> #1174 -> #1581 -> #2673 hoping to see this merged soon, thanks @Jmainguy for getting this (hopefully) finally merged.

**Comment by abadger** [comment]
Alright merged!  Thanks to @oneirol for the initial code, @trevoro for taking on the burden when the repositories were split, @morgo for reviewing, @clok for adding support for mysql-5.7, @the-lars for an alternate implementation, and @Jmainguy for taking it the final mile!

**Comment by abadger** [comment]
Merged to devel and stable-2.0 branches.

# Merged

Hi!

This has been merged in, and will also be included in the next major release.

If you or anyone else has any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Pull request merged**
