### PR TITLE
Fix connection creation in iam_policy module to allow usage of profiles with boto

### PR DESCRIPTION
**Pull request by micxer**
Fixing the same error as in #255 for the iam_policy module.

### CODE REVIEW

**Comment by bcoca** [comment]
cc @defionscode, @seiffert

**Comment by juliedavila** [comment]
@micxer how does this resolve when keys are passed in explicitly via module args? feel like it could get ignored

**Comment by micxer** [comment]
@defionscode no problem, `get_aws_connection_info` takes care of that. I also updated the code since the same error in the `iam` module was fixed in a simpler and better way than I fixed it.

**Comment by juliedavila** [comment]
+1 

good to merge

**Comment by micxer** [comment]
Just rebased to current devel branch.

**Comment by abadger** [comment]
Looks good.  Thanks for the code and the testing!

# Merged

Hi!

This has been merged in, and will also be included in the next major release.

If you or anyone else has any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Pull request merged**
