### PR TITLE
[FIX] Git: specify branch in reset

### PR DESCRIPTION
**Pull request by andreparames**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

Git
##### ANSIBLE VERSION

devel
##### SUMMARY

When force=yes is used, the git module tries to run "git reset --hard [remote]" which is not a valid command, since it should specify a treeish. This commit adds the remote branch to the command.

Before:

```
fatal: [host]: FAILED! => {"changed": false, "cmd": "/usr/bin/git reset --hard origin", 
"failed": true, "msg": "Failed to checkout branch master", "rc": 128, "stderr": "fatal: 
ambiguous argument 'origin': unknown revision or path not in the working tree.\n
Use '--' to separate paths from revisions, like this:\n'git <command> [<revision>...]
 -- [<file>...]'\n", "stdout": "", "stdout_lines": []}
```

After:

```
ok: [host]
```

### CODE REVIEW

**Comment by robinro** [comment]
@andreparames 
Thanks for this PR. It looks good to me (although I did not run it).

Could you create an integration test to avoid future regressions for this case?
See https://github.com/ansible/ansible/blob/devel/test/integration/roles/test_git/tasks/main.yml

Also I have in the back of my mind that the `git reset` arguments changed in some previous git version. If the integration test works on all distributions you know the most relevant distributions are covered.

**Comment by gregdek** [comment]
Thanks @andreparames for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @andreparames for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@andreparames A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@andreparames Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@andreparames A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@andreparames Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
