### PR TITLE
Added no_syslog option to command and async_wrapper modules (rebase #1675)

### PR DESCRIPTION
**Pull request by lberruti**
See ansible/ansible#11502
Rebased version of #1675

### CODE REVIEW

**Comment by abadger** [comment]
@bcoca thought the desired functionality was achievable with ansible's current featureset.  I'll let him reply as to what that would look like.

**Comment by gregdek** [comment]
Thanks @lberruti for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

**Comment by lberruti** [comment]
ready_for_review

Thanks!

**Comment by bcoca** [comment]
request needs to be cleaned up, this has several other commits on it

as for the feature, i avoided putting it into async_wrapper as it seems to be needed to track the jobs, left it as a follow up since we also need to rewrite it to avoid race conditions.

**Comment by lberruti** [comment]
@bcoca what do you mean "it seems to be needed to track the jobs"?

**Comment by bcoca** [comment]
Just that I need to check the polling code to confirm how it works before I
can merge this. Pretty sure it's ok, but need to verify.

**Comment by gregdek** [comment]
Thanks @lberruti for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@lberruti A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@lberruti Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by lberruti** [comment]
@gregdek ready_for_review

I don't known why shippable fails at 187.4 (check on task started as a "fire-and-forget").
This one passes on my env:

```
ansible-playbook 2.2.0 (detached HEAD 123d54e736) last updated 2016/07/30 09:58:34 (GMT +200)
  lib/ansible/modules/core: (no_syslog_rebase 622ec9f226) last updated 2016/07/30 11:07:16 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD db979dde74) last updated 2016/07/30 09:58:35 (GMT +200)
  config file =
  configured module search path = Default w/o overrides

TARGET='non_destructive destructive' TEST_FLAGS='-t test_async_wrapper' IMAGE=ansible/ansible:fedora23 TEST=integration test/utils/shippable/ci.sh
```

**Comment by gregdek** [comment]
Thanks @lberruti for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@lberruti seems to pass now, fyi. You might consider coming to one of the Ansible Core team meetings to advocate for this PR, btw.

**Comment by gregdek** [comment]
Thanks @lberruti for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by lberruti** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @lberruti for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
