### PR TITLE
ini_file should only change what was specified and nothing more #5860

### PR DESCRIPTION
**Pull request by noseka1**
See also:
http://alesnosek.com/blog/2015/08/03/improving-ansibles-ini-file-module/

### CODE REVIEW

**Comment by gregdek** [comment]
@noseka1 looks like this PR fails Travis. 

Please make the suggested revisions, and when you're done, please add a comment with the text "ready_for_review" and we will continue with the review process.  Thanks!

**Comment by noseka1** [comment]
ready_for_review

**Comment by gregdek** [comment]
Excellent @noseka1, thanks.

@jpmens Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by jpmens** [comment]
shipit

**Pull request merged**
