### PR TITLE
GCE libcloud 0.15 support

### PR DESCRIPTION
**Pull request by paparomeo**
Update for https://github.com/ansible/ansible-modules-core/pull/103

### CODE REVIEW

**Comment by gregdek** [comment]
@erjohnso Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please give it a +1; at that point, we will add the “priority_reviewed” flag to this PR, which will move it to the top of our queue for potential inclusion.

**Comment by erjohnso** [comment]
@gregdek - Visual inspection looks good and I think it satisfies the checklist, :+1:

Do you typically run any unit / integration tests on PRs?  If not, I can take it for a test drive and report back.

**Comment by paparomeo** [comment]
@erjohnso: it would be great if you could do some manual testing since I'm not actively using this any more.

**Comment by paparomeo** [comment]
Rebased on current `devel`.

**Comment by gregdek** [comment]
@paparomeo sorry, but it appears that the underlying code has changed (again) since your submission, and this PR once again needs to be rebased. My apologies; I didn't see the thumbs-up from @erjohnso previously.

If you believe that this PR still applies, please rebase and we will put it back into our community review process as soon as possible. 

Once you have rebased this PR, please add a comment with the text "ready_for_review" and we will continue with the review process.  Thanks!

@erjohnso we don't yet require integration tests for modules, so manual testing will be sufficient.

**Comment by paparomeo** [comment]
@erjohnso: rebased on current `devel`: ready_for_review

**Comment by gregdek** [comment]
Thanks @paparomeo.

@erjohnso can you take this for a test drive when you get a chance? 

If it passes, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

(Note: the travis failure is I think transient, and is from an unrelated module.)

**Comment by gregdek** [comment]
Thanks @paparomeo. @erjohnso please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by erjohnso** [comment]
Very, very sorry for not getting to this sooner @paparomeo and @gregdek! :(

shipit

**Comment by gregdek** [comment]
Looks like this one is old enough to be bitten by the cron.py Travis issue. (Which is unrelated to the actual PR.)

Marking as shipit, but with a note to the @ansible/core team to fix that bit when you merge.

Thanks @erjohnso for the review, and thanks @paparomeo for the original PR.

**Comment by paparomeo** [comment]
:+1:

**Comment by abadger** [comment]
Squashed and committed here: https://github.com/ansible/ansible-modules-core/commit/1bd04f797e2da8da8261c067eda09777ddf23fd7  If you want to check that I didn't do anything stupid with my git commands, that would be great.  This has been applied to the devel tree so right now it's slated for 2.1.

Thanks @paparomeo for the code and @erjohnso for the review!

# Merged

Hi!

This has been merged in, and will also be included in the next major release.

If you or anyone else has any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Pull request closed without merging**
