### PR TITLE
Two fixes for ec2_elb_lb module to make stickiness work with undefined expiration period 

### PR DESCRIPTION
**Pull request by haad**
Convert enabled value to boolean to actually work, make sure we can set expiration period to 0(None) to disable it

### CODE REVIEW

**Comment by gregdek** [comment]
@jsdalton @rickmendes Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by ghost** [comment]
I like the fix for enabled. It makes sense to me to be able to enable stickiness, but leave the expiration at the default of the duration of the browser session. So let's go ahead and shipit.

**Comment by gregdek** [comment]
Thanks @haad for the PR and @rickmendes for the review. Marking for potential inclusion.

**Comment by abadger** [comment]
Thanks for the contribution!  merged to devel and stable-2.0 branches.

# Merged

Hi!

This has been merged in, and will also be included in the next major release.

If you or anyone else has any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Pull request merged**
