### PR TITLE
fixed a bug with calculation md5 sum

### PR DESCRIPTION
**Pull request by UvaK**
the bug appears for files > 1KiB

### CODE REVIEW

**Comment by gregdek** [comment]
@lwade @ralph-tice please review; if you +1 we will promote to priority_reviewed

**Comment by bcoca** [comment]
it might be better to just use the common md5 function in the shared basic.py.

**Comment by gregdek** [comment]
@bcoca is that recommendation firm enough to make it a requirement?

**Comment by bcoca** [comment]
it is not what this PR means to do, but the PR would not be needed as the shared function already does buffered reads.

**Comment by gregdek** [comment]
Thanks @UvaK for submitting this PR, but it appears as though this code has been entirely rewritten and this PR no longer applies. Closing.

**Pull request closed without merging**
