### PR TITLE
Fix to revoke privileges for mysql user = ''

### PR DESCRIPTION
**Pull request by sysadmin75**
Issue 9848 fix - Unable to revoke privileges for MySQL user

### CODE REVIEW

**Comment by sysadmin75** [comment]
https://github.com/ansible/ansible/issues/9848

**Comment by gregdek** [comment]
@marktheunissen please review. If you +1, we will promote to P1_reviewed.

**Comment by marktheunissen** [comment]
Hi @gregdek, I think my name is still on the copyright of this module, but I haven't worked with Ansible for over 2 years now. I think someone else might be a better choice for a P1 review.

**Comment by gregdek** [comment]
Thanks @marktheunissen -- will find another owner for this and other modules.

**Comment by gregdek** [comment]
@banyek can you review here?

**Comment by banyek** [comment]
Oh sorry I didn't seen this mail. Give me some time

**Comment by gregdek** [comment]
No worries @banyek, thanks. Appreciate if you can take a look.

**Comment by gregdek** [comment]
@banyek friendly ping if you can take a look here.

**Comment by banyek** [comment]
I've checked it, and I don't see any bad with it (I mean I believe you this is the change needed :) but I wasn't used to write this module. 
If that's ok, I can say LGTM

**Pull request merged**
