### PR TITLE
Fixes #139 - ec2_vol errors when attaching a volume from a snapshot

### LINKED ISSUE #139: ec2_vol errors when attaching a volume from a snapshot
**Issue type:**

Bug report

**Ansible Version:**

1.6.2

**Environment:**

Mac OS X 10.9.3

**Summary:**

ec2_vol module fails to create a new volume from a snapshot and attach to an image, returning an error message that doesn't make sense given the arguments.

**Steps to reproduce:**
1. Start an instance on EC2, record the instance id
2. Create a new snapshot on EC2, record the snapshot id
3. Use the ec2_vol module to attach:
   
   ```
   ansible localhost -m ec2_vol -a "instance=i-123456 snapshot=snap-abcdef"
   ```

**Expected results:**

Creates a new EBS volume from the snapshot, attaches volume to the instance.

**Actual results:**

```
$ ansible localhost -m ec2_vol -a "instance=i-123456 snapshot=snap-abcdef"
localhost | FAILED >> {
    "failed": true,
    "msg": "Cannot specify volume_size and either one of name or id"
}
```

The error makes no sense, given that neither volume_size, name, nor id are arguments.

Note that the documentation for ec2_vol has an example with this exact combination of arguments, so I assume this is legal. From the docs:

```
# Example using snapshot id
- local_action:
    module: ec2_vol
    instance: XXXXXX
    snapshot: "{{ snapshot }}"
```

### PR DESCRIPTION
**Pull request by willusher**
The parameter validation in ec2_vol does not account for volumes to be created from snapshots.

fixes #139

### CODE REVIEW

**Comment by bennojoy** [comment]
@willusher  Could you please have a look at the conflicts

**Comment by gregdek** [comment]
@willusher Thanks for submitting this pull request. Please accept our apologies for taking so long to review it.

Unfortunately, due to this delay, it appears that the underlying code has changed, and this PR needs to be rebased. If you believe that this PR still applies, please rebase and we will then put it into our (new, faster) community review process as soon as possible.  Again, apologies for the delay and the extra work.

**Comment by eeroniemi** [comment]
I'm also suffering from this bug, would be great to get this fixed.

**Comment by eeroniemi** [comment]
I created new PR that should work with current devel branch - https://github.com/ansible/ansible-modules-core/pull/1747

**Comment by bcoca** [comment]
closing via merged #1747

**Pull request closed without merging**
