### PR TITLE
ops_template.py: Taking care of the JSON src variable

### LINKED ISSUE #3312: ops_template.py: Take care of json src variable
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

ops_template.py
##### ANSIBLE VERSION

```
air$ ansible-playbook --version
ansible-playbook 2.1.0
  config file = /usr/local/git/github.com/dc-on-docker/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

As mentioned in [ansible/ansible #15133](https://github.com/ansible/ansible/issues/15133), configuring OpenSwitch through the [OpenSwitch switch role](https://github.com/keinohguchi/ops-switch-role).
##### OS / ENVIRONMENT

Reproduced on ArchLinux control machine, just like [ansible/ansible #15133](https://github.com/ansible/ansible/issues/15133).
##### SUMMARY

Call `module.from_json` in case of `dc` or `rest` transport case.
##### STEPS TO REPRODUCE

```

---
- name: fabric switches
  hosts: fabrics
  gather_facts: yes
  vars:
    ansible_user: admin
    ops_system_hostname: "{{ inventory_hostname }}"
    ops_debug: no
  roles:
    - role: switch
      ops_intf_admin_state: up

- name: spine switches
  hosts: spines
  gather_facts: yes
  vars:
    ansible_user: admin
    ops_system_hostname: "{{ inventory_hostname }}"
    ops_debug: no
  roles:
    - role: switch
      ops_intf_admin_state: up

- name: leaf switches
  hosts: leaves
  gather_facts: yes
  vars:
    ansible_user: admin
    ops_system_hostname: "{{ inventory_hostname }}"
    ops_debug: no
  roles:
    - role: switch
      ops_intf_admin_state: up
```
##### EXPECTED RESULTS

Configure the OPS switch both through DC or REST APIs.
##### ACTUAL RESULTS

```
air$ play site.yaml

PLAY [fabric switches] *********************************************************

TASK [setup] *******************************************************************
ok: [fab1]

TASK [switch : print JSON input for this play] *********************************
skipping: [fab1]

TASK [switch : configure the switch] *******************************************
fatal: [fab1]: FAILED! => {"changed": false, "failed": true, "msg": "argument src is of type <type 'str'> and we were unable to convert
to dict"}
```

### PR DESCRIPTION
**Pull request by keithnoguchi**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

osp_template.py
##### ANSIBLE VERSION

```
air$ ansible-playbook --version
ansible-playbook 2.1.0
  config file = /usr/local/git/github.com/dc-on-docker/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

Call module.from_json() to take care of the JSON file.

Fixes #3312

After the change, we can configure the OpenSwitch by using the [switch role](https://github.com/keinohguchi/ops-switch-role)

```
air$ play site.yaml

PLAY [fabric switches] *********************************************************

TASK [setup] *******************************************************************
ok: [fab1]

TASK [switch : print JSON input for this play] *********************************
skipping: [fab1]

TASK [switch : configure the switch] *******************************************
changed: [fab1]

TASK [switch : result from the switch] *****************************************
skipping: [fab1]

PLAY [spine switches] **********************************************************

TASK [setup] *******************************************************************
ok: [spine2]
ok: [spine1]

TASK [switch : print JSON input for this play] *********************************
skipping: [spine1]
skipping: [spine2]

TASK [switch : configure the switch] *******************************************
changed: [spine1]
changed: [spine2]

TASK [switch : result from the switch] *****************************************
skipping: [spine1]
skipping: [spine2]

PLAY [leaf switches] ***********************************************************

TASK [setup] *******************************************************************
ok: [leaf1]
ok: [leaf2]
ok: [leaf3]

TASK [switch : print JSON input for this play] *********************************
skipping: [leaf1]
skipping: [leaf3]
skipping: [leaf2]

TASK [switch : configure the switch] *******************************************
changed: [leaf3]
changed: [leaf1]
changed: [leaf2]

TASK [switch : result from the switch] *****************************************
skipping: [leaf2]
skipping: [leaf1]
skipping: [leaf3]

PLAY RECAP *********************************************************************
fab1                       : ok=2    changed=1    unreachable=0    failed=0
leaf1                      : ok=2    changed=1    unreachable=0    failed=0
leaf2                      : ok=2    changed=1    unreachable=0    failed=0
leaf3                      : ok=2    changed=1    unreachable=0    failed=0
spine1                     : ok=2    changed=1    unreachable=0    failed=0
spine2                     : ok=2    changed=1    unreachable=0    failed=0
```

### CODE REVIEW

**Comment by keithnoguchi** [comment]
travis is green, as shown below:

https://travis-ci.org/keinohguchi/ops-switch-role

**Comment by gregdek** [comment]
Thanks @keinohguchi. To the current maintainers, @privateip please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by keithnoguchi** [comment]
Thank you, @gregdek, for your quick reply!  Really appreciated!  I'll go through the [module-checklist](http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and get back to you and @privateip!

Thank you for your support!

Cheers,

**Comment by privateip** [comment]
:+1:

**Comment by gregdek** [comment]
Thanks again to @keinohguchi for this PR, and thanks @privateip for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request merged**
