### PR TITLE
Added new parameter  subnet_group_name 

### PR DESCRIPTION
**Pull request by rahulmehrotra1**
Added a new non-default parameter subnet_group_name to specify subnet group to be used during creation of Elastic Cache.

### CODE REVIEW

**Comment by gregdek** [comment]
@rhlmhrtr Thanks for submitting this pull request. Please accept our apologies for taking so long to review it.

Unfortunately, due to this delay, it appears that the underlying code has changed, and this PR needs to be rebased. If you believe that this PR still applies, please rebase and we will then put it into our (new, faster) community review process as soon as possible.  Again, apologies for the delay and the extra work.

**Comment by gregdek** [comment]
@rhlmhrtr A friendly reminder: this pull request has been marked as needing your action, and it hasn't been updated in the last month. 

If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we'll keep it open pending your changes.

If we receive no indication from you within a week, we will close this pull request.

**Comment by rahulmehrotra1** [comment]
@gregdek Sorry for the late reply. I will rebase this changed today

**Comment by gregdek** [comment]
Thanks @rhlmhrtr. I've removed the pending_action tag, but a reminder that we're still waiting on the rebase.

**Comment by gregdek** [comment]
@rhlmhrtr Another friendly reminder: this pull request has been marked as needing your action, and it hasn't been updated in the last month. 

If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we'll keep it open pending your changes.

If we receive no indication from you within a week, we will close this pull request.

**Comment by gregdek** [comment]
Closing due to inactivity. Apologies @rhlmhrtr -- if you feel we've closed this PR in error, feel free to resubmit a new PR.

**Pull request closed without merging**
