### PR TITLE
Adds the ability to choose the folder of cloned VM (rebased version)

### PR DESCRIPTION
**Pull request by galindro**
Adds the ability to choose the folder of cloned VM (ansible/ansible#10326):

``` yaml
- vsphere_guest:
    vcenter_hostname: "vcenter"
    username: "root"
    password: "pass"
    guest: "test"
    from_template: "yes"
    template_src: "test_template"
    cluster: "cluster_1"
    resource_pool: "/Resources"
    vm_extra_config:
      folder: "Test_Folder"
```

### CODE REVIEW

**Comment by marvinpinto** [comment]
hmm I think this might be a dupe of https://github.com/ansible/ansible-modules-core/pull/2196 ?

**Comment by galindro** [comment]
Yes. The difference is that I've added in my code a routine to check if the folder exists before the clone. Now, ansible team needs to decide which of them they will merge.

**Comment by fennm** [comment]
This change doesn't work for me if I don't specify a folder to clone into:

```
failed: [testnode -> localhost] => {"failed": true}
msg: Could not clone selected machine: local variable 'name' referenced before assignment

FATAL: all hosts have already failed -- aborting
```

**Comment by gregdek** [comment]
Thanks @galindro. @chrrrles @rhoop please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
Thanks @galindro for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

**Comment by robynbergeron** [comment]
@galindro A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes.

**Comment by gregdek** [comment]
@galindro Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If we don't hear from you within another 14 days, we will close this pull request.

**Comment by gregdek** [comment]
Closed due to contributor inactivity.

**Pull request closed without merging**
