### PR TITLE
Match existing INI file entry with leading whitespace (fixes #4997)

### LINKED ISSUE #4997: ini_file module doesn't match existing key when it is indented
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

`ini_file` module
##### ANSIBLE VERSION

```
ansible 2.1.1.0
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

When a key in an INI file exists but is prefixed with whitespace, the `ini_file` module adds a new entry rather than updating the existing entry.
##### STEPS TO REPRODUCE

Playbook:

```
- hosts: localhost
  gather_facts: no
  tasks:
    - ini_file:
        dest: ./foo.ini
        section: main
        option: foo
        value: baz
```

INI file:

```
[main]
  foo = bar
```
##### EXPECTED RESULTS

```
[main]
  foo = baz
```
##### ACTUAL RESULTS

```
[main]
  foo = bar
foo = baz
```

### PR DESCRIPTION
**Pull request by agaffney**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

`ini_file` module
##### ANSIBLE VERSION

```
ansible 2.1.1.0
```
##### SUMMARY

As noted in https://github.com/ansible/ansible-modules-core/issues/4997, the `ini_file` module does not match an existing key when it has leading whitespace. This commit will match those existing entries but will not preserve the leading whitespace.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @agaffney. To the current maintainers, @jpmens, @noseka1 please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by jpmens** [comment]
shipit

**Comment by gregdek** [comment]
Thanks again to @agaffney for this PR, and thanks @jpmens, @noseka1 for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by agaffney** [comment]
Bah, I apparently submitted this with the wrong branch and then subsequently overwrote my `devel` branch

**Comment by agaffney** [comment]
I've re-pushed my changes to the `devel` branch in my fork of the repo. This is the same commit that was originally approved.

**Comment by abadger** [comment]
Merged to devel and stable-2.1.  SHould make it into the 2.1.2 release.

**Comment by richard-scott** [comment]
Does this also fix the problem when there is white space between the option name, and its value such as:

```
[mysqld]
bind-address      = 127.0.0.1
```

In my config file, the space between the 's' and the '=' is made up of spaces and tabs, and as such this module can't find/replace the entry ;-(

**Pull request merged**
