### PR TITLE
Fix 4161 - docker_container module fails when no ports are exposed.

### PR DESCRIPTION
**Pull request by ghost**
#4161
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

docker_container
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel de549ad675) last updated 2016/07/12 08:58:41 (GMT +200)
  lib/ansible/modules/core: (fix_4161 fbc2da345e) last updated 2016/07/12 11:16:26 (GMT +200)
  lib/ansible/modules/extras: (devel c6a45234e0) last updated 2016/07/12 10:15:35 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

The simple solution to the error. I would like to refactor out the ports part of the init, but I'm not sure about the coding standard used here.

Is it correct that self.published_ports isn't initialized with self._parse_publish_ports() before the if-statement?

### CODE REVIEW

**Comment by gregdek** [comment]
maintainer unknown ping @gregdek @resmo @robynbergeron.

**Comment by chouseknecht** [comment]
@tecarlsson  First, a big thank-you for catching this bug and flagging my shamefully, horrible attempt at fixing publish _all_ ports.  I think what we actually want though is this: #4166. Please have a look, and see if you agree.  Thanks!

**Comment by gregdek** [comment]
Thanks @tecarlsson for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by ghost** [comment]
Yes #4166 is what we want. :+1: 
That was my first idea also, but I didn't dare to make that change since I don't know all the ins and outs of the code. :)

**Pull request closed without merging**
