### PR TITLE
Fix argument rhn register

### PR DESCRIPTION
**Pull request by mscherer**
##### Issue Type:
- Bugfix Pull Request
##### Plugin Name:

rhn_register
##### Summary:

Password and activationkey should be tagged as no_log, as they are supposed to be secret.
sslcacert is a path, so should be tagged as such.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @mscherer. To the current maintainers, @barnabycourt, @vritant, @flossware, @alikins please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by alikins** [comment]
ACK

(aka, shipit :shipit:)

**Comment by alikins** [comment]
I think this should also resolve issue #3111 for the rhn_register module

**Comment by gregdek** [comment]
Thanks again to @mscherer for this PR, and thanks @barnabycourt, @vritant, @flossware, @alikins for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request merged**
