### PR TITLE
Add OpenStack Floating IP module

### PR DESCRIPTION
**Pull request by emonty**

### CODE REVIEW

**Comment by gregdek** [comment]
@emonty putting this into community_review for bookkeeping purposes.

**Comment by abadger** [comment]
@j2sol sol I've reviewed this one and the code looks good.  Let me/us know when you've had a chance to take a look and we can merge.

**Comment by abadger** [comment]
@emonty Found two documentation problems: there's a `default false` and `default 60`.  Both of these need colons.

**Comment by omgjlk** [comment]
I think this looks fine, good enough to merge. As a close follow up feature I'd like to see an option to delete the floating IP when detaching it, essentially removing it from the allocation pool. We see people all the time consume all the floating IPs into one project not realizing that they need to delete as well as detach. It could be a simple option that's acted on in the state=absent case. But again, not before this initially gets merged.

**Comment by omgjlk** [comment]
This could document the return value too, like we did with previous os_\* modules recently.

**Comment by gregdek** [comment]
Putting in needs_revision until I see that the docs problems have been fixed.

**Comment by emonty** [comment]
@gregdek chatted with @j2sol - this is ready to go now

**Pull request merged**
