### PR TITLE
Add a module to [un]install postgresql extensions

### PR DESCRIPTION
**Pull request by dschep**
https://github.com/ansible/ansible/pull/7874 updated for reorganized module repos.

### CODE REVIEW

**Comment by bcoca** [comment]
module looks good, except the 'state' option does not seem be documented

**Comment by dschep** [comment]
@bcoca, I've added that documentaiton. Upon looking at upstream it seems that DB modules got reorganized. Should I move this module to reflect that too?

**Comment by bcoca** [comment]
yep, i missed that, moving it to the postgrseql directory would be appropriate.

**Comment by dschep** [comment]
Done. @bcoca, do task playbooks now need to refer to postgresql.postgresql_db or is that not necessary?

**Comment by bcoca** [comment]
modules are searched in up to 3 dirs, so no need to add path at the current level.

**Comment by dschep** [comment]
Awesome :+1:

**Comment by bcoca** [comment]
one last thing, can you reopen this PR in the extras repo?

**Comment by abadger** [comment]
Added to the ansible-modules-axtras repo: https://github.com/ansible/ansible-modules-extras/commit/4b574ba29445a29f31adc4396ad8ff710ccd78a5

Thanks for the new module!

**Pull request closed without merging**
