### PR TITLE
Fix cron.py to remove a cron_file when job: is undefined

### PR DESCRIPTION
**Pull request by samdoran**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

`cron.py`
##### ANSIBLE VERSION

```
2.1.2.0
```
##### OS / ENVIRONMENT

**Ansible host:**
macOS 10.12 build 16A323
`ansible` installed via `pip`

**Managed node:**
CentOS Linux release 7.2.1511 (Core)
##### SUMMARY

When the optional `job` parameter is undefined, for example, when using the module to remove a `cron_file`, a type error is thrown because `strip()` is expecting a string.

This fix checks to see if it is defined before trying to use `strip()`. If `job` is undefined, it sets it to a null string.
##### STEPS TO REPRODUCE
1. Run playbook that creates a `cron_file`.
2. Run playbook that removes a `cron_file`.

Example playbook:

``` yaml
- hosts: all
  become: yes
  gather_facts: yes

  tasks:
    # Creates a cron file under /etc/cron.d
    - name: Add cron job
      cron:
        name: yum autoupdate
        weekday: 2
        minute: 0
        hour: 12
        user: root
        job: "YUMINTERACTIVE: 0 /usr/sbin/yum-autoupdate"
        cron_file: ansible_yum-autoupdate
        state: present

    # Removes a cron file from under /etc/cron.d
    - name: Remove cron file
      cron:
        name: yum autoupdate
        cron_file: ansible_yum-autoupdate
        state: absent
```
##### EXPECTED RESULTS

```
PLAY [lab-2] *******************************************************************

TASK [setup] *******************************************************************
ok: [lab-2]

TASK [Add cron job] ************************************************************
changed: [lab-2]

TASK [Remove cron file] ********************************************************
changed: [lab-2]

PLAY RECAP *********************************************************************
lab-2                      : ok=3    changed=2    unreachable=0    failed=0
```
##### ACTUAL RESULTS

```
PLAY [lab-2] *******************************************************************

TASK [setup] *******************************************************************
ok: [lab-2]

TASK [Add cron job] ************************************************************
changed: [lab-2]

TASK [Remove cron file] ********************************************************
fatal: [lab-2]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_das09z/ansible_module_cron.py\", line 700, in <module>\r\n    main()\r\n  File \"/tmp/ansible_das09z/ansible_module_cron.py\", line 645, in main\r\n    job = crontab.get_cron_job(minute, hour, day, month, weekday, job, special_time, disabled)\r\n  File \"/tmp/ansible_das09z/ansible_module_cron.py\", line 385, in get_cron_job\r\n    job = job.strip('\\r\\n')\r\nAttributeError: 'NoneType' object has no attribute 'strip'\r\n", "msg": "MODULE FAILURE"}

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
lab-2                      : ok=2    changed=1    unreachable=0    failed=1
```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @samdoran. To the current maintainers, @dsummersl, @EvanK please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by EvanK** [comment]
~~shipit~~

It looks like this bug is already addressed in #5151, by avoiding the `get_cron_job` call entirely when a job is being removed rather than added.

The PR in question is _marked for inclusion_, but not yet merged

**Comment by gregdek** [comment]
Thanks again to @samdoran for this PR, and thanks @dsummersl, @EvanK for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by resmo** [comment]
merging #5151 in favor of this PR as requested by @EvanK

**Pull request closed without merging**
