### PR TITLE
Added kms keys and tags to module

### PR DESCRIPTION
**Pull request by kalpatel01**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

ec2_vol
##### ANSIBLE VERSION

```
ansible 1.9.6
```

Added 2 features to ec2_vol module:

kms key support
ability to add tags (Module exist to add and remove tags, adding here makes dynamic tagging easier)
Fixed bug where AnsibleAWSError doesn't exist.

Repull - https://github.com/ansible/ansible-modules-core/pull/3064

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @kalpatel01 for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gundalow** [comment]
Hi,

Looks like this branch needs updating to fix the travis issues, please see this guide on how to do that cleanly.

http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

revisions_needed

**Comment by gregdek** [comment]
Thanks @kalpatel01 for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@kalpatel01 A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by jmalette** [comment]
Kal - what's the eta on this fix?

**Comment by gundalow** [comment]
@jmalette Looks like someone may need to take over this PR and use prmoved (see above links from `ansibot`) to the new repo. Doesn't look like @kalpatel01 is active anymore

**Comment by kalpatel01** [comment]
I took a break leaving country with no computer and spotty internet.  ill be back next month if it can wait.
Kal
-------- Original message --------From: John R Barker <notifications@github.com> Date: 12/19/16  10:33 PM  (GMT+05:30) To: ansible/ansible-modules-core <ansible-modules-core@noreply.github.com> Cc: kalpatel01 <kal@klowz.com>, Mention <mention@noreply.github.com> Subject: Re: [ansible/ansible-modules-core] Added kms keys and tags to module
  (#4110) 
@jmalette Looks like someone may need to take over this PR and use prmoved (see above links from ansibot) to the new repo. Doesn't look like @kalpatel01 is active anymore

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ansible/ansible-modules-core","title":"ansible/ansible-modules-core","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ansible/ansible-modules-core"}},"updates":{"snippets":[{"icon":"PERSON","message":"@gundalow in #4110: @jmalette Looks like someone may need to take over this PR and use prmoved (see above links from `ansibot`) to the new repo. Doesn't look like @kalpatel01 is active anymore"}],"action":{"name":"View Pull Request","url":"https://github.com/ansible/ansible-modules-core/pull/4110#issuecomment-268018991"}}}

**Pull request closed without merging**
