### PR TITLE
Fix example indentation bug

### PR DESCRIPTION
**Pull request by jaimegago**
This is is just a minor example fix.

### CODE REVIEW

**Comment by bcoca** [comment]
actually your fix is incorrect, with_items is a task directive, not part of the ec2_vol options as such it is at the correct indentation level.

**Comment by jaimegago** [comment]
@bcoca well I must be missing something, maybe you can spot it:

Playbook with -what I thought- is wrong indentation as copy/paste from example:

```
---
- hosts: "localhost"
  connection: "local"
  gather_facts: False

  tasks:
    - ec2:
        image: "ami-b53dc0f1"
        instance_type: "m3.medium"
        region: "us-west-1"
        vpc_subnet_id: "REDACTED"
        instance_tags:
          Name: "jaime-test-deleteme"
        wait: yes
        exact_count: 1
        count_tag:
          Name: "jaime-test-deleteme"
      register: ec2

    - ec2_vol:
        instance: "{{ item.id }} "
        volume_size: 5
        with_items: ec2.instances
      register: ec2_vol
```

Fails with : 

```
LAY [localhost] **************************************************************

TASK: [ec2 ] ******************************************************************
ok: [localhost]

TASK: [ec2_vol ] **************************************************************
fatal: [localhost] => One or more undefined variables: 'item' is undefined

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/home/vagrant/playbook.retry

localhost                  : ok=1    changed=0    unreachable=1    failed=0
```

When I change the indentation as per my PR it works.

**Comment by bcoca** [comment]
your playbook si wrong, with_items is indented too much, the same as this PR attempts to do.

**Comment by jaimegago** [comment]
@bcoca This playbook which I agree is wrong is a _COPY/PASTE_ of the example, my PR is about fixing "with_items being indented too much" precisely!

This is a copy paste from the example maybe it will be more obvious...

```
# Playbook example combined with instance launch
- ec2:
    keypair: "{{ keypair }}"
    image: "{{ image }}"
    wait: yes
    count: 3
  register: ec2
- ec2_vol:
    instance: "{{ item.id }} "
    volume_size: 5
    with_items: ec2.instances
  register: ec2_vol
```

**Pull request merged**
