### PR TITLE
rds module: add command to reboot RDS instance

### PR DESCRIPTION
**Pull request by herbyg-axial**

### CODE REVIEW

**Comment by juliedavila** [comment]
@herbyg-axial can you rebase this please

**Comment by gregdek** [comment]
Hi @herbyg-axial still think this PR applies? Willing to rebase?

**Comment by gregdek** [comment]
@herbyg-axial A friendly reminder: this pull request has been marked as needing your action, and it hasn't been updated in the last month. 

If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we'll keep it open pending your changes.

If we receive no indication from you within a week, we will close this pull request.

**Comment by herbyg-axial** [comment]
@gregdek This is being rebased and updated

**Comment by herbyg-axial** [comment]
OK, this is cleaned up and ready to go.

**Pull request merged**
