### PR TITLE
Set folder with from_template option in vsphere_guest module

### PR DESCRIPTION
**Pull request by galindro**
Adds the ability to choose the folder of cloned VM (https://github.com/ansible/ansible/issues/10326):

``` yaml
- vsphere_guest:
    vcenter_hostname: "vcenter"
    username: "root"
    password: "pass"
    guest: "test"
    from_template: "yes"
    template_src: "test_template"
    cluster: "cluster_1"
    resource_pool: "/Resources"
    vm_extra_config:
      folder: "Test_Folder"
```

### CODE REVIEW

**Comment by bennojoy** [comment]
@galindro seems like there is another commit which modfies the asg module , can you please check

**Comment by galindro** [comment]
@bennojoy , I'm sorry but this PR isn't related to asg module, AFAIK... What you are trying to say? Are you referencing this PR: https://github.com/ansible/ansible-modules-core/pull/1447 ?

**Comment by bcoca** [comment]
@galindro no, look at your commits and/or files modified, somehow a stray commit to the ec2_asg module is included in this PR

**Comment by galindro** [comment]
@bcoca @bennojoy ,this is because I've used the same fork that I make the PR https://github.com/ansible/ansible-modules-core/pull/1447. 

I need first remove my previous fork, make a new fork, change the code in a new branch and make a new PR? If I remove the first fork, the PR https://github.com/ansible/ansible-modules-core/pull/1447 will be broken?

**Comment by gregdek** [comment]
@galindro I would recommend two new PRs from different branches and closing these PRs.

**Comment by galindro** [comment]
@gregdek ,I'll close this PR and make a new one. Isn't necessary to close the PR #1447

**Comment by galindro** [comment]
New PR openned: https://github.com/ansible/ansible-modules-core/pull/1663

**Pull request closed without merging**
