### PR TITLE
Make ec2_eip idempotent

### PR DESCRIPTION
**Pull request by jml**
This is exactly https://github.com/ansible/ansible-modules-core/pull/300/ but with the `allocate` state renamed to `allocated` and the `allocate_eip` function extracted from `main` into a top-level function.

### CODE REVIEW

**Comment by juliedavila** [comment]
@jml this looks good (havent tested yet) but I'd like to avoid the merge commit 9c275fcbbaaf84a0fd05f3fbd19625c0cf92cbe7. Could you fix it?

**Comment by jml** [comment]
@defionscode Thanks. I've got rid of the merge commit. Let me know if it needs further work.

**Comment by jml** [comment]
@defionscode friendly ping

**Comment by jml** [comment]
Is this OK to be merged, or would you like me to do some more work?

**Comment by bcoca** [comment]
So since instance ID is not required, I would prefer to keep this as 'present' and just allocate it to the account when no instance id is supplied. This would not require a 3rd state

**Comment by jml** [comment]
Done. Please take a look.

**Comment by jml** [comment]
Is this good to merge?

**Comment by bcoca** [comment]
the commit history still looks messy, can you rebase this to one commit?

**Comment by jml** [comment]
Done. Thanks.

**Comment by sruon** [comment]
This was apparently reverted in commit c36e8947bcfae48d07347d3fd32f1aa345958bb7

I will open a new separate issue.

**Pull request merged**
