### PR TITLE
add stat symlink target details in follow=no mode

### PR DESCRIPTION
**Pull request by 399a36c3b7**
- Feature Pull Request
##### Summary:

This will add capability for stat's users to query the size,
checksum, mime attributes of the symlink target as well as the
real path of symlink's target by including all of target's stat
attributes under lnk_<attrname> items, as well as lnk_source
with follow=no.
##### Example:

```
$ head -n 100 /dev/random > /tmp/foorandom
$ ln -s /tmp/foorandom /tmp/bar
$ cat play.yml

---
- hosts: localhost
  tasks:
    - stat:
        follow: no
        path: /tmp/bar
      register: statres
    - debug:
        var: statres
```

```
PLAY [localhost] ************************************************************** 

TASK: [stat ] ***************************************************************** 
ok: [localhost]

TASK: [debug ] **************************************************************** 
ok: [localhost] => {
    "var": {
        "statres": {
            "changed": false, 
            "invocation": {
                "module_args": "", 
                "module_complex_args": {
                    "follow": false, 
                    "path": "/tmp/bar"
                }, 
                "module_name": "stat"
            }, 
            "stat": {
                "atime": 1457965423.0, 
                "ctime": 1457965423.0, 
                "dev": 16777220, 
                "exists": true, 
                "gid": 0, 
                "gr_name": "wheel", 
                "inode": 4072461, 
                "isblk": false, 
                "ischr": false, 
                "isdir": false, 
                "isfifo": false, 
                "isgid": false, 
                "islnk": true, 
                "isreg": false, 
                "issock": false, 
                "isuid": false, 
                "lnk_atime": 1457965491.0, 
                "lnk_checksum": "d4d56bbc33e2d81afb2ff021ad742149762800ad", 
                "lnk_ctime": 1457965408.0, 
                "lnk_dev": 16777220, 
                "lnk_exists": true, 
                "lnk_gid": 0, 
                "lnk_gr_name": "wheel", 
                "lnk_inode": 4072454, 
                "lnk_isblk": false, 
                "lnk_ischr": false, 
                "lnk_isdir": false, 
                "lnk_isfifo": false, 
                "lnk_isgid": false, 
                "lnk_isreg": true, 
                "lnk_issock": false, 
                "lnk_isuid": false, 
                "lnk_md5": "04967306a5978508ac7e2f4c4b1b63bc", 
                "lnk_mode": "0644", 
                "lnk_mtime": 1457965408.0, 
                "lnk_nlink": 1, 
                "lnk_path": "/tmp/foorandom", 
                "lnk_pw_name": "redacted", 
                "lnk_rgrp": true, 
                "lnk_roth": true, 
                "lnk_rusr": true, 
                "lnk_size": 30066, 
                "lnk_source": "/tmp/foorandom", 
                "lnk_uid": 501, 
                "lnk_wgrp": false, 
                "lnk_woth": false, 
                "lnk_wusr": true, 
                "lnk_xgrp": false, 
                "lnk_xoth": false, 
                "lnk_xusr": false, 
                "mode": "0755", 
                "mtime": 1457965423.0, 
                "nlink": 1, 
                "path": "/tmp/bar", 
                "pw_name": "redacted", 
                "rgrp": true, 
                "roth": true, 
                "rusr": true, 
                "size": 14, 
                "uid": 501, 
                "wgrp": false, 
                "woth": false, 
                "wusr": true, 
                "xgrp": true, 
                "xoth": true, 
                "xusr": true
            }
        }
    }
}
```

This will add capability for stat's users to query the size,
checksum, mime attributes of the symlink target as well as the
real path of symlink's target by including all of target's stat
attributes under lnk_<attrname> items, as well as lnk_source
with follow=no.

### CODE REVIEW

**Comment by bcoca** [comment]
you are removing previous features and fixes, please apply your changes against a newer version of the module

**Comment by 399a36c3b7** [comment]
@bcoca sorry about that, fixed it up. can you take another look?

**Comment by gregdek** [comment]
Thanks @alxnov. To the current maintainers, @bpennypacker please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @alxnov for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@alxnov A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@alxnov Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@alxnov A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@alxnov Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@alxnov A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by abadger** [comment]
We looked at this PR today and felt that this is duplicating functionality.  The stat module can already get both the symlink and the symlink's target by using the follow=True parameter.  Since this PR was already marked to be closed, I'll go ahead and close it now.

**Pull request closed without merging**
