### PR TITLE
add possibility to upload binary file via uri module

### PR DESCRIPTION
**Pull request by mploski**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

uri
##### ANSIBLE VERSION

2.2
##### SUMMARY

This feature allow to send binary files to endpoint smoothly. 
Added new parameter source.
When source parameter is valid file is open and file descriptor is passed to URLLIB2. Its used as data parameter.
https://github.com/ansible/ansible-modules-core/issues/3157

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @mludy. To the current maintainers, @romeotheriault please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @mludy for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by mludy** [comment]
ready_for_review

**Comment by mploski** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @mludy. To the current maintainers, @romeotheriault please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @mludy for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by mploski** [comment]
Something strange happen here. I will reopen this PR

**Pull request closed without merging**
