### PR TITLE
Os nova list addresses

### LINKED ISSUE #1171: Invalid public ip address from nova_compute.
_openstack_find_nova_addresses_ in nova_compute munges ip addresses together if an instance has more than one floating ip address.

Instances created with > 1 floating ip address get an invalid response:
{'key': 'public_ip', 'value': '90.216.134.1610.76.71.191'}

```
failed: [90.216.133.1610.75.71.181 -> 127.0.0.1] => {"elapsed": 300, "failed": true}
msg: Timeout when waiting for search string OpenSSH in 90.216.134.1610.76.71.191:22
```

### PR DESCRIPTION
**Pull request by sky-shiny**
Fixes #1171

### CODE REVIEW

**Comment by bcoca** [comment]
??

**Comment by sky-shiny** [comment]
Yeah, sorry about that. Here's the details: https://github.com/ansible/ansible-modules-core/issues/1171

**Comment by sky-shiny** [comment]
Is that better?  Removed the bogus commits.

**Comment by bcoca** [comment]
yes, this looks like a bad attempt to stringify the response, ','.join might have been a better choice.

**Pull request merged**
