### PR TITLE
add awslogs option in docker module log driver

### PR DESCRIPTION
**Pull request by j3ffrw**
add awslogs option in docker module log driver

### CODE REVIEW

**Comment by gregdek** [comment]
@cove @joshuaconner @softzilla @smashwilson Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by smashwilson** [comment]
:+1: Looks good to me! :shipit:

One thing I will note is that we currently have no validation of `log_driver`'s _value_ against the Docker API version. There have been a few additions each version since `log_driver` was introduced. We also don't attempt to validate `log_opts` against the driver. But, if you mix them up, the `DockerAPIError` will get caught and reported properly, so I don't think it's a big deal.

**Comment by gregdek** [comment]
Thanks again to @j3ffrw for this PR, and thanks @cove @joshuaconner @softzilla @smashwilson @zfil @ThomasSteinbach for reviewing. Marking for inclusion.

**Comment by bcoca** [comment]
can you clean up the commit history and add a note that awslogs are only available in versions 2.1 and above?

**Comment by gregdek** [comment]
Thanks @j3ffrw. @cove @joshuaconner @softzilla @smashwilson @zfil @ThomasSteinbach please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
@j3ffrw A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes.

**Comment by j3ffrw** [comment]
@bcoca done with commit cleanup and rebase

**Pull request merged**
