### PR TITLE
user: make system=yes work on Darwin systems.

### PR DESCRIPTION
**Pull request by rqelibari**
##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
system/user.py module

##### ANSIBLE VERSION
```
ansible 2.3.0 (devel 4981feee99) last updated 2016/11/15 14:27:13 (GMT +200)
  lib/ansible/modules/core: (detached HEAD a4cddac368) last updated 2016/11/15 14:29:56 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 19c7d5b31b) last updated 2016/11/15 14:28:34 (GMT +200)
  config file = 
  configured module search path = Default w/o overrides
```

##### SUMMARY
Extend user module for Darwin operating systems such that the `system` option of the user module now generates a system uid (< 500) if possible. If all system uids are taken, normal uid will be generated.

Extend `_get_next_uid` method of `DarwinUser` class  to take an extra argument `system` so the method knows, that the user wants a system uid. Change logic to prefer next free id below of 500.

Commit message: Add ability to add real system users with next free system uid (< 500) on macOS.

### CODE REVIEW

**Comment by rqelibari** [comment]
Why does the failing node on Shippable say:

```
2016-11-15 14:03:49     system = True if system == True else False
2016-11-15 14:03:49                    ^
2016-11-15 14:03:49 SyntaxError: invalid syntax
```

Isn't this valid python syntax?

**Comment by rqelibari** [comment]
Improved syntax of admonished line.

**Comment by gregdek** [comment]
Thanks @rqelibari for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by rqelibari** [comment]
@bcoca: You already reviewed my last PR. Is this one different? Can I help somehow?

**Comment by rqelibari** [comment]
@bcoca Can I do something to speed up the review process?

**Pull request closed without merging**
