### PR TITLE
Fix use of unauthenticated connection examples in git module docs

### PR DESCRIPTION
**Pull request by ypid**
##### ISSUE TYPE
- Docs Pull Request
##### COMPONENT NAME
- git module
##### ANSIBLE VERSION

devel
##### SUMMARY
- Fix use of unauthenticated connection examples in git module docs

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @ypid for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by robinro** [comment]
Wouldn't it make more sense to use real, working repositories?
Using the ansible/\* repos should be fine and also allows for some variation.

**Comment by ypid** [comment]
> Wouldn't it make more sense to use real, working repositories?

I am fine with the example, not working git URLs currently used. Ref: https://github.com/ansible/ansible/issues/17479

**Comment by gregdek** [comment]
Thanks @ypid for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by ypid** [comment]
ready_for_review
Please merge, this is a very small docs improvement.

**Comment by gregdek** [comment]
Thanks @ypid for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Review by robinro — APPROVED** [review]
LGTM, shipit

**Comment by gregdek** [comment]
Thanks @ypid for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by ypid** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @ypid for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by jctanner** [comment]
Migrated to https://github.com/ansible/ansible/pull/22875

**Pull request closed without merging**
