### PR TITLE
Adding start and stop actions to os_server_actions

### PR DESCRIPTION
**Pull request by tkinz27**
Also making the os_server server status check allow a server in
the possible states from os_server_actions

I discussed this a bit more https://groups.google.com/forum/#!topic/ansible-devel/AaiUHLBucbw

### CODE REVIEW

**Comment by gregdek** [comment]
@emonty @shrews @dguerri @juliakreger @j2sol @rcarrillocruz

Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by omgjlk** [comment]
This looks good to me. I assume you've tested it @tkinz27 ?  If so, 

shipit

**Comment by tkinz27** [comment]
Yeah I use this code fairly regularly.

**Comment by gregdek** [comment]
Thanks @tkinz27 for the PR and thanks @j2sol for the review.

Marking for inclusion. cc: @ansible/core team.

**Comment by jimi-c** [comment]
Merged, thanks!

**Pull request merged**
