### PR TITLE
add force_disable module arg

### PR DESCRIPTION
**Pull request by jrmsgit**
Hi

Trying to disable the Apache2.4 access_compat module via an ansible playbook using the apache2_module I found that to disable that module the command a2dismod asks for confirmation as it can be a dangerous change.

You can provide the -f arg to a2dismod in order to avoid that confirmation so I modified the apache2_module a bit so it can accept now a force_disable argument to add the -f arg to the command line.

I guess that that could be of help so I'm sharing it.

Thanks!

Jeremías

### CODE REVIEW

**Comment by jrmsgit** [comment]
Sorry for the two commits...

**Comment by bennojoy** [comment]
@jrmsgit  can you please add the version_added flag to the doc string

**Comment by jrmsgit** [comment]
@bennojoy thanks for the feedback. I'm not sure what should I do... The module already has a version_added flag in the doc string, it's set as 1.6. Should increase it to 1.7 or something like that? This is my first attempt for a contribution to the project, sorry.

**Comment by jrmsgit** [comment]
@bennojoy I've set the version_added as 2.0. Thanks!

**Comment by bcoca** [comment]
the version added update was for the new option, not the module itself

**Comment by jrmsgit** [comment]
@bcoca ok, thanks. I think it's fine now then.

**Comment by gregdek** [comment]
@berendt Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please give it a +1; at that point, we will add the “priority_reviewed” flag to this PR, which will move it to the top of our queue for potential inclusion.

**Comment by gregdek** [comment]
Hi @berendt -- are you available to review this PR?

**Comment by gregdek** [comment]
Since @berendt seems to be unavailable to review, putting this into core_review -- it may take a while longer for this patch to be reviewed. Thanks for your patience here.

**Comment by gregdek** [comment]
Thanks @jrmsgit for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@jrmsgit A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@jrmsgit Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@jrmsgit A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@jrmsgit Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@jrmsgit A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
