### PR TITLE
EC2 - start and stop by tag

### PR DESCRIPTION
**Pull request by wtcross**
This PR builds on code written by @lorin ([here](https://github.com/ansible/ansible/pull/7197)) before the code reorganization and splitting out of `ansible-modules-core`. It looks like [an issue was created for this repo](https://github.com/ansible/ansible-modules-core/issues/138), but no PR.

I added just one line to make the existing code work and made sure everything looks good.

### CODE REVIEW

**Comment by wtcross** [comment]
This feature would be very nice to have in core for several scenarios.

**Comment by lorin** [comment]
:+1:

**Comment by haad** [comment]
+1

**Comment by gregdek** [comment]
@wtcross Thanks for submitting this pull request. Please accept our apologies for taking so long to review it.

Unfortunately, due to this delay, it appears that the underlying code has changed, and this PR needs to be rebased. If you believe that this PR still applies, please rebase and we will then put it into our (new, faster) community review process as soon as possible.  Again, apologies for the delay and the extra work.

**Comment by haad** [comment]
I have rebased this code at #1703 so we can close this PR

**Pull request closed without merging**
