### PR TITLE
win_get_url re-download file only if modified

### PR DESCRIPTION
**Pull request by talcloudshare**
Avoid downloading the same file again if the file on the server wasn't modified, this is based on the file modified date

### CODE REVIEW

**Comment by bcoca** [comment]
I would not add this w/o adding an option to 'force' the download

**Comment by talcloudshare** [comment]
Makes sense, will try to address that tomorrow

**Comment by talcloudshare** [comment]
Added force parameter, it accepts yes/no and defaults to no

**Comment by trondhindenes** [comment]
On line 65, Set-content won't throw an error since it proably will be a non-terminating one. You should probably add an `-erroraction "stop"` to the set-content cmdlet. Non-terminating errors are not picked up by try/catch blocks, so there's a real chance your catch block won't be executed even if something goes wrong with the code as is.

**Comment by talcloudshare** [comment]
Thanks, added `-ErrorAction Stop`. Let me know if you find any other issues.

**Comment by gregdek** [comment]
@angstwad Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please give it a +1; at that point, we will add the “priority_reviewed” flag to this PR, which will move it to the top of our queue for potential inclusion.

**Comment by trondhindenes** [comment]
@talcloudshare I'm picky here, but the "force" param accepts any string value without failing. Could you make sure you fail if the specified param value is outside of the accepted values? We usually use the Convertto-Bool function to auto-accept any boolean-able values, such as "true", "yes" and "1".

This should fail:
`win_get_url -a "url=http://download.microsoft.com/download/1/6/B/16B06F60-3B20-4FF2-B699-5E9B7962F9AE/VSU_4/vcredist_x64.exe dest='C:\vcredist' force=something"`

**Comment by talcloudshare** [comment]
Sorry, have been quite busy. Not sure if this resolves the issue you mentioned as it still doesn't fail when a string value doesn't match the accepted boolean vaules, but it does defaults to false on unexpected inputs.

**Comment by trondhindenes** [comment]
Yep, I just noticed on another PR that that's the behavior of convertto-bool. That's fine.

**Comment by trondhindenes** [comment]
Looks good now :+1: from me. Nice addition to the module.

**Comment by gregdek** [comment]
Thanks @talcloudshare for the PR, and thanks @trondhindenes for the review, as always :)

**Comment by gregdek** [comment]
Oops... thought this was an Extras module, merged prematurely. @bcoca @jimi-c @toshio please double-check to make sure we're good here (and revert if needed)

**Pull request merged**
