### PR TITLE
cloud/s3 module: added delobj command

### PR DESCRIPTION
**Pull request by bpennypacker**
##### Ansible Version:

ansible 1.8 (devel 43eb821d3f) last updated 2015/01/07 20:16:03 (GMT +000)
  lib/ansible/modules/core: (detached HEAD db5668b84c) last updated 2015/01/07 20:16:14 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD 110250d344) last updated 2015/01/07 20:16:20 (GMT +000)
##### Environment:

N/A
##### Summary:

This pull request adds the ability to delete an object from an S3 bucket.  Currently the S3 module has the ability to delete an entire bucket via the 'delete' command, but does not have a way to delete an individual item (object) from within a bucket.

Rather than override the 'delete' command and risk inadvertently deleting an entire bucket when you really wanted to just delete an object within the bucket I've added a command named 'delobj' to explicitly delete an object within the bucket.
##### Steps To Reproduce:

```
    - s3: bucket=mybucket object=/path/to/item mode=delobj
```
##### Expected Results:

The object should be removed from the specified bucket
##### Actual Results:

N/A

### CODE REVIEW

**Comment by bpennypacker** [comment]
Any chance of getting this accepted?  I've been trying to get this added to the s3 module since last May, before ansible-modules-core was even split out from ansible (see https://github.com/ansible/ansible/pull/7569)...

**Comment by bennojoy** [comment]
@bpennypacker sorry for delay here, would it be possible to resolve the conflicts

**Comment by bcoca** [comment]
don't merge back into your branch, do a pull --rebase and put your changes on top of current.

**Comment by bpennypacker** [comment]
rebasing isn't working - I'm getting a ton of conflicts and I'm not sure why.  Since this is a pretty straightforward commit I'm going to just close this one out, get a current copy of ansible-modules-core, then resubmit the pull request using that.  I'll post a link here to the new pull request when its ready.

**Comment by bpennypacker** [comment]
Here's the new pull request: https://github.com/ansible/ansible-modules-core/pull/1503

**Pull request closed without merging**
