### PR TITLE
add retry with exponential backoff on route53

### PR DESCRIPTION
**Pull request by ashwanthkumar**
Similar to #569 but for route53.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @ashwanthkumar. @bpennypacker please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by bpennypacker** [comment]
Looks good.  shipit.

Thanks, @ashwanthkumar!

**Comment by ashwanthkumar** [comment]
@bpennypacker Thanks! One small question - Do you think, would it be useful if we can extract this retry method separately and use it across all AWS modules? Since they've throttling implemented for all the services.

**Comment by bcoca** [comment]
that is something i was trying out here https://github.com/bcoca/ansible/tree/retry_rate (also rate limiting and result 'paging')

**Comment by bpennypacker** [comment]
I like the retry idea.  I do think it would make for a good method for other modules if it can be abstracted properly. It might need a bit more robust exception handling so other exceptions can be handled - I'd have to think about that a bit.

**Comment by ashwanthkumar** [comment]
@gregdek @bpennypacker Would we be merging this?

**Comment by gregdek** [comment]
Thanks again to @ashwanthkumar for this PR, and thanks @bpennypacker for reviewing. Marking for inclusion.

**Comment by joelthompson** [comment]
@bcoca -- just wondering about your previous comment. I just submitted #3379 for much the same thing, though in a different way (using a decorator), and was also thinking that we should do something more standard across AWS modules. It looks like you deleted the branch you referenced, so I'm not sure what you were experimenting with, but what about potentially putting something like this in ansible.module_utils.ec2?

**Pull request merged**
