### PR TITLE
Fix derivation of remote head branch. Fixes #70.

### LINKED ISSUE #70: git: get_head_branch incorrect when branch name contains a slash
[re-posting module issue from ansible/ansible#6672]
##### Issue Type:

Bug Report
##### Ansible Version:

1.5.3
##### Environment:

OS X 10.9.2
##### Summary:

`get_head_branch()` fails to correctly compute the HEAD branch if the branch name contains a slash. This is caused by splitting on '/' and indexing [-1] [here](https://github.com/ansible/ansible-modules-core/blob/c8e1a2077ed356fb893cd9886f758ac3d284e6b9/source_control/git.py#L398).
##### Steps To Reproduce:

Run this playbook:

```
- name: checkout llvm
  git: repo=https://github.com/thpani/llvm.git
       dest=/home/vagrant/llvm/
```

Checkout fails because branch is computed as
`release_33_nullsucc`
instead of
`patches/release_33_nullsucc`.
##### Expected Results:

`get_head_branch()` computes the correct branch name.

I.e. behave as if the above example were

```
- name: checkout llvm
  git: repo=https://github.com/thpani/llvm.git
       dest=/home/vagrant/llvm/
       version=patches/release_33_nullsucc
```
##### Actual Results:

```
TASK: [checkout llvm] *********************************************************
failed: [default] => {"failed": true}
msg: Failed to checkout branch release_33_nullsucc
```

### PR DESCRIPTION
**Pull request by leroux**
##### Issue Type:

Bugfix Pull Request
##### Ansible Version:

devel
##### Environment:

N/A
##### Summary:

`get_head_branch()` fails to correctly compute the HEAD branch if the branch name contains a slash. Fixes issue #70.
##### Steps To Reproduce:

```
mkdir test-repo
cd test-repo

git init
git commit --allow-empty -m "Empty"
git checkout -b test/hello
git symbolic-ref HEAD refs/heads/test/hello

ansible all -vvvv -i "localhost," -c local -m git -a "repo=. dest=./cloned-test-repo"
```
##### Expected Results:

```
<localhost> REMOTE_MODULE git repo=. dest=./cloned-test-repo
<localhost> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1417638703.34-254701010202261 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1417638703.34-254701010202261 && echo $HOME/.ansible/tmp/ansible-tmp-1417638703.34-254701010202261']
<localhost> PUT /var/folders/17/bkfps9l155v_zhlnnf_8b0040000gn/T/tmpkVCfGl TO /Users/leroux/.ansible/tmp/ansible-tmp-1417638703.34-254701010202261/git
<localhost> EXEC ['/bin/sh', '-c', u'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /Users/leroux/.ansible/tmp/ansible-tmp-1417638703.34-254701010202261/git; rm -rf /Users/leroux/.ansible/tmp/ansible-tmp-1417638703.34-254701010202261/ >/dev/null 2>&1']
localhost | success >> {
    "after": "aaaf6f9a4d02467fd05b604f25e0f52d5752ba2c",
    "before": null,
    "changed": true
}
```
##### Actual Results:

```
<localhost> REMOTE_MODULE git repo=. dest=./cloned-test-repo
<localhost> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1417635768.98-64434188432060 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1417635768.98-64434188432060 && echo $HOME/.ansible/tmp/ansible-tmp-1417635768.98-64434188432060']
<localhost> PUT /var/folders/17/bkfps9l155v_zhlnnf_8b0040000gn/T/tmpDFLwXB TO /Users/leroux/.ansible/tmp/ansible-tmp-1417635768.98-64434188432060/git
<localhost> EXEC ['/bin/sh', '-c', u'LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8 /usr/bin/python /Users/leroux/.ansible/tmp/ansible-tmp-1417635768.98-64434188432060/git; rm -rf /Users/leroux/.ansible/tmp/ansible-tmp-1417635768.98-64434188432060/ >/dev/null 2>&1']
localhost | FAILED >> {
    "failed": true,
    "msg": "Failed to checkout branch hello"
}
```

### CODE REVIEW

**Comment by mgcleveland** [comment]
Tested and it works for me.

**Comment by andrewtchin** [comment]
LGTM

**Comment by jacobmacelroy** [comment]
A work around for this is to specify version=your/branch but it would be better if you didn't have to do that.  +1 for this.

**Comment by abadger** [comment]
Did some quick testing and it doesn't look like git rev-parse works for bare repos.  Looks like we'll need to have a different code path to handle that.

**Comment by timsutton** [comment]
I took a different approach, which was to leave the existing code as-is, but not split over '/' but instead `ref: refs/heads/` etc.

``` diff
diff --git a/source_control/git.py b/source_control/git.py
index 0cb8730..27d557c 100644
--- a/source_control/git.py
+++ b/source_control/git.py
@@ -466,10 +466,12 @@ def get_head_branch(git_path, module, dest, remote, bare=False):
     # If we're in a detached HEAD state, look up the branch associated with
     # the remote HEAD in .git/refs/remotes/<remote>/HEAD
     f = open(os.path.join(repo_path, "HEAD"))
+    prefix = 'ref: refs/heads/'
     if is_not_a_branch(git_path, module, dest):
         f.close()
         f = open(os.path.join(repo_path, 'refs', 'remotes', remote, 'HEAD'))
-    branch = f.readline().split('/')[-1].rstrip("\n")
+        prefix = 'ref: refs/remotes/%s/' % remote
+    branch = f.readline().split(prefix)[-1].rstrip("\n")
     f.close()
     return branch
```

I looked at the rev-parse strategy with some local test repos on my machine but found that with a local repo I need to specify `HEAD` instead of a remote name (because there wasn't one), and that if it's a checkout in a detached HEAD then the remote name was fine. So it looks like the rev-parse approach might need some additional logic anyway, and I don't think the integration tests currently test these situations properly.

**Comment by gregdek** [comment]
@leroux A friendly reminder: this pull request has been marked as needing your action, and it hasn't been updated in the last month. 

If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we'll keep it open pending your changes.

If we receive no indication from you within a week, we will close this pull request.

**Pull request closed without merging**
