### PR TITLE
Adds basic authentication & skip certificate validation to win_get_ur…

### PR DESCRIPTION
**Pull request by abriening**
Adds basic auth and SSL cert skipping to win_get_url module.

### CODE REVIEW

**Comment by gregdek** [comment]
@angstwad please review; if you give +1, we will promote to P1_reviewed.

**Comment by angstwad** [comment]
@gregdek Doing just a visual inspection, this looks okay to me.  I'd prefer a Windows/PowerShell expert (I am not an expert :smile:) give their thumbs up before confirming.

**Comment by gregdek** [comment]
Well then let's call in the cavalry. @trondhindenes @jhawkesworth?

**Comment by trondhindenes** [comment]
Looks good. One thing (and call me picky):
`if($params.skip_certificate_validation) {`
Rememer that the object coming in via json params is a string. So whatever the skip_certificate_validation is set to here (even "false") will result in this expression getting validated to true. I recommend using the builtin convertto-bool function to convert the param into a proper boolean object and then perform your test on that. Something like:
`if(($params.skip_certificate_validation) -and (ConvertTo-bool $params.skip_certificate_validation))
{
#execute code
}`

**Comment by gregdek** [comment]
I like picky. :)  Thanks @trondhindenes.

**Comment by abriening** [comment]
@trondhindenes I'm using the Parse-Args from lib/ansible/module_utils/powershell.ps1; this should be a psobject parsed with  ConvertFrom-Json. The values shouldn't need to be converted. Or are you trying to handle quoted "true" and "false" in the config?

**Comment by jhawkesworth** [comment]
Not looked at the code but I think the point is that even if
$params.skip_certificate_validation is set to "false" the if() test will
consider that true (because only an empty string would be false).

**Comment by abriening** [comment]
Rebased and added the ConvertTo-bool; will now support boolean, 1/0, "on", "yes", "true", "1"

**Comment by jhawkesworth** [comment]
Did a little testing on this this morning and is at least backwardly compatible
I confirm the requested revision have been made so I am happy to upvote this
@gregdek / @bcoca please
shipit

**Comment by gregdek** [comment]
Thanks @jhawkesworth and other reviews, and thanks @abriening for the PR. Marking for inclusion.

**Pull request merged**
