### PR TITLE
Adding the ability to associate eips with network interfaces on Amazon EC2

### PR DESCRIPTION
**Pull request by evanccnyc**
This works on my branch for adding and removing of all ips etc. Let me know what else needs to be done so it can be checked in.

### CODE REVIEW

**Comment by bcoca** [comment]
cc @lorin @bennojoy @defionscode

**Comment by evanccnyc** [comment]
Any update on getting this checked in?

**Comment by bcoca** [comment]
needs people to review it first

**Comment by evanccnyc** [comment]
@bcoca how can I get people to review it?

**Comment by bcoca** [comment]
cc @lorin @bennojoy @defionscode review ping

**Comment by lorin** [comment]
:+1:

**Comment by evanccnyc** [comment]
@bcoca Can we get it checked in?

**Comment by bennojoy** [comment]
Hi!

This has been merged in, and will also be included in the next major release.

If you or anyone else has any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:

https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code
Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by bennojoy** [comment]
https://github.com/ansible/ansible-modules-core/pull/1990 should provide this same funtionatly

**Pull request merged**
