### PR TITLE
use tuple even when pass in the single user parameter

### PR DESCRIPTION
**Pull request by l-hedgehog**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

mysql_user
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Deault w/o overrides
```
##### SUMMARY

use tuple even when pass in the single user parameter

See http://mysql-python.sourceforge.net/MySQLdb.html#some-examples,

> Why the tuple? Because the DB API requires you to pass in any parameters as a sequence. Due to the design of the parser, (max_price) is interpreted as using algebraic grouping and simply as max_price and not a tuple. Adding a comma, i.e. (max_price,) forces it to make a tuple.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @l-hedgehog. To the current maintainers, @Jmainguy please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @l-hedgehog for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by l-hedgehog** [comment]
So I was really trying to solve the same issue as #3038.

I updated my PR since I think it's somewhat more "correct" to create one element tuple with `(user,)`.

**Comment by l-hedgehog** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @l-hedgehog. To the current maintainers, @Jmainguy please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by l-hedgehog** [comment]
Considering this is the exact same fix with @oscherler 's #3594, I'll close mine.

**Comment by Jmainguy** [comment]
Sorry about the delay @l-hedgehog, thank you for contributing and I will do my best to respond to these requests quicker in the future.

**Pull request closed without merging**
