### PR TITLE
ansible_facts reflects 1.8 output

### PR DESCRIPTION
**Pull request by andrewgdavis**

### CODE REVIEW

**Comment by bcoca** [comment]
??

**Comment by andrewgdavis** [comment]
the output of ansible_facts changed between versions.  the one line change provided the data in the same manner 1.8 did.

The relevant history:
https://github.com/ansible/ansible-modules-core/issues/1005

The solution put in place-- but the behavior changed between versions:
https://github.com/ansible/ansible-modules-core/pull/1039

I don't know what the direction is of the future "docker_facts" module so that may supercede my fix.  Until then, the one line change may help someone.

**Comment by ritterwolf** [comment]
I quickly tested this against a playbook that fails under 1.9, and it works for me.

**Comment by gimoh** [comment]
This isn't a complete fix, in 1.8.4 `docker_containers` included inspect data for all matched or running containers, not only the ones where state changed.  See [my comment on #1005](https://github.com/ansible/ansible-modules-core/issues/1005#issuecomment-99393219).

**Comment by gregdek** [comment]
@ansible/docker Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please give it a +1; at that point, we will add the “priority_reviewed” flag to this PR, which will move it to the top of our queue for potential inclusion.

**Pull request merged**
