### PR TITLE
Support changing an OpenStack Keystone user's password

### PR DESCRIPTION
**Pull request by gwsapan**
This change updates the keystone_user module to be able to update a user's password to a new one, rather than silently ignoring such a change.

### CODE REVIEW

**Comment by gwsapan** [comment]
Fixed an unassigned variable error in the original changeset by reverting it, and recommitting it. The change is now fully contained in commit 7f0787edb7ea751a46e1bc6dad8c2cf516098c86.

**Comment by gregdek** [comment]
@emonty feedback please :)

**Comment by gregdek** [comment]
@emonty another friendly ping for your thoughts here.

**Comment by emonty** [comment]
I need to look at this one on my laptop ... 
On Jul 23, 2015 2:05 PM, Greg DeKoenigsberg notifications@github.com wrote:@emonty another friendly ping for your thoughts here.

**Comment by emonty** [comment]
This needs a rebase. But also - there are two unrelated changes - the nova and quantum modules - that should not be in this. Other than that, seems sane enough to me.

**Comment by gregdek** [comment]
@gwsapan Thanks for submitting this pull request. Unfortunately, it appears that the underlying code has changed since your submission, and this PR now needs to be rebased. 

If you believe that this PR still applies, please rebase and we will put it into our community review process as soon as possible. 

Once you have rebased this PR, please add a comment with the text "ready_for_review" and we will continue with the review process.  Thanks!

**Comment by gwsapan** [comment]
Will do next week. Thanks.

**Comment by gregdek** [comment]
Thanks @gwsapan for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

**Comment by gregdek** [comment]
Closing due to bitrot and inactivity.

**Pull request closed without merging**
