### PR TITLE
Fixed an issue with unarchive using the ansible temporty directory

### PR DESCRIPTION
**Pull request by gregsidelinger**
Here is my simple fix for issue #2708 which I reported a few days ago.  The unarchive module now creates it's own temp directory when needing to download the file instead of using the directory the module is running out of.  The cleanup of the temporary dir most likely should be handled in a cleaner way as I'm sure there are a few cases where it could be left around.

### CODE REVIEW

**Comment by robynbergeron** [comment]
Thanks @gregsidelinger. @pileofrogs please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by pileofrogs** [comment]
shipit

Looks good.  Thanks!

**Comment by gregdek** [comment]
Thanks again to @gregsidelinger for this PR, and thanks @pileofrogs for reviewing. Marking for inclusion.

**Comment by bcoca** [comment]
this changes the current behavior w/o any of it being apparent to the user, in any case this might need a more generic fix if become + temp files are in play.

**Comment by robynbergeron** [comment]
@gregsidelinger Looks like @bcoca thinks this needs_revision -- marking as such. 

@pileofrogs -- just pinging as an FYI to you on this, in case you have any thoughts.

**Comment by robynbergeron** [comment]
@gregsidelinger -- when this is ready for review, please let us know using the ready_for_review comment, and should probably ping @bcoca as well so he knows to take a look as he had the revision request.

**Comment by gregsidelinger** [comment]
@bcoca can you give some details on your issues with the patch.  I actually though it was the cleanest way to get around the issue as it did not require a bunch of extra logic.

However I was thinking of adding a new option to the module that would let you specify the tempory location to download the file to.  That way the current behavior could be maintained and users could specify the location if needed.   

Here is the description of the option as I'm thinking of it.

```
  tmp_path:
    description:
      - If copy=no and src contains :// the location the file will be downloaded to before being unarchived. The file will be removed after it's unarchived.
      - tmp_path supports two special values which will pick location for you. 'ansible_tmp' will use the ansible temp directory while 'os_tmp' will use the standard OS tmp location as returned by a call to mkdtemp.
    required: false
    default: "ansible_tmp"
    version_added: "2.0"
```

**Comment by gregdek** [comment]
Thanks @gregsidelinger for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

**Comment by gregdek** [comment]
Thanks @gregsidelinger. @nitzmahone please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
OK, so something very bad has happened with this PR, as it has 156 file changes and 250+ commits in it -- and since it seemed like @bcoca was giving it a -1 anyway, I'm going to close this and recommend you create a new PR.

**Pull request closed without merging**
