### PR TITLE
Fix azure.py, "ResetPasswordOnFirstLogon parameter is deprecated"

### PR DESCRIPTION
**Pull request by tksarah**
#2245

Hello, this is a fix for issue 2245 I reported on 11 Oct.
I was fixed so that it does not use "reset_pass_atlogon" parameter because it is deprecated.
I deleted to fix some codes to relate "ResetPasswordOnFirstLogon".

My test environment below;
Ansible version : ansible2.0.0-0.7.rc2
Ansible Host OS : Ubuntu 14.04 x86_64
Python azure module : 1.0.2

### CODE REVIEW

**Comment by robynbergeron** [comment]
Thanks @tksarah. @jwhitbeck please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by tksarah** [comment]
Hello, @robynbergeron @gregdek 

I received an email from John Whitbeck below.

"Unfortunately I haven't used the azure module for a very long time so I
don't feel like I could give a meaningful code review at this point."

Therefore Could you add other reviewers?

**Comment by gregdek** [comment]
(untagging so the bot will reassign with new maintainer)

**Comment by nitzmahone** [comment]
Thanks for the fix!

**Pull request merged**
