### PR TITLE
fix #9983, wait_for: fail with error if port and path missing

### PR DESCRIPTION
**Pull request by halberom**
If neither port or path are specified, wait_for enters the `while datetime.datetime.now() < end:` loop, not performing any action until the designated timeout, when it will exit ok.

tested fix with the vagrant ansible provisioner

play

```

---
- hosts: all
  remote_user: vagrant
  tasks:
  - wait_for: path=/tmp state=present timeout=30
    register: result
  - debug: var=result

  - wait_for: port=22 host=0.0.0.0 state=present timeout=30
    register: result
  - debug: var=result

  - wait_for: state=present timeout=30
    register: result
  - debug: var=result
```

current

```
==> default: Running provisioner: ansible...
PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=true ANSIBLE_HOST_KEY_CHECKING=false ANSIBLE_SSH_ARGS='-o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=60s' ansible-playbook --private-key=/Users/glynch/vagrant/centos/.vagrant/machines/default/virtualbox/private_key --user=vagrant --connection=ssh --limit='default' --inventory-file=/Users/glynch/vagrant/centos/.vagrant/provisioners/ansible/inventory play.yml

PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [default]

TASK: [wait_for path=/tmp state=present timeout=30] *************************** 
ok: [default]

TASK: [debug var=result] ****************************************************** 
ok: [default] => {
    "var": {
        "result": {
            "changed": false, 
            "elapsed": 0, 
            "gid": 0, 
            "group": "root", 
            "invocation": {
                "module_args": "path=/tmp state=present timeout=30", 
                "module_name": "wait_for"
            }, 
            "mode": "01777", 
            "owner": "root", 
            "path": "/tmp", 
            "port": null, 
            "search_regex": null, 
            "size": 4096, 
            "state": "directory", 
            "uid": 0
        }
    }
}

TASK: [wait_for port=22 host=0.0.0.0 state=present timeout=30] **************** 
ok: [default]

TASK: [debug var=result] ****************************************************** 
ok: [default] => {
    "var": {
        "result": {
            "changed": false, 
            "elapsed": 0, 
            "invocation": {
                "module_args": "port=22 host=0.0.0.0 state=present timeout=30", 
                "module_name": "wait_for"
            }, 
            "path": null, 
            "port": 22, 
            "search_regex": null, 
            "state": "present"
        }
    }
}

TASK: [wait_for state=present timeout=30] ************************************* 
ok: [default]

TASK: [debug var=result] ****************************************************** 
ok: [default] => {
    "var": {
        "result": {
            "changed": false, 
            "elapsed": 30, 
            "invocation": {
                "module_args": "state=present timeout=30", 
                "module_name": "wait_for"
            }, 
            "path": null, 
            "port": null, 
            "search_regex": null, 
            "state": "present"
        }
    }
}

PLAY RECAP ******************************************************************** 
default                    : ok=7    changed=0    unreachable=0    failed=0   
```

After code change

```
==> default: Running provisioner: ansible...
PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=true ANSIBLE_HOST_KEY_CHECKING=false ANSIBLE_SSH_ARGS='-o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=60s' ansible-playbook --private-key=/Users/glynch/vagrant/centos/.vagrant/machines/default/virtualbox/private_key --user=vagrant --connection=ssh --limit='default' --inventory-file=/Users/glynch/vagrant/centos/.vagrant/provisioners/ansible/inventory play.yml

PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [default]

TASK: [wait_for path=/tmp state=present timeout=30] *************************** 
ok: [default]

TASK: [debug var=result] ****************************************************** 
ok: [default] => {
    "var": {
        "result": {
            "changed": false, 
            "elapsed": 0, 
            "gid": 0, 
            "group": "root", 
            "invocation": {
                "module_args": "path=/tmp state=present timeout=30", 
                "module_name": "wait_for"
            }, 
            "mode": "01777", 
            "owner": "root", 
            "path": "/tmp", 
            "port": null, 
            "search_regex": null, 
            "size": 4096, 
            "state": "directory", 
            "uid": 0
        }
    }
}

TASK: [wait_for port=22 host=0.0.0.0 state=present timeout=30] **************** 
ok: [default]

TASK: [debug var=result] ****************************************************** 
ok: [default] => {
    "var": {
        "result": {
            "changed": false, 
            "elapsed": 0, 
            "invocation": {
                "module_args": "port=22 host=0.0.0.0 state=present timeout=30", 
                "module_name": "wait_for"
            }, 
            "path": null, 
            "port": 22, 
            "search_regex": null, 
            "state": "present"
        }
    }
}

TASK: [wait_for state=present timeout=30] ************************************* 
failed: [default] => {"failed": true}
msg: either the port or path parameter must be passed to wait_for

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/Users/glynch/play.retry

default                    : ok=5    changed=0    unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

### CODE REVIEW

**Comment by bcoca** [comment]
isn't this a feature for those that just want to wait for a specific amount of time (sleep)?

**Comment by halberom** [comment]
Don't think so - there is http://docs.ansible.com/pause_module.html

**Comment by halberom** [comment]
Mind you if people are using it for that purpose, it would certainly ~~break their functionality~~ disrupt their existing playbooks.  I could update the error output to suggest the pause module.

**Comment by halberom** [comment]
I guess this is one of those 'people may be using a possibly unintended "feature" of the module' - so maybe just a note recommending the pause module instead of using wait_for timeout.  Have a think and let me know your preference.  Cheers.

**Comment by bcoca** [comment]
actually they have a different effect, pause affects the whole play and bypasses the host loop, wait_for is per host. It will become even more relevant in v2 when you can run tasks in free form (vs lockstep as they are now).

I would opt for documenting the behavior vs removing it.

**Comment by alxgu** [comment]
I ran into this "trap" and opened a bug report https://github.com/ansible/ansible-modules-core/issues/400
:+1:  for the PR

**Comment by halberom** [comment]
@bcoca ack'd, will review and update

**Pull request closed without merging**
