### PR TITLE
Improve the unzip output scraping

### LINKED ISSUE #3788: unarchive seems to fail on contents with special characters in their name on zip (Ansible 2.1)
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

unarchive
##### ANSIBLE VERSION

```
~/projects/isd/pp-onlyBarrys-MacBook-Pro ansible --version
ansible 2.1.0.0
  config file = /Users/barry/projects/isd/pp-only/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

```
[defaults]
roles_path = ../
remote_tmp = /tmp/ansible/

[ssh_connection]
pipelining = True
control_path = /tmp/ansible-ssh-%%h-%%p-%%r
```
##### OS / ENVIRONMENT

Running from Mac OS X El Capitan -> CentOS 7
##### SUMMARY

Ever since updating to Ansible 2.1 unarchive doesn't work for a specific JBoss EAP 6.4.0 zip file.
It would seem that it skips unarchiving files with spaces, or other special characters.

After running rsync on the target server to determine which files were not unpacked, I got the following:

```
jboss-eap-6.4/docs/licenses/apache software license, version 2.0 - apache-2.0.txt
jboss-eap-6.4/docs/licenses/common development and distribution license - cddl.txt
jboss-eap-6.4/docs/licenses/common public license, version 1.0 - cpl-1.0.txt
jboss-eap-6.4/docs/licenses/eclipse distribution license, version 1.0 - edl-1.0.txt
jboss-eap-6.4/docs/licenses/eclipse public license, version 1.0 - epl-1.0.txt
jboss-eap-6.4/docs/licenses/gnu general public license, version 2 - gpl-2.0.txt
jboss-eap-6.4/docs/licenses/gnu general public license, version 2 with the classpath exception - gpl-2.0-ce.txt
jboss-eap-6.4/docs/licenses/gnu lesser general public license, version 2.1 - lgpl-2.1.txt
jboss-eap-6.4/docs/licenses/gnu library general public license, version 2 - lgpl-2.0.txt
jboss-eap-6.4/docs/licenses/h2 license, version 1.0 - h2.txt
jboss-eap-6.4/docs/licenses/jdom license - jdom-1.0.txt
jboss-eap-6.4/docs/licenses/mozilla public license, version 1.1 - mpl-1.1.txt
jboss-eap-6.4/docs/licenses/the bsd license - bsd.txt
jboss-eap-6.4/docs/licenses/the jython license - license.html
jboss-eap-6.4/docs/licenses/the mit license - mit.txt
jboss-eap-6.4/docs/licenses/the werken company license - license.html
jboss-eap-6.4/docs/licenses/w3c software notice and license - w3c.txt
```

These files were in the zip, but not unpacked.

The only files correctly unpacked:

```
~/projects/isd/pp-onlyBarrys-MacBook-Pro vagrant ssh -c "ls -tral /tmp/licenses/"
-rw-rw-r--.  1 vagrant vagrant 2809 Mar 27  2015 osgi-1.0.txt
-rw-rw-r--.  1 vagrant vagrant  328 Mar 27  2015 jcip-cc-by-2.5.txt

```
##### STEPS TO REPRODUCE

I'm using an empty Vagrant box (geerlingguy/centos7). Use the attached zip file (it contains the license folder from JBoss EAP, which triggered this issue for me)
[licenses.zip](https://github.com/ansible/ansible-modules-core/files/289138/licenses.zip)

Run the following Ad-Hoc command to reproduce:

ansible -i .vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory all -m unarchive -a "src=~/licenses.zip dest=/tmp/" -vvvv

I've also included a very simple test which does work:

[test-simple.zip](https://github.com/ansible/ansible-modules-core/files/289166/test-simple.zip)
##### EXPECTED RESULTS

I'd like unarchive to work on these kinds of files again :)
##### ACTUAL RESULTS

```
~/projects/isd/pp-onlyBarrys-MacBook-Pro ansible -i .vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory all -m unarchive -a "src=~/licenses.zip dest=/tmp/" -vvvv
Using /Users/barry/projects/isd/pp-only/ansible.cfg as config file
Loaded callback minimal of type stdout, v2.0
<127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: vagrant
<127.0.0.1> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o Port=2200 -o 'IdentityFile="/Users/barry/projects/isd/pp-only/.vagrant/machines/pp/virtualbox/private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=10 -o ControlPath=/tmp/ansible-ssh-%h-%p-%r 127.0.0.1 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /tmp/ansible/ansible-tmp-1464596341.4-227141540631675 `" && echo ansible-tmp-1464596341.4-227141540631675="` echo /tmp/ansible/ansible-tmp-1464596341.4-227141540631675 `" ) && sleep 0'"'"''
<127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: vagrant
<127.0.0.1> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o Port=2200 -o 'IdentityFile="/Users/barry/projects/isd/pp-only/.vagrant/machines/pp/virtualbox/private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=10 -o ControlPath=/tmp/ansible-ssh-%h-%p-%r 127.0.0.1 '/bin/sh -c '"'"'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python && sleep 0'"'"''
<127.0.0.1> PUT /Users/barry/licenses.zip TO /tmp/ansible/ansible-tmp-1464596341.4-227141540631675/source
<127.0.0.1> SSH: EXEC sftp -b - -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o Port=2200 -o 'IdentityFile="/Users/barry/projects/isd/pp-only/.vagrant/machines/pp/virtualbox/private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=10 -o ControlPath=/tmp/ansible-ssh-%h-%p-%r '[127.0.0.1]'
<127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: vagrant
<127.0.0.1> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o Port=2200 -o 'IdentityFile="/Users/barry/projects/isd/pp-only/.vagrant/machines/pp/virtualbox/private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=10 -o ControlPath=/tmp/ansible-ssh-%h-%p-%r 127.0.0.1 '/bin/sh -c '"'"'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python && sleep 0'"'"''
<127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: vagrant
<127.0.0.1> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o Port=2200 -o 'IdentityFile="/Users/barry/projects/isd/pp-only/.vagrant/machines/pp/virtualbox/private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=10 -o ControlPath=/tmp/ansible-ssh-%h-%p-%r 127.0.0.1 '/bin/sh -c '"'"'rm -f -r /tmp/ansible/ansible-tmp-1464596341.4-227141540631675/ > /dev/null 2>&1 && sleep 0'"'"''
pp | FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "backup": null,
            "content": null,
            "copy": true,
            "creates": null,
            "delimiter": null,
            "dest": "/tmp/",
            "directory_mode": null,
            "exclude": [],
            "extra_opts": [],
            "follow": false,
            "force": null,
            "group": null,
            "keep_newer": false,
            "list_files": false,
            "mode": null,
            "original_basename": "licenses.zip",
            "owner": null,
            "regexp": null,
            "remote_src": null,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": "/tmp/ansible/ansible-tmp-1464596341.4-227141540631675/source"
        }
    },
    "msg": "path /tmp/licenses/common public license, version 1.0 - cpl-1.0.txt does not exist",
    "path": "/tmp/licenses/common public license, version 1.0 - cpl-1.0.txt",
    "state": "absent"
}
```

Example of zip file that is unarchived correctly:

```
~/projects/isd/pp-onlyBarrys-MacBook-Pro ansible -i .vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory all -m unarchive -a "src=~/test-simple.zip dest=/tmp/"
pp | SUCCESS => {
    "changed": true,
    "dest": "/tmp/",
    "extract_results": {
        "cmd": "/usr/bin/unzip -o \"/tmp/ansible/ansible-tmp-1464597052.87-106526549435190/source\" \"test-simple.txt\" -d \"/tmp/\"",
        "err": "",
        "out": "Archive:  /tmp/ansible/ansible-tmp-1464597052.87-106526549435190/source\n extracting: /tmp/test-simple.txt    \n",
        "rc": 0
    },
    "gid": 0,
    "group": "root",
    "handler": "ZipArchive",
    "mode": "01777",
    "owner": "root",
    "secontext": "system_u:object_r:tmp_t:s0",
    "size": 4096,
    "src": "/tmp/ansible/ansible-tmp-1464597052.87-106526549435190/source",
    "state": "directory",
    "uid": 0
}
```

### PR DESCRIPTION
**Pull request by dagwieers**
##### ISSUE TYPE

- Bugfix Pull Request
##### COMPONENT NAME

unarchive
##### SUMMARY

Ensure we capture the complete file (also when it includes spaces).
Drop lines that do not conform (in length) to what we expect (e.g. header/footer).

This fixes #3788, #3792, #3813, #3905 and ansible/ansible#16060

### CODE REVIEW

**Comment by dagwieers** [comment]
shipit

**Comment by gregdek** [comment]
Thanks @dagwieers. Since you are one of the maintainers (@dagwieers, @pileofrogs) of this module and you commented with "shipit", we are marking this PR for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by dagwieers** [comment]
shipit

**Comment by dagwieers** [comment]
@bcoca @abadger Please include this as part of v2.1.1, because more people are reporting duplicate issues.

**Comment by bcoca** [comment]
cherry picked to stable-2.1

**Comment by dagwieers** [comment]
Thanks !

**Pull request merged**
