### PR TITLE
reconcile usage of aws access key & secret key with aws_connect_kwargs f...

### LINKED ISSUE #1022: s3 module usage yields error => aws_access_key and aws_secret_key undefined.
Missed some s3 usage conditions in the shift to aws_connect_kwargs to support STS tokens, this is currently causing s3 usage to fail in some conditions:

https://github.com/ansible/ansible-modules-core/commit/64a2077787904f144f77839660071f35f25d181f#commitcomment-10455189

### PR DESCRIPTION
**Pull request by semifocused**
...or remaining s3 usage conditions

Fixes https://github.com/ansible/ansible-modules-core/issues/1022

### CODE REVIEW

**Comment by DMarby** [comment]
Looks good to me

**Comment by bcoca** [comment]
needs rebase

**Comment by semifocused** [comment]
Rebased and resolved conflict with recent commit.  Sent a line comment https://github.com/defionscode/ansible-modules-core/commit/611165a77eee80162f20643f7b0ab4e2f10d17f1 to the author.  Review appreciated.

**Comment by bcoca** [comment]
seems you have extra commits in the branch

**Comment by semifocused** [comment]
@bcoca - sorry about that, I've created a clean rebase on a new branch, will close this PR and let's move over to https://github.com/ansible/ansible-modules-core/pull/1029

**Pull request closed without merging**
