### PR TITLE
authorized_key: support --diff

### PR DESCRIPTION
**Pull request by mgedmin**
### Test plan

``` yml
# test.yml

---
- hosts: localhost
  gather_facts: no
  vars:
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    user: "{{ ansible_user }}"
  tasks:
    - authorized_key: path=./auth_keys key="{{ key }}" user="{{ user }}"
```

```
$ ansible-playbook -i localhost, test.yml -CD
$ ansible-playbook -i localhost, test.yml -D
```
### Expected output

```
PLAY [localhost] ***************************************************************

TASK [authorized_key] **********************************************************
--- before: ./auth_keys
+++ after: ./auth_keys
@@ -0,0 +1 @@
+ssh-rsa AAAA.....

changed: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0   
```

### CODE REVIEW

**Comment by robynbergeron** [comment]
Thanks @mgedmin for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

**Comment by gregdek** [comment]
Thanks @mgedmin for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by mgedmin** [comment]
Rebased!

ready_for_review

**Comment by gregdek** [comment]
Thanks @mgedmin for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @mgedmin for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by mgedmin** [comment]
Rebased.

ready_for_review

**Comment by gregdek** [comment]
Thanks @mgedmin for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @mgedmin for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by mgedmin** [comment]
Rebased (for the 3rd time)!

~~ready_for_review~~

EDIT: welp, rebased on my outdated local copy of `devel` rather than upstream `devel`, please hold a sec.

**Comment by mgedmin** [comment]
Rebased (correctly this time).

I also split the patch into smaller commits for easier review (hint, hint).

ready_for_review

**Comment by gregdek** [comment]
Thanks @mgedmin for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @mgedmin for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by mgedmin** [comment]
Rebased (for the 4th time)!

ready_for_review

**Comment by gregdek** [comment]
Thanks @mgedmin for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Review by chrrrles — COMMENTED** [review]
Tested +1

**Comment by edgarsj** [comment]
+1

**Comment by mgedmin** [comment]
Migrated to https://github.com/ansible/ansible/pull/19277 with https://prmover.pythonanywhere.com/
(I hoped it would add a comment mentioning the new URL to this PR automatically, but apparently it only closes old PRs and doesn't link to new ones.)

(EDIT: I'm not very observant -- it mentions the old PR in the comment of the new PR, which makes GitHub add a mention here.  Still, mentions aren't as easy to see as comments.)

**Pull request closed without merging**
