### PR TITLE
Unify all 3 modules.

### PR DESCRIPTION
**Pull request by Jmainguy**
Use same connection method, use config_file, and add ssl support

### CODE REVIEW

**Comment by willthames** [comment]
Nice, I like the improvements, seems much more elegant. I wonder if it's worth having a shared `module_utils/mysql.py` that has the connect bit in it.

**Comment by gregdek** [comment]
My only concern is that the modules have different maintainers currently -- @marktheunissen and @banyek.  I will ping them for review, but it might take a while to coordinate.

It might also be useful to have additional maintainers.

It might also, as @willthames said, be useful to have a shared module_utils for this.

**Comment by gregdek** [comment]
Anyway, putting into community review. 

@marktheunissen @banyek Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by bcoca** [comment]
+1 for putting the shared code into module_utils/mysql.py

**Comment by banyek** [comment]
+1 for sharing shared code

**Comment by Jmainguy** [comment]
@gregdek Mark @marktheunissen does not seem to enjoy being the maintainer.  #2365 removes him from the author field to avoid confusion, and of course maintains him as the copyright holder. 

That being said, @willthames @banyek @bcoca Would you like me to tackle placing it in shared code mysql.py (good idea) as part of this PR, or move that into a separate one.

**Comment by bcoca** [comment]
I think it would make this PR simpler (though depending on PR on core). But I won't stop this if you don't have the time right now as it does fix/normalize the modules.

**Comment by Jmainguy** [comment]
Nah that sounds good. I will take a stab at placing connect code into mysql.py and having the three modules call that. Will update PR when I got that ready.

**Comment by Jmainguy** [comment]
@bcoca @willthames @banyek added shared code PR above.

**Comment by tersmitten** [comment]
Great work! We wanted to do this for a long time, but didn't find the time.

We still have some unmerged mysql bugfixes, maybe they can be incorporated too? That will save some testing time.

**Comment by tersmitten** [comment]
https://github.com/ansible/ansible-modules-core/pull/2170

**Comment by Jmainguy** [comment]
Updated to use unified documentation for shared code. Makes it easier to update as needed, dependent on https://github.com/ansible/ansible/issues/13191 getting merged.

**Comment by marktheunissen** [comment]
I am no longer the maintainer, as per https://github.com/ansible/ansible-modules-core/pull/2653

**Comment by gregdek** [comment]
Thanks @Jmainguy for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

**Comment by Jmainguy** [comment]
@gregdek 'ready_for_review'

**Comment by gregdek** [comment]
Thanks @Jmainguy. @banyek please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
Thanks @Jmainguy. @banyek please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by willthames** [comment]
@Jmainguy wonder if there's a further reuse opportunity by creating and using a `mysql_argument_spec` (see similar `ec2_argument_spec`) that can then be extended by each module in turn.

For me though, this passes_guidelines

**Comment by gregdek** [comment]
Thanks @Jmainguy for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

**Comment by Jmainguy** [comment]
@gregdek ready_for_review

no spaces or anything =)

**Comment by gregdek** [comment]
Thanks @Jmainguy. @banyek please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
Thanks @Jmainguy. @banyek please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by abadger** [comment]
Refactor merged

**Pull request merged**
