### PR TITLE
Add rebuild to os_server_actions

### PR DESCRIPTION
**Pull request by cantorek**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

cloud/openstack/os_server_actions
##### ANSIBLE VERSION

```
ansible 2.0.2.0
  config file =
  configured module search path = Default w/o overrides
```
##### SUMMARY

This is to ease the server rebuild, so you can use it in ansible playbooks for easy re-roll of existing instances.
Rebuild is faster and more elegant than destroying and creating new machine.
Image name along with server is needed to perform a rebuild.

Please let me know if you find this module not appropriate for rebuild action and I will create a new module just for it or I'll put it wherever you want.

Thanks,
Oskar

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @cantorek. To the current maintainers, @emonty, @shrews, @juliakreger, @j2sol, @rcarrillocruz please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by rcarrillocruz** [comment]
I'm afraid there was already a PR for this:

https://github.com/ansible/ansible-modules-core/pull/4289

**Comment by cantorek** [comment]
-_-

Thanks, somehow I've missed that.
I guess you can reject this one or merge diff when (if) #4289 gets merged.

**Comment by gregdek** [comment]
Thanks @cantorek for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by cantorek** [comment]
Closing since  #4289 got merged.

**Pull request closed without merging**
