### PR TITLE
rhn_channel: channel.software.setSystemChannels is depreciated

### LINKED ISSUE #112: rhn_channel is using depreciated methods
Issue Type:
Bug Report

Ansible Version: 
1.7.2

Environment: 
OS X 10.9 / RHEL 6/7

Summary:
When adding a child channel to rhn sat server rhn_channel fails with 500 error. 

Steps To Reproduce:
attempt to subscribe to a child channel with rhn_channel to sat server 5.4+

Expected Results:
Server gets subscribed to child channel.

Actual Results:
xmlrpclib.ProtocolError: <ProtocolError for redhat.example.com/rpc/api: 500 Internal Server Error>

channel.software.setSystemChannels is depreciated. 
https://access.redhat.com/documentation/en-US/Red_Hat_Network_Satellite/5.5/html/API_Overview/files/html/handlers/ChannelSoftwareHandler.html#setSystemChannels

PR to follow

### PR DESCRIPTION
**Pull request by whereismyjetpack**
Fixes #112 replace channel.software.setSystemChannels with system.setChildChannels. Looks like channel.software.setSystemChannels has been depreciated for some time. tested on RHN sat server 5.5

### CODE REVIEW

**Comment by ghost** [comment]
Thanks a lot for this fix.

**Comment by whereismyjetpack** [comment]
No problem. Let me know if you run into issues!

**Comment by dekimsey** [comment]
When is this getting merged?

**Comment by bcoca** [comment]
this requires a rebase first.

**Comment by whereismyjetpack** [comment]
@bcoca , let me know if you need anything else. Thanks!

**Comment by bcoca** [comment]
your rebase contains some ec2 plugin changes, please correct

**Comment by whereismyjetpack** [comment]
Sorry, I'm a moron. I'll just resubmit when I get a free moment tomorrow

**Comment by whereismyjetpack** [comment]
sorry guys. I don't know what I did to create the PR with the ec2 plugin changes. i've resubmitted. hopefully this time I didn't totally ruin everything https://github.com/ansible/ansible-modules-core/pull/845

**Pull request closed without merging**
