### PR TITLE
WIP: Test PR, do not merge.

### PR DESCRIPTION
**Pull request by mattclay**
##### ISSUE TYPE

Feature Pull Request
##### COMPONENT NAME

ping
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel 9248cde239) last updated 2016/07/06 22:36:37 (GMT -700)
  lib/ansible/modules/core: (detached HEAD 37b7708c5d) last updated 2016/07/06 22:36:44 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD 0f01acd6c4) last updated 2016/07/06 14:59:45 (GMT -700)
  config file = /home/matt/.ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

Testing the new module integration tests, do not merge this change.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @mattclay. To the current maintainers, @grossws please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by grossws** [comment]
@mattclay, OK, I'll just ignore it =)

**Comment by grossws** [comment]
Or should I close it, @gregdek?

**Comment by mattclay** [comment]
I'll be using this PR to test more changes to our CI process. I'll close it when I'm finished.

**Comment by grossws** [comment]
Ok, got it

**Comment by gregdek** [comment]
This PR is a work-in-progress. @mattclay, when you're ready to have this PR reviewed, please remove WIP from the title of the PR.

**Comment by mattclay** [comment]
Done testing module PRs, closing.

**Pull request closed without merging**
