### PR TITLE
adds the option to pass security groups by name to ec2_elb_lb module

### PR DESCRIPTION
**Pull request by ghost**
Adds a simple security_group_names option as an alternative to security_group_ids. You can specify one or the other, but not both at the same time.

### CODE REVIEW

**Comment by gregdek** [comment]
@jsdalton Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please give it a +1; at that point, we will add the “priority_reviewed” flag to this PR, which will move it to the top of our queue for potential inclusion.

**Comment by gregdek** [comment]
@rickmendes Sorry, looks like something has changed in the last couple of weeks and this now needs to be rebased.

**Comment by ghost** [comment]
@gregdek I resolved the conflicts. I was surprised to see some of my code was already on devel.

**Comment by ghost** [comment]
@gregdek Looks like someone else took my code and put it up in their PR a couple of months later. Check out commit 985cdf2c281c78a9f0861ed8c2f77752b3854812. Not good OSS etiquette.

**Comment by bcoca** [comment]
hmm, i'll check how that happened, in any case nothing left to add in this ticket (removes a blank line now) so I'm closing it.

**Comment by bcoca** [comment]
this was the pull request #1476

**Comment by gregdek** [comment]
@rickmendes looks like you're right. @bcoca has pointed out the proper behavior to the offending contributor. Sorry that we missed it; too many PRs in flight, I'm afraid. Happy to add you to the module as an author (and potential future reviewer) if you would be willing.

**Comment by ghost** [comment]
@gregdek I am happy to be a future reviewer and would like to be added as an author. Thanks.

@bcoca Thanks for reaching out to the offending developer.

**Comment by gregdek** [comment]
Thanks @rickmendes. Will add you in the next pass.

**Pull request closed without merging**
