### PR TITLE
APT: Add multiple packages inline + support Async

### PR DESCRIPTION
**Pull request by eloycoto**
Hi, 

If you want to use Async module in apt at the moment it's difficult. 

Async task are not compatible with loops, so my behaviour is to use multiple packages inline. I used this approach for pip as example. 

So, my idea is to use the following: 

``` task.yml
- name: Install deps
  apt:
    name: "git make ngrep"
    update_cache: yes
  async: 10000
  poll: 0
  register: apt_sleeper
```

So with this patch, the system will accept multiple packages, as apt-get install do. 

I've just check, and debian names can't be with space. So no exception it's expected. 

Thanks
Regards.

### CODE REVIEW

**Comment by jordanell** [comment]
:+1:

**Comment by eloycoto** [comment]
Hi, 

I [wrote a post in my blog](http://acalustra.com/acelerate-your-ansible-playbooks-with-async-tasks.html) about Async that it's related with this PR. Hope to help to understand. 

Regards.

**Comment by bcoca** [comment]
you really don't need this patch as a comma separated list would also be taken by the module

**Comment by bcoca** [comment]
also apt/yum and others have a with_ optimization, which bypasses the async limitation, so I'm going to close this as a non-issue.

**Comment by eloycoto** [comment]
Hi @bcoca,

I've just testing with commas and yes it's working, but without spaces. Like that: 

```
---
- hosts: 127.0.0.1
  connection: local
  vars:
    packages:
      - vim
      - zsh

  tasks:
  - name: APT with commas
    apt:
      name: "{{ ','.join(packages) }}"
      state: present
```

Thanks for your time, and sorry for invalid PR ;-)

**Pull request closed without merging**
