### PR TITLE
bugfixes for redhat_subscription

### PR DESCRIPTION
**Pull request by detiber**
- correctly return pool ids for newer versions of subscription-manager
- allow for managing subscriptions after initial registration.

### CODE REVIEW

**Comment by detiber** [comment]
This is for addressing both: https://github.com/ansible/ansible-modules-core/issues/422
and https://github.com/ansible/ansible-modules-core/issues/421

**Comment by detiber** [comment]
~~This is definitely rough around the edges, wanted to get some feedback on it before I started to dig in too deeply on it though.~~

**Comment by gregdek** [comment]
@jlaska Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please give it a +1; at that point, we will add the “priority_reviewed” flag to this PR, which will move it to the top of our queue for potential inclusion.

**Comment by jlaska** [comment]
@gregdek I'm unable to test the proposed changes, but by review they seem quite appropriate. 

@detiber The only suggestion I might offer is to update the examples included in the docstring to demonstrate some of the new capabilities/fixes.

With the proposed changed, :+1: from me.

**Comment by detiber** [comment]
@gregdek @jlaska Rebased, added a fix for the Travis CI failure,  and added an example for changing the consumed subscriptions (the only real feature added). I couldn't think of a way to document the fix for https://github.com/ansible/ansible-modules-core/issues/421, since it is just fixing an issue with a change in the output of subscription manager between versions.

**Comment by jlaska** [comment]
@detiber Looks good, thanks for your changes!

**Comment by abadger** [comment]
Thank @detiber  for the code and @jlaska for the review!

# Merged

Hi!

This has been merged in, and will also be included in the next major release.

If you or anyone else has any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Pull request merged**
