### PR TITLE
simpler way to check if systemd is the init system

### PR DESCRIPTION
**Pull request by reactormonk**
According to
http://www.freedesktop.org/software/systemd/man/sd_booted.html
check if the directory /run/systemd/system/ exists.

### CODE REVIEW

**Comment by gregdek** [comment]
@reactormonk Thanks for your pull request. This module is critical to Ansible's functionality, so it's owned by the Core team, and it can take a while for patches to be reviewed. Thanks for your patience here.

**Comment by bcoca** [comment]
is this applicable to older versions? most of our issues stem from how systemd has changed over time and made it hard to recognize, will it also work inside containers?

**Comment by reactormonk** [comment]
Yes it will work inside containers. The older version checks for cgroups, but has a false positive in case of containers. https://github.com/systemd/systemd/commit/66e4118

Explicit creation of `/run/systemd/system` in https://github.com/systemd/systemd/commit/3a90ae0 - the directory will also be implicity created after startup.

Earlier name: `/dev/.run/systemd/system`. https://github.com/systemd/systemd/commit/2b583ce6576d4a074ce6f1570b3e60b65c64ae7d

**Comment by eliasp** [comment]
SaltStack uses the same approach:

``` Python
            # This check does the same as sd_booted() from libsystemd-daemon:
            # http://www.freedesktop.org/software/systemd/man/sd_booted.html
            if os.stat('/run/systemd/system'):
                context['systemd.sd_booted'] = True
```

**Comment by reactormonk** [comment]
Exposing `sd_booted` as a fact would be nice, but I don't know how to do that.

**Comment by bcoca** [comment]
I"m going to merge this but I'm going to restore the other checks in case this one fails

**Pull request merged**
