### PR TITLE
system/user: add keep_shell option

### PR DESCRIPTION
**Pull request by billwanjohi**
Some users will set a preferred shell after creation.
This new option lets them keep it while still setting one for new users or those lacking one.

### CODE REVIEW

**Comment by gregdek** [comment]
@sfromm Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please give it a +1; at that point, we will add the “priority_reviewed” flag to this PR, which will move it to the top of our queue for potential inclusion.

**Comment by billwanjohi** [comment]
Any chance we could try a different reviewer?

**Comment by billwanjohi** [comment]
Rebased to keep up with devel.

**Comment by gregdek** [comment]
Thanks @billwanjohi for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

**Comment by billwanjohi** [comment]
@gregdek I rebased again, this is ready_for_review

**Comment by gregdek** [comment]
Thanks @billwanjohi. @sfromm please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
Thanks @billwanjohi. @sfromm please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by robynbergeron** [comment]
@ansible This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
Retagging for review by @ansible/core team. @billwanjohi thanks for your PR and your patience.

**Pull request closed without merging**
