### PR TITLE
Add doc for gce's return object

### PR DESCRIPTION
**Pull request by phanect**
Maybe we need "Return Values" sections on doc, but for now I added this in "Notes" section

### CODE REVIEW

**Comment by phanect** [comment]
The error on CI seems derived from current `devel` head [813053c](https://travis-ci.org/ansible/ansible-modules-core/builds/79919189).
I will rebase after the issue is fixed.

**Comment by phanect** [comment]
Error seems to be fixed and I rebased my fork.

**Comment by bcoca** [comment]
don't document this in the notes, use the RETURN_DOCS facility (check copy, stat or any of the cloud stack modules for examples)

**Comment by phanect** [comment]
@bcoca Oh, already there is parameter to state return values.

I rewrote partially. Above commit is in progress. I will rebase after I finished it.

**Comment by phanect** [comment]
@bcoca Sorry for late reply.
I found I may add wrong info because of lacking understanding for gce module.
Let me close this PR.

**Pull request closed without merging**
