### PR TITLE
Remove the neccesity of sizes when replace

### PR DESCRIPTION
**Pull request by dronjax**
##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME

ec2_asg module

##### ANSIBLE VERSION

```
ansible 2.1.2.0
```
##### SUMMARY

Remove the neccesity to provide min_size and desired_size when enabling replace_instance using this module.

```

```

Previously, you need to specify sizes when use replace instances.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @dragoon20 for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @dragoon20 for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by dronjax** [comment]
@gregdek I just rebased it

ready_for_review

**Comment by gregdek** [comment]
Thanks @dragoon20 for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
