### PR TITLE
nxos_interface

### PR DESCRIPTION
**Pull request by jedelman8**
##### ISSUE TYPE

- New Module Pull Request
##### COMPONENT NAME

nxos_interface
##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = xxx
```
##### SUMMARY

Idempotent module to manage interfaces on Nexus switches.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @jedelman8 for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by privateip** [comment]
missing version_added in docstring

**Comment by privateip** [comment]
Changes look good but please rebase your PR

**Comment by gregdek** [comment]
Thanks @jedelman8 for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by jedelman8** [comment]
ready_for_review

**Comment by privateip** [comment]
Your PR contains a merge commit.  You will need to back it out and rebase with the latest devel branch before we can accept your PR

**Comment by gregdek** [comment]
Thanks @jedelman8 for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
