### PR TITLE
Add virtualenv_python arg to pip module

### PR DESCRIPTION
**Pull request by wbolster**
See #586 for details.

### CODE REVIEW

**Comment by wbolster** [comment]
Note to reviewer: there's a FIXME value in the `versionadded` field that should be changed prior to merging.

**Comment by wbolster** [comment]
Is there anything I can do to move this forward? (and close #586)

/cc @bcoca

**Comment by bcoca** [comment]
@wbolster for one, this does not merge cleanly, after that i can only ask for patience as we go through the backlog

**Comment by wbolster** [comment]
Okay, I've updated this PR to apply cleanly against the current `devel` branch, which was updated in the mean time. No more merge conflicts now.

**Comment by gregdek** [comment]
@mattupstate please review; if you give +1 we will promote to P1_reviewed.

**Comment by mattupstate** [comment]
Is this not already supported by using the `command` option?

**Comment by gregdek** [comment]
@mattupstate Yes; that's actually addressed in #586.

**Comment by mattupstate** [comment]
@gregdek I don't understand how something can be addressed without a pull request.

**Comment by gregdek** [comment]
Sorry, didn't make myself clear.

Yes, there's an example for using the command option for doing this in issue #586. That's also where @wbolster provides the rationale for including this in the pip module directly.

**Comment by wbolster** [comment]
@mattupstate No, the `command` option specifies which `virtualenv` command to use. This PR is about adding support to the Ansible `pip` module for a flag that will translate to the `-p` option to `virtualenv`.The end result would be that something like `virtualenv -ppython3.4` is executed; the first part comes from the `command` option, and the second part from the proposed flag. See https://github.com/ansible/ansible-modules-core/issues/586#issuecomment-69732132 for a detailed explanation why this is needed.

**Comment by gregdek** [comment]
@mattupstate a friendly ping to weigh in on this PR when you can.

**Comment by mattupstate** [comment]
@gregdek It looks OK to me. And for future reference, I'm not super concerned about reviewing the modules I originally wrote. I contributed them when Ansible was first open sourced and things have changed quite a bit since then, so I'm not exactly the best person to review anymore.

**Pull request merged**
