### PR TITLE
Added sha256sum check to files downloaded by unarchive module.

### PR DESCRIPTION
**Pull request by lukehoersten**
This is similar functionality to get_url module and makes sense to be in unarchive with the new download functionally. Really simple addition here. Same code as get_url.

### CODE REVIEW

**Comment by abadger** [comment]
get_url in 2.0 will have a new checksum parameter and the sha256sum parameter will be deprecated.  Perhaps we want to use that functionality instead?

**Comment by lukehoersten** [comment]
Yeah we should make it match. I didn't see that in the code though. Is it on a branch other than devel?

**Comment by abadger** [comment]
Ah, I made a mistake - the checksum stuff isn't quite merged yet.  The pr
is here: https://github.com/ansible/ansible-modules-core/pull/141. Just a
few things left to do before that gets merged.

**Comment by muffl0n** [comment]
ansible/ansible#11840 has been merged, so you can use that functionality provided there.

**Comment by lukehoersten** [comment]
Great. I'll work on that today. Thanks.

**Comment by lukehoersten** [comment]
I doubt I'll get around to this any time soon. This PR is deprecated now anyway.

**Pull request closed without merging**
