### PR TITLE
Added support for accepting extra config options in vm reconfiguration.

### PR DESCRIPTION
**Pull request by chlam4**
##### ISSUE TYPE

- Feature Pull Request
- New Module Pull Request
- Bugfix Pull Request
- Docs Pull Request
##### ANSIBLE VERSION

```
<!--- Paste verbatim output from “ansible --version” between quotes -->
```
##### SUMMARY

```
<!--- Paste verbatim command output here, e.g. before and after your change -->
```

### CODE REVIEW

**Comment by resmo** [comment]
Thanks @chlam4. To the current maintainers, @chrrrles, @rhoop please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
Thanks again to @chlam4 for this PR, and thanks @chrrrles, @rhoop for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by resmo** [comment]
(cleared some bot comments as the bot was confused by my comments, sorry for the wrong messages)

**Comment by gregdek** [comment]
Thanks @chlam4. To the current maintainers, @chrrrles, @rhoop please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by chrrrles** [comment]
shipit

**Comment by chlam4** [comment]
Thanks @chrrrles @gregdek @resmo.  What will be the next step?  Is there anything I'm supposed to do now to move this forward?  Thanks again!

**Comment by resmo** [comment]
thanks again @chlam4 .

**Pull request merged**
