### PR TITLE
Remove 'str' type so that json is properly quoted

### PR DESCRIPTION
**Pull request by wimnat**

### CODE REVIEW

**Comment by wimnat** [comment]
@defionscode

**Comment by juliedavila** [comment]
What was this causing? Duplicate quotes?

**Comment by wimnat** [comment]
It would replace double quotes in my json file with single quotes, thus breaking the json

**Comment by juliedavila** [comment]
+1

Ah, weird it didn't come up earlier. Thanks

**Comment by gregdek** [comment]
Thanks @wimnat for the PR and thanks @defionscode for the review. Marking for inclusion.

cc: @ansible/core team.

**Pull request merged**
