### PR TITLE
deprecated _fact network modules: Rename in modules-core

### PR DESCRIPTION
**Pull request by gundalow**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

eos_template

### CODE REVIEW

**Comment by gundalow** [comment]
I need to work out why `ansible-validate-modules` is failing here but not in `ansible-modules-extras`
https://app.shippable.com/runs/57e1808113e4ac0f00db4cad/16/console

**Comment by gundalow** [comment]
Ah the reason modules-extras is working is because `asa_template` was added in 2.2. I wonder if we can just remove the modules as it hasn't made it into an official release.

I'll have a think about updating `ansible-validate-modules`

**Comment by gregdek** [comment]
This PR is a work-in-progress. @gundalow, when you're ready to have this PR reviewed, please remove WIP from the title of the PR.

**Comment by gundalow** [comment]
Fix to `ansible-validate-modules` is in https://github.com/sivel/ansible-testing/pull/36

**Comment by gundalow** [comment]
`ansible-validate-modules` has been updated and now correctly deals with deprecated modules.

ready_for_review

**Comment by gregdek** [comment]
Thanks @gundalow. To the current maintainers, @privateip, @gundalow, @jedelman8, @GGabriele, @privateip, @gundalow please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Review by Qalthos — APPROVED** [review]

**Comment by gregdek** [comment]
Thanks @gundalow for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gundalow** [comment]
Git mutter mutter. Re created as https://github.com/ansible/ansible-modules-core/pull/5072

**Pull request closed without merging**
