### PR TITLE
Enabling JSON for network/junos/junos_command.py #4103

### LINKED ISSUE #4103: Enable the use of JSON for junos_command
##### ISSUE TYPE

- Feature Idea
##### COMPONENT NAME

network/junos/junos_command.py
##### ANSIBLE VERSION

```
ansible 2.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

--- JUNOS 15.1R3.6 built 2016-03-24 18:40:35 UTC
##### SUMMARY

Enable format JSON for output from junos device running 14.2 or higher. 
From 14.2 onward, junos supports JSON
##### STEPS TO REPRODUCE

```
    - name: show version json
      junos_command:
        host: "{{ inventory_hostname }}"
        commands:
          - "show version"
        format: json
```

Results:

```
.......
"stdout": [{"multi-routing-engine-results": [{"multi-routing-engine-item": [{"re-name": [{"data": "fpc0"}], "software-information": [{"host-name": [{"data": "netlab-sw01-a"}], "junos-version": [{"data": "15.1R3.6"}], "package-information": [{"comment": [{"data": "JUNOS EX  Software Suite [15.1R3.6]"}], "name": [{"data": "junos"}]}, {"comment": [{"data": "JUNOS FIPS mode utilities [15.1R3.6]"}], "name": [{"data": "fips-mode-powerpc"}]}, {"comment": [{"data": "JUNOS Online Documentation [15.1R3.6]"}], "name": [{"data": "jdocs-ex"}]}, {"comment": [{"data": "JUNOS EX 4200 Software Suite [15.1R3.6]"}], "name": [{"data": "junos-ex-4200"}]}, {"comment": [{"data": "JUNOS Web Management Platform Package [15.1R3.6]"}], "name": [{"data": "jweb-ex"}]}], "product-model": [{"data": "ex4200-24t"}], "product-name": [{"data": "ex4200-24t"}]}]}]}]}], "stdout_lines": [{"multi-routing-engine-results": [{"multi-routing-engine-item": [{"re-name": [{"data": "fpc0"}], "software-information": [{"host-name": [{"data": "netlab-sw01-a"}], "junos-version": [{"data": "15.1R3.6"}], "package-information": [{"comment": [{"data": "JUNOS EX  Software Suite [15.1R3.6]"}], "name": [{"data": "junos"}]}, {"comment": [{"data": "JUNOS FIPS mode utilities [15.1R3.6]"}], "name": [{"data": "fips-mode-powerpc"}]}, {"comment": [{"data": "JUNOS Online Documentation [15.1R3.6]"}], "name": [{"data": "jdocs-ex"}]}, {"comment": [{"data": "JUNOS EX 4200 Software Suite [15.1R3.6]"}], "name": [{"data": "junos-ex-4200"}]}, {"comment": [{"data": "JUNOS Web Management Platform Package [15.1R3.6]"}], "name": [{"data": "jweb-ex"}]}], "product-model": [{"data": "ex4200-24t"}], "product-name": [{"data": "ex4200-24t"}]}]}]}]}]}
```

### PR DESCRIPTION
**Pull request by stianvi**
##### ISSUE TYPE

- Feature Pull Request
##### COMPONENT NAME

network/junos/junos_command.py
##### ANSIBLE VERSION

```
ansible 2.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

Just enabled JSON. This does not check the device version, this will be done in py-junos-eznc/device.py
Fixes #4103 

```
"stdout": [{"multi-routing-engine-results": [{"multi-routing-engine-item": [{"re-name": [{"data": "fpc0"}], "software-information": [{"host-name": [{"data": "netlab-sw01-a"}], "junos-version": [{"data": "15.1R3.6"}], "package-information": [{"comment": [{"data": "JUNOS EX  Software Suite [15.1R3.6]"}], "name": [{"data": "junos"}]}, {"comment": [{"data": "JUNOS FIPS mode utilities [15.1R3.6]"}], "name": [{"data": "fips-mode-powerpc"}]}, {"comment": [{"data": "JUNOS Online Documentation [15.1R3.6]"}], "name": [{"data": "jdocs-ex"}]}, {"comment": [{"data": "JUNOS EX 4200 Software Suite [15.1R3.6]"}], "name": [{"data": "junos-ex-4200"}]}, {"comment": [{"data": "JUNOS Web Management Platform Package [15.1R3.6]"}], "name": [{"data": "jweb-ex"}]}], "product-model": [{"data": "ex4200-24t"}], "product-name": [{"data": "ex4200-24t"}]}]}]}]}], "stdout_lines": [{"multi-routing-engine-results": [{"multi-routing-engine-item": [{"re-name": [{"data": "fpc0"}], "software-information": [{"host-name": [{"data": "netlab-sw01-a"}], "junos-version": [{"data": "15.1R3.6"}], "package-information": [{"comment": [{"data": "JUNOS EX  Software Suite [15.1R3.6]"}], "name": [{"data": "junos"}]}, {"comment": [{"data": "JUNOS FIPS mode utilities [15.1R3.6]"}], "name": [{"data": "fips-mode-powerpc"}]}, {"comment": [{"data": "JUNOS Online Documentation [15.1R3.6]"}], "name": [{"data": "jdocs-ex"}]}, {"comment": [{"data": "JUNOS EX 4200 Software Suite [15.1R3.6]"}], "name": [{"data": "junos-ex-4200"}]}, {"comment": [{"data": "JUNOS Web Management Platform Package [15.1R3.6]"}], "name": [{"data": "jweb-ex"}]}], "product-model": [{"data": "ex4200-24t"}], "product-name": [{"data": "ex4200-24t"}]}]}]}]}]}
```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @stianvi. To the current maintainers, @privateip please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gundalow** [comment]
Looks good to me, @privateip Can you please review & merge

**Comment by gregdek** [comment]
Thanks @stianvi for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gundalow** [comment]
Hi,

Looks like this branch needs updating, please see this guide on how to do that cleanly.

http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

**Comment by stianvi** [comment]
rebase fails due to changes to same file.

$ git rebase -i   devel
error: could not apply 3718d40... Enabling JSON #4103

with the following in rebase comment:
pick 3718d40 Enabling JSON #4103

**Comment by stianvi** [comment]
@gundalow rebase fixed in PR  #4715. Closing this.

**Pull request closed without merging**
