### PR TITLE
Fix multiple issues with unzip and gtar support

### LINKED ISSUE #2480: Add strip-component option in unarchive module
Please add  a `strip-component` or `strip-level` option in `unarchive` module ! :)

Thanks

### PR DESCRIPTION
**Pull request by dagwieers**
##### ISSUE TYPE

- Bugfix Pull Request
##### COMPONENT NAME

unarchive
##### SUMMARY

- Ensure that **extra_opts** works correctly with transformations
- Add the option `--show-transformed-names` when **extra_opts:** is being used
- Ignore bogus warnings related to empty filenames
- Properly quote _and_ escape filenames for unzip and gtar commands
- Rewrite gtar options and provide run_command with array, not string

This fixes #2480, #4109 and #4471.
- Check-mode was disabled for zip-files since gtar did not support it.

_This change enables check-mode support for zip-files (which was possible since the earlier rewrite to make it idempotent), but does skip the task when used with gtar. (Best of both worlds)_

This replaces PR #4401, the changes overlap somewhat so I merged them to make testing easier.

### CODE REVIEW

**Comment by dagwieers** [comment]
@abadger This one is a must-have as well (see discussion #2480).

**Comment by dagwieers** [comment]
shipit

**Comment by gregdek** [comment]
Thanks @dagwieers. Since you are one of the maintainers (@dagwieers, @pileofrogs) of this module and you commented with "shipit", we are marking this PR for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by dagwieers** [comment]
shipit

**Comment by dagwieers** [comment]
shipit

**Comment by erikdw** [comment]
@dagwieers : sorry, I failed to update within the PR itself... copying those comments here (I _hate_ git submodules BTW):

I would like to test, but these git submodules are beyond my current abilities. i.e., if I just wanted to use your branch I'm not sure how to do that in the git submodule -- I know how to it with regular git repos.

So I tried hand-copying your `unarchive.py` file from this PR, but then after I ran `source hacking/env-setup` and then tried my playbook I got this error:

```
ansible/lib/ansible/cli/__init__.py", line 27, in <module>
    import yaml
ImportError: No module named yaml
```

Notably, I don't get that error when I _don't_ have your `unarchive.py` hand-copied into my repo.

**Comment by erikdw** [comment]
Here's the test (result is running `ansible` from the HEAD of ansible git repo's devel branch, not with the proposed changes in this tarball, since I have been unable to figure out how to test them):

Set up tarball:

```
cd /tmp/
mkdir -p level1/level2/
touch level1/level2/file1
tar --{owner,group}=root -cvf level1.tgz level1
```

Run ansible `unarchive` module pointed at some host (`hostfoo` below):

```
% ansible -i hostfoo, -b -m unarchive -a "src=/tmp/level1.tgz dest=/tmp/ extra_opts='--strip-components=1'" all
hostfoo | FAILED! => {
    "changed": false, 
    "failed": true, 
    "msg": "Unexpected error when accessing exploded file: [Errno 2] No such file or directory: '/tmp/level1'"
}
```

Show that the `unarchive` module _did_ expand the tarball, it's just the validation that failed:

```
% ansible -i hostfoo, -m shell -a "find /tmp/level2" all                                                    
hostfoo | SUCCESS | rc=0 >>
/tmp/level2
/tmp/level2/file1
```

**Comment by dagwieers** [comment]
Here's my output:

```
[dag@moria ~]$ cd /tmp/
[dag@moria tmp]$ mkdir -p level1/level2/
[dag@moria tmp]$ touch level1/level2/file1
[dag@moria tmp]$ tar --{owner,group}=root -cvf level1.tgz level1
level1/
level1/level2/
level1/level2/file1
[dag@moria tmp]$ ansible -i localhost, -m unarchive -a "src=/tmp/level1.tgz dest=/tmp/ extra_opts='--strip-components=1'" all
localhost | SUCCESS => {
    "changed": true, 
    "check_results": {
        "cmd": "/bin/gtar -C \"/tmp/\" -d --show-stored-names --strip-components=1 -f \"/home/dag/.ansible/tmp/ansible-tmp-1468006895.04-207090464924809/source\"", 
        "err": "/bin/gtar: : Warning: Cannot stat: No such file or directory\n/bin/gtar: level2: Warning: Cannot stat: No such file or directory\n/bin/gtar: level2/file1: Warning: Cannot stat: No such file or directory\n", 
        "out": "/bin/gtar: : Warning: Cannot stat: No such file or directory\n/bin/gtar: level2: Warning: Cannot stat: No such file or directory\n/bin/gtar: level2/file1: Warning: Cannot stat: No such file or directory\n", 
        "rc": 1, 
        "unarchived": false
    }, 
    "dest": "/tmp/", 
    "extract_results": {
        "cmd": "/bin/gtar -C \"/tmp/\" -x --show-stored-names --strip-components=1 -f \"/home/dag/.ansible/tmp/ansible-tmp-1468006895.04-207090464924809/source\"", 
        "err": "", 
        "out": "", 
        "rc": 0
    }, 
    "gid": 10, 
    "group": "wheel", 
    "handler": "TarArchive", 
    "mode": "01777", 
    "owner": "root", 
    "secontext": "system_u:object_r:tmp_t:s0", 
    "size": 36864, 
    "src": "/home/dag/.ansible/tmp/ansible-tmp-1468006895.04-207090464924809/source", 
    "state": "directory", 
    "uid": 0
}
[dag@moria tmp]$ ls -la level2/
total 44
drwxrwxr-x.   2 dag  dag    4096 Jul  8 21:41 .
drwxrwxrwt. 278 root wheel 36864 Jul  8 21:41 ..
-rw-rw-r--.   1 dag  dag       0 Jul  8 21:41 file1
```

**Comment by dagwieers** [comment]
I don't think you are running the right module.

**Comment by erikdw** [comment]
@dagwieers : as I said, I cannot figure out how to test with your PR branch, because of the submodules.  If the test shows it working, then awesome, please merge away!

**Comment by erikdw** [comment]
Also, your test is insufficient.  It's using localhost where we've just created /tmp/level1, so the validation would work even if it really shouldn't have.  :)   Maybe use a different dir locally or use a remote host.

**Comment by dagwieers** [comment]
You can download the `unarchive.py` and put it in `library/`. The yaml error you got is really weird. You should have the python yaml library, otherwise ansible wouldn't work. Try: `python -c "import yaml"`

Here is the same test with the directory removed:

```
[dag@moria tmp]$ rm -rf level*
[dag@moria tmp]$ mkdir -p level1/level2/
touch level1/level2/file1
tar --{owner,group}=root -cvf level1.tgz level1[dag@moria tmp]$ touch level1/level2/file1
[dag@moria tmp]$ tar --{owner,group}=root -cvf level1.tgz level1
level1/
level1/level2/
level1/level2/file1
[dag@moria tmp]$ rm -rf level1
[dag@moria tmp]$ ansible -i localhost, -m unarchive -a "src=/tmp/level1.tgz dest=/tmp/ extra_opts='--strip-components=1'" all
localhost | SUCCESS => {
    "changed": true, 
    "check_results": {
        "cmd": "/bin/gtar -C \"/tmp/\" -d --show-stored-names --strip-components=1 -f \"/home/dag/.ansible/tmp/ansible-tmp-1468007428.08-131128388826272/source\"", 
        "err": "/bin/gtar: : Warning: Cannot stat: No such file or directory\n/bin/gtar: level2: Warning: Cannot stat: No such file or directory\n/bin/gtar: level2/file1: Warning: Cannot stat: No such file or directory\n", 
        "out": "/bin/gtar: : Warning: Cannot stat: No such file or directory\n/bin/gtar: level2: Warning: Cannot stat: No such file or directory\n/bin/gtar: level2/file1: Warning: Cannot stat: No such file or directory\n", 
        "rc": 1, 
        "unarchived": false
    }, 
    "dest": "/tmp/", 
    "extract_results": {
        "cmd": "/bin/gtar -C \"/tmp/\" -x --show-stored-names --strip-components=1 -f \"/home/dag/.ansible/tmp/ansible-tmp-1468007428.08-131128388826272/source\"", 
        "err": "", 
        "out": "", 
        "rc": 0
    }, 
    "gid": 10, 
    "group": "wheel", 
    "handler": "TarArchive", 
    "mode": "01777", 
    "owner": "root", 
    "secontext": "system_u:object_r:tmp_t:s0", 
    "size": 36864, 
    "src": "/home/dag/.ansible/tmp/ansible-tmp-1468007428.08-131128388826272/source", 
    "state": "directory", 
    "uid": 0
}
```

But it also works with my own tests, obviously.

**Comment by erikdw** [comment]
Yah, I don't understand the yaml library error either -- since I am just using the `source hacking/env-setup` invocation, and the behavior is varying depending on whether I've hand-copied into my ansible repo the unarchive.py file you have.  The suggestion to test inclusion of the yaml library via python doesn't reveal a general problem:

```
% python -c "import yaml"                                                                                                
%
```

But yep, your test with the deletion of the `/tmp/level*` after creating the tarball and before running unarchive seems to prove it's working.  So please merge away.

**Comment by dagwieers** [comment]
@abadger Can we get this merged ?

**Comment by dagwieers** [comment]
shipit shipit shipit damnit :-)

**Comment by dagwieers** [comment]
PR #4401 was moved into this pull-request as well.

**Comment by gregdek** [comment]
Thanks @dagwieers for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by dagwieers** [comment]
ready_for_review and wide testing :-)

**Comment by dagwieers** [comment]
ready_for_review and wide testing :-)

**Comment by gregdek** [comment]
Thanks @dagwieers. To the current maintainers, @dagwieers, @pileofrogs please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by dagwieers** [comment]
shipit

**Comment by gregdek** [comment]
Thanks @dagwieers. Since you are one of the maintainers (@dagwieers, @pileofrogs) of this module and you commented with "shipit", we are marking this PR for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by dagwieers** [comment]
shipit for real !

**Comment by dagwieers** [comment]
@abadger Can we be sure this ships with Ansible v2.2 ?

**Comment by gundalow** [comment]
Squashed & Merged.

Thanks for taking the time to improve this

**Comment by abadger** [comment]
Hey @dagwieers  sorry for not seeing this earlier and thanks @gunalow for picking up the slack.  Please ping me on irc (even if I'm asleep, I'll catch up on irc in the morning) if you need my attention.  It's way too easy for me to miss things that come in via email :-(

**Comment by dagwieers** [comment]
No problem, I understand the situation :-)

**Pull request merged**
