### PR TITLE
remove blank lines from htpasswd file

### PR DESCRIPTION
**Pull request by Jmainguy**

### CODE REVIEW

**Comment by Jmainguy** [comment]
This is designed to fix #1116 . Note this only removes blank lines, the module can still fail if the file contains invalid entries, like a username without a password.

**Comment by Jmainguy** [comment]
This also creates a temporary file if check_mode, and removes the temp file once its finished. This is so the module does not fail if check_mode and the file contains a blank line.

**Comment by Jmainguy** [comment]
This will now return change = True if there are blank lines in the file, since it will then need to edit the file and remove blank lines

**Comment by bcoca** [comment]
soo, use mktemp functions to create a tmp file, no need for using uuid and /tmp yourself.

**Comment by jimi-c** [comment]
Merged, thanks!

**Pull request merged**
