### PR TITLE
adding stickiness support to ec2_elb_lb.py

### PR DESCRIPTION
**Pull request by mschurenko**
We needed stickiness support at work so I added it to ec2_elb_lb. it would be nice if this could be looked at relatively soon. I'm finding that I have to maintain my own forks of ec2 modules as lots of times functionality (such as this) is missing.

Thanks

### CODE REVIEW

**Comment by mschurenko** [comment]
We don't need this anymore and it's not going to get merged so really, what's the point?

**Comment by bcoca** [comment]
others might still need it

**Comment by mschurenko** [comment]
ok. good point.

**Comment by bcoca** [comment]
also, sorry for the delay, but this is on my radar and I hope to get it in soon

**Comment by mschurenko** [comment]
no problem. i know you guys are busy.

**Comment by bcoca** [comment]
The implementation looks good, but I think it would fit better having a stickyness parameter (choices: builtin,application,none(default) with stickyness_cookie and stickyness_expiration as supporting options.

**Comment by gmalouf** [comment]
Setting none would have to undo a stickiness setting as well right?

**Comment by bcoca** [comment]
@gmalouf that is how we would like it to work

**Comment by mschurenko** [comment]
What about like this?

``` yaml
module: ec2_elb_lb
stickiness:
  type: application
  enabled: True # default is True
  app_cookie: SESSIONID
```

@bcoca if you don't like this way can you express "having a stickyness parameter (choices: builtin,application,none(default) with stickyness_cookie and stickyness_expiration as supporting options" in yaml? I'm not exactly sure what you mean.

Thanks

**Comment by bcoca** [comment]
this format looks fine

**Comment by mschurenko** [comment]
Sorry I have been busy, moved, started a new job and forgot about this. @bcoca would you like me to fix it up still?

**Comment by bcoca** [comment]
@mschurenko yes, i would appreciate that, takes it off my list

**Comment by mschurenko** [comment]
ok I should have it done within the next week or so.

**Comment by mschurenko** [comment]
Ok it should be good. Let me know if the pull request is clean enough.

**Comment by bennojoy** [comment]
@mschurenko 

i tested with this task

```
- local_action:
     module: ec2_elb_lb
     name: "test-please-delete"
     state: present
     zones:
       - us-east-1c
     listeners:
        - protocol: http # options are http, https, ssl, tcp
          load_balancer_port: 80
          instance_port: 80
     stickiness:
        type: application
        enabled: False
        cookie: SESSIONID
```

and it seems to return changed=true status every time it runs, maybe _delete_policy should check if the policy exists and if not return changed=False

**Comment by mschurenko** [comment]
Thanks @bennojoy. That's a good suggestion. ~~I'll try to add that.~~ I've added a check for that.

**Comment by bennojoy** [comment]
@mschurenko  looks good to merge.. Thanks ,  The pr  is broken out over many commits, can you please consider submitting just one squashed commit so that it keeps the history concise

**Comment by bennojoy** [comment]
@mschurenko  a minor one can you please change version_added to 2.0 instead of 1.9 in the docstring

**Comment by mschurenko** [comment]
ok @bennojoy. Is this good now?

**Comment by bennojoy** [comment]
Hi!

This has been merged in, and will also be included in the next major release.

If you or anyone else has any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:

https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code
Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Pull request merged**
