### PR TITLE
Improve Detached HEAD Detection for Git Module

### PR DESCRIPTION
**Pull request by femnad**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

source_control/git
##### ANSIBLE VERSION

```
ansible 2.2.0
  config file = /home/femnad/.ansible.cfg
  configured module search path = Default w/o overrides
```

where `ansible.cfg` is:

```
[defaults]
inventory = ~/y/ansible/inventory
retry_files_enabled = false
```
###### Before

```
$ ansible-playbook -l lithium install-fish.yaml -t clone

PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ok: [lithium]

TASK [git_clone : Clone project with git] **************************************
fatal: [lithium]: FAILED! => {"changed": false, "failed": true, "msg": "Could not determine remote revision for HEAD", "rc": 0, "stderr": "", "stdout": "", "stdout_lines": []}

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
lithium                    : ok=1    changed=0    unreachable=0    failed=1   

```
###### After

```
$ ansible-playbook -l lithium install-fish.yaml -t clone

PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ok: [lithium]

TASK [git_clone : Clone project with git] **************************************
changed: [lithium]

PLAY RECAP *********************************************************************
lithium                    : ok=2    changed=1    unreachable=0    failed=0   
```

Where the cloned repo is at the following state before running the playbook

```
$ git status
HEAD detached at 2.3.0
nothing to commit, working directory clean
```

The playbook is located at:

[https://github.com/femnad/casastrap/blob/master/install-fish.yaml](https://github.com/femnad/casastrap/blob/master/install-fish.yaml)
###### Description

When an already cloned repo is in a detached HEAD state and is at the same
commit as when it was originally detached, the update operation fails with the
"Could not determine remote revision for HEAD" error, since the detached
HEAD is misinterpreted as a branch.

The detached HEAD detection works by checking whether there are any local
branches with names starting with '\* ' and containing the phrases 'no branch'
or 'detached from'. However, this approach is not taking detached HEADs still
on the same commit as the original branch into account, which are listed by git
as "\* (HEAD detached at <...>)".

To fix this problem, simply add the phrase 'detached at' to the list of
patterns used for checking the existence of a detached HEAD state, thereby make
sure that the git module operation is successful in any type of detached HEAD
state.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @femnad for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @femnad for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by femnad** [comment]
ready_for_review

**Comment by femnad** [comment]
A Python3 test is failing on a method which wasn't modified by this pull request and I am able to trigger failures when the git repo clone to be updated is modified. However I don't think it would be a good practice to fix those errors in this pull request so I am inclined to create new pull requests for those issues.
Edit: the error in case of local modifications behavior was addressed with #5293.
Edit 2: The failing integration test is this one: https://github.com/ansible/ansible/blob/devel/test/integration/targets/git/tasks/main.yml#L178. However, that behavior was fixed for Python3 via a3d4d74d528753b23b9a875040c94bf622d1eb5c but I'm stumped at this to point with regard to the cause of that failure.
Edit 3: So turns out there was another `to_bytes` in the git module. I submitted a pull request to fix that one: #5375

**Comment by gregdek** [comment]
Thanks @femnad for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
