### PR TITLE
Added support for immediate block storage provisioning

### PR DESCRIPTION
**Pull request by cdmitri**
**Added support for immediate block storage provisioning**
- Already exists in ec2 module
- Syntax is the same as in ec2 module
  
  volumes:
       - display_name: vm1-vol1
         device_name: /dev/vdb
         volume_size: 10
         delete_on_termination: true
       - display_name: vm1-vol2
         device_name: /dev/vdc
         volume_size: 20
         delete_on_termination: false
- `delete_on_termination` is not an openstack feature
  but will work during deletion

**Changed the authentication to Password() method**
- Reflects most recent documentation
- Necessary to switch between compute and volume
  actions if API URLs for those are different,
  which is true for a lot of installations

### CODE REVIEW

**Comment by imiu** [comment]
I've been looking to have this feature for a while! Kudos to you for making it available!

**Comment by keithchambers** [comment]
LGTM!

**Comment by keithchambers** [comment]
Is there a reason this isn't getting merged?

**Comment by emonty** [comment]
Sorry - these modules are deprecated and not accepting new features. I believe this feature is covered in the new modules at ansible/ansible-modules-extras#92 - albeit in two modules, not one. However, if it's not, I'd love to make those better and make sure it serves your needs. Do you have a strong feeling on being able to combine volume creation and server creation as one play? I don't have a strong aversion to doing that in the os_server module as well ...

**Comment by emonty** [comment]
Created issue ansible/ansible-modules-extras#321 to track this need

**Pull request closed without merging**
