### PR TITLE
Fix quote on grants of more than one word

### PR DESCRIPTION
**Pull request by joshrendek**
Fixed a quote location on the grants composed of more than one word. Current docs will raise an error with a invalid privilege command.

### CODE REVIEW

**Comment by gregdek** [comment]
@marktheunissen Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by gregdek** [comment]
@marktheunissen This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by marktheunissen** [comment]
Hi Greg, I am no longer the maintainer, please see https://github.com/ansible/ansible-modules-core/pull/2653

**Comment by robynbergeron** [comment]
@Jmainguy still waiting on your review.  Please comment with text 'shipit' or 'needs_revision' as appropriate. If we don't hear from you within 14 days, we will start to look for additional maintainers for this module.

**Comment by Jmainguy** [comment]
```
[root@phy01 ansible]# ansible-playbook -i hosts site.yml 

PLAY [XZ] **********************************************************************

TASK [mysql_user : test Broken] ************************************************
fatal: [centos6.soh.re]: FAILED! => {"changed": false, "failed": true, "msg": "invalid privileges string: Invalid privileges specified: frozenset(['\"REPLICATION CLIENT\"'])"}
...ignoring

TASK [mysql_user : Test Fixed] *************************************************
changed: [centos6.soh.re]

PLAY RECAP *********************************************************************
centos6.soh.re             : ok=2    changed=1    unreachable=0    failed=0   

[root@phy01 ansible]# cat roles/mysql_user/tasks/main.yml 
---
- name: test Broken
  mysql_user: name=replication password=12345 priv=*.*:"REPLICATION CLIENT" state=present
  ignore_errors: true

- name: Test Fixed
  mysql_user: name=replication password=12345 priv="*.*:REPLICATION CLIENT" state=present
[root@phy01 ansible]# ansible-playbook -i hosts site.yml 

PLAY [XZ] **********************************************************************

TASK [mysql_user : test Broken] ************************************************
fatal: [centos6.soh.re]: FAILED! => {"changed": false, "failed": true, "msg": "invalid privileges string: Invalid privileges specified: frozenset(['\"REPLICATION CLIENT\"'])"}
...ignoring

TASK [mysql_user : Test Fixed] *************************************************
ok: [centos6.soh.re]

PLAY RECAP *********************************************************************
centos6.soh.re             : ok=2    changed=0    unreachable=0    failed=0   
```

**Comment by Jmainguy** [comment]
@robynbergeron @joshrendek Sorry for the delay.

Great job on this PR, thank you for submitting this and being so patient.

'shipit'

**Comment by gregdek** [comment]
Thanks again to @joshrendek for this PR, and thanks @Jmainguy for reviewing. Marking for inclusion.

**Pull request merged**
