### PR TITLE
Added additional AMI attributes to the output. Also added state=list …

### PR DESCRIPTION
**Pull request by Constantin07**
Now the output of AMI create prints comprehensive list of attributes related to image, including block device mapping.

```
TASK: [image | debug var=ami_res] *********************************************
ok: [127.0.0.1] => {
    "var": {
        "ami_res": {
            "architecture": "x86_64",
            "block_device_mapping": {
                "/dev/sdb": {
                    "delete_on_termination": true,
                    "encrypted": false,
                    "size": 1,
                    "snapshot_id": "snap-03d23674",
                    "volume_type": "standard"
                },
                "/dev/xvda": {
                    "delete_on_termination": true,
                    "encrypted": false,
                    "size": 8,
                    "snapshot_id": "snap-5a2e452f",
                    "volume_type": "gp2"
                }
            },
            "changed": true,
            "creationDate": "2015-10-14T16:38:46.000Z",
            "description": null,
            "hypervisor": "xen",
            "image_id": "ami-dba1f4be",
            "invocation": {
                "module_args": "",
                "module_name": "ec2_ami"
            },
            "is_public": false,
            "location": "296076420565/proj-test",
            "msg": "AMI creation operation complete",
            "ownerId": "296076420565",
            "root_device_name": "/dev/xvda",
            "root_device_type": "ebs",
            "state": "available",
            "tags": {},
            "virtualization_type": "hvm"
        }
    }
}
```

### CODE REVIEW

**Comment by wimnat** [comment]
Don't add 'list' state - do a _facts module instead.  There's a pending PR for ec2_vol_facts and hopefully once accepted the list option will be deprecated.

**Comment by Constantin07** [comment]
May be it's worth to add this to ec2_ami_find module instead of creating a _facts one?
It currently outputs similar data but incomplete. Just thinking of not duplicating the functionality.

**Comment by wimnat** [comment]
Yeh sounds good. The find module I guess is a facts module but it's not how I would of written it. So yeh, just add any additional parameters to that module and remove the list state here

**Comment by Constantin07** [comment]
@wimnat Are you OK then to remove the state=list for this module and leave just the enriched output?
Just removed the state=list option.

**Comment by wimnat** [comment]
Yep.

**Comment by robynbergeron** [comment]
[module: cloud/amazon/ec2_ami.py]

Hi @Constantin07 -- thanks for this PR, and thanks @wimnat for your quick feedback :)

Trying to decipher where we are here -- @wimnat, with the last commit from @Constantin07, is this looking ready to go?

Also hailing @scicoin-project as the module owner for feedback.

**Comment by wimnat** [comment]
@Constantin07 can you rebase this and merge your two commits?  The history isn't very clean at the moment with your second commit just removing changes you made in the first commit.

needs_revision

**Comment by Constantin07** [comment]
@wimnat , Sorry for messy commit.
Unfortunately I deleted my local branch after pull request so not sure if I can rebase it.
Do I need create another pull request with a clear commit? (and close this one)

**Comment by wimnat** [comment]
You can usually restore deleted branches in github but if you can't then
yeh, just do a new PR and reference this one.

**Comment by Constantin07** [comment]
This PR is closed and opened #2320 which includes combined improvements.

**Pull request closed without merging**
