### PR TITLE
Use connect_to_aws method and remove empty aliases

### PR DESCRIPTION
**Pull request by wimnat**
Resolves https://github.com/ansible/ansible-modules-core/issues/714

### CODE REVIEW

**Comment by gregdek** [comment]
@zbal Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by gregdek** [comment]
@zbal This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by robynbergeron** [comment]
@zbal still waiting on your review.  Please comment with text 'shipit' or 'needs_revision' as appropriate. If we don't hear from you within 14 days, we will start to look for additional maintainers for this module.

**Comment by gregdek** [comment]
Moving to @ansible/core for review.

Sorry for the delay @wimnat.

**Pull request closed without merging**
