### PR TITLE
Fixes #3661 - Make use of conn_type variable so we can easily handle …

### LINKED ISSUE #3661: get_url fails with some ftp servers
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

get_url
##### ANSIBLE VERSION

```
ansible 2.0.2.0
  config file = 
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

Ansible.cfg does not exist. So it is using all default values.
##### OS / ENVIRONMENT

I think that is not platform-specific.
But I have tested un ubuntu 14.04 and CentOS 6.
##### SUMMARY

The get_url module fails with "fatal" error with some ftp servers.
This is the error shown:

```
fatal: [localhost]: FAILED! => {"changed": false, "dest": "/tmp", "failed": true, "gid": 0, "group": "root", "mode": "01777", "msg": "Request failed", "owner": "root", "response": "OK (282593 bytes)", "size": 4096, "state": "directory", "status_code": null, "uid": 0, "url": "ftp://ftp.surfsara.nl/pub/outgoing/pbs_python-4.6.0.tar.gz"}
```
##### STEPS TO REPRODUCE

Create a simple playbook like that and call ansible-playbook:

```
- hosts: localhost
  connection: local
  tasks:
   - get_url: url=ftp://ftp.surfsara.nl/pub/outgoing/pbs_python-4.6.0.tar.gz dest=/tmp
   # the next one also fails
   - get_url: url=ftp://mirror.cc.columbia.edu/pub/software/apache/hadoop/core/hadoop-1.2.1//hadoop-1.2.1.tar.gz  dest=/tmp
```
##### EXPECTED RESULTS

Correctly download the file and return this output:

```
PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [get_url] *****************************************************************
changed: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0   
```
##### ACTUAL RESULTS

```
PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [get_url] *****************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "dest": "/tmp", "failed": true, "gid": 0, "group": "root", "mode": "01777", "msg": "Request failed", "owner": "root", "response": "OK (282593 bytes)", "size": 4096, "state": "directory", "status_code": null, "uid": 0, "url": "ftp://ftp.surfsara.nl/pub/outgoing/pbs_python-4.6.0.tar.gz"}

NO MORE HOSTS LEFT *************************************************************
    to retry, use: --limit @test.retry

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1   
```

### PR DESCRIPTION
**Pull request by ronnietaylor**
##### ISSUE TYPE
- Bugfix Pull Request
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel d08fda9320) last updated 2016/05/24 21:03:58 (GMT -700)
  lib/ansible/modules/core: (detached HEAD aa995806b9) last updated 2016/05/24 21:04:04 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD d1a4f703ce) last updated 2016/05/24 21:04:09 (GMT -700)
  config file = /Users/ronnietaylor/Documents/Development/ansible-experiments/vangrants/ubuntu1404/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

Fixes #3661

Goes with corresponding pull request: https://github.com/ansible/ansible/pull/15995

Make use of new conn_type variable returned by fetch_url that contains the output from `urlparse.urlparse(url)` (i.e. 'ftp', 'http' or 'https').

This ultimately lets get_url check against something other than just HTTP status codes since successful FTP connections don't return status codes in the response headers like HTTP does. By passing along the connection type we can prevent incorrectly throwing errors for successful FTP connections.

Since the parsing of the url already happens at this level then it seemed best to just capture it once and pass it through to get_url instead of parsing the url again later.

This new variable will contain a string like the following:

```
>>> conn_type
'ftp'
```

… in the get_url module.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @ronnietaylor. To the current maintainers, @jpmens please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by jpmens** [comment]
shipit

**Comment by gregdek** [comment]
Thanks again to @ronnietaylor for this PR, and thanks @jpmens for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by ronnietaylor** [comment]
Actually....I may have found a regression in my local repo after using this fix. 

A problem occurred in one of my other playbooks that uses the apt_key module. It threw an exception of "too many values to unpack".

As best I can tell this is because I changed the number of objects returned by fetch_url which is used by apt_key and other modules.

See the corresponding change here:

https://github.com/ansible/ansible/pull/15995

So I'd like some feedback on a different tactic. I was originally trying to avoid parsing the url again within get_url since that is already done down in open_url. However, it seems now that parsing it again in get_url in order to set conn_type may a simpler way and avoids the side affects.

Let me know what you think.

Thanks.

**Comment by ronnietaylor** [comment]
After further testing and thought I'm closing this pull request and will submit a single, simplified one that more cleanly solves this issue.

**Pull request closed without merging**
