### PR TITLE
service: add option for ignoring missing runlevel warnings

### PR DESCRIPTION
**Pull request by larsbu**
##### ISSUE TYPE

 Feature Pull Request
##### COMPONENT NAME

service.py
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel 1268f4778d) last updated 2016/08/12 15:02:04 (GMT +200)
  lib/ansible/modules/core: (detached HEAD a216ef210b) last updated 2016/08/12 15:03:55 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 39153ea154) last updated 2016/08/12 15:04:06 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```
##### SUMMARY

insserv reports warnings for missing runlevel of other services. e.g.:

```
    "msg": "Failed to install service. rc: 0, out: , err: insserv: Service network is missed in the runlevels 4 to use service aurad\ninsserv: Service syslog is missed in the runlevels 4 to use service vasd\n"
```

Because it is difficult to fix every vendor supplied init.d script this PR introduces an option to ignore such warnings.

Old references for the issue:
Issue #1502
PR https://github.com/ansible/ansible-modules-core/pull/1846

### CODE REVIEW

**Comment by bcoca** [comment]
Since we are splitting the service module, this does not seem something we want in the generic form, but in the `sysvinit` specific one.

**Comment by gregdek** [comment]
Thanks @larsbu. To the current maintainers, @grossws please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by alxgu** [comment]
@bcoca  When do you split the `sysvinit` part? 
Will it be done for version 2.2?

**Comment by gregdek** [comment]
Thanks @larsbu for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by alxgu** [comment]
Any progress here?

**Comment by mtkunkel** [comment]
I just ran into this same problem.  3rd party init.d scripts are garbage.  chkconfig rc=0 but stderr causes module failure.   Do we need to open an issue over on the main ansible repo?


Quick (and oh so dirty) workaround is as follows:
```
  register: service_result
  failed_when: "service_result.failed == true and not 'rc: 0' in service_result.msg"
```

**Pull request closed without merging**
