### PR TITLE
Docker Module Check Mode

### PR DESCRIPTION
**Pull request by pmyjavec**
Implementation of a check mode for the Docker module. Notifies a user
when a change would be made to containers (or lack of there of) on remote
servers.

### CODE REVIEW

**Comment by pmyjavec** [comment]
Been using this most of the day, feels fairly solid so far.

**Comment by pmyjavec** [comment]
Should I bother rebasing this, do you think it's something that will ever get merged?

**Comment by bcoca** [comment]
yes, but we are in the middle of releasing 1.9 so it won't make that release

**Comment by thefallentree** [comment]
Couldn't believe that this core functionality (IMHO) is not already in the ansible docker module...

**Comment by pmyjavec** [comment]
I will rebase this next week. Hopefully get  it in soon...

**Comment by gregdek** [comment]
Hi @pmyjavec -- yes, please rebase this. Once you've done so, we can ping the authors of this module so they can help with the review.

**Comment by gregdek** [comment]
@pmyjavec a friendly ping that we're still waiting on rebase here...

**Comment by pmyjavec** [comment]
No worries,  I will have a go In the next few days

**Comment by gregdek** [comment]
@pmyjavec A friendly reminder: this pull request has been marked as needing your action, and it hasn't been updated in the last month. 

If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we'll keep it open pending your changes.

If we receive no indication from you within a week, we will close this pull request.

**Comment by gregdek** [comment]
Closing due to inactivity. Apologies @pmyjavec -- if you feel we've closed this PR in error, feel free to resubmit a new PR.

**Comment by resmo** [comment]
@gregdek @pmyjavec  I'll pick it up.

**Pull request closed without merging**
