### PR TITLE
Initial implementation of s3_lifecycle module

### PR DESCRIPTION
**Pull request by echiu64**
Per issue https://github.com/ansible/ansible-modules-core/issues/1420
See main project for unit tests and README (https://github.com/echiu64/ansible-s3-lifecycle)
Welcome comments/review as I work to fully complete this module

### CODE REVIEW

**Comment by bcoca** [comment]
The module manages lifecycle to s3 relationships more than the lifecycles themselves which are fully defined inline.  It expects deep knowledge of the lifecycle definitions and does not give an easy (guided by options) way to create one, usable by someone very familiar with the aws internals/API but requires a big learning curve for others.

Sadly we already have some aws modules this way which makes it hard for people to get started, I would like to move away from this mode of doing things.

Tests can be added to ansible/ansible under test/integration with the other cloud tests

**Comment by echiu64** [comment]
Any suggestions how to make it easier? Only thing i can think of is maybe we auto generate rule ids on behalf of the user. And maybe get rid of status and just use state (absent/present) vs combination of status and state. When I do the glacier transition, i could always do a transition_to_glacier option, vs using a "storage_class" option?

**Comment by gregdek** [comment]
@ansible/core is this better as an extras module? I'm inclined to think so.

**Comment by wimnat** [comment]
Working with @echiu64, this has been addressed with a PR in extras - https://github.com/ansible/ansible-modules-extras/pull/718.  This PR can probably be closed.

**Comment by bcoca** [comment]
closing as per above

**Pull request closed without merging**
