### PR TITLE
Unarchive no longer transfers archive if creates= check succeeds

### PR DESCRIPTION
**Pull request by rdolejsi**
Unarchive no longer transfers the archive in case the creates= parameter yields a successful match, thus preventing lenghty operations over the network (especially with large archive distributions).

### CODE REVIEW

**Comment by rdolejsi** [comment]
Please note: the unpack module on the client is actually called twice to achieve this - with extra signalling using precheck=True/False parameter. Please suggest other form of signalling if this is not the correct way of doing it.

**Comment by rdolejsi** [comment]
This is a replacement request for the closed pullreq #9139 (no changes, update to current HEAD).

This is a half of the patch, complementary to core Ansible pullreq http://github.com/ansible/ansible/pull/9232. Both pullreqs are required.

**Comment by abadger** [comment]
Added a comment on https://github.com/ansible/ansible/pull/9232 -- I think we merged a different pull request in November that achieved the same goals.

**Comment by abadger** [comment]
Commit that implemented a fix for this: https://github.com/ansible/ansible/commit/e79acf3f882a2f9d46a44df500ce9cd9955ca227

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Pull request closed without merging**
