### PR TITLE
fixed broken facts

### PR DESCRIPTION
**Pull request by ThomasSteinbach**
In commit 80aca4b9369073d7b58ff168cf4eef8bb126c2d0, a rework of the docker module, the returned facts becomes broken. In commit 45b067f097c49a5baaf37fe5d7734c9666ca7184 a first fix was made, but doesn't brought back the facts information before the rework.

Mainly the last fix just returned the container id, whereas the facts before the rework returned detailed information about the containers changed. For instance the IPv4 address, by which created containers could instantly appended to the dynamic ansible inventory.

With this fix all information belongig to changed containers were returned, such that created containers could be added to the dynamic inventory as before.

### CODE REVIEW

**Comment by ThomasSteinbach** [comment]
Are there any further tasks I have to do to get the change pulled to ansible:devel? I haven't done a pull request before.

**Comment by abadger** [comment]
@smashwilson @cove @joshuaconner @softzilla would any of you be willing to review this change?  It's non-obvious to me that this fixes the problem without unintended side effects but you guys know the code better so you can probably figure out if it is a good change much quicker than I can.

**Comment by ThomasSteinbach** [comment]
Maybe @smashwilson should review the change, because he is the one who has reworked the module and 'broke' the returned facts.

I use my fix since months successfull. No issues. I am everytime annoyed I am installing Ansible on a fresh system and running into problems without that fix.

**Comment by gregdek** [comment]
Still waiting on review.

**Comment by abadger** [comment]
Thanks @ThomasSteinbach and looking forward to working more with you in the future!  Hopefully adding more people to the docker module maintainers list will get things reviewed and merged quicker. 

For those coming to this via a web search, #2093 was reviewed and merged into the devel branch (will be 2.0).  It should fix this issue as well so going ahead and closing it.

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Pull request closed without merging**
