### PR TITLE
Stable 2.1

### LINKED ISSUE #4247: unarchive failed to unpack tar files
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

unarchive
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```
##### OS / ENVIRONMENT

management node: centos 6.5
remote node: centos 6.5
##### SUMMARY

unarchive module shows error when it handle gzip, bzip2 and xz compressed as well as uncompressed tar files using Ansible stable 2.1.0.0 version.
##### STEPS TO REPRODUCE

unarchive:
    src: /usr/local/src/example.tar.gz
    dest: /usr/local/src
    creates: /usr/local/src/example/Makefile
    copy: no

```

```

##### EXPECTED RESULTS

changed: [xxxxx]
##### ACTUAL RESULTS

fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Unexpected error when accessing exploded file: [Errno 2] 没有那个文件或目录: '/usr/local/src/test.txt'"}

NO MORE HOSTS LEFT *************************************************************
    to retry, use: --limit @test.retry

```

```

### PR DESCRIPTION
**Pull request by xiaozhizhu**
##### ISSUE TYPE

- Bugfix Pull Request
##### COMPONENT NAME

unarchive
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

Fixes #4247
Found where the problem is: files/unarchive.py (Line 557):

```
if out:
     unarchived = False
```

Unarchived is set as always True. Before you reach this condition, unarchived has been set True. But when a new target tar file haven't been unpacked, out is '' and "if out:" will not be execute, so unarchived will be always True, the module will fail everytime. I think the correct is this:

```
if not out:
     unarchived = False
```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @xiaozhizhu for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by bcoca** [comment]
this PR has many foreign commits, please rebase.

**Comment by gregdek** [comment]
Thanks @xiaozhizhu for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by alikins** [comment]
This seems to be a patch against the stable-2.1 branch but filed as a pr against devel/. Intended to be filed against stable-2.1?

**Comment by gregdek** [comment]
@xiaozhizhu A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by dagwieers** [comment]
resolved_by_pr #4244

**Comment by gregdek** [comment]
@xiaozhizhu Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gundalow** [comment]
Hi,
I believe this has been resolved_by_pr #4244 so I'll close this.

**Pull request closed without merging**
