### PR TITLE
added regex support to find

### PR DESCRIPTION
**Pull request by bcoca**
Also added 'singular' aliasess to patterns and paths

### CODE REVIEW

**Comment by abadger** [comment]
-1 I really think we should have separate parameters for regexes and shell globs.  Combining them into a single parameter is a bad standard to set.

**Comment by abadger** [comment]
Here's my alternative implementation: https://github.com/ansible/ansible-modules-core/pull/2263

**Comment by robynbergeron** [comment]
[module: files/find.py]

**Comment by abadger** [comment]
+1  Looks good to me!

**Pull request merged**
