### PR TITLE
ec2_ami module is now idempotent

### PR DESCRIPTION
**Pull request by robbwagoner**
ec2_ami module now checks for the existence of an AMI ID for a given AMI
Name. Since AMI Names must be regionally unique, this can be used to
lookup the AMI ID of interest. E.g. for the following AMI Names:
- `ubuntu/images/hvm/ubuntu-trusty-14.04-amd64-server-20150209.1`
- `amzn-ami-hvm-2014.09.2.x86_64-gp2`

`instance_id` is only required if the AMI Name doesn't exist.

```

---

- name: get the Ubuntu AMI
  hosts: localhost
  connection: local
  tasks:
    - name: Ubuntu 14.04 Trusty
      local_action:
        module: ec2_ami
        name: 'ubuntu/images/hvm/ubuntu-trusty-14.04-amd64-server-20150209.1'
      register: ami_ubuntu

    - debug: var=ami_ubuntu

    - name: Amazon Linux 2014.09.1 HVM 64-bit GP2 SSD
      local_action:
        module: ec2_ami
        name: 'amzn-ami-hvm-2014.09.2.x86_64-gp2'
      register: ami_amazon

    - debug: var=ami_amazon
```

Output:

```

PLAY [get the Ubuntu AMI] *****************************************************

GATHERING FACTS ***************************************************************
ok: [localhost]

TASK: [Ubuntu 14.04 Trusty] ***************************************************
ok: [localhost -> 127.0.0.1]

TASK: [debug var=ami_ubuntu] **************************************************
ok: [localhost] => {
    "ami_ubuntu": {
        "changed": false,
        "image_id": "ami-08f8b160",
        "invocation": {
            "module_args": "",
            "module_name": "ec2_ami"
        },
        "msg": "AMI found",
        "name": "ubuntu/images/hvm/ubuntu-trusty-14.04-amd64-server-20150209.1",
        "state": "available"
    }
}

TASK: [Amazon Linux 2014.09.1 HVM 64-bit GP2 SSD] *****************************
ok: [localhost -> 127.0.0.1]

TASK: [debug var=ami_amazon] **************************************************
ok: [localhost] => {
    "ami_amazon": {
        "changed": false,
        "image_id": "ami-ee6e2a86",
        "invocation": {
            "module_args": "",
            "module_name": "ec2_ami"
        },
        "msg": "AMI found",
        "name": "amzn-ami-hvm-2014.09.2.x86_64-gp2",
        "state": "available"
    }
}

PLAY RECAP ********************************************************************
localhost                  : ok=5    changed=0    unreachable=0    failed=0
```

### CODE REVIEW

**Comment by viatcheslavmogilevsky** [comment]
When it will be on release?
Actually, this is my workaround:

``` yaml
    - ec2_ami:
        instance_id: "{{ server_ec2_id }}"
        wait: yes
        name: my-awesome-image
        state: present
      ignore_errors: true
      register: server_image

# I need to get image id. It doesn't mean that image just created or already exists

    - set_fact:
        server_image_id: "{{ server_image.msg| regex_replace('^.*is\\salready\\sin\\suse\\sby\\sAMI\\s(ami-.*)$', '\\\\1')}}"
      when: server_image|failed

    - set_fact:
        server_image_id: "{{ server_image.image_id }}"
      when: server_image|changed
```

**Comment by bennojoy** [comment]
@robbwagoner  Could you please resolve the conflicts and squash commits.. thanks

**Comment by robbwagoner** [comment]
@bennojoy - Thanks for the follow up. I will endeavor to resolve the conflicts this week.

**Comment by bennojoy** [comment]
this should be fixed via #737

**Comment by gregdek** [comment]
Going to assume that #737 fixes this issue. If not, @robbwagoner please file a new PR with any proposed changes.

**Comment by robbwagoner** [comment]
@gregdek thanks. #737 LGTM.

**Pull request closed without merging**
