### PR TITLE
Add more info and minor fixes

### PR DESCRIPTION
**Pull request by daveres**
Additional info:
- Physical disk (I use ansible_devices variable for compatibility with linux)
- Logical disk (I use ansible_mounts variable for compatibility with linux)
- DNS Servers for network interfaces
- Enviroment variables
- Installed kbs

Fix:
- Error with cpu info (physical processors)

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @daveres for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

**Comment by gregdek** [comment]
Thanks @daveres for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

**Comment by gregdek** [comment]
@daveres A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes.

**Comment by robynbergeron** [comment]
@daveres Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If we don't hear from you within another 14 days, we will close this pull request.

**Comment by gregdek** [comment]
Closing due to contributor inactivity.

**Pull request closed without merging**
