### PR TITLE
Add DigitalOcean API v2 support for SSH keys and Domains with fixes

### PR DESCRIPTION
**Pull request by ianheggie**
@zyegfryed     zyegfryed   Add DigitalOcean API v2 support for SSH keys and Domains management  
b0126fd
Commits on Aug 22, 2015
    @connorfinnerty     connorfinnerty  Digital Ocean APIv2 uses domain name instead of id

### CODE REVIEW

**Comment by gregdek** [comment]
@mgregson Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by gregdek** [comment]
Thanks @ianheggie for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

**Comment by robynbergeron** [comment]
@ianheggie A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes.

**Comment by gregdek** [comment]
@ianheggie Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If we don't hear from you within another 14 days, we will close this pull request.

**Comment by gregdek** [comment]
Closing due to lack of response.

**Comment by ianheggie** [comment]
Really late reply - is this even needed now? (Has it been fixed through some other pull request?)

**Pull request closed without merging**
