### PR TITLE
Add comment option to authorized_key

### PR DESCRIPTION
**Pull request by cao**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

authorized_key - Adds or removes an SSH authorized key
##### ANSIBLE VERSION

```
2.1.0.0
```
##### SUMMARY

The patch adds the comment option to the authorized_key module.

The comment option can be used to overwrite the comment for an SSH key before writing it to disk. It is useful when fetching the keys from a source that does not carry a meaningful comment, such as Gitlab or Github.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @cao for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by cao** [comment]
Any chance this will make it into the 2.2 release?

**Comment by gregdek** [comment]
Thanks @cao for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by cao** [comment]
Rebased onto HEAD of origin:devel.

Failed check by Shippable is through some unrelated connectivity issue:

> curl: (6) Could not resolve host: raw.githubusercontent.com

ready_for_review

**Comment by cao** [comment]
ready_for_review still :-)

**Pull request closed without merging**
