### PR TITLE
Fixes #4227

### LINKED ISSUE #4227: ELB documentation does not match reality: listeners are mandatory
##### ISSUE TYPE
- Documentation Report
##### COMPONENT NAME

ec2_elb_lb
##### ANSIBLE VERSION

ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
##### CONFIGURATION

$ env | grep ANSIBLE
ANSIBLE_HOST_KEY_CHECKING=false
##### OS / ENVIRONMENT

Mac OS X El Capitan
##### SUMMARY

The documentation states that listener is an optional item, when it seems it is not.
##### STEPS TO REPRODUCE

Using the following task:

```
- name: Create ELB for sender servers
  local_action:
    module: ec2_elb_lb
    name: "{{ elb_sender }}"
    state: present
    zones: "{{ availability_zones }}"
    tags:
      Name: "{{ elb_sender }}"
      type: "{{ type_sender }}"
      env: "{{ env }}"
    cross_az_load_balancing: "yes"
    security_group_names: "{{ security_group_sender }}"
    wait: yes
```
##### EXPECTED RESULTS

ELB created without listeners as per documentation
##### ACTUAL RESULTS

```
fatal: [localhost -> localhost]: FAILED! => {"changed": false, "failed": true, "msg": "At least one port is required for ELB creation"}
```

### PR DESCRIPTION
**Pull request by ghost**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

ec2_elb_lb module
##### ANSIBLE VERSION

Tested with two versions to make sure it was backwards compatible.

```
ansible 1.9.2
  configured module search path = /Users/rmendes/github/oss/ansible-modules-core:/Users/rmendes/github/oss/ansible-modules-extras

ansible 2.1.1.0
  config file = /Users/rmendes/tmp/ansible/module-tests/aws_elb_lb/issue-4227/ans21/ansible.cfg
  configured module search path = ['/Users/rmendes/github/oss/ansible-modules-core', '/Users/rmendes/github/oss/ansible-modules-extras']
```
##### SUMMARY

Fixes #4227. Issue reported documentation was bad. When I tested with boto2 and boto3 I found it failed with both. My thought is AWS changed their requirement since the original module was written.

Before the fix:

```
PLAY [create a test elb] ******************************************************

TASK: [Create ELB for sender servers] *****************************************
failed: [localhost -> 127.0.0.1] => {"failed": true}
msg: At least one port is required for ELB creation

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1
```

After the fix:

```
PLAY [create a test elb] ******************************************************

TASK: [Create ELB for sender servers] *****************************************
failed: [localhost -> 127.0.0.1] => {"failed": true}
msg: missing required arguments: listeners

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1
```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks again to @rickmendes. This module is going into community review.

We notice that you are one of the maintainers (@jsdalton, @rickmendes) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by ghost** [comment]
According to this, one or more listeners is required for an ELB - http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/elb-listener-config.html.

So let's shipit.

**Comment by gregdek** [comment]
Thanks @rickmendes. Since you are one of the maintainers (@jsdalton, @rickmendes) of this module and you commented with "shipit", we are marking this PR for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by ryansb** [comment]
I don't know if this should be required for all states: it seems to me like `state=absent` shouldn't require that the user provide a full listener config. You could check the `state` before raising a `fail_json` if there are no listeners and the state isn't "absent".

**Comment by ghost** [comment]
@ryansb I am glad you had me take a look. The code was already there to check on present. I think the messaging was just confusing to people.

**Pull request merged**
