### PR TITLE
Fix for exclude_hosts in wait_for connection drained

### PR DESCRIPTION
**Pull request by b1-88er**
##### Issue Type:
- Bugfix Pull Request
##### Plugin Name:

`wait_for`
##### Summary:

Fix for exclude_hosts in wait_for connection drained

Solves: https://github.com/ansible/ansible-modules-core/issues/3185

When calculating active connections, exclude_hosts gets ignored because
we check if ip (string) is present in list of tuples (int, string(ip)).
Making `self.exclude_ips` flat list of strings solves the issue.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @eddwardo for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

**Comment by gregdek** [comment]
(unlabeling pending reviewer change)

**Comment by gregdek** [comment]
Thanks @eddwardo. To the current maintainers, @gregswift please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by b1-88er** [comment]
Might duplicate: https://github.com/ansible/ansible-modules-core/pull/1301

**Comment by gregdek** [comment]
Thanks @eddwardo for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregswift** [comment]
#1301 was merged in and will be in 2.0.2 release. Please confirm that this solves your issue.

**Comment by gregdek** [comment]
@eddwardo A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
