### PR TITLE
[WIP] launchd service plugin

### PR DESCRIPTION
**Pull request by bcoca**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

launchd
##### ANSIBLE VERSION

```
2.2
```
##### SUMMARY

launchd service manager plugin

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @bcoca for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @bcoca for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by tcr-ableton** [comment]
I can't get the module to work, ansible fails with the following message:

``` bash
fatal: [127.0.0.1 -> localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}
```

Here is how my test environment is set up:
- Using official ansible repository devel branch
- `.gitmodules` entry for core modules is set to `https://github.com/bcoca/ansible-modules-core`
- I checked out the _launchd_ branch of in `lib/ansible/modules/core`
- And here is the test playbook I'm running:
  
  ``` yaml
  - name: test launchd support
  hosts: 127.0.0.1
  gather_facts: false
  connection: local
  
  tasks:
    - local_action:
        module: launchd
        name: com.spotify.webhelper
        state: started
        sudo: yes
  ```

Any indications on how to properly test it ( ref #3076 ) ? What's your setup @bcoca ?
Thanks

**Comment by aheinz-fe** [comment]
@tcr-ableton Per https://github.com/ansible/ansible-modules-core/pull/3076#issuecomment-220044801, 

> please test heavily as I don't have a Mac

There aren't any tests in this PR either, so let's just assume that responsibility falls to us.

**Comment by bcoca** [comment]
This is a 1st draft and since I don't have access for a Mac I really cannot test. 

I mostly composed this from  @tcr-ableton's submission to service module  + reading of the man page. 

Since then I've been told that launchd has changed and that the commands I use are deprecated, but also the only ones that work across versions ... so it is very probable that we'll need to build in some code to deal with different versions in the future.

**Comment by tcr-ableton** [comment]
Hehe, then I'll try to make it work @bcoca and will post advancements here then!

Also, I had initially used these legacy command for the exact reason you mention: they ensure backward compatiblity, and are far more easy to manipulate/grasp compared to the new ones. So maybe it's a good enough starting point to use the legacy, and update the module if they're marked as deprecated in the future.

**Comment by tcr-ableton** [comment]
Also, as of today, the service module modification works. So is there a reason from blocking it to go upstream? This separate launchd implementation could be a future feature work.

**Comment by bcoca** [comment]
@tcr-ableton mostly that it should be deprecated soon, in favor of 'per system' plugins, `service:` will still work but will call the underlying specific system plugins (like `package:` currently works).

**Comment by gregdek** [comment]
This PR is a work-in-progress. @bcoca, when you're ready to have this PR reviewed, please remove WIP from the title of the PR.

**Comment by bcoca** [comment]
moved to https://github.com/ansible/ansible/pull/20881

**Pull request closed without merging**
