### PR TITLE
support secure connection on fakes3

### PR DESCRIPTION
**Pull request by yosida95**
I want to use s3 module for S3 compatible storage (Riak CS) with secure connections.  This PR add fakes3s scheme to switch is_secure flag.

### CODE REVIEW

**Comment by juliedavila** [comment]
@yosida95 can you rebase plz?

**Comment by yosida95** [comment]
@defionscode done

**Comment by defionscode** [comment]
Tested. Good to go.

**Comment by juliedavila** [comment]
@yosida95 apologies, we'll need you to rebase again.

**Comment by yosida95** [comment]
@defionscode rebased.

**Pull request merged**
