### PR TITLE
Add boot from volume to nova_compute

### PR DESCRIPTION
**Pull request by tnoff**

### CODE REVIEW

**Comment by tnoff** [comment]
Hi, has anyone gotten the chance to look at this yet?

**Comment by tnoff** [comment]
Fixed the merge conflict, any chance this can get looked at pls?

**Comment by sivel** [comment]
I believe this module is being deprecated in favor of all new modules.

cc @emonty

**Comment by sivel** [comment]
See https://github.com/ansible/ansible-modules-core/pull/1055/files

**Comment by tnoff** [comment]
That works for me, if that one gets merged close mine I suppose :)

**Comment by emonty** [comment]
@tylernorth the os_server module merge, so I'm going to go ahead and close this one. Please break it and let me know if there are any problems ...

**Pull request closed without merging**
