### PR TITLE
Mysql_db single_transaction and quick (#2)

### PR DESCRIPTION
**Pull request by hyperized**
##### Issue Type:
- Feature Pull Request
##### Plugin Name:

mysql_db
##### Summary:

Adding functionality for 'single_transaction' and 'quick' to aid fast dumping in large (InnoDB) databases.
Continuation of https://github.com/ansible/ansible-modules-core/pull/3240 where I somehow managed to mess up my branch completely.
##### Example:

```
- mysql_db:
    state: dump
    name: database
    target: dump.sql.gz
    single_transaction: true
    quick: true
```

### CODE REVIEW

**Comment by hyperized** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @hyperized for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by resmo** [comment]
I hate it when that happens, sorry @hyperized we need a rebase again.

```
git remote add upstream https://github.com/ansible/ansible-modules-core.git # only once if not already done
git checkout devel
git pull --ff-only upstream devel
git fetch
git checkout patch-2
git rebase devel
editor  database/mysql/mysql_db.py
# resolve the conflicts
git add   database/mysql/mysql_db.py
git rebase --continue
git push orgin patch-2 -f
```

**Comment by hyperized** [comment]
@resmo whenever you are ready :).

**Comment by gregdek** [comment]
Thanks @hyperized. To the current maintainers, @Jmainguy please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by resmo** [comment]
Since this is a resubmission of #3240 due some problems while resolving git conflicts, and the #3240 was in 'shipit' by @Jmainguy. I'll handle it as shipit.

**Pull request merged**
