### PR TITLE
Added GovCloud to regions

### PR DESCRIPTION
**Pull request by snoldak924**

### CODE REVIEW

**Comment by jimi-c** [comment]
Hi @snoldak924, more ideally, the ec2_ami_search module should be modified to use the regions list in the common code (`module_utils/ec2.py`) instead, so that this issue doesn't come up in the future.

**Comment by snoldak924** [comment]
That sounds good. I don't know how to do that.

**Comment by juliedavila** [comment]
@snoldak924 could you please rebase when you have a moment?

**Comment by snoldak924** [comment]
I don't know how to do that either. :grimacing:

**Comment by bcoca** [comment]
closing this as it was already added via 30c7f9a7.

**Pull request closed without merging**
