### PR TITLE
vyos_command Document ANSIBLE_VYOS_TERMINAL_LENGTH

### PR DESCRIPTION
**Pull request by samdoran**
##### ISSUE TYPE

 - Docs Pull Request

##### COMPONENT NAME
vyos_command.py

##### ANSIBLE VERSION

```
ansible 2.3.0 (us/devel 5984e3ee9b) last updated 2016/11/18 16:01:35 (GMT -400)
  lib/ansible/modules/core: (vyos-docs 5a4b03d8e0) last updated 2016/11/18 17:36:44 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 9511de1e3d) last updated 2016/11/18 16:31:58 (GMT -400)
  config file = /Users/sdoran/Projects/Vagrant/Ansible Lab/ansible.cfg
  configured module search path = ['/Users/sdoran/Source/ansible/library']
```

##### SUMMARY

Add information on new environment variable added in PR [#18546](https://github.com/ansible/ansible/pull/18546).
Add note on command that should not be run via Ansible.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @samdoran. To the current maintainers, @privateip, @gundalow, @qalthos please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gundalow** [comment]
Hi,
Can you please revert the white space issues. I know what you've done is arguably "correct" though it's now different to all the other modules which makes diffing to spot issues harder.

Updated description to be clearer

**Review by gundalow — CHANGES_REQUESTED** [review]
needs_revision Please revert whitespace changes

**Comment by samdoran** [comment]
Sure thing. On PTO so just now saw this. I'll update it tomorrow.

**Pull request merged**
