### PR TITLE
Adding in Linode private IP support, display group support, missing indempotence fixed

### PR DESCRIPTION
**Pull request by jaddison**
... and optional prepending of "&lt;linode_id&gt;-".

These issues have been brought up before in #7223, #6025, #5991, #5992, #7086. Issues and pull requests have been closed due to moving repositories - it seems like quite a bit has been lost in this move...

### CODE REVIEW

**Comment by abadger** [comment]
@zbal is this something you have time to review?

**Comment by arturmartins** [comment]
This is great!

I like the LinodeID prefix idea, but I bumped into a problem to set the server's /etc/hostname with the exactly same linode name (#1937).

According to **RFC 952** and **RFC 1123**: _Domain names must contain **only letters** (upper or lower case) and **digits**._ 

Therefore I recommend to change `LinodeID_` to `LinodeID-`.

**Comment by arturmartins** [comment]
BTW, the idempotence is only fixed to the scenario that no prefix is used or the complete linode name is given.

**Comment by jaddison** [comment]
Thanks for the comments. The prefix isn't new, just the option to disable
it is. I can change the prefix to use a dash. It shouldn't cause any issues
with existing users, seeing how the indempotence want there before anyhow.

Regarding indempotence itself, I actually noticed that last night. A fix is
forthcoming, along with Linode NodeBalancer support via three new
modules.... In a day or two.

**Comment by jaddison** [comment]
With that last commit, I've address @arturmartins comments and also added in Linode NodeBalancer  (their load balancing 'appliance' functionality) support with 3 modules based largely on @DistilledLtd's efforts.

**Comment by buunguyen** [comment]
:+1: I look forward to see the private IP and display group support gets merged, need them badly.

@jaddison maybe it's a good idea to reissue the Linode NodeBalancer from another branch to a separate PR. That probably makes the job of the reviewers easier and ensures that the private IP fix can get merged even if the balancer needs further revision.

**Comment by tarqd** [comment]
Display group support is essential for getting the most out of this and the dynamic Linode inventory (which can group by display group). Really needs to be merged

**Comment by gregdek** [comment]
So this is essentially three new modules for linode. Is there any reason these shouldn't be in extras rather than core? cc: @ansible/core

**Comment by jaddison** [comment]
The main reason to put them in core was that the original Linode module is there, and these new modules rely on (and this PR changes) it.

Edit: If there was a desire to move all Linode modules to extras, then that would be ok too, but I think it makes sense to group them together.

**Comment by gregdek** [comment]
Thanks @jaddison for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

**Comment by gregdek** [comment]
Sorry for missing this one for so long @jaddison. This one has been sitting for a while because it's a weird corner case that our bots mishandled -- a combination of old modules and new modules in core.

I'm going to close this PR. My recommendation at this point is to split it into multiple PRs:
- A PR in this repository to address the issue in cloud/linode/linode.py; 
- Separate PRs in the Extras repo, one for each of the new modules proposed (since we now strongly discourage new modules in Core).

Thanks, and sorry again for the painful delay.

**Pull request closed without merging**
