### PR TITLE
Don't add included files as arguments on the command line

### PR DESCRIPTION
**Pull request by dagwieers**
##### ISSUE TYPE

- Bugfix Pull Request
##### COMPONENT NAME

unarchive
##### ANSIBLE VERSION

v2.1.0.0 and newer
##### SUMMARY

This means we will have to unarchive the complete archive if a single change is found.
Unfortunately we cannot fix this for `unzip`, the only hope is a pure-python reimplementation.

This fixes problems reported in the comments of #3810

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @dagwieers for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by dagwieers** [comment]
Code is perfectly fine, there is a problem with a unit-test related to a HTTP 500 error unrelated to this change.

ready_for_review or beter shipit ! :-)

**Comment by dagwieers** [comment]
@abadger @jimi-c I think this one ought to be backported to v2.1.2 and merged in v2.2, the story is in the issue tickets. Thanks for considering.

shipit

**Comment by dagwieers** [comment]
@abadger Please merge in stable-2.1 and devel !

**Comment by gregdek** [comment]
Thanks @dagwieers. Since you are one of the maintainers (@dagwieers, @pileofrogs) of this module and you commented with "shipit", we are marking this PR for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by resmo** [comment]
@dagwieers I was not able to cherry-pick without conflict, please provide a PR against stable-2.1 branch.

``` diff
diff --cc files/unarchive.py
index d3aa1e1,95bfe36..0000000
--- a/files/unarchive.py
+++ b/files/unarchive.py
@@@ -499,15 -543,16 +500,26 @@@ class ZipArchive(object)
          return dict(unarchived=unarchived, rc=rc, out=out, err=err, cmd=cmd, diff=diff)

      def unarchive(self):
-         cmd = [ self.cmd_path, '-o', self.src ]
+         cmd = '%s -o "%s"' % (self.cmd_path, self.src)
          if self.opts:
++<<<<<<< HEAD
+             cmd += ' ' + ' '.join(self.opts)
+         if self.includes:
+             cmd += ' "' + '" "'.join(self.includes) + '"'
+         # We don't need to handle excluded files, since we simply do not include them
+#         if self.excludes:
+#             cmd += ' -x ' + ' '.join(self.excludes)
+         cmd += ' -d "%s"' % self.dest
++=======
+             cmd.extend(self.opts)
+          # NOTE: Including (changed) files as arguments is problematic (limits on command line/arguments)
+ #        if self.includes:
+             # NOTE: Command unzip has this strange behaviour where it expects quoted filenames to also be escaped
+ #            cmd.extend(map(shell_escape, self.includes))
+         if self.excludes:
+             cmd.extend([ '-x' ] + self.excludes)
+         cmd.extend([ '-d', self.dest ])
++>>>>>>> c776932... Don't add included files as arguments on the command line (#4626)
          rc, out, err = self.module.run_command(cmd)
          return dict(cmd=cmd, rc=rc, out=out, err=err)
```

**Comment by dagwieers** [comment]
Right, it's quite invasive. Let me see what I can do.

**Pull request merged**
