### PR TITLE
Added support for SunOS to hostname

### PR DESCRIPTION
**Pull request by lenw**

### CODE REVIEW

**Comment by gregdek** [comment]
@lenw Thanks for submitting this pull request. Please accept our apologies for taking so long to review it.

Unfortunately, due to this delay, it appears that the underlying code has changed, and this PR needs to be rebased. If you believe that this PR still applies, please rebase and we will then put it into our (new, faster) community review process as soon as possible.  Again, apologies for the delay and the extra work.

**Comment by lenw** [comment]
I should have a chance next to week to rebuild this

**Comment by gregdek** [comment]
Thanks @lenw.

**Comment by gregdek** [comment]
@lenw any chance you could rebase this soon? Thanks!

**Comment by lenw** [comment]
@gregdek rebased - let me know if thats ok ?

**Comment by lenw** [comment]
Its failing for an unrelated error 

```
0.17s$ python2.4 -m compileall -fq -x 'cloud/' .
Compiling ./system/cron.py ...
  File "./system/cron.py", line 241
    os.chmod(path, 0o644)
                       ^
SyntaxError: invalid syntax
```

**Comment by mscherer** [comment]
I think the PR should be cleaned, as there is some unrelated commits there.

**Comment by gregdek** [comment]
Closing this one because it's quite bitrotted. @lenw please feel free to submit a cleaned up version of this PR.

**Pull request closed without merging**
