### PR TITLE
fix for #14609

### LINKED ISSUE #14609: ec2_group module not using array with rules parameter
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 2.1.0 (devel e35b1cf154) last updated 2016/02/22 11:05:15 (GMT -400)
```
##### Ansible Configuration:

Nothing special
##### Environment:

N/A
##### Summary:

The rules parameter of the ec2_group module is not taking a list as its documentation suggests.
##### Steps To Reproduce:

Use data with the following schema:

```
defaults:
  security_groups:
    ssh:
      rules:
        - proto: tcp
          to_port: 22
          from_port: 22
          cidr_ip: 0.0.0.0/0
```

Here's the play along with debug info showing that the data is properly formatted

```
      - debug: var=item.value                                                  
        with_dict: "{{ defaults.security_groups }}"

     - name: create security groups                                            
        ec2_group:                                                              
          aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"            
          aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"        
          state: present                                                        
          name: "{{ item.key }}"                                                
          description: "{{ item.value.description | default(item.key) }}"      
          region: "{{ defaults.region }}"                                      
          vpc_id: "{{ vpc_info.vpcs[0].id }}"                                  
          rules: "{{ item.value.rules }}"                                      
        with_dict: "{{ defaults.security_groups }}"

```
##### Expected Results:

The ec2_group module should have created the security group.
##### Actual Results:

It blew up. Here's the debug message and error.

```
TASK [debug] *******************************************************************
ok: [localhost] => (item={'value': {u'rules': [{u'to_port': 22, u'from_port': 22, u'cidr_ip': u'0.0.0.0/0', u'proto': u'tcp'}]}, 'key': u'ssh'}) => {
    "item": {
        "key": "ssh",
        "value": {
            "rules": [
                {
                    "cidr_ip": "0.0.0.0/0",
                    "from_port": 22,
                    "proto": "tcp",
                    "to_port": 22
                }
            ]
        }
    },
    "item.value": {
        "rules": [
            {
                "cidr_ip": "0.0.0.0/0",
                "from_port": 22,
                "proto": "tcp",
                "to_port": 22
            }
        ]
    }
}

TASK [create security groups] **************************************************

    failed: [localhost] => (item={'value': {u'rules': [{u'to_port': 22, u'from_port': 22, u'cidr_ip': u'0.0.0.0/0', u'proto': u'tcp'}]}, 'key': u'ssh'}) => {"failed": true, "item": {"key": "ssh", "value": {"rules": [{"cidr_ip": "0.0.0.0/0", "from_port": 22, "proto": "tcp", "to_port": 22}]}}, "msg": "Invalid rule parameter '['"}


```

### PR DESCRIPTION
**Pull request by windowsrefund**
##### Issue Type:
- Bugfix Pull Request
##### Plugin Name:

ec2_group
##### Additional Info

Fixes https://github.com/ansible/ansible/issues/14609

### CODE REVIEW

**Comment by robynbergeron** [comment]
Thanks @windowsrefund for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

**Comment by lightblu** [comment]
+1 confirmation, works for me on tag "v2.0.1.0-0.2.rc2" but is broken on develop.

**Comment by gregdek** [comment]
Thanks @windowsrefund for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

**Comment by windowsrefund** [comment]
This exists in devel now

**Pull request closed without merging**
