### PR TITLE
Added get_url header support

### PR DESCRIPTION
**Pull request by danpilch**
Added the ability to pass custom http headers to the fetch_url method.

### CODE REVIEW

**Comment by mplushnikov** [comment]
+1 for header support!

**Comment by gregdek** [comment]
@jpmens Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please give it a +1; at that point, we will add the “priority_reviewed” flag to this PR, which will move it to the top of our queue for potential inclusion.

**Comment by gregdek** [comment]
@danpilch looks like this has developed merge conflicts while waiting for review. If you could rebase, we will put it back into community review. Sorry for the delay and the extra work.

**Comment by jpmens** [comment]
Looks good to me: +1

**Comment by bcoca** [comment]
still needs rebase

**Comment by danpilch** [comment]
Rebased.

**Pull request merged**
