### PR TITLE
mysql_user: Fix database table quoting in privileges_unpack()

### PR DESCRIPTION
**Pull request by towolf**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

mysql_user
##### ANSIBLE VERSION

```
ansible-playbook 2.2.0 (devel 3aae0b8a6b) last updated 2016/06/03 10:53:57 (GMT +200)
  lib/ansible/modules/core: (fix_quoting_of_privs_database_table 0ee8a30d51) last updated 2016/06/03 12:13:02 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD b0aec50b9a) last updated 2016/06/01 14:11:22 (GMT +200)
  config file = /home/towolf/src/ansible/users/tobias.wolf/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

In Ansible 2.x this module gives `changed = True` for all privileges
that are specified including a table with

```
priv: "database.table:GRANT"
```

Mysql returns escaped names in the format

```
`database`.`tables`:GRANT
```

However in PR #1358, which was intended to support dotted database names
(a crazy idea to begin with), the quotes for the table name were left
out, leading to `curr_priv != new_priv`.

This means that the idempotency comparison between new_priv and
curr_priv is always 'changed'.

This PR re-introduces quoting to the table part of the priv.

### CODE REVIEW

**Comment by towolf** [comment]
@Jmainguy please merge this to fix up your PR https://github.com/ansible/ansible-modules-core/pull/1358.

I'm surprised that since a year npbody has complained about this, since it would never show "ok green".

**Comment by gregdek** [comment]
Thanks @towolf. To the current maintainers, @Jmainguy please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by ghost** [comment]
@Jmainguy this does finish out the fix for that issue from about a year ago. Would recommend to shipit

**Comment by towolf** [comment]
@Jmainguy please review soon.

**Comment by Jmainguy** [comment]
Hey sorry for the delay. I spent a few hours reviewing this (getting my test env working most of the time) and it looks good to me. I confirmed the bug is present in current devel, and that this change will fix it (I had to do a rebase against devel for the unit tests to pass for some reason). 

I added some new unit tests to catch this going forward.

https://github.com/ansible/ansible/pull/17328

Nice work towolf++

:shipit:

**Pull request merged**
