### PR TITLE
Add an option lock_wait to the apt module

### LINKED ISSUE #4717: apt: wait for lock
##### ISSUE TYPE
- Feature Idea
##### COMPONENT NAME
- apt
##### ANSIBLE VERSION

Any, but most likely 2.x branch
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

Debian family Linux running apt package management
##### SUMMARY

This is a feature request but also works around a problem that is very common when manipulating apt packages/repositories on a given host from multiple instances of apt.

Currently if there is an instance working with apt (via ansible apt module or not) there is a lock which is being held exclusively and as such no other apt instance can get a hold of. The result is that if there's a second instance of apt which tries to acquire the lock it gets an instant failure. In the case of doing this via ansible the result is:

```
msg: Failed to lock apt for exclusive operation
```

This is the default apt behavior and as far as I can tell there is not way to pass a flag to apt command line, or apt configuraion, to tell it to **wait** for the lock to be released and then only timeout after a certain period of time.

It would be very useful if ansible's apt module itself was to provide such a feature. Say an optional flag - for example `lock_wait=60` which would make ansible try to acquire the lock every second for X seconds and eventually timing out. This way if two ansible playbooks running at the same time are trying to use the apt repository they will have much higher chance of succeeding.

Currently one of them errors out only so that the user retry the entire playbook .
##### STEPS TO REPRODUCE

Run two ansible instances each utilizing the apt module at the very same time - one of them will fail with the above error.
##### EXPECTED RESULTS

If we have this feature in ansible then we don't need to wrap each individual playbook's apt calls with retries and have it built-in the apt module itself.

### PR DESCRIPTION
**Pull request by mrLarbi**
##### ISSUE TYPE

- Feature Pull Request
##### COMPONENT NAME

apt
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

Add an option to the apt module to wait a certain amount of time for the dpkg lock.

Fixes  #4717 

```

```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @mrLarbi for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by mrLarbi** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @mrLarbi for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @mrLarbi for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by mrLarbi** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @mrLarbi for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @mrLarbi for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by mrLarbi** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @mrLarbi for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @mrLarbi for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by mrLarbi** [comment]
ready_for_review

**Pull request closed without merging**
