### PR TITLE
Adding support for conda in ansible

### PR DESCRIPTION
**Pull request by lowks**
##### ISSUE TYPE
- New Module Pull Request
  ##### COMPONENT NAME
- packaging/language
##### ANSIBLE VERSION

```
2.0.0.2
```
##### SUMMARY

Adding support for miniconda packaging in Ansbile

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @lowks for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by lowks** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @lowks for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by jiffyclub** [comment]
@lowks you have not obtained explicit permission to contribute this to ansible or to re-license it, and even if you had I don't think you are allowed to put your copyright on it. The original utility is here: https://github.com/UDST/ansible-conda. Refer to the [license](https://github.com/UDST/ansible-conda/blob/master/LICENSE.txt) there for the appropriate copyright.

**Comment by lowks** [comment]
I am so sorry. There was no one doing anything on it. I did maintain
original author name on it. Only put my name as maintainer as I did add
some code to make it pass the tests. You want me to close the PR ? Again
very sorry

**Comment by lowks** [comment]
@jiffyclub I have written in to udst@urbansim.com to ask for permission to redistribute this module and if they are okay I will proceed, if not I will close this PR down following their wishes. Thank you for the pointer. Again sorry for not doing this first. It slipped my mind.

**Comment by RyanMagnusson** [comment]
Any update on the permission @lowks?

**Comment by lowks** [comment]
I have written to the authors telling them of intent. Got no reply.

**Comment by gundalow** [comment]
Closing, should be moved to the main repo

**Pull request closed without merging**
