### PR TITLE
Update old except syntax to modern version

### PR DESCRIPTION
**Pull request by LinusU**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME
- All of them
##### ANSIBLE VERSION

```
ansible 2.0.1.0
  config file = 
  configured module search path = Default w/o overrides
```
##### SUMMARY

This change updates all occurrences of the, deprecated, old style `except` syntax to the new modern one. The modern one was already used in a few places, but much of the code where lagging behind and using the deprecated one.

The deprecated syntax throws SyntaxError in Python3 so this pull request will bring us a tad bit closer to python3 compatibility.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @LinusU for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by sivel** [comment]
Ansible supports Python 2.4 on target machines. This change breakers python24 compatibility.  As such, I'm goi g to go ahead and close this out.

**Comment by LinusU** [comment]
@sivel There is 117 occurrences of the new style though, so then we probably want to change those to the old one.

It's very unfortunate though since this makes it incompatible with Python 3. Ubuntu has shipped their new LTS now which only comes with python3, thus ansible is currently unable to orchestrate Ubuntu machines unless you install python2 manually on them beforehand.

Is there any plans to start supporting python 3 in addition to python 2? Why is the support for 2.4 in place, is it still necessary? or is it time to bump it to a newer 2.x release?

**Comment by LinusU** [comment]
All of these distros ship with python 2.6:

| Distro | Release |
| --- | --- |
| Ubuntu 9.04 | Apr 2009 |
| Fedora 11 | Jun 2009 |
| Ubuntu 10.04 LTS | Apr 2010 |
| RHEL 6.0 | Nov 2010 |
| Debian Squeeze | Feb 2011 |
| Scientific Linux 6.0 | Mar 2011 |
| CentOS 6.0 | July 2011 |

If we could limit the 2.x support to 2.6 or newer, it would be trivial to move towards 2.x and 3.x compatibilty within the same source

**Comment by sivel** [comment]
We have plans on adding python3 support, and have methods to ensure compatibility with Python 2.4.

Look for more improvements in the Ansible 2.2 release.

We have no current plans on dropping Python 2.4 in the near future, primarily due to wide spread use of RHEL5.

**Comment by LinusU** [comment]
@sivel That sounds very interesting, how can I, and the rest of the community, help with this? What are the methods to ensure compatibility? Is there a branch where work against this is being carried out? Any issues/pull requests where it's being discussed?

**Pull request closed without merging**
