### PR TITLE
rackspace: set headers when uploading files to CF.

### PR DESCRIPTION
**Pull request by vmihailenco**
Otherwise CDN (Akamai) downloads file without the headers. The sequence
is following:
1. Ansible uploads file to CF.
2. Akamai downloads the file and caches it in CDN.
3. Ansible sets headers.

As a result Akamai serves file without headers.

This is backwards incompatible change, because headers keys are not
prefixed with `x-object-meta-`. Which allows user to set headers like
`Access-Control-Allow-Origin`.

### CODE REVIEW

**Comment by sivel** [comment]
dupe of #1003 which I more in favor of due to less changes

**Comment by vmihailenco** [comment]
No, I am the author of https://github.com/ansible/ansible-modules-core/pull/1003 and it does not fix situation when Akamai does not see headers after upload, because Ansible did not set them yet.

**Comment by sivel** [comment]
I'll try to review this soon.  My first step will be writing a full series of tests for this module before validating these changes.

**Comment by gregdek** [comment]
@sivel friendly ping. :)

**Comment by gregdek** [comment]
@sivel another friendly ping :)

**Comment by gregdek** [comment]
@sivel ping

**Comment by mmcdaris** [comment]
:+1: It would be great to get this one merged! :)

**Comment by phumpal** [comment]
lgtm. @sivel - any chance we can get this merged soon-ish? been using this fix for ~5 months.

**Comment by sivel** [comment]
This PR contains merge conflicts that will first need to be addressed.  After that I will continue working towards properly testing the changes.

**Comment by phumpal** [comment]
Cool, thanks for the update!

**Comment by zefer** [comment]
@sivel who is responsible for fixing the merge conflicts? I don't want us all to be waiting for somebody else :)

**Comment by sivel** [comment]
The submitter is responsible for handling merge conflicts.

**Comment by gregdek** [comment]
Looks like we missed this one in our previous rebase triage. Sorry about that.

@vmihailenco If you believe that this PR still applies, please rebase and we will put it into our community review process as soon as possible. 

Once you have rebased this PR, please add a comment with the text "ready_for_review" and we will continue with the review process.  Thanks!

**Comment by vmihailenco** [comment]
@gregdek I've rebased this PR against devel branch, but I can't properly test this since we migrated to S3+CF :/ So feel free to close this PR.

**Comment by phumpal** [comment]
@gregdek - as @vmihailenco has mentioned we migrated off CF to S3 so we don't have a reliable means of testing. 

However, I think it would be beneficial if this were patched for other users. 

What else is needed to complete the review process except the `"ready_for_review"` text?

**Comment by gregdek** [comment]
Well, since it's in core, we really do need testing, and @sivel has committed to the testing, so I'm going to put this into community_review and we'll wait for @sivel.

**Comment by gregdek** [comment]
Thanks @vmihailenco. @angstwad please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by robynbergeron** [comment]
@angstwad This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
@angstwad still waiting on your review.  Please comment with text 'shipit' or 'needs_revision' as appropriate. If we don't hear from you within 14 days, we will start to look for additional maintainers for this module.

**Comment by gregdek** [comment]
(also cc @sivel for advice here)

**Comment by sivel** [comment]
@angstwad is no longer a Rackspace employee.  I will take over, however I cannot do so immediately, but will attempt to look at this more within the next 2 weeks.

**Comment by gregdek** [comment]
OK, thanks @sivel.

**Comment by gregdek** [comment]
@sivel This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by sivel** [comment]
# Merged

Hi!

This has been merged in, and will also be included in the next major release.

If you or anyone else has any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Pull request merged**
