### PR TITLE
add vm disk editing

### PR DESCRIPTION
**Pull request by tapanswain-zz**
need to add new state for adding disk to exiting  vm .

### CODE REVIEW

**Comment by bcoca** [comment]
what is this?

**Comment by tapanswain-zz** [comment]
please  find the issue here. 

https://github.com/ansible/ansible-modules-core/issues/980

**Comment by bcoca** [comment]
it seems you got a bunch of unrelated commits in the request, clean up and resubmit

**Comment by abadger** [comment]
@tapanswain Perhaps you opened this pull request for the wrong branch?  It appears to be asking to merge our stable-1.9 branch into our devel branch (which we wouldn't do... we cherry-pick commits in devel into 1.9 not the other way around).  I looked at the list of commits and didn't see any from you which is what leads me to believe you submitted the PR for the wrong branch.

**Comment by tapanswain-zz** [comment]
Hi  All,

I am from perl background and use perl sdk for automating the things.

I am recently started  using ansible , while going through  vsphere_guest.py . I could not get the logic how to add disk to exciting vm.

def reconfigure_vm(vsphere_client, vm, module, esxi, resource_pool, cluster_name, guest, vm_extra_config, vm_hardware, vm_disk, vm_nic, state, force):

if vm_hardware['memory_mb']: -- it works

if vm_hardware['num_cpus']: -- it works

but where you are call for disk edit , i could see vm_disk parameter in the function. There is no call for this.

please find the link for  perl code,  Need  your help here  to make this working in  vsphere_guest module.
https://github.com/tapanswain/vmware-sdk/blob/master/VMUtil.pm
https://github.com/tapanswain/vmware-sdk/blob/master/vdiskcreate-updated.pl https://github.com/tapanswain/vmware-sdk/blob/master/vdiskcreate-updated.pl

Tapan

**Comment by bcoca** [comment]
so I'm closing this request as it seems to be a bad branch, @tapanswain feel free to reopen with a branch with your actual changes.

**Comment by aioue** [comment]
As of 1.9.1 nothing apart from CPU and RAM can be changed when reconfiguring or launching from a template. This would help bring some of that functionality into Ansible.

**Pull request closed without merging**
