### PR TITLE
Bulk spelling improvement to modules-core

### PR DESCRIPTION
**Pull request by gundalow**
##### ISSUE TYPE
- Docs Pull Request
##### COMPONENT NAME

eos_command
# Plus lots of others, though I don't think it's useful to ping everybody
##### ANSIBLE VERSION

```
ansible 2.3.0 (devel aa1ec8af17) last updated 2016/10/07 11:07:23 (GMT +100)
  lib/ansible/modules/core: (devel 149f10f8b7) last updated 2016/10/07 11:07:26 (GMT +100)
  lib/ansible/modules/extras: (devel cc2651422a) last updated 2016/10/07 11:07:27 (GMT +100)
```
##### SUMMARY

Lots of typo fixes, no functional changes.
The aim was to improve the module documentation and examples, though to be reasonably happy that I've got most of those I needed to fix the comments in code.

There are no doubt more spelling mistakes/typos this does make a substantial improvement

This will fix some issues with documentation generaion such as:
- Correcting typos of `returned:` in the `RETURN` documentation section
- Network examples should use `wait_for` 
- Formatting issues `M(!)` -> `C(M(!))`

---

This change is [Reviewable](https://reviewable.io/reviews/ansible/ansible-modules-core/5225)

### CODE REVIEW

**Comment by gundalow** [comment]
CI failing with

```
2016-10-11 10:15:06 + ansible-validate-modules --exclude '/utilities/|/shippable(/|$)' .
2016-10-11 10:15:14 ./network/netvisor/pn_trunk.py
============================================================================
2016-10-11 10:15:14 ERROR: version_added for new option (pn_unknown_mcast_level) should be 2.3. Currently 0.0
2016-10-11 10:15:14 ERROR: version_added for new option (pn_unknown_ucast_level) should be 2.3. Currently 0.0
============================================================================
2016-10-11 10:15:14 ./network/nxos/nxos_ntp_options.py
============================================================================
2016-10-11 10:15:14 ERROR: version_added for new option (stratum) should be 2.3. Currently 0.0
```

**Comment by gregdek** [comment]
Thanks @gundalow for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gundalow** [comment]
We can ignore the shippable failure. Once this has been merged & submodules ref updated CI will pass again.

**Comment by gundalow** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @gundalow for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request merged**
