### PR TITLE
Added register AMI from volume snapshot feature

### PR DESCRIPTION
**Pull request by patlachance**
Hello, please find a proposal for a new feature to allow AMI creation 'from volume snapshot', in addition to the existing 'from a running instance' feature.

### CODE REVIEW

**Comment by gregdek** [comment]
@patlachance Thanks for submitting this pull request. Please accept our apologies for taking so long to review it.

Unfortunately, due to this delay, it appears that the underlying code has changed, and this PR needs to be rebased. If you believe that this PR still applies, please rebase and we will then put it into our (new, faster) community review process as soon as possible.  Again, apologies for the delay and the extra work.

**Comment by patlachance** [comment]
rebase done.

**Comment by patlachance** [comment]
rebase done.

**Comment by patlachance** [comment]
Rebase done! Sorry for the delay

**Comment by patlachance** [comment]
Is there anythinig else required to merge this request?

**Comment by bcoca** [comment]
cc @scicoin-project @defionscode @bennojoy  for review

**Comment by bennojoy** [comment]
@patlachance  #1786 seems to add the same functionlity and a bit more, can you please give it a try.

**Comment by gregdek** [comment]
Thanks @patlachance for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

**Comment by robynbergeron** [comment]
@patlachance A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes.

**Comment by gregdek** [comment]
@patlachance Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If we don't hear from you within another 14 days, we will close this pull request.

**Comment by gregdek** [comment]
Closing due to contributor inactivity.

**Comment by patlachance** [comment]
Sorry for delay, I rebased the code and create a new p/r https://github.com/ansible/ansible-modules-core/pull/4075

**Pull request closed without merging**
