### PR TITLE
docker_image: added build arguments support

### PR DESCRIPTION
**Pull request by kis8ya**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

docker_image
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel cc61531a74) last updated 2016/05/16 18:06:28 (GMT +300)
```
##### SUMMARY

Implements #2408 (ARG docker keyword support).
Changes from #2699 PR.

### CODE REVIEW

**Comment by chouseknecht** [comment]
+1

**Comment by gregdek** [comment]
Thanks @kis8ya for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @kis8ya for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by kis8ya** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @kis8ya for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by jlec** [comment]
LGTM, could we get this merged please?

**Comment by gregdek** [comment]
Thanks @kis8ya for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by kis8ya** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @kis8ya for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @kis8ya for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by simono** [comment]
I guess this was fixed with #4349

**Comment by kis8ya** [comment]
duplicates #4349

**Pull request closed without merging**
