### PR TITLE
Fixings issue #69 where S3 get operations needed too many perms

### LINKED ISSUE #69: s3: Unnecessary bucket_check condition while getting an object from s3
Hi There,

I was advised here: https://github.com/ansible/ansible/issues/8123 to open a separate issue on newly separated repos.

Summary:

AWS IAM policy enables us to restrict users to specific file or folder in a bucket. While S3 get object operation is successful from other tools, ansible s3 module fails and returns an error Target bucket not found.

The operation succeeds when list bucket rights are provided to that IAM user.

Thanks!

### PR DESCRIPTION
**Pull request by juliedavila**
##### Issue Type:

Bugfix pull request
##### Plugin Name:

s3
##### Summary:

Fixes: https://github.com/ansible/ansible-modules-core/issues/69

Previously it was mandatory for S3:ListBucket permissions to exist on the IAM policy of the requesting entity in order to do a GET operation. This introduces a new param `validate_objects` which allows to for more restricted roles/users/groups to still be able to do `GET` operations against a key in a bucket.

The default behavior in `boto` is to do a verification that the target bucket and key objects exists and then establishes an object based on the info retrieved from that query. When `validate=False` is set on the various S3 calls it skips the validation and makes an object from "local" truth.

Since there is no validation in the prior points, there is an additional exception handler in the function `download_s3file` that will let the user know if the bucket or key does not exist.
##### Example:

``` yaml
   - name: testing s3 get
     s3dev:
       region: us-east-1
       validate_objects: no
       bucket: ansible-lockdown-store
       object: Vagrantfile
       dest: /tmp/Vagrantfile
       profile: limited
       mode: get
```

### CODE REVIEW

**Comment by resmo** [comment]
Thanks @defionscode for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

**Comment by juliedavila** [comment]
René! Welcome to the team!

**Comment by resmo** [comment]
@defionscode thx! Didn't recognize your github handle, now I know. ;)

**Comment by JoelGilliland** [comment]
I've been using my own out of date version of this module for a while now, so this is much appreciated. 

However, there's permission cases where I wouldn't want to validate the bucket, but would still want to validate the key as I believe the error code returned by S3 may be different. The latest version I use locally does validate=key/bucket/both/none with default of both. Maybe this is overkill, not sure.

Also, not sure if it's the place of this module to let the user know that when using overwrite=different will validate the key whether or not they have validate_objects=false set as it's required to get the etag. Something to think about though

One last thing, since keysum validates by default, and the operations are out of order in the "put" block, the operation will still fail if the user does not have list permissions. I've fixed this in my version(which also cuts down on API calls to S3). I'll try to finish things up and test this weekend with mine and link here or put in a PR.

**Comment by JoelGilliland** [comment]
Here is what I've been working on: https://github.com/JoelGilliland/ansible-modules-core/blob/s3-validate/cloud/amazon/s3.py I had to switch the connect statement back to the old way as the one committed to devel does not work on my VM. I have started writing some tests to try to cover possible scenarios using the S3 module at https://github.com/JoelGilliland/ansible-s3-tests.

**Comment by gregdek** [comment]
Thanks @defionscode for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@defionscode A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@defionscode Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@defionscode A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@defionscode Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@defionscode A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@defionscode Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@defionscode A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@defionscode Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@defionscode A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@defionscode Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@defionscode A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
