### PR TITLE
Win copy/file/template modules (for ansible-modules-core)

### PR DESCRIPTION
**Pull request by jhawkesworth**
Note these modules also need action plugins for which a separate PR has been created here: https://github.com/ansible/ansible/pull/9611
Both would be required.

### CODE REVIEW

**Comment by cchurch** [comment]
:clap: Sweet! I'll review/test and get back to you.

**Comment by jhawkesworth** [comment]
Thanks Chris, I'll put some notes on the other PR.

**Comment by jhawkesworth** [comment]
@cchurch Just to say I realised I'd missed switching the actual modules to use SHA1 checksums, so I've pushed a change for that now.

**Comment by rasmuswlarsen** [comment]
I'm not sure if this is the correct place to ask this. But are these windows module being added to Ansible?

**Comment by jhawkesworth** [comment]
Questions generally best asked on the mailing lists, but since you are here.

There are two parts to this PR - some modifications were also needed to the
main Ansible project, specifically action plugins needed to support
templating.

My understanding is the Ansible core team want to refactor the action
plugins to remove some repeated code so this was unmerged until they have
had the chance to do so.

**Pull request merged**
