### PR TITLE
Cancel spot requests before fail. 

### PR DESCRIPTION
**Pull request by kai11**
Fix for https://github.com/ansible/ansible-modules-core/issues/2057

### CODE REVIEW

**Comment by kai11** [comment]
@evanccnyc Second attempt. Playbook at https://gist.github.com/kai11/09d9bb952d422348a006

**Comment by evanccnyc** [comment]
This works for me now. Though I am wondering if we want to cleanup the error message, make it more obvious that the spot request was cancelled.

**Comment by kai11** [comment]
Changing message to be more clear is up to you - I'm not native English speaker.
PS. While you're at it, please check https://github.com/ansible/ansible-modules-core/pull/2211 as well.

**Comment by evanccnyc** [comment]
I think its fine on second look.

Anyway worksforme.

**Comment by gregdek** [comment]
Thanks @kai11. @tgerla @lwade please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by robynbergeron** [comment]
@tgerla @lwade This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
Reassigning to @ansible/core for review.

@kai11 sorry for the delay.

**Comment by dmrsol** [comment]
Hello! Any progress?

**Comment by gregdek** [comment]
Thanks @kai11 for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@kai11 A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@kai11 Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@kai11 A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
