### PR TITLE
Add local network type to openstack/os_network

### LINKED ISSUE #5589: os_network provider_network_type should allow 'local'
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
os_network

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file =
  configured module search path = ['/etc/ansible/roles/plugins/library']
```

##### OS / ENVIRONMENT
Ubuntu 16.04

##### SUMMARY
'local' should be a valid provider_network_type in https://github.com/ansible/ansible-modules-core/blob/devel/cloud/openstack/os_network.py#L172

##### STEPS TO REPRODUCE
Create a network with os_network using provider_network_type: local

Use a neutron network plugin like networking_calico which expects to receive 'local' networks: https://github.com/openstack/networking-calico/blob/master/networking_calico/plugins/ml2/drivers/calico/mech_calico.py#L540-L541

##### EXPECTED RESULTS
I expected it to create the network in Neutron with the type I specified.

Maybe this field should not have prescribed types and should simply rely on the Neutron API to filter valid/invalid types as needed?

##### ACTUAL RESULTS
```
fatal: [aio1_utility_container-2d7be198]: FAILED! => {"changed": false, "failed": true, "msg": "value of provider_network_type must be one of: flat,vlan,vxlan,gre, got: local"}
```

### PR DESCRIPTION
**Pull request by omgjlk**
- Bugfix Pull Request

openstack/os_network

```
devel
```

```

```

This type is used by some plugins, such as networking_calico.

Fixes #5589

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks again to @j2sol. This module is going into community review.

We notice that you are one of the maintainers (@emonty, @shrews, @juliakreger, @j2sol, @rcarrillocruz) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by Thingee** [comment]
@j2sol I was noticing "geneve" is another type. http://docs.openstack.org/mitaka/config-reference/networking/networking_options_reference.html#modular-layer-2-ml2-plug-in-configuration-options

**Comment by omgjlk** [comment]
Thanks for noticing. I've updated the PR and commit message to reflect adding geneve as well.

**Review by Thingee — APPROVED** [review]

**Comment by Thingee** [comment]
LGTM

**Comment by gregdek** [comment]
Thanks again to @j2sol for this PR, and thanks @emonty, @shrews, @juliakreger, @j2sol, @rcarrillocruz, @thingee for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Review by Thingee — APPROVED** [review]

**Pull request closed without merging**
