### PR TITLE
fixes issue 871 where vm's are created if exact count is specified but instance state is stopped

### PR DESCRIPTION
**Pull request by bennojoy**
fixes issue 871 where exact count would create new instances if the instane state is stopped or terminated

### CODE REVIEW

**Comment by gregdek** [comment]
@tgerla @lwade Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please give it a +1; at that point, we will add the “priority_reviewed” flag to this PR, which will move it to the top of our queue for potential inclusion.

**Comment by gregdek** [comment]
@bennojoy -- does this PR still apply? If so, can you rebase?

**Comment by gregdek** [comment]
And if you do rebase, please add a comment with the text "ready_for_review" so we can continue with the review process.  Thanks!

**Comment by gregdek** [comment]
@bennojoy A friendly reminder: this pull request has been marked as needing your action, and it hasn't been updated in the last month. 

If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we'll keep it open pending your changes.

If we receive no indication from you within a week, we will close this pull request.

**Comment by robynbergeron** [comment]
@bennojoy Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If we don't hear from you within another 14 days, we will close this pull request.

**Comment by gregdek** [comment]
Closed due to contributor inactivity.

**Pull request closed without merging**
