### PR TITLE
Ability to tag route tables

### PR DESCRIPTION
**Pull request by philm**
I've tested this functionality in a local integration test, in which I checked no tagging vs. these two different formats:

```
# format 1
resource_tags:
  Environment: Dev

# format 2
resource_tags: { "Environment":"Dev" }
```

One thing that isn't addressed is removing tags, but the other resources (e.g. subnets) don't expose that functionality yet either. Will tackle that in a separate, future PR.

### CODE REVIEW

**Comment by bcoca** [comment]
# Rebase Request

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us. 

It looks like the code underneath has changed since this was submitted.  Can you take care of rebasing this for us?
- You should be able to run "git rebase" against this branch to bring it up to date
- Resolve any merge conflicts and test changes
- Push to the same branch and github should update the pull request automatically.

Just as a quick reminder of things, this is a really busy project.  We have over 800 contributors and to manage the queue effectively
we assign things a priority between P1 (highest) and P5.  We'd like to thank you very much for your time!  
We'll work things in priority order, so just wanted you to be aware of the queue and know we haven't forgotten about you!

We will definitely see your comments on this issue when reading this ticket, but may not be able to reply promptly.  You may also wish to join one of our two mailing lists
which are very active:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Thank you once again for this and your interest in Ansible!

**Comment by philm** [comment]
@bcoca, all set.

**Comment by bcoca** [comment]
so trying to test this, I don't see any tags on the route, I see them on the vpc but this worked before this patch

```
- hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - ec2_vpc:
        cidr_block: 172.23.0.0/16
        region: us-east-1b
        resource_tags:
            Environment: "Development"
```

**Comment by juliedavila** [comment]
Looking at the code a bit it looks like the tags get added to the routes only when a VPC is being created. It should be modified such that it can tag pre-existing VPCs as well IMO. Additionally, perhaps this would be better suited as a p/r to the ec2_tag module (assuming tagging routes is unsupported there).

**Comment by philm** [comment]
@nousdefions: excellent point - tagging responsibilities should be only handled by the ec2_tag module, otherwise we have multiple tagging implementations to maintain throughout the codebase. Currently ec2_vpc is only tagging newly created resources and cannot remove tags, whereas ec2_tag already handles multiple scenarios.

We could even prune out the existing tagging functionality in this module. 

Before (with integrated tagging):

```
ec2_vpc:
  state: present
  cidr_block: 172.22.0.0/16
  subnets:
    - cidr: 172.22.1.0/24
      az: us-west-2c
      resource_tags: { "Environment":"Dev", "Tier" : "Web" }
    - cidr: 172.22.2.0/24
      az: us-west-2b
      resource_tags: { "Environment":"Dev", "Tier" : "App" }
    - cidr: 172.22.3.0/24
      az: us-west-2a
      resource_tags: { "Environment":"Dev", "Tier" : "DB" }
```

After (leveraging ec2_tag module):

```
ec2_vpc:
  state: present
  cidr_block: 172.22.0.0/16
  subnets:
    - cidr: 172.22.1.0/24
      az: us-west-2c
    - cidr: 172.22.2.0/24
      az: us-west-2b
    - cidr: 172.22.3.0/24
      az: us-west-2a
register: vpc

ec2_tag:
  resource: "{{ item.id }}"
  tags: 
    Environment: Dev
    Tier: Web
when: item.az == 'us-west-2c'
with_items: vpc.subnets

ec2_tag:
  resource: "{{ item.id }}"
  tags: 
    Environment: Dev
    Tier: App
when: item.az == 'us-west-2b'
with_items: vpc.subnets

ec2_tag:
  resource: "{{ item.id }}"
  tags: 
    Environment: Dev
    Tier: DB
when: item.az == 'us-west-2a'
with_items: vpc.subnets
```

...yes, a bit more code to do the same thing, but it also provides the additional tagging features not baked into ec2_vpc.

I'm going to close this PR. Meanwhile, I also created https://github.com/ansible/ansible-modules-core/pull/585, to be able to return additional details about the route tables, if someone needs to tag them via ec2_tag.

(cc'ing @bcoca)

**Pull request closed without merging**
