### PR TITLE
Update apt.py documentation

### PR DESCRIPTION
**Pull request by asolano**
##### ISSUE TYPE

- Docs Pull Request
##### COMPONENT NAME

apt.py
##### ANSIBLE VERSION

N/A
##### SUMMARY

Use full YAML syntax in the examples.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @asolano for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by resmo** [comment]
LGTM

**Comment by gregdek** [comment]
Thanks again to @asolano for this PR. This PR was reviewed by an Ansible member. Marking for inclusion.

However, we would still appreciate if the maintainer(s) @ansible could look over it.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by bcoca** [comment]
is this just a formatting change?

**Comment by asolano** [comment]
Yes, to encourage people to use native YAML.

**Comment by gregdek** [comment]
@asolano A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by asolano** [comment]
The PR still applies. ready_for_review

**Comment by gregdek** [comment]
Thanks @asolano for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request merged**
