### PR TITLE
git doc: don't prepend ssh:// for ssh repo

### PR DESCRIPTION
**Pull request by lorin**
The github ssh example has ssh:// at the beginning of the url. However, this
doesn't work. It does work if the ssh:// is removed.

### CODE REVIEW

**Comment by abadger** [comment]
Thanks for the fixed example!

# Merged

Hi!

This has been merged in, and will also be included in the next major release.

If you or anyone else has any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Comment by abadger** [comment]
@lorin Actually.... I just tested this and ssh://git@github.com seems to be the correct syntax so I've reverted this:

```
$ cat git.yml
- hosts: localhost
  tasks:
  - git: repo=ssh://git@github.com/abadger/q.git dest=/var/tmp/mytest

$ ansible-playbook git.yml

PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [git repo=ssh://git@github.com/abadger/q.git dest=/var/tmp/mytest] ****** 
ok: [localhost]

PLAY RECAP ******************************************************************** 
localhost                  : ok=2    changed=0    unreachable=0    failed=0 

$ cat git2.yml
- hosts: localhost
  tasks:
  - git: repo=git@github.com/abadger/q.git dest=/var/tmp/mytest
 $ ansible-playbook git2.yml

PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [git repo=git@github.com/abadger/q.git dest=/var/tmp/mytest] ************ 
failed: [localhost] => {"cmd": "/usr/bin/git ls-remote git@github.com/abadger/q.git -t refs/tags/HEAD", "failed": true, "rc": 128}
stderr: fatal: 'git@github.com/abadger/q.git' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

msg: fatal: 'git@github.com/abadger/q.git' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/badger/git.retry

localhost                  : ok=1    changed=0    unreachable=0    failed=1
```

This was with both current devel and 1.8.2.

Let me know if you're seeing something different.
Let me know if you're seeing something different.

**Comment by lorin** [comment]
@abadger Below is what I'm seeing:

```
$ ansible web -m git -a "repo=git@github.com:lorin/mezzanine-example.git dest=/tmp/project accept_hostkey=yes"
web | success >> {
    "after": "ca7399f17a383279e4f9c3e920de029eca5f6bd8",
    "before": null,
    "changed": true
}

$ ansible web -m git -a "repo=ssh://git@github.com:lorin/mezzanine-example.git dest=/tmp/other accept_hostkey=yes"
web | FAILED >> {
    "cmd": "/usr/bin/git ls-remote ssh:********",
    "failed": true,
    "msg": "ERROR: Repository not found.\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.",
    "rc": 128,
    "stderr": "ERROR: Repository not found.\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n",
    "stdout": ""
}
```

I'm running Ansible 1.8.2. I wonder if this depends on what version of git you have installed? I've tested this with git 1.9.1.

**Comment by sivel** [comment]
It should be worth noting that git accepts 2 forms of ssh "URLs"

http://git-scm.com/book/en/v2/Git-on-the-Server-The-Protocols#The-SSH-Protocol

The `ssh://` version only uses `/` characters whereas the "scp" format uses a single `:` to separate host and path.

So you can't just slap a `ssh://` onto the front of a scp style URL, and you can't use a colon `host:path` separator with `ssh://`

**Comment by lorin** [comment]
Whoops, I hadn't realized I had switched the colon with the slash. Thanks, @sivel.

**Pull request merged**
