### PR TITLE
Cloudformation module boto3 rewrite (w/ @tedder)

### PR DESCRIPTION
**Pull request by ryansb**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

cloudformation
##### ANSIBLE VERSION

```
ansible 2.3.0 (devel 5ece97ae5b) last updated 2016/10/17 15:34:16 (GMT -400)
  lib/ansible/modules/core: (ryansb-edit-boto3-rewrite 90dbc1841b) last updated 2016/10/19 11:01:44 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 9897c502a6) last updated 2016/10/17 15:34:17 (GMT -400)
  config file = 
  configured module search path = Default w/o overrides
```
##### SUMMARY

This PR contains modifications to #5230, @tedder's rewrite of the CloudFormation module to boto3. I fixed a couple small issues in the PR (documentation, returned values) but otherwise this is identical to the original PR.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @ryansb for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by tedder** [comment]
@ryansb - thanks. I really appreciate having a second set of eyes, the style/whitespace fixes are good too. Time for `shipit`.

**Comment by ryansb** [comment]
Merged

**Comment by ryansb** [comment]
https://github.com/ansible/ansible-modules-core/compare/953cd915bb567564d951de79167229eec7bc5aa7...cd9e39420bc1676ff7ed84f933e8e4e78c485bef

**Pull request closed without merging**
