### PR TITLE
Update vsphere_guest.py

### PR DESCRIPTION
**Pull request by certinub**
Add an option to move a VM to a different host when reconfiguring
implement esxi['hostname'] option into reconfigure_vm()

### CODE REVIEW

**Comment by gregdek** [comment]
@rhoop Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please give it a +1; at that point, we will add the “priority_reviewed” flag to this PR, which will move it to the top of our queue for potential inclusion.

**Comment by rhoop** [comment]
I won't have time until later in the week.

**Comment by gregdek** [comment]
Thanks @rhoop. As your time allows, of course. :)

**Comment by gregdek** [comment]
@rhoop found any time to review this PR?

**Comment by rhoop** [comment]
I'll look at it today.

**Comment by gregdek** [comment]
@certinub Apologies -- it appears that the underlying code has changed since your submission, and this PR now needs to be rebased. 

If you believe that this PR still applies, please rebase and we will put it into our community review process as soon as possible. 

Once you have rebased this PR, please add a comment with the text "ready_for_review" and we will continue with the review process.  Thanks!

**Comment by gregdek** [comment]
@certinub A friendly reminder: this pull request has been marked as needing your action, and it hasn't been updated in the last month. 

If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we'll keep it open pending your changes.

If we receive no indication from you within a week, we will close this pull request.

**Comment by robynbergeron** [comment]
@certinub Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If we don't hear from you within another 14 days, we will close this pull request.

**Comment by gregdek** [comment]
Closed due to contributor inactivity.

**Pull request closed without merging**
