### PR TITLE
Added reloaded-stopped state to docker module

### PR DESCRIPTION
**Pull request by zachbadgett**
##### Issue Type:
- Feature Pull Request
##### Plugin Name:

docker
##### Summary:

Currently the docker plugin allows a "reloaded" state which recreates a container (if it's different). After it's been reloaded it starts the container; this may not always be the desired state. To solve this I added a reloaded-stopped state which will update the container with the latest image while leaving the container stopped.
##### Example:

```
# example usage
- name: container
  docker:
    name: container
    image: container:latest
    state: reloaded-stopped

- shell: docker cp /config.toml container:/config.toml

- shell: docker restart container
```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @zachbadgett. To the current maintainers, @cove, @softzilla, @smashwilson, @zfil, @ThomasSteinbach please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by zachbadgett** [comment]
Hey @cove, @softzilla, @smashwilson, @zfil, @ThomasSteinbach any update?

**Comment by zachbadgett** [comment]
@gregdek are the owners of the docker plugin inactive?

**Comment by gregdek** [comment]
Selectively active, I would say.

**Comment by gregdek** [comment]
Thanks @zachbadgett. To the current maintainers, @cove, @softzilla, @smashwilson, @zfil, @ThomasSteinbach please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @zachbadgett for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
