### PR TITLE
Add cpu_shares option for docker module

### PR DESCRIPTION
**Pull request by awasilyev**
This PR add cpu_shares option (https://docs.docker.com/engine/reference/run/#cpu-share-constraint) to the docker module.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @awasilyev. @cove @joshuaconner @softzilla @smashwilson please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
@cove @joshuaconner @softzilla @smashwilson @zfil @ThomasSteinbach This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by smashwilson** [comment]
I was a little unsure about defaulting to `0` rather than `None` but that's [consistent with the docker CLI](https://docs.docker.com/engine/reference/run/#runtime-constraints-on-resources). :+1: Looks good to me. 

shipit

**Comment by gregdek** [comment]
Thanks again to @awasilyev for this PR, and thanks @cove @joshuaconner @softzilla @smashwilson @zfil @ThomasSteinbach for reviewing. Marking for inclusion.

**Comment by gregdek** [comment]
Thanks @awasilyev for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts; we may have merged a separate fix. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

**Comment by awasilyev** [comment]
ready_for_review

**Comment by smashwilson** [comment]
Yep, still looks good. shipit

**Comment by robynbergeron** [comment]
Thanks again to @awasilyev for this PR, and thanks @cove @joshuaconner @softzilla @smashwilson @zfil @ThomasSteinbach for reviewing. Marking for inclusion.

**Comment by bcoca** [comment]
cannot add shipit if it still needs rebase

**Comment by awasilyev** [comment]
I will rebase it again, but in case it will be reviewed for a long time again - the second rebase also become obsolete

**Comment by robynbergeron** [comment]
Thanks @awasilyev. @cove @joshuaconner @softzilla @smashwilson @zfil @ThomasSteinbach please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by smashwilson** [comment]
Thanks for your patience, @awasilyev - I know there's a lot of backlog on these sometimes. :+1: Still looks good to me!

shipit

**Pull request merged**
