### PR TITLE
fix opensuse apache2_module always changed=True

### PR DESCRIPTION
**Pull request by robinro**
opensuse 13.2 uses sysconf_addword to implement a2enmod/a2dismod. This outputs `"modulename" already present` and `"modulename" not present` if one wants to add (remove) something that is already (or not) there.
This patch includes those outputs while still allowing the old strings.

### CODE REVIEW

**Comment by gregdek** [comment]
@berendt Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by robinro** [comment]
@gregdek @berendt 
Please let me know if there is anything to add or things to do to help integrate the change into ansible.
I had a look through the checklist. Most of the points are on overall module design and thus don't apply. The ones I found applicable are fulfilled.

**Comment by robinro** [comment]
The merged version updates to the current devel version. It reverts the change done for #2081. See also #2082 for the corresponding discussion.

**Comment by robinro** [comment]
#2417 also fixes this

**Comment by gregdek** [comment]
Closing as dupe of #2417.

HOWEVER: @robinro it looks as though we don't have a community reviewer for this module currently, since #2417 is in core_review. Would you be willing to take over maintainership of this module? If so, ping me and we can discuss. Thanks!

**Pull request closed without merging**
