### PR TITLE
Fixed issues with iterating over ec2_group rules

### PR DESCRIPTION
**Pull request by sgnn7**
Sometimes the rules would end up being a string instead of a dict so the
iteration would fail rule validation so now we <del>explicitly check if
that's the case and convert the str to a dict.</del> parse the args properly.

<del>PS: We can't use json module since the string has single quotes instead
of double quotes.</del>

Edited to match the new PR code

### CODE REVIEW

**Comment by timbyr** [comment]
I believe this is caused by the argument_spec relying on defaults.

Updating it from 

```
            rules=dict(),
            rules_egress=dict(),
```

 to 

```
            rules=dict(type='list'),
            rules_egress=dict(type='list'),
```

Fixes this issue without the need for ast

**Comment by sgnn7** [comment]
@timbyr I'm new to the codebase so I didn't know about the `type` param - let me test that out and update the PR.

**Comment by sgnn7** [comment]
@timbyr That worked! Updated the PR.

**Comment by robynbergeron** [comment]
Thanks @sgnn7 for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

**Comment by timbyr** [comment]
Already resolved by #3117

**Comment by gregdek** [comment]
Thanks @sgnn7 for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

**Comment by gregdek** [comment]
Closing as dupe of #3117.

**Pull request closed without merging**
