### PR TITLE
Make it clear that the dest path delimiters must be escaped

### PR DESCRIPTION
**Pull request by slimandslam**
Make it clear that the dest path delimiters must be escaped

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @slimandslam. @brianlloyd please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
@brianlloyd This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by brianlloyd** [comment]
shipit

**Comment by gregdek** [comment]
Thanks again to @slimandslam for this PR, and thanks @brianlloyd for reviewing. Marking for inclusion.

**Pull request merged**
