### PR TITLE
Add EC2 facts from dynamic instance metadata

### PR DESCRIPTION
**Pull request by gnethercutt**
Adds data from [dynamic metadata](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html#instancedata-dynamic-data-retrieval).

| Data | Version introduced | Description |
| --- | --- | --- |
| fws/instance-monitoring | 2009-04-04 | Value showing whether the customer has enabled detailed one-minute monitoring in CloudWatch. Valid values: {enabled , disabled} |
| instance-identity/document | 2009-04-04 | JSON containing instance attributes, such as instance-id, private IP address, etc. |
| instance-identity/pkcs7 | 2009-04-04 | Used to verify the document's authenticity and content against the signature. |
| instance-identity/signature | 2009-04-04 | Data that can be used by other parties to verify its origin and authenticity. |

```
        "ansible_ec2_fws_instance_monitoring": "enabled", 
        "ansible_ec2_instance_identity_document_accountId": "123456789012", 
        "ansible_ec2_instance_identity_document_architecture": "x86_64", 
        "ansible_ec2_instance_identity_document_availabilityZone": "us-east-1a", 
        "ansible_ec2_instance_identity_document_billingProducts": null, 
        "ansible_ec2_instance_identity_document_devpayProductCodes": null, 
        "ansible_ec2_instance_identity_document_imageId": "ami-ab9aa0d6", 
        "ansible_ec2_instance_identity_document_instanceId": "i-25b93888", 
        "ansible_ec2_instance_identity_document_instanceType": "m3.medium", 
        "ansible_ec2_instance_identity_document_kernelId": null, 
        "ansible_ec2_instance_identity_document_pendingTime": "2015-04-16T22:32:03Z", 
        "ansible_ec2_instance_identity_document_privateIp": "172.18.42.12", 
        "ansible_ec2_instance_identity_document_ramdiskId": null, 
        "ansible_ec2_instance_identity_document_region": "us-east-1", 
        "ansible_ec2_instance_identity_document_version": "2010-08-31", 
```

instance-identity/document is a json blob, thus the addition of the _json_ dependency.  There were already some shenanigans around name mangling and treating the security_groups array differently, so I tackled the json document in the same manner.  I'd like to come back with some refactoring cleanup, but this should guarantee backwards compatibility for all ec2_facts users while giving them more properties with the same naming convention.

Notably this adds availability to the AWS account id and region without resorting to extracting it from other properties which should probably be treated opaquely.

### CODE REVIEW

**Comment by gregdek** [comment]
@silviud Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please give it a +1; at that point, we will add the “priority_reviewed” flag to this PR, which will move it to the top of our queue for potential inclusion.

**Comment by gregdek** [comment]
@silviud friendly ping if you have time to review this PR.

**Comment by gregdek** [comment]
@silviud are you available to review this PR?

**Comment by gregdek** [comment]
Looks like @silviud is unavailable to review, so putting this into core_review. It may take a while to review this; thanks for your patience here.

**Comment by gregdek** [comment]
Thanks @gnethercutt. To the current maintainers, @silviud please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @gnethercutt for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @gnethercutt for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@gnethercutt A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@gnethercutt Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@gnethercutt A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@gnethercutt Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@gnethercutt A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@gnethercutt Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@gnethercutt A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@gnethercutt Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@gnethercutt A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@gnethercutt Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@gnethercutt A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@gnethercutt Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gnethercutt** [comment]
Yep, I'll clean up the merge conflicts, retest, then update the PR.

**Comment by gnethercutt** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @gnethercutt. To the current maintainers, @silviud please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
