### PR TITLE
prevents groups from being wiped out on user update on OS X

### PR DESCRIPTION
**Pull request by domibarton**
This merge request will fix the issue #2537, where the `user` module will reset the users primary group on Mac OS X when no `group` parameter is defined.

Please also have a look at the [origin issue](https://github.com/ansible/ansible/issues/13266).

### CODE REVIEW

**Comment by bcoca** [comment]
in current devel this seems to be fixed by : 

```

    def _make_group_numerical(self):
        '''Convert SELF.GROUP to is stringed numerical value suitable for dscl.'''
        if self.group is None:
            self.group = 'nogroup'

```

which seems better as the function is called from both create and modify user

**Comment by bcoca** [comment]
hmm, nvmd, that is also in 1.9, the diff just pushed it down

**Comment by gregdek** [comment]
@sfromm Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by gregdek** [comment]
@sfromm This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by tima** [comment]
@gregdek I think (someone correct me if I'm wrong) this was resolved by the commit @nitzmahone made to close out #2537. I'm not sure why this PR didn't get marked merged here. @nitzmahone's commit looks identical to the diff of what's here.

**Comment by nitzmahone** [comment]
Yeah, the way I merged it didn't close the PR, but yes, it's fixed and merged to both devel and 2.0-stable.

**Pull request closed without merging**
