### PR TITLE
add ability to pass extra parameters when using easy_install

### PR DESCRIPTION
**Pull request by reynn**
##### ISSUE TYPE

- Feature Pull Request
##### COMPONENT NAME

easy_install
##### ANSIBLE VERSION

```
2.1.1.0
```
##### SUMMARY

The easy_install module does not allow additional arguments to be passed similar in a way to the pip module, this means you cannot for example install from easy_install from a custom index.  This causes easy_install to fail when there is no general internet access.

```
easy_install: name=pip extra_args="-i http://example.customindex.com/pypi-cache/simple"
```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @reynn. To the current maintainers, @mattupstate please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @reynn for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by reynn** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @reynn. To the current maintainers, @mattupstate please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
