### PR TITLE
CommandModule: detect change based on update to some file

### PR DESCRIPTION
**Pull request by quinot**
When generating a file by running an ad hoc command on the target
host, allow detection of change based to a change in the contents
of a named file specified as a parameter to the action
(updates=<filename>).

Supersedes #296.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @quinot for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

**Comment by towolf** [comment]
This looks good and useful to me. Why has no-one commented on this yet?

@bcoca Please review.

What we need in addition to change detection is support for check mode. I'm gonna work on a PR for check mode. It would execute a "check" command to see if the main command would give a change.

**Comment by bcoca** [comment]
I have several issues with this PR I think it is too much of a corner case that can easily be dealt with by stat, w/o the issues of the non availability of md5.

**Comment by gregdek** [comment]
Thanks @quinot for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@quinot A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@quinot Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@quinot A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by quinot** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @quinot for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @quinot for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by quinot** [comment]
AFAICT the build failure is an artefact not caused by this change.

**Comment by towolf** [comment]
You can try force push to trigger the CI

**Comment by quinot** [comment]
I was mistaken, the error _was_ actually a legit one. Commit amended.

**Comment by quinot** [comment]
Build now succeeds
ready_for_review

**Comment by gregdek** [comment]
Thanks @quinot for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
