### PR TITLE
Use HostConfig object when creating container with Docker Remote API > 1.15

### LINKED ISSUE #1707: Update docker module to support newer versions of the server (mem_limit has been moved to host_config in API version 1.19)
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.9.2
##### Environment:

Running from: OS X 10.95
Managing: Ubuntu 15.04
##### Summary:

Starting a container results in the error "mem_limit has been moved to host_config in API version 1.19" starting container
##### Steps To Reproduce:

Using Ansible to configure starting a Jenkins container 

```
- name: Jenkins data directory
  command: "docker create -v {{HOME}}/.jenkins:/var/jenkins_home:rw -v {{HOME}}/.ssh:/.ssh:ro -v {{HOME}}/.ssl:/.ssl:ro --name jenkins_data busybox"
  sudo: yes
  when: docker_containers.stdout.find('jenkins_data') == -1


- name: Start Jenkins container
  docker: 
    name: jenkins_master
    image: mediaplayout/jenkins
    volumes_from: jenkins_data
    pull: always
    state: started
    ports: 
      - 8080:8080
      - 50000:50000
  sudo: yes  
```

I'm getting the error

```
BECOME-SUCCESS-nnwoeoumeitqznkijaqrhohdpyhijpbr
Traceback (most recent call last):
  File "/home/mediaplayout/.ansible/tmp/ansible-tmp-1436530356.59-234590896125756/docker", line 3132, in <module>
    main()
  File "/home/mediaplayout/.ansible/tmp/ansible-tmp-1436530356.59-234590896125756/docker", line 1494, in main
    started(manager, containers, count, name)
  File "/home/mediaplayout/.ansible/tmp/ansible-tmp-1436530356.59-234590896125756/docker", line 1354, in started
    created = manager.create_containers(delta)
  File "/home/mediaplayout/.ansible/tmp/ansible-tmp-1436530356.59-234590896125756/docker", line 1227, in create_containers
    containers = do_create(count, params)
  File "/home/mediaplayout/.ansible/tmp/ansible-tmp-1436530356.59-234590896125756/docker", line 1217, in do_create
    result = self.client.create_container(**params)
  File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 237, in create_container
    volume_driver
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/utils.py", line 546, in create_container_config
    'mem_limit has been moved to host_config in API version 1.19'
docker.errors.InvalidVersion: mem_limit has been moved to host_config in API version 1.19
```

This task does work:

```
- name: Register running Docker containers
  register: running_docker_containers
  command: docker ps
  sudo: yes

- name: Start Jenkins container
  command: docker run -d -p 8080:8080 -p 50000:50000 --volumes-from jenkins_data --name jenkins_master mediaplayout/jenkins
  sudo: yes
  when: running_docker_containers.stdout.find('jenkins_master') == -1
```

### PR DESCRIPTION
**Pull request by larsks**
This is mlosev's patch (from #1208), rebased against devel as of
2790af2.  It resolves #1707, which was caused by an API incompatibility
between the docker module and server API version 1.19.

### CODE REVIEW

**Comment by bcoca** [comment]
next time let me know you opened a new PR, though you can avoid this by just pushing with -f to the old branch

**Comment by larsks** [comment]
I didn't think I could replace somebody else's PR.  I'll have to look into that for next time.  Thanks!

**Comment by dgromov** [comment]
It seems like this commit breaks setting the mem_limit. It removes it from the create_container call so versions <1.19 don't work anymore and never sets it in the host_config so 1.19 doesn't work either.

**Comment by larsks** [comment]
@dgromov must have gotten lost in the rebase! I will try to fix that today, unless you get to it first.

**Pull request merged**
