### PR TITLE
- fix check_mode test to avoid errors

### PR DESCRIPTION
**Pull request by leehuk**
Fix for #2811, which appears to have been introduced by #2774 @Jmainguy / @koichirok

### CODE REVIEW

**Comment by Jmainguy** [comment]
@leehuk change line 330 to return True and then this is good to merge

**Comment by leehuk** [comment]
Thanks @Jmainguy, I've added that fix too

**Comment by Jmainguy** [comment]
@leehuk Thank you for finding and fixing this bug.

@bcoca 'shipit'

**Comment by gregdek** [comment]
Thanks @leehuk. @Jmainguy please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
Thanks again to @leehuk for this PR, and thanks @Jmainguy for reviewing. Marking for inclusion.

**Pull request merged**
