### PR TITLE
Consistent path attribute for file-related modules

### PR DESCRIPTION
**Pull request by dagwieers**
##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

acl, ini_file, lineinfile, replace, stat, xattr

##### SUMMARY

Not all file-related modules consistently use "path" as the attribute to
specify a single filename, some use "dest", others use "name". Most do
have aliases for either "name" or "destfile".

This change makes "path" the default attribute for (single) file-related
modules, but also adds "dest" and "name" as aliases, so that people can
use a consistent way of attributing paths, but also to ensure backward
compatibility with existing playbooks.

If this is acceptable, I don't mind doing the same for the extras
repository, and other modules.

### CODE REVIEW

**Comment by dagwieers** [comment]
The reason for me for changing this, is that it makes Ansible needlessly harder to use if you have to remember that e.g. the **xattr** module requires the **name** attribute, the **lineinfile** module requires a **dest** attribute, and the **stat** module requires a **path** attribute.

**Comment by bcoca** [comment]
We should still make note on each module when this change happened, the description should say 'previous to version 2.3 this was `name`'.

**Comment by dagwieers** [comment]
@bcoca Makes sense !

Will do this on Wednesday (and will look for more core modules that fit this bill).

**Comment by dagwieers** [comment]
BTW The Shippable check that failed is not something I think I should implement:

```
2016-10-31 11:56:33 ============================================================================
2016-10-31 11:56:33 ./files/xattr.py
2016-10-31 11:56:33 ============================================================================
2016-10-31 11:56:33 ERROR: version_added for new option (path) should be 2.3. Currently 0.0
2016-10-31 11:56:33 
2016-10-31 11:56:33 ============================================================================
2016-10-31 11:56:33 ./files/acl.py
2016-10-31 11:56:33 ============================================================================
2016-10-31 11:56:33 ERROR: version_added for new option (path) should be 2.3. Currently 0.0
2016-10-31 11:56:33 
2016-10-31 11:56:33 ============================================================================
2016-10-31 11:56:33 ./files/lineinfile.py
2016-10-31 11:56:33 ============================================================================
2016-10-31 11:56:33 ERROR: version_added for new option (path) should be 2.3. Currently 0.0
2016-10-31 11:56:33 
2016-10-31 11:56:33 ============================================================================
2016-10-31 11:56:33 ./files/replace.py
2016-10-31 11:56:33 ============================================================================
2016-10-31 11:56:33 ERROR: version_added for new option (path) should be 2.3. Currently 0.0
2016-10-31 11:56:33 
2016-10-31 11:56:33 ============================================================================
2016-10-31 11:56:33 ./files/ini_file.py
2016-10-31 11:56:33 ============================================================================
2016-10-31 11:56:33 ERROR: version_added for new option (path) should be 2.3. Currently 0.0
2016-10-31 11:56:33 
```

**Comment by bcoca** [comment]
@dagwieers ignore those errors for now 
@mattclay  anyway around them?

**Comment by mattclay** [comment]
@bcoca There isn't a way to bypass the version_added errors while the PR is open. However, once it's merged and submodule refs are updated, the errors will disappear.

**Comment by gregdek** [comment]
Thanks @dagwieers for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@dagwieers A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by dagwieers** [comment]
This PR has been moved over to ansible/ansible#19800

**Pull request closed without merging**
