### PR TITLE
Allow touch on links

### PR DESCRIPTION
**Pull request by Duologic**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

ansible.modules.core.files.file
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /path/to/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

I use Ansible to write Vassals for Uwsgi --emperor. The setup uses a symlink to the original file. To reload the Vassal, we need to touch the symlink and not the original file.

Adding the symlinks to the list of states allows me to accomplish this. I don't see a reason why you can't use touch on a symlink. Please collaborate if there is a valid reason not to do this.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @Duologic for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @Duologic for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@Duologic A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@Duologic Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@Duologic A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by nervo** [comment]
ping @Duologic

**Comment by Duologic** [comment]
Sorry about the long response time, I didn't check up on my Github notifications. I've rebased my commit on the latest devel.

Can this get merged faster now? Otherwise it'll become out of sync again and probably never gets merged.

**Comment by Duologic** [comment]
I'm not sure why the checks failed, can anybody give me a hint? Or fix it? :)

**Comment by gregdek** [comment]
@Duologic Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by Duologic** [comment]
What a hassle to get such a simple pull request in...

**Comment by gregdek** [comment]
@Duologic A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by Duologic** [comment]
Oh come'on. This is really fucked up.

**Comment by Duologic** [comment]
Looks like this got into upstream some other way.

**Comment by Duologic** [comment]
Or not, but wathever.

**Pull request closed without merging**
