### PR TITLE
Added a new state 'recreated' for docker module

### PR DESCRIPTION
**Pull request by ArtemChekunov**
"recreated" it is sequence of states "absent" and "started",  you can to use it if you need upgrade version of container.

### CODE REVIEW

**Comment by gregdek** [comment]
@cove @joshuaconner @softzilla @smashwilson Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please give it a +1; at that point, we will add the “priority_reviewed” flag to this PR, which will move it to the top of our queue for potential inclusion.

**Comment by smashwilson** [comment]
Hmm. What's the actual difference between `state: recreated` and `state: restarted`? We already have seven possible states for this module, so I'd like to be careful about adding additional ones.

I _suspect_ that `state: restarted` is restarting an existing container with the exact configuration that was used to start it in the first place, including a possibly-obsolete configuration and image. If that's the case, I could see an argument for just outright replacing `state: restarted` with the behavior you've written as `restarted`. On the other hand, while you _can_ replicate `state: recreated` by composing existing states...

``` yaml
- name: recreate a docker container
  docker:
    name: ohno
    image: someuser/oldandbusted
    state: "{{ item }}"
  with_items:
  - absent
  - started
```

... you _can't_ replicate the existing `state: restarted` the same way. I suppose it comes down to whether or not `state: restarted` is useful to anyone as it is.

Do any of the other `docker` module users have opinions about this?

**Comment by ArtemChekunov** [comment]
State restarted just restart a container.
But i need to restart container with latest image.
I can to use nest construction, it is true: 
with_items: 
- absent 
- started

but this construction don't declarative

**Comment by gregdek** [comment]
@smashwilson any further opinion on how to proceed here? Leaving in needs_info for now.

**Comment by joshuaconner** [comment]
I think I am with @smashwilson on this. While

```
with_items:
- absent
- started
```

isn't declarative, it's a fundamentally non-declarative operation, so I think makes sense for this set of actions to not be first-class supported in the Docker module.

**Comment by gregdek** [comment]
Thanks @sc0rp1us for the PR, but two -1s from maintainers justifies us closing this PR without merging. Apologies.

**Pull request closed without merging**
