### PR TITLE
issue #994: use HAS_BOTO to determine if import was successful

### PR DESCRIPTION
**Pull request by steenzout**
- removed import of sys module where it wasn't necessary.
- HAS_BOTO constant to check if import was successful.
- trigger a failure when import fails.

### CODE REVIEW

**Comment by bcoca** [comment]
don't change the shebang, it breaks the ansible_python_interpreter feature.

**Comment by steenzout** [comment]
if I don't change it I can't use the EC2 module on a `virtualenv` that has ansible and boto installed.
that's the root cause of the issue I'm having.

if the implementation of `ansible_python_interpreter` feature needs this then it also changes the expected behavior of all other non-ansible python packages that are installed on a `virtualenv`.
does it make sense to break a standard to implement a feature?

I read the doc about this feature and wouldn't `virtualenv -p python2 ~/env` and `source ~/env/bin/activate` and `~/env/bin/deactivate` be a cleaner solution to overcome the problem where systems only have a python3 interpreter (or need/want to use a python2 non-default interpreter) and you would need to switch between interpreters to run ansible?
plus you wouldn't need code to implement it and maintain it and it would be standard, right?

I'll try and see what happens if I set the `ansible_python_interpreter` but even if it works it's not practical since you're making me set a variable on all of my inventories, even if my system has a default python2 interpreter because I use `virtualenv` directly or through `tox` to test my playbooks, roles, etc.

if I install ansible through `macports` I guess I'll also need to set this variable as well on all of my inventories since my python interpreter is `/opt/local/bin/python` and `pip` is `/opt/local/bin/pip` and `boto` will be installed in

```
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/boto
```

otherwise I won't be able to access the EC2 core module since the default interpreter looks somewhere in:

```
...
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/
/Library/Python/2.7/site-packages
...
```

would people using `brew` have the same problem?

now, imagine I set that variable on all my inventories.
my production environment is say... redhat.
I guess I need to double the inventory files or pass different parameters to the ansible playbook?

I rather `sed` all of shebang lines to put it as they are on the commit when I set the `virtualenv` and install ansible on my mac and completely forget about this feature. :)

conclusion: I can remove the commit (or you can discard the commit) but anyone using `virtualenv` or using a non-default python interpreter to install ansible and external dependencies will have the same issue as I'm having.

your call... :)

**Comment by sivel** [comment]
The correct answer is of course to remove that commit. Changing the interpreter line is the incorrect approach.

**Comment by steenzout** [comment]
I've removed the shebang line change from the commit.
I'll post the issue of using `virtualenv` with ansible modules with an external dependency on the dev mailing list.

**Comment by abadger** [comment]
@steenzout For virtualenv, you want something like this solution: http://stackoverflow.com/questions/20575084/best-way-to-always-run-ansible-inside-a-virtualenv-on-remote-machines

Basically leveraging the ansible_python_interpreter and a short wrapper script to enable the virtualenv.

**Comment by steenzout** [comment]
@abadger thank you for the link.
my case is actually having different local machines where I can run playbooks (in different OS), which use `virtualenv` where ansible and 3rd party dependencies are installed.
I've managed to find a easier workaround with just using bash (for local and remote execution of playbooks tasks) without the need for the `ansible_python_interpreter` feature.

hope the commit is acceptable.
let me know if more tweaks are needed.

**Comment by abadger** [comment]
yep, looks good.  Thanks!

# Merged

Hi!

This has been merged in, and will also be included in the next major release.

If you or anyone else has any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Pull request merged**
