### PR TITLE
WIP: add 'env_file' support. Refs #792.

### PR DESCRIPTION
**Pull request by vpetersson**
Suggested/untested env-file support for public feedback.

### CODE REVIEW

**Comment by gregdek** [comment]
@vpetersson since you've marked this as "WIP", I'm going to apply the "needs_revision" flag here. When you've had a chance to test/refine it, let us know by adding "ready_for_review" in a subsequent comment, and we will kick off the formal review process. Thanks!

**Comment by vpetersson** [comment]
@gregdek Could you (or anyone) provide me with some pointers on the approach here?

**Comment by dexterbt1** [comment]
Any updates on this?

**Comment by vpetersson** [comment]
I have no update on my end. Would want some feedback from the core devs to ensure that i'm not going about this in the wrong direction (as I have very limited bandwidth).

**Comment by gesellix** [comment]
@vpetersson with "untested" did you mean the lack of automated tests or that you didn't give it a try on any of your servers? If it's only missing some integrative manual tests, I would give it a try :-)

**Comment by vpetersson** [comment]
@gesellix It's missing tests. Please give it a shot.

**Comment by the-frey** [comment]
@vpetersson I think @gesellix was suggesting that you try doing it yourself, btw ;)

**Comment by gesellix** [comment]
@the-frey @vpetersson I wanted to give it a try, but didn't have enough time, yet. So, I'll still do it as soon as time permits, but anybody else may step in :-)

**Comment by gesellix** [comment]
@vpetersson I finally had a chance to try your changes :-)
Sadly, it didn't work out of the box, because the `env_file` needs to be read before creating the container config. See https://github.com/gesellix/ansible-modules-core/commit/c8f09e71712cad09bd986ac87c7f78998b1b229a for my fix, which also adds a dedicated method to merge `env_file` with `env`. If you like, you can merge the changes with your branch, otherwise I can add an own PR.
What's missing: it hasn't been rebased on the current upstream master, yet. Ah, which also means that I checked with Ansible 1.9 and not with the most recent 2.x.

**Comment by gesellix** [comment]
I also applied the changes based on the current upstream (Ansible 2.x) in a different branch. See https://github.com/gesellix/ansible-modules-core/tree/add_env_file_support_v2

**Comment by vpetersson** [comment]
Thanks @gesellix. Feel free to take the lead on the PR. I currently do not have time for that.

**Comment by gesellix** [comment]
@vpetersson alright - I created #2929 to continue with it, now based on Ansible 2.x. Thanks for the initial code!

**Comment by gesellix** [comment]
@vpetersson would you mind closing this PR to avoid confusion with #2929? Thanks a lot!

**Comment by vpetersson** [comment]
Sure.

**Pull request closed without merging**
