### PR TITLE
Allow us to sort by all available datatypes

### PR DESCRIPTION
**Pull request by jjshoe**
Make it so you can sort AMI's by all available data types

### CODE REVIEW

**Comment by bcoca** [comment]
you should add note to the description that these search params are only available in 2.1 and above.

**Comment by jjshoe** [comment]
@bcoca good catch, will do.

**Comment by jjshoe** [comment]
@bcoca updated to reflect your feedback.

**Comment by robynbergeron** [comment]
Thanks @jjshoe. @tombamford please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by manicminer** [comment]
@robynbergeron shipit

Thanks @jjshoe!

**Comment by gregdek** [comment]
Thanks again to @jjshoe for this PR, and thanks @tombamford for reviewing. Marking for inclusion.

**Pull request merged**
