### PR TITLE
openstack nics by name

### PR DESCRIPTION
**Pull request by overquota**
add nic to instance by name (label in nova) besides net-id

### CODE REVIEW

**Comment by overquota** [comment]
We need this feature because we have several regions with 1 share network which has the same name everywhere, but different net-id

**Comment by xsuchy** [comment]
I would like to have this feature as well.

**Comment by emonty** [comment]
We're not taking new features to the old nova_compute modue in favor of the new os_server module. However, the feature you have here is handled in the new module in #1055

**Comment by overquota** [comment]
cool, thanks!

**Pull request closed without merging**
