### PR TITLE
New Docker restart policy 'unless-stopped'

### PR DESCRIPTION
**Pull request by anthonygreen**
Add option for new Docker restart policy 'unless-stopped'

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @anthonygreen. @cove @joshuaconner @softzilla @smashwilson please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by smashwilson** [comment]
Duplicate of #2485 which has already been blessed (although not merged).

**Comment by anthonygreen** [comment]
@smashwilson sorry, I search the repo for 'unless-stopped' but that didn't find the duplicate. I'll close the pull request.

**Comment by smashwilson** [comment]
@anthonygreen No worries. Thanks for giving it a shot just the same!

**Pull request closed without merging**
