### PR TITLE
Create IAM Role - Return AWS Result

### PR DESCRIPTION
**Pull request by Etherdaemon**
Hey @defionscode. Here's the initial PR to add an additional value to the returned result on the creation of an IAM role. I decided to leave the existing return statement, but will also return the AWS result as well. This is related to https://groups.google.com/forum/#!topic/ansible-devel/kjgi34b2550 discussion. I'll do another PR to write a custom waiter method for IAM instance profiles and IAM roles as boto2 doesn't have waiters implemented (unlike boto3).

Cheers

Karen

### CODE REVIEW

**Comment by Etherdaemon** [comment]
Updated as it looks like issue #2138 was asking for the same thing so added in instance_profile and iam_role results together.

Will return this:

```
ok: [127.0.0.1] => {
     "changed": false,
     "iam_result": {
    "_ansible_no_log": false,
    "changed": true,
    "instance_profile_result": {
        "arn": "arn:aws:iam::<ACCOUNT_NUMBER>:instance-profile/vc_spectre_allinone_ec2_iam_role",
        "create_date": "2015-11-05T11:00:28.336Z",
        "instance_profile_id": "<PROFILE_ID>",
        "instance_profile_name": "vc_spectre_allinone_ec2_iam_role",
        "path": "/",
        "roles": {}
    },
    "invocation": {
        "module_args": {
            <MODULE_ARGS>
        },
        "module_name": "iam"
    },
    "role_result": {
        "arn": "arn:aws:iam::<ACCOUNT_NUMBER>:role/vc_spectre_allinone_ec2_iam_role",
        "assume_role_policy_document": "%7B%22Statement%22%3A%20%5B%7B%22Action%22%3A%20%5B%22sts%3AAssumeRole%22%5D%2C%20%22Effect%22%3A%20%22Allow%22<BLAH_BLAH>",
        "create_date": "2015-11-05T11:00:27.939Z",
        "path": "/",
        "role_id": "<ROLE_ID>",
        "role_name": "vc_spectre_allinone_ec2_iam_role"
    },
    "roles": [
        "LAMP-Role",
        "Test_EC2",
        "vc_spectre_allinone_ec2_iam_role"
    ]
}
}
```

**Comment by gregdek** [comment]
@defionscode Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by gregdek** [comment]
@defionscode @seiffert This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by robynbergeron** [comment]
@defionscode @seiffert still waiting on your review.  Please comment with text 'shipit' or 'needs_revision' as appropriate. If we don't hear from you within 14 days, we will start to look for additional maintainers for this module.

**Comment by ryansydnor** [comment]
:+1: from me. would be quite useful! If you don't hear back from @defionscode or @seiffert in the next few days, :shipit:

**Comment by gregdek** [comment]
Thanks @ryansydnor -- unfortunately, only an official reviewer can give a valid shipit, but thanks for the vote of confidence. :) I know that @defionscode will be looking at this one soon.

**Comment by fiunchinho** [comment]
I'm also interested on this feature. Please upvote!

**Comment by gregdek** [comment]
@defionscode @seiffert This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by robynbergeron** [comment]
@defionscode @seiffert still waiting on your review.  Please comment with text 'shipit' or 'needs_revision' as appropriate. If we don't hear from you within 14 days, we will start to look for additional maintainers for this module.

**Comment by gregdek** [comment]
Thanks @Etherdaemon for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

**Comment by Constantin07** [comment]
Successfully tested.

```
TASK [debug] *******************************************************************
task path: /home/endavaMgmt/test_scripts/ansible/iam.yml:20
ok: [127.0.0.1] => {
    "iam": {
        "changed": true,
        "instance_profile_result": null,
        "role_result": {
            "arn": "arn:aws:iam::756660693972:role/test",
            "assume_role_policy_document": "%7B%22Statement%22%3A%20%5B%7B%22Action%22%3A%20%5B%22sts%3AAssumeRole%22%5D%2C%20%22Effect%22%3A%20%22Allow%22%2C%20%22Principal%22%3A%20%7B%22Service%22%3A%20%5B%22ec2.amazonaws.com%22%5D%7D%7D%5D%7D",
            "create_date": "2016-05-18T12:45:51.199Z",
            "path": "/",
            "role_id": "AROAI7VYQTANIB2JGWIMQ",
            "role_name": "test"
        },
        "roles": [
            "AnsibleRole",
            "DevTest_Role",
            "test"
        ]
    }
}
```

Do you have an ETA when this is going to be merged?

**Pull request merged**
