### PR TITLE
fixes #12831 by updating the boto iam connection method

### PR DESCRIPTION
**Pull request by Etherdaemon**
fixes #12831 by updating the boto iam connection method to utilise connect_to_region which AWS China region supports.

### CODE REVIEW

**Comment by Etherdaemon** [comment]
Apologies - didn't realise the issue I had opened was in the parent module and the pull request in the submodule. Issue is here: https://github.com/ansible/ansible/issues/12831

**Comment by robynbergeron** [comment]
Hi @Etherdaemon -- thanks for this PR, and for the accompanying bug report :)

@defionscode @seiffert -- Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by robynbergeron** [comment]
Also: I think normally we might ask folks to split a PR spanning multiple modules into separate PRs -- but this looks pretty straightforward (1 line fix to 3 modules covering the whole boto/iam family) so I think it's okay. @ansible/core team can let us know if they feel otherwise. :)

**Comment by juliedavila** [comment]
This should instead be

``` python
    try:
        if region:
            iam = boto.iam.connect_to_region(region, **aws_connect_kwargs)
        else:
            iam = boto.iam.connection.IAMConnection(**aws_connect_kwargs)
    except boto.exception.NoAuthHandlerFound, e:
        module.fail_json(msg=str(e))
```

Otherwise it will fail when region isn't explicitly passed.

**Comment by Etherdaemon** [comment]
Thanks defionscode. I've updated all 3 files as requested and synced across from upstream as well.

**Comment by juliedavila** [comment]
shipit

**Pull request merged**
