### PR TITLE
Fix for UTF-8 iconv processing in Synchronize module

### PR DESCRIPTION
**Pull request by m-emelchenkov**
Workaround for bugreport https://github.com/ansible/ansible-modules-core/issues/267

### CODE REVIEW

**Comment by gregdek** [comment]
@tima please review; if you give +1 we will tag P1_reviewed for faster inclusion.

**Comment by tima** [comment]
@gregdek I looked at this and I'm pretty sure it's not the right thing to do and can't recommend it be merged in. 

As @bcoca surmised (https://github.com/ansible/ansible-modules-core/issues/267#issuecomment-69429470) it's a parsing error of module params happening at a lower level. This synchronize module use case just so happens to expose it. Another module that accepts a comma in a param value would have the same issue.

This PR will not work if a user defines multiple rsync_opts like is shown in the module docs you get a comma instead of a space between `--no-motd` and `--exclude` that rsync can't handle and throw and error.

`rsync --delay-updates -F --compress --archive --rsh 'ssh  -S none -o StrictHostKeyChecking=no' --no-motd,--exclude=.git --out-format='<<CHANGED>>%i %n%L' "/tmp/helloworld" "/var/www/helloworld"'`

Now if I reformat my task differently without this PR applied so that "native" YAML list parsing is done, like so...

```
    -  synchronize:
        src: "/tmp/helloworld"
        dest: "/var/www/helloworld"
        rsync_opts: ['--no-motd', '--exclude=.git']
```

Ansible generates the correct rsync command.

`rsync --delay-updates -F --compress --archive --rsh 'ssh  -S none -o StrictHostKeyChecking=no' --no-motd --exclude=.git --out-format='<<CHANGED>>%i %n%L' "/tmp/helloworld" "/var/www/helloworld"'`

**Comment by gregdek** [comment]
OK, @tima, thanks. Am I to surmise that any workaround to the issue in #267 would be similarly inappropriate? In other words, should we just close this PR? Is there an open issue that we can use to track the underlying bug here?

**Comment by gregdek** [comment]
Closing due to -1 from @tima and lack of response from original submitter.

**Comment by m-emelchenkov** [comment]
@tima, you give me an idea how to pass the parameter without the problem. Thanks!!!

```
- synchronize:
    src: "../../../Sources/www/"
    dest: "/var/www/{{ domain }}/"
    delete: "yes"
    perms: "no"
    rsync_path: "sudo -u www-{{ host }} rsync"
    rsync_opts: ["--iconv=UTF8-MAC,UTF-8"]
```

**Pull request closed without merging**
