### PR TITLE
ec2_tag.py - Added fail for boto exception and documented the return structure

### PR DESCRIPTION
**Pull request by Constantin07**
This PR just adds some minor updates:
1. Added doc for return structure.
2. Removed sys.exit(0)
3. Added nice fails for boto exceptions, e.g. the one I came across:

```
TagLimitExceeded: The maximum number of Tags for a resource has been reached
```

### CODE REVIEW

**Comment by gregdek** [comment]
@lwade Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by gregdek** [comment]
@lwade This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by robynbergeron** [comment]
@lwade still waiting on your review.  Please comment with text 'shipit' or 'needs_revision' as appropriate. If we don't hear from you within 14 days, we will start to look for additional maintainers for this module.

**Comment by Constantin07** [comment]
When this PR will be reviewed?

**Comment by Constantin07** [comment]
Any updates?

**Comment by gregdek** [comment]
Thanks @Constantin07 for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

**Comment by Constantin07** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @Constantin07 for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

**Comment by gregdek** [comment]
Thanks @Constantin07 for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

**Pull request closed without merging**
