### PR TITLE
Adding a new network returns as changed=False

### PR DESCRIPTION
**Pull request by dmahler**
Updating to return changed=True

### CODE REVIEW

**Comment by gregdek** [comment]
@emonty @shrews @dguerri @juliakreger @j2sol @rcarrillocruz Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by omgjlk** [comment]
shipit

**Comment by gregdek** [comment]
Thanks @dmahler for the PR and @j2sol for the review.

Marking for inclusion. cc: @ansible/core team.

**Comment by dmahler** [comment]
Rebased

**Comment by dmahler** [comment]
@gregdek Do I need to do anything else now?  Thanks!

**Comment by gregdek** [comment]
@dmahler apologies, but it looks like this still needs rebasing... my guess is because these modules are going rapid churn. Might be best to coordinate with @j2sol to see what's going on here.

**Comment by dmahler** [comment]
Last update fixed the same thing this was about, abandoning this PR

**Pull request closed without merging**
