### PR TITLE
Fix volume bindings for docker 1.4.0

### PR DESCRIPTION
**Pull request by ghost**
Related to 
https://github.com/docker/docker-py/issues/419
https://github.com/docker/docker/issues/9628

### CODE REVIEW

**Comment by steveej** [comment]
Do I understand correctly that your commit disables regular volumes for docker >= 1.4.0?

**Comment by ghost** [comment]
Well, it seems to be so. I think you should discard this commit. We need to check client api version instead of docker version.

**Comment by steveej** [comment]
I don't think that any version checking is needed. I think that the handling of binds/volumes has been wrong in the first place. I've tried to improve it with #547.

**Comment by gregdek** [comment]
Closing in favor of #547.

**Pull request closed without merging**
