### PR TITLE
make assemble handle files recursively

### PR DESCRIPTION
**Pull request by techhazard**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

core files module: assemble
##### ANSIBLE VERSION

```
ansible 2.2.0
config file =
configured module search path = Default w/o overrides
```
##### SUMMARY

This adds a recursive option for the assemble module
The changes for the action plugin are in https://github.com/ansible/ansible/pull/16302

This new option is False by default (so it doesn't mess with the old behaviour)
When this option is True assemble will look into the subdirectories for files and add them, recursively

### CODE REVIEW

**Comment by bcoca** [comment]
this feature currently only addresses `remote_src=yes`, it would need to be duplicated for the action plugin

**Comment by gregdek** [comment]
Thanks @awesomefireduck for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by techhazard** [comment]
@bcoca could you please eleborate?
I tested this succesfully with `remote_src=no`

(And what do you mean by "action plugin"? I'm still fairly new to the whole pull-requests/ansible developing)

**Comment by bcoca** [comment]
action plugins are 'super modules' that deal with actions locally on the controller, `remote_src=no` means the assemble will happen controller side and then final product copied to target, since you have NOT added code to the action plugin, i very much doubt your test shows this working.

**Comment by bcoca** [comment]
source of the assemble action plugin https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/action/assemble.py

**Comment by techhazard** [comment]
My destination is localhost as well, perhaps that matters?

And I'm sure I used `remote_src=no` since I just ran it again with on and off and it worked with both.

**Comment by bcoca** [comment]
try using a actual remote machine

**Comment by techhazard** [comment]
I will
(local docker over ssh will be good enough, right?)

**Comment by techhazard** [comment]
I set up a docker ubuntu image I can reach via ssh
But I'm not sure how to test the script
before I just ran

```
 hacking/test-module -m lib/ansible/modules/core/files/assemble.py -a "src=$HOME/ansible/roles/bash/files/scripts dest=$HOME/test remote_src=no recursive=yes"
```

could you give me a hand?

**Comment by techhazard** [comment]
I figured it out.

When I let ansible SSH to the docker container I have the following results:
(I manually synced the dir to be on the same location on both local and remote)

| remote_src | recursive | result |
| --- | --- | --- |
| yes | no | success (no recursion) |
| no | no | fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "msg": "unsupported parameter for module: recursive"} (no file created) |
| yes | yes | success (with recursion) |
| no | yes | fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "msg": "unsupported parameter for module: recursive"} (no file created) |

This corresponds with your earlier comment.

So I just need to apply the exact same changes to the action plugin, correct?
But since that's a different repository, will that be a different pull-request?

**Comment by bcoca** [comment]
yes

**Comment by techhazard** [comment]
I applied the same changes to the action plugin, but I can't seem to test it...
I already have a docker container I can SSH into, but it keeps saying 

```
FAILED! => {"changed": false, "failed": true, "msg": "unsupported parameter for module: recursive"}
```

when I run it in a regular playbook (I used the `source hacking/env-setup` step).
This is with remote_src set to false and recursive set to true, but also with recursive set to false.

And when I try the following it fails as well

```
usr@host:~/git/ansible$ ./hacking/test-module -m lib/ansible/plugins/action/assemble.py -a 'dest:"~/bashtest" src:"~/testdir"'
```

but it fails with something which I think is unrelated:

```
usr@host:~/git/ansible$ ./hacking/test-module -m lib/ansible/plugins/action/assemble.py -a 'dest:"~/bashtest" src:"~/testdir"'                                         
* including generated source, if any, saving to: /home/usr/.ansible_module_generated
***********************************
RAW OUTPUT

from: can't read /var/mail/__future__
/home/usr/.ansible_module_generated: 19: /home/usr/.ansible_module_generated: __metaclass__: not found
/home/usr/.ansible_module_generated: 21: /home/usr/.ansible_module_generated: import: not found
/home/usr/.ansible_module_generated: 22: /home/usr/.ansible_module_generated: import: not found
/home/usr/.ansible_module_generated: 23: /home/usr/.ansible_module_generated: import: not found
/home/usr/.ansible_module_generated: 24: /home/usr/.ansible_module_generated: import: not found
from: can't read /var/mail/ansible.plugins.action
from: can't read /var/mail/ansible.utils.boolean
from: can't read /var/mail/ansible.utils.hashing
/home/vince/.ansible_module_generated: 31: /home/usr/.ansible_module_generated: Syntax error: "(" unexpected

***********************************
INVALID OUTPUT FORMAT

Traceback (most recent call last):
  File "./hacking/test-module", line 197, in runtest
    results = json.loads(out)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

Could you help me test my changes so that I can make a pull-request?

**Comment by bcoca** [comment]
remember that with `remote_src=false` the assemble source is on the controller and you need to have access to it with the user that is running ansible.

**Comment by techhazard** [comment]
I know, but it should at least recognize the option, right?

**Comment by techhazard** [comment]
I would really like to be able to see this merged, and for that I need to be able to test this.

**Comment by bcoca** [comment]
have both the assemble source and the target file be on the remote system.

**Comment by techhazard** [comment]
I think rebasing on ansible/devel might not have gone so well...

**Comment by techhazard** [comment]
undone the rebase

**Comment by techhazard** [comment]
I still can't get it to work.

#### Here's what I have:

`~/projects/git/ansible` contains the code from awesomefireduck/ansible:recursive-assemble
`~/projects/git/ansible/lib/ansible/modules/core` contains the code from awesomefireduck/ansible-modules-core:recursive-assemble

`~/ansible-playroom/` contains my playbooks including the following testbook.yml:

``` yaml
---
- hosts: ssh_test
  tasks:
  - name: test
    assemble:
      src: ~/test
      dest: ~/test_assemble
      remote_src: no # I toggle this one
      recursive: yes # and this one
```

`/etc/ansible/hosts` contains the following lines

```
[ssh_test]
ssh_test ansible_host=0.0.0.0 ansible_port=32768 ansible_user=root ansible_ssh_private_key_file="~/.ssh/id_rsa"
```

I am able to ssh into ssh_test with a key pair, ansible-playbook is as well.

`~/test/` and `ssh_test:~/test/` contain the following structure (as file:contents)

```
1:1
2/
  1:21
  2:22
  3:23
  4:24
  5:25
  6:26
  7:27
  8:28
  9:29
  10:210
3:3
4:4
5:5
6:6
7:7
8/
  1:81
  2:82
  [...]
  10:810
9:9
10:10
```

#### Here is what I did:

I sourced the hacking/env-setup` script (I use bash)

`cd ~/projects/git/ansible; . hacking/env-setup`

I went to my ansible playbooks dir

`cd ~/ansible-playbook`

I ran `ansible-playbook -vvv testbook.yml`with all four combinations.

#### Here are my results

| recursive | remote_src | result |
| --- | --- | --- |
| no | no | success (files in dir 2 and 8 are skipped) |
| no | yes | success (files in dir 2 and 8 are skipped) |
| yes | no | `fatal: [ssh_test]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"dest": "/root/test_assemble", "original_basename": "test", "recursive": true, "src": "/root/.ansible/tmp/ansible-tmp-1467723141.61-216839759887201/src"}}, "msg": "unsupported parameter for module: recursive"}` |
| yes | yes | `fatal: [ssh_test]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"dest": "~/test_assemble", "recursive": true, "remote_src": true, "src": "~/test"}}, "msg": "unsupported parameter for module: recursive"}` |

It is clearly not picking up the changes I made. Either I made a mistake in making the changes or I'm not testing my changes the right way. 

Can anybody help me here? I'd rather not give this up :-/

**Pull request closed without merging**
