### PR TITLE
Adds custom_data parameter to azure virtual machine resource

### PR DESCRIPTION
**Pull request by cromulentbanana**
##### ISSUE TYPE

- Feature Pull Request
##### COMPONENT NAME

azure_rm_virtualmachine
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel 9d5dff5596) last updated 2016/09/25 16:33:59 (GMT +200)
  lib/ansible/modules/core: (azure_enable_customdata c56ce32021) last updated 2016/09/25 15:36:32 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 8aa338ddfa) last updated 2016/09/25 16:34:29 (GMT +200)
  config file = /home/dlevin/Documents/Venture/devops/ansible.cfg
  configured module search path = ['library']

```
##### SUMMARY

This patch adds custom_data parameter to azure virtual machine resource which enables data or scripts to be passed to cloud-init for post-boot vm configuration.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @cryptobanana for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by cromulentbanana** [comment]
Hi, could someone kindly confirm whether this pull request is still under consideration? I just haven't seen any activity here yet. Thanks!

**Comment by cromulentbanana** [comment]
Hi @gregdek I understand that reviews may take a while, but is there any estimate for when someone will look at my request?

**Comment by gregdek** [comment]
Hi @cryptobanana. Right now we're in feature freeze for the 2.2 release, so no new feature requests are currently being reviewed.

Once 2.2 releases, I'd recommend joining the Ansible Core Team IRC meeting on Freenode to advocate for this PR. Details: https://github.com/ansible/community/blob/master/MEETINGS.md

**Pull request closed without merging**
