### PR TITLE
unarchive: added support for rar and 7zip archives

### PR DESCRIPTION
**Pull request by rdolejsi**
Unarchive module supports also rar and 7z archives now - provided the necessary utilities are installed on the host.

### CODE REVIEW

**Comment by rdolejsi** [comment]
This is a replacement request for the closed Ansible pullreq http://github.com/ansible/ansible/pull/9141 (no changes, update to current HEAD).

**Comment by gregdek** [comment]
@rdolejsi, thanks for submitting this pull request. Please accept our apologies for taking so long to review it.

Unfortunately, due to this delay, it appears that the underlying code has changed, and this PR needs to be rebased. If you believe that this PR still applies, please rebase and we will then put it into our review process as soon as possible.  Again, apologies for the delay and the extra work.

**Comment by gregdek** [comment]
@rdolejsi A friendly reminder: this pull request has been marked as needing your action, and it hasn't been updated in the last month. 

If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we'll keep it open pending your changes.

If we receive no indication from you within a week, we will close this pull request.

**Comment by gregdek** [comment]
Closed due to contributor inactivity. Note to future contributors: if you would like to pick up this contribution, please do so by opening a new pull request rather than reopening this one. Thanks!

**Pull request closed without merging**
