### PR TITLE
s3: support for provider-specific options

### PR DESCRIPTION
**Pull request by philm**
Re-submitting functionality from https://github.com/ansible/ansible/pull/6872 to new repo.

### CODE REVIEW

**Comment by juliedavila** [comment]
@philm could you rebase this when you get a chance?

**Comment by defionscode** [comment]
PR appears abandoned, recommending it be closed.

**Comment by philm** [comment]
@defionscode will handle later today...

**Comment by juliedavila** [comment]
Gotcha! No problem, take your time. I'll remove the prior comment knowing you're still around.

**Comment by philm** [comment]
@defionscode - all set.

**Comment by juliedavila** [comment]
So on this, I'd like to see more on the documentation side for people to understand how to use this parameter. Perhaps as a note with boto api links? Specifically boto allows for
- headers
- replace, 
- cb
- num_cb
- policy
- md5
- reduced_redundancy
- encrypt_key

And unless you read the boto api docs it's not obvious that these are valid keys for that parameter nor is it obvious what constitutes a proper value for each of those. Something that could help is adding logic to detect that valid keys were passed and for bonus points a check to ensure that the type of each key's value is proper (ie; int, str, bool, etc)

I'm open to suggestions on this, ultimately it just comes down to a UX issue for me.

**Comment by philm** [comment]
@defionscode - got it, I will add some more notes to the docs for this one.

**Comment by juliedavila** [comment]
@philm looks like it'll need a rebase/merge-conflict fix too

**Comment by juliedavila** [comment]
@philm friendly ping

**Comment by philm** [comment]
@defionscode - ready for you, thanks!

**Comment by gregdek** [comment]
Hi @philm -- looks like we've drifted again and this needs another rebase. Apologies for this. If you can get it rebased, we will try to review and merge as quickly as we can. @defionscode be on the lookout. :)

**Comment by philm** [comment]
@gregdek @defionscode - looks like 40eef6c3ecd940817acd900e5451afd7883098e4 added an "encrypt" option, which was the original purpose of this PR, but based on feedback I got in https://github.com/ansible/ansible/pull/6872, I went with a more backend-neutral approach. 

Let me know if it still makes sense to include this functionality (perhaps for other backend-specific options) - thx!

**Comment by gregdek** [comment]
@defions marking as needs_info, waiting for your decision here.

**Comment by juliedavila** [comment]
Hmmm. My thoughts....

Looking over the current encrypt option, my initial inclination is to support that + `provider_options`. However, given my prior note about the lack of intuitiveness for the options:

```
headers
replace
cb
num_cb
policy
md5
reduced_redundancy
encrypt_key
```

I feel more geared towards having specific parameters (ie, `encrypt_key`, `md5`, etc) over having a generic provider options parameter as it would lend itself to a more user friendly experience. This is further supported by the `encrypt` function being merged already. Wouldn't want to create duplication of functionality here.

**Comment by philm** [comment]
Yup, I agree. The explicit interface is more user-friendly. I'm going to close this PR.

**Pull request closed without merging**
