### PR TITLE
Allowing to specify specific external ip for gce instances

### PR DESCRIPTION
**Pull request by daniel-sc**
Credits go to @ZuluPro - this is mainly taken from his closed (because not rebased) PR: https://github.com/ansible/ansible-modules-core/pull/539

### CODE REVIEW

**Comment by robynbergeron** [comment]
Hi @daniel-sc -- thanks for submitting this PR, and also to @zulupro for the original work.

@erjohnso -- Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by daniel-sc** [comment]
Hi @erjohnso - can you please review?

**Comment by daniel-sc** [comment]
@robynbergeron what is the progress here? How do we get this PR merged?

**Comment by robynbergeron** [comment]
Thanks @daniel-sc for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

**Comment by daniel-sc** [comment]
@robynbergeron this PR was waiting over 2 month for review - can I be sure it will be reviewed soon if I rebase it??

**Comment by erjohnso** [comment]
Hi @daniel-sc - I believe the delay is my bad and the ansible folks want me to do all the reviews for GCE modules and I don't do as good a job on keeping up as I should.

If you rebase, I'll give it the thumbs up so ansible folks merge it in.

**Comment by daniel-sc** [comment]
Hi @robynbergeron I did the rebase, so this is 'ready_for_review'!

**Comment by robynbergeron** [comment]
Thanks @daniel-sc. @erjohnso please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by robynbergeron** [comment]
Thanks @daniel-sc. @erjohnso please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by erjohnso** [comment]
shipit

Thanks again @daniel-sc and sorry again for the lag!

**Comment by daniel-sc** [comment]
Thanks @erjohnso for the review - @robynbergeron can you please merge?

**Comment by robynbergeron** [comment]
Thanks @daniel-sc for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

**Comment by erjohnso** [comment]
Hi @robynbergeron,

I believe this has already been reviewed and was marked 'shipit', so shouldn't it just be merged now? I recognize I dropped the ball on reviewing this in the first place, but @daniel-sc has been very patient in trying to get this merged in.  I just want to make sure that if he does rebase again that it gets merged in pronto to avoid another delay.

thank you!

**Comment by daniel-sc** [comment]
Hi @robynbergeron , hi @erjohnso I did another rebase - please 'shipit' soon, as I'm not too eager to do a third rebase. If you like to do another review it is of course as well 'ready_for_review' (I'm not really sure what is automated or a real person here ;-) )

**Comment by erjohnso** [comment]
Thank you @daniel-sc!

shipit

**Comment by erjohnso** [comment]
shipit

**Comment by gregdek** [comment]
Thanks @daniel-sc. @erjohnso please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
Thanks again to @daniel-sc for this PR, and thanks @erjohnso for reviewing. Marking for inclusion.

**Comment by erjohnso** [comment]
Awsome, thanks @gregdek and for the work and patience @daniel-sc!

**Pull request merged**
