### PR TITLE
Fixing compile time error exception handling for python 3.

### PR DESCRIPTION
**Pull request by ghost**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

 digital_ocean
 digital_ocean_domain
 digital_ocean_sskey
##### ANSIBLE VERSION

ansible-devel
##### SUMMARY

Fixing compile time error exception handling for python 3.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @Hypermanzer for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by sivel** [comment]
Should this also remove those exclusions from `PY3_EXCLUDE_LIST` in `.travis.yml`?

**Comment by abadger** [comment]
@sivel in normal times yes.  Currently I have several people working on these things at pycon so I've been taking care of it after I merge so that we don't get conflicts.

**Comment by sivel** [comment]
Cool, just checking

**Pull request merged**
