### PR TITLE
Sort subnets by the order they are specified in the play

### LINKED ISSUE #172: ec2_vpc subnets in seemingly random order
When building VPCs using the ec2_vpc module the subnets are returned in a seemingly arbitrary order. It would be nice if they were returned in the order specified or ordered by cidr block to simplify deploying EC2 instances into specific subnets consistently.

### PR DESCRIPTION
**Pull request by abadger**
Fixes #172

This is an alternative to https://github.com/ansible/ansible-modules-core/pull/825

### CODE REVIEW

**Comment by abadger** [comment]
Just need a reviewer to check that this works and solves the problem.

**Comment by abadger** [comment]
By reviewer, I mostly mean, any second pair of eyes, preferably but not necessarily someone that uses ec2_vpd :-)

**Comment by sgargan** [comment]
Verified that the subnets are returned in the order specified.

``` yml
- hosts: localhost
  connection: local

  # Test for issue #904 
  # Sort subnets by the order they are specified in the play #904
  tasks:

    - name: Create a VPC with 3 subnets
      local_action:
        module: ec2_vpc
        state: present
        cidr_block: 172.22.0.0/16
        resource_tags: { "Name": "Ansible-Test-VPC" }
        subnets:
          - cidr: 172.22.3.0/24
            az: us-west-2c
            resource_tags: {"Name": "Ansible-Test-Subnet-1" }
          - cidr: 172.22.2.0/24
            az: us-west-2b
            resource_tags: {"Name": "Ansible-Test-Subnet-2" }
          - cidr: 172.22.1.0/24
            az: us-west-2a
            resource_tags: {"Name": "Ansible-Test-Subnet-3" }
        region: us-west-2
      register: vpc

    - name: verify subnets sorted in the order they're specified in the play
      assert:
        that:
          - vpc.subnets | length == 3
          - vpc.subnets[0].cidr == '172.22.3.0/24'
          - vpc.subnets[1].cidr == '172.22.2.0/24'
          - vpc.subnets[2].cidr == '172.22.1.0/24'

    - name: teardown vpc
      local_action:
        module: ec2_vpc
        state: absent
        vpc_id: '{{vpc.vpc_id}}'
        region: us-west-2
        resource_tags: { "Name": "Ansible-Test-VPC" }
```

**Comment by sgargan** [comment]
Removing the VPC does require that the resource tags are specified, these probably shouldn't be mandatory for removal.

**Comment by abadger** [comment]
Thanks for testing!

Regarding removal, I agree, there are several other modules that have similar issues too (for instance, this thread about the docker module: https://groups.google.com/forum/#!topic/ansible-project/nF_sP5EreVY ).  For this module, probably need to change resource_tags to required=False in the argument_spec and then put in code that checks that it's present unless the state='absent'.  I'll merge a pr that does that.

# Merged

Hi!

This has been merged in, and will also be included in the next major release.

If you or anyone else has any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Pull request merged**
