### PR TITLE
Fix service_enable_rcconf() fails to parse rcconf contains multi-line value

### PR DESCRIPTION
**Pull request by koichirok**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

service module (system/service.py)
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel df81f1197f) last updated 2016/08/10 09:52:52 (GMT +000)
  lib/ansible/modules/core: (detached HEAD 5d7b46e0dd) last updated 2016/08/10 09:53:01 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD eaa71f51d6) last updated 2016/08/10 09:53:01 (GMT +000)
  config file = 
  configured module search path = Default w/o overrides
```

all other branches contain 672b83b5 may also have this multi-line value issue.
##### SUMMARY

FreeBSD officially supports multi-line value like below in rc.conf[1] but current service module implementaion fails to parse such a value.  This PR fixes this issue.

> Example of multi-line value, cite from [rc.conf(5)](https://www.freebsd.org/cgi/man.cgi?rc.conf%285%29)
> 
> ```
> ifconfig_ed0_aliases="\
>         inet 127.0.0.251 netmask 0xffffffff \
>         inet 127.0.0.252 netmask 0xffffffff \
>         inet 127.0.0.253 netmask 0xffffffff \
>         inet 127.0.0.254 netmask 0xffffffff"
> ```

This PR also fixes possible unexpected file changes caused by stripping every line for the purpose of appending newline at end of file if file not end with new line. This issue introduced at  cd0a194 and
all branches contains it are affected.

**Without fix:**

```
$ tail -7 /etc/rc.conf
     ifconfig_lo0_aliases="\
        inet 127.0.0.251 netmask 0xffffffff \
        inet 127.0.0.252 netmask 0xffffffff \
        inet 127.0.0.253 netmask 0xffffffff \
        inet 127.0.0.254 netmask 0xffffffff"

nscd_enable="NO"
$ ansible localhost -s -c local -m service -a 'name=nscd enabled=yes'
127.0.0.1 | FAILED! => {
    "changed": false, 
    "failed": true, 
    "msg": "unable to set rcvar"
}
```

**With fix in this PR:**
You can see:
1. service module successfully set nscd_enable from YES to NO.
2. ifconfig_lo0_aliases' leading spaces are preserved.

```
$ tail -7 /etc/rc.conf
     ifconfig_lo0_aliases="\
        inet 127.0.0.251 netmask 0xffffffff \
        inet 127.0.0.252 netmask 0xffffffff \
        inet 127.0.0.253 netmask 0xffffffff \
        inet 127.0.0.254 netmask 0xffffffff"

nscd_enable="YES"
$ cp /etc/rc.conf ~/
$ ansible localhost -s -c local -m service -a 'name=nscd en$bled=no'                                                                                                               
127.0.0.1 | SUCCESS => {
    "changed": true, 
    "enabled": false, 
    "name": "nscd"
}
$ diff  ~/rc.conf /etc/rc.conf
23c23
< nscd_enable="YES"

---
> nscd_enable="NO"
```

### CODE REVIEW

**Comment by koichirok** [comment]
Oops, I'll fix failed test (syntax error) asap.

**Comment by gregdek** [comment]
Thanks @koichirok. To the current maintainers, @grossws please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by koichirok** [comment]
I've fixed syntax error.

**Comment by gregdek** [comment]
Thanks @koichirok for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@koichirok A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by koichirok** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @koichirok for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by mscherer** [comment]
We have to keep that module working on python 2.4, so we can't add it to the blacklist.

**Comment by gregdek** [comment]
@koichirok A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@koichirok Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@koichirok A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
