### PR TITLE
Fixes: User module on SunOS always returns changed in check mode

### PR DESCRIPTION
**Pull request by ag-wood**
Fixes Issue #2296 : User module on SunOS always returns changed in check mode

### CODE REVIEW

**Comment by robynbergeron** [comment]
[module: system/user.py]

**Comment by robynbergeron** [comment]
hi @ag-wood -- thanks for this PR! :)

@sfromm -- Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by bcoca** [comment]
@ag-wood please check #2311, i think this fixes it for all cases on solaris, not just user modification but also passwords

**Comment by gregdek** [comment]
So this already needs rebasing... should it be rebased or closed in favor of #2311?

**Comment by gregdek** [comment]
Closed due to inactivity.

**Pull request closed without merging**
