### PR TITLE
Fix getting actual_stdin_open backport for 2.0.x

### PR DESCRIPTION
**Pull request by PikachuEXE**
##### ISSUE TYPE

- Bugfix Pull Request
##### COMPONENT NAME

docker
##### ANSIBLE VERSION

```
2.0.x and later
```
##### SUMMARY

Get the correct OpenStdin from docker-py
Backport of #4040

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @PikachuEXE. All backport requests must be reviewed by the core team, and this can take time. We appreciate your patience. 

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @PikachuEXE for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by PikachuEXE** [comment]
I can see the Travis check is passed and Shippable check is failed
But by looking at the Shippable log, it seems the tests are not even run
So I don't know what to "fix" ready_for_review

**Comment by gregdek** [comment]
Thanks @PikachuEXE. To the current maintainers, @cove, @softzilla, @zfil, @ThomasSteinbach please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
