### PR TITLE
Remove skipped=True when using creates and removes

### PR DESCRIPTION
**Pull request by fgsch**
Based on #8645

### CODE REVIEW

**Comment by gregdek** [comment]
@romeotheriault please review; if you give +1 to this PR, we will promote to P1_reviewed.

**Comment by rrtj3** [comment]
Sorry it's been a while since I've worked on this module, but I guess I'm not sure I understand the desire to remove the skipped=True when a file exists or is non-existent, with the creates and removes checks. 

Why exactly do we not want to have the 'skipped=True'? The stdout says we're skipping....

**Comment by fgsch** [comment]
@romeotheriault it's been a while but IIRC same reason as https://github.com/ansible/ansible/issues/8645

**Comment by rrtj3** [comment]
I see. That makes sense to me. 

+1

**Comment by gregdek** [comment]
Thanks @romeotheriault -- promoting to P1_reviewed.

**Pull request merged**
