### PR TITLE
docker module: Mimic Docker CLI behavior when running an image using  "hostname" parameter

### PR DESCRIPTION
**Pull request by moncho**
Running and image with the docker module from Ansible results in different container information as if the same image was run using Docker CLI.

An example, running any image from Ansible like this:

```
- name: run container
      docker:
        image: "ubuntu"
        hostname : host.mydomain.com
        command : "/bin/echo hello world"  
```

and then checking the container information created in Docker (`docker inspect **container_id** | grep "Hostname\|Domainname"`    ) gives this:

```
        "Domainname": "",
        "Hostname": "host.mydomain.com",
```

while doing the same thing using the Docker CLI:

```
docker run --hostname  host.mydomain.com ubuntu /bin/echo hello world
```

results in:

```
        "Domainname": "mydomain.com",
        "Hostname": "host",
```

I have changed the module so that it splits the **hostname** in **hostname** and **domainname** and passes them as params to the Docker python client to fix it.

### CODE REVIEW

**Comment by gregdek** [comment]
@cove @joshuaconner @softzilla @smashwilson please review; if any of you +1 we will flag as "P1_reviewed" for fast track inclusion.

**Comment by joshuaconner** [comment]
When I look at the the "Files changed" tab the only change I see is the typo fix. Is there something else?

**Comment by gregdek** [comment]
Oh, that's weird. I wonder if the rest of this got pulled in as part of a different commit to a different PR on Mar 19?

Well, if it's in, it's in. I guess this PR is now "fix a typo that should pretty clearly be fixed."

**Comment by abadger** [comment]
It looks like the typo was merged in another PR as well: https://github.com/ansible/ansible-modules-core/pull/969

Not sure why github isn't reflecting that.

@moncho -- I think all of your changes have been merged so I'm closing this.  Feel free to open a new PR, ping me on IRC (abadger1999 on irc.freenode.net) or email the mailing list if there's more to do.

**Pull request closed without merging**
