### PR TITLE
Add acl freebsd

### PR DESCRIPTION
**Pull request by mscherer**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

acl
##### SUMMARY

posix acl have been in freebsd since 5.0, so this patch add support for it. However, on zfs, it seems that nfsv4 acl are used rather than posix, so I pushed that as well.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @mscherer for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by mscherer** [comment]
Still a unrelated faillure, guess I will push later

**Comment by gregdek** [comment]
Thanks @mscherer for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by mscherer** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @mscherer for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request merged**
