### PR TITLE
Escape spaces, backslashes when create new entry in fstab

### LINKED ISSUE #1861: mount module _escape_fstab doesn't handle integers
When I ran the mount module I got the following error:

```
/scp:r35: #$ python ~/.ansible/tmp/ansible-tmp-1438625022.07-152487730049288/mount
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1438625022.07-152487730049288/mount", line 2079, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1438625022.07-152487730049288/mount", line 354, in main
    name, changed = set_mount(module, **args)
  File "/root/.ansible/tmp/ansible-tmp-1438625022.07-152487730049288/mount", line 134, in set_mount
    escaped_args = dict([(k, _escape_fstab(v)) for k, v in args.iteritems()])
  File "/root/.ansible/tmp/ansible-tmp-1438625022.07-152487730049288/mount", line 110, in _escape_fstab
    return v.replace('\\', '\\134').replace(' ', '\\040').replace('&', '\\046')
AttributeError: 'int' object has no attribute 'replace'
```

I replaced the body of `_escape_fstab` with:

``` python
def _escape_fstab(v):
    """ escape space (040), ampersand (046) and backslash (134) which are invalid in fstab fields """
    if hasattr(v, 'replace') and callable(getattr(v, 'replace')):
        return v.replace('\\', '\\134').replace(' ', '\\040').replace('&', '\\046')
    else:
        return v
```

And that did the trick.

This is on an OL6u6 box running Python 2.6.6 ...

### LINKED ISSUE #3192: `system/mount` module adds `fstab` entries with space/backslashes/etc in `src`, `opts` incorrectly
##### Issue Type:
- Bug Report
##### Plugin Name:

system/mount
##### Ansible Version:

```
ansible 2.0.0.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

Default
##### Environment:

N/A
##### Summary:

New entries with spaces/backslashes/etc in fields except `name` are added without escaping. 
Existing entries are modified correctly after merging PR #1454. Bug affects _only_ new entries.

Also it's not idempotent because current mount module ignores incorrect lines in `fstab`.
##### Steps To Reproduce:

Just add some new entry to fstab with spaces in `src` or `opts`.

```
# two times to demonstrate non-idempotence:
ansible localhost -m mount -a 'src="//some/share with spaces" name=/mnt/s1 fstype=cifs opts=ro state=present fstab=/tmp/test-fstab'
ansible localhost -m mount -a 'src="//some/share with spaces" name=/mnt/s1 fstype=cifs opts=ro state=present fstab=/tmp/test-fstab'
```
##### Expected Results:

`/tmp/test-fstab` with one entry:

```
//some/share\\040with\\040spaces /mnt/s1 cifs ro 0 0
```
##### Actual Results:

`/tmp/test-fstab` contains:

```
//some/share with spaces /mnt/s1 cifs ro 0 0
//some/share with spaces /mnt/s1 cifs ro 0 0
```

I will publish PR with fix in a few minutes.

### PR DESCRIPTION
**Pull request by grossws**
##### Issue Type:
- Bugfix Pull Request
##### Plugin Name:

system/mount
##### Summary:

This patch made use of `escaped_args` when adding new entry to `fstab`, so escape for all fields (not only `name`) is handled correctly.

Moreover this patch fixes incorrect handling of `int` values in `dump` and `passno` introduced by my previous patch in PR #1454 by checking type and avoid its escaping.

Also this patch reverts unnecessary changes from commit d59de3af633424aa1048334e421294667e113247.

Fixes #3192, #1861 (introduced by my previous fix in PR #1454).
##### Extra

Supplement to PR #1454 and issue #530.

Fixes #3192.
Fixes #1861 (introduced by PR #1454).

Signed-off-by: Konstantin Gribov grossws@gmail.com

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @grossws for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

**Comment by grossws** [comment]
@gregdek any progress on reviewing this PR? 

Current `system/mount` modules breaks fstab on each module invocation requiring manual intervention to repair it.

**Comment by gregdek** [comment]
I can escalate for severity, but we're going to enter freeze for next version soon, not sure if the core team will get to it.

Another possibility: you could become a reviewer for this module, if you're interested. That would give you the right to say "shipit" to this PR, which would promote it directly to the core team for consideration for inclusion. It means that you'd be asked to review subsequent PRs. Let me know if you're willing to do that.

**Comment by grossws** [comment]
@gregdek You mean `system` module? If yes, I can review PRs except ones related to SELinux which is out of scope of my interests now.

**Comment by gregdek** [comment]
Thanks @grossws. I will add you as a maintainer for the system modules except selinux.

**Comment by gregdek** [comment]
Thanks again to @grossws. This module is going into community review.

We notice that you are one of the maintainers (@grossws) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by grossws** [comment]
shipit

**Comment by grossws** [comment]
@gregdek I rechecked patch since upstream `system/mount` module had slightly changed.

**Comment by gregdek** [comment]
Thanks @grossws. Since you are one of the maintainers (@grossws) of this module and you commented with "shipit", we are marking this PR for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by bcoca** [comment]
invalid ship label, must be by reviewer not by PR submitter

**Comment by grossws** [comment]
@bcoca, OK. Any chance that it will get merged into next stable version? Now I have to fix corrupted `fstab`s on several servers _manually_ after each call to playbook uses `system/mount`.

**Comment by eeroniemi** [comment]
If it helps, I had this same problem and by using mount.py of this PR everything worked fine.

**Pull request merged**
