### PR TITLE
Added an option to not fail on status mismatch for uri module.

### PR DESCRIPTION
**Pull request by JoelGilliland**
This is useful if you need to do something based on a returned status code.

### CODE REVIEW

**Comment by bcoca** [comment]
I wonder if a better interface is setting the status code to None or empty list

**Comment by JoelGilliland** [comment]
I thought about that, I'm open to whatever everyone thinks is best.

**Comment by gregdek** [comment]
@romeotheriault Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please give it a +1; at that point, we will add the “priority_reviewed” flag to this PR, which will move it to the top of our queue for potential inclusion.

**Comment by gregdek** [comment]
@romeotheriault are you available to review this PR?

**Comment by rrtj3** [comment]
Apologies, I don't have time right now to test this out. I can look at it
and say it _looks_ ok or not but cannot test it right now. If that is
adequate let me know and I'll visually review it.

**Comment by gregdek** [comment]
Hi @romeotheriault -- thanks for the heads-up. Yeah, because it's a core module, the PR really does need some actual testing from someone before we can merge it. 

So the next step here is to come back to @JoelGilliland -- any testing you can share with us? Maybe a github gist or something you can share? Ultimately, the best approach is to have something in the integration tests in ansible/ansible, but for now, some test artifacts would be great.

Also, would you be willing to help with this module by being an additional community maintainer of it?

(Either way, ping me directly by my github id so I see the response, thanks!)

**Comment by JoelGilliland** [comment]
@gregdek I'll see what I can do. I can say I've been using this in a production environment with no issues, but most certainly agree some integration tests would be most ideal. I'll try to get some artifacts soon-ish to you either way.

I would love to help with this module, I'm just not sure how much time I can dedicate to it right now.

**Comment by bcoca** [comment]
so I'm partial to making the status code an empty list, as tasks already have a 'failed_when' to this new option seems redundant.

**Comment by JoelGilliland** [comment]
@bcoca I don't disagree. If that is the consensus, I'd be happy to change and test when I have free time.

**Comment by gregdek** [comment]
Thanks @JoelGilliland for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

**Comment by gregdek** [comment]
@JoelGilliland if you're still interested in this PR, it still needs rebasing -- if/when you do, please comment "ready_for_review" and we will get it back into community_review.

If no response in the next two weeks, we will close this PR.

**Comment by gregdek** [comment]
Thanks @JoelGilliland for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by JoelGilliland** [comment]
Closing this in favor of new pull request https://github.com/ansible/ansible-modules-core/pull/3527

**Pull request closed without merging**
