### PR TITLE
pn_ospfarea (New Module)

### PR DESCRIPTION
**Pull request by amitsi**
##### ISSUE TYPE

- New Module Pull Request
##### COMPONENT NAME

OSPF Area Module
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/etc/ansible/pluribus-ansible/ansible/library']
```
##### SUMMARY

```

```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @amitsi for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by amitsi** [comment]
If target system is 2.7 Ubuntu, do I need to resolve the 2.4 Syntax issues?

**Comment by amitsi** [comment]
If target system is 2.7 Ubuntu, do I need to resolve the 2.4 Syntax issues?

**Comment by amitsi** [comment]
If target system is 2.7 Ubuntu, do I need to resolve the 2.4 Syntax issues?

**Comment by amitsi** [comment]
If target system is 2.7 Ubuntu, do I need to resolve the 2.4 Syntax issues?

**Comment by amitsi** [comment]
If target system is 2.7 Ubuntu, do I need to resolve the 2.4 Syntax issues?

**Comment by amitsi** [comment]
If target system is 2.7 Ubuntu, do I need to resolve the 2.4 Syntax issues?

**Comment by amitsi** [comment]
If target system is 2.7 Ubuntu, do I need to resolve the 2.4 Syntax issues?

**Comment by amitsi** [comment]
If target system is 2.7 Ubuntu, do I need to resolve the 2.4 Syntax issues?

**Comment by amitsi** [comment]
If target system is 2.7 Ubuntu, do I need to resolve the 2.4 Syntax issues?

**Comment by amitsi** [comment]
If target system is 2.7 Ubuntu, do I need to resolve the 2.4 Syntax issues?

**Comment by amitsi** [comment]
If target system is 2.7 Ubuntu, do I need to resolve the 2.4 Syntax issues?

**Comment by amitsi** [comment]
If target system is 2.7 Ubuntu, do I need to resolve the 2.4 Syntax issues?

**Comment by amitsi** [comment]
ready_for_review

**Comment by gundalow** [comment]
Merged, thanks.

**Pull request merged**
