### PR TITLE
fixed memory_limit for docker api version  >= 1.19

### PR DESCRIPTION
**Pull request by ilya-epifanov**

### CODE REVIEW

**Comment by bcoca** [comment]
cc @smashwilson @cove @softzilla @joshuaconner

**Comment by tnguyen1** [comment]
+1 for this PR - _create_container_config_ method is invoked in docker-py library: https://github.com/docker/docker-py/blob/master/docker/utils/utils.py#L676
Docker's parameter **Memory** has to be used instead of **mem_limit**.

**Comment by abadger** [comment]
@ilya-epifanov Thanks for the fix! @tnguyen1 Thanks for finding the docker-py code that makes clear what we need to use!

# Merged

Hi!

This has been merged in, and will also be included in the next major release.

If you or anyone else has any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Comment by abadger** [comment]
And pushed to the stable-1.9 branch now too.

**Pull request merged**
