### PR TITLE
update docs for cloudformation

### PR DESCRIPTION
**Pull request by smiller171**
documentation update for #1460

### CODE REVIEW

**Comment by bcoca** [comment]
actually, this is a bit misleading, the path is from the current working directory on the target host, you just happen to be using a 'local' connection.

**Comment by smiller171** [comment]
@bcoca does that look more accurate?

**Comment by bcoca** [comment]
yes, though I'm tempted to just create an action module to allow for good relative paths

**Comment by smiller171** [comment]
@bcoca I think that this would be ideal

**Pull request merged**
