### PR TITLE
[docker] Don't remove named containers with state=started

### LINKED ISSUE #3087: cloud/docker: recreates stopped named containers with state=started
##### Issue Type:

Bug Report
##### Plugin Name:

docker
##### Ansible Version:

```
ansible 2.0.0.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

N/A
##### Environment:

N/A
##### Summary:

Docker module recreates stopped named container with state=started
##### Steps To Reproduce:

Task description

```
- name: Start container
  docker:
    image: debian
    name: lab
    pull: missing
    detach: yes
    net: bridge
    tty: yes
    command: sleep infinity
    state: started
```

Output from ansible-paybook -vv

```
TASK [start-container : Start container] ***************************************
changed: [localhost] => {"ansible_facts": {"docker_containers": [{"AppArmorProfile": "", "Args": ["infinity"], "Config": {"AttachStderr": false, "AttachStdin": false, "AttachStdout": false, "Cmd": ["sleep", "infinity"], "Domainname": "", "Entrypoint": null, "Env": ["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"], "Hostname": "75bb43da9afb", "Image": "android", "Labels": {}, "OnBuild": null, "OpenStdin": false, "StdinOnce": false, "Tty": true, "User": "", "Volumes": null, "WorkingDir": ""}, "Created": "2016-02-21T15:57:18.464570878Z", "Driver": "btrfs", "ExecIDs": null, "GraphDriver": {"Data": null, "Name": "btrfs"}, "HostConfig": {"Binds": null, "BlkioDeviceReadBps": null, "BlkioDeviceReadIOps": null, "BlkioDeviceWriteBps": null, "BlkioDeviceWriteIOps": null, "BlkioWeight": 0, "BlkioWeightDevice": null, "CapAdd": null, "CapDrop": null, "CgroupParent": "", "ConsoleSize": [0, 0], "ContainerIDFile": "", "CpuPeriod": 0, "CpuQuota": 0, "CpuShares": 0, "CpusetCpus": "", "CpusetMems": "", "Devices": null, "Dns": null, "DnsOptions": null, "DnsSearch": null, "ExtraHosts": null, "GroupAdd": null, "IpcMode": "", "Isolation": "", "KernelMemory": 0, "Links": null, "LogConfig": {"Config": {}, "Type": "journald"}, "Memory": 0, "MemoryReservation": 0, "MemorySwap": 0, "MemorySwappiness": -1, "NetworkMode": "bridge", "OomKillDisable": false, "OomScoreAdj": 0, "PidMode": "", "PidsLimit": 0, "PortBindings": null, "Privileged": false, "PublishAllPorts": false, "ReadonlyRootfs": false, "RestartPolicy": {"MaximumRetryCount": 0, "Name": ""}, "SecurityOpt": null, "ShmSize": 67108864, "UTSMode": "", "Ulimits": null, "VolumeDriver": "", "VolumesFrom": null}, "HostnamePath": "/var/lib/docker/containers/75bb43da9afb967ee60c095f3dd5f03183f80b3973ccb75d62d08678f0de6436/hostname", "HostsPath": "/var/lib/docker/containers/75bb43da9afb967ee60c095f3dd5f03183f80b3973ccb75d62d08678f0de6436/hosts", "Id": "75bb43da9afb967ee60c095f3dd5f03183f80b3973ccb75d62d08678f0de6436", "Image": "sha256:484a6a69ac0c4f06b7bff344a36745414fe57024c07ab3c90d8146b835256008", "LogPath": "", "MountLabel": "", "Mounts": [], "Name": "/lab", "NetworkSettings": {"Bridge": "", "EndpointID": "a929802ab259e1992472d2ac0383f82ca82ca19f901f565a6dcc1ccd3072f4ce", "Gateway": "172.17.0.1", "GlobalIPv6Address": "", "GlobalIPv6PrefixLen": 0, "HairpinMode": false, "IPAddress": "172.17.0.2", "IPPrefixLen": 16, "IPv6Gateway": "", "LinkLocalIPv6Address": "", "LinkLocalIPv6PrefixLen": 0, "MacAddress": "02:42:ac:11:00:02", "Networks": {"bridge": {"Aliases": null, "EndpointID": "a929802ab259e1992472d2ac0383f82ca82ca19f901f565a6dcc1ccd3072f4ce", "Gateway": "172.17.0.1", "GlobalIPv6Address": "", "GlobalIPv6PrefixLen": 0, "IPAMConfig": null, "IPAddress": "172.17.0.2", "IPPrefixLen": 16, "IPv6Gateway": "", "Links": null, "MacAddress": "02:42:ac:11:00:02", "NetworkID": "6a6c469a29d9f7d80a25d6df2e158d1f4c4ead81a463fe4ac13b20a60280ce6d"}}, "Ports": {}, "SandboxID": "6ccf812bac48ad68b87808dcc05dad84cf41054a21d03f48e2eb1dcba45414a7", "SandboxKey": "/var/run/docker/netns/6ccf812bac48", "SecondaryIPAddresses": null, "SecondaryIPv6Addresses": null}, "Path": "sleep", "ProcessLabel": "", "ResolvConfPath": "/var/lib/docker/containers/75bb43da9afb967ee60c095f3dd5f03183f80b3973ccb75d62d08678f0de6436/resolv.conf", "RestartCount": 0, "State": {"Dead": false, "Error": "", "ExitCode": 0, "FinishedAt": "0001-01-01T00:00:00Z", "OOMKilled": false, "Paused": false, "Pid": 16620, "Restarting": false, "Running": true, "StartedAt": "2016-02-21T15:57:18.649681499Z", "Status": "running"}}]}, "changed": true, "msg": "removed 1 container, started 1 container, created 1 container.", "reload_reasons": null, "summary": {"created": 1, "killed": 0, "pulled": 0, "removed": 1, "restarted": 0, "started": 1, "stopped": 0}}
```
##### Expected Results:

Named container restarts with last saved state
##### Actual Results:

Named container was recreated from image

Looks like the problem caused by this code:
https://github.com/ansible/ansible-modules-core/blob/devel/cloud/docker/docker.py#L1690

### PR DESCRIPTION
**Pull request by alapshin**
##### Issue Type:

Bugfix Pull Request
##### Plugin Name:

cloud/docker
##### Ansible Version:

```
ansible 2.0.0.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### Summary:

Change module behavior with `name` and `state=started` parameters.
Original version would remove container with matched name and create new one from passed image. New version doesn't remove existing named containers.

Fixes #3087

### CODE REVIEW

**Comment by robynbergeron** [comment]
Thanks @alapshin. @cove @joshuaconner @softzilla @smashwilson @zfil @ThomasSteinbach please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
@cove @joshuaconner @softzilla @smashwilson @zfil @ThomasSteinbach This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
Kicking again

**Comment by gregdek** [comment]
Thanks @alapshin. To the current maintainers, @cove, @softzilla, @smashwilson, @zfil, @ThomasSteinbach please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by cornfeedhobo** [comment]
shipit

**Comment by gregdek** [comment]
Thanks @alapshin for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@alapshin A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by alapshin** [comment]
No longer relevant due to deprecation of original docker module.

**Pull request closed without merging**
