### PR TITLE
fix 2nd example in package module

### PR DESCRIPTION
**Pull request by lloydbenson**
##### ISSUE TYPE
- Docs Pull Request
##### COMPONENT NAME

package
##### ANSIBLE VERSION

N/A : http://docs.ansible.com/ansible/package_module.html
##### SUMMARY

Just fixing a couple of typos so it looks right on the main site.

### CODE REVIEW

**Comment by bcoca** [comment]
the example is a variable on purpose, as the module name for apache changes depending on distribution.

**Comment by lloydbenson** [comment]
Is the semi colon also on purpose?

**Comment by lloydbenson** [comment]
If the variable is on purpose wouldn't it make sense to have the other example with ntpdate also in brackets to be consistent?

**Comment by bcoca** [comment]
i fixed the colon directly, ntpdate is one of the few packages that seems to have the same name across distros. This is noted in the comments above the examples.

**Pull request closed without merging**
