### PR TITLE
Add new Dv2 Azure instances

### PR DESCRIPTION
**Pull request by kanwei**

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @kanwei. @nitzmahome please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
@nitzmahome This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by robynbergeron** [comment]
@nitzmahome still waiting on your review.  Please comment with text 'shipit' or 'needs_revision' as appropriate. If we don't hear from you within 14 days, we will start to look for additional maintainers for this module.

**Comment by gregdek** [comment]
Moving this to core review, since @nitzmahome is now on the core team anyway.

**Comment by gregdek** [comment]
@nitzmahone maybe we should have spelled your name right in the triage file. :/

Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Pull request merged**
