### PR TITLE
Ansible reports "All packages providing xxx are up to date", but that is not true.

### PR DESCRIPTION
**Pull request by bnese**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

yum
##### ANSIBLE VERSION

```
ansible 2.0.1.0
```
##### SUMMARY

Workaround for detecting updates for packages when 'yum check-update' breaks package name and package version into multiple lines.
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=584525#c9

Before fix:

```
[root@tmp ~]# ansible example1 -s -m yum -a "state=latest name=package_with_a_long_name update_cache=yes"
example1 | SUCCESS => {
    "changed": false,
    "msg": "",
    "rc": 0,
    "results": [
        "All packages providing package_with_a_long_name are up to date",
        ""
    ]
```

But when running 'yum upgrade package_with_a_long_name' on host example1 it find a newer version available.

First run after fix:

```
[root@tmp ~]# ansible example1 -s -m yum -a "state=latest name=package_with_a_long_name update_cache=yes"
example1 | SUCCESS => {
    "changed": true,
    "msg": "",
    "rc": 0,
    "results": [
        "Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
Resolving Dependencies
--> Running transaction check
---> Package package_with_a_long_name.noarch 0:1.0.0-15 will be updated
---> Package package_with_a_long_name.noarch 0:1.0.0-18 will be an update
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================
 Package                       Arch     Version        Repository          Size
================================================================================
Updating:
 package_with_a_long_name   noarch   1.0.0-18    example-noarch    19 k

Transaction Summary
================================================================================
Upgrade  1 Package

Total download size: 19 k
Downloading packages:
Delta RPMs disabled because /usr/bin/applydeltarpm not installed.
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Updating   : package_with_a_long_name-1.0.0-18.noarch               1/2 
  Cleanup    : package_with_a_long_name-1.0.0-15.noarch                  2/2 
  Verifying  : package_with_a_long_name-1.0.0-18.noarch               1/2 
  Verifying  : package_with_a_long_name-1.0.0-15.noarch                  2/2 

Updated:
  package_with_a_long_name.noarch 0:1.0.0-18                              

Complete!
"
    ]
}

```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @bnese for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @bnese for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@bnese A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by bnese** [comment]
It seems like there is a fix for this in devel:
`
        # remove incorrect new lines in longer columns in output from yum check-update
        out=re.sub('\n\W+', ' ', out)
        available_updates = out.split('\n')
`
I'll close my PR.

**Pull request closed without merging**
