### PR TITLE
Fix container list in a docker swarm environment

### LINKED ISSUE #3107: Docker container's state doesn't work on a swarm environment
##### Issue Type:

Bug Report
##### Plugin Name:

docker
##### Ansible Version:

ansible 2.0.0.2
##### Ansible Configuration:

N/A
##### Environment:

Ubuntu 14.04
##### Summary:

The state of a docker container running in a swarm cluster is not ok.
If a docker container is deployed in a swarm cluster, when the playbook is running again, Ansible try to run again the container so an error occurred: 

```
fatal: [master-1]: FAILED! => {"changed": false, "failed": true, "msg": "Docker API Error: Conflict: The name php-demo-swarm is already assigned. You have to delete (or rename) that container to be able to assign php-demo-swarm to a container again."}
```
##### Steps To Reproduce:

Playbook example:

```
- hosts: master
  tasks:
     - name: Deploy on Swarm Master
       vars:
          docker_cert_path: "/home/ubuntu/.docker"
       docker:
          image: php-test
          state: started
          name: php-demo-swarm
          detach: True
          use_tls: verify
          docker_url: "tcp://localhost:3376"
          tls_ca_cert: "{{ docker_cert_path }}/ca.pem"
          tls_client_cert: "{{ docker_cert_path }}/cert.pem"
          tls_client_key: "{{ docker_cert_path }}/key.pem"
          env:
             "constraint:node==node-1"
          ports:
             - "::80"
```

master-1 is a swam master
node-1 is a swarm agent node included in the cluster.
##### Expected Results:

If this step is running 2 times, the second time it should do nothing because container is already started.
##### Actual Results:

An error:

```
fatal: [master-1]: FAILED! => {"changed": false, "failed": true, "msg": "Docker API Error: Conflict: The name php-demo-swarm is already assigned. You have to delete (or rename) that container to be able to assign php-demo-swarm to a container again."}
```

### PR DESCRIPTION
**Pull request by tbouvet**
##### Issue Type:
- Bugfix Pull Request
##### Plugin Name:

cloud/docker
##### Summary:
- The container state is not ok in docker swarm environment (node's name is in the container name).
- The default Network Mode is not ok : replace **bridge** by **default**

Fixes #3107 
##### Example:
- Container name in docker swarm :

```
u'Names': [u'/node-4/sick_brown']
```
- Network Mode: container['HostConfig']['NetworkMode'] :
  `
  u'NetworkMode': u'default'
  `

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @tbouvet. @cove @joshuaconner @softzilla @smashwilson @zfil @ThomasSteinbach please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by resmo** [comment]
Thanks @tbouvet for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

**Comment by tbouvet** [comment]
Thanks @resmo 
Rebase is done.

**Comment by tbouvet** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @tbouvet. To the current maintainers, @cove, @softzilla, @smashwilson, @zfil, @ThomasSteinbach please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by chouseknecht** [comment]
@tbouvet Rather than continuing to patch the docker module, it might be worth giving the new [docker_service](https://github.com/ansible/ansible-modules-core/blob/devel/cloud/docker/docker_service.py) module a spin. It consumes Docker compose (version 1 and 2), and lets compose decide how to build and deploy things. It also has a built in scale parameter, letting you deploy and scale in one step.

**Comment by gregdek** [comment]
Thanks @tbouvet for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by tbouvet** [comment]
As @chouseknecht  said, switch to [docker_service](https://github.com/ansible/ansible-modules-core/blob/devel/cloud/docker/docker_service.py).

**Pull request closed without merging**
