### PR TITLE
Add way to specify environment

### PR DESCRIPTION
**Pull request by jhutar**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

packaging/os/redhat_subscription
##### ANSIBLE VERSION

```
ansible 1.9.4
  configured module search path = None
```
##### SUMMARY

When I have attempted to use redhat_subscription against Satellite 6.x (which requires environment to be specified and if not provided on subscription-manager command-line, it asks for it), it hanged forever (I guess that subscription-manager was waiting for input on which environment to use).

I have just added `environment` option which allows you to specify the value. I have basically duplicated what I have seen in commit which added `org_id`.

Note that to be able to register against Satellite 6.x, you need to install `http://{{ sat_server }}/pub/katello-ca-consumer-latest.noarch.rpm` first which configures stuff and setup Satellite's CA certificate.

```
  - name: "Install katello-ca-consumer from Satellite"
    yum:
      name="http://{{ sat_server }}/pub/katello-ca-consumer-latest.noarch.rpm"
      state=present
  - name: "Register to Satelite"
    redhat_subscription:
      state=present
      username="{{ sat_user }}"
      password="{{ sat_pass }}"
      autosubscribe=true
      environment=Library
```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @jhutar. To the current maintainers, @barnabycourt, @alikins please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @jhutar for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by jhutar** [comment]
Rebased. ready_for_review

**Comment by gregdek** [comment]
Thanks @jhutar. To the current maintainers, @barnabycourt, @alikins please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by jhutar** [comment]
ping?

**Comment by gregdek** [comment]
Thanks @jhutar for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by jhutar** [comment]
Rebased. ready_for_review

**Comment by jhutar** [comment]
Fixed docs string to have 'version_added: "2.2"'. ready_for_review

**Comment by gregdek** [comment]
Thanks @jhutar. To the current maintainers, @barnabycourt, @alikins please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by alikins** [comment]
shipit

**Comment by gregdek** [comment]
Thanks again to @jhutar for this PR, and thanks @barnabycourt, @alikins for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by jhutar** [comment]
Thanks!

**Comment by alikins** [comment]
Shipping it.

**Pull request merged**
