### PR TITLE
Allow setting/changing the default tablespace for a PostgreSQL database

### PR DESCRIPTION
**Pull request by carobme**
##### ISSUE TYPE

- Feature Pull Request
##### COMPONENT NAME

module: postgresql_db
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel 95c983438b) last updated 2016/07/18 12:28:58 (GMT +200)
  lib/ansible/modules/core:  not found - use git submodule update --init lib/ansible/modules/core
  lib/ansible/modules/extras:  not found - use git submodule update --init lib/ansible/modules/extras
```
##### SUMMARY

This patch adds a tablespace option to the postgresql_db module.

I've created this before I discovered an open pull request by @bivald, otherwise I'd taken that as a starting point. His patch (#2220) and mine are very similar, the difference essentially is that the patch in #2220 doesn't allow changing the (default) tablespace after the database has been created, whereas this patch does. Tested against PostgreSQL 9.4 and 9.5.

My suggestion is to merge this and close #2220.

```

```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @mbeck- for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by carobme** [comment]
Doc indentation problem fixed and rebased.

ready_for_review

**Comment by carobme** [comment]
Added "version_added" to new option.

ready_for_review

**Comment by gregdek** [comment]
Thanks @mbeck- for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @mbeck- for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@mbeck- A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@mbeck- Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@mbeck- A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@mbeck- Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
