### PR TITLE
Allow empty password for new user

### LINKED ISSUE #2895: mysql_user won't create user if password is empty
**Bug Report**

**Ansible version**: 2.0.0.2

**Ansible Configuration**: See below

**Environment**: Running OS X 10.11.3, managing MySQL 5.5.46 on FreeBSD 10.2.

**Summary**: It seems like the `mysql_user` module won't create a user if the password is empty, this worked fine in 1.9.4.

**Steps To Reproduce**:

`ANSIBLE_CONFIG=ansible.vagrant.cfg ansible freebsd-mysql -m mysql_user -a "name='ha-check' password='' host='%'" --become`

**Expected results**: User is created.

**Actual results**: User is not created.

---

Contents of `ansible.vagrant.cfg`:

```
ask_sudo_pass=False
hostfile=.vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory
log_path=logs/ansible.vagrant.log
host_key_checking=False
remote_user=vagrant
private_key_file=~/.vagrant.d/insecure_private_key
retry_files_enabled=False
```

### PR DESCRIPTION
**Pull request by Jmainguy**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

database/mysql/mysql_user.py
##### ANSIBLE VERSION

devel
##### SUMMARY

Fixes #2895 allows an empty password to be set

```
ansible -i hosts all -m mysql_user -a "name=ha-check password='' host='%'"
```

### CODE REVIEW

**Comment by Jmainguy** [comment]
@mscherer mind looking at this?

**Comment by gregdek** [comment]
Thanks again to @Jmainguy. This module is going into community review.

We notice that you are one of the maintainers (@Jmainguy) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by mscherer** [comment]
Since password is always set, I would suggest to just use "if encrypted:  else: " rather than if password and encrypted, elif password and not encrypted". Password is supposed to be not null, si we check it explicitely before calling.

**Comment by Jmainguy** [comment]
Closing this in favor of #3445

**Pull request closed without merging**
