### PR TITLE
Fix ec2.py bug when it does not respect network_id

### PR DESCRIPTION
**Pull request by akazakov**
If instance already exists, but in a differnet VPC, we should
not count towards exact_count
## Example

Imagine the followin situation

VPC_A:
  Subnet_A:
    Instance1:
      Tags:
        Name: my_instance

VPC_B:
  Subnet_B: {}

Now if we call ec2 module:

ec2:
  image_id: ...
  vpc_subnet_id: Subnet_B
  exact_count: 1
    count_tag:
      Name: "my_instance"

Without the fix, this will result in no-op, as if instance was present in
Subnet_B

Even weirder behaviour would be observed if you call it with exact_count

> 1, because now you'd end up with some copies in the right subnet, and
> 1 in the wrong (Subnet_A)

With the fix, it will create necessary count in Subnet_B and ignore
Subnet_A

### CODE REVIEW

**Comment by cserafin1124** [comment]
This code is useful and seems good. Please merge this!

**Comment by akazakov** [comment]
@bcoca Is there anything I can do to help this merged?

**Comment by copumpkin** [comment]
:shipit:

**Comment by gregdek** [comment]
Thanks @akazakov. @tgerla @lwade please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by akazakov** [comment]
@tgerla @lwade  @gregdek ping?

**Comment by akazakov** [comment]
Can someone please look at this???

**Comment by jsmartin** [comment]
I'm not a maintainer (and do not aspire to be), but this makes logical sense to me.  +1

**Comment by akazakov** [comment]
@gregdek Can you please merge this? It has 3 votes from other people to merge this.

**Comment by ryansydnor** [comment]
Agree with @jsmartin here. :shipit: !

**Comment by gregdek** [comment]
Moving this module to @ansible/core review. @akazakov sorry for the delay.

**Comment by akazakov** [comment]
ping?

**Pull request closed without merging**
