### PR TITLE
Add support for instance_initiated_shutdown_behavior parameter on ec2 module

### PR DESCRIPTION
**Pull request by ekiourk**
This PR resolves this issue https://github.com/ansible/ansible-modules-core/issues/475

### CODE REVIEW

**Comment by multiplemigs** [comment]
any update on when or whether this feature will be pulled in to the core/cloud/aws ec2.py file of the official repo?

**Comment by gregdek** [comment]
Thanks @ekiourk for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

**Comment by robynbergeron** [comment]
@ekiourk A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes.

**Comment by gregdek** [comment]
@ekiourk Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If we don't hear from you within another 14 days, we will close this pull request.

**Comment by gregdek** [comment]
Closing due to contributor inactivity.

**Pull request closed without merging**
