### PR TITLE
Add OpenStack Orchestration Stack module

### PR DESCRIPTION
**Pull request by emonty**

### CODE REVIEW

**Comment by emonty** [comment]
This depends on not-yet-released patches to shade. Will ping back when they're released. It's also a patch to supercede #2036

**Comment by gregdek** [comment]
Marking "needs_revision" since it's dependent on shade stuff.

**Comment by Shrews** [comment]
Support for this in shade has landed and will appear in the 1.0 release, due to be released "real soon now". I think this module will need some updating now.

**Comment by gregdek** [comment]
@emonty A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes.

**Comment by robynbergeron** [comment]
@emonty Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If we don't hear from you within another 14 days, we will close this pull request.

**Comment by gregdek** [comment]
So since this one hasn't been touched in quite a while, and since @Shrews opined earlier that "I think this module will need some updating now", I'm going to go ahead and close this PR. @emonty, feel free to reopen with changes or open a new PR as you see fit.

**Pull request closed without merging**
