### PR TITLE
Cancel spot requests before fail. Fix for #2057

### PR DESCRIPTION
**Pull request by kai11**

### CODE REVIEW

**Comment by gregdek** [comment]
@tgerla @lwade Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by evanccnyc** [comment]
This should definitely be fixed before 2.0 ships.

**Comment by kai11** [comment]
Any progress?

**Comment by evanccnyc** [comment]
ccing @lwade again.

**Comment by evanccnyc** [comment]
@kai11 do you have a playbook I can use for testing this?

**Comment by kai11** [comment]
@evanccnyc https://gist.github.com/kai11/09d9bb952d422348a006 from https://github.com/ansible/ansible-modules-core/issues/2057

**Comment by evanccnyc** [comment]
@kai11 hmm based on that playbook I see a lot of:

```
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "wait for spot requests timeout on Mon Oct  5 16:57:19 2015, cancelled []"}
```

With the spot instance still showing opened after the fact.

**Comment by kai11** [comment]
@evanccnyc 

TASK [launch spot with short timeout] ******************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "wait for spot requests timeout on Mon Oct  5 21:03:55 2015, cancelled [u'sir-XXX']"}

I'm using v2.0.0-0.1.alpha1 with this fix applied.
Which tag\commit you tried it with?

**Comment by evanccnyc** [comment]
Latest dev pull.

**Comment by kai11** [comment]
@evanccnyc Problem seems to be in amazon API - new spot request may not be returned.
Please check another attempt to fix this problem - https://github.com/ansible/ansible-modules-core/pull/2210

**Pull request closed without merging**
