### PR TITLE
pn_cluster (New Module)

### PR DESCRIPTION
**Pull request by amitsi**
##### ISSUE TYPE

- New Module Pull Request
##### COMPONENT NAME

Cluster Create (for vLAG (Virtual Link Aggregation)
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/etc/ansible/pluribus-ansible/ansible/library']
```
##### SUMMARY

```

```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @amitsi for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @amitsi for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by amitsi** [comment]
ready_for_review

**Comment by amitsi** [comment]
'ready_for_review'

**Comment by gregdek** [comment]
Thanks @amitsi for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gundalow** [comment]
Merged, thanks.

**Comment by gundalow** [comment]
Merged, thanks.

**Pull request merged**
