### PR TITLE
Fixing open stack compile time errors irt exception handling for Pyth…

### PR DESCRIPTION
**Pull request by ghost**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

ansible-devel
##### ANSIBLE VERSION

cloud/openstack/_glance_image.py
cloud/openstack/_keystone_user.py
cloud/openstack/_nova_compute.py
cloud/openstack/_nova_keypair.py
cloud/openstack/_quantum_floating_ip.py
cloud/openstack/_quantum_floating_ip_associate.py
cloud/openstack/_quantum_network.py
cloud/openstack/_quantum_router.py
cloud/openstack/_quantum_router_gateway.py
cloud/openstack/_quantum_router_interface.py
cloud/openstack/_quantum_subnet.py
##### SUMMARY

Fixing open stack compile time errors irt exception handling for Python 3

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @Hypermanzer. To the current maintainers, @DEPRECATED, @emonty, @shrews, @juliakreger, @j2sol, @rcarrillocruz please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by omgjlk** [comment]
Yeah, these are all deprecated, but good to have 'em fixed. shipit

**Comment by gregdek** [comment]
Thanks again to @Hypermanzer for this PR, and thanks @DEPRECATED, @emonty, @shrews, @juliakreger, @j2sol, @rcarrillocruz for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by abadger** [comment]
Looks good.  Merged to devel.

**Pull request merged**
