### PR TITLE
fixes user module for rhel5 by using -n instead of -N

### PR DESCRIPTION
**Pull request by Jmainguy**
fixes user module for rhel5 by using -n instead of -N, all other distros will still use -N

### CODE REVIEW

**Comment by abadger** [comment]
I think that this would solve the error but it does introduce different behaviour.  -N means that the user will not be added to any group.  -g self.name means that the user will be added to the group with that name.  This could be surprising if that group already existed for another purpose.

**Comment by Jmainguy** [comment]
On RedHat5

```
   -g, --gid GROUP
      The group name or number of the user’s initial login group. The group name must exist. A group number must refer to an already existing group.
      /etc/default/useradd.

   -n A group having the same name as the user being added to the system will be created by default. This option will turn off this Red Hat Linux specific behavior.
      When this option is used, users by default will be placed in whatever group is specified in /etc/default/useradd. If no default group is defined, group 1 will be
      used.
```

-n is out of the question in my opinion, do not want to add this user to gid 1. 
that pretty much just leaves -g, adding the user to a group that matches their name by default.

I imagine when people are using ansible, and they do not specify a group, they expect the user to be added to their own group. Where as the current code (If you do not merge my addition) will not add a user to their own group, if that group already exists.

Do you believe the current behavior of not adding a user to their own group, if it exists already and if group= is not defined is the correct behavior?

**Comment by bcoca** [comment]
what about "-n -g self.name", would that qualify as a default?

## 

Brian Coca

**Comment by abadger** [comment]
After some IRC discussion we realized that rhel5's -n is the same as more modern shadow-utils -N.  (IIRC, a RedHat patch to add -n was implemented upstream and changed to a capital N at the same time).

**Comment by abadger** [comment]
Thanks @jmainguy!

# Merged

Hi!

This has been merged in, and will also be included in the next major release.

If you or anyone else has any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Comment by madkiss** [comment]
This is also broken on SLES 11.

**Pull request merged**
