### PR TITLE
yum module: add support for check_mode /w yum package groups

### PR DESCRIPTION
**Pull request by jfchevrette**
Currently, when using check_mode with a yum package group (@group), ansible will return changed=True all the time. This is inconvenient when running in check_mode to see if your hosts configs are proper. In my use case, I have a playbook that I run in check_mode every morning and an email report is sent if I have any non-compliant hosts/tasks. (changed != 0)

This pull request adds check_mode support for package groups with state=installed or state=latest

Checking for package removal is tricky and I have not found a clean way to implement this. Ideas are welcome.

There is no way to ask yum or repoquery directly if a package group has installable packages or updateable packages. The way this is implemented is by expanding the package group using 'repoquery' and by passing the list of packages to is_installed which will return wether or not it has any packages that would be installed. Since repoquery will list ALL member packages even though they are excluded in yum.conf, there is a need to use both is_installed and is_available to ensure we only check for those packages yum would normally install (taking into account the excluded ones)

### CODE REVIEW

**Comment by jfchevrette** [comment]
Sorry I'm new to this. Am I expected to fix my PR at this point? (files were renamed resulting in the PR to conflict)

**Comment by bcoca** [comment]
if you can, it will make merging it that much faster, there are many more developers creating PRs than maintainers merging them.

**Comment by jfchevrette** [comment]
@bcoca I have tried to fix the PR by fetching and merging the changes that caused the conflict. Again I am fairly new to this so I'm not sure if I did it right. According to github the PR doesn't have conflicts anymore.

**Comment by jfchevrette** [comment]
Any chance this could be merged soon?

**Comment by bcoca** [comment]
its in the queue, dealing with p2 first

**Comment by gregdek** [comment]
Hi @jfchevrette. Thanks for submitting this pull request. Please accept our apologies for taking so long to review it.

Unfortunately, due to this delay, it appears that the underlying code has changed, and this PR needs to be rebased. If you believe that this PR still applies, please rebase and we will then put it into our (new, faster) community review process as soon as possible.  Again, apologies for the delay and the extra work.

**Comment by gregdek** [comment]
@jfchevrette A friendly reminder: this pull request has been marked as needing your action, and it hasn't been updated in the last month. 

If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we'll keep it open pending your changes.

If we receive no indication from you within a week, we will close this pull request.

**Comment by jfchevrette** [comment]
@gregdek I have fixed the conflicts but I believe I have done something wrong in rebasing my changes. If this can't be merged please let me know and I will create a new PR.

**Comment by gregdek** [comment]
@jfchevrette Yep, the PR now contains changes to nine files -- maybe stashing the original file, starting with a new fork of the devel repo, closing this PR and creating a new PR would be simplest. Thanks for looking into it!

**Pull request closed without merging**
