### PR TITLE
Add HTTP Proxy options for win_get_url module

### PR DESCRIPTION
**Pull request by tksarah**
I think that some enterprise user make have an authentication http proxy when they use win_get_url module. If this module has parameter for these , I think It is useful. I modified to add 'proxy_url' , 'user' and 'pass' options.

```
win_get_url:
  url: 'https://example.com/download-file.jpg'
  proxy_url: 'http://10.0.0.1:8080'
  user: 'username'
  pass: 'password'
  dest: '/tmp/download-file.jpg'
```

### CODE REVIEW

**Comment by gregdek** [comment]
@tksarah thanks for the PR.

@angstwad Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by tksarah** [comment]
@gregdek Thank you.
@angstwad Hello, I have tested this module with PowerShell v3.0(on Windows 7) and v4.0(on Windows Server 2012) . It was good works with a both.

**Comment by tksarah** [comment]
I saw #1607 was merged. Therfore I updated these.


@angstwad
@gregdek

**Comment by tksarah** [comment]
I saw #1607 was merged. Therefore I updated these.
I have tested this module with PowerShell v3.0(on Windows 7) and v4.0(on Windows Server 2012) again.

@angstwad
@gregdek

**Comment by gregdek** [comment]
@angstwad are you available to review? This PR is pending your approval.

**Comment by angstwad** [comment]
shipit

Visually inspected - looks okay to me, but again, not a PS genius here.  No capability to test the module, however.

**Comment by gregdek** [comment]
Thanks again to @tksarah for this PR, and thanks @angstwad for reviewing. Marking for inclusion.

**Comment by tksarah** [comment]
Fantastic - many thanks!

**Comment by nitzmahone** [comment]
Merged to devel via https://github.com/ansible/ansible-modules-core/commit/3281cad95e6cf4fa2f213c641102bf4d7bc16b2f (squashed, fixed merge conflicts). Will also pull into stable-2.0. Thanks!

**Pull request closed without merging**
