### PR TITLE
jinja2 support for cloudformation module

### PR DESCRIPTION
**Pull request by vorlock**
Hi all,
I posted this (https://groups.google.com/d/msg/ansible-devel/j3QiAu7EZmE/UGdYFqWy6x8J) message on ansible-devel. Do you think it's feasible to use something like it or are there philosophical constrains against it?

### CODE REVIEW

**Comment by gregdek** [comment]
@vorlock Thanks for submitting this pull request. Please accept our apologies for taking so long to review it.

Unfortunately, due to this delay, it appears that the underlying code has changed, and this PR needs to be rebased. If you believe that this PR still applies, please rebase and we will then put it into our (new, faster) community review process as soon as possible.  Again, apologies for the delay and the extra work.

**Comment by vorlock** [comment]
@gregdek np mate, I could rebase it but if nobody until now expressed any interest it mean it's not very widely needed, so I'm going to close it. Thx for your interest anyway.

**Comment by gregdek** [comment]
Thanks @vorlock.

**Comment by Vit0ld** [comment]
Hi, actually this seems to be a good idea. What needs to be done to make it happen - recreate the PR with this patch against current devel branch?

**Comment by vorlock** [comment]
@Vit0ld I think so.

**Comment by gregdek** [comment]
@Vit0ld yep, that would do it. Create a new PR and we'll put it into the review process.

**Comment by eslng** [comment]
Hi,
Will that do #1890 ?

**Pull request closed without merging**
