### PR TITLE
Remove duplicate logic

### PR DESCRIPTION
**Pull request by niothiel**
Looks like the same statement was copy and pasted initially. It's been removed.

### CODE REVIEW

**Comment by robynbergeron** [comment]
[module: cloud/amazon/s3.py]

**Comment by robynbergeron** [comment]
Hi @niothiel -- thanks for this PR. 

@lwade @ralph-tice -- Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

Also pinging the rest of the AWS crew for eyes: @jsmartin @scicoin-project @tombamford @garethr @lorin @jarv @jsdalton @silviud @adq @zbal @zeekin @willthames @carsongee @defionscode @tastychutney @bpennypacker @loia

**Comment by willthames** [comment]
This fix looks reasonable, but it doesn't really go as far as it should - the `overwrite` option is a bit magic. It's also badly typed as it's effectively a union of ansible.bool and an enum

Can we add the various options to the documentation, and deprecate the booleanness (possibly).

**Pull request merged**
