### PR TITLE
Added n7k support

### PR DESCRIPTION
**Pull request by GGabriele**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

nxos_feature
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```
##### SUMMARY

In regards to #4465 and due to some N7K API bug, I've made some changes to retrieve and parse raw outputs instead of structured data back from API calls.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @GGabriele. All backport requests must be reviewed by the core team, and this can take time. We appreciate your patience. 

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gundalow** [comment]
Strange Shippable failures, is this branch upto date with `devel`?

**Comment by gundalow** [comment]
Adding 2.2 milestone as this is something we should track for the release.

**Comment by GGabriele** [comment]
This was for a 2.1 bug fix...I'll push these changes to the 2.2 PR soon

**Comment by gregdek** [comment]
Thanks @GGabriele for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request merged**
