### PR TITLE
Update docker module to support dns search

### PR DESCRIPTION
**Pull request by romaimperator**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

cloud/docker/docker
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel c42501cfe7) last updated 2016/05/02 20:09:50 (GMT -500)
  lib/ansible/modules/core: (devel 4a8a292793) last updated 2016/05/02 20:10:46 (GMT -500)
  lib/ansible/modules/extras: (devel 7fd4180857) last updated 2016/05/02 22:49:17 (GMT -500)
  config file = /Users/dan/projects/server-ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

I added the optional dns_search argument to the docker module. This isn't explicitly supported by docker-py but it works with docker-py version 1.8.1 for sure.

### CODE REVIEW

**Comment by romaimperator** [comment]
Amended commit to add the documentation if forgot about.

**Comment by gregdek** [comment]
Thanks @romaimperator. To the current maintainers, @cove, @softzilla, @smashwilson, @zfil, @ThomasSteinbach please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by romaimperator** [comment]
Correcting documentation to be named 'dns_search' instead of 'dns'

**Comment by gregdek** [comment]
Thanks @romaimperator for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by romaimperator** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @romaimperator. To the current maintainers, @cove, @softzilla, @smashwilson, @zfil, @ThomasSteinbach please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @romaimperator for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@romaimperator A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by romaimperator** [comment]
Closing because this module is now deprecated and the docker_container module already includes this.

**Pull request closed without merging**
