### PR TITLE
 mount: Support for Check Mode fixes #181 

### LINKED ISSUE #181: mount: Support for Check Mode
##### Issue Type:

Feature Idea
##### Ansible Version:

Dev
##### Environment:

N/A
##### Summary:

Remote module does not support check mode
##### Steps To Reproduce:

N/A
##### Expected Results:

N/A
##### Actual Results:

N/A

### PR DESCRIPTION
**Pull request by fti7**
mount: Support for Check Mode fixes #181

### CODE REVIEW

**Comment by bcoca** [comment]
@fti7 could you rebase?

**Comment by bcoca** [comment]
could you rebase this?

**Comment by Jmainguy** [comment]
@fti7 think you could rebase this?

**Comment by gregdek** [comment]
Marking this "pending_closure" due to non-responsiveness of submitter.

@fti7 we would love to help you merge this, but if we don't hear from you within a week, we will close this PR unmerged.

**Comment by gregdek** [comment]
Closed due to non-responsiveness of original submitter.

**Pull request closed without merging**
