### PR TITLE
cron - discourage line breaks in job param

### LINKED ISSUE #4312: Adding `\n<something>` at the end of a job in the cron module breaks idempotence
#2316

##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

cron_module
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

Running with `retry_files_enabled = False`
##### OS / ENVIRONMENT

Debian testing running playbooks to a Debian squeeze machine
##### SUMMARY

Adding `\n<something>` at the end of a job in the cron module breaks idempotence.

I was trying this to try to fix #2316 
##### STEPS TO REPRODUCE

```
- name: cron
  cron: name="foo" hour=4 user="root"
           job="foobar\n#"
           cron_file=ansible_foobar
```
##### EXPECTED RESULTS

The cron file create should be:

```
* 4 * * * root foobar
#
```

And stay like this each time the playbook is ran
##### ACTUAL RESULTS

The cron file created is at first:

```
* 4 * * * root foobar
#
```

Then after running the playbook a second time it becomes:

```
* 4 * * * root foobar
#
#
```

And so on.

### PR DESCRIPTION
**Pull request by EvanK**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

cron module
##### ANSIBLE VERSION

```
2.1.1.0
```
##### SUMMARY

~~Fails~~ **generates a warning for** any `job` containing line breaks.

With #4285 merged (strips leading/trailing line breaks) and #4330 marked for inclusion (fixes trailing newline at end of cron file), there should be no sane reason for an individual job to contain line breaks -- see my rationale in #4312. This ~~enforces~~ **gently encourages** such a limitation and updates documentation accordingly.

Closes #4312

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks again to @EvanK. This module is going into community review.

We notice that you are one of the maintainers (@dsummersl, @EvanK) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @EvanK for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by EvanK** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @EvanK. To the current maintainers, @dsummersl, @EvanK please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @EvanK for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by EvanK** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @EvanK. To the current maintainers, @dsummersl, @EvanK please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @EvanK for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by EvanK** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @EvanK. To the current maintainers, @dsummersl, @EvanK please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by EvanK** [comment]
shipit

**Comment by gregdek** [comment]
Thanks @EvanK. Since you are one of the maintainers (@dsummersl, @EvanK) of this module and you commented with "shipit", we are marking this PR for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Review by dsummersl — APPROVED** [review]

**Comment by dsummersl** [comment]
shipit

**Pull request closed without merging**
