### PR TITLE
document how force=no works for win_get_url and add RETURN

### LINKED ISSUE #3457: win_get_url: with force=no - (403 error) cant get file timestamp from https://github.com
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

win_get_url
##### ANSIBLE VERSION

```
id@emachines-e520:~/ansible$ ansible --version
ansible 2.0.0.2
  config file = /home/id/ansible/ansible.cfg
  configured module search path = ./library
```

Where `./library` is checked out from `ansible/$repo_name:devel`.
##### CONFIGURATION

``` ini
[defaults]
bin_ansible_callbacks=True
inventory = ./inventory/lan
callback_plugins = ./callback_plugins
library = ./library
hash_behaviour = merge
```

AFAIK nothing was changed since `1.9.4`, and this same playbook used to work back then.
##### OS / ENVIRONMENT
- Linux (ubuntu 15.10) control node.
- Windows 10 (WINRM) target host.
##### SUMMARY

force = no checks the timestamp from http headers. However github.com returns a 403 and it errors out for some reason.
##### STEPS TO REPRODUCE

```
- name: Install Brigadier.exe for Downloading Apple Bootcamp
  win_get_url:
    url: https://github.com/timsutton/brigadier/releases/download/0.2.4/brigadier.exe
    dest: "{{ binpath }}/brigadier.exe"
    force: no
  when: "'brigadier' in win_pkgs"
```
##### EXPECTED RESULTS

The .ps1 script gets http headers of file (from github). Then extracts the `Last-Modified:` header. So it can compare it to the timestamp on the local file.
##### ACTUAL RESULTS

```
TASK [4_pkgs : Install Brigadier.exe for Downloading Apple Bootcamp] ***********
fatal: [ga-z170x-g3]: FAILED! => {"changed": false, "failed": true, "msg": "Error when requesting Last-Modified date from https://github.com/timsutton/brigadier/releases/download/0.2.4/brigadier.exe Exception calling \"GetResponse\" with \"0\" argument(s): \"The remote server returned an error: (403) Forbidden.\""}
```

### PR DESCRIPTION
**Pull request by jhawkesworth**
##### ISSUE TYPE

- Docs Pull Request
##### COMPONENT NAME

win_get_url
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = 
  configured module search path = Default w/o overrides

```
##### SUMMARY

Sort of fixes https://github.com/ansible/ansible-modules-core/issues/3457 by telling users how it works

```
<!--- Paste verbatim command output here, e.g. before and after your change -->
```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @jhawkesworth for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by jhawkesworth** [comment]
Not really sure why travis doesn't like this

The command "python2.7 -m compileall -fq ." exited with 0.

0.45s$ python3.4 -m compileall -fq . -x $(echo "$PY3_EXCLUDE_LIST"| tr ' ' '|')

**\* Error compiling './windows/win_get_url.py'...

  File "./windows/win_get_url.py", line 126

```
'''

 ^
```

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 224-225: truncated \UXXXXXXXX escape

The command "python3.4 -m compileall -fq . -x $(echo "$PY3_EXCLUDE_LIST"| tr ' ' '|')" exited with 1.

0.39s$ python3.5 -m compileall -fq . -x $(echo "$PY3_EXCLUDE_LIST"| tr ' ' '|')

**\* Error compiling './windows/win_get_url.py'...

  File "./windows/win_get_url.py", line 126

```
'''

 ^
```

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 224-225: truncated \UXXXXXXXX escape

Perhaps it was a newline

**Comment by sivel** [comment]
A quick search indicates that it is due to needing to escape your `\` chars to look like `\\`

**Comment by jhawkesworth** [comment]
Thanks @sivel, having another go now

**Comment by jhawkesworth** [comment]
looks like travis is happy now.  I think the bot will remove the needs revision label so I will leave it as now.

**Comment by jhawkesworth** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @jhawkesworth. To the current maintainers, @jhawkesworth please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by jhawkesworth** [comment]
Have remembered that I'm the owner of win_get_url these days.  Still doesn't seem right for me to merge it though.  I guess it can wait till the next parse through the docs pull requests.

**Pull request merged**
