### PR TITLE
Expand the user home folder in the key_file argument of the git module

### LINKED ISSUE #91: git module key_file= option doesn't interpret the ~/ as $HOME
[This is a clone of ansible/ansible#7533 of which I am **not** the author]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.2
##### Environment:

Ubuntu 12.04
##### Summary:

git module key_file= option doesn't interpret the ~/ as $HOME
##### Steps To Reproduce:

```
git: repo=ssh://git@bitbucket.org/xxx/yyyy.git dest=~/compile key_file=~/.ssh/bitbucket_app -vvvv
```
##### Expected Results:

read the keyfile and checkout from git :)
##### Actual Results:

```
<localhost> REMOTE_MODULE git repo=ssh:********@bitbucket.org/xxx/yyy.git dest=~/compile key_file=~/.ssh/bitbucket_app
failed: [localhost] => {"cmd": "/usr/bin/git ls-remote origin -h refs/heads/master", "failed": true, "item": "", "rc": 128}
stderr: Warning: Identity file ~/.ssh/bitbucket_app not accessible: No such file or directory.
```

### PR DESCRIPTION
**Pull request by astorije**
This is a clone of https://github.com/ansible/ansible/pull/8351 (cloned after the repository structure change), that is based of a recent version of the `git`module.

It fixes #91 by using `expanduser` and `abspath` on the `key_file` argument.

### CODE REVIEW

**Comment by astorije** [comment]
@mpdehaan thanks for labeling this PR.

Anything I can do to help merging this? It stayed open about 2 months before the repo structure organization and I'd be more responsive to fix things related to it soon rather than in another few months.

**Comment by astorije** [comment]
@mpdehaan or @bcoca, any chance this can be merged (or commented) sometime soon? It's kind of an annoying bug as I need to hack my playbooks to have them working. Pleeease :)

If not, well still a big thank you for your work on this project!!

**Comment by bcoca** [comment]
@astorije  its in the queue, we are trying to do them in priority order and right now we are going through the P2s

**Comment by astorije** [comment]
Hey @bcoca thanks for the update. I kind of wished it could go to P2 when I submitted it, but well, I guess it is not annoying that many people :)

Good luck going through P2s, let me know if I can help with this PR!

**Comment by abadger** [comment]
Simple and looks good.  Thanks!

# Merged

Hi!

This has been merged in, and will also be included in the next major release.

If you or anyone else has any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Comment by astorije** [comment]
Thanks a lot @abadger and the rest of the team! Long live Ansible!

**Pull request merged**
