### PR TITLE
win_file: no longer causes a stack trace if called with --diff & extra return info

### LINKED ISSUE #3700: playbook --diff option crashes when win_copy or win_template used
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

win_copy
win_template
##### ANSIBLE VERSION

```
ansible 2.0.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
## /etc/ansible/ansible.cfg

forks          = 20
ansible_managed = Ansible managed: Do NOT manually edit.
retry_files_save_path = ~/.ansible-retry
no_target_syslog = True
ssh_args = -o ControlMaster=auto -o ControlPersist=30m
pipelining = True
verbose = bright blue
## /etc/ansible/group_vars/windows/vars.yml

ansible_user: administrator
ansible_port: 5986
ansible_connection: winrm
ansible_winrm_server_cert_validation: ignore

The ansible_password for the 'windows' group is in a vault.
##### OS / ENVIRONMENT

Debian stable (jessie) using Ansible from Debian jessie-backports repository.
##### SUMMARY

When running a playbook with either a win_copy or win_template module being used, it'll crash when if the --diff command line flag is used when the destination file is created or changes.
If the destination file already exists in a state where no change is necessary then the crash does not occur.

Without the use of --diff the playbook will run to completion.
##### STEPS TO REPRODUCE

I've created a playbook with the following files and content:

```
$ cat site.yml

---

- hosts: jenkins-slaves

  roles:
  - { role: test }


$ cat roles/test/files/test_file.txt
This is a test file.


$ cat roles/test/tasks/main.yml

---

- name: Make sure c:/temp directory exists
  win_file:
    path: c:/temp
    state: directory

- name: Remove c:/temp/test_file.txt to make sure the next step changes.
  win_file:
    path: c:/temp/test_file.txt
    state: absent

- name: Copy test_file.txt to c:/temp
  win_copy:
    src: test_file.txt
    dest: c:/temp/test_file.txt
```

And I run it like so to reproduce the problem:

```
ansible-playbook site.yml --diff
```

##### EXPECTED RESULTS

Running the command without --diff

```
$ ansible-playbook site.yml

PLAY [jenkins-slaves] **********************************************************

TASK [setup] *******************************************************************
ok: [per-jenkins-s01.hc.int]

TASK [test : Make sure c:/temp directory exists] *******************************
ok: [per-jenkins-s01.hc.int]

TASK [test : Remove c:/temp/test_file.txt to make sure the next step changes.] *
ok: [per-jenkins-s01.hc.int]

TASK [test : Copy test_file.txt to c:/temp] ************************************
changed: [per-jenkins-s01.hc.int]

PLAY RECAP *********************************************************************
per-jenkins-s01.hc.int     : ok=4    changed=1    unreachable=0    failed=0

```
##### ACTUAL RESULTS

First of all without -vvvv

```
$ ansible-playbook site.yml --diff

PLAY [jenkins-slaves] **********************************************************

TASK [setup] *******************************************************************
ok: [per-jenkins-s01.hc.int]

TASK [test : Make sure c:/temp directory exists] *******************************
ok: [per-jenkins-s01.hc.int]

TASK [test : Remove c:/temp/test_file.txt to make sure the next step changes.] *
changed: [per-jenkins-s01.hc.int]

TASK [test : Copy test_file.txt to c:/temp] ************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'state'
fatal: [per-jenkins-s01.hc.int]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}

NO MORE HOSTS LEFT *************************************************************
        to retry, use: --limit @/home/deploy/.ansible-retry/site.retry

PLAY RECAP *********************************************************************
per-jenkins-s01.hc.int     : ok=3    changed=1    unreachable=0    failed=1
```

Then if I add -vvvv

```
$ ansible-playbook site.yml --diff -vvvv
Using /etc/ansible/ansible.cfg as config file
Loaded callback default of type stdout, v2.0

PLAYBOOK: site.yml *************************************************************
1 plays in site.yml

PLAY [jenkins-slaves] **********************************************************

TASK [setup] *******************************************************************
<per-jenkins-s01.hc.int> ESTABLISH WINRM CONNECTION FOR USER: administrator on PORT 5986 TO per-jenkins-s01.hc.int
<per-jenkins-s01.hc.int> EXEC Set-StrictMode -Version Latest
(New-Item -Type Directory -Path $env:temp -Name "ansible-tmp-1463638825.06-222590266924537").FullName | Write-Host -Separator '';
<per-jenkins-s01.hc.int> PUT "/tmp/tmpTXNw2C" TO "C:\Users\Administrator\AppData\Local\Temp\ansible-tmp-1463638825.06-222590266924537\setup.ps1"
<per-jenkins-s01.hc.int> EXEC Set-StrictMode -Version Latest
Try
{
& 'C:\Users\Administrator\AppData\Local\Temp\ansible-tmp-1463638825.06-222590266924537\setup.ps1'
}
Catch
{
$_obj = @{ failed = $true }
If ($_.Exception.GetType)
{
$_obj.Add('msg', $_.Exception.Message)
}
Else
{
$_obj.Add('msg', $_.ToString())
}
If ($_.InvocationInfo.PositionMessage)
{
$_obj.Add('exception', $_.InvocationInfo.PositionMessage)
}
ElseIf ($_.ScriptStackTrace)
{
$_obj.Add('exception', $_.ScriptStackTrace)
}
Try
{
$_obj.Add('error_record', ($_ | ConvertTo-Json | ConvertFrom-Json))
}
Catch
{
}
Echo $_obj | ConvertTo-Json -Compress -Depth 99
Exit 1
}
Finally { Remove-Item "C:\Users\Administrator\AppData\Local\Temp\ansible-tmp-1463638825.06-222590266924537" -Force -Recurse -ErrorAction SilentlyContinue }
ok: [per-jenkins-s01.hc.int] => {"ansible_facts": {"ansible_architecture": "64-bit", "ansible_date_time": {"date": "19/05/2016", "day": "19", "hour": "14", "iso8601": "2016-05-19T14:20:26", "minute": "20", "month": "05", "year": "2016"}, "ansible_distribution": "Microsoft Windows NT 6.3.9600.0", "ansible_distribution_version": "6.3.9600.0", "ansible_fqdn": "per-jenkins-s01.hc.int", "ansible_hostname": "PER-JENKINS-S01", "ansible_interfaces": [{"default_gateway": "10.128.0.1", "dns_domain": "hc.int", "interface_index": 12, "interface_name": "vmxnet3 Ethernet Adapter"}], "ansible_ip_addresses": ["10.128.3.107", "fe80::250:56ff:febe:59ef", "fdcc:ea9c:25af:3:250:56ff:febe:59ef", "2002:74d4:f466:3:250:56ff:febe:59ef"], "ansible_lastboot": "2016-05-19 13:09:47Z", "ansible_os_family": "Windows", "ansible_os_name": "Microsoft Windows Server 2012 R2 Standard", "ansible_powershell_version": 4, "ansible_system": "Win32NT", "ansible_totalmem": 3220688896, "ansible_uptime_seconds": 4239, "ansible_winrm_certificate_expires": "2017-05-19 11:10:48"}, "changed": false, "invocation": {"module_name": "setup"}}

TASK [test : Make sure c:/temp directory exists] *******************************
task path: /home/deploy/playbooks/testing/roles/test/tasks/main.yml:3
<per-jenkins-s01.hc.int> ESTABLISH WINRM CONNECTION FOR USER: administrator on PORT 5986 TO per-jenkins-s01.hc.int
<per-jenkins-s01.hc.int> EXEC Set-StrictMode -Version Latest
(New-Item -Type Directory -Path $env:temp -Name "ansible-tmp-1463638826.72-119268660938328").FullName | Write-Host -Separator '';
<per-jenkins-s01.hc.int> PUT "/tmp/tmp6qttns" TO "C:\Users\Administrator\AppData\Local\Temp\ansible-tmp-1463638826.72-119268660938328\win_file.ps1"
<per-jenkins-s01.hc.int> EXEC Set-StrictMode -Version Latest
Try
{
& 'C:\Users\Administrator\AppData\Local\Temp\ansible-tmp-1463638826.72-119268660938328\win_file.ps1'
}
Catch
{
$_obj = @{ failed = $true }
If ($_.Exception.GetType)
{
$_obj.Add('msg', $_.Exception.Message)
}
Else
{
$_obj.Add('msg', $_.ToString())
}
If ($_.InvocationInfo.PositionMessage)
{
$_obj.Add('exception', $_.InvocationInfo.PositionMessage)
}
ElseIf ($_.ScriptStackTrace)
{
$_obj.Add('exception', $_.ScriptStackTrace)
}
Try
{
$_obj.Add('error_record', ($_ | ConvertTo-Json | ConvertFrom-Json))
}
Catch
{
}
Echo $_obj | ConvertTo-Json -Compress -Depth 99
Exit 1
}
Finally { Remove-Item "C:\Users\Administrator\AppData\Local\Temp\ansible-tmp-1463638826.72-119268660938328" -Force -Recurse -ErrorAction SilentlyContinue }
ok: [per-jenkins-s01.hc.int] => {"changed": false, "invocation": {"module_name": "win_file"}}

TASK [test : Remove c:/temp/test_file.txt to make sure the next step changes.] *
task path: /home/deploy/playbooks/testing/roles/test/tasks/main.yml:8
<per-jenkins-s01.hc.int> ESTABLISH WINRM CONNECTION FOR USER: administrator on PORT 5986 TO per-jenkins-s01.hc.int
<per-jenkins-s01.hc.int> EXEC Set-StrictMode -Version Latest
(New-Item -Type Directory -Path $env:temp -Name "ansible-tmp-1463638827.9-260778574954546").FullName | Write-Host -Separator '';
<per-jenkins-s01.hc.int> PUT "/tmp/tmpii91Ab" TO "C:\Users\Administrator\AppData\Local\Temp\ansible-tmp-1463638827.9-260778574954546\win_file.ps1"
<per-jenkins-s01.hc.int> EXEC Set-StrictMode -Version Latest
Try
{
& 'C:\Users\Administrator\AppData\Local\Temp\ansible-tmp-1463638827.9-260778574954546\win_file.ps1'
}
Catch
{
$_obj = @{ failed = $true }
If ($_.Exception.GetType)
{
$_obj.Add('msg', $_.Exception.Message)
}
Else
{
$_obj.Add('msg', $_.ToString())
}
If ($_.InvocationInfo.PositionMessage)
{
$_obj.Add('exception', $_.InvocationInfo.PositionMessage)
}
ElseIf ($_.ScriptStackTrace)
{
$_obj.Add('exception', $_.ScriptStackTrace)
}
Try
{
$_obj.Add('error_record', ($_ | ConvertTo-Json | ConvertFrom-Json))
}
Catch
{
}
Echo $_obj | ConvertTo-Json -Compress -Depth 99
Exit 1
}
Finally { Remove-Item "C:\Users\Administrator\AppData\Local\Temp\ansible-tmp-1463638827.9-260778574954546" -Force -Recurse -ErrorAction SilentlyContinue }
ok: [per-jenkins-s01.hc.int] => {"changed": false, "invocation": {"module_name": "win_file"}}

TASK [test : Copy test_file.txt to c:/temp] ************************************
task path: /home/deploy/playbooks/testing/roles/test/tasks/main.yml:13
<per-jenkins-s01.hc.int> ESTABLISH WINRM CONNECTION FOR USER: administrator on PORT 5986 TO per-jenkins-s01.hc.int
<per-jenkins-s01.hc.int> EXEC Set-StrictMode -Version Latest
(New-Item -Type Directory -Path $env:temp -Name "ansible-tmp-1463638829.08-120915265414229").FullName | Write-Host -Separator '';
<per-jenkins-s01.hc.int> PUT "/tmp/tmpR14tbv" TO "C:\Users\Administrator\AppData\Local\Temp\ansible-tmp-1463638829.08-120915265414229\stat.ps1"
<per-jenkins-s01.hc.int> EXEC Set-StrictMode -Version Latest
Try
{
& 'C:\Users\Administrator\AppData\Local\Temp\ansible-tmp-1463638829.08-120915265414229\stat.ps1'
}
Catch
{
$_obj = @{ failed = $true }
If ($_.Exception.GetType)
{
$_obj.Add('msg', $_.Exception.Message)
}
Else
{
$_obj.Add('msg', $_.ToString())
}
If ($_.InvocationInfo.PositionMessage)
{
$_obj.Add('exception', $_.InvocationInfo.PositionMessage)
}
ElseIf ($_.ScriptStackTrace)
{
$_obj.Add('exception', $_.ScriptStackTrace)
}
Try
{
$_obj.Add('error_record', ($_ | ConvertTo-Json | ConvertFrom-Json))
}
Catch
{
}
Echo $_obj | ConvertTo-Json -Compress -Depth 99
Exit 1
}
Finally { Remove-Item "C:\Users\Administrator\AppData\Local\Temp\ansible-tmp-1463638829.08-120915265414229" -Force -Recurse -ErrorAction SilentlyContinue }
<per-jenkins-s01.hc.int> EXEC Set-StrictMode -Version Latest
(New-Item -Type Directory -Path $env:temp -Name "ansible-tmp-1463638830.23-107221973557933").FullName | Write-Host -Separator '';
<per-jenkins-s01.hc.int> EXEC Set-StrictMode -Version Latest
(New-Item -Type Directory -Path $env:temp -Name "ansible-tmp-1463638830.56-147789613751721").FullName | Write-Host -Separator '';
<per-jenkins-s01.hc.int> PUT "/tmp/tmpl18pxj" TO "C:\Users\Administrator\AppData\Local\Temp\ansible-tmp-1463638830.56-147789613751721\file.ps1"
<per-jenkins-s01.hc.int> EXEC Set-StrictMode -Version Latest
Try
{
& 'C:\Users\Administrator\AppData\Local\Temp\ansible-tmp-1463638830.56-147789613751721\file.ps1'
}
Catch
{
$_obj = @{ failed = $true }
If ($_.Exception.GetType)
{
$_obj.Add('msg', $_.Exception.Message)
}
Else
{
$_obj.Add('msg', $_.ToString())
}
If ($_.InvocationInfo.PositionMessage)
{
$_obj.Add('exception', $_.InvocationInfo.PositionMessage)
}
ElseIf ($_.ScriptStackTrace)
{
$_obj.Add('exception', $_.ScriptStackTrace)
}
Try
{
$_obj.Add('error_record', ($_ | ConvertTo-Json | ConvertFrom-Json))
}
Catch
{
}
Echo $_obj | ConvertTo-Json -Compress -Depth 99
Exit 1
}
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 122, in run
    res = self._execute()
  File "/usr/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 424, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/lib/python2.7/dist-packages/ansible/plugins/action/copy.py", line 202, in run
    diffs.append(self._get_diff_data(dest_file, source_full, task_vars))
  File "/usr/lib/python2.7/dist-packages/ansible/plugins/action/__init__.py", line 620, in _get_diff_data
    if peek_result['state'] == 'absent':
KeyError: 'state'

fatal: [per-jenkins-s01.hc.int]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}

NO MORE HOSTS LEFT *************************************************************
        to retry, use: --limit @/home/deploy/.ansible-retry/site.retry

PLAY RECAP *********************************************************************
per-jenkins-s01.hc.int     : ok=3    changed=0    unreachable=0    failed=1
```

The same happens if I use win_template instead.

I don't mind that the module doesn't show me a diff, but it shouldn't crash the playbook when --diff is used.

### PR DESCRIPTION
**Pull request by jhawkesworth**
##### ISSUE TYPE

- Bugfix Pull Request
##### COMPONENT NAME

win_file
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel 221520cbad) last updated 2016/07/13 06:36:31 (GMT +100)
  lib/ansible/modules/core: (win_file_improvements 61e28d1b5f) last updated 2016/07/13 07:59:16 (GMT +100)
  lib/ansible/modules/extras: (devel 8fe06a86f7) last updated 2016/07/13 06:39:13 (GMT +100)
  config file = 
  configured module search path = Default w/o overrides

```
##### SUMMARY

The main purpose of the change was to fix https://github.com/ansible/ansible-modules-core/issues/3700

I also made the following minor improvements.
   Added created_utc, is_directory, operation, path, size return attributes
   Test-Path only called once now to make conditionals simpler to read

I documented the return values, and switched the existing examples to use the preferred 'yaml style' instead of 'key=value style' arguments.

Fixes https://github.com/ansible/ansible-modules-core/issues/3700

Using the reproducer playbook on https://github.com/ansible/ansible-modules-core/issues/3700

```
BEFORE:

ansible-playbook -l12 3700.yml --diff

PLAY [windows] *****************************************************************

TASK [setup] *******************************************************************
ok: [WIN-U10ID8KFK0E]

TASK [Make sure c:/temp directory exists] **************************************
ok: [WIN-U10ID8KFK0E]

TASK [Remove c:/temp/test_file.txt to make sure the next step changes.] ********
changed: [WIN-U10ID8KFK0E]

TASK [Copy test_file.txt to c:/temp] *******************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'state'
fatal: [WIN-U10ID8KFK0E]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}

NO MORE HOSTS LEFT *************************************************************
    to retry, use: --limit @3700.retry

PLAY RECAP *********************************************************************
WIN-U10ID8KFK0E            : ok=3    changed=1    unreachable=0    failed=1   


AFTER:

ansible-playbook -l12 3700.yml --diff

PLAY [windows] *****************************************************************

TASK [setup] *******************************************************************
ok: [WIN-U10ID8KFK0E]

TASK [Make sure c:/temp directory exists] **************************************
changed: [WIN-U10ID8KFK0E]

TASK [Remove c:/temp/test_file.txt to make sure the next step changes.] ********
ok: [WIN-U10ID8KFK0E]

TASK [Copy test_file.txt to c:/temp] *******************************************
changed: [WIN-U10ID8KFK0E]
--- before
+++ after: /home/jon/bug-fixing/test_file.txt
@@ -0,0 +1 @@
+This is a test file.


PLAY RECAP *********************************************************************
WIN-U10ID8KFK0E            : ok=4    changed=2    unreachable=0    failed=0   


```

I ran integration tests successfully against win_copy, win_file and win_template against 2008r2 ps3 and 2012r2 ps4

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks again to @jhawkesworth. This module is going into community review.

We notice that you are one of the maintainers (@jhawkesworth) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by jhawkesworth** [comment]
@nitzmahone @trondhindenes - could you give this a try?

Otherwise I think its ready to go so I'm going to add a 

shipit

**Comment by gregdek** [comment]
Thanks @jhawkesworth. Since you are one of the maintainers (@jhawkesworth) of this module and you commented with "shipit", we are marking this PR for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by jhawkesworth** [comment]
For info @JimBarber has documented testing the code that's on this PR on https://github.com/ansible/ansible-modules-core/issues/3700 (original bug report).

**Comment by gregdek** [comment]
Thanks @jhawkesworth for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@jhawkesworth A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by jhawkesworth** [comment]
@nitzmahone - if I recall you weren't keen on this implementation and I noticed a win_file refactoring branch the other day when I was updating my forks.  Is it worth me rebasing or shall we let this one die?

**Comment by jhawkesworth** [comment]
closing this.  Since there are now merge conflicts it would probably be easier for me to start again, if its in fact needed now.

**Comment by JimBarber** [comment]
This is still a problem in Ansible 2.2.
I'm the one that raised the original problem here:
https://github.com/ansible/ansible-modules-core/issues/3700

**Comment by jhawkesworth** [comment]
@JimBarber This is on my list to tackle this during bug fix period for 2.3.

I tried to create an integration test for this before but at the time there was no way to run just some parts of a playbook in diff mode.  

Because it affects a core module and it requires manual testing its tricky to get support for getting this merged at the moment, so once I have a new version I would be greatful if you could test it.

**Pull request closed without merging**
