### PR TITLE
Updated git.py: Fixing example usage for git+ssh

### PR DESCRIPTION
**Pull request by jmound**

### CODE REVIEW

**Comment by abadger** [comment]
The example appears to work just fine so there's no need to change this.

**Comment by sivel** [comment]
This change is actually invalid.  The example is correct.  You are switching away from the `ssh://` protocol but not switching the first delimiter after the hostname.

See the following link for the different SSH URL types for git: https://git-scm.com/book/en/v2/Git-on-the-Server-The-Protocols#The-SSH-Protocol

**Comment by jmound** [comment]
If so, something else is wrong. It works with ```repo=git@github.com:holman/dotfiles.git``` and fails with ```repo=ssh:\\git@github.com:holman/dotfiles.git```

* Setup (OSX 10.11)
```
$ mkdir delme; cd delme; mkvirtualenv delme
$ pip install ansible
$ pip freeze | grep ansible
ansible==1.9.4
$ cat hosts
[localhost]
127.0.0.1
```
* Working:
```
$ cat playbook.yml 
---

- hosts: localhost
  connection: local

  tasks:
    - git: repo=git@github.com:holman/dotfiles.git dest=./dotfiles
$ ansible-playbook -i hosts playbook.yml 

PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [127.0.0.1]

TASK: [git repo=git@github.com:holman/dotfiles.git dest=./dotfiles] *********** 
changed: [127.0.0.1]

PLAY RECAP ******************************************************************** 
127.0.0.1                  : ok=2    changed=1    unreachable=0    failed=0   
```
* Not working:
```
$ rm -rf dotfiles/
$ cat playbook.yml 
---

- hosts: localhost
  connection: local

  tasks:
    - git: repo=ssh://git@github.com:holman/dotfiles.git dest=./dotfiles
$ ansible-playbook -i hosts playbook.yml 

PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [127.0.0.1]

TASK: [git repo=ssh://git@github.com:holman/dotfiles.git dest=./dotfiles] ***** 
failed: [127.0.0.1] => {"cmd": "/usr/local/bin/git ls-remote 'ssh:********@github.com:holman/dotfiles.git' -h refs/heads/HEAD", "failed": true, "rc": 128}
stderr: ssh: Could not resolve hostname github.com:holman: nodename nor servname provided, or not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

msg: ssh: Could not resolve hostname github.com:holman: nodename nor servname provided, or not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/Users/justin/playbook.retry

127.0.0.1                  : ok=1    changed=0    unreachable=0    failed=1   
 
```

As far as I can tell, I have no ```ansible.cfg``` or ```~/.ssh/config``` set.

**Comment by jmound** [comment]
Thanks. I hadn't noticed the difference in the syntax.

**Comment by sivel** [comment]
The problem is that you can't just affix `ssh://` to he beginning of an SCP style url.

When you use `ssh://` you cannot use the `:` delimiter after the hostname.  You must use only `/`, as it is a URL.

When you omit that you are using SCP style syntax and must use the colon such as `user@host:path` 

The URL I reference should explain and further help address the confusion.

**Pull request closed without merging**
