### PR TITLE
Document `copy` module vault decryption behavior

### PR DESCRIPTION
**Pull request by fajpunk**
##### ISSUE TYPE
- Docs Pull Request
##### COMPONENT NAME

`copy` module
##### ANSIBLE VERSION

```
ansible 2.2.0 (copy-module-docs-vault 91d8f8fd4f) last updated 2016/09/27 15:11:53 (GMT -500)
  lib/ansible/modules/core:  not found - use git submodule update --init lib/ansible/modules/core
  lib/ansible/modules/extras:  not found - use git submodule update --init lib/ansible/modules/extras
  config file = 
  configured module search path = Default w/o overrides
```
##### SUMMARY

There is no documentation that I can see that describes how the ansible-vault can be used to encrypt arbitrary and even binary files, and that the `copy` module will decrypt them transparently if they are specified in the `src` argument. I have also submitted a PR to the Ansible vault docs: https://github.com/ansible/ansible/pull/17777

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @fajpunk for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by fajpunk** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @fajpunk for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by tiwoc** [comment]
Could this PR please be considered for merging? It would be great if the copy module docs mentioned that copy can be used with Vault-encrypted files.

**Pull request closed without merging**
