### PR TITLE
updating choices for rds parameter engines

### PR DESCRIPTION
**Pull request by jasonpaige**

### CODE REVIEW

**Comment by ghost** [comment]
:+1:

**Comment by gregdek** [comment]
Thanks @h1ppo. @tastychutney please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by aioue** [comment]
+1 really need this please

**Comment by johnprice99** [comment]
+1

**Comment by robynbergeron** [comment]
@tastychutney This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by aioue** [comment]
This is a trivial list update that fixes ansible not being able to create aurora param groups.

**Comment by scottanderson42** [comment]
#shipit

**Comment by noqcks** [comment]
please can we ship this :(

**Comment by gregdek** [comment]
@tastychutney still waiting on your review.  Please comment with text 'shipit' or 'needs_revision' as appropriate. If we don't hear from you within 14 days, we will start to look for additional maintainers for this module.

**Comment by tastychutney** [comment]
I reviewed it on the 14th. 

-scott

**Comment by gregdek** [comment]
Oh... @tastychutney is @scottanderson42. Well, our bot didn't know that. We will inform the bot. :)

Marking for inclusion. Thanks @h1ppo for the PR.

**Pull request merged**
