### PR TITLE
Do not leak the vtp_password in log

### PR DESCRIPTION
**Pull request by mscherer**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

nxos_vtp_password

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @mscherer. To the current maintainers, @jedelman8, @GGabriele, @privateip, @gundalow please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gundalow** [comment]
@alikins Did you cherrypick this into stable-2.2 as well, if not can you please do so, thanks

**Comment by alikins** [comment]
@gundalow Sure. Are we tracking 2.2-stable cherry-pick candidates  somewhere?

**Comment by gundalow** [comment]
I can see the fix has been applied to devel & stable-2.2.

**Pull request merged**
