### PR TITLE
Osx support for users/groups

### PR DESCRIPTION
**Pull request by renard**
##### Issue Type:

Feature Pull Request
##### Ansible Version:

```
ansible 1.8 (devel b7082677de) last updated 2014/08/29 00:02:43 (GMT +200)
```
##### Environment:

All, target Darwin Mac OS X
##### Summary:

Add basic users and groups management for Darwin Mac OS X hosts.
##### How to use:

Same as for other hosts.

Please note that this version does not yet support encrypted user
passwords. Be aware of security concerns.

### CODE REVIEW

**Comment by rayalan** [comment]
Is there anything that can be done to help this patch along? I did a quick check today and it rebased cleanly onto the top of devel and all tests passed.

**Comment by renard** [comment]
Is there a blocking point about merging that PR?

**Comment by bcoca** [comment]
first it needs a rebase as it cannot be merged, second we just need more time to get to it

**Comment by renard** [comment]
Here it is I rebased it.

**Comment by Grazfather** [comment]
This makes the GID field required. See issue #2073

**Pull request merged**
