### PR TITLE
Fixing bug, added missing param

### PR DESCRIPTION
**Pull request by GGabriele**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

nxos_feature
##### ANSIBLE VERSION

```
ansible 2.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/share/ansible/']
```
##### SUMMARY

Added needed missing param in `get_cli_body_ssh` function.

### CODE REVIEW

**Comment by gregdek** [comment]
maintainer unknown ping @gregdek @resmo @robynbergeron.

**Comment by resmo** [comment]
Thanks @GGabriele, 

I'll add you as a maintainer of this module (since your are the author).

**Comment by gregdek** [comment]
Thanks again to @GGabriele. This module is going into community review.

We notice that you are one of the maintainers (@privateip, @GGabriele) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by GGabriele** [comment]
shipit

**Comment by gregdek** [comment]
Thanks @GGabriele. Since you are one of the maintainers (@privateip, @GGabriele) of this module and you commented with "shipit", we are marking this PR for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by resmo** [comment]
@GGabriele this fix should be backported to 2.1 right?

**Comment by GGabriele** [comment]
@resmo correct

**Comment by resmo** [comment]
@GGabriele ok, done

**Pull request merged**
