### PR TITLE
Getting rid of a None type error when no resource tags are passed.

### PR DESCRIPTION
**Pull request by kwoodson**
##### ISSUE TYPE

Bugfix Pull Request
##### COMPONENT NAME

cloud/amazon/ec2_vpc.py
##### ANSIBLE VERSION

```
ansible 2.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

I don't think this is dependent on ansible version.
##### SUMMARY

```
Using module file /usr/lib/python2.7/site-packages/ansible/modules/core/cloud/amazon/ec2_vpc.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: kwoodson
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 && sleep 0'
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_yU0wjd/ansible_module_ec2_vpc.py", line 745, in <module>
    main()
  File "/tmp/ansible_yU0wjd/ansible_module_ec2_vpc.py", line 737, in main
    (vpc_dict, new_vpc_id, subnets_changed, igw_id, changed) = create_vpc(module, vpc_conn)
  File "/tmp/ansible_yU0wjd/ansible_module_ec2_vpc.py", line 419, in create_vpc
    existing_tags_subset_of_new_tags = (set(csn.tags.items()).issubset(set(new_subnet_tags.items())))
AttributeError: 'NoneType' object has no attribute 'items'

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_name": "ec2_vpc"
    }, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_yU0wjd/ansible_module_ec2_vpc.py\", line 745, in <module>\n    main()\n  File \"/tmp/ansible_yU0wjd/ansible_module_ec2_vpc.py\", line 737, in main\n    (vpc_dict, new_vpc_id, subnets_changed, igw_id, changed) = create_vpc(module, vpc_conn)\n  File \"/tmp/ansible_yU0wjd/ansible_module_ec2_vpc.py\", line 419, in create_vpc\n    existing_tags_subset_of_new_tags = (set(csn.tags.items()).issubset(set(new_subnet_tags.items())))\nAttributeError: 'NoneType' object has no attribute 'items'\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "parsed": false
}

```

The code defaults to an empty dictionary instead of None.  This prevents the code from throwing the None type exception.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @kwoodson. To the current maintainers, @carsongee please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by carsongee** [comment]
shipit

**Comment by gregdek** [comment]
Thanks again to @kwoodson for this PR, and thanks @carsongee for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by abadger** [comment]
No errors fro mthis but for symmetry I'd also change Line 447: https://github.com/ansible/ansible-modules-core/pull/4638/files#diff-2075e0e67e4a09450bcdc16c642a772fR447

That way if new_subnet_tags ever gets used below the if-then-else blocks it will be a dict whichever code path was used.

**Comment by ryansb** [comment]
LGTM

**Comment by kwoodson** [comment]
@abadger, updated Line 447 as well.

Both return empty dict.

**Comment by abadger** [comment]
Merged to devel and cherry-picked to stable-2.1.  It will be in 2.1.2 _if_ we do another 2.1.2rc.  If not, it will be in 2.1.3 if we make another 2.1.x release.

**Pull request merged**
