### PR TITLE
Fixes: #3232. Use of datetime consistent with module_utils/basic.py

### PR DESCRIPTION
**Pull request by ghost**
##### Issue Type:
- Bugfix Pull Request
##### Plugin Name:

accelerate
##### Summary:

Make use of `datetime` consistent with `lib/ansible/module_utils/basic.py` to prevent the import of the latter stopping the module from initializing the accelerate daemon

### CODE REVIEW

**Comment by bcoca** [comment]
I'm not sure I understand what the problem is here, can you elaborate on what the error is?

**Comment by ghost** [comment]
Sorry, I should have added a gist of the generated module script. https://gist.github.com/geoffwright/b34dd361b0a1a7dd71b6

The accelerate module imports datetime with `from datetime import datetime`, shortly after `module_utils/basic.py` gets pulled in and imports datetime with `import datetime`. After `module_utils/basic.py` boilerplate is done we go back to the accelerate module and it attempts `datetime.now()` and fails.

**Comment by mattclay** [comment]
Tested on Ubuntu 15.10, fixes the issue for me.

**Comment by abadger** [comment]
Merged to both devel and stable-2.0.   Thanks @geoffwright for the fix and @mattclay for the review

**Comment by abadger** [comment]
Note -- once we have ziploader in 2.1.0 we should be able to remove `the import *` portion of the import from basic and then we won't have to worry about this.

**Pull request merged**
