### PR TITLE
restore mem_limit

### PR DESCRIPTION
**Pull request by larsks**
mem_limit got lost in the #1744; this restores it.  Thanks to @dgromov
for the report.

### CODE REVIEW

**Comment by larsks** [comment]
@dgromov if you have the chance please confirm that this fixes your report.  Thanks!

**Comment by dgromov** [comment]
Yeah, this does fix my issue. Based on https://github.com/docker/docker-py/pull/644/ this should also work with 1.19 so I'm happy. Thanks!

**Comment by gregdek** [comment]
@cove @joshuaconner @softzilla @smashwilson Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please give it a +1; at that point, we will add the “priority_reviewed” flag to this PR, which will move it to the top of our queue for potential inclusion.

**Comment by joshuaconner** [comment]
+1 

lgtm thanks!

**Pull request merged**
