### PR TITLE
Preserve order during Yaml to JSON parsing

### PR DESCRIPTION
**Pull request by bgeesaman**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

cloudformation module
##### ANSIBLE VERSION

```
ansible 2.0.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

When using template_format: yaml in the cloudformation module, the order of the yaml components are not preserved during the parsing to JSON (which is fine per JSON's spec). This results in a syntactically valid JSON document that cloudformation happily accepts. However, when viewing the running template in the AWS Cloudformation GUI of the stack that was just created, the order really helps readability. Preserving order just helps us humans looking at the parsedJSON to have a better chance at reading/troubleshooting issues when comparing the source Yaml to the actual JSON result.

```
N/A as visual output remains unchanged.
```

Adapted the bits from here: https://gist.github.com/yuvipanda/10481205

### CODE REVIEW

**Comment by resmo** [comment]
Thanks @bgeesaman. To the current maintainers, @jsmartin please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by jsmartin** [comment]
@resmo I did not merge or review the feature this PR is referring to.  Not a huge fan of using an alternate format for the templates, tbh.  Looks like @bcoca did the original:  https://github.com/ansible/ansible-modules-core/pull/1435

**Comment by bgeesaman** [comment]
We're merging generated snippets of yaml (mostly updating AMI mappings after AMI builds with packer) via a single jinja template to create the final CF template in yaml followed by a call to the cloud formation module specifying that yaml file. This is/was far more usable than trying to jam in those sections using raw JSON (watch the commas!) or to have to add in an additional outside tool to do the template merging like troposphere. @tedder gave us the inspiration from the comment in #1435 and it's actually pretty elegant in practice for simple use cases like ours.

**Comment by gregdek** [comment]
Thanks again to @bgeesaman for this PR, and thanks @jsmartin for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by resmo** [comment]
(cleared some bot comments as the bot was confused by my comments, sorry for the wrong messages)

**Comment by gregdek** [comment]
Thanks @bgeesaman. To the current maintainers, @jsmartin please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @bgeesaman for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by tedder** [comment]
I assume this becomes moot once native yaml support is added, yeah?

**Comment by ryansb** [comment]
This is now obsolete since native YAML support is in now.

**Pull request closed without merging**
