### PR TITLE
Added 'suspended' as desired state for VM

### PR DESCRIPTION
**Pull request by berney**
##### ISSUE TYPE

- Feature Pull Request
##### COMPONENT NAME

cloud/vmware/vsphere_guest
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file =
  configured module search path = Default w/o overrides
```
##### SUMMARY

Add 'suspended' as a desired state for a VM.
Doesn't error about force being needed if VM is already suspended.

```
TASK [vsphere : Suspend vSphere Guest VM] ************************************
ok: [vcsa -> localhost] => (item=Test VM)

PLAY RECAP ******************************************************************
vcsa                                : ok=1             changed=0          unreachable=0             failed=0
```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @berney. To the current maintainers, @chrrrles, @rhoop please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @berney for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by berney** [comment]
I was missing 'suspended' in main() as a desired state level, I've fixed this now.

**Comment by berney** [comment]
This has been migrated to https://github.com/ansible/ansible/pull/19202 after the ansible repository changes.

**Pull request closed without merging**
