### PR TITLE
place holder and docs for respective action plugin

### PR DESCRIPTION
**Pull request by chrismeyersfsu**
##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

- set_artifact

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @chrismeyersfsu for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by abadger** [comment]
license header and return documentation are missing (that's why test-sanity is failing in shippable)

**Comment by chrismeyersfsu** [comment]
Related to https://github.com/ansible/ansible/pull/18689

**Comment by bcoca** [comment]
closed via set_stats

**Pull request closed without merging**
