### PR TITLE
Task to copy a file remotely

### PR DESCRIPTION
**Pull request by aseigneurin**
I would like to submit this task that copies a file from the remote server to the remote server. This task differs from the "copy" task that copies a file from the local host to the remote server.

The copy is only performed if the MD5 sum of the file has changed, making this task idempotent, as opposed to executing the "cp" shell command.

Let me know if this makes sense or if there is a better alternative.

### CODE REVIEW

**Comment by alex-deref** [comment]
Hi, I had a similar requirement just the other day, and put together a draft with the same idea, but also supporting recursive copy. You can see discussion on the mailing list (subject: New module (draft) for copying files locally.)

https://groups.google.com/forum/#!topic/ansible-devel/97ppWbwLp5w

And you can see my code here:

https://gist.github.com/alex-deref/dc66a0ca7e1904c30508

**Comment by aseigneurin** [comment]
Looks very nice! I shall give this a try.

**Comment by aseigneurin** [comment]
I've just tried your module and it's great!

It is a superset of the module I have submitted as you can both copy a whole directory or a single file, in both cases while being idempotent.

I would suggest doing a pull request with your code instead of mine.

**Comment by gregdek** [comment]
Hi @aseigneurin -- thanks for the PR! Unfortunately, new modules aren't being accepted into the Core modules repo. Could you please file this PR against the ansible/ansible-modules-extras repo and reference this PR in the new module? That way we can get the needed reviewers to take a look at it. Thanks, and sorry for the delay in responding here.

**Comment by bcoca** [comment]
actually, this overlaps with existing functionality in the copy module  (remote_src=true)

**Pull request closed without merging**
