### PR TITLE
Explanation of privilege escalation in notes

### PR DESCRIPTION
**Pull request by skylerbunny**
An attempt to make clear how privilege escalation works with respect to the src/source host and dest/destination host. One existing note was incorporated into three new ones, iterating each.

### CODE REVIEW

**Comment by gregdek** [comment]
@tima Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by tima** [comment]
shipit

(The Travis failure does not seem to be related to this specific commit.)

**Comment by gregdek** [comment]
Thanks @skylerbunny for the PR, and thanks @tima for the review.

(Travis issue was transient.)

Marking for inclusion.

**Comment by gregdek** [comment]
cc: @ansible/core team.

**Comment by jimi-c** [comment]
Merged, thanks!

**Pull request merged**
