### PR TITLE
Add support for S3 canned permissions. resolves #1939

### LINKED ISSUE #1939: Add support for S3 permissions
The amazon s3 module does not currently support setting permissions on buckets or objects. By default, all buckets are private.

Boto's S3 interface does support the use of canned ACL's.
See: http://boto.readthedocs.org/en/latest/s3_tut.html

### PR DESCRIPTION
**Pull request by jcowley**
Followed the patterns in google/gc_storage.py for consistency.

See the Boto S3 documentation here: http://boto.readthedocs.org/en/latest/s3_tut.html

### CODE REVIEW

**Comment by gregdek** [comment]
@lwade @ralph-tice Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by lwade** [comment]
Basic testing with:

'''    - name: Put object
      s3s: bucket=mybucket object=/my/desired/key.txt src=/tmp/test.txt mode=put permission=public-read
    - name: Create bucket
      s3s: bucket=mybucket2 mode=create permission=public-read
'''

Worked just fine and no problems there in the code, it's a simple operation.

@jcowley could you add an example to the docs section please?

Seems like in future it would be useful to have a permissions modification capability.

**Comment by jcowley** [comment]
Thanks @lwade.

There is one docs example already: [creating an empty bucket with permissions](https://github.com/ansible/ansible-modules-core/pull/1940/files#diff-ad894f56f9678a3a8ea3d5c8ae92890dR175). Let me know if other / different examples would be useful and I'll add them.

Agree that permission modification would be useful, and it is supported by Boto. How do you think that could best be exposed in the S3 module? If a 'modify' or 'update' mode were added, I would expect it to support modification of any attribute (including file contents), which could be complicated to implement and test. Alternatively, we could add a mode that's specific to updating permissions, but I'm not sure that's the best choice.

**Comment by lwade** [comment]
Hey @jcowley, sorry I must have missed that. 

Yes ref: permission modification. I think the idea of just adding a modify mode makes most sense, perhaps just to modify permissions on a key atm.

**Comment by lwade** [comment]
Anyhow, for another PR I think ;) Thanks @jcowley

**Comment by jcowley** [comment]
Thanks @lwade. So this one is good to merge in?

**Comment by bennojoy** [comment]
Hi!

This has been merged in, and will also be included in the next major release.

If you or anyone else has any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:

https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code
Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by Narenek** [comment]
@jcowley thanks for adding this feature, I was looking into doing it myself (though probably not as competently) and will definitely be using it.

**Comment by jcowley** [comment]
@narenek: You're welcome. Glad someone else will be using it.

**Pull request merged**
