### PR TITLE
Support for legacy docker registry warning message

### PR DESCRIPTION
**Pull request by hvpareja**
After the Docker 1.8 release and the new Docker Registry 2.1, the docker API returns an unexpected message for Ansible when pulling a docker image if the docker registry hasn't been upgraded. Although the pull is successful, Ansible fails because the warning message below was not considered in lines 1406 - 1407:

"<docker_image>: this image was pulled from a legacy registry.  Important: This registry version will not be supported in future versions of docker."

In order to make Ansible capable to accept the above message as a successful pull, I suggest to merge this pull request.

More info:

The old version of the docker registry: https://github.com/docker/docker-registry.
The new version of the docker registry: https://github.com/docker/distribution

### CODE REVIEW

**Comment by robynbergeron** [comment]
Hi @hvpareja -- thanks for this PR.

@cove @joshuaconner @softzilla @smashwilson -- 

Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by smashwilson** [comment]
Looks like this is fixing the same bug that #2376 addresses, but that one seems a bit more robust - it actually scans _all_ lines of pull output for the status messages that indicate that a download occurred.

I've already accepted that one, so hopefully it'll meet your needs, too :smile:

**Comment by zachbadgett** [comment]
#2376 does not fix this issue.

Running 2.0.1.0 it still fails on legacy registry error, I get a "Unrecognized status from pull.". I think this solution should be implemented to account for that status.

**Comment by gregdek** [comment]
@hvpareja A friendly reminder: this pull request has been marked as needing your action, and it hasn't been updated in the last month. 

If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we'll keep it open pending your changes.

If we receive no indication from you within a week, we will close this pull request.

**Comment by hvpareja** [comment]
Hi! Sorry @gregdek, I might missed the notification. I'll take action on Monday morning. 

Regards

**Comment by hvpareja** [comment]
Hi @gregdek, I've rebased the branch and it's ready for the community's review.

Regards

**Comment by gregdek** [comment]
Thanks @hvpareja. To the current maintainers, @cove, @softzilla, @smashwilson, @zfil, @ThomasSteinbach please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @hvpareja for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@hvpareja A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@hvpareja Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@hvpareja A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@hvpareja Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by hvpareja** [comment]
This PR can be closed @gregdek

**Comment by gregdek** [comment]
Thanks @hvpareja.

**Pull request closed without merging**
