### PR TITLE
Normalize security_groups parameters to allow mixed of names/ids

### PR DESCRIPTION
**Pull request by filipenf**
##### ISSUE TYPE

- Bugfix Pull Request

Fixes issue https://github.com/ansible/ansible-modules-core/issues/1719
##### COMPONENT NAME

ec2_lc
##### ANSIBLE VERSION

1.9.x / 2.0 / 2.1
##### SUMMARY

Fixes `No default VPC for this user` when creating a launch configuration using security group names instead of ids.

This hotfix takes advantage of `get_ec2_security_group_ids_from_names` added by @wimnat couple months ago.

This will also bring more flexibility as allows users to mix security groups names/ids when creating a launch configuration.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @filipenf for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by wimnat** [comment]
Maybe update documentation for sec group parameter to make it clear what version this functionality was added? needs_revision

**Comment by filipenf** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @filipenf for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @filipenf for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by filipenf** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @filipenf for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by mhbrown** [comment]
Thanks @filipenf. Hoping this gets merged sometime. It's been a while.

**Pull request closed without merging**
