### PR TITLE
Add support for encrypted EBS volumes in launch configuration

### PR DESCRIPTION
**Pull request by steynovich**
Add support for encrypted EBS volumes in launch configuration. This uses the same logic as encrypted volumes in the ec2 module.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @steynovich for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

**Comment by fuhrysteve** [comment]
If you want an EC2 instance running on an encrypted volume, you can to start from an encrypted AMI.

Here's a poor man's guide:
1. decide what AMI you want encrypted. Example: `ami-93e1cf84` (happens to be an Ubuntu 16.04 image)
2. In the AWS control panel, go to EC2 => AMI => Public Images => search for `ami-93e1cf84` => Right click => Copy AMI => enable encryption => click "Copy AMI"
3. Wait 20mins or so for it to copy & encrypt your new AMI image

Now you can use this new private encrypted AMI instead of whatever AMI you were using before, and it will magically be using an encrypted volume. You don't need this pull request to spin up an encrypted EC2 instance, if that's all you're trying to do.

**Comment by steynovich** [comment]
The purpose of this PR is to add support for encryption of additional EBS volumes (e.g. /dev/xvdf). Those blank volumes are created from scratch, not from snapshot or AMI.

**Comment by fuhrysteve** [comment]
Ah I see - that makes sense.

**Pull request closed without merging**
