### PR TITLE
Handle race condition in directory creation.

### LINKED ISSUE #1648: race condition in directory creation using file module
Ansible 1.9.2 (also observed this issue on 1.7.2)

mybook.yml:

```

---
-
  hosts: all
  serial: 10
  tasks:
  -
    file:
      path: "/tmp/banana"
      state: "directory"
```

myhosts

```
lh0
lh1
lh2
lh3
lh4
lh5
lh6
lh7
lh8
lh9
```

NB all these are aliases of 127.0.0.1 in my `/etc/localhosts`

The following command will occasionally fail, in my experience about 5% failure rate, but YMMV:

```
rm -rf /tmp/banana ; ansible-playbook -i myhosts  mybook.yml
```

```
PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [lh4]
ok: [lh0]
ok: [lh3]
ok: [lh1]
ok: [lh2]
ok: [lh6]
ok: [lh5]
ok: [lh7]
ok: [lh8]
ok: [lh9]

TASK: [file ] ***************************************************************** 
changed: [lh3]
failed: [lh0] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1435747470.28-279212074405278/file", line 2005, in <module>
    main()
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1435747470.28-279212074405278/file", line 279, in main
    os.mkdir(curpath)
OSError: [Errno 17] File exists: '/tmp/banana'
OpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: auto-mux: Trying existing master
debug1: mux_client_request_session: master session id: 2
Shared connection to lh0 closed.

ok: [lh1]
ok: [lh2]
ok: [lh4]
ok: [lh5]
ok: [lh6]
ok: [lh7]
ok: [lh9]
ok: [lh8]

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/ubuntu/mybook.retry

lh0                        : ok=1    changed=0    unreachable=0    failed=1   
lh1                        : ok=2    changed=0    unreachable=0    failed=0   
lh2                        : ok=2    changed=0    unreachable=0    failed=0   
lh3                        : ok=2    changed=1    unreachable=0    failed=0   
lh4                        : ok=2    changed=0    unreachable=0    failed=0   
lh5                        : ok=2    changed=0    unreachable=0    failed=0   
lh6                        : ok=2    changed=0    unreachable=0    failed=0   
lh7                        : ok=2    changed=0    unreachable=0    failed=0   
lh8                        : ok=2    changed=0    unreachable=0    failed=0   
lh9                        : ok=2    changed=0    unreachable=0    failed=0   
```

I have been able to automate the triggering of this with:

```
true; while [ $? == 0 ]; do rm -rf /tmp/banana ; ansible-playbook -i myhosts  mybook.yml ; done
```

### PR DESCRIPTION
**Pull request by mjg123**
If we try to make a directory, but someone else creates the directory
at the same time as us, we don't need to raise that error to the user.
They asked for the directory to exist, and now it does. This fixes
the race condition which was causing that error to be raised, and
closes #1648.

### CODE REVIEW

**Comment by mjg123** [comment]
Oh, my bad - failed CI on my first attempt. Good to go now.

**Comment by bcoca** [comment]
we would prefer to check that the OSError matches the EEXIST code instead of looking at directory creation, as that captures the explicit case and there are other reasons (mostly permissions) why you might get a traceback and not be able to see if the directory already exists.

**Comment by mjg123** [comment]
I can do that. The problem with EEXIST is that it doesn't distinguish between the path already existing as a file or as a directory, but a combination of EEXIST and os.isdir would be thorough enough.

**Comment by benediktarnold** [comment]
Will this fix be in the next 1.9 release?

**Comment by msabramo** [comment]
Would love to see this in a 1.9 release. We had a deploy today which ran into this and errored out halfway through, resulting in us getting the new version of our app on some nodes and the old version on other nodes. :frown:

**Comment by msabramo** [comment]
It would be great to backport this to 1.9

**Comment by datacarl** [comment]
Used this as workaround for 1.9

```
- stat: path={{path}}
  register: dir

- name: Create  dir
  file: path={{path}} state=directory
  when: dir.stat.exists == False
```

**Pull request merged**
