### PR TITLE
docker: fix image repo tags while polling image by digest

### LINKED ISSUE #2917: docker: pull image by digest is broken
##### ISSUE TYPE

Bug Report
##### COMPONENT NAME

_docker module
##### ANSIBLE VERSION

2.0.0.2
##### SUMMARY

ansible-2.0.0.2
docker-py-1.6.0

got error while trying to run image by digest:

[root@xxx ~]# ansible -i localhost -c local -m docker -a 'name=test username=reg password=xxxx image="reg.xxxx.com/core@sha256:1b2375b1896b155a1cb4642982716d600eb9db9a0ef8196816f9740eb476d6f6"' localhost
localhost | FAILED! => {
    "changed": false,
    "error": "APIError(HTTPError(u'500 Server Error: Internal Server Error for url: http+unix://var/run/docker.sock/v1.17/auth',),)",
    "failed": true,
    "msg": "failed to login to the remote registry, check your username/password."
}

but if I pull image manually it works:

[root@ba0 ~]# docker pull reg.xxxxxx.com/core@sha256:1b2375b1896b155a1cb4642982716d600eb9db9a0ef8196816f9740eb476d6f6
sha256:1b2375b1896b155a1cb4642982716d600eb9db9a0ef8196816f9740eb476d6f6: Pulling from core
23722516ba3e: Pull complete
7306025a0c80: Pull complete
a9bf3069f2d8: Pull complete
f999f7797861: Pull complete
56f05a7fa3ed: Pull complete
7dcfa77ddb83: Pull complete
de437bf3928d: Pull complete
139d7fd869c9: Pull complete
fd26f44056b7: Pull complete
66dcbd10ffca: Pull complete
78fc91261994: Pull complete
Digest: sha256:1b2375b1896b155a1cb4642982716d600eb9db9a0ef8196816f9740eb476d6f6
Status: Downloaded newer image for reg.xxxxxx.com/core@sha256:1b2375b1896b155a1cb4642982716d600eb9db9a0ef8196816f9740eb476d6f6
[root@ba0 ~]# ansible -i localhost -c local -m docker -a 'name=test username=reg password=xxxxx image="reg.xxxxxx.com/core@sha256:1b2375b1896b155a1cb4642982716d600eb9db9a0ef8196816f9740eb476d6f6"' localhost
localhost | SUCCESS => {

### PR DESCRIPTION
**Pull request by qiluo-msft**
##### ISSUE TYPE

Bugfix Pull Request
##### COMPONENT NAME

docker
##### ANSIBLE VERSION

```
2.0.x and later
```
##### SUMMARY

Fixes #2917: continue the work of awasilyev's pull request
- Rebase to latest devel branch
- Fix image repo tags while polling image by digest

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @qiluo-msft. To the current maintainers, @cove, @softzilla, @smashwilson, @zfil, @ThomasSteinbach please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @qiluo-msft for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by qiluo-msft** [comment]
Rebased. ready_for_review

**Comment by gregdek** [comment]
Thanks @qiluo-msft. To the current maintainers, @cove, @softzilla, @smashwilson, @zfil, @ThomasSteinbach please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by qiluo-msft** [comment]
Anything else needed for a review?

**Comment by gregdek** [comment]
Thanks @qiluo-msft for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@qiluo-msft A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by qiluo-msft** [comment]
Rebased. ready_for_review

**Comment by gregdek** [comment]
maintainer unknown ping @gregdek @resmo @robynbergeron.

**Comment by gregdek** [comment]
Thanks @qiluo-msft for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@ansible/core This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@ansible/core still waiting on your review. Please comment with text 'shipit' or 'needs_revision' as appropriate. If we don't hear from you within 14 days, we will start to look for additional maintainers for this module.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@ansible/core This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@ansible/core still waiting on your review. Please comment with text 'shipit' or 'needs_revision' as appropriate. If we don't hear from you within 14 days, we will start to look for additional maintainers for this module.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@ansible/core This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@ansible/core still waiting on your review. Please comment with text 'shipit' or 'needs_revision' as appropriate. If we don't hear from you within 14 days, we will start to look for additional maintainers for this module.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@ansible/core This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@ansible/core still waiting on your review. Please comment with text 'shipit' or 'needs_revision' as appropriate. If we don't hear from you within 14 days, we will start to look for additional maintainers for this module.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@ansible/core This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@ansible/core still waiting on your review. Please comment with text 'shipit' or 'needs_revision' as appropriate. If we don't hear from you within 14 days, we will start to look for additional maintainers for this module.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
