### PR TITLE
Add new docker parameter shm_size

### PR DESCRIPTION
**Pull request by dkerwin**
Hi,

Docker 1.10 introduces a new run parameter 'shm_size'. Upcoming docker-py release will support shm_size as well (code exists already). Would be awesome to have it in Ansible 2.1.

Cheers :beers: 
Daniel

### CODE REVIEW

**Comment by dkerwin** [comment]
ping

**Comment by robynbergeron** [comment]
Thanks @dkerwin. @cove @joshuaconner @softzilla @smashwilson @zfil @ThomasSteinbach please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
Thanks @dkerwin for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

**Comment by dkerwin** [comment]
Wow. Something went completely wrong. I'll revert

**Comment by dkerwin** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @dkerwin. @cove @joshuaconner @softzilla @smashwilson @zfil @ThomasSteinbach please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
Thanks @dkerwin. @cove @joshuaconner @softzilla @smashwilson @zfil @ThomasSteinbach please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by dkerwin** [comment]
10 days... ping

**Comment by dkerwin** [comment]
Getting close to our 2 month anniversary. Can some please have a look at this trivial patch? Thanks in advance

**Comment by dkerwin** [comment]
Another 2 weeks. Seriously? I really want to extend ansible and make it a great choice for docker deployments but you're giving me a hard time.

**Comment by gregdek** [comment]
@dkerwin sincere apologies. We do appreciate your contribution. The Docker module is an outlier, for a lot of reasons: fast moving target, reviewers who disagree, lots of PRs. For this reason, we are very close to completing a rewrite of the module entirety. Stay tuned.

**Comment by gregdek** [comment]
Spec is here: https://github.com/ansible/proposals/tree/master/docker

**Comment by gregdek** [comment]
Thanks @dkerwin for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@dkerwin A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by dkerwin** [comment]
I'm ready_for_review

**Comment by gregdek** [comment]
Thanks @dkerwin. To the current maintainers, @cove, @softzilla, @smashwilson, @zfil, @ThomasSteinbach please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @dkerwin for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@dkerwin A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@dkerwin Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
