### PR TITLE
module group: Check if the gid is set

### PR DESCRIPTION
**Pull request by thudry**
Check for Darwin if the gid is set. #1085

### CODE REVIEW

**Comment by rmgrimm** [comment]
Would it be better to have line 287 read as `def group_mod(self, **kwargs):` instead of `def group_mod(self, gid=None):`? It could then be consistent with the rest of the `group_mod` signatures in the file.

I made a similar and much smaller fix with #973. Unlike this one, mine doesn't allow gid to be optional as is described in the documentation.

**Comment by bambou42** [comment]
In the documentation gid is not required

    gid	no		Optional GID to set for the group.

**Comment by gregdek** [comment]
@bambou42 Thanks for submitting this pull request. Please accept our apologies for taking so long to review it.

Unfortunately, due to this delay, it appears that the underlying code has changed, and this PR needs to be rebased. If you believe that this PR still applies, please rebase and we will then put it into our (new, faster) community review process as soon as possible.  Again, apologies for the delay and the extra work.

**Comment by thudry** [comment]
It should be good now

**Comment by bcoca** [comment]
you have a merge commit now

**Comment by thudry** [comment]
Sorry :/ is it good now ?

**Comment by bcoca** [comment]
yes, i merged it already, thanks!

**Pull request merged**
