### PR TITLE
make git updates respect depth

### LINKED ISSUE #14954: git update with depth limit creates too big local repo
##### Issue Type:
- Feature Idea
##### Ansible Version:

```
ansible 1.9.4
  configured module search path = None
```

and 

```
ansible 2.0.1.0
  config file = /home/XXX/ansible.cfg
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

```
[defaults]
nocows = 1
```
##### Environment:

Fedora 23, git version 2.5.0
##### Summary:

When running playbook with git statement that has update=yes and depth=1, behaviour has changed with version 2.0. 

Now updated repository will become much bigger.
##### Steps To Reproduce:

Run this playbook with ansible 1.9 and 2.0 twice: 

```

---
- hosts: 127.0.0.1
  connection: local
  become: no
  tasks:
  - name: check out pma from git
    git: dest=./pma depth=1 update=yes repo=https://github.com/phpmyadmin/phpmyadmin.git
```
##### Expected Results:

With Ansible 1.9, in both runs the resulting size of pma directory is 76M. Would expect that in 2.0 result would be same, so updated repo does not grow without any updates.
##### Actual Results:

WIth Ansible 2.0, first run result ./pma dir 76M size but second run 
(updating cloned git repo) is resulting 603M directory.

### PR DESCRIPTION
**Pull request by robinro**
##### Issue Type:
- Bugfix Pull Request
##### Plugin Name:

source_control/git
##### Summary:

make git updates respect argument `depth`

until now `fetch` gets all tags and heads at full depth, this change
- uses `depth` argument for `fetch`
- only get the specified `version` in `fetch`
- Fixes ansible/ansible#14954

### CODE REVIEW

**Comment by robinro** [comment]
I'm not sure something breaks by removing the fetch of `tags/*`. I don't think it should because the checked out version is specified, but maybe someone assumes all tags are fetched.

**Comment by resmo** [comment]
Thanks @robinro for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

**Comment by robinro** [comment]
This might affect #527, I'll check this and add tests.

**Comment by abadger** [comment]
At today's Ansible Core meeting we reviewed the code and thought it looked good to merge.  We want integration tests so that we don't accidentally break it with other git fixes and we'll have to keep an eye out for any regressions with tag handling.  robinro is going to work on this and then we can merge.

https://meetbot.fedoraproject.org/ansible-meeting/2016-04-12/ansible_core_meeting.2016-04-12-15.08.log.html#l-64

**Comment by robinro** [comment]
@abadger integration tests are available at ansible/ansible#15391
I also added a change to be more conservative and always do a full clone when `depth` is not specified. This is what more what users might assume.

#527 is independent as far as I see.

**Comment by abadger** [comment]
Decided at today's meeting to merge @robinro will keep an eye out for bugs that could be related to this.

**Pull request merged**
