### PR TITLE
Adding docker_serivice module

### PR DESCRIPTION
**Pull request by chouseknecht**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

docker_service.py
##### ANSIBLE VERSION

```
ansible 2.2.0 (docker_container fca5ba153e) last updated 2016/05/06 23:42:16 (GMT -400)
  lib/ansible/modules/core: (detached HEAD 1f5cf669dd) last updated 2016/05/06 23:40:41 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 431591c2b4) last updated 2016/05/06 23:40:44 (GMT -400)
  config file =
  configured module search path = Default w/o overrides
```
##### SUMMARY

New module based on docker/compose python module. Consumes docker compose from a project directory or inline, allowing for the management of one or more services and containers in a stand-alone or swarm environment. Supports check mode and differences and attempts to idempotent.

### CODE REVIEW

**Comment by chouseknecht** [comment]
The build is failing because of version_added = '2.1'. The build expects a value of '2.2'. I would like to make this part of '2.1', if possible.

**Comment by sivel** [comment]
Your interpreter line also needs to be fixed.

needs_revision

**Comment by chouseknecht** [comment]
Missed that. Fixed now. Thanks!

**Comment by gregdek** [comment]
Thanks @chouseknecht for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @chouseknecht for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
