### PR TITLE
remove calling format to make fakes3 work

### PR DESCRIPTION
**Pull request by ghost**
fakes3 only works after this augment removed

### CODE REVIEW

**Comment by bcoca** [comment]
what happens when you don't use fakes3? should this not be conditional like is_secure?

**Comment by ch3n2k** [comment]
if OrdinaryCallingFormat is specified, the buckets and files created by Ansible are not accessible by other tools (like s3cmd). And files created by other tools are not accessible by Ansible either. If remove this parameter or using the default SubdomainCallingFormat, there will be no such issue.

**Comment by ch3n2k** [comment]
From the fakes3 side, we can see that there will be one more level of directory in the middle if OrdinaryCallingFormat is specified.

fakes3_root
  +---- bucket_name_1
  |
  +---- fakes3 ----  bucket_name_2

**Comment by ghost** [comment]
my fakes3 setup fault, needs to specify -H start parameter

**Pull request closed without merging**
