### PR TITLE
Add support for AWS Security Token Service (temporary credentials) to all AWS cloud modules in stable-1.9.

### PR DESCRIPTION
**Pull request by droxer**
AWS Security Token Service is really important features, and I think we probably need to have it in stable-1.9 version, so I did a cherry-pick from https://github.com/ansible/ansible-modules-core/commit/64a2077787904f144f77839660071f35f25d181f to stable-1.9.

### CODE REVIEW

**Comment by willthames** [comment]
I believe #2421 is the better fix as it uses `connect_to_aws` which has a special fix for boto/boto#2100. 

However, if you spot anything I've missed in #2421 that is present here, please let me know. Also, if you can test that #2421 meets your needs, that would be handy too!

**Comment by droxer** [comment]
@willthames #2421 looks more consistent, more than happy to have it. 

Right now, I desire to have the sts support in v1.9 very much.

**Comment by gregdek** [comment]
Assigning to core team for backport request.

**Comment by willthames** [comment]
@gregdek can we put the backport request against #2421 and not this PR please.

**Comment by droxer** [comment]
@willthames @gregdek I don't mind you take this PR or #2421 as a backport request. Just really want to have AWS sts in stable-1.9.

BTW, I tested the PR with security token already.

**Comment by gregdek** [comment]
Thanks @droxer. All backport requests must be reviewed by the core team, and this can take time. We appreciate your patience.

**Comment by gregdek** [comment]
Closing in favor of #2421. Thanks @droxer for the PR.

**Comment by droxer** [comment]
@gregdek, I am thinking this PR is different with #2421. This one is bugfix for AWS STS on stable-1.9 branch, and also it is a existed [commit](https://github.com/ansible/ansible-modules-core/commit/1500b5bcdb8cb49681d973c8b59648b8d198716c) from current devel branch. #2421 is only workable against devel branch which already have fixed AWS STS issue.

**Comment by willthames** [comment]
@droxer #2421 is just a change to use `connect_to_aws` (which is the better fix - as there is a boto bug that ignores security tokens otherwise). If it doesn't work against stable-1.9, I'll patch it as such.

Changing to `get_aws_connection_info` is not in itself enough (`connect_to_aws` does use that under the hood).

**Comment by droxer** [comment]
@willthames agreed withyou,  `get_aws_connection_info`  is not enough, but this commit also update params which passed to `connect_to_region`.

#2421 is a better fix compared with using `connect_to_region`, but it should be applied after this one if you want patch it on stable-1.9 branch. 

BTW, I already tested AWS STS by using this commit on stable-1.9 branch.

**Comment by willthames** [comment]
@droxer, apologies, you are quite correct. This change is needed too (for some reason I thought `connect_to_aws` obtained the `aws_connect_kwargs`).

**Comment by droxer** [comment]
@willthames no worries. :) 

Reopen this PR or you can just apply the commit in your #2421, it up to you. :)

**Comment by droxer** [comment]
@gregdek can you reopen the PR, and backport to branch stable-1.9.

**Pull request closed without merging**
