### PR TITLE
Unpack AWS reservations while waiting to terminate (Fixes #4011)

### LINKED ISSUE #4011: ec2 termination timeout when instance_ids contains instances from multiple reservations
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

ec2
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel 17447ff035) last updated 2016/06/20 11:08:27 (GMT -400)
  lib/ansible/modules/core: (detached HEAD f0f5272f90) last updated 2016/06/22 10:42:10 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 6cb6829384) last updated 2016/06/22 10:42:10 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

Linux minastirith 4.5.4-1-ARCH #1 SMP PREEMPT Wed May 11 22:21:28 CEST 2016 x86_64 GNU/Linux
##### SUMMARY

Waiting for terminating instances with ec2 module will timeout if all instances specified in `instance_id` are not from the same reservation.
##### STEPS TO REPRODUCE

Using the following playbook:

```
- hosts: localhost
  connection: local
  tasks:
    - name: Launch an instance
    - ec2:
        key_name: "{{ lookup('ENV', 'AWS_KEY_NAME') }}"
        aws_access_key: "{{ lookup('ENV', 'AWS_ACCESS_KEY_ID') }}"
        aws_secret_key: "{{ lookup('ENV', 'AWS_SECRET_ACCESS_KEY') }}"
        region: "us-west-2"
        state: present
        wait: yes
        image: ami-03de3c63
        instance_type: t2.nano
        wait_timeout: 300
      register: ec2
    - set_fact:
        instance_1: "{{ ec2.instances[0].id }}"

- hosts: localhost
  connection: local
  tasks:
    - name: Launch another instance from a different play
    - ec2:
        key_name: "{{ lookup('ENV', 'AWS_KEY_NAME') }}"
        aws_access_key: "{{ lookup('ENV', 'AWS_ACCESS_KEY_ID') }}"
        aws_secret_key: "{{ lookup('ENV', 'AWS_SECRET_ACCESS_KEY') }}"
        region: "us-west-2"
        state: present
        wait: yes
        image: ami-03de3c63
        instance_type: t2.nano
        wait_timeout: 300
      register: ec2
    - set_fact:
        instance_2: "{{ ec2.instances[0].id }}"


- hosts: localhost
  connection: local
  tasks:
    - name: Instances terminate in AWS but task times out
    - ec2:
        key_name: "{{ lookup('ENV', 'AWS_KEY_NAME') }}"
        aws_access_key: "{{ lookup('ENV', 'AWS_ACCESS_KEY_ID') }}"
        aws_secret_key: "{{ lookup('ENV', 'AWS_SECRET_ACCESS_KEY') }}"
        region: "us-west-2"
        instance_ids: ["{{ instance_1 }}", "{{ instance_2 }}"]
        state: 'absent'
        wait: yes
        wait_timeout: 60

```

I run: 

```
 ansible-playbook -i localhost, -e ansible_python_interpreter=python2 playbook.yml
```

This terminates the instances,  but the task times out.

##### EXPECTED RESULTS

Successful execution of the termination task.
##### ACTUAL RESULTS

```
(ansible)kotfic@minastirith:~/scratch/ec2_termination_playbooks ⇒ ansible-playbook -i localhost, -e ansible_python_interpreter=python2 playbook.yml

PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Launch an instance] ******************************************************
changed: [localhost]

TASK [set_fact] ****************************************************************
ok: [localhost]

PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Launch another instance from a different play] ***************************
changed: [localhost]

TASK [set_fact] ****************************************************************
ok: [localhost]

PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Instances terminate in AWS but task times out] ***************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "wait for instance termination timeout on Wed Jun 22 11:22:28 2016"}

NO MORE HOSTS LEFT *************************************************************
 [WARNING]: Could not create retry file 'playbook.retry'.         Unable to create local directories(): [Errno 2] No such file or directory:
''


PLAY RECAP *********************************************************************
localhost                  : ok=7    changed=2    unreachable=0    failed=1   

```

### PR DESCRIPTION
**Pull request by kotfic**
##### ISSUE TYPE

- Bugfix Pull Request
##### COMPONENT NAME

ec2
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel 17447ff035) last updated 2016/06/20 11:08:27 (GMT -400)
  lib/ansible/modules/core: (detached HEAD f0f5272f90) last updated 2016/06/22 10:42:10 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 6cb6829384) last updated 2016/06/22 10:42:10 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides


```
##### SUMMARY

Fixes #4011 Previously calculation of the number of instances that have been
terminated assumed all instances were in the first reservation returned
by AWS.  If this is not the case the calculated number of instances
terminated never reaches the number of instances and the module always
times out. By unpacking the instances we get an accurate number and the
module correctly exits.

Before:

```
(ansible)kotfic@minastirith:~/scratch/ec2_termination_playbooks ⇒ ansible-playbook -i localhost, -e ansible_python_interpreter=python2 playbook.yml

PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Launch an instance] ******************************************************
changed: [localhost]

TASK [set_fact] ****************************************************************
ok: [localhost]

PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Launch another instance from a different play] ***************************
changed: [localhost]

TASK [set_fact] ****************************************************************
ok: [localhost]

PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Instances terminate in AWS but task times out] ***************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "wait for instance termination timeout on Wed Jun 22 11:22:28 2016"}

NO MORE HOSTS LEFT *************************************************************
 [WARNING]: Could not create retry file 'playbook.retry'.         Unable to create local directories(): [Errno 2] No such file or directory:
''


PLAY RECAP *********************************************************************
localhost                  : ok=7    changed=2    unreachable=0    failed=1   

```

After:

```
(ansible)kotfic@minastirith:~/scratch/ec2_termination_playbooks ⇒ ansible-playbook -i localhost, -e ansible_python_interpreter=python2 playbook.yml

PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Launch an instance] ******************************************************
changed: [localhost]

TASK [set_fact] ****************************************************************
ok: [localhost]

PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Launch another instance from a different play] ***************************
changed: [localhost]

TASK [set_fact] ****************************************************************
ok: [localhost]

PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Instances terminate in AWS but task times out] ***************************
changed: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=8    changed=3    unreachable=0    failed=0   

(ansible)kotfic@minastirith:~/scratch/ec2_termination_playbooks ⇒

```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @kotfic for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by opadron** [comment]
👍  Looking forward to seeing this issue fixed.

**Comment by kotfic** [comment]
Any chance of seeing movement on this?  it is a clean fix for a bug that is giving us a lot of trouble!  Thanks!

**Comment by kotfic** [comment]
@gregdek @bcoca @abadger Any chance for a review on this?  Thanks!

**Comment by gregdek** [comment]
@kotfic my best recommendation to you is to join one of the upcoming Core Team meetings on IRC: 

https://github.com/ansible/community/blob/master/MEETINGS.md#core-team-meeting

**Comment by kotfic** [comment]
@gregdek Thanks will do!

**Pull request merged**
