### PR TITLE
Read files in chunks to avoid OOM scenarios for large files.

### PR DESCRIPTION
**Pull request by ghost**
The hash implementation originally read the entire file into memory which can lead to out of memory errors for large files.  Instead, read the file in chunks and update the hash iteratively.

### CODE REVIEW

**Comment by ghost** [comment]
I should have noticed the shared utils, sorry.  I also changed gc_storage.py to do the same as the S3 module.

**Comment by gregdek** [comment]
Hi @erewh0n. Thanks for submitting this pull request. Please accept our apologies for taking so long to review it.

Unfortunately, due to this delay, it appears that the underlying code has changed, and this PR needs to be rebased. If you believe that this PR still applies, please rebase and we will then put it into our (new, faster) community review process as soon as possible.  Again, apologies for the delay and the extra work.

**Comment by gregdek** [comment]
@erewh0n A friendly reminder: this pull request has been marked as needing your action, and it hasn't been updated in the last month. 

If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we'll keep it open pending your changes.

If we receive no indication from you within a week, we will close this pull request.

**Comment by abadger** [comment]
I took a quick look at this and realized that we had merged a fix for this already but that one had a bug and this one was better.  I've rebased this PR and merged it here: https://github.com/ansible/ansible-modules-core/commit/5f2b365faa456990dfa65c7d4ba3393168069f67

Sorry it took so long to get this one integrated and thanks for working on this!

# Merged

Hi!

This has been merged in, and will also be included in the next major release.

If you or anyone else has any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Pull request closed without merging**
