### PR TITLE
Fix win_copy problems from: https://github.com/ansible/ansible-modules-core/issues/1404

### PR DESCRIPTION
**Pull request by jhawkesworth**
and update documentation.

Requires
https://github.com/ansible/ansible/pull/11115

Note that originally this change required https://github.com/ansible/ansible/pull/11086 but I have closed that PR and replaced with the one above due to unwanted files in 11086 PR. (1st June 2015)

### CODE REVIEW

**Comment by cchurch** [comment]
:+1: Integration tests pass for me against these changes.

**Comment by jhawkesworth** [comment]
Thanks for testing.  Will see if I can sort out ansible/ansible#11086

**Comment by jhawkesworth** [comment]
rebased.  For some reason github seems to think I committed changes 13 days ago.

**Comment by jhawkesworth** [comment]
Thanks for merging. I think https://github.com/ansible/ansible/pull/11115
is also needed to ensure that the checksum always returns a string instead
of an array in the common powershell code. (and fix corresponding
integration test).

Sorry this one has been a bit of an epic.

Jon

**Pull request merged**
