### PR TITLE
Update Azure Module to work with azure.py=1.0.1

### PR DESCRIPTION
**Pull request by matiasdecarli**
This is due to [these](https://github.com/Azure/azure-sdk-for-python/blob/fa3119c497e98343c7f789e07d108d1d2d457bd2/ChangeLog.txt#L47) breaking changes

### CODE REVIEW

**Comment by robynbergeron** [comment]
@matiasdecarli Thanks for the PR. 

@jwhitbeck -- Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.
If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by bcoca** [comment]
this PR is not backwards compatible, we should support the older version of the library also

**Comment by matiasdecarli** [comment]
Will try to do this on the weekend

**Comment by matiasdecarli** [comment]
@bcoca done

**Comment by jwhitbeck** [comment]
@robynbergeron Unfortunately, I haven't used this module in over a year so I don't think I'm the best person to review this PR.

**Comment by tksarah** [comment]
@robynbergeron  @matiasdecarli  Notification , I found azure python module is 1.0.2.

**Comment by matiasdecarli** [comment]
@bcoca Can we merge this now?

**Comment by abacaj** [comment]
waiting for this ...

**Comment by leafmulch** [comment]
also waiting - thanks.

**Pull request merged**
