### PR TITLE
fix problem with file content and high cpu/out of memory errors

### PR DESCRIPTION
**Pull request by h0nIg**
fix problem with file content and high cpu/out of memory errors. i took a look and the reason is some weird stuff with ConvertTo-Json and the depth of 99. the user can still fetch the file and examine it. fixxes https://github.com/ansible/ansible-modules-core/issues/2330

### CODE REVIEW

**Comment by jhawkesworth** [comment]
I have not tried the following but I wonder if doing 

$logcontents = Get-Content $logfile | Select-Object -Property \* ;

Might reduce the memory and cpu usage 

I got the idea from this page about ConvertTo-Json : 

https://technet.microsoft.com/en-us/library/hh849922.aspx

**Comment by h0nIg** [comment]
not working. also tried with the following, but failed:

```
Set-Attr $result "log" $logcontents[0]
```

the funny part is: if i'm doing the following, its fast:

```
Set-Attr $result "log" $logcontents[0].Clone()
```

but the sad part is, this is slow too:

```
Set-Attr $result "log" $logcontents.Clone()
```

**Comment by gregdek** [comment]
Thanks @h0nIg. @sivel please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by jhawkesworth** [comment]
@h0nIg this was still bothering me.

I found a post suggesting you use export-clixml to examine what objects and methods are contained in a structure, and then I found an example here https://technet.microsoft.com/en-us/library/hh849952.aspx so it looks like something like the following would reduce the memory usage as $logcontents is just an array of strings, rather than an array of object references.

$logcontents = Get-Content $logfile | Out-String -stream

Worth a try?

**Comment by h0nIg** [comment]
omg... thats the solution. corrected commit, but this time the output will not be an array but an concatenated string of the stdout. the reason for changing is, that the user may want to .find('error string') == -1 on the full output instead of walking through the array (which you have to join and find() again). I think this change is ok, since ansible major version upgrade can break older versions

**Comment by h0nIg** [comment]
since @sivel is not responding, can somebody else review the change?

ping: @petemounce @elventear @smadam813 @jhawkesworth @angstwad @sivel @chrishoffman @cchurch

**Comment by jhawkesworth** [comment]
This change looks fine to me and if I were PR owner I would approve it.

Jon

**Comment by jhawkesworth** [comment]
@nitzmahone can you take a look at this at some point?

**Comment by mojo4life** [comment]
works_for_me

**Comment by koloros** [comment]
i would appreciate the inclusion.

works_for_me

ping: @trondhindenes @petemounce @elventear @smadam813 @jhawkesworth @angstwad @sivel @chrishoffman @cchurch

**Comment by nitzmahone** [comment]
This is a good stopgap fix until we get around to re-doing the JSON serialization to stop using Convert-ToJson. Merging to devel and backporting to 2.0.x.

**Comment by jhawkesworth** [comment]
Many thanks

**Pull request merged**
