### PR TITLE
Fix route53 issue when boto profile used.

### PR DESCRIPTION
**Pull request by jonhadfield**
This is a fix for issue #1901 which occurs when a profile is specified.
The route53 module imports the ec2 utils:
`from ansible.module_utils.ec2 import *`
Which has a method that checks for boto support calling:
`return hasattr(boto.ec2.EC2Connection, 'profile_name')`
Although boto IS imported, it's the boto.ec2 module that contains the EC2Connection class, so it will fail with:
`AttributeError: 'module' object has no attribute 'ec2'`
The PR adds the necessary import to the route53.py module to be consistent with others.

### CODE REVIEW

**Comment by robynbergeron** [comment]
Hi, @jonhadfield -- thanks for this PR. 

@bpennypacker -- Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

Note that a few folks have reported seeing this issue in #1901, so it would be great to get fixed up. Thanks! :D

**Comment by willthames** [comment]
I've suggested an alternative fix on #2405. Such a fix would address this for all modules, not just piecemeal. Props to @twaggs for spotting the link.

**Comment by gregdek** [comment]
So @willthames is it your opinion that we should close this PR in favor of #2405?

**Comment by willthames** [comment]
@gregdek, that is indeed my opinion

**Comment by mscherer** [comment]
remove needinfo, since the info was provided by willthames

**Comment by gregdek** [comment]
Closing in favor of #2405.

**Pull request closed without merging**
