### PR TITLE
Allow login database to be specified in postgresql_db and support redshift

### PR DESCRIPTION
**Pull request by MichaelAquilina**
I noticed that connecting to a Redshift cluster using the postgres module is not currently possible due to defaulting to "postgres" as the initial database used for login. Redshift does not contain such a database, it has "dev" instead. 

This change adds support for specifying the database to be used for login - adding support for Redshift as a result.

EDIT: Supporting redshift requires an additional "is_redshift" parameter which caters for the fact that the `pg_roles` table does not exist

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @MichaelAquilina for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

**Comment by MichaelAquilina** [comment]
Hi, any idea of a timeframe when this could be reviewed?

**Comment by gregdek** [comment]
Thanks @MichaelAquilina for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by MichaelAquilina** [comment]
read_for_review

**Comment by MichaelAquilina** [comment]
ready_for_review

**Comment by MichaelAquilina** [comment]
just realised my difftool automerged some stuff badly. Will fix.

**Comment by MichaelAquilina** [comment]
ready_for_review

**Comment by MichaelAquilina** [comment]
I seem to be getting an error from `/database/mysql/mysql_db.py` even though I havent even touched that file. I've rebased on the latest devel and the issue is still persisting. Do you have any idea what the issue could be @gregdek ?

**Comment by gregdek** [comment]
@MichaelAquilina check the rebase again; this is generally an "age of PR" kind of error. Maybe apply the patch against a clean checkout of devel?

**Comment by gregdek** [comment]
@MichaelAquilina A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@MichaelAquilina Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by MichaelAquilina** [comment]
I'm having some trouble getting this PR to pass the tests. Its not entirely obvious why but I still think that this something that should be kept open till I get the chance to look at it again :)

**Comment by gregdek** [comment]
@MichaelAquilina A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
