### PR TITLE
Add missing GPLv3 License header

### LINKED ISSUE #1643: Modules missing GPLv3 License header
The following modules are missing the GPLv3 License Header:
- cloud/amazon/ec2_eip.py
- cloud/amazon/ec2_group.py
- cloud/amazon/ec2_key.py
- cloud/amazon/ec2_scaling_policy.py
- cloud/openstack/keystone_user.py
- cloud/vmware/vsphere_guest.py
- commands/raw.py
- commands/script.py
- commands/shell.py
- files/fetch.py
- files/template.py
- inventory/add_host.py
- inventory/group_by.py
- utilities/logic/pause.py
- windows/win_template.py

Some of the above are docs only files for action plugins or windows modules.  however they are still technically code, it should probably still have license headers.

### PR DESCRIPTION
**Pull request by mikeputnam**
Fixes #1643

### CODE REVIEW

**Comment by gregdek** [comment]
Straight GPL header inclusions, nothing else. Should be acceptable to merge.

**Comment by bcoca** [comment]
we are still checking if we can do this

**Comment by gregdek** [comment]
Oh, right -- these kind of need to come from the original authors, don't they? Yeeeah.

**Comment by mikeputnam** [comment]
If it would be useful, I can reach out via Github comments to each person logged as the first commit for each file.

**Pull request merged**
