### PR TITLE
In pip.py, do not automatically add '-e' (editable) flag when a VCS URL is provided as package name.

### PR DESCRIPTION
**Pull request by albertca**
Implements #226

### CODE REVIEW

**Comment by dotsdl** [comment]
This is definitely worth merging. Was there originally some rationale for requiring the `-e` flag for VCS pip installs? For my use cases I don't want these installed in `develop` mode, and if I did I would explicit include the `-e` flag myself.

**Comment by tjanez** [comment]
I agree with @dotsdl.

Unfortunately, it might be necessary to introduce a new parameter to the `pip` module (e.g. `editable`) and set its default to `yes` to not break backwards compatibility. I wouldn't miss it though.

**Comment by gregdek** [comment]
Hi @albertca. Apologies for taking so long to review this. If you believe this PR still applies, please rebase it, and we will get it into our community review process immediately.

**Comment by gregdek** [comment]
@albertca A friendly reminder: this pull request has been marked as needing your action, and it hasn't been updated in the last month. 

If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we'll keep it open pending your changes.

If we receive no indication from you within a week, we will close this pull request.

**Comment by albertca** [comment]
2015-07-22 22:47 GMT+02:00 Greg DeKoenigsberg notifications@github.com:

> @albertca https://github.com/albertca A friendly reminder: this pull
> request has been marked as needing your action, and it hasn't been updated
> in the last month.
> 
> If you still believe that this PR applies, and you intend to address the
> issues with this PR, just let us know in the PR itself and we'll keep it
> open pending your changes.
> 
> If we receive no indication from you within a week, we will close this
> pull request.
> 
> Yes, I still believe the patch is worth it. Please, keep it opened.

I will create a new PR in the comming weeks.

> —
> Reply to this email directly or view it on GitHub
> https://github.com/ansible/ansible-modules-core/pull/227#issuecomment-123856919
> .

## 

Albert Cervera i Areny
Tel. 93 553 18 03
@albertnan
www.NaN-tic.com

**Comment by gregdek** [comment]
@albertca leaving it open. Thanks for letting us know.

**Comment by felix-engelmann** [comment]
created editable parameter which defaults to yes in pull request  #1988

**Comment by albertca** [comment]
I close the pull request as felix-engelmann proposal already looks good to me

**Pull request closed without merging**
