### PR TITLE
Add diff to apt.py

### PR DESCRIPTION
**Pull request by towolf**
for install, remove, deb_install, and upgrade actions.

Since apt has very commonly familiar output, just use the normal output
from apt-get or aptitude -- trimmed to the interesting parts -- to show
to the user if she specified --diff on the CLI.

Uses the recent support for the `diff['prepared]` key.

Fixes ansible/ansible#10239

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @towolf for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

**Comment by gregdek** [comment]
Thanks @towolf for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

**Comment by towolf** [comment]
Force pushed rebased PR: ready_for_review

Dunno why @ansible.com people who touched this file didn't have a look at open PRs for the same.

**Comment by towolf** [comment]
So, @abadger and @chrrrles, could you check this out? Brian already said [that it looks good to him](https://groups.google.com/d/msg/ansible-devel/-Vclg-cxJhM/p-rJnsjUDwAJ) on `ansible-devel`.

**Comment by towolf** [comment]
Adding diff to modules is on the official roadmap now.

**Comment by towolf** [comment]
@gregdek my other PR was broken again. It would be good if committers checked against [this tool](https://ansible.sivel.net/pr/byfile.html) if there are open PRs and maybe merge them if they are good to go before making conflicting edits.

Please merge as soon as it suits you folks.

**Comment by resmo** [comment]
tested locally, works for me. +1

**Pull request merged**
