### PR TITLE
Add prefixing and suffixing fuctionality to assemble module

### PR DESCRIPTION
**Pull request by underyx**
Bumped into the lack of this feature while writing a playbook and thought I'd help out. Hope it'll make it in before the 1.9 RC feature freeze!

Complemented by ansible/ansible#10399.

### CODE REVIEW

**Comment by gregdek** [comment]
@sfromm please review; if you +1 this change, we will mark P1_reviewed for faster inclusion.

**Comment by underyx** [comment]
For the record, the above commit is a rebase onto a46b3a4dc4d940f291ee94e5e488e491799d7bde.

**Comment by gregdek** [comment]
@underyx Thanks for submitting this pull request. Unfortunately, it appears that the underlying code has changed since your submission, and this PR now needs to be rebased. 

If you believe that this PR still applies, please rebase and we will put it into our community review process as soon as possible. 

Once you have rebased this PR, please add a comment with the text "ready_for_review" and we will continue with the review process.  Thanks!

**Comment by underyx** [comment]
Aww, again? :(

I'll fix this soon then.

**Comment by gregdek** [comment]
Yep, sorry. :/ Still working on process. The text "ready_for_review" will ensure that it hits my inbox (and ultimately a bot) for quicker triage.

**Comment by underyx** [comment]
Rebased onto 5b64993b227dc908a6f0d1d43509049a528ae425. 

ready_for_review

**Comment by gregdek** [comment]
Thanks @underyx -- sorry for the delay here.

@sfromm are you available to review changes to this PR?

If so, please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by underyx** [comment]
On an unrelated note, I'm currently at cz.pycon.org and I'm watching this talk about how important it is for open source contributors to be able to see that their contributions actually were useful for someone.

_wink wink nudge nudge :D_

**Comment by mscherer** [comment]
So the code look good to me, but I can't merge it due to conflict, can you rebase ?

I just have one question, why do you add a '\n' by default on the prefix/suffix ?
(also, you need to update the 'version_added' tag for 2.1 )

**Comment by underyx** [comment]
@mscherer Rebased onto 304a33a42bdebd37d892ca1d1066b07ac2d64ea9, and changed the `version_added` lines as well. Thanks!

**Comment by underyx** [comment]
@mscherer oh, and the rationale behind adding the `\n`s is simply to keep the prefix and suffix fragments' behavior consistent with all the other ones — I don't think there should be anything special about them other than their position in the rendered file, and the current code is adding newlines between fragments.

**Comment by underyx** [comment]
Thinking about this a bit more my current implementation does not ensure a newline between the last fragment and a suffix, so I'm changing

```
    if suffix is not None:
        if not suffix.endswith('\n'):
            suffix += '\n'
        tmp.write(suffix)
```

to

```
    if suffix is not None:
        if add_newline:
            suffix = '\n' + suffix
        if not suffix.endswith('\n'):
            suffix += '\n'
        tmp.write(suffix)
```

**Comment by gregdek** [comment]
Thanks @underyx for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

**Pull request merged**
