### PR TITLE
rackspace: use empty prefix to set files metadata.

### PR DESCRIPTION
**Pull request by vmihailenco**
Without prefix='' pyrax uses `X-Container-Meta-` prefix, so
`Access-Control-Allow-Origin` becomes
`X-Container-Meta-Access-Control-Allow-Origin`.

Without clear=True Rackspace API refuses to set metadata.

Details are available at https://github.com/rackspace/pyrax/issues/364

With this fix and https://github.com/ansible/ansible-modules-core/pull/1002 I am able to set `Control-Allow-Origin`:

```
- name: update data to the CDN
  rax_files_objects:
    container: mycontainer
    method: put
    src: /home/data
    api_key: "{{ rax_api_key }}"
    region: "{{ rax_region }}"
    username: "{{ rax_username }}"
    meta:
      Access-Control-Expose-Headers: "Access-Control-Allow-Origin"
      Access-Control-Allow-Origin: "*"
```

### CODE REVIEW

**Comment by sivel** [comment]
To maintain backwards compatibility, a new argument should be added that enables this functionality, defaulted to the way it works now.

**Comment by bcoca** [comment]
as @sivel mention, lets not break backwards compatibility

**Comment by vmihailenco** [comment]
@sivel @bcoca what do you think about https://github.com/ansible/ansible-modules-core/pull/1237 ? I am not interested in improving this PR since it does not fix our issue. I can make suggested change for https://github.com/ansible/ansible-modules-core/pull/1237 though.

**Comment by sivel** [comment]
@vmihailenco so are you saying we can close this PR?

**Comment by vmihailenco** [comment]
Yep, https://github.com/ansible/ansible-modules-core/pull/1237 contains the full fix and replaces this PR.

**Pull request closed without merging**
