### PR TITLE
Revert "Revert "Add OpenStack Router Gateway module""

### PR DESCRIPTION
**Pull request by emonty**
Reverts ansible/ansible-modules-core#1050

### CODE REVIEW

**Comment by bcoca** [comment]
requires rebase

**Comment by emonty** [comment]
Let's hold on this one for a sec - I think we can make it and the other two router modules take better advantage of underlying library much better.

**Comment by gregdek** [comment]
@emonty ping -- this now also needs rebase if it's still valid

**Comment by gregdek** [comment]
@emonty @shrews @dguerri @juliakreger @j2sol @rcarrillocruz any ideas on this one?

**Comment by Shrews** [comment]
Not sure what's up with the revert of the revert, but this module needs some cleanup. Adding needs_revision seems appropriate.

**Comment by gregdek** [comment]
So it needs revision _and_ rebase! Let's add both!

@emonty when you're ready, please add a comment with the text "ready_for_review" and we will continue with the review process.  Thanks!

**Pull request closed without merging**
