### PR TITLE
Run versioned validate-module from ansible/ansible stable-2.2

### PR DESCRIPTION
**Pull request by gundalow**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

validate-modules
##### ANSIBLE VERSION

n/a
##### SUMMARY

Run versioned validate-module from ansible/ansible stable-2.2

See https://github.com/ansible/ansible/pull/18001 for more details

---

This change is [Reviewable](https://reviewable.io/reviews/ansible/ansible-modules-core/5330)

### CODE REVIEW

**Comment by gregdek** [comment]
maintainer unknown ping @gregdek @resmo @robynbergeron.

**Comment by gregdek** [comment]
Thanks @gundalow. All backport requests must be reviewed by the core team, and this can take time. We appreciate your patience. 

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @gundalow for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gundalow** [comment]
ready_for_review

**Comment by mattclay** [comment]
shipit

**Comment by gregdek** [comment]
Thanks again to @gundalow for this PR. This PR was reviewed by an Ansible member. Marking for inclusion.

However, we would still appreciate if the maintainer(s) @ansible/core could look over it.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gundalow** [comment]
Merging so we can cut 2.2 RC3

**Pull request merged**
