### PR TITLE
Explain that state=present should be used with yum and url

### PR DESCRIPTION
**Pull request by Tahvok**
Document that url or file install should be used with 'state=present'.
Some get confused when using 'state=latest' and seeing it failing with no obvious reason.

### CODE REVIEW

**Comment by gregdek** [comment]
Tossing over to @abadger who is handling all yum PRs currently.

**Comment by gregdek** [comment]
Since yum is a very central module, we're not going to merging any yum PRs until after 2.0 is released. Thanks for your continued patience, @Tahvok.

**Comment by h-michael** [comment]
:+1:

**Comment by abadger** [comment]
Thanks @Tahvok !  Sorry 2.0 development took so long.  This is now merged to devel and should be in the 2.1.0 release.

**Pull request merged**
