### PR TITLE
adding Amazon RDS snapshot features

### PR DESCRIPTION
**Pull request by sassman**
this basically supports only 2 use cases:
- make sure a given snapshot is absent (delete)
- make sure a given snapshot is present based on another snapshot (copy)

### CODE REVIEW

**Comment by bcoca** [comment]
not sure if we want the new module as the rds one already supports some snapshot functionality

**Comment by sassman** [comment]
do you suggest to add the features (copy and delete snapshot) to rds module?

**Comment by bcoca** [comment]
no, sorry, the more I look at it the more sense it makes to deprecate the snapshotting features in rds

**Comment by sassman** [comment]
I totally agree. 
IMO an own command as an entry point for all the snapshoting features makes the most sense. 
Indeed it is somehow handy to work with a specific rds instance and just make a snapshot of it. But working with a own snapshot command would even feel more naturally after all.

Do you need any further input/help/contribution/refactoring to get this merged?

**Comment by juliedavila** [comment]
@sassman Sorry for the delay on getting back to you on this pull request. A cpl things:
1. Could you abstract away the function-related bits away from main into their own functions. Maybe `copy_snapshot` and `delete_snapshot` functions?
2. Would it be possible for you to add in the functionality to create a snapshot given a db instance name?
   -  Bonus points if you can add in a `max_snapshot_age` parameter which will skip the task should the snapshot be younger than the max age.
   - Also, if you add this, then perhaps add absent, present and _copy_ as state options.

Thoughts?

**Comment by sassman** [comment]
@defionscode no problem, thanks for the feedback.
1. absolutely!
2. that is a very nice idea, makes it also a bit more smart, as ansible used to be

will try a change on those and ping back

**Comment by gregdek** [comment]
Hi @sassman. Just checking in to see how these changes are coming.

**Comment by gregdek** [comment]
@sassman A friendly reminder: this pull request has been marked as needing your action, and it hasn't been updated in the last month. 

If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we'll keep it open pending your changes.

If we receive no indication from you within a week, we will close this pull request.

**Comment by gregdek** [comment]
Closing due to inactivity.

**Pull request closed without merging**
