### PR TITLE
Added link to Linode API for more information regarding distribution ids

### PR DESCRIPTION
**Pull request by r4j4h**
##### ISSUE TYPE
- Docs Pull Request
##### COMPONENT NAME

linode module
##### ANSIBLE VERSION

```
N/A
```
##### SUMMARY

A reader may or may not be familiar with how to choose an appropriate distribution id. Ideally I would be submitting a PR that provides such functionality and returns it in a variable but at least this is a start. :)

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @r4j4h for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@r4j4h A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@r4j4h Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by r4j4h** [comment]
Hi there, sorry, I do intend on fixing the url. If anyone knows offhand the correct syntax feel free to post it and it will expedite things.

**Comment by gregdek** [comment]
@r4j4h A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@r4j4h Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@r4j4h A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by r4j4h** [comment]
I think it failed on a CI hiccup

```
  git config user.name "ansible" 0s  
  git config user.email "ansible@ansible.com" 0s  
  if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then git rebase $TRAVIS_BRANCH; fi; 0s  
  pip install git+https://github.com/ansible/ansible.git@devel#egg=ansible 31s  
  pip install git+https://github.com/sivel/ansible-testing.git#egg=ansible_testing 2s  
  python2.4 -m compileall -fq -x 'cloud/' .
```

**Comment by r4j4h** [comment]
I don't know why such a simple docs PR keeps failing

**Comment by mattclay** [comment]
This PR failed to build because the branch is too old. The branch will need to be rebased to pass CI.

**Pull request closed without merging**
