### PR TITLE
refactor the eos_command module to use the CommandRunner

### LINKED ISSUE #3727: eos_command does not work with --check ansible-playbook option
**Yes**
##### ISSUE TYPE

**Bug Report**
##### COMPONENT NAME

eos_command
##### ANSIBLE VERSION

2.1
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

when i use eos_command for configuring arista devices or running commands like " write mem"  with the --check option  , what ever list of commands specified under eos_command still gets applied to the devices .  whereas --check documentation indicates the following

  -C, --check           don't make any changes; instead, try to predict some
                        of the changes that may occur

```
##### STEPS TO REPRODUCE
Sample playbook:

- name: Play to configure Vlans on arista devices
  connection: local
  gather_facts: no
  hosts: "{{  arista }}"
  tags: 
    - arista

  tasks:
     - name: Prechecks to verify vlan does not exist
       eos_command:
         commands:
           - show vlan {{vlan}} | json
         provider: "{{ cli }}"
       failed_when: "'not found in current VLAN' not in output.msg"
       register: output
     - debug: var=output       


     - name: Configure Vlans
       eos_command:
         commands:
           - enable 
           - configure terminal
           - vlan {{ vlan }}
           - name {{ vlan_desc }}
           - exit
           - exit
           - write memory
         provider: "{{ cli }}"

     - name: Postchecks to verify vlan exists
       eos_command:
         commands:
           - show vlan  {{vlan}} | json
         provider: "{{ cli }}"
       register: output
     - debug: var=output 

```
##### EXPECTED RESULTS

See problem description
##### ACTUAL RESULTS

See problem description

### PR DESCRIPTION
**Pull request by privateip**
- This adds support the CommandRunner to handle executing commands on
  the remote device.
- It also changes the waitfor argument to wait_for to remain compatible
  with other modules and adds an alias for waitfor.
- Restricts commands to show commands only when check mode is specified. (fixes #3727)

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @privateip for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gundalow** [comment]
So Travis is failing because of the following two errors:

```
6.98s$ ansible-validate-modules --exclude 'utilities/' .
============================================================================
./network/eos/eos_command.py
============================================================================
ERROR: version_added for new option (wait_for) should be 2.2. Currently 0.0
ERROR: Did not find "ansible.module_utils.basic" import
```

It is technically correct that `wait_for` is a new option in 2.2 as the initial module was added in 2.1

**Comment by privateip** [comment]
yeah the version_added makes sense ... this is the rule that is breaking network modules though

> ERROR: Did not find "ansible.module_utils.basic" import

Network modules do not directly import basic anymore

**Comment by gundalow** [comment]
All of the examples are missing `host:`, should that be added to the docs?

**Comment by gundalow** [comment]
I've hit retry on Travis now that ansible-validate-modules has been updated

**Pull request merged**
