### PR TITLE
Fixes #3256 - Update unmanaged cron jobs, rather than duplicating them

### LINKED ISSUE #3256: cron duplicates cron jobs if '#Ansible: ' comment isn't the start of the preceeding line
##### Issue Type:

- Bug Report
##### Plugin Name:

cron
##### Ansible Version:

```
ansible 1.9.4
  configured module search path = None
```
##### Ansible Configuration:

```
[defaults]
forks=0
inventory=./hosts
```
##### Environment:

```
$ python --version
Python 2.7.10
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.11.2
BuildVersion:   15C50
```
##### Summary:

If a cronjob exists but lacks a corresponding `#Ansible:` comment on the previous line, a duplicate entry will be added. This is issue manifests itself when converting an existing crontab over to ansible. If you have preexisting cronjobs, and you'd like to now manage them via ansible, you'd expect that adding an ansible task for a preexisting cronjob wouldn't do anything (except maybe add `#Ansible: cronjob-name` to the preceeding line).

Specifically, the cron.CronTab class has an attribute `self.ansible == "#Ansible: "` that is used in the method `cron.CronTab.find_job` to find cronjobs via their preceding comments. If the cronjob doesn't have a corresponding comment, it's invisible to the cron module.
##### Steps To Reproduce:
1. Manually add cronjob via crontab -e
   
   ```
   $ sudo crontab -l
   # DO NOT EDIT THIS FILE - edit the master and reinstall.
   # (/tmp/crontab6ASD42 installed on Tue Mar 15 18:40:15 2016)
   # (Cron version V5.0 -- $Id: crontab.c,v 1.12 2004/01/23 18:56:42 vixie Exp $)
   * * * * * /bin/true
   ```
2. Add cron task with identical job
   
   ```
   - name: add test cronjob
   cron: name="test" user=root job="/bin/true"
   ```
##### Expected Results:

I expect a single cronjob to be present

```
$ sudo crontab -l
# DO NOT EDIT THIS FILE - edit the master and reinstall.
# (/tmp/crontab8GGP41 installed on Tue Mar 15 18:42:05 2016)
# (Cron version V5.0 -- $Id: crontab.c,v 1.12 2004/01/23 18:56:42 vixie Exp $)
#Ansible: test
* * * * * /bin/true
```
##### Actual Results:

A second, identical cronjob has been added

```
$ sudo crontab -l
# DO NOT EDIT THIS FILE - edit the master and reinstall.
# (/tmp/crontab8GGP41 installed on Tue Mar 15 18:42:05 2016)
# (Cron version V5.0 -- $Id: crontab.c,v 1.12 2004/01/23 18:56:42 vixie Exp $)
* * * * * /bin/true
#Ansible: test
* * * * * /bin/true
```

### PR DESCRIPTION
**Pull request by EvanK**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

cron module
##### ANSIBLE VERSION

```
ansible 2.1.1.0
```
##### SUMMARY

Fixes #3256

Given an existing crontab in the remote, with the following jobs (all currently _unmanaged by ansible_):

```
# not to be modified by ansible
* * * * * /bin/true
# intended to be taken over and managed by ansible...
*/10 * * * * /bin/true
# also not to be modified by ansible
* * * * * /bin/false
```
### With `state=present`

Without a `name`:

``` diff
TASK [cron] ********************************************************************
changed: [33.33.33.10]
--- before: crontab for user "deploy"
+++ after: crontab for user "deploy"
@@ -4,3 +4,5 @@
 */10 * * * * /bin/true
 # this is also a job not to be modified by ansible
 * * * * * /bin/false
+#Ansible: None
+*/10 * * * * /bin/true
```

With a `name`:

``` diff
TASK [cron] ********************************************************************
changed: [33.33.33.10]
--- before: crontab for user "deploy"
+++ after: crontab for user "deploy"
@@ -4,3 +4,5 @@
 */10 * * * * /bin/true
 # this is also a job not to be modified by ansible
 * * * * * /bin/false
+#Ansible: managed job
+*/10 * * * * /bin/true
```
### With `state=absent`

Without a `name`:

``` diff
TASK [cron] ********************************************************************
ok: [33.33.33.10]
```

With a `name`:

``` diff
TASK [cron] ********************************************************************
ok: [33.33.33.10]
```
### With `state=present`

Without a `name`:

``` diff
TASK [cron] ********************************************************************
changed: [33.33.33.10]
--- before: crontab for user "deploy"
+++ after: crontab for user "deploy"
@@ -1,6 +1,7 @@
 # this is a job not to be modified by ansible
 * * * * * /bin/true
 # this is a job we intend to be taken over and managed by ansible...
+#Ansible: None
 */10 * * * * /bin/true
 # this is also a job not to be modified by ansible
 * * * * * /bin/false
```

With a `name`:

``` diff
TASK [cron] ********************************************************************
changed: [33.33.33.10]
--- before: crontab for user "deploy"
+++ after: crontab for user "deploy"
@@ -1,6 +1,7 @@
 # this is a job not to be modified by ansible
 * * * * * /bin/true
 # this is a job we intend to be taken over and managed by ansible...
+#Ansible: managed job
 */10 * * * * /bin/true
 # this is also a job not to be modified by ansible
 * * * * * /bin/false
```
### ~~With `state=absent`~~

Due to changes in #5151, unmanaged jobs won't be touched by `state=absent` -- which probably makes more sense anyway...

~~Without a `name`:~~

``` diff
TASK [cron] ********************************************************************
changed: [33.33.33.10]
--- before: crontab for user "deploy"
+++ after: crontab for user "deploy"
@@ -1,6 +1,5 @@
 # this is a job not to be modified by ansible
 * * * * * /bin/true
 # this is a job we intend to be taken over and managed by ansible...
-*/10 * * * * /bin/true
 # this is also a job not to be modified by ansible
 * * * * * /bin/false
```

~~With a `name`:~~

``` diff
TASK [cron] ********************************************************************
changed: [33.33.33.10]
--- before: crontab for user "deploy"
+++ after: crontab for user "deploy"
@@ -1,6 +1,5 @@
 # this is a job not to be modified by ansible
 * * * * * /bin/true
 # this is a job we intend to be taken over and managed by ansible...
-*/10 * * * * /bin/true
 # this is also a job not to be modified by ansible
 * * * * * /bin/false
```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks again to @EvanK. This module is going into community review.

We notice that you are one of the maintainers (@dsummersl, @EvanK) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by EvanK** [comment]
shipit

**Comment by gregdek** [comment]
Thanks @EvanK. Since you are one of the maintainers (@dsummersl, @EvanK) of this module and you commented with "shipit", we are marking this PR for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @EvanK for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by EvanK** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @EvanK. To the current maintainers, @dsummersl, @EvanK please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by EvanK** [comment]
shipit

**Comment by gregdek** [comment]
Thanks @EvanK. Since you are one of the maintainers (@dsummersl, @EvanK) of this module and you commented with "shipit", we are marking this PR for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by mscherer** [comment]
Sorry, can't merge due to conflict :/

**Comment by EvanK** [comment]
@mscherer Pulled and merged in latest upstream devel, but I'm not seeing any conflicts

**Comment by mscherer** [comment]
I try to do a rebase and merge, and it say "This branch cannot be rebased due to conflicts"

**Comment by EvanK** [comment]
That's doubly odd because Github doesn't appear to see any merge conflicts either.

I've just merged from upstream again, can you try the latest commit from this branch (`56d1eb7`)?

**Comment by EvanK** [comment]
@mscherer You know what, nevermind! I just tried to rebase this branch against `devel` at the cli, and found the problem...I'll push a fix shortly!

**Comment by EvanK** [comment]
Rebased against devel, and resolved the conflict

**Pull request merged**
