### PR TITLE
Convert the network subfolder to py3/py2.4 syntax

### PR DESCRIPTION
**Pull request by mscherer**
##### ISSUE TYPE
- Feature Pull Request

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @mscherer. To the current maintainers, @jpmens, @romeotheriault, @privateip please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by mscherer** [comment]
I didn't add that to .travis because this would have conflicted with others PR.

**Comment by abadger** [comment]
The changes to networking/basic look good here.  @privateip  & @Qalthos, should the networking modules here be ported to py2.4 compatible syntax (as this PR does) or to python-2.6+ syntax?

**Comment by privateip** [comment]
👍

**Comment by mscherer** [comment]
I pushed the .travis change, since all others PR were merged.

**Pull request merged**
