### PR TITLE
Basic authentication on win_get_url.ps1

### PR DESCRIPTION
**Pull request by xpicio**
Hello i did some test with module win_get_url and it seems is not work correctly with username and password. Hope this helps.

Bye Bye

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @xpicio for the PR!

@angstwad Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by jhawkesworth** [comment]
Not sure if we should be caching credentials as effectively we would be modifying the system state after the first run.  I suppose we should either Remove the credential from the cache on cleanup or not cache the credentials.

**Comment by gregdek** [comment]
@angstwad This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by robynbergeron** [comment]
@angstwad still waiting on your review.  Please comment with text 'shipit' or 'needs_revision' as appropriate. If we don't hear from you within 14 days, we will start to look for additional maintainers for this module.

**Comment by jhawkesworth** [comment]
I volunteer to be a maintainer of this module.

**Comment by jhawkesworth** [comment]
looking again I would say this needs_revision as caching the credentials does not make much sense given how modules work in ansible.
The change to use $webResponse instead of $response is good though.

**Comment by xpicio** [comment]
As suggested by @jhawkesworth i removed the snippet of code that saving credential in CredentialCache object

**Comment by nitzmahone** [comment]
all substantive changes have already been merged via other PRs, closing

**Comment by xpicio** [comment]
@nitzmahone pay attention there is a bug on the latest version that is not been fixed:

```
$webRequest.IfModifiedSince = ([System.IO.FileInfo]$dest).LastWriteTime
$webRequest.Method = "GET"
[System.Net.HttpWebResponse]$webResponse = $webRequest.GetResponse()

$stream = New-Object System.IO.StreamReader($response.GetResponseStream())
```

the `$response`variable has not been initialized. Check again my code, i fixed it.

**Comment by nitzmahone** [comment]
Ah ok, I see it now. It just looked like variable renames that were left.

**Comment by nitzmahone** [comment]
The formatting changes and multiple commits were causing issues- hope it's OK that I just pulled in the bugfix (see commit above).

Thanks!

**Pull request closed without merging**
