### PR TITLE
Use vpc_security_groups for rds2 in rds module

### LINKED ISSUE #1320: rds should use vpc_security_group_ids parameter when using boto.rds2
##### Issue Type:

Bug report
##### Ansible Version:

```
ansible 1.9.0.1
  configured module search path = None
```

```
python -c 'import boto; print boto.__version__'
2.38.0
```
##### Ansible Configuration:

```
[defaults]
remote_user=root
```
##### Environment:

OS X -> Arch Linux
##### Summary:

Using the `vpc_security_groups` field results in a backtrace. I believe it's as a result of boto.rds2 using changing the parameter name to `vpc_security_group_ids` ([rds](http://docs.pythonboto.org/en/latest/ref/rds.html#boto.rds.RDSConnection.create_dbinstance), [rds2](http://docs.pythonboto.org/en/latest/ref/rds2.html#boto.rds2.layer1.RDSConnection.create_db_instance)).
##### Steps To Reproduce:

Use the rds module with the `vpc_security_groups` field.
##### Expected Results:

Creating the RDS instance.
##### Actual Results:

```
failed: [localhost] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/Users/.../.ansible/tmp/ansible-tmp-1431542488.13-155094175069439/rds", line 2807, in <module>
    main()
  File "/Users/.../.ansible/tmp/ansible-tmp-1431542488.13-155094175069439/rds", line 1008, in main
    invocations[module.params.get('command')](module, conn)
  File "/Users/.../.ansible/tmp/ansible-tmp-1431542488.13-155094175069439/rds", line 652, in create_db_instance
    module.params.get('username'), module.params.get('password'), **params)
  File "/Users/.../.ansible/tmp/ansible-tmp-1431542488.13-155094175069439/rds", line 429, in create_db_instance
    db_engine, username, password, **params)['CreateDBInstanceResponse']['CreateDBInstanceResult']['DBInstance']
TypeError: create_db_instance() got an unexpected keyword argument 'vpc_security_groups'
```

### PR DESCRIPTION
**Pull request by nfirvine**
Fixes #1320

### CODE REVIEW

**Comment by bennojoy** [comment]
@nfirvine  could you please resolve the conflicts..  thanks

**Comment by gregdek** [comment]
@nfirvine Thanks for submitting this pull request. Please accept our apologies for taking so long to review it.

Unfortunately, due to this delay, it appears that the underlying code has changed, and this PR needs to be rebased. If you believe that this PR still applies, please rebase and we will then put it into our (new, faster) community review process as soon as possible.  Again, apologies for the delay and the extra work.

**Comment by gregdek** [comment]
A friendly reminder: this pull request has been marked as needing your action, and it hasn't been updated in the last month. 

If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we'll keep it open pending your changes.

If we receive no indication from you within a week, we will close this pull request.

**Comment by nfirvine** [comment]
I've lost interest, so I'm closing.

**Pull request closed without merging**
