### PR TITLE
Update vsphere_guest.py to include parameter for eagerly_scrub vmdisk

### PR DESCRIPTION
**Pull request by hmiller997**
##### ISSUE TYPE

- Feature Pull Request
##### COMPONENT NAME

ansible-modules-core/cloud/vmware/
##### ANSIBLE VERSION

```
ansible 2.1.0.0

```
##### SUMMARY

Need this change to allow for VMware disk to be Thick Provision Eager Zeroed.
new option         eagerly_scrub:
for parameter     vm_disk:
values                 yes or no

```

```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @hmiller997. To the current maintainers, @chrrrles, @rhoop please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by mattclay** [comment]
Tests on shippable failed because this PR branch was created before shippable was enabled. If you rebase the branch the tests will pass, although in this case the tests will just no-op since there are no tests for this module.

**Comment by kkr16** [comment]
Hi, I was about to submit a pull request for this, I did it differently, I set the type==eager instead of adding a new parameter. So we end up with three options, explicitly setting type=thin or type=eager (thick eager zero). anything else will go to thick lazy zero.

```
if type == "eager":
    disk_backing.set_element_eagerlyScrub("eager_zero")
elif type == "thin":
    disk_backing.set_element_thinProvisioned(1)
```

instead of 

```
 if type != "thick":
      disk_backing.set_element_thinProvisioned(1)
```

**Comment by rhoop** [comment]
Hi all. I am out of commission for the next week. I will get to all of these PR's by next Friday.

**Comment by hmiller997** [comment]
Implemented kkr16's change. 
Closing this pull request and opened:
 Update vsphere_guest.py to include parameter for eagerly_scrub vmdisk part 2. #5193 
because I deleted and recreated my repo fork.

**Pull request closed without merging**
