### PR TITLE
Update synopsis documentation of file copy module.

### PR DESCRIPTION
**Pull request by quorten**
##### ISSUE TYPE

 - Docs Pull Request

##### COMPONENT NAME

copy

##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = 
  configured module search path = Default w/o overrides
```

##### SUMMARY

Documentation update to synopsis and examples of copy module.

A feature was added to the copy module to for file copies between two different locations on a remote, but this change was described only in the options and not in the synopsis or examples.  It would be nice for readers quickly skimming the documentation to in fact see that copies between locations on the remote are also supported.

```

```

Now that remote-to-remote copies are supported in the file module,
the module documentation has been updated to indicate this in the
synopsis and examples to make the capability obvious for someone
skimming the documentation.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @quorten for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by quorten** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @quorten for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by jctanner** [comment]
@quorten I would prefer something like "copies a file from the local or remote machine to a location on the remote machine"

**Comment by quorten** [comment]
@jctanner, thanks for the recommendation, I think it's a better way to write the sentence.  I've updated the pull request with the recommended change.

**Comment by quorten** [comment]
Looking at the documentation for the copy module another time, it might also be nice for there to be an example that uses `remote_src`.  I've updated the pull request and added one example for this.

**Comment by gregdek** [comment]
Thanks @quorten for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by quorten** [comment]
ready_for_review

**Comment by quorten** [comment]
Sorry about that, `shippable` somehow got buggy and many of the tests timed out rather than passing.

**Comment by gregdek** [comment]
Thanks @quorten for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Review by dharmabumstead — APPROVED** [review]
Docs look good.

**Pull request closed without merging**
