### PR TITLE
Apply yum Security updates

### PR DESCRIPTION
**Pull request by dileep-p**

### CODE REVIEW

**Comment by dileep-p** [comment]
HI @bcoca , do I need to tag anyone for review this, or is it normal wait time ?

**Comment by bcoca** [comment]
so we talked this over in core and we think a state is a better approach

`yum: name=* state=secured` 

this also allows for specific updates

`yum: name=bash state=secured`

**Comment by bcoca** [comment]
others like `state=security` or `state=security_only` best

**Comment by klj613** [comment]
+1 - at the moment im using the shell module but i want to be able to trigger handlers only if something changed

i think using state is the best option as well

**Comment by parberge** [comment]
Maybe there should be something added about this won't "work" (the command will work, but it will never install any packages) with CentOS "out of the box" since CentOS isn't getting the Errata information which is needed for yum to successfully identify security patches.

**Comment by gregdek** [comment]
Thanks @dileep-p for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

**Comment by robynbergeron** [comment]
@dileep-p A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes.

**Comment by gregdek** [comment]
@dileep-p Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If we don't hear from you within another 14 days, we will close this pull request.

**Comment by gregdek** [comment]
Closing due to inaction.

**Pull request closed without merging**
