### PR TITLE
user: add expired state

### PR DESCRIPTION
**Pull request by billwanjohi**
(Ported from https://github.com/ansible/ansible/pull/6303)

It's very useful and routine to disable a *nix user.
I implemented expired instead of locked because this prevents any use of
the account, safer than just preventing password-based authentication.

I have tests [1], but since none of the suite came along with the core
modules, I'm unsure how to submit them. Discussed in #40.

[1] https://github.com/billwanjohi/ansible/blob/add_locked_state/test/integration/roles/test_user/tasks/main.yml

### CODE REVIEW

**Comment by bcoca** [comment]
I'm thinking a more flexible implementation should be expires="date string" (default None == never), which enables the creation of users with expiration dates (common when you have a contractor/consultant), expires=now would then be the particular case that you wanted to add.

making note that  'password_expires' and 'locked' are options that we should implement.

**Comment by billwanjohi** [comment]
That sounds reasonable. @bcoca are you speaking for the collective? i.e. if I reimplemented this, would it be considered for inclusion in some reasonable time period? You may have seen, I originally submitted this last March, made changes based on feedback, only to see it languish.

**Comment by bcoca** [comment]
I can only ask for patience, there are a lot of PRs for new features (good problem to have for an OSS project) and we tend to prioritize bugs. I know its frustrating, (up to a few months ago I was on the other side of this) but we have increased the resources and are making a big effort to go through the backlog.

**Comment by ahmgithubahm** [comment]
Hi all.  Looks like this feature has been implemented, in 1.9, but I am having trouble 'un-expiring' a user.  If I miss out 'expires:', Ansible makes no change to /etc/shadow, so the user stays expired.  If I include 'expires=', I get an error:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1441284323.66-108325559784408/user", line 3735, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1441284323.66-108325559784408/user", line 2035, in main
    supports_check_mode=True
  File "/root/.ansible/tmp/ansible-tmp-1441284323.66-108325559784408/user", line 2512, in **init**
    self._check_argument_types()
  File "/root/.ansible/tmp/ansible-tmp-1441284323.66-108325559784408/user", line 3189, in _check_argument_types
    self.params[k] = float(value)
ValueError: empty string for float()

Am I missing something?

ansible-1.9.2-1.el6.noarch on CentOS 6 from EPEL, target server also CentOS 6.

**Pull request merged**
