### PR TITLE
Replaces 'old' get_ec2_creds connection method with get_aws_connection_info

### PR DESCRIPTION
**Pull request by sclausson**
New connection method supports passing in a security_token for temporary credentials.

### CODE REVIEW

**Comment by gregdek** [comment]
@defionscode Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by gregdek** [comment]
(p.s. @defionscode can you also add your github ID to the authors string?)

**Comment by juliedavila** [comment]
+1
shipit

and yep I'll make a sep PR

**Comment by gregdek** [comment]
Thanks @sclausson for the PR and thanks @defionscode for the review.

cc: @ansible/core team for inclusion.

**Pull request merged**
