### PR TITLE
Adding do_module and additional rework for #4219

### PR DESCRIPTION
**Pull request by harneksidhu**
##### ISSUE TYPE
- New Module Pull Request
- Bugfix Pull Request
##### COMPONENT NAME
- cloud/digital_ocean/do_block_storage
- cloud/digital_ocean/do_droplet
- cloud/digital_ocean/do_tag
##### ANSIBLE VERSION

```
ansible 2.3.0
  config file =
  configured module search path = Default w/o overrides
```
##### SUMMARY

This PR is submitted because of the DigitalOcean rework #4219.
- digital_ocean is now deprecated and replaced with do_droplet which will remove the dependency from dopy
- digital_ocean_block_storage is now deprecated/renamed to do_block_storage. Some minor bug fixes and enhancements were also made
- digital_ocean_tag is now deprecated/renamed to do_tag 
#5275 should be merged in first before this PR as it is dependent on the ssh key functionality.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @harneksidhu for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by hellais** [comment]
Would it be possible to also expose the `api_baseurl` as an option to allow pointing to DigitalOcean API compatible backend with this module?

I am working with a cloud provider that implements an API compatible with DigitalOcean and it would be very useful to be able to use this ansible module when talking to it.

This is basically what I mean: https://github.com/hellais/ansible-modules-core/commit/bfa7cfc7c41c8bee8715f5706ddf54c22b0ac947.

Could you pull this commit into your PR?

**Comment by harneksidhu** [comment]
@alukovenko Should we merge in https://github.com/hellais/ansible-modules-core/commit/bfa7cfc7c41c8bee8715f5706ddf54c22b0ac947?

**Comment by alukovenko** [comment]
@harneksidhu looks good to me, let's go for it

**Comment by harneksidhu** [comment]
@hellais `api_basurl` would only work on this module. We are planning on making a `do_utils` file in the near future to bring in common functionality across all digital ocean modules. Send in the PR and we'll merge it in for now and then we will abstract it out so it will work for the others.

**Comment by pmarques** [comment]
@harneksidhu @hellais I don't see any problem in support this, I can also merge this into my PRs.

**Comment by gregdek** [comment]
Thanks @harneksidhu for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@harneksidhu A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
