### PR TITLE
fix for start/stop ec2 instances

### PR DESCRIPTION
**Pull request by majidaldo**
- state variable undefined
- instance_ids could be undefined
- starting/stopping an instance should have no business in changing instance attributes
- checking for instances in transition (what to do about them?)

for my purposes, this does the job. but let's see what the community thinks.
#1703

### CODE REVIEW

**Comment by bennojoy** [comment]
@majidaldo  The changes look good thanks, i am not exactly sure if we should remove the instance attributes code (source dest check) , do you find a better place where this could be added ?

**Comment by majidaldo** [comment]
@bennojoy i'm really not an ec2 expert nor an expert in this module. i just believe this start/stop method should keep things as is. i didn't find it straightforward to write my code as it had enough issues to deal with.

i assume you could change the attributes somewhere else in the code. plus you would have to know what is allowed by aws.

**Comment by bennojoy** [comment]
@majidaldo  i think the startstop function is not the best part but it would be most viable part to add this fucntionality as of now due to the complexity of the module, Also from the interface point of view it would be consistent as the user states that the instance state should be 'running' state with the attributes specified in the task.
If you could add back the attributes check part, i can test and merge this in.

**Comment by gregdek** [comment]
Closed due to inactivity.

**Pull request closed without merging**
