### PR TITLE
Fix permissions issue with 'cron' module

### PR DESCRIPTION
**Pull request by ghost**
I have a task like this in a playbook. The ansible_ssh_user is 'root'
for this host. 

```
- cron:
    hour: 00
    job: /home/backup/backup.sh
    name: baserock.org data backup
    user: backup
```

Running it gave me the following error:

```
TASK: [backup cron job, runs every day at midnight] ***************************
failed: [baserock-backup1] => {"failed": true}
msg: crontab: can't open '/tmp/crontabvVjoZe': Permission denied
crontab: user backup cannot read /tmp/crontabvVjoZe
```

The temporary file created by the 'cron' module is created with the
Python tempfile.mkstemp() function. This creates a file that is readable
only by 'root' (mode 600). The Busybox `crontab` program then checks if
the file is readable by the 'backup' user, and fails if it isn't. So we
need to make sure the file is world-readable before running `crontab`.

### CODE REVIEW

**Comment by gregdek** [comment]
@dsummersl please review; if you give +1, we will tag P1_reviewed for faster inclusion.

**Comment by gregdek** [comment]
@dsummersl a friendly ping to take a look at this PR?

**Comment by gregdek** [comment]
@dsummersl are you available to take a look at this PR?

**Comment by dsummersl** [comment]
I'll take a look.

**Comment by dsummersl** [comment]
Looks good - I wasn't sure whether `0o644` worked in python2 and python3, tested it, it does.

**Pull request merged**
