### PR TITLE
database/postgresql: added synchronous_commit parameter to postgresql user and db modules

### PR DESCRIPTION
**Pull request by caylorme**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME
- database/postgresql/postgresql_db
- database/postgresql/postgresql_user
##### ANSIBLE VERSION

devel
##### SUMMARY

Added a parameter to allow users to specify synchronous_commit for creation, alteration, or deletion of postgresql databases and users. This will allow users to set up databases and users before the replication nodes have been implemented.

A common use case of this is if a user wants to create the databases or user in the same module as installing postgres, but has not yet set up the replication nodes, the transaction will never take place

adding the ability to override synchronous_commit on the transactions

added synchronous_commit parameter to postgresql user and db modules

### CODE REVIEW

**Comment by caylorme** [comment]
Documentation on the asynchronous_commit setting can be found here:
http://www.postgresql.org/docs/current/static/runtime-config-wal.html

Documentation around asynchronous commits can be found here:
http://www.postgresql.org/docs/current/static/wal-async-commit.html

If anyone thinks that we should be setting this at the SESSION level instead of LOCAL, meaning we could set synchronous_commit in a separate transaction before sending the other queries, let me know.

More info on setting these parameters through queries, check here:
http://www.postgresql.org/docs/current/static/sql-set.html

**Comment by resmo** [comment]
Thanks @caylorme for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

**Comment by gregdek** [comment]
Thanks @caylorme for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@caylorme A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
