### PR TITLE
added 'disableexcludes' flag to yum module, to replicate the same yum flag

### PR DESCRIPTION
**Pull request by lil-cain**
Added a 'disableexcludes' flag, to ignore the excludes configured in yum.conf

### CODE REVIEW

**Comment by solomongifford** [comment]
I'd like this included as well.  Thanks lil-cain.

**Comment by spanneberg** [comment]
+1 for adding this

**Comment by jfchevrette** [comment]
I was just looking to do this. +1 !

**Comment by gregdek** [comment]
Hi @lil-cain. Thanks for submitting this pull request. Please accept our apologies for taking so long to review it.

Unfortunately, due to this delay, it appears that the underlying code has changed, and this PR needs to be rebased. If you believe that this PR still applies, please rebase and we will then put it into our (new, faster) community review process as soon as possible.  Again, apologies for the delay and the extra work.

**Comment by gregdek** [comment]
Actually moving this to core review despite its inactivity, because of (a) the popularity of the patch, and (b) the fact that we're already doing a lot of stuff in the yum module.

**Comment by gregdek** [comment]
This PR has been open a very long time and has been awaiting rebase for 9 months now, so I'm closing. @lil-cain feel free to open a new PR if you believe it still applies. Apologies.

**Pull request closed without merging**
