### PR TITLE
Add module for managing ELB load balancer policy.

### PR DESCRIPTION
**Pull request by herbygillot**
For use in creating and associating policies for session stickiness, SSL/public key configuration or proxy protocol support on EC2 ELBs.

### CODE REVIEW

**Comment by gregdek** [comment]
@herbygillot this patch fails Travis CI build. Please correct errors above and we'll take another look.

**Comment by sivel** [comment]
The error is:

```
Compiling ./cloud/amazon/ec2_elb_lb_policy.py ...
SyntaxError: ('invalid syntax', ('./cloud/amazon/ec2_elb_lb_policy.py', 171, 15, '            for category in self.LB_POLICY_CATEGORIES}\n'))
```

The reason is that statement does not work in python2.6 and requires python2.7.  The dict comprehension should be written out in a full for loop.

**Comment by gregdek** [comment]
@herbygillot A friendly reminder: this pull request has been marked as needing your action, and it hasn't been updated in the last month. 

If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we'll keep it open pending your changes.

If we receive no indication from you within a week, we will close this pull request.

**Comment by gregdek** [comment]
Closed due to inactivity.

**Pull request closed without merging**
