### PR TITLE
Digitalocean tags (replaces #4209)

### LINKED ISSUE #4117: digitalocean tag support
##### ISSUE TYPE
- Feature Idea
##### COMPONENT NAME

digital_ocean
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /Users/vivo/workspaces/me/ansible-digitalocean/ansible.cfg
  configured module search path = ['/Users/vivo/workspaces/me/ansible-modules-core']
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

DigitalOcean now supports tagging of Droplets.
Ansible should offer support for using tags

E.g. to ensure that a tag exists:

```
  digital_ocean: >
    state=present
    command=tag
    name="foo"
    api_token="{{ lookup('env','DO_API_TOKEN') }}"
```

I am already working on adding the support. Just wanted to create an issue to avoid duplication of effort

### PR DESCRIPTION
**Pull request by kontrafiktion**
##### ISSUE TYPE
- New Module Pull Request
##### COMPONENT NAME

cloud/digitalocean
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file =
  configured module search path = Default w/o overrides
```
##### SUMMARY

[Fixes #4117] [Replaces #4209] Add tag support to DigitalOcean module. 
uses ansible.module_utils.urls library instead of dopy.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @kontrafiktion for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by zyegfryed** [comment]
Looks goo for me. `ship_it`

**Comment by timka** [comment]
LGTM. `ship_it`

**Comment by kontrafiktion** [comment]
@gregdek "ship_it" or "shipit"?

**Comment by gundalow** [comment]
@zyegfryed @timka It's ..., you've votes haven't been counted (...redacted because it broke the bot)

**Comment by gregdek** [comment]
Thanks again to @kontrafiktion for this PR, and thanks @ansible/core for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gundalow** [comment]
Merged, thanks!

**Pull request merged**
