### PR TITLE
Add support for selinux user when adding a new user

### PR DESCRIPTION
**Pull request by badpass**
useradd modification, from man:
-Z, --selinux-user SEUSER
  The SELinux user for the user's login. The default is to leave this field blank, which causes the
  system to select the default SELinux user.

Add the param "seuser" to set the seuser-name when adding a new user for a system with support for selinux.

### CODE REVIEW

**Comment by bcoca** [comment]
i would extend the description ' on selinux enabled systems'

**Comment by badpass** [comment]
good point, I change the commit message

**Comment by pwnall** [comment]
@badpass I think @bcoca was referring to the user-visible documentation here
https://github.com/ansible/ansible-modules-core/pull/1941/files#diff-364488963ab3238692762924e55c4991R55

Commenting because this looks useful for me :+1:

**Comment by badpass** [comment]
@pwnall  and @bcoca I changed the user-visible documentation.

**Comment by gregdek** [comment]
Thanks @badpass. @sfromm please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by badpass** [comment]
shipit

**Pull request merged**
