### PR TITLE
do not inspect absent containers

### PR DESCRIPTION
**Pull request by jarmoni**
Solves issue #1863

### CODE REVIEW

**Comment by gregdek** [comment]
@cove @joshuaconner @softzilla @smashwilson Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by smashwilson** [comment]
It looks like #2093 solves this one along with a few other issues. I gave that one the go-ahead, so hopefully this'll be fixed soon.

**Comment by zentavr** [comment]
I wonder when this request will be satisfied?

**Comment by abadger** [comment]
Okay, #2093 has been merged so this should now be fixed in the devel branch.  Sorry for the length of time this took to get an fix applied for.

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Pull request closed without merging**
