### PR TITLE
fix errant module reference in eip module

### PR DESCRIPTION
**Pull request by snorecone**
This appears to be a copy/paste error, but "module" is undefined in this scope, and boto exceptions should just be caught in main().

### CODE REVIEW

**Comment by robynbergeron** [comment]
Hi @snorecone -- thanks for this PR. 

@lorin @rickmendes -- Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by ghost** [comment]
Agreed exceptions should be caught in main(). Code looks cleaner now. shipit

**Comment by gregdek** [comment]
Thanks @snorecone for the PR, and thanks @rickmendes for the review. Marking for potential inclusion.

**Comment by bcoca** [comment]
I agree that the current error thrown is not that useful, but it is preferred to have a more local error explaining the actual action that caused it. `'Error while searching for a device: %s ' % str(e)`

**Comment by gregdek** [comment]
@snorecone A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes.

**Comment by robynbergeron** [comment]
@snorecone Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If we don't hear from you within another 14 days, we will close this pull request.

**Comment by gregdek** [comment]
Closing due to contributor inaction.

**Pull request closed without merging**
