### PR TITLE
ec2_metric_alarm.py - added actions_enabled option (enable/disable actions)

### PR DESCRIPTION
**Pull request by Constantin07**
##### Issue Type:
- Feature Pull Request
##### Summary:

This PR adds "actions_enabled" option which additionally allows to enable or disable all actions for CloudWatch alarm.
If option is not specified it behaves as the old version so it doesn't brake compatibility.
The output format hasn't changed.
The "changed" output status also reflects when only this option is changed.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @Constantin07 for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

**Comment by Constantin07** [comment]
Hi Guys,

Any updates?

**Comment by gregdek** [comment]
@Constantin007 not at present, because there are no community maintainers for this module.

If you would be willing to review all subsequent PRs for this module, we could make you the community maintainer. Would you be interested? You would then be able to give a "shipit" to this PR, which would then move it directly to final review.

**Comment by gregdek** [comment]
Thanks @Constantin07 for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@Constantin07 A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by Constantin07** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @Constantin07 for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
