### PR TITLE
Fixes #1509

### LINKED ISSUE #1509: git module: always returns status changed
**Issue Type:**

Bug report

**Ansible Version:**

1.9.1

**Environment:**

OS X 10.3 provisioning Ubuntu 14.04

**Summary:**

git module always returns status changed, even if there was no changes at all.

The repo is cloned into `/opt`, which requires root permissions, however the repo itself cannot be cloned by the root user, so is cloned to `/tmp`, then moved into `/opt`. There's a second job to pull future updates as the `foo` user when the repo already exists.

```
- name: Check if scripts repository is already installed.
  stat: "path=/opt/scripts"
  register: scripts_repo

- name: Clone the scripts repository.
  git:
    repo: ssh://git@repo.example.com:/example.com/server-scripts.git
    dest: /tmp/scripts
    accept_hostkey: true
  sudo: yes
  sudo_user: foo
  when: not scripts_repo.stat.exists

- name: Move the scripts repo.
  command: mv /tmp/scripts /opt/scripts
  sudo: yes
  when: not scripts_repo.stat.exists

- name: Ensure scripts is up to date (when not cloning).
  git:
    repo: ssh://git@repo.example.com:/example.com/server-scripts.git
    dest: /opt/scripts
    accept_hostkey: true
  sudo: yes
  sudo_user: foo
  when: scripts_repo.stat.exists
  register: scripts_update 

- debug: var=scripts_update 
```

Output from task runner indicated that the before and after commit refs are the same, however changed is `true`:

```
TASK: [Check if scripts repository is already installed.] *********************
ok: [192.168.33.10]

TASK: [Clone the scripts repository.] *****************************************
skipping: [192.168.33.10]

TASK: [Move the scripts repo.] ************************************************
skipping: [192.168.33.10]

TASK: [Ensure scripts is up to date (when not cloning).] **********************
changed: [192.168.33.10]

TASK: [debug var=scripts_update] **********************************************
ok: [192.168.33.10] => {
    "var": {
        "scripts_update": {
            "after": "a8f34d434fcc0a1356aa4d8dda1eb1112bbff105",
            "before": "a8f34d434fcc0a1356aa4d8dda1eb1112bbff105",
            "changed": true,
            "invocation": {
                "module_args": "",
                "module_name": "git"
            }
        }
    }
}
```

I've found a [similar issue from 2014](https://github.com/ansible/ansible/issues/6526), which was caused by an unclean repository, however in this case the repo itself appears to be clean:

```
/opt/scripts $ sudo -u foo git status
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean
```

**Steps To Reproduce:**

Unclear. We're doing the same round the houses approach for another repo, and that is reporting `changed` correctly.

**Expected Results:**

`scripts_update.changed` should be `false` when the before and after commit refs are the same.

**Actual Results:**

`scripts_update.changed` is `true`.

### PR DESCRIPTION
**Pull request by w1r0x**
Remove updated submodules (they always in detached head state) from local modifications list
Always update submodules when track_submodules=yes is used. See ansible #12309
Get submodule branch from .gitmodules. Was always 'master' hardcoded

See #1509

### CODE REVIEW

**Comment by gregdek** [comment]
Putting into core review, since this is a request to pull a PR into stable.

**Comment by w1r0x** [comment]
@gregdek Can you say should I port it to 'devel' branch and make pull request there?

**Comment by gregdek** [comment]
Thanks @w1r0x. All backport requests must be reviewed by the core team, and this can take time. We appreciate your patience.

**Comment by w1r0x** [comment]
Thank you @gregdek. I already create backport pull request #2874 .So you can close this one.

**Comment by jctanner** [comment]
@w1r0x thanks, closing per your request.

**Pull request closed without merging**
