### PR TITLE
Fix an issue where by a call to ec2.get_image wasn't wrapped in a try…

### PR DESCRIPTION
**Pull request by jjshoe**
…/except, and would occasionally throw an exception in the wild. Also greatly simplifies two of the ugliest known loops to man down into a single loop.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @jjshoe. @scicoin-project please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by jjshoe** [comment]
@scicoin-project - get a chance to review yet?

**Comment by jjshoe** [comment]
@gregdek @scicoin-project

PR is two months old, update?

**Comment by jjshoe** [comment]
@gregdek @scicoin-project - Any update?
@bcoca - What's the process when no community review is forthcoming?

**Comment by gregdek** [comment]
@jjshoe you are now an owner of this module, so when you want to give it a shipit, let us know. :)

**Comment by jjshoe** [comment]
shipit

**Comment by gregdek** [comment]
Thanks @jjshoe. Since you are one of the maintainers (@jjshoe) of this module and you commented with "shipit", we are marking this PR for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request merged**
