### PR TITLE
Ec2 module cleanup

### PR DESCRIPTION
**Pull request by zimbatm**
A couple of changes before submitting something larger. No functionality is changed here.

### CODE REVIEW

**Comment by bcoca** [comment]
please note that we don't normally take style change requests as they break attribution, this request has a bit more than that so we are keeping it for review.

**Comment by zimbatm** [comment]
any ETA on the review ?

**Comment by zimbatm** [comment]
the interesting bit of this PR got integrated in another commit, feel free to close

**Comment by bennojoy** [comment]
Closing are per request

**Pull request closed without merging**
