### PR TITLE
Iam trust policy

### PR DESCRIPTION
**Pull request by nitzmahone**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

iam.py
##### SUMMARY

Update of https://github.com/ansible/ansible-modules-core/pull/3264

cc @MichaelBaydoun

### CODE REVIEW

**Comment by bcoca** [comment]
dont use a merge, breaks travis and can create issues once this is merged into the tree again

**Comment by nitzmahone** [comment]
@bcoca yeah good call- I was initially just going to post this as a test branch; redone with cherry-picks

**Comment by gregdek** [comment]
Thanks @nitzmahone for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by MichaelBaydoun** [comment]
tested_working, works great, worksforme, shipit

**Comment by esc** [comment]
Is this released yet?

**Comment by MichaelBaydoun** [comment]
It's merged into devel, so should be included in the next release.

**Comment by nitzmahone** [comment]
@MichaelBaydoun way to cover all the bot bases there... ;)

**Pull request merged**
