### PR TITLE
New: Return ARN from iam_cert so that it can be used later on

### PR DESCRIPTION
**Pull request by mheap**
When using `ec2_lb` with SSL, you need to specify the ARN name for a certificate. This PR exposes this value in the return data so that it can be registered for later use

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @mheap. @defionscode please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
@defionscode This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by robynbergeron** [comment]
@defionscode still waiting on your review.  Please comment with text 'shipit' or 'needs_revision' as appropriate. If we don't hear from you within 14 days, we will start to look for additional maintainers for this module.

**Comment by gregdek** [comment]
Moving this module to @ansible/core review. @mheap thanks for your PR and your patience.

**Comment by gregdek** [comment]
Thanks @mheap for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

**Comment by defionscode** [comment]
shipit

**Comment by juliedavila** [comment]
dupe of #2219 I'd like to give preference to the first submitter

**Comment by mheap** [comment]
#2219 Looks like a more complete solution, so go with that one

**Comment by alikins** [comment]
https://github.com/ansible/ansible-modules-core/issues/3183  requests this.

**Comment by alikins** [comment]
https://github.com/ansible/ansible-modules-core/pull/2843  too for that matter.

**Pull request closed without merging**
