### PR TITLE
Git: report changed when needed in check mode

### PR DESCRIPTION
**Pull request by rcutmore**
##### ISSUE TYPE

- Bugfix Pull Request
##### COMPONENT NAME

Git
##### ANSIBLE VERSION

```
ansible 2.3.0 (git-integration-tests add3fbb61f) last updated 2016/10/22 19:48:22 (GMT -400)
  lib/ansible/modules/core: (git-check-mode a9765b0ecc) last updated 2016/10/24 18:03:52 (GMT -400)
  lib/ansible/modules/extras: (devel 5b7e052d06) last updated 2016/10/22 19:55:36 (GMT -400)
  config file = 
  configured module search path = Default w/o overrides
```
##### SUMMARY

Fixes a bug where a task is reported as not changed in check mode despite the remote URL changing.

Command:

```
- name: clone repo with new url in check mode
  git: repo="https://github.com/ansible-test-robinro/git-test-old" dest="./test"
  check_mode: True
```

Before:

```
ok: [testhost] => {"after": "ee165e681ddd3a06cb2f42e269f2dad761b3157a", "before": "ee165e681ddd3a06cb2f42e269f2dad761b3157a", "changed": false, "remote_url_changed": true, "warnings": []}
```

After:

```
changed: [testhost] => {"after": "ee165e681ddd3a06cb2f42e269f2dad761b3157a", "before": "ee165e681ddd3a06cb2f42e269f2dad761b3157a", "changed": true, "remote_url_changed": true, "warnings": []}
```

### CODE REVIEW

**Comment by rcutmore** [comment]
@jctanner @robinro This is to fix the issue mentioned [here](https://github.com/ansible/ansible/pull/16893#issuecomment-255603789) so that the new tests in that PR will pass again. Let me know if there are any issues.

**Comment by gregdek** [comment]
Thanks @rcutmore for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by robinro** [comment]
LGTM
ship_it

**Comment by gregdek** [comment]
@rcutmore A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by rcutmore** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @rcutmore for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Review by robinro — APPROVED** [review]
LGTM

**Pull request closed without merging**
