### PR TITLE
synchronize: use sshpass to avoid interactive passwords

### PR DESCRIPTION
**Pull request by bryceliu**
Use sshpass to avoid asking for passwords interactively.

``` yaml
- name: upgrade database
  synchronize: src={{ database.src }} dest={{ database.dest }} archive=yes checksum=yes
      compress=yes copy_links=no links=yes mode=push group=no owner=no
      perms=yes recursive=yes times=no sshpass={{ ansible_ssh_pass }}
```

### CODE REVIEW

**Comment by gregdek** [comment]
@hellofreedom Thanks for submitting this pull request. Unfortunately, it appears that the underlying code has changed since your submission, and this PR now needs to be rebased. 

If you believe that this PR still applies, please rebase and we will put it into our community review process as soon as possible. 

Once you have rebased this PR, please add a comment with the text "ready_for_review" and we will continue with the review process.  Thanks!

**Comment by bryceliu** [comment]
ready_for_review

**Comment by gregdek** [comment]
@hellofreedom did you mean to close this PR?

**Comment by bryceliu** [comment]
@gregdek I rebased this PR by adding a new one #2053, because I didn't know how to rebase a PR  against the current one. I'm sorry if it confused you.

**Comment by gregdek** [comment]
No worries -- thanks!

**Pull request closed without merging**
