### PR TITLE
ec2 traceback

### PR DESCRIPTION
**Pull request by wyyang**
##### Summary:

There is a bug in the ec2 module about boto profiles that's rather rare to occur. When someone (me) has multiple vpcs under different accounts stored in different boto profiles, trying to create a new ec2 instance in a vpc with subnet specified, with a credential stored in a boto profile that's different from the default one, ansible will use the wrong default credential to pull the subnet list, which will result in subnet not found since it's querying the wrong vpc using the wrong credentials.

I already have a fix with touches 2 lines in modules/core/cloud/amazon/ec2.py and 1 line module_utils/ec2.py, which I would like to check in.
##### Steps To Reproduce:
1. Create 2 VPCs and subnets, with different VPC ids and subnet ids using two AWS accounts.
2. Create one .boto profiles for each set of vpc/aws accounts.
3. Turn debug level to 2 in the .boto file.
4. Write a simple playbook to create an instance in the VPC with subnet defined, using the .boto profile that's different than the default profile.
5. Have exact_count defined, instead of count defined. Remember to define count_tag.
6. To reduce other possible aws credentials getting into the way, make sure you have no AWS access/security key environment variables defined, and rename you ~/.aws to ~/.aws1.
7. Run the playbook in verbose mode.
##### Expected Results:

It will fail. With boto debug level set to high, you will see ansible made 2 AWS calls. The first one is successful, that's when it try to get the count of the instances with the tag defined in count_tag. The second one fails with 400 Bad Request error, showing the subnet ID does not exist. 
##### Actual Results:

I masked out my actual AWS credentials, IDs for security reasons.

```
TASK: [phase1_ec2 | ec2 ] ***************************************************** 
<localhost> REMOTE_MODULE ec2 image=ami-xxxxxxxx group_id=sg-xxxxxxxx region=us-east-1 keypair=xxxx-keypair instance_type=m3.medium vpc_subnet_id=subnet-xxxxxxxx profile=tango
<localhost> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1433463240.95-278778469275873 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1433463240.95-278778469275873 && echo $HOME/.ansible/tmp/ansible-tmp-1433463240.95-278778469275873']
<localhost> PUT /tmp/tmphXyiSN TO /home/wyang/.ansible/tmp/ansible-tmp-1433463240.95-278778469275873/ec2
<localhost> EXEC ['/bin/sh', '-c', u'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /home/wyang/.ansible/tmp/ansible-tmp-1433463240.95-278778469275873/ec2; rm -rf /home/wyang/.ansible/tmp/ansible-tmp-1433463240.95-278778469275873/ >/dev/null 2>&1']
failed: [localhost] => {"failed": true, "parsed": false}


send: 'POST / HTTP/1.1\r\nAccept-Encoding: identity\r\nContent-Length: 157\r\nUser-Agent: Boto/2.38.0 Python/2.6.6 Linux/2.6.32-431.29.2.el6.x86_64\r\nHost: ec2.us-east-1.amazonaws.com\r\nX-Amz-Date: 20150605T001401Z\r\nContent-Type: application/x-www-form-urlencoded; charset=UTF-8\r\nAuthorization: AWS4-HMAC-SHA256 Credential=access_key2/20150605/us-east-1/ec2/aws4_request,SignedHeaders=host;x-amz-date,Signature=signature_2\r\n\r\n'
send: 'Action=DescribeInstances&Filter.1.Name=instance-state-name&Filter.1.Value.1=running&Filter.2.Name=tag%3AName&Filter.2.Value.1=us0602acl099&Version=2014-10-01'
reply: 'HTTP/1.1 200 OK\r\n'
header: Content-Type: text/xml;charset=UTF-8
header: Transfer-Encoding: chunked
header: Vary: Accept-Encoding
header: Date: Fri, 05 Jun 2015 00:14:00 GMT
header: Server: AmazonEC2


send: 'GET /?Action=DescribeSubnets&SubnetId.1=subnet-xxxxxxxx&Version=2014-10-01 HTTP/1.1\r\nAccept-Encoding: identity\r\nContent-Length: 0\r\nHost: ec2.us-east-1.amazonaws.com\r\nAuthorization: AWS4-HMAC-SHA256 Credential=access_key1/20150605/us-east-1/ec2/aws4_request,SignedHeaders=host;x-amz-date,Signature=signature_1\r\nX-Amz-Date: 20150605T001401Z\r\nUser-Agent: Boto/2.38.0 Python/2.6.6 Linux/2.6.32-431.29.2.el6.x86_64\r\n\r\n'
reply: 'HTTP/1.1 400 Bad Request\r\n'
header: Transfer-Encoding: chunked
header: Date: Fri, 05 Jun 2015 00:14:00 GMT
header: Cneonction: close
header: Server: AmazonEC2
Traceback (most recent call last):
  File "/home/wyang/.ansible/tmp/ansible-tmp-1433463240.95-278778469275873/ec2", line 3054, in <module>
    main()
  File "/home/wyang/.ansible/tmp/ansible-tmp-1433463240.95-278778469275873/ec2", line 1248, in main
    (tagged_instances, instance_dict_array, new_instance_ids, changed) = enforce_count(module, ec2, vpc)
  File "/home/wyang/.ansible/tmp/ansible-tmp-1433463240.95-278778469275873/ec2", line 707, in enforce_count
    = create_instances(module, ec2, vpc, override_count=to_create)
  File "/home/wyang/.ansible/tmp/ansible-tmp-1433463240.95-278778469275873/ec2", line 789, in create_instances
    vpc_id = vpc.get_all_subnets(subnet_ids=[vpc_subnet_id])[0].vpc_id
  File "/usr/lib/python2.6/site-packages/boto-2.38.0-py2.6.egg/boto/vpc/__init__.py", line 1153, in get_all_subnets
    return self.get_list('DescribeSubnets', params, [('item', Subnet)])
  File "/usr/lib/python2.6/site-packages/boto-2.38.0-py2.6.egg/boto/connection.py", line 1186, in get_list
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidSubnetID.NotFound</Code><Message>The subnet ID 'subnet-a8c429c5' does not exist</Message></Error></Errors><RequestID>514ac442-00c3-4533-80e0-9df9f3734bd6</RequestID></Response>


FATAL: all hosts have already failed -- aborting
```

### CODE REVIEW

**Comment by bcoca** [comment]
I'm not sure what you are trying to do with this PR but this won't merge

**Comment by wyyang** [comment]
Shall I pull against the development branch? I could not run it either in python 2.6 or python 2.7.

[23:14 wyang@us0101ado019 ecommerce]$ ansible-playbook -vvvv --extra-vars "service=cl" --vault-password-file ~/.vault_pass.txt deploy-asg.yml 
Traceback (most recent call last):
  File "/opt/rh/python27/root/usr/bin/ansible-playbook", line 5, in <module>
    pkg_resources.run_script('ansible==2.0.0', 'ansible-playbook')
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/pkg_resources.py", line 540, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/pkg_resources.py", line 1455, in run_script
    execfile(script_filename, namespace, namespace)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/ansible-2.0.0-py2.7.egg/EGG-INFO/scripts/ansible-playbook", line 66, in <module>
    sys.exit(cli.run())
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/ansible-2.0.0-py2.7.egg/ansible/cli/playbook.py", line 160, in run
    results = pbex.run()
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/ansible-2.0.0-py2.7.egg/ansible/executor/playbook_executor.py", line 68, in run
    pb = Playbook.load(playbook_path, variable_manager=self._variable_manager, loader=self._loader)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/ansible-2.0.0-py2.7.egg/ansible/playbook/__init__.py", line 47, in load
    pb._load_playbook_data(file_name=file_name, variable_manager=variable_manager)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/ansible-2.0.0-py2.7.egg/ansible/playbook/__init__.py", line 78, in _load_playbook_data
    entry_obj = Play.load(entry, variable_manager=variable_manager, loader=self._loader)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/ansible-2.0.0-py2.7.egg/ansible/playbook/play.py", line 98, in load
    return p.load_data(data, variable_manager=variable_manager, loader=loader)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/ansible-2.0.0-py2.7.egg/ansible/playbook/base.py", line 175, in load_data
    self._attributes[name] = method(name, ds[name])
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/ansible-2.0.0-py2.7.egg/ansible/playbook/play.py", line 151, in _load_tasks
    return load_list_of_blocks(ds=ds, play=self, variable_manager=self._variable_manager, loader=self._loader)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/ansible-2.0.0-py2.7.egg/ansible/playbook/helpers.py", line 39, in load_list_of_blocks
    assert ds is None or isinstance(ds, list), 'block has bad type: %s' % type(ds)
AssertionError: block has bad type: <class 'ansible.parsing.yaml.objects.AnsibleMapping'>

Thanks

-- 
Weiyi Yang

On June 5, 2015 at 6:55:47 PM, Brian Coca (notifications@github.com) wrote:

I'm not sure what you are trying to do with this PR but this won't merge

**Comment by sivel** [comment]
Yes, PRs should be made against devel.  Regardless your PR seemed messed up since it had a lot of extra commits included.

The reason for that error is that your playbook is improperly formatted.  A section requiring a list, was instead provided as a mapping/dict.

**Comment by bcoca** [comment]
still that should be a error and not a traceback, so it is a bug

**Comment by wyyang** [comment]
My playbook worked fine against 1.9.1. Same playbook but run against Dev it comes out with failures.

Weiyi

**Comment by gregdek** [comment]
@wyyang A friendly reminder: this pull request has been marked as needing your action, and it hasn't been updated in the last month. 

If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we'll keep it open pending your changes.

If we receive no indication from you within a week, we will close this pull request.

**Pull request closed without merging**
