### PR TITLE
Add DigitalOcean API v2 support for SSH keys and Domains management

### PR DESCRIPTION
**Pull request by zyegfryed**
DigitalOcean API v2 has been added for Droplet management but is still lacking for SSH key and Domain management. This PR solves it.

### CODE REVIEW

**Comment by gregdek** [comment]
@mgregson Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please give it a +1; at that point, we will add the “priority_reviewed” flag to this PR, which will move it to the top of our queue for potential inclusion.

**Comment by bryan-ash** [comment]
+1 I believe this PR conforms to the guidelines.

There is a problem in `digital_ocean_domain.py`, in that the v2 API uses domain name instead of id when fetching record. I have fixed in 7c4b22242bbdf97982e49f237749112596d3d332

**Comment by mgregson** [comment]
Looks reasonable. :+1:

**Comment by robynbergeron** [comment]
Just leaving a friendly note here that the digital ocean V1 API has been deprecated, and is being shut down on November 9. https://developers.digitalocean.com/documentation/v1/ Not sure if this is addressed with the above PR, but looks like maybe not.

@mgregson -- is your thumbs-up to the PR from @zyegfryed? or the edit from @bryan-ash (which would need a PR)?

**Comment by ianheggie** [comment]
Note my pull request #2446 fixes destroying domains and it includes PR from @bryan-ash (fixes add domains), which includes PR from @zyegfryed (initial changes). I have tested it in my own deployment scripts for creating a droplet, registering a domain and then destroying the droplet and associated domain.

**Comment by gregdek** [comment]
Thanks @zyegfryed for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

**Comment by robynbergeron** [comment]
@zyegfryed A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes.

**Comment by zyegfryed** [comment]
@robynbergeron Sorry for the late answer but I was quite busy lately. Gonna try to rebase it in the coming week. Cheers.

**Comment by zyegfryed** [comment]
@gregdek The PR is rebased and passing checks successfully, it's 'ready_for_review'.

**Comment by gregdek** [comment]
Thanks @zyegfryed. @mgregson please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
@mgregson This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
Thanks @zyegfryed for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

**Comment by gregdek** [comment]
@mgregson still waiting on your review.  Please comment with text 'shipit' or 'needs_revision' as appropriate. If we don't hear from you within 14 days, we will start to look for additional maintainers for this module.

**Comment by zyegfryed** [comment]
@gregdek The PR is rebased and passing checks successfully, it's 'ready_for_review'.

**Comment by gregdek** [comment]
Thanks @zyegfryed. @mgregson please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
Thanks @zyegfryed. @mgregson please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
@mgregson are you still available to review this PR? It's seen some changes since your last review; want to make sure they're still acceptable.

**Comment by gregdek** [comment]
Thanks @zyegfryed for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by zyegfryed** [comment]
@gregdek The PR is rebased and passing checks successfully, it's 'ready_for_review'.

**Comment by gregdek** [comment]
Thanks @zyegfryed. To the current maintainers, @mgregson please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by alukovenko** [comment]
@zyegfryed there is a minor merging conflict; if you could fix it - I will review immediately.

Followup: it would also make sense to check for the latest version of dopy (0.3.7) because of https://github.com/ansible/ansible-modules-core/issues/3899

**Comment by gregdek** [comment]
Thanks @zyegfryed for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by zyegfryed** [comment]
@alukovenko Resolved the conflict. Should be merge-able again. Thanks.

**Comment by alukovenko** [comment]
@zyegfryed Thanks! Would it also make sense to change requirements on dopy version to the latest version of dopy (0.3.7) because of https://github.com/ansible/ansible-modules-core/issues/3899 ?

**Comment by zyegfryed** [comment]
@alukovenko AFAIK the two are unrelated and as this time of writing there's no requirement on dopy version on any DigitalOcean module. However, if you want me to add it, tell and I'll do it.

**Comment by alukovenko** [comment]
@zyegfryed I agree, not connected. Will process #3899 as a different issue.

shipit

**Comment by gregdek** [comment]
Thanks again to @zyegfryed for this PR, and thanks @mgregson, @alukovenko for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @zyegfryed for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@zyegfryed A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@zyegfryed Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by zyegfryed** [comment]
ready_for_review

**Pull request closed without merging**
