### PR TITLE
cloudformation: add parameter for stack policy during update

### PR DESCRIPTION
**Pull request by eliah-hecht-zocdoc**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

cloudformation
##### ANSIBLE VERSION

```
ansible 2.0.2.0
  config file =
  configured module search path = Default w/o overrides
```
##### SUMMARY

Add `stack_policy_on_update` parameter to the CloudFormation module. This is used for temporarily overriding the stack policy.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @eliah-hecht-zocdoc. To the current maintainers, @jsmartin please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by jsmartin** [comment]
shipit

**Comment by jsmartin** [comment]
@eliah-hecht-zocdoc Please add some docstrings for the new feature, then we can ship it.

**Comment by eliah-hecht-zocdoc** [comment]
OK, will do. What should I put for `version_added` in the docstring?

**Comment by jsmartin** [comment]
"2.2" at this point I believe.

**Comment by eliah-hecht-zocdoc** [comment]
Docstrings added

**Comment by jsmartin** [comment]
shipit

**Comment by gregdek** [comment]
Thanks again to @eliah-hecht-zocdoc for this PR, and thanks @jsmartin for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @eliah-hecht-zocdoc for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@eliah-hecht-zocdoc A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@eliah-hecht-zocdoc Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by chris-smith-zocdoc** [comment]
I've merged devel back into this branch and resolved the conflicts. ready_for_review

**Pull request closed without merging**
