### PR TITLE
[git] faster when you use a specific sha as version

### PR DESCRIPTION
**Pull request by tverlaan**
As per the subject.

### CODE REVIEW

**Comment by tverlaan** [comment]
This should be an improvement for #149

**Comment by gregdek** [comment]
This module is maintained by the Ansible core team, so it may take a while longer to get a review; we appreciate your patience. attn: @bcoca @abadger @jimi-c @bennojoy

**Comment by gregdek** [comment]
Hi @tverlaan. Thanks for your patience here.

First, it appears that the underlying code has changed since your submission. If you believe that this PR still applies, please rebase and we will put it back into our review process. 

Second, there's no hurry, since this is core functionality that would need to be reviewed by the core team, we won't be able to review until after 2.0 is released, so marking with the "next" milestone to indicate that.

**Comment by tverlaan** [comment]
Hi @gregdek. I'm not really using the speedup that this PR might create. So I'm not going to put more effort in it (this isn't my first try getting this patch into the repo).
I'm sure you've heard it before but the time it takes before a PR is considered/looked at is a bit long. Too long for my taste (especially for a small enhancement). I'm not sure what the Ansible team is trying to do to shorten this but I'd recommend to do something with it.

Closing since not rebasing.

**Comment by robynbergeron** [comment]
Hi @tverlaan -- thanks for taking the time to respond, and for providing your honest feedback on the state of the PR process. 

We know the lag time has been far from ideal -- and fixing the process (as well as catching up) is one of the big things that @gregdek and I are focusing on right now. I'm sorry that we didn't get to this sooner, and I hope that this experience doesn't stop you from contributing in the future as we continue to make improvements to the process.

**Pull request closed without merging**
