### PR TITLE
Use addresses and names reserved for documentation

### PR DESCRIPTION
**Pull request by ypid**
##### ISSUE TYPE
- Docs Pull Request
##### COMPONENT NAME

All matching once/all that I found.
##### ANSIBLE VERSION

devel
##### SUMMARY

Use addresses and names reserved for documentation while trying to preserve the meaning of the examples.

Related to: https://github.com/ansible/ansible/issues/17479

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @ypid for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @ypid for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by ypid** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @ypid for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @ypid for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by ypid** [comment]
ready_for_review

**Pull request closed without merging**
