### PR TITLE
Added in ec2_elb_lb module the "facts" state

### PR DESCRIPTION
**Pull request by lucaagostini**
I've added in the "ec2_elb_lb" module the "facts" state to get the information of an ELB.
This is usefull, for example, when you have to update a DNS record with the value of the dns name of the ELB and the ELB already exists (it can be created in a CloudFormation template).
If there isn't any ELB with the requested name, the module will fail with a message.

This is an example in how to use the module with the `facts` state:

```
- name: TEST
  hosts: localhost
  connection: local
  user: myuser
  tasks:
    - local_action:
        module: ec2_elb_lb
        name: my-elb-name
        state: facts
      register: res_elb
    - debug: msg="Update the DNS entry with the value '{{ res_elb.elb.dns_name }}'"
```

### CODE REVIEW

**Comment by bennojoy** [comment]
@lucaagostini  seems similar to #696 ?

**Comment by tedder** [comment]
#696 gives instance information; this gives ELB information. The two could (and perhaps should) be combined since they are complementary.

**Comment by lucaagostini** [comment]
@bennojoy: @tedder is right about the difference between the modules

**Comment by bcoca** [comment]
I would push for the merging both sets into a ec2_elb_facts module

**Comment by gregdek** [comment]
@lucaagostini Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please give it a +1; at that point, we will add the “priority_reviewed” flag to this PR, which will move it to the top of our queue for potential inclusion.

**Comment by gregdek** [comment]
@lucaagostini Thanks for submitting this pull request. Please accept our apologies for taking so long to review it.

Unfortunately, due to this delay, it appears that the underlying code has changed, and this PR needs to be rebased. If you believe that this PR still applies, please rebase and we will then put it into our (new, faster) community review process as soon as possible.  Again, apologies for the delay and the extra work.

**Comment by gregdek** [comment]
A friendly reminder: this pull request has been marked as needing your action, and it hasn't been updated in the last month. 

If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we'll keep it open pending your changes.

If we receive no indication from you within a week, we will close this pull request.

**Comment by lucaagostini** [comment]
Hello, I believe that this pull request has been deprecated by the "ec2_elb_facts_module" module in the 2.0 version

**Comment by gregdek** [comment]
Thanks for checking it out @lucaagostini, and for submitting the initial PR. Closing this PR as deprecated.

**Pull request closed without merging**
