### PR TITLE
Fixes #3549

### LINKED ISSUE #3549: ec2_eip error: 'module' not found
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

ec2_eip
##### ANSIBLE VERSION

```
ansible 2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

Basic usage of ec2_eip module has failed with error.
##### STEPS TO REPRODUCE

```
- name: allocate a new elastic IP and associate it with an instance
  ec2_eip: device_id="{{ ec2_cms.instance_ids }}" region="{{ global.region }}"
  register: cms_eip

- debug: msg="Allocated elastic IP for CMS is {{ cms_eip.public_ip }}"
```
##### EXPECTED RESULTS

Associate EIP
##### ACTUAL RESULTS

Error:

```
TASK [ec2-create : allocate a new elastic IP and associate it with an instance] 
14:44:03            task path: /var/lib/rundeck/ansible-temp-run/appcloud-ansible/roles/ec2-create/tasks/ec2-cms.yml:22
14:44:04            An exception occurred during task execution. To see the full traceback, use -vvv. The error was: NameError: global name 'module' is not defined
14:44:04            fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/var/lib/rundeck/.ansible/tmp/ansible-tmp-1461671043.7-159857386516552/ec2_eip\", line 2705, in <module>\n    main()\n  File \"/var/lib/rundeck/.ansible/tmp/ansible-tmp-1461671043.7-159857386516552/ec2_eip\", line 356, in main\n    module.check_mode, isinstance=is_instance)\n  File \"/var/lib/rundeck/.ansible/tmp/ansible-tmp-1461671043.7-159857386516552/ec2_eip\", line 273, in ensure_present\n    instance = find_device(ec2, device_id, isinstance=False)\n  File \"/var/lib/rundeck/.ansible/tmp/ansible-tmp-1461671043.7-159857386516552/ec2_eip\", line 242, in find_device\n    module.fail_json(msg=str(e))\nNameError: global name 'module' is not defined\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}
```

### PR DESCRIPTION
**Pull request by ghost**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

ec2_eip module
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file =
  configured module search path = ['/Users/rmendes/github/oss/ansible-modules-core', '/Users/rmendes/github/oss/ansible-modules-extras']
```
##### SUMMARY

Fixes #3549. The module object was not being explicitly passed to functions. On older versions of Ansible this did not seem to matter. Seeing this error, made me realize it was time to make it explicit to ensure no one sees the issue.

The change takes the module object created in main and passes it to functions that need it. The module object was only being used in failure cases where a device_id is specified.

Before the fix:

```
fatal: [localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "module_stderr": "Traceback (most recent call last):\n  File \"/var/lib/rundeck/.ansible/tmp/ansible-tmp-1461671043.7-159857386516552/ec2_eip\", line 2705, in <module>\n    main()\n  File \"/var/lib/rundeck/.ansible/tmp/ansible-tmp-1461671043.7-159857386516552/ec2_eip\", line 356, in main\n    module.check_mode, isinstance=is_instance)\n  File \"/var/lib/rundeck/.ansible/tmp/ansible-tmp-1461671043.7-159857386516552/ec2_eip\", line 273, in ensure_present\n    instance = find_device(ec2, device_id, isinstance=False)\n  File \"/var/lib/rundeck/.ansible/tmp/ansible-tmp-1461671043.7-159857386516552/ec2_eip\", line 242, in find_device\n    module.fail_json(msg=str(e))\nNameError: global name 'module' is not defined\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "parsed": false
}
```

After the fix:

```
fatal: [localhost - > localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "msg": "EC2ResponseError: 400 Bad Request\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Response><Errors><Error><Code>InvalidInstanceID.NotFound</Code><Message>The instance ID 'i-11111111' does not exist</Message></Error></Errors><RequestID>296a8758-b97a-4261-a333-39a4d0d85901</RequestID></Response>"
}
```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks again to @rickmendes. This module is going into community review.

We notice that you are one of the maintainers (@rickmendes) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by ghost** [comment]
This is testing out fine on success and fail cases. So I would like to shipit

**Comment by gregdek** [comment]
Thanks @rickmendes. Since you are one of the maintainers (@rickmendes) of this module and you commented with "shipit", we are marking this PR for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by ghost** [comment]
@gregdek I asked to be removed from ec2_elb_lb, not ec2_eip. If removing from one removes from all I am fine with you taking the owner_pr tag off. Otherwise, I am still on the hook for maintaining this one and the owner_pr tag should be put back.

Let me know either way. Thanks.

**Comment by ryansb** [comment]
@rickmendes Yup, you will be removed from the ec2_elb_lb and left as maintainer for the EIP module. We do maintainership by module.

**Comment by ryansb** [comment]
LGTM - thanks for fixing that one! Merged as https://github.com/ansible/ansible-modules-core/commit/72655fe4c851007e3f9caa51c22b1ece42b3589e

**Comment by ghost** [comment]
@ryansb No problem. Now that I am focused on one module I should be able to get to issues sooner.

**Comment by ryansb** [comment]
Oops - forgot to close this one.

**Pull request closed without merging**
