### PR TITLE
Added validate_bucket and validate_key for any S3 GET requests

### PR DESCRIPTION
**Pull request by JoelGilliland**
This is a fix for https://github.com/ansible/ansible-modules-core/issues/69
Original pull request 1498 has been refactored to include less API calls.

### CODE REVIEW

**Comment by gregdek** [comment]
@tgerla @lwade Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please give it a +1; at that point, we will add the “priority_reviewed” flag to this PR, which will move it to the top of our queue for potential inclusion.

**Comment by adenot** [comment]
+1

**Comment by JoelGilliland** [comment]
After testing more, I've found some pretty glaring bugs in other parts of the module other than GET. I'm trying to acquire full access to a sandbox account to do more full, end to end tests. We can close this, and I can open a new one when completed, or whatever you guys think is best.

**Comment by gregdek** [comment]
I'll go ahead and close this PR, @JoelGilliland, and we'll look for your next PR.  Also, since you've found additional bugs, it might be useful to file them as separate issues. Thanks!

**Pull request closed without merging**
