### PR TITLE
unarchive - ZipFile class name collision

### PR DESCRIPTION
**Pull request by tphummel**
##### Issue Type:

Bug Report Pull Request
##### Ansible Version:

```
ansible --version
ansible 1.9 (devel 2a04663255) last updated 2015/01/20 14:15:43 (GMT -700)
  lib/ansible/modules/core: (detached HEAD 396c399b54) last updated 2015/01/20 14:21:03 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD 2396f36f11) last updated 2015/01/20 14:21:07 (GMT -700)
  v2/ansible/modules/core: (detached HEAD 8ba8f5ef4d) last updated 2015/01/20 14:21:11 (GMT -700)
  v2/ansible/modules/extras: (detached HEAD 2396f36f11) last updated 2015/01/20 14:21:14 (GMT -700)
  configured module search path = None
```
##### Environment:

master OSX 10.10.1 controlling ubuntu 14.04.1
##### Summary:

It appears changes introduced in https://github.com/ansible/ansible-modules-core/commit/6159b5c4235b427cd6553a2d8d99d4fff12bc805 caused a collision between the core python ZipFile and the ansible class ZipFile.
##### Steps To Reproduce:

```
- name: create directory
  sudo: yes
  file:
    path: /home/deploy
    state: directory

- name: expand package
  sudo: yes
  unarchive:
    src: /tmp/pkg.zip
    dest: /home/deploy
    copy: no
```
##### Expected Results:

```
TASK: [deploy | expand package] ******************************************* 
changed: [host]
```
##### Actual Results:

```
failed: [host] => {"failed": true, "parsed": false}
SUDO-SUCCESS-ysixiasgspdttquszbfwqhnyonlcpbyh
Traceback (most recent call last):
  File "/home/deploy/.ansible/tmp/ansible-tmp-1421882254.59-91494488231388/unarchive", line 1855, in <module>
    main()
  File "/home/deploy/.ansible/tmp/ansible-tmp-1421882254.59-91494488231388/unarchive", line 282, in main
    for filename in handler.files_in_archive:
  File "/home/deploy/.ansible/tmp/ansible-tmp-1421882254.59-91494488231388/unarchive", line 98, in files_in_archive
    archive = ZipFile(self.src)
TypeError: __init__() takes exactly 4 arguments (2 given)


FATAL: all hosts have already failed -- aborting
```

### CODE REVIEW

**Comment by abadger** [comment]
_sugh_ Thanks for catching that.  I'm going to rename the internal class rather than the python library class.

**Comment by tphummel** [comment]
@abadger sounds good. thanks for the fast response.

**Comment by bcoca** [comment]
closing in favor of abadger's incoming PR

**Comment by abadger** [comment]
Hopefully fixed in the above commit.  I also found out why the integration tests in the main repo weren't catching this and fixed them so that unzipping is tested: ansible/ansible@cce87acfedaeca097bf6e84ea8618b226bd2d98d

**Comment by tphummel** [comment]
looks good to me. thank you!

**Pull request closed without merging**
