### PR TITLE
Allow apache instance to be set when managing multiple apache instances

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by gregdek** [comment]
@berendt Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please give it a +1; at that point, we will add the “priority_reviewed” flag to this PR, which will move it to the top of our queue for potential inclusion.

**Comment by gregdek** [comment]
@berendt friendly ping to review this PR if you have time.

**Comment by berendt** [comment]
@gregdek Sorry for the delay. I will have a look tomorrow.

**Comment by gregdek** [comment]
Hi @berendt -- any chance to review this one?

**Comment by gregdek** [comment]
Looks like @berendt is unavailable to review here, so putting into core_review. It may take a while to get this PR reviewed. Thanks for your patience here.

**Comment by gregdek** [comment]
Thanks @geoffwright for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by ghost** [comment]
Since I submitted this I've finally moved on from using Apache for anything, so I think this can be closed. If an active apache on Debian user sees the need for this and would like to rebase it, please feel free to reopen.

**Pull request closed without merging**
