### PR TITLE
Renamed the Modules from dnos* -> dellos*, updated copyright, correct…

### PR DESCRIPTION
**Pull request by skg-net**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME
- modules/core/network/dellos*
##### ANSIBLE VERSION
- ansible 2.2.0 (devel f497d771c8) last updated 2016/09/15 12:00:53 (GMT -700)
  lib/ansible/modules/core: (detached HEAD 48d932643b) last updated 2016/09/15 12:01:19 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD aa45bd8a94) last updated 2016/09/15 12:01:19 (GMT -700)
  config file = /home/skg/lothlorien/test-network-modules/ansible.cfg
  configured module search path = Default w/o overrides
##### SUMMARY
- Renamed the Modules from dnos\* -> dellos*
- Updated the copyright
- Corrected documentation issue.
- Removed unwanted import

### CODE REVIEW

**Comment by skg-net** [comment]
@gundalow @privateip, Please take a look at it.

**Comment by gregdek** [comment]
maintainer unknown ping @gregdek @resmo @robynbergeron.

**Comment by gregdek** [comment]
Thanks @skg-net for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gundalow** [comment]
Can you please rebase this change? 

We had to update `extends_documentation_fragment` anyway as CI was failing.

**Comment by skg-net** [comment]
rebased. ready_for_review

**Comment by gregdek** [comment]
Thanks @skg-net. To the current maintainers, @dhivyap, @skg-net, @privateip, @gundalow please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gundalow** [comment]
`ansible/ansibullbot` ownership details have been updated in https://github.com/ansible/ansibullbot/commit/6c4151c8dc5443c712a03faf98a7495ed95fa44b

**Comment by gundalow** [comment]
Merged, thank you.

**Pull request merged**
