### PR TITLE
rackspace: pass full path to the isdir.

### PR DESCRIPTION
**Pull request by vmihailenco**

### CODE REVIEW

**Comment by sivel** [comment]
I'll try to review this soon. My first step will be writing a full series of tests for this module before validating these changes.

**Comment by gregdek** [comment]
@sivel any progress here?

**Comment by sivel** [comment]
Not as of yet.  Tests take a super long time to write.

**Comment by gregdek** [comment]
@sivel just a periodic ping to check in.

**Comment by gregdek** [comment]
Ping @sivel for an update here.

**Pull request merged**
