### PR TITLE
added django_manage: syncdb --all; migrate --fake

### PR DESCRIPTION
**Pull request by conrado**
it is quite common to initialize deployments with syncdb --all and migrate --fake

### CODE REVIEW

**Comment by gregdek** [comment]
@conrado thanks for submitting this pull request. Please accept our apologies for taking so long to review it.

It appears that this PR needs to be rebased due to changes in the code base. If you believe that this PR still applies, please rebase and we will then put it into our review process.

**Comment by gregdek** [comment]
@conrado A friendly reminder: this pull request has been marked as needing your action, and it hasn't been updated in the last month. 

If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we'll keep it open pending your changes.

If we receive no indication from you within a week, we will close this pull request.

**Comment by conrado** [comment]
@gregdek ping

**Comment by gregdek** [comment]
Ah, thanks @conrado for your response! Looks like it needs to be rebased now, though, so please do that and we will put it back into community_review.

**Comment by gregdek** [comment]
@tastychutney Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by cchurch** [comment]
Looks like it needs to be rebased again as a result of merging https://github.com/ansible/ansible-modules-core/pull/1810...

**Comment by robynbergeron** [comment]
Hi @conrado -- sorry, looks like this needs a rebase, per @cchurch's comments. Getting ever closer :) 

Once you have rebased this PR, please add a comment with the text "ready_for_review" and we will continue with the review process. 

Thanks for continuing to see this one through, we appreciate it!

**Comment by gregdek** [comment]
Closing due to contributor inactivity.

**Pull request closed without merging**
