### PR TITLE
Added external_ips parameter to GCE

### PR DESCRIPTION
**Pull request by ZuluPro**
Allow user to use a static IP.
 The parameter is a list, so user gives a list of IP's name or 'ephemeral' for a new (as in libcloud).

If several instances are created and there are not enough element in `external_ips`, missing will be 'ephemeral'.

Module will fail if a unknown IP's name is given.

By default the parameter is an empty list, so the module hold its behavior and attach new IP to VM.

### CODE REVIEW

**Comment by ZuluPro** [comment]
Do you want me to do something for facilitate your works?

**Comment by gregdek** [comment]
@ZuluPro Thanks for submitting this pull request. Please accept our apologies for taking so long to review it.

Unfortunately, due to this delay, it appears that the underlying code has changed, and this PR needs to be rebased. If you believe that this PR still applies, please rebase and we will then put it into our (new, faster) community review process as soon as possible.  Again, apologies for the delay and the extra work.

**Comment by gregdek** [comment]
Hi @ZuluPro -- we'd love to evaluate this for inclusion if it still applies, but it needs to be rebased.

**Comment by ZuluPro** [comment]
Ok, I will make it, do you think I can make
`git pull git@github.com:ansible/ansible-modules-core.git master`
(from my current branch)

Or do you have an another solution ?

**Comment by ZuluPro** [comment]
It has been implemented with another PR.

**Pull request closed without merging**
