### PR TITLE
re-implements #226

### PR DESCRIPTION
**Pull request by felix-engelmann**
in optional (editable) way 
with backward compatibility

same as in pull request #227

### CODE REVIEW

**Comment by albertca** [comment]
LGTM

**Comment by gregdek** [comment]
Thanks @felix-engelmann and @albertca for continuing to pursue this one.

@mattupstate Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by gregdek** [comment]
@felix-engelmann Thanks for submitting this pull request. Unfortunately, it appears that the underlying code has changed since your submission, and this PR now needs to be rebased. 

If you believe that this PR still applies, please rebase and we will put it into our community review process as soon as possible. 

Once you have rebased this PR, please add a comment with the text "ready_for_review" and we will continue with the review process.  Thanks!

**Comment by felix-engelmann** [comment]
Rebased PR and again ready_for_review

**Pull request merged**
