### PR TITLE
Add insecure_registry to docker-py pull method

### PR DESCRIPTION
**Pull request by ghost**
Starting from docker-py>=0.5.0 it is impossible to work with private registries based on HTTP.
So we need additional parameter to allow pull from insecure registry
Related to ansible/ansible#9111

### CODE REVIEW

**Comment by abadger** [comment]
It looks like insecure_registry was not a valid parameter before docker-py 0.5.0.  Is that correct?  If so we should either guard against using it in docker-py < 0.5.0 and return an error if the parameter is specified with an old docker-py or always return an error if docker-py < 0.5.0.  Since it appears insecure_registry is not needed with docker-py < 0.5.0, the guarding case is probably more appropriate.

**Comment by abadger** [comment]
I made the changes mentioned above to check that the docker-py version was recent enough and merged the changes:
- https://github.com/ansible/ansible-modules-core/commit/4172d445d3bd8699add652f3b7dc4693397f8d92
- https://github.com/ansible/ansible-modules-core/commit/f65d9ab79326a67430beac4ea4671f9a0e6e7097

Let me know if my changes break things.  Thanks for the pull request!

# Merged

Hi!

This has been merged in, and will also be included in the next major release.

If you or anyone else has any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Comment by drbild** [comment]
@abadger Is there some reason these commits aren't included in the latest release, 1.8.4?

**Comment by abadger** [comment]
@drbild they were added after 1.8.0 was out.  1.8.[1-4] are bugfix releases so this wasn't added in any of those.  We're putting out a 1.9 release soon (1.9rc1 was tagged in the repository, no tarball yet because of some things that needed work to create an official tarball using our jenkins instance).  We're going to have an rc2 around tuesday.  You can take a look at what's going into 1.9 by clonign the repository and following the instructions in this thread:

https://groups.google.com/forum/#!topic/ansible-project/iURJ7cpp5Q0

**Comment by drbild** [comment]
@abadger Makes sense!  Thanks for the quick response and the link.

**Pull request closed without merging**
