### PR TITLE
made port default depending on db engine

### LINKED ISSUE #452: rds module sets Postgres to listen on port 3306 if not specified
##### Issue Type:

Bug Report
##### Ansible Version:

``` bash
[dvaida@scat Atlassian-Stash-Ansible]$ ansible --version
ansible 1.9 (devel ef9cb19976) last updated 2014/12/02 17:29:39 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 63e81cfc2e) last updated 2014/10/30 15:43:29 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD a0df36c6ab) last updated 2014/10/30 15:43:35 (GMT +200)
  v2/ansible/modules/core: (detached HEAD cb69744bce) last updated 2014/10/30 15:43:42 (GMT +200)
  v2/ansible/modules/extras: (detached HEAD 8a4f07eecd) last updated 2014/10/30 15:43:54 (GMT +200)
  configured module search path = None
[dvaida@scat Atlassian-Stash-Ansible]$
```
##### Environment:

FC19
##### Summary:

When the 'port' parameter is not specified, the rds module creates the Postgres instance listening on port 3306 (MySQL).
If the 'port' is set in the playbook to '5432', the DB instance is created correctly.
##### Steps To Reproduce:

```
- name: adding the RDS instance
    local_action:
      module: rds
      backup_retention: 14
      backup_window: 03:00-04:00
      command: create
      db_engine: postgres
      db_name: "{{ db_name }}" 
      engine_version: 9.3.5
      instance_name: "{{ db_instance_name }}"
      instance_type: db.t2.small
      maint_window: Sat:02:00-Sat:03:00
      size: 5
      subnet: "{{ db_subnet }}" 
      vpc_security_groups: "{{ private_postgres_sg_creation.group_id }}"
      username: "{{ db_master_username }}"
      password: "{{ db_master_password }}"
      region: "{{ region }}" 
      wait: yes
      wait_timeout: 1800
    register: rds_instance
```
##### Expected Results:

DB instance gets created and listens on correct port.
##### Actual Results:

Postgres RDS DB listens on port 3306.

### PR DESCRIPTION
**Pull request by bcoca**
should fix #452

### CODE REVIEW

**Comment by gregdek** [comment]
@cove @joshuaconner @softzilla @smashwilson Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by smashwilson** [comment]
@gregdek Er, I think you've flagged the wrong team for this one - it doesn't look like a Docker PR.

**Comment by gregdek** [comment]
@smashwilson LOL -- picky, picky. Fortunately we've got a new triage assistant bot to help with this (which I'm running right now!) 

So let's try this again. @bpennypacker  @willthames Please review this PR and give "shipit" or "needs_revision" as appopriate. Thanks!

**Comment by robynbergeron** [comment]
@bpennypacker @willthames This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by willthames** [comment]
shipit

**Comment by bpennypacker** [comment]
shipit

**Comment by gregdek** [comment]
Thanks again to @bcoca for this PR, and thanks @bpennypacker @willthames for reviewing. Marking for inclusion.

**Pull request merged**
