### PR TITLE
Add support for sockets to the file-module

### PR DESCRIPTION
**Pull request by tuxis-ie**
This patch checks if the given path is a socket. If it's not, it bails. Otherwise, it checks and sets the permissions and ownership.

### CODE REVIEW

**Comment by tuxis-ie** [comment]
I've just been pointed at http://docs.ansible.com/ansible/stat_module.html. Which makes this possibly duplicate. Although the file-module will (incorrectly) handle the sockets as if it were files.

So I guess this PR is not completely useless. But I am unsure if it's useful.

**Comment by gregdek** [comment]
Thanks @tuxis-ie for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

**Comment by gregdek** [comment]
Thanks @tuxis-ie for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@tuxis-ie A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by tuxis-ie** [comment]
@gregdek As said in https://github.com/ansible/ansible-modules-core/pull/2758#issuecomment-169040690, I'm unsure if this patch is useful at all. 

Feel free to close this if it isn't. I don't have the feeling that this issue has been reviewed at all yet.

**Comment by gregdek** [comment]
@tuxis-ie it is a small-ish patch, and potentially useful, but since this is a (very) core module, it can take quite a while to digest these kinds of patches.

If you want to advocate for its inclusion, I'd recommend two things:
1. Rebase so it can be merged without conflict.
2. Attend an Ansible Core team meeting on IRC (https://github.com/ansible/community/blob/master/MEETINGS.md).

Since we just entered freeze for 2.2 release, it may be a while yet before this has a chance of getting in, though.

**Comment by gregdek** [comment]
@tuxis-ie A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by tuxis-ie** [comment]
ready_for_review

**Pull request closed without merging**
