### PR TITLE
Added feature to register an AMI from an EBS volume snapshot

### PR DESCRIPTION
**Pull request by patlachance**
##### ISSUE TYPE

- Feature Pull Request
##### COMPONENT NAME

core/cloud/amazon/ec2_ami.py
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel 1b29c87936) last updated 2016/06/26 06:49:33 (GMT +000)
  lib/ansible/modules/core: (detached HEAD 530ee87bd3) last updated 2016/06/26 06:49:37 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD 1c36665545) last updated 2016/06/26 06:49:40 (GMT +000)
  config file = /home/ec2-user/.ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

Needed to register an image without including the instance root device. 
This is a rebase of https://github.com/ansible/ansible-modules-core/pull/1346

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @patlachance for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by patlachance** [comment]
Tests now succeed so I guess the PR is ready_for_review ! Thanks!

**Comment by gregdek** [comment]
Thanks @patlachance. To the current maintainers, @jjshoe please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by patlachance** [comment]
@gregdek @jjshoe anything else missing to get this PR integrated upstream?

**Comment by jjshoe** [comment]
@patlachance Can you provide a set of steps so this can be tested?

**Comment by jjshoe** [comment]
#4518

**Comment by patlachance** [comment]
@jjshoe sure, have a look at the following example http://www.itisopen.net/2016/08/30/Creating_a_custom_CoreOS_AMI_from_scratch_using_ansible-part1.html

**Comment by patlachance** [comment]
@jjshoe any further help required to test the feature?

**Comment by patlachance** [comment]
@gregdek @jjshoe any further help required to test the feature?

**Comment by gregdek** [comment]
@patlachance let's give @jjshoe a bit longer to respond on this one. We're in feature freeze anyway for the 2.2 release, so this won't land until 2.3 even if it gets approval.

**Comment by jjshoe** [comment]
@gregdek @patlachance 

I haven't had a chance to test this yet, but there's actually two or three versions of this PR in the backlog long before this one. One is even marked ready for upstream review.

**Comment by gregdek** [comment]
@jjshoe if you'd like to close this PR in favor of another PR, just let me know. We can certainly do that.

**Pull request closed without merging**
