### PR TITLE
exclude_hosts does not work as expected with state=drained

### PR DESCRIPTION
**Pull request by vaupelt**
There are established connections for a service. The service is bound to a ipv4-mapped ipv6 address. Wait_for wrongly waits for clients listed in exclude_hosts.

### CODE REVIEW

**Comment by vaupelt** [comment]
This issue attracted no interest here as well as on mailing list (https://groups.google.com/forum/#!topic/ansible-devel/JfreSVJmso8). Is there something I could do to change it?

**Comment by bcoca** [comment]
its on the list for review, but we have a huge backlog to get through

**Comment by gregdek** [comment]
Patch does not appear to pass Travis test for Python 2.4 compatibility.

**Comment by gregdek** [comment]
@vaupelt apologies, but it looks like broken code from elsewhere slipped into your branch here. Can you please rebase this? If it passes merge tests, I'll then put it into community_review status so we can move forward with it.

**Comment by bcoca** [comment]
so the travis issues are unrelated and have been fixed already (would need to rebase to show here, but not needed).

**Comment by gregdek** [comment]
@vaupelt let's rebase anyway to be sure. Sorry for the confusion, but want to make sure we get a clean Travis build to work from.

**Comment by vaupelt** [comment]
I'm new to git and need some advise. The Travis build runs through. Do I did it right or, if not, what could I do, now.

**Comment by gregdek** [comment]
@vaupelt thanks, we're good now. 

@jhoekx @jarv @AnderEnder Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please give it a +1; at that point, we will add the “priority_reviewed” flag to this PR, which will move it to the top of our queue for potential inclusion.

**Comment by ahill00** [comment]
@vaupelt - Can you detail a little more what this patch provides?

In #1822 I was also attempting to patch the buggy behavior in exclude_hosts, but this diff looks like more than that.

**Comment by vaupelt** [comment]
More and more software is ipv6 ready nowadays. I struggled with an Apache server that binds to an ipv4-mapped ipv6 address (looks like an ipv4 addresses prefixed with ::ffff:). One can choose either ipv4 or ipv6 to connect to such an address but it will always be listed in /proc/net/tcp6. It was possible to wait for such connections to drain but there was no way to exclude some remote hosts. This PR is intended to solve this issue in a convenient way.

**Comment by gregswift** [comment]
I chaffed a bit at this originally but after several reviews it seems legit, and in theory should address @andyhky 's concern in #1822

**Comment by ahill00** [comment]
I also have tested this after attempting to patch issues in #1822 - it worked well. Thanks for the patch @vaupelt

**Comment by vaupelt** [comment]
@jhoekx @jarv @AnderEnder some suggestions/findings?

**Comment by vaupelt** [comment]
@gregdek I suspect your notification has not reached the review team. Can you please ping them.

**Comment by shakuzen** [comment]
I faced a simpler problem which this pull request consequently fixes in a more complicated way (to encompass the other functionality it is trying to fix). For my case, simple IPv4 addresses in `exclude_hosts` were not being considered ever due to [this line L233](https://github.com/ansible/ansible-modules-core/blob/devel/utilities/logic/wait_for.py#L233) missing extracting the IP address from the tuple like is done on [this line L182](https://github.com/ansible/ansible-modules-core/blob/devel/utilities/logic/wait_for.py#L182)

Therefore [this line (L247)](https://github.com/ansible/ansible-modules-core/blob/devel/utilities/logic/wait_for.py#L247) always returns `True` and no connections are ever excluded from the active connection count.

Would it be worth submitting a pull request that just fixes that separately in the meantime, since it is something I imagine could be reviewed and merged much more quickly?
It seems this pull request has been opened for quite a while an not a single one of the assigned community reviewers has commented whatsoever.

To fix this simpler case, L233 simply needs to be changed to:

``` python
        return [ _convert_host_to_hex(h)[1] for h in exclude_hosts ]
```

**Comment by gregdek** [comment]
@jhoekx @jarv @AnderEnder are any of you available to review this PR?

**Comment by robynbergeron** [comment]
@jhoekx @jarv @AnderEnder This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
Previous maintainers have been unresponsive, so reassigning to the @ansible/core team for their review.

@vaupelt apologies for the delay, and thanks for the PR.

**Comment by gregswift** [comment]
@robynbergeron considering i'm the original author would my review count ? if that will help move this forward i'll give it another run through since its been a while since my initial review. would just like to see this get merged before it hits 1y.

**Comment by gregdek** [comment]
Unlabeling so next bot run picks up new reviewer (thanks @gregswift)

**Comment by robynbergeron** [comment]
@gregswift per our chat earlier and given your long, long ago history of contributing on this one -- you're now the lucky maintainer of this module! :) The bot runs every six hours so next time this goes through it's all you.

**Comment by robynbergeron** [comment]
@gregswift -- You should get a comment from the bot letting you know to tell us to ship the thing or put it in needs revision, but if you don't, I think you know what to do :) (after testing, of course, so feel free to put that through the retest as you said above and hopefully we can move this one along. :smiley: Thank you!!)

**Comment by gregdek** [comment]
Thanks @vaupelt. To the current maintainers, @gregswift please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregswift** [comment]
gonna get setup to do a verify and then update. might take me a few days but should ave an update by next week

**Comment by gregswift** [comment]
@vaupelt i just ran some verifications and it looks good.

```
# Running with nothing connected
$ ansible localhost -m wait_for -a "host=::1 port=631 state=drained timeout=30"
localhost | SUCCESS => {
    "changed": false, 
    "elapsed": 0, 
    "path": null, 
    "port": 631, 
    "search_regex": null, 
    "state": "drained"
}
# Running with telnet ::1 631 
$ ansible localhost -m wait_for -a "host=::1 port=631 state=drained timeout=30"
localhost | FAILED! => {
    "changed": false, 
    "elapsed": 30, 
    "failed": true, 
    "msg": "Timeout when waiting for ::1:631 to drain"
}
# Running with telnet ::1 631
$ ansible localhost -m wait_for -a "host=::1 port=631 state=drained timeout=30 exclude_hosts=::1"
localhost | SUCCESS => {
    "changed": false, 
    "elapsed": 0, 
    "path": null, 
    "port": 631, 
    "search_regex": null, 
    "state": "drained"
}
# Running with nothing connected
$ ansible localhost -m wait_for -a "host=127.0.0.1 port=631 state=drained timeout=30"
localhost | SUCCESS => {
    "changed": false, 
    "elapsed": 0, 
    "path": null, 
    "port": 631, 
    "search_regex": null, 
    "state": "drained"
}
# Running with telnet 127.0.0.1 631
$ ansible localhost -m wait_for -a "host=127.0.0.1 port=631 state=drained timeout=30"
localhost | FAILED! => {
    "changed": false, 
    "elapsed": 30, 
    "failed": true, 
    "msg": "Timeout when waiting for 127.0.0.1:631 to drain"
}
# Running with telnet 127.0.0.1 631
$ ansible localhost -m wait_for -a "host=127.0.0.1 port=631 state=drained timeout=30 exclude_hosts=127.0.0.1"
localhost | SUCCESS => {
    "changed": false, 
    "elapsed": 0, 
    "path": null, 
    "port": 631, 
    "search_regex": null, 
    "state": "drained"
}
```

I do wonder if we should add an ipv6 example to the docs. Thoughts on that? otherwise i think its ready

**Comment by gregswift** [comment]
@vaupelt Can you replesae rebase/squash this.

extra points for adding an ipv6 example in the module docs, but not needed.

**Comment by gregswift** [comment]
nm... being cherry picked.

**Comment by bcoca** [comment]
closing, did manual cherry pick to avoid 'merge commit', this will be in releases >2.0.2

**Pull request closed without merging**
