### PR TITLE
Fix #3153 again

### LINKED ISSUE #3153: fstab parameter of mount module won't work
##### Issue Type:
- Bug Report
##### Ansible Version:

ansible 2.0.0.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = /usr/share/ansible
##### Environment:

Ubuntu 14.04 64Bit
##### Summary:

set fstab=**/tmp/fstab** in mount module result in 'can't find mount point in **/etc/fstab**'
##### Steps To Reproduce:

```
./test-module -m ../lib/ansible/modules/core/system/mount.py -a "src=/dev/sda9 name=/tmp/mnt fstype=ext3 state=mounted **fstab=/tmp/fstab**"
```
##### Expected Results:

```
changed: ok
```

and a line in /tmp/fstab and 'mount -a' should show the mounted device
##### Actual Results:

```
***********************************
PARSED OUTPUT
{
    "failed": true, 
    "invocation": {
        "module_args": {
            "dump": null, 
            "fstab": **"/tmp/fstab"**, 
            "fstype": "ext3", 
            "name": "/tmp/mnt", 
            "opts": null, 
            "passno": null, 
            "src": "/dev/sda9", 
            "state": "mounted"
        }
    }, 
    "msg": "Error mounting /tmp/mnt: mount: /tmp/mnt konnte nicht in **/etc/fstab oder /etc/mtab** gefunden werden\n"
}
```

### PR DESCRIPTION
**Pull request by mscherer**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

mount
#### SUMMARY

A wrong patch was merged, and it doesn't work on RHEL 6.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @mscherer. To the current maintainers, @grossws please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by robinro** [comment]
It might be nice to have an integration test for this.

Maybe something with `mount -o bind` that works within docker?

**Comment by rwky** [comment]
FYI this is also causing problems with Ubuntu 14.04.

**Comment by gregdek** [comment]
Thanks @mscherer for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by abadger** [comment]
Thanks @mscherer I rebased and merged.  This is now in stable-2.1 and devel.

**Pull request closed without merging**
