### PR TITLE
Ultimate fix of the mount module for Linux

### PR DESCRIPTION
**Pull request by jtyr**
##### ISSUE TYPE

Bugfix Pull Request
##### COMPONENT NAME

`mount` module
##### ANSIBLE VERSION

For 2.1.x or 2.2.
##### SUMMARY

This is the continuation of the fix started in the PR #4439. @abadger, please try to run your Docker test with this fix.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @jtyr. To the current maintainers, @grossws please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by abadger** [comment]
This looks good.  I'll merge it tomorrow morning so I have a chance to look into anything that might break once it is in.

**Comment by jtyr** [comment]
@abadger Did you try to run your docker tests with this patch?

**Comment by abadger** [comment]
Note: Because we're putting out 2.1.2 in a few hours I've reverted this and the other bind mount changes  in stable-2.1.  Work continues on the devel branch.

**Pull request merged**
