### PR TITLE
add support for auth_socket

### LINKED ISSUE #3003: Add plugin as parameter for mysql_user
##### Issue Type:

Feature Idea
##### Ansible Version:

```
$ ansible --version
ansible 2.0.0.0
  config file = 
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

Default configuration.
##### Environment:

N/A
##### Summary:

From the MySQL 5.7 what's new page:

> The server now requires account rows in the mysql.user table to have a nonempty plugin column value and disables accounts with an empty value.

On a fresh installation of MySQL 5.7 the `root` user for host `localhost` is now configured with a plugin value of `auth_socket`. This prevents users other then root to connect as root using the `mysql` client utility:

```
user@server$ mysql -u root -pP4ssw0rd -h localhost
ERROR 1698 (28000): Access denied for user 'root'@'localhost'
```

While as root this works:

```
root@server# mysql -u root -pP4ssw0rd -h localhost
```

Currently I can't change this configuration with Ansible.
##### Steps To Reproduce:

It would be nice to introduce a new parameter to this module which accepts all possible plugin values (defaulting to mysql_native_password) , e.g.:

``` yaml
mysql_user: name=root password=abc123 plugin=mysql_native_password
mysql_user: name=root password=abc123 plugin=auth_socket
```
##### Expected Results:

N/A
##### Actual Results:

N/A

### PR DESCRIPTION
**Pull request by verwilst**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

database/mysql/mysql_user
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel c42501cfe7) last updated 2016/05/03 09:13:13 (GMT +000)
  lib/ansible/modules/core: (detached HEAD b6ad3b6773) last updated 2016/05/02 14:18:29 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD 1846de2809) last updated 2016/05/02 14:18:33 (GMT +000)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

Add support for plugins ( auth_socket ) for authentication in MySQL. Fixes #3003

```
root@ansible:/tmp# ansible debian8 -m mysql_user -a "user=bob plugin=auth_socket" --forks 1
debian8 | SUCCESS => {
    "changed": true, 
    "user": "bob"
}
root@ansible:/tmp# ansible debian8 -m mysql_user -a "user=bob plugin=auth_socket" --forks 1
debian8 | SUCCESS => {
    "changed": false, 
    "user": "bob"
}

mysql> select User,Host,plugin from user where User like 'bob';
+------+-----------+-------------+
| User | Host      | plugin      |
+------+-----------+-------------+
| bob  | localhost | auth_socket |
+------+-----------+-------------+
1 row in set (0.00 sec)

```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @verwilst. To the current maintainers, @Jmainguy please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @verwilst for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by verwilst** [comment]
Merged changes from other commit.

**Comment by verwilst** [comment]
ready_for_review

**Comment by oscherler** [comment]
I’ve been looking at this about a month, not from the `auth_socket` angle but for Pluggable Authentication in general. It’s _hard_:
- Pluggable Authentication is supported from MySQL 5.5.7 and MariaDB 5.2.0, with different syntaxes (`IDENTIFIED WITH auth_plugin AS 'hash_string'` and `IDENTIFIED VIA auth_plugin USING 'hash_string'`, respectively);
- MariaDB started supporting MySQL’s syntax since an unknown revision;
- MySQL also supports `IDENTIFIED WITH auth_plugin BY 'auth_string'`, where `auth_string` is an unencrypted password, since 5.7.6. To my knowledge, MariaDB doesn’t support this yet (10.1.14);
- MySQL supports `ALTER USER` from version 5.7.6, which seems to be required if you want to provide a cleartext password and have it encrypted the plugin. MariaDB does not support this.
- There are also passwordless plugins, like `auth_socket`. For them, the syntax is `IDENTIFIED WITH auth_plugin` or `IDENTIFIED VIA auth_plugin`;
- In MariaDB, the authentication string for the PAM plugin is optional. In MySQL it is mandatory;
- When the plugin is not `mysql_native_password`, the `hash_string` is not a MySQL hash, its format depends on the plugin used (e.g. for PAM: `'mysql, root=developer, users=data_entry'`). It therefore cannot be checked with `is_hash`;
- I won’t even start with SHA256 passwords, it’s [total chaos](https://dev.mysql.com/doc/refman/5.6/en/sha256-authentication-plugin.html).

So when creating a user, you have to:
- Ensure that Pluggable Authentication is supported, or that the plugin used is `mysql_native_password`;
- Switch the syntax for MariaDB;
- Know about plugins that don’t take an `auth_string`;
- If the password is unencrypted, ensure that the syntax is supported, or that the plugin is `mysql_native_password`.

And when updating a password:
- I don’t think you can change the plugin used for an existing user, so `user_exists` has to be modified to check for the plugin;
- `is_hash` cannot be used as it is now to check the provided encrypted password if the plugin is not `mysql_native_password`;
- If the password is unencrypted, ensure that the syntax is supported, or that the plugin is `mysql_native_password`.

Moreover, all of this is hard to test, because I haven’t been able to install a version of MariaDB prior to 5.5 anywhere. It failed even in an Ubuntu 10.04 Vagrant box. I will probably need to create a fleet of Docker containers to test all versions that should be supported.

I will keep trying, but any information or opinion that could help me is welcome. For example:
- Opinions on which minimum version of MySQL and MariaDB this module should support Pluggable Authentication for;
- Docker files for older version of MySQL or MariaDB;
- Pointing out mistakes in my reasoning;
- Etc.

Thank you.

**Comment by Jmainguy** [comment]
@oscherler Awesome write up, thank you.

There are a number of mysql forks out there, and we can either write a new module for each fork (mysql,mariadb,percona, etc etc etc) or we can keep working on these main 3 mysql_modules and add checks for when then syntax starts to diverge.

If its a feature the main forks will all share, I think it makes a ton of sense to add it to these modules and just start adding if checks for the version and change syntax accordingly. If its a feature just for fork that the rest wont share, we should likely write a small module for that fork that basically includes the core mysql module and just adds those specific features.

Just spitting out ideas though. Definitely open to suggestions.

As far as OS's, I think going as old as support for the OS's is present makes sense, Centos 5, whatever the oldest LTS Ubuntu supported one is (guessing 14.04?), and the default mysql forks / versions that they suggest installing on those os's.

**Comment by oscherler** [comment]
I made some progress. I have a project with 13 Docker images with different MySQL or MariaDB versions, and playbooks to try and test all situations.

I think I’m done fixing `user_add`, but I’ll need more time to do `user_mod`.

**Comment by Jmainguy** [comment]
@oscherler Awesome thats great to hear, keep it up

**Pull request closed without merging**
