### PR TITLE
Fix docker container restart issue where the container is removed

### PR DESCRIPTION
**Pull request by sebssource**
##### ISSUE TYPE

- Bugfix Pull Request
##### COMPONENT NAME

docker.py
##### ANSIBLE VERSION

```
ansible 2.0.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

I noticed the bug in the above version but it is present in master as well.
##### SUMMARY

Basically using a handler to restart a container causes the container to be removed, and it doesn't restart properly since the handler doesn't have all the information to run the image and create a container. The containers start up without proper volumes mounted and wrong networking settings.

Checking commit history this looks like a regression.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @sbstnp. To the current maintainers, @cove, @softzilla, @smashwilson, @zfil, @ThomasSteinbach please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by lenfree** [comment]
I also bumped into this problem. @timrchavez @hsoft any chance of reviewing this soon? :)

**Comment by ghost** [comment]
I'm not sure why I'm brought into this, but a quick history check shows that this is a direct revert of #1972, which has much more context than this PR here, so my gut tells me that the proper fix is almost certainly not what is proposed here, but something that requires a finer analysis.

**Comment by lenfree** [comment]
I compared Ansible v1.9.4 with v2.0.2 and I don't have this block of code from line 1804 in v1.9.4. I recently upgrade to use v2 and start getting this error but not in v1.9.4.

**Comment by gregdek** [comment]
Thanks @sbstnp for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@sbstnp A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by sebssource** [comment]
I'm closing this, it appears to be more complicated than first thought. Will create another with the proper fix later.

**Pull request closed without merging**
