### PR TITLE
Yum on rhn-plugin systems requires root

### PR DESCRIPTION
**Pull request by dekimsey**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

yum
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /Users/dkimsey/.ansible.cfg
  configured module search path = ['library/']
```
##### SUMMARY

This change forces the yum module to die if executed on an RHN enabled system on non-root.

RHN enabled systems cannot be reliably queried unless repoquery/yum are
executed as root. Attempting to fall-back to repoquery will give
inconsistent results (seeing as how to actually perform a task one must
sudo anyway).
##### Example `repoquery` execution

Decisions made based on data obtained during non-root execution will not match expectations when executed as root.

```
[dkimsey@test-bar-02 ~]$ repoquery --plugins --show-duplicates --quiet
ansible
*Note* Spacewalk repositories are not listed below. You must run this
command as root to access Spacewalk repositories.
[dkimsey@test-bar-02 ~]$ sudo repoquery --plugins --show-duplicates
--quiet ansible
ansible-0:1.9.2-1.el7.noarch
ansible-0:1.9.4-1.el7.noarch
ansible-0:2.1.0.0-1.el7.noarch
```

### CODE REVIEW

**Comment by dekimsey** [comment]
I'm assuming something is up with devel, because the errors reported from Travis have nothing to do with this pull request.

**Comment by gregdek** [comment]
Thanks @dekimsey for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by dekimsey** [comment]
ready_for_review

I had to rebase on devel to fix the CI errors.

**Comment by gregdek** [comment]
Thanks @dekimsey for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
