### PR TITLE
Catch the rare condition where ami creation failed, this is critical …

### LINKED ISSUE #3600: Failed AMI creation makes AMI run until timeout
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

ec2_ami
##### ANSIBLE VERSION

```
2.1
```
##### SUMMARY

Though rare an AMI creation can fail, returning a status of `failed`. The code doesn't check for this case, and keeps waiting until the timeout is expired. 
##### EXPECTED RESULTS

ec2_ami should return when a state of `failed` is encountered
##### ACTUAL RESULTS

ec2_ami does not return when a state of `failed` is encountered

### PR DESCRIPTION
**Pull request by jjshoe**
##### ISSUE TYPE

- Bugfix Pull Request
##### COMPONENT NAME

ec2_ami
##### SUMMARY

Fixes #3600

### CODE REVIEW

**Comment by jjshoe** [comment]
ready_to_review

**Comment by gregdek** [comment]
Thanks again to @jjshoe. This module is going into community review.

We notice that you are one of the maintainers (@jjshoe) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by jjshoe** [comment]
shipit

**Comment by gregdek** [comment]
Thanks @jjshoe. Since you are one of the maintainers (@jjshoe) of this module and you commented with "shipit", we are marking this PR for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request merged**
