### PR TITLE
Fixing nxos_facts parsing

### PR DESCRIPTION
**Pull request by GGabriele**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

nxos_facts 
##### ANSIBLE VERSION

```
ansible 2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = xxx
```
##### SUMMARY

Fixed a bogus param parsing

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks again to @GGabriele. This module is going into community review.

We notice that you are one of the maintainers (@privateip, @GGabriele) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by GGabriele** [comment]
shipit

**Comment by gregdek** [comment]
Thanks @GGabriele. Since you are one of the maintainers (@privateip, @GGabriele) of this module and you commented with "shipit", we are marking this PR for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gundalow** [comment]
The Travis Job was failing due to what appeared to be issues with apt repos. The job has been restarted and now passes

**Comment by gregdek** [comment]
Thanks @GGabriele for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by privateip** [comment]
@GGabriele I have incorporated these changes into #4578 

If you are happy with those changes, lets just close out this PR and get 4578 merged

**Comment by GGabriele** [comment]
It sounds good!

**Pull request closed without merging**
