### PR TITLE
Docker module: add oom_score_adj param

### PR DESCRIPTION
**Pull request by awasilyev**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

docker
##### ANSIBLE VERSION

```
ansible 2.0.1.0
```
##### SUMMARY

This adds ability to set oom_score_adj param of docker container. 
Base functionality available since docker-1.10 https://github.com/docker/docker/pull/16277

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @awasilyev. To the current maintainers, @cove, @softzilla, @smashwilson, @zfil, @ThomasSteinbach please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @awasilyev for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by awasilyev** [comment]
ready_for_review

**Comment by awasilyev** [comment]
any chance to get this reviewed?

**Comment by chouseknecht** [comment]
@awasilyev why are we modifying _docker.py? It is deprecated. Does this change instead need to be applied to docker_container.py

**Comment by awasilyev** [comment]
A lot of people uses docker.py in production... switching from docker.py to docker_container requires to rewrite/retest a lot of code

**Pull request closed without merging**
