### PR TITLE
Add track submodule branches parameter

### PR DESCRIPTION
**Pull request by bibliotechy**
Was https://github.com/ansible/ansible/pull/7877
Allows user to decide if git submodule should track branches/tags or track commit hashes defined in the superproject.

Add track_branches parameter to the git module.

Defaults to track branches behavior.

Original Issue was https://github.com/ansible/ansible/issues/7030
##### Issue Type:

“Bug Report” /  “Feature Idea”
##### Ansible Version:

ansible 1.6 (devel a5e7492c4f) last updated 2014/04/15 21:12:13 (GMT -400)
##### Environment:

Ubuntu 12.04
##### Summary:

Git submodule update is hard coded to track branches (always adds the `--remote` flag, assuming the git version is late enough to support tracking branches.

https://github.com/ansible/ansible/blob/1c9950678a8a226020c6a1a32d6a60f942495072/library/source_control/git#L423-424

I have a use case where we definitely want to track the sha1 recorded in the superproject, not a branch or tag of the submodule. I'm willing to put in a PR on this, but wonder about the best way to add in a choice on this. A submodule_remote parameter? Something else?
##### Steps To Reproduce:

In a git repo with submodules that are tracked by commit hash stored in the superproject rather than branch or tag, run 

`git: repo=reponame dest=place/to/put/it`
##### Expected Results:

I'd expect all of my submodule repos to be checkout out on the commit stored in the the superproject.
##### Actual Results:

All of my submodule repos are be checkout out to the commit at the tip of the master branch.

If the submodules also do not use the label "master" for the master branch, it throws an error

`fatal: Needed a single revision`

`Unable to find current origin/master revision in submodule path`

### CODE REVIEW

**Comment by pztrick** [comment]
:+1: My project tracks commit hashes and I'm currently checking out this P/R's 37ed9b1 just so I can deploy at all.

**Comment by josef-spak** [comment]
I'd like to rebase/squash this and change the default behavior to match git behavior if that's OK?

**Comment by mtotheikle** [comment]
+1

We need this fix / option added as well since our projects must use the parents project recorded SHA-1. I'd say that without this fix applied the Git module is broken as most projects I've worked on require tracking the recored SHA-1 or face issues with upstream changes breaking projects.

I'm for making the default behavior of this the same as git as that would cause less confusion.

After trying to figure out where things were breaking in my project I found this commit that introduced the option, https://github.com/ansible/ansible/commit/11895fa43734ce246a7bf64746df618540251c1f. Maybe @addshore could explain the reasoning for adding it as the default?

**Comment by bcavagnolo** [comment]
+1 on merging this. Just ran into this issue today.

**Comment by addshore** [comment]
+1 to this too

**Comment by abadger** [comment]
@bibliotechy not trying to derail getting this feature in, but I have a question -- at the end of your report your note that submodules without a master branch get a fatal error.  From reading up about git submodules --remote, it looks like you should add a `branch=no-master-so-specify-branch-name` to the .gitmodules file for the project.  Is there a reason that should not be done?

@addshore Since you wrote the code that adds --remote, the question was asked why this was made the default.  Is there a reason or was that just an oversight?

**Comment by addshore** [comment]
@abadger oversight on my part

**Comment by abadger** [comment]
Excellent.   I think we should reverse the default to use commit hashes (like git itself does), then.

The parameter name and description also seem a little confusing.  How about something like:

```
track_submodules:
    required: false
    default: "no"
    choices: ["yes", "no"]
    version_added: "1.8"
    description:
         - if C(yes), submodules will track the latest commit on their master branch (or other branch specified in .gitmodules).  If C(no), submodules will be kept at the revision specified by the main project. This is equivalent to specifying the --remote flag to git submodule update.
```

**Comment by abadger** [comment]
Thanks for the work on this @bibliotechy !

# Merged

Hi!

This has been merged in, and will also be included in the next major release.

If you or anyone else has any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Pull request merged**
