### PR TITLE
Fixes #1131: Add option to only add user to groups that exist

### LINKED ISSUE #1131: Add option to only add user to groups that exist
I'd like an option in the user module to allow for users to only be added to groups specified in the 'groups' parameter if the groups exist, and just happily skip any groups that do not rather than having the task fail.

This looks pretty trivial to add, so I'll try implementing it myself first and hopefully submit a pull request shortly.

### PR DESCRIPTION
**Pull request by tonyyarusso**
Adding a simple option to the user module to allow additional groups that don't exist to just be skipped, rather than triggering a failure.

### CODE REVIEW

**Comment by gregdek** [comment]
@tonyyarusso Thanks for submitting this pull request. Please accept our apologies for taking so long to review it.

Unfortunately, due to this delay, it appears that the underlying code has changed, and this PR needs to be rebased. If you believe that this PR still applies, please rebase and we will then put it into our (new, faster) community review process as soon as possible.  Again, apologies for the delay and the extra work.

**Comment by tonyyarusso** [comment]
All right, I think I did that right (first time rebasing).

**Comment by gregdek** [comment]
@tonyyarusso apologies, but looks like the underlying code has changed again, requiring you to rebase again.

If you believe that this PR still applies, please rebase and we will put it into our community review process as soon as possible. 

Once you have rebased this PR, please add a comment with the text "ready_for_review" and we will continue with the review process.  Thanks!

**Comment by tonyyarusso** [comment]
Rebase is done again.

**Comment by gregdek** [comment]
Got it. Thanks @tonyyarusso.

@sfromm Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by tonyyarusso** [comment]
Poke?

**Comment by jordiecometrica** [comment]
shipit

This adds a simple option whose default doesn't change behaviour. It would be nice to include a test for the new behaviour, but that missing test should not hinder the inclusion of this change.

**Comment by jjshoe** [comment]
As discussed in #ansible:

user bobs groups: foo,bar,baz
server 1 groups: foo,zulu
server 2 groups: bar,alpha
server 3 groups: foxtrot

PR creator wants user bob to be added to correct groups on server 1, and server 2, server 3 shouldn't match. However instead of changing the module this can be accomplished with the intersect filter.

**Comment by jjshoe** [comment]
```
TASKS:

- name: What groups are valid?
  debug: msg="{{ global_groups | intersect(item.valid_groups) }}"
  with_items: users


VARS:

global_groups:
  - foo
  - bar

users:
  - name: jim
    valid_groups:
      - foo
      - bar
      - baz
  - name: jill
    valid_groups:
      - bar
      - potato
```

**Comment by jjshoe** [comment]
@tonyyarusso - Where you able to get moving using intersect?

**Comment by gregdek** [comment]
Thanks @tonyyarusso for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

**Comment by jctanner** [comment]
Related PR https://github.com/ansible/ansible-modules-core/pull/881

**Pull request closed without merging**
