### PR TITLE
Dont use shell to run external processes in apt_rpm

### LINKED ISSUE #2839: apt-rpm
##### Issue Type:

Bug Report
##### Component Name:

apt_rpm
##### Ansible Version:

N/A
##### Summary:

When I try to install a package using this command. It gives me a error.
ansible remote_hosts -m apt_rpm -s -a "pkg=elinks state=present"

image

image

FYI, I tried installing through Apt-get command and it works.

### PR DESCRIPTION
**Pull request by evgkrsk**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

apt_rpm
##### ANSIBLE VERSION

all versions thru 2014-2016 (present time).
##### SUMMARY

Ensure that shell redirection is working properly on apt-get run by setting use_unsafe_shell=True to module.run_command

Fixes #2839 

Before change (actual result):

```
"changed": false,
"failed": true,
"msg": 'apt-get -y install elinks' failed: E: Unable to locate package>\nE: Unable to locate package /dev\n
```

after change (expected result):

```
"changed": true,
"failed": false,
"msg": 'elinks present(s)'
```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks again to @evgkrsk. This module is going into community review.

We notice that you are one of the maintainers (@evgkrsk) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by evgkrsk** [comment]
shitip

**Comment by evgkrsk** [comment]
shipit

**Comment by gregdek** [comment]
Thanks @evgkrsk. Since you are one of the maintainers (@evgkrsk) of this module and you commented with "shipit", we are marking this PR for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by mscherer** [comment]
I am a bit hesitant to merge, use_shell mean there is potential security issue, and so, wouldn't it be simpler to just not return "out" if we want to get it to /dev/null ?

**Comment by evgkrsk** [comment]
Sure, you are right. I rewrite all shell calls with module.run_command, please review (but PR branch name is no more relevant).

**Comment by evgkrsk** [comment]
ping, shipit

**Pull request merged**
