### PR TITLE
Subversion should not check revision info after exporting repository

### PR DESCRIPTION
**Pull request by agnek**
Subversion should not check revision info after exporting repository.

### CODE REVIEW

**Comment by Octen** [comment]
I tested @agnek's bugfix and **it works fine**.

_Thank you in advance for the merger of this pull requests soon._

**Comment by gregdek** [comment]
@agnek, thanks for submitting this pull request. Please accept our apologies for taking so long to review it.

Unfortunately, due to this delay, it appears that the underlying code has changed, and this PR needs to be rebased. If you believe that this PR still applies, please rebase and we will then put it into our review process as soon as possible.  Again, apologies for the delay and the extra work.

**Comment by bcoca** [comment]
the change looks good, but we need a rebase

**Comment by gregdek** [comment]
@agnek as soon as you can rebase, we have approval from @bcoca to merge.

**Comment by agnek** [comment]
@gregdek i'll try to do it asap.

**Comment by agnek** [comment]
@bcoca @gregdek guys, looks like this bug was already fixed by someone. So there are no need to to merge my pull request with current head. Just close and delete my pull request.

**Comment by gregdek** [comment]
Thanks @agnek for taking a closer look.

**Pull request closed without merging**
