### PR TITLE
Gentoo/OpenRC+systemd: check for systemd if falling back to service command

### PR DESCRIPTION
**Pull request by Tatsh**
Gentoo with OpenRC fix
See https://bugs.gentoo.org/show_bug.cgi?id=504116

This is a re-do of https://github.com/ansible/ansible/pull/8041

### CODE REVIEW

**Comment by ghost** [comment]
i think this PR might be obsolete as ansible as moved on towards using /proc/1/comm to see if systemd is not just installed, but also enabled: https://github.com/ansible/ansible-modules-core/blob/devel/system/service.py#L415  This should appear in the next ansible major release.

**Comment by ghost** [comment]
you can probably test it by simply replacing with service.py with the one from master.

**Comment by Tatsh** [comment]
I like that approach better. I will give it a try.

**Comment by Tatsh** [comment]
Works for me. Closing this in favour of the `/proc/1/comm` way of detection.

**Pull request closed without merging**
