### PR TITLE
Ensure yum failures in with-loop result into a failed task

### LINKED ISSUE #4214: yum repo not showing failed on a package not found
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

yum module
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = 
  configured module search path = Default w/o overrides

```
##### CONFIGURATION

standard, nothing off the wall
##### OS / ENVIRONMENT

CentOS 7
##### SUMMARY

Output shows `ok` but the task actually failed, very confusing
##### STEPS TO REPRODUCE

```
- name: install some repos
  become: yes
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - epel-release
    - docker-io

- name: Install pip, python-dev package and docker with yum
  become: yes
  yum:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - python-dev
    - python-pip
    - docker

- name: Install pip modules
  become: yes
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version | default(omit) }}"
  with_items:
    - name: docker-py
      version: 1.8.1
    - name: docker-compose

- name: enable docker
  become: yes
  service:
    name: docker
    state: started
    enabled: yes

```
##### EXPECTED RESULTS

I would expect the task to fail, python-dev doesn't exist in centos 7
##### ACTUAL RESULTS

```
ok: [xxx.xxx.xxx.xxx] => (item=[u'python-dev', u'python-pip', u'docker']) => {"changed": false, "failed": true, "invocation": {"module_args": {"conf_file": null, "disable_gpg_check": false, "disablerepo": null, "enablerepo": null, "exclude": null, "install_repoquery": true, "list": null, "name": ["python-dev", "python-pip", "docker"], "state": "latest", "update_cache": false, "validate_certs": true}, "module_name": "yum"}, "item": ["python-dev", "python-pip", "docker"], "msg": "No Package matching 'python-dev' found available, installed or updated", "rc": 0, "results": []}
```

### LINKED ISSUE #4384: yum module not reporting error in Ansible 2.1.1.0
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

yum module
##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.1.1.0

```
##### CONFIGURATION

```
[defaults]
inventory = ~/inventory/production
host_key_checking = False
log_path = ~/ansible.log

retry_files_save_path=~/

[ssh_connection]
pipelining = True
```
##### OS / ENVIRONMENT

Centos 6.8
##### SUMMARY

When an yum install/update error occurs the module does not report an error, but playbooks fails.
##### STEPS TO REPRODUCE

ansible-playbook -sK yum-test.yml

yum-test.yml

```
- name: Test yum module issue
  hosts: host.bla.com

  tasks:

  - name: Install packages
    yum: name={{ item }} state=installed
    with_items:
     - bash
     - non-existing

```
##### EXPECTED RESULTS

with Ansible 1.9.6

```
PLAY [Test yum module issue] ************************************************** 

GATHERING FACTS *************************************************************** 
ok: [host.bla.com]

TASK: [Install both packages] ************************************************* 
failed: [host.bla.com] => (item=bash,non-existing) => {"changed": false, "failed": true, "item": "bash,non-existing", "rc": 0, "results": ["bash-4.1.2-33.el6_7.1.x86_64 providing bash is already installed"]}
msg: No Package matching 'non-existing' found available, installed or updated

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @~/yum-test.retry

host.bla.com      : ok=1    changed=0    unreachable=0    failed=1   
```
##### ACTUAL RESULTS

with Ansible 2.1.1.0

```
PLAY [Test yum module issue] ***************************************************

TASK [setup] *******************************************************************
ok: [host.bla.com]

TASK [Install both packages] ***************************************************
ok: [host.bla.com] => (item=[u'bash', u'non-existing'])

NO MORE HOSTS LEFT *************************************************************
    to retry, use: --limit @~/yum-test.retry

PLAY RECAP *********************************************************************
host.bla.com      : ok=1    changed=0    unreachable=0    failed=1   

```

extra -vvvv

```
PLAYBOOK: yum-test.yml *********************************************************
1 plays in yum-test.yml

PLAY [Test yum module issue] ***************************************************

TASK [setup] *******************************************************************
<host.bla.com> ESTABLISH SSH CONNECTION FOR USER: None
<host.bla.com> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=~/.ansible/cp/ansible-ssh-%h-%p-%r host.bla.com '/bin/sh -c '"'"'sudo -H -S  -p "[sudo via ansible, key=dsjbuxtbnozklzojrujazlvlapqjycat] password: " -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-dsjbuxtbnozklzojrujazlvlapqjycat; LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python'"'"'"'"'"'"'"'"' && sleep 0'"'"''
ok: [host.bla.com]

TASK [Install both packages] ***************************************************
task path: ~/test-playbooks/yum-test.yml:14
<host.bla.com> ESTABLISH SSH CONNECTION FOR USER: None
<host.bla.com> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=~/.ansible/cp/ansible-ssh-%h-%p-%r host.bla.com '/bin/sh -c '"'"'sudo -H -S  -p "[sudo via ansible, key=bvmeagjbdfynwjneknafiyqpjwepjjdu] password: " -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-bvmeagjbdfynwjneknafiyqpjwepjjdu; LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python'"'"'"'"'"'"'"'"' && sleep 0'"'"''
ok: [host.bla.com] => (item=[u'bash', u'non-existing']) => {"changed": false, "failed": true, "invocation": {"module_args": {"conf_file": null, "disable_gpg_check": false, "disablerepo": null, "enablerepo": null, "exclude": null, "install_repoquery": true, "list": null, "name": ["bash", "non-existing"], "state": "installed", "update_cache": false, "validate_certs": true}, "module_name": "yum"}, "item": ["bash", "non-existing"], "msg": "No Package matching 'non-existing' found available, installed or updated", "rc": 0, "results": ["bash-4.1.2-33.el6_7.1.x86_64 providing bash is already installed"]}

NO MORE HOSTS LEFT *************************************************************
    to retry, use: --limit @~/yum-test.retry

PLAY RECAP *********************************************************************
host.bla.com      : ok=1    changed=0    unreachable=0    failed=1   

```

### PR DESCRIPTION
**Pull request by dagwieers**
##### ISSUE TYPE

- Bugfix Pull Request
##### COMPONENT NAME

yum
##### ANSIBLE VERSION

Ansible v2.1.1.0 and earlier
##### SUMMARY

The implementation is fairly simple, we force the rc= parameter to not be zero so that the check in _executor/task_result.py_ correctly determines that it failed. Without this change Ansible would report the task to be ok (despite failed=True and msg=Some_error_message) although Ansible stops and the summary output reports a failed task.

This fixes #4214, #4384, #4981 and also relates to ansible/ansible#12070, ansible/ansible#16006, ansible/ansible##16597, ansible/ansible#17208 and ansible/ansible/pull/17252

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @dagwieers for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by willthames** [comment]
Nice and simple @dagwieers, I like it.

**Comment by dagwieers** [comment]
@gregdek What is needed to get this into Ansible ?

**Comment by gregdek** [comment]
Definitely recommend taking this one directly to the next Ansible Core IRC meeting: https://github.com/ansible/community/blob/master/MEETINGS.md

**Comment by mscherer** [comment]
For the record, this also fix https://github.com/ansible/ansible-modules-core/issues/4981

**Comment by abadger** [comment]
Merged to devel ans stable-2.2

**Pull request merged**
