### PR TITLE
Support tagging ELBs using boto 2.0.

### PR DESCRIPTION
**Pull request by welex91**
Patched ec2_elb_lb as per feedback from @jonhadfield and @Constantin07. I can close https://github.com/ansible/ansible-modules-extras/pull/1454 if the module owner agrees with this approach.

### CODE REVIEW

**Comment by Constantin07** [comment]
Thanks @welex91

**Comment by gregdek** [comment]
Thanks @welex91. @jsdalton @rickmendes please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
Thanks @welex91 for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

**Comment by welex91** [comment]
Fixed merge conflicts, ready_for_review.

**Comment by gregdek** [comment]
Thanks @welex91. @jsdalton @rickmendes please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
Thanks @welex91. @jsdalton @rickmendes please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by welex91** [comment]
@gregdek : anything that I can do to move this along ?

**Comment by gregdek** [comment]
Thanks @welex91 for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

**Comment by welex91** [comment]
ready_for_review   (is a 2 month review cycle normal ? I've already rebased this once as requested).

**Comment by sivel** [comment]
It appears as though the rebase was unsuccessful.  There are now 362 commits in this pull request.

**Comment by welex91** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @welex91. To the current maintainers, @jsdalton, @rickmendes please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by ghost** [comment]
@welex91 Sorry for the delays. Extremely busy time in my day job. Let's shipit

**Comment by gregdek** [comment]
Thanks again to @welex91 for this PR, and thanks @jsdalton, @rickmendes for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by nand0p** [comment]
@welex91 should we add the append_tags option here, as per the discussion in https://github.com/ansible/ansible-modules-core/pull/3163 ?

**Comment by welex91** [comment]
@nand0p : if I understand the discussion in #3163 correctly, your plan is to add boto 3.0 support after rebasing ? Seems like a good time to add the `append_tags` option.

**Comment by nand0p** [comment]
@welex91 sounds like a plan.  hopefully this can get merged soon, and i will rebase and update #3163 accordingly

**Comment by bcoca** [comment]
@welex91 can you fix/squash your commit history?

**Comment by welex91** [comment]
@bcoca I tried, but pulled in some extra commits (no idea how). Is there some way to revert this ?

**Comment by gregdek** [comment]
Thanks @welex91 for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by welex91** [comment]
:ready_for_review: rebased and squashed...

**Comment by gregdek** [comment]
Thanks @welex91. To the current maintainers, @jsdalton, @rickmendes please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request merged**
