### PR TITLE
Change s3 to use connect_to_region

### PR DESCRIPTION
**Pull request by mlaccetti**
- Allows us to use Ansible/s3 for GovCloud when accessing a pre-existing bucket

### CODE REVIEW

**Comment by mlaccetti** [comment]
Related to the original issue to consume the 'region' setting: https://github.com/ansible/ansible/issues/8783

**Comment by mlaccetti** [comment]
Is there any idea as to the ETA on this? Can't really use Ansible in production until this comes in.  :(

**Comment by bcoca** [comment]
I would move the import to the top with the rest, otherwise the change looks good

**Comment by mlaccetti** [comment]
I cloned the way it was done in the rest of the code; I can move the import to the top and remove the redundancy.

**Comment by mlaccetti** [comment]
Okie dokie, cleaned up the imports.

**Pull request merged**
