### PR TITLE
add vlidate_certs option for unarchive module

### PR DESCRIPTION
**Pull request by vmindru**
missing thsis option, needed when fetching file from HTTPS

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @vmindru. @pileofrogs please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by robynbergeron** [comment]
@pileofrogs This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by pileofrogs** [comment]
I'm working on refactoring unarchive into three separate modules. A generic unarchive similar to the one we have now, a tar specific module and a zip specific module. I hope to support many options and also a catchall extra-args type option.

I don't have a lot of time to do it though, so if you want to help work on that, I could use it. Let me know if you're interested.

**Comment by vmindru** [comment]
@pileofrogs  sure i can help , let's nail this down and make the world a better place!

**Comment by gregdek** [comment]
Thanks @vmindru for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

**Comment by vmindru** [comment]
@gregdek  ack will do this tomorrow

**Comment by vmindru** [comment]
this is not ready for review

**Comment by vmindru** [comment]
this is ready for review

**Comment by gregdek** [comment]
Thanks @vmindru. To the current maintainers, @pileofrogs please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by dagwieers** [comment]
Reviewing as the new maintainer. I am looking at the change and I see the option `validate_certs` being added, but I don't see it being used. So this PR cannot work as it is now. Is there some piece of the puzzle missing ?

**Comment by vmindru** [comment]
@dagwieers  this is expected unarchive is calling fetch_url() that "knows" and reacts on this param

**Comment by vmindru** [comment]
unless the argument exists on our FS we asume it's an URL,  if the argument contains '://' which kind of indicates this is an URL we will call fetch_url to do the dirty job 

```
285     # did tar file arrive?
286     if not os.path.exists(src):
287         if copy:
288             module.fail_json(msg="Source '%s' failed to transfer" % src)
289         # If copy=false, and src= contains ://, try and download the file to a temp directory.
290         elif '://' in src:
291             tempdir = os.path.dirname(__file__)
292             package = os.path.join(tempdir, str(src.rsplit('/', 1)[1]))
293             try:
294                 rsp, info = fetch_url(module, src)
295                 # If download fails, raise a proper exception
296                 if rsp is None:
297                     raise Exception(info['msg'])
298                 f = open(package, 'w')
299                 # Read 1kb at a time to save on ram
300                 while True:
301                     data = rsp.read(BUFSIZE)
302 
303                     if data == "":
304                         break # End of file, break while loop
305 
306                     f.write(data)
307                 f.close()
308                 src = package

```

**Comment by vmindru** [comment]
the let's go to lib/ansible/module_utils/urls.py as suggested by the import at the bottom 

```
811 def fetch_url(module, url, data=None, headers=None, method=None,
812               use_proxy=True, force=False, last_mod_time=None, timeout=10):
813     '''
814     Fetches a file from an HTTP/FTP server using urllib2.  Requires the module environment
815     '''
816 
817     if not HAS_URLLIB2:
818         module.fail_json(msg='urllib2 is not installed')
819     elif not HAS_URLPARSE:
820         module.fail_json(msg='urlparse is not installed')
821 
822     # Get validate_certs from the module params
823     validate_certs = module.params.get('validate_certs', True)
824 
825     username = module.params.get('url_username', '')
826     password = module.params.get('url_password', '')
827     http_agent = module.params.get('http_agent', None)
828     force_basic_auth = module.params.get('force_basic_auth', '')
829 
830     follow_redirects = module.params.get('follow_redirects', 'urllib2')
831 
832     r = None
833     info = dict(url=url)
834     try:
835         r = open_url(url, data=data, headers=headers, method=method,
836                      use_proxy=use_proxy, force=force, last_mod_time=last_mod_time, timeout=timeout,
837                      validate_certs=validate_certs, url_username=username,
838                      url_password=password, http_agent=http_agent, force_basic_auth=force_basic_auth,
839                      follow_redirects=follow_redirects)
840         info.update(r.info())
841         info['url'] = r.geturl()  # The URL goes in too, because of redirects.
842         info.update(dict(msg="OK (%s bytes)" % r.headers.get('Content-Length', 'unknown'), status=200))
843     except NoSSLError, e:
844         distribution = get_distribution()
845         if distribution.lower() == 'redhat':
846             module.fail_json(msg='%s. You can also install python-ssl from EPEL' % str(e))
847         else:
848             module.fail_json(msg='%s' % str(e))
849     except (ConnectionError, ValueError), e:
850         module.fail_json(msg=str(e))
851     except urllib2.HTTPError, e:
852         info.update(dict(msg=str(e), status=e.code, **e.info()))
853     except urllib2.URLError, e:
854         code = int(getattr(e, 'code', -1))
855         info.update(dict(msg="Request failed: %s" % str(e), status=code))
856     except socket.error, e:
857         info.update(dict(msg="Connection failure: %s" % str(e), status=-1))
858     except Exception, e:
859         info.update(dict(msg="An unknown error occurred: %s" % str(e), status=-1))
860 
861     return r, info
```

then  observe

```
835         r = open_url(url, data=data, headers=headers, method=method,
836                      use_proxy=use_proxy, force=force, last_mod_time=last_mod_time, timeout=timeout,
837                      validate_certs=validate_certs, url_username=username,

```

**Comment by vmindru** [comment]
and finally :) if  we have this  we will amend ssl handler 

```
653 def maybe_add_ssl_handler(url, validate_certs):
654     # FIXME: change the following to use the generic_urlparse function
655     #        to remove the indexed references for 'parsed'
656     parsed = urlparse.urlparse(url)
657     if parsed[0] == 'https' and validate_certs:
658         if not HAS_SSL:
659             raise NoSSLError('SSL validation is not available in your version of python. You can use validate_certs=False, however this is unsafe and not recommended')
660 
661         # do the cert validation
662         netloc = parsed[1]
663         if '@' in netloc:
664             netloc = netloc.split('@', 1)[1]
665         if ':' in netloc:
666             hostname, port = netloc.split(':', 1)
667             port = int(port)
668         else:
669             hostname = netloc
670             port = 443
671         # create the SSL validation handler and
672         # add it to the list of handlers
673         return SSLValidationHandler(hostname, port)
```

**Comment by vmindru** [comment]
does all of this make sens ?)

**Comment by dagwieers** [comment]
@vmindru You're right, I wasn't expecting fetch_url() to go and look for module parameters. Interesting and scary at the same time. Especially because e.g. we plan to use password for encrypted archives, but it may have an impact on fetch_url...

**Comment by vmindru** [comment]
tell me about :)

**Comment by vmindru** [comment]
@dagwieers  - thanks for the review, can we pass this further?

**Comment by dagwieers** [comment]
So while I have my reservations:
1. on the use of module parameters in fetch_url()
   (with potential clashes of used parameters)
2. to the fact that the unarchive module has URL fetching functionality
   (why not simply do 2 tasks, and keep the modules more simple ?)

I cannot break with decisions made by people before me :-)
So if the two items listed above are a given, I guess we can add this to the module.
(And what about the other fetch_url() options (e.g. username, password, http_agent, force_basic_auth, follow_redirects) ?)

@bcoca @jimi-c @abadger @gregdek Is it common practice to put common functionality from other modules into modules ? Do we have guidelines wrt. this ?

**Comment by dagwieers** [comment]
shipit

**Comment by gregdek** [comment]
Thanks again to @vmindru for this PR, and thanks @dagwieers, @pileofrogs for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by vmindru** [comment]
@dagwieers  

> (And what about the other fetch_url() options (e.g. username, password, http_agent, force_basic_auth, follow_redirects) ?)

uhm , I don't know would have to check how other modules have implemented this. Brainstorming is welcomed.

**Comment by dagwieers** [comment]
@vmindru Don't worry, this was not a question to you directly. I am just wondering, if a module is adding its own download functionality, how much of the functionality (of `fetch_url()`) do we want to support. All these options are implemented exactly as `validate_certs()`, but should we leave this up to specialized modules, are should every module be full-featured in downloading...

**Comment by resmo** [comment]
could you please squash the commits and remove the conflict headers in it?

**Comment by vmindru** [comment]
@rasmo - squashed, what do you mean about "conflict headers" ?

**Comment by vmindru** [comment]
@rasmo is this still valid request ?

**Comment by gregdek** [comment]
Thanks @vmindru for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by vmindru** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @vmindru. To the current maintainers, @dagwieers, @pileofrogs please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by dagwieers** [comment]
Was already reviewed. Fine for me. I only wonder why it is not ready for v2.1 instead ?

shipit

**Comment by vmindru** [comment]
@dagwieers  - travis failed with version 2.1 for some reason.

**Comment by vmindru** [comment]
https://travis-ci.org/ansible/ansible-modules-core/builds/127737511 

the error  was:

ERROR: version_added for new option (validate_certs) should be 2.2. Currently 2.1

**Comment by dagwieers** [comment]
Oh ok, I didn't know we were enforcing this. Makes sense.
This means no functionality can be added for v2.1 anymore ?

**Comment by resmo** [comment]
Travis makes a simple check for every new param added. Usually a new param corresponds with a new feature and new feature won't be backported. That is why travis fails if you add a version_added not equal current dev version. IMHO it is safe to backport it to 2.1.

Please get rid of the second commit and ignore travis. I'll cherry-pick it to 2.1.

**Comment by vmindru** [comment]
yo @resmo thanks , done.

**Comment by gregdek** [comment]
Thanks @vmindru for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by resmo** [comment]
Sorry to say I changed my mind. won't merge it to 2.1 anymore. Please add version_added 2.2 again. It's a freeze and bug fixes only. Thanks for your understanding.

**Comment by vmindru** [comment]
ready_for_review

**Pull request merged**
