### PR TITLE
Docker module: add wait parameter

### PR DESCRIPTION
**Pull request by lorin**
Add a `wait` parameter to the _docker_ module.

When this parameter is specified, when starting or restarting a container, the module will block until the container has stopped. If the return value of the process is non-zero, the module will fail, using the process's output as the error message.

Example use case: initializing a database or running a database migration inside of a container. This task must complete before going to the next task in the playbook, and if it fails you need a meaningful error message.

### CODE REVIEW

**Comment by vgrossmann** [comment]
+1

**Comment by mikz** [comment]
:+1:

**Comment by AdamCmiel** [comment]
+1

**Comment by gregdek** [comment]
@lorin if this still applies, please rebase and we will get it into the community review process asap.

**Comment by anthcourtney** [comment]
+1

**Comment by lorin** [comment]
@gregdek this has been obsoleted by #1031, which just got merged.

**Pull request closed without merging**
