### PR TITLE
verify both tags and commits

### PR DESCRIPTION
**Pull request by pixelrebel**
This fixes a bug where the module fails to verify tags.  I added a conditional statement in `verify_commit_sign()` that checks if `version` argument is a tag, if so, use `git verify-tag` instead.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @pixelrebel for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

**Comment by pixelrebel** [comment]
Thanks @gregdek.  If you were a betting man, would you bet on this making it into the 2.0.0 release?

**Comment by pixelrebel** [comment]
Any chance of getting this merged soon?

**Comment by ajstuart** [comment]
+1

**Comment by robinro** [comment]
@pixelrebel Could you add an integration test to prevent future regressions?

See https://github.com/ansible/ansible/blob/devel/test/integration/roles/test_git/tasks/main.yml
(be careful when you run the tests, test_git currently messes with your known_hosts files)

**Comment by pixelrebel** [comment]
@robinro Suggestions on how to code a good test for this?  It would require a GPG truststore setup on the test server.

**Comment by robinro** [comment]
@pixelrebel 
gpg should be available in the test environment, so you can import a key. Just do some `command` before the actual git call.

Maybe one can do some funny trick with the `apt_key` module and use their keyring? But that's more of a hack than one gpg command.

**Comment by pixelrebel** [comment]
@robinro 

Does the test environment have gpg v2.1.0+?  That's the minimum required version for verifying signatures.

**Comment by pixelrebel** [comment]
@robinro Here's your PR for test: https://github.com/ansible/ansible/pull/15551

Requires gpg v2.1.0

**Comment by pixelrebel** [comment]
@ansible How about we try to get this merged within a year of the initial PR?  I'd like to contribute more, but this is painful.

**Comment by pixelrebel** [comment]
@robinro bump

**Comment by robinro** [comment]
Thanks @pixelrebel for the PR. Thanks @abadger for the merge.

**Comment by pixelrebel** [comment]
@robinro Thanks very much for helping me through the CI tests.
@abadger Awesome!  I'm stoked!  Thanks for the merge!

**Comment by abadger** [comment]
Cool.  I'm rebasing the tests and applying them now.  If they pass I'll take a look at cherry-picking into the stable-2.2 branch as well.

**Comment by ageis** [comment]
+1 can't wait to see this in 2.2

**Pull request merged**
