### PR TITLE
Speedup git module on clone and pull

### PR DESCRIPTION
**Pull request by robinro**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

source_control/git.py
##### ANSIBLE VERSION

devel
##### SUMMARY

This is based on the discussion in https://github.com/ansible/ansible-modules-core/issues/149 and https://github.com/ansible/ansible/issues/14501.

The git module does an unnecessary amount of communication with the git server on clone and pull. At least in trivial cases the data going over the network should be kept minimal. This PR reduces the number of calls to ls-remote for standard cases. It brings clone and pull very close to the raw git timings when cloning a repo without any arguments specified.
##### Example Playbook

```
- hosts: localhost
  tasks:
    - name: ensure target is empty
      file: name=/tmp/ansible.git state=absent

    - name: SHELL clone repo
      shell: git clone https://github.com/ansible/ansible-modules-core /tmp/ansible.git

    - name: SHELL pull repo
      shell: 
        cmd: git fetch --tags && git reset --hard origin/HEAD
        chdir: /tmp/ansible.git

    - name: ensure target is empty
      file: name=/tmp/ansible.git state=absent

    - name: MODULE clone repo
      git:
        repo: https://github.com/ansible/ansible-modules-core
        dest: /tmp/ansible.git

    - name: MODULE pull repo
      git:
        repo: https://github.com/ansible/ansible-modules-core
        dest: /tmp/ansible.git

    - name: ensure target is empty
      file: name=/tmp/ansible.git state=absent

    - name: MODULE-VERSION clone repo
      git:
        repo: https://github.com/ansible/ansible-modules-core
        dest: /tmp/ansible.git
        version: devel

    - name: MODULE-VERSION pull repo
      git:
        repo: https://github.com/ansible/ansible-modules-core
        dest: /tmp/ansible.git
        version: devel
```
##### Output before:

```
MODULE-VERSION clone repo ----------------------------------------------- 4.21s
MODULE clone repo ------------------------------------------------------- 4.36s
SHELL clone repo -------------------------------------------------------- 2.56s
MODULE-VERSION pull repo ------------------------------------------------ 5.49s
MODULE pull repo -------------------------------------------------------- 1.10s
SHELL pull repo --------------------------------------------------------- 1.01s
```
##### Output after:

```
MODULE-VERSION clone repo ----------------------------------------------- 3.23s
MODULE clone repo ------------------------------------------------------- 2.72s
SHELL clone repo -------------------------------------------------------- 2.49s
MODULE-VERSION pull repo ------------------------------------------------ 1.88s
MODULE pull repo -------------------------------------------------------- 1.05s
SHELL pull repo --------------------------------------------------------- 1.04s
```

### CODE REVIEW

**Comment by robinro** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @robinro for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by robinro** [comment]
@jctanner Can you review this PR? You were involved in the discussions around #149.

**Comment by gundalow** [comment]
Added to the 2.2 gDoc review list

**Comment by alikins** [comment]
Had an oddity happen while testing... I'm 99% sure this was a github hiccup, but I'll include the results for reference.

Running the example playbook took ~30mins and failed on 'SHELL checkout'

```
[fedora-23:ansible (devel % u=)]$ ansible-playbook repro/git_module_speed_4562/git.yml 

PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
Monday 12 September 2016  10:16:25 -0400 (0:00:00.006)       0:00:00.006 ****** 
ok: [localhost]

TASK [ensure target is empty] **************************************************
Monday 12 September 2016  10:16:26 -0400 (0:00:00.478)       0:00:00.484 ****** 
ok: [localhost]

TASK [SHELL clone repo] ********************************************************
Monday 12 September 2016  10:16:26 -0400 (0:00:00.219)       0:00:00.704 ****** 


fatal: [localhost]: FAILED! => {"changed": true, "cmd": "git clone https://github.com/ansible/ansible-modules-core /tmp/ansible.git", "delta": "0:27:52.286479", "end": "2016-09-12 10:44:18.967384", "failed": true, "rc": 128, "start": "2016-09-12 10:16:26.680905", "stderr": "Cloning into '/tmp/ansible.git'...\nerror: RPC failed; result=18, HTTP code = 200\nfatal: The remote end hung up unexpectedly\nfatal: early EOF\nfatal: index-pack failed", "stdout": "", "stdout_lines": [], "warnings": []}
    to retry, use: --limit @repro/git_module_speed_4562/git.retry

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1   

Monday 12 September 2016  10:44:18 -0400 (0:27:52.508)       0:27:53.213 ****** 
=============================================================================== 
SHELL clone repo ----------------------------------------------------- 1672.51s
setup ------------------------------------------------------------------- 0.48s
ensure target is empty -------------------------------------------------- 0.22s
```

**Comment by alikins** [comment]
A few example runs of old version new using the example playbook:

```
Monday 12 September 2016  11:40:32 -0400 (0:00:07.911)       0:00:39.340 ****** 
=============================================================================== 
MODULE-VERSION clone repo ---------------------------------------------- 15.51s
MODULE-VERSION pull repo ------------------------------------------------ 7.91s
MODULE clone repo ------------------------------------------------------- 6.32s
SHELL clone repo -------------------------------------------------------- 4.01s
MODULE pull repo -------------------------------------------------------- 3.80s
SHELL pull repo --------------------------------------------------------- 0.64s
setup ------------------------------------------------------------------- 0.61s
ensure target is empty -------------------------------------------------- 0.23s
ensure target is empty -------------------------------------------------- 0.15s
ensure target is empty -------------------------------------------------- 0.14s


Monday 12 September 2016  11:41:39 -0400 (0:00:04.168)       0:00:31.720 ****** 
=============================================================================== 
MODULE clone repo ------------------------------------------------------- 9.98s
SHELL clone repo -------------------------------------------------------- 7.72s
MODULE-VERSION clone repo ----------------------------------------------- 6.13s
MODULE-VERSION pull repo ------------------------------------------------ 4.17s
SHELL pull repo --------------------------------------------------------- 1.97s
MODULE pull repo -------------------------------------------------------- 0.69s
setup ------------------------------------------------------------------- 0.56s
ensure target is empty -------------------------------------------------- 0.22s
ensure target is empty -------------------------------------------------- 0.14s
ensure target is empty -------------------------------------------------- 0.13s


Monday 12 September 2016  11:42:54 -0400 (0:00:04.913)       0:00:28.121 ****** 
=============================================================================== 
MODULE-VERSION clone repo ----------------------------------------------- 8.37s
SHELL clone repo -------------------------------------------------------- 5.97s
MODULE clone repo ------------------------------------------------------- 5.48s
MODULE-VERSION pull repo ------------------------------------------------ 4.91s
SHELL pull repo --------------------------------------------------------- 1.04s
MODULE pull repo -------------------------------------------------------- 1.00s
setup ------------------------------------------------------------------- 0.81s
ensure target is empty -------------------------------------------------- 0.22s
ensure target is empty -------------------------------------------------- 0.16s
ensure target is empty -------------------------------------------------- 0.14s

Monday 12 September 2016  11:43:54 -0400 (0:00:04.971)       0:00:33.683 ****** 
=============================================================================== 
MODULE clone repo ------------------------------------------------------- 9.85s
MODULE-VERSION clone repo ----------------------------------------------- 8.12s
SHELL clone repo -------------------------------------------------------- 7.73s
MODULE-VERSION pull repo ------------------------------------------------ 4.97s
MODULE pull repo -------------------------------------------------------- 1.20s
SHELL pull repo --------------------------------------------------------- 0.80s
setup ------------------------------------------------------------------- 0.47s
ensure target is empty -------------------------------------------------- 0.25s
ensure target is empty -------------------------------------------------- 0.14s
ensure target is empty -------------------------------------------------- 0.14s
```

And with the new version:

```
Monday 12 September 2016  11:47:36 -0400 (0:00:01.049)       0:00:23.053 ****** 
=============================================================================== 
SHELL clone repo -------------------------------------------------------- 7.01s
MODULE-VERSION clone repo ----------------------------------------------- 6.12s
MODULE clone repo ------------------------------------------------------- 5.73s
MODULE-VERSION pull repo ------------------------------------------------ 1.05s
SHELL pull repo --------------------------------------------------------- 1.04s
setup ------------------------------------------------------------------- 0.82s
MODULE pull repo -------------------------------------------------------- 0.77s
ensure target is empty -------------------------------------------------- 0.23s
ensure target is empty -------------------------------------------------- 0.14s
ensure target is empty -------------------------------------------------- 0.13s

Monday 12 September 2016  11:48:11 -0400 (0:00:05.910)       0:00:22.932 ****** 
=============================================================================== 
MODULE-VERSION clone repo ----------------------------------------------- 6.46s
MODULE-VERSION pull repo ------------------------------------------------ 5.91s
SHELL clone repo -------------------------------------------------------- 4.28s
MODULE clone repo ------------------------------------------------------- 3.84s
SHELL pull repo --------------------------------------------------------- 0.68s
MODULE pull repo -------------------------------------------------------- 0.67s
setup ------------------------------------------------------------------- 0.58s
ensure target is empty -------------------------------------------------- 0.23s
ensure target is empty -------------------------------------------------- 0.14s
ensure target is empty -------------------------------------------------- 0.14s

Monday 12 September 2016  11:49:26 -0400 (0:00:01.327)       0:00:24.266 ****** 
=============================================================================== 
SHELL clone repo -------------------------------------------------------- 6.36s
MODULE clone repo ------------------------------------------------------- 6.27s
MODULE-VERSION clone repo ----------------------------------------------- 6.18s
SHELL pull repo --------------------------------------------------------- 1.95s
MODULE-VERSION pull repo ------------------------------------------------ 1.33s
MODULE pull repo -------------------------------------------------------- 1.10s
setup ------------------------------------------------------------------- 0.57s
ensure target is empty -------------------------------------------------- 0.23s
ensure target is empty -------------------------------------------------- 0.13s
ensure target is empty -------------------------------------------------- 0.13s
```

**Comment by robinro** [comment]
Thanks @alikins for testing this. I agree that the first error is most likely some github/network hickup.

I ran the playbook several times to get warm caches and then took a typical result out of several runs. Network timings of production systems vary a lot. Especially with flaky network reducing the number of network transactions (i.e. this PR) helps.
One could do a more sophisticated benchmark, but the improvement imo is pretty visible. The runtime reduction is great especially for MODULE-VERSION pull, which is probably also the most-run case.

**Comment by alikins** [comment]
Code looks good to me, and seems to work and speed things up. The existing 'test_git' integration test works with it. 

Merging...

**Comment by robinro** [comment]
Thanks @alikins

**Comment by jctanner** [comment]
@robinro just wanted to give a delayed thank you for this one.

**Pull request merged**
