### PR TITLE
allow for sshpass support for `synchronize`

### PR DESCRIPTION
**Pull request by ritzk**
Needs - https://github.com/ansible/ansible/pull/12704 .Also has more detailed info
- add sshpass support to sync module

### CODE REVIEW

**Comment by robynbergeron** [comment]
Hi @ritzk -- thanks for submitting this PR!

@tima -- Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by robynbergeron** [comment]
Also: Not sure what is up with this one and #2247 -- trying to sort it out by reading #1755 but not getting very far just yet.  If @elvis-macak @ritzk @tima and others can just make sure to indicate if anything needs closing in favor of other PRs, that would be great! :) Thanks, everyone.

**Comment by ritzk** [comment]
Hi @robynbergeron 

@elvis-macak posted https://github.com/ansible/ansible-modules-core/pull/2247 , this uses sshpass to read from pipe .

An update over https://github.com/ansible/ansible-modules-core/issues/1755 , where password was passed as command line ( which could allow anyone logged in to see this via "ps aux") . Not sure why, a new ticket was opened.

## 

https://github.com/ansible/ansible-modules-core/pull/2244 commit allows synchronize module to use sshpass via environment variable, as I could not ensure sshpass to work with pipe ( I could be wrong). 

This patch works in conjunction with https://github.com/ansible/ansible/pull/12704 .

**Comment by tima** [comment]
Can we please close this one to consolidate all efforts to resolve this thru #2247. Submitting a competing PR like this to what @elvis-macak has been leading is complicating matters and is making it harder to come to some sort of consensus.

**Comment by ritzk** [comment]
@tima both of us are using a different approach. I am using env variable, and @elvis-macak is using fd pipe ( which is not working for me)

**Comment by tima** [comment]
@ritzk I am well aware you are using a different approach and I'm saying I don't like it. I don't think any of the current solutions are acceptable, just 'less bad' than the others. Please close this PR and let's work this thru with what @elvis-macak started.

**Comment by bcoca** [comment]
closing in favor of feature request https://github.com/ansible/ansible/issues/13099

**Pull request closed without merging**
