### PR TITLE
Fixes #4795 - Validate filename portion of `cron_file`

### LINKED ISSUE #4795: Verify that cron_file argument is valid.
##### ISSUE TYPE

- Feature Idea
##### COMPONENT NAME

cron
##### ANSIBLE VERSION

```
ansible 2.0.0.2
  config file =
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

Ubuntu
##### SUMMARY

Cron will only read cron-files without . (dots) in them, particularly 
`[The filenames] must consist solely of upper- and lower-case letters, digits, underscores, and hyphens. This means that they cannot contain any dots.` 
It would be nice if
1) The cron-module gave a warning if the user ran cron_file with an illegal filename, and 
2) this were mentioned in the documentation of the cron-module, and
3) the cron-module had a "sanitise" option which would replace dots with some optional character. 

Point 1 is the most important, it will save others from the going through the same debugging as we had to ;-) 
##### STEPS TO REPRODUCE

```

```

##### ACTUAL RESULTS

```

```

### PR DESCRIPTION
**Pull request by EvanK**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

`cron` module
##### ANSIBLE VERSION

```
ansible 2.1.2.0
```
##### SUMMARY

Validates the filename portion of `cron_file` param (as some linux distros restrict what it can contain), and returns a warning if said validation fails. Also updates docs accordingly.

```
$ sudo ansible localhost -m cron -a "job=/bin/false user=deploy cron_file='.warnings-test'"

localhost | SUCCESS => {
    "changed": true, 
    "cron_file": ".warnings-test", 
    "envs": [], 
    "jobs": [
        "None"
    ], 
    "warnings": [
        "cron_file \".warnings-test\" must consist solely of upper- and lower-case letters, digits, underscores, and hyphens"
    ]
}
 [WARNING]: cron_file ".warnings-test" must consist solely of upper- and lower-case letters, digits, underscores, and hyphens
```

Fixes #4795

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @EvanK for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by EvanK** [comment]
CI failure is due to a broken version check in `devel`. I'll merge upstream once it's fixed

**Comment by EvanK** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @EvanK. To the current maintainers, @dsummersl, @EvanK please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by EvanK** [comment]
shipit

**Comment by gregdek** [comment]
Thanks @EvanK. Since you are one of the maintainers (@dsummersl, @EvanK) of this module and you commented with "shipit", we are marking this PR for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
