### PR TITLE
added rsync protocol support

### PR DESCRIPTION
**Pull request by hyeonseongc**
sometimes, I would like to use rsync protocol to synchronize files
so just a first concept I added rsync protocol support
my major idea is that I'd like to send a command to inventory host to pull files from some other 
host that running rsync daemon.
it can be done with delegate_to options using this code.
I'm not quite sure that this approch is right
so, please review and give me an advice
thanks.
work with ansible/ansible#12197

### CODE REVIEW

**Comment by gregdek** [comment]
@tima Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by tima** [comment]
@peter-jang: Thanks for the submission. For my own understanding, can you explain why the rsync protocol can't be used between an inventory_hostname and delegate_to hosts?

**Comment by hyeonseongc** [comment]
@tima  thanks for comment. 
my bad.. I tested code again today, there's no problem either push or pull.
pushing files from delegate hosts to other hosts can be used.
I might be confused.

**Comment by gregdek** [comment]
Thanks @peter-jang for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

**Comment by hyeonseongc** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @peter-jang. @tima please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
Thanks @peter-jang. @tima please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by hyeonseongc** [comment]
thank you for your advice @tima 
I've pushed new commit

**Comment by tima** [comment]
Thanks @peter-jang. Looks good to me. @abadger?

**Comment by gregdek** [comment]
Since @tima is maintainer, interpreting his "looks good" as a "shipit". Thanks @tima for review, and thanks to @peter-jang for submitting the PR.

**Comment by tima** [comment]
Yes. I suppose I should have said that @gregdek. I was hoping @abadger would take a quick look also since he's been doing so much work in there.

**Comment by hyeonseongc** [comment]
Thank you.
FYI, ansible/ansible#12197 is also need to ship for this work properly.

**Comment by gregdek** [comment]
We don't really have a clear process for ansible/ansible dependent PRs -- so hoping that the core team does the right thing here when it comes time to merge. :)

**Comment by tima** [comment]
@gregdek Right. Modules and their associated action plugin when applicable should live together in the same repo wherever that is but that's a whole discussion.

**Pull request merged**
