### PR TITLE
Elasticache Module: cache engine choices

### PR DESCRIPTION
**Pull request by noqcks**
Here I am adding a choice of either elasticache or redis to use as a cache engine.

### CODE REVIEW

**Comment by noqcks** [comment]
@jsdalton plz review

**Comment by robynbergeron** [comment]
Thanks @noqcks. @jsdalton please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by jsdalton** [comment]
looks fine shipit

On Mon, Jan 4, 2016 at 3:30 AM, Robyn Bergeron notifications@github.com
wrote:

> Thanks @noqcks https://github.com/noqcks. @jsdalton
> https://github.com/jsdalton please review according to guidelines (
> http://docs.ansible.com/ansible/developing_modules.html#module-checklist)
> and comment with text 'shipit' or 'needs_revision' as appropriate.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ansible/ansible-modules-core/pull/2734#issuecomment-168652405
> .

## 

Sincerely,

Jim Dalton
jim.dalton@gmail.com

**Comment by gregdek** [comment]
Thanks again to @noqcks for this PR, and thanks @jsdalton for reviewing. Marking for inclusion.

**Comment by bcoca** [comment]
please flatten the commits and add to the description that these choices are only available starting at Ansible 2.1 and describe the previous behavior.

**Comment by noqcks** [comment]
@bcoca These two choices were always available, it just wasn't immediately clear. You could always use either `redis` or `memcached`, but it was not apparent by the documentation. 

I _believe_ I've squashed my commits, however this is one of my first pull-requests on an open-source repo, so im not exactly sure.

**Comment by bcoca** [comment]
ah, i see, it was freeform before but there were really no other choices?

**Comment by noqcks** [comment]
Yep, exactly. There were always only two options (redis or memcached). You can see that [in these lines](https://github.com/noqcks/ansible-modules-core/blob/elasticache-engine-choices/cloud/amazon/elasticache.py#L438-L443).

**Pull request merged**
