### PR TITLE
Created do_floating_ip module

### PR DESCRIPTION
**Pull request by pmarques**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

cloud/digital_ocean/do_floating_ip
cloud/digital_ocean/do_floating_ip_facts
##### SUMMARY

Add support for create delete and assign Digital Ocean Floating IPs to a droplet.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @pmarques for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by harneksidhu** [comment]
What is the purpose of do_floating_ip_facts? Is it just to get a list of floating ips? What use case does it serve if that is the case?

**Comment by pmarques** [comment]
I first implemented it because It was nice to check after run some tasks, but it can be useful for list all the floating IPS and verified if the one that exists is there (digital ocean don't support "unique IDs" / tags for floating IPS :( )

**Comment by harneksidhu** [comment]
Thanks for explaining that. I see there are similar _facts modules for the other cloud providers in Ansible. 

I think you can verify a floating IP by iterating through all IPS on the account? https://developers.digitalocean.com/documentation/v2/#list-all-floating-ips

I'm making some changes to the Response and Rest classes and will submit a new PR so once that is done, you can copy that and make the change to this PR.

**Comment by pmarques** [comment]
I got the name *_facts from the development documentation, [conventions & recommendations](http://docs.ansible.com/ansible/developing_modules.html#conventions-recommendations).
When you say a generic _do_facts_ what you do have in mind? Get all droplets, Floating IPs, etc? or just a generic module where you specify the type of facts you want? Since digital ocean modules are being refactored, #4219, this can be more clear after that.

Verify a floating IP from a list is not so straight forward, for instance:
- Run a task to create a Floating IP
- Use some IP failover software to assign IP to a droplet

You can run a task that make sure the Floating IP is "present", what happens if the Floating IP is not assigned to a droplet? The Floating IP can / should have a tight relation with a DNS record and I'm not sure if this is the way :/ maybe @andrewsomething can help on that

**Comment by harneksidhu** [comment]
I worked on a floating ip module a few months ago for personal use. I was able to verify that a floating ip is assigned to a droplet by polling the action code.

https://github.com/harneksidhu/ansible-digitalocean/blob/master/digital_ocean_floating_ip.py#L168

When you assign a floating ip to a droplet, you should be returned an action id. This action id should then be polled until it is complete which indicates that the floating ip is assigned. 

That example I sent was written without fetch_url() but it is still possible. You would just have to do it manually.

**Comment by pmarques** [comment]
That is the "easy" case :) I left a todo to "wait" for the Floating IP assignment. But I still see a edge case where the Floating IP is not assigned to anyone.
Correct me if I'm wrong, but if I delete a droplet with a Floating IP it will be released and stay free. Hence I can't find automatically its purpose to reassign. Note that this a edge case or something that the user can wrongly assume and so we need to advert him.

As soon as I have some spare time I will add the "wait" for Floating IP assignment.

**Comment by andrewsomething** [comment]
For Floating IPs, the IP address itself is the unique ID. Querying the API will verify it's existence and whether it is assigned to a Droplet: https://developers.digitalocean.com/documentation/v2/#retrieve-an-existing-floating-ip

I might not totally be understanding question, but I think we should focus on uses cases. If the IP is being reassigned via some separate failover software outside of Ansible, I'd think your playbook should just ensure that the Floating IP exists and allow the failover software to handle the initial assignment.

**Comment by gregdek** [comment]
@pmarques A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by pmarques** [comment]
@andrewsomething I have updated the code create and Floating IP or make sure that one Floating IP is associated to one droplet in a list of droplets. I think this is ready_for_review and I appreciate any comment to this module. I'm already using it in my pipelines.

**Comment by gregdek** [comment]
Thanks @pmarques for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by pmarques** [comment]
This PR already needs_rebase 😞

**Comment by harneksidhu** [comment]
@pmarques 
If you are struggling with rebase, this is a good gist I use to perform it. https://gist.github.com/MohammadYounes/be44789c92465768d701

**Comment by pmarques** [comment]
@harneksidhu thanks but I don't have problems with the rebase, I just need to be sure that don't break anything from someone and I think that it will be more clean to do one rebase before merge

**Pull request closed without merging**
