### PR TITLE
Add ignore_errors attribute to cloudformation

### PR DESCRIPTION
**Pull request by jamesloh**
When deleting a non-existent stack, playbook fails. Setting ignore_errors: yes will enable playbook to continue.

### CODE REVIEW

**Comment by bcoca** [comment]
we already have ignore_errors at task level, there should be no need to add this to the module itself

**Comment by jamesloh** [comment]
Dear Brian:

I wasn't able to do the following without the patch. Consequently, it fails
when the stack is truly absent. Is there a way around this?
- name: tear down old deployment
  cloudformation:
    ignore_errors: yes
    stack_name: "{{ stack_name }}"
    state: "absent"
    region: "{{vpc_region}}"
    template: "{{ output_cfn_json }}"

Regards,
James Loh

On Wed, Jul 15, 2015 at 11:56 PM, Brian Coca notifications@github.com
wrote:

> we already have ignore_errors at task level, there should be no need to
> add this to the module itself
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ansible/ansible-modules-core/pull/1732#issuecomment-121623701
> .

## 

Regards,

James Loh

**Comment by bcoca** [comment]
so that looks all kinds of wrong, you are mixing tag level directives with
module options, these last ones need to be indented under the module:

```
- name: tear down old deployment
  cloudformation:
      stack_name: "{{ stack_name }}"
      state: "absent"
      region: "{{vpc_region}}"
      template: "{{ output_cfn_json }}"
  ignore_errors: yes
```

**Comment by jamesloh** [comment]
Thanks, Brian. When I unindented ignore_errors, it worked.

Now I understand how much indentation matters in Ansible.

Regards,
James Loh

On Thu, Jul 16, 2015 at 1:07 PM, Brian Coca notifications@github.com
wrote:

> so that looks all kinds of wrong, you are mixing tag level directives with
> module options, these last ones need to be indented under the module:
> - name: tear down old deployment
>   cloudformation:
>   stack_name: "{{ stack_name }}"
>   state: "absent"
>   region: "{{vpc_region}}"
>   template: "{{ output_cfn_json }}"
>   ignore_errors: yes
> 
> On Wed, Jul 15, 2015 at 7:08 PM, James Loh notifications@github.com
> wrote:
> 
> > Dear Brian:
> > 
> > I wasn't able to do the following without the patch. Consequently, it
> > fails
> > when the stack is truly absent. Is there a way around this?
> > - name: tear down old deployment
> >   cloudformation:
> >   ignore_errors: yes
> >   stack_name: "{{ stack_name }}"
> >   state: "absent"
> >   region: "{{vpc_region}}"
> >   template: "{{ output_cfn_json }}"
> > 
> > Regards,
> > James Loh
> > 
> > On Wed, Jul 15, 2015 at 11:56 PM, Brian Coca notifications@github.com
> > wrote:
> > 
> > > we already have ignore_errors at task level, there should be no need to
> > > add this to the module itself
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > 
> > https://github.com/ansible/ansible-modules-core/pull/1732#issuecomment-121623701
> > 
> > > .
> > 
> > ## 
> > 
> > Regards,
> > 
> > James Loh
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/ansible/ansible-modules-core/pull/1732#issuecomment-121773085
> > 
> > .
> 
> ## 
> 
> Brian Coca
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ansible/ansible-modules-core/pull/1732#issuecomment-121811768
> .

## 

Regards,

James Loh

**Comment by bcoca** [comment]
closing this as it was a misunderstanding

**Pull request closed without merging**
