### PR TITLE
fix authorized_keys in check_mode

### PR DESCRIPTION
**Pull request by verm666**
This change is in response to issue #1515.

The original problem is: in authorized_key module you have no idea about users
which will be created by Ansible at first run. I can propose next two ways to
solve this problem:
1. Combine modules system/user.py and system/authorized_key.py in one module
    (so you will know everything about users in that module)
2. Use small workaround: add my commit and always provide 'path' parameter
    for authorized_key module during runs with --check option (in case of simplicity of Ansible it's looks not really bad).

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @verm666!

@bradobro can you review this patch? If you give it a +1 we will tag as "P1_reviewed" for quicker inclusion.

**Comment by abadger** [comment]
I think this is probably the best workaround for now.  @verm666 could you add a documentation note in the modules' description  that path is necessary if check mode is used and the user doesn't exist yet?

Other than that, the code itself looks fine.

**Comment by bcoca** [comment]
seems like an extra commit to apt_repository snuck in here, please fix

**Comment by verm666** [comment]
@bcoca, who should remove extra commit? If it's I - what is the best way to do this?

**Comment by gregdek** [comment]
It should just be a rebase, right? If you rebase your repo and then push, the PR should automatically update.

**Comment by abadger** [comment]
Yeah, rebase interactive should let you do this:

https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#Changing-Multiple-Commit-Messages

**Comment by verm666** [comment]
Can I just recreate pull request from separate branch (issue-1515, e.g.)? This pull request (and another one with commit to apt_repository.py) was created from my devel branch, so it was a mistake. This PR should be closed / rejected.

**Comment by abadger** [comment]
@verm666 Yep, that would be fine.  Just link to this PR in the new one so that we don't forget the conversation here :-)

**Pull request closed without merging**
