### PR TITLE
Hostname module should update ansible_hostname

### PR DESCRIPTION
**Pull request by hkariti**
When successfully changing the hostname, return an updated ansible_hostname fact.

### CODE REVIEW

**Comment by gregdek** [comment]
@user, thanks for submitting this pull request. Please accept our apologies for taking so long to review it.

It appears that this PR needs to be rebased due to changes in the code base. If you believe that this PR still applies, please rebase and we will then put it into our review process.

**Comment by hkariti** [comment]
@gregdek rebased

**Comment by gregdek** [comment]
Looks straightforward to me. @bcoca @jimi-c @abadger can you confirm?

**Comment by jimi-c** [comment]
Confirmed and merged, thanks!

**Pull request merged**
