### PR TITLE
Add supports_check_mode=True to mysql_db module

### PR DESCRIPTION
**Pull request by towolf**
The most important cases are state=present and state=absent.

Future work: import and dump could be simulated and hence checked.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @towolf. @Jmainguy please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by Jmainguy** [comment]
Sorry for the delay.

Code looks good to me, tested it and it works for me.

@gregdek 'shipit'

**Comment by Jmainguy** [comment]
@towolf Nice work, thank you for contributing.

**Comment by hloeffler** [comment]
@gregdek ping

**Comment by hloeffler** [comment]
@bcoca @gregdek ping?
this is not how to motivate your community

**Comment by Jmainguy** [comment]
@robynbergeron @gregdek ^^ please mark for inclusion when you get a chance. Thank you. :shipit:

**Comment by gregdek** [comment]
Thanks again to @towolf for this PR, and thanks @Jmainguy for reviewing. Marking for inclusion.

**Pull request merged**
