### PR TITLE
win_feature_docs_update

### PR DESCRIPTION
**Pull request by trondhindenes**
##### ISSUE TYPE
- Docs Pull Request
##### COMPONENT NAME

win_feature
##### ANSIBLE VERSION

```
2.2.0
```
##### SUMMARY

The fact that win_feature fails on client os computers comes up from time to time, so calling that out in docs

### CODE REVIEW

**Comment by trondhindenes** [comment]
ref #2792

**Comment by gregdek** [comment]
Thanks @trondhindenes for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by trondhindenes** [comment]
Not sure why CI didn't go thru, as it's only a doc update.
ready_for_review

**Comment by trondhindenes** [comment]
@gregdek I'm unable to see why the CI jobs seem to throw errors on this PR. Could you help me figure it out?

**Comment by gregdek** [comment]
Ach, sorry I didn't see this before I went on vacation @trondhindenes -- looking now. 

From what I can tell, it seems like it was an infrastructure timeout of some kind from shippable itself. That's a whole lot of tests for a two-line docs patch, LOL.

I think the right thing to do here is just slap "bot_broken" and "shipit" on this one, so that's what I'm gonna do -- @mattclay you can take a closer look at the CI issue if you're so inclined.

**Pull request merged**
