### PR TITLE
Fix #4202: Can't unarchive remote files

### LINKED ISSUE #4202: unarchive failed to transfer on devel
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

unarchive
##### ANSIBLE VERSION

ansible 2.2.0 (devel 134d70e7b9) last updated 2016/07/18 12:43:12 (GMT +1000)
  lib/ansible/modules/core: (detached HEAD 7de287237f) last updated 2016/07/18 12:43:16 (GMT +1000)
  lib/ansible/modules/extras: (detached HEAD 68ca157f3b) last updated 2016/07/18 12:43:16 (GMT +1000)
  config file = /home/linus/Documents/ansible-playbooks/ansible.cfg
  configured module search path = Default w/o overrides
##### CONFIGURATION

ansible_managed = Ansible managed: {file} modified on %Y-%m-%d %H:%M:%S by {uid} on {host}
hostfile = ./inventory
remote_user = centos
host_key_checking = False
log_path = /var/log/ansible.log
##### OS / ENVIRONMENT

management node: ubuntu 14.04
remote node: centos 7
##### SUMMARY

unarchive module shows error when src is an url using latest Ansible devel but works fine using the same playbook using Ansible stable 2.1.0.0 version.
##### STEPS TO REPRODUCE

```
unarchive:
    copy: no
    src: https://someurl.tar.gz
    dest: /tmp/somefolder
    owner: user
    group: user

```

##### EXPECTED RESULTS

changed
##### ACTUAL RESULTS

fatal: [xx.xx.xx.xx]: FAILED! => {"changed": false, "failed": true, "msg": "Source 'https://someurl.tar.gz' failed to transfer"}

### PR DESCRIPTION
**Pull request by lucascbeyeler**
##### ISSUE TYPE
- Bugfix Pull Request (Issue #4202 )
##### COMPONENT NAME

Unarchive
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel 2b28beb1d7) last updated 2016/07/23 10:54:10 (GMT -200)
  lib/ansible/modules/core: (detached HEAD b3c606047d) last updated 2016/07/23 10:54:35 (GMT -200)
  lib/ansible/modules/extras: (detached HEAD d9b4613941) last updated 2016/07/23 10:54:35 (GMT -200)
  config file = /home/lucasbeyeler/.ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

Today, when you try to unarchive some file using the option remote_src=true or copy=no to get a remote file, you receive the follow message:

```
FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"backup": null, "content": null, "copy": false, "creates": null, "delimiter": null, "dest": "/usr/local/src", "directory_mode": null, "exclude": [], "extra_opts": [], "follow": false, "force": null, "group": null, "keep_newer": false, "list_files": false, "mode": null, "original_basename": "file.tgz", "owner": null, "regexp": null, "remote_src": false, "selevel": null, "serole": null, "setype": null, "seuser": null, "src": "https://some/file.tgz", "validate_certs": true}}, "msg": "Source 'https://some/file.tgz' failed to transfer"}
```

That's happens because the default value of remote_src and copy are exactly what the condition ask for failure. If one of the vars are set with the default value, you will immediately throw to this message. As you can see:

```
...
copy              = dict(required=False, default=True, type='bool'),
remote_src        = dict(required=False, default=False, type='bool'),
...
    if not os.path.exists(src):
        if not remote_src or copy:
            module.fail_json(msg="Source '%s' failed to transfer" % src)
```

What I did was only change the OR for AND and the unarchive started to work again, as you can see:

**The modification:**

```
    if not os.path.exists(src):
        if not remote_src and copy:
            module.fail_json(msg="Source '%s' failed to transfer" % src)
```

**The result:**

```
{"changed": true, "dest": "/usr/local/src", "extract_results": {"cmd": "/usr/bin/gtar -C \"/usr/local/src\" -xz -f \"/tmp/ansible_cMM8V5/file.tgz\"", "err": "", "out": "", "rc": 0}, "gid": 0, "group": "root", "handler": "TgzArchive", "invocation": {"module_args": {"backup": null, "content": null, "copy": false, "creates": null, "delimiter": null, "dest": "/usr/local/src", "directory_mode": null, "exclude": [], "extra_opts": [], "follow": false, "force": null, "group": null, "keep_newer": false, "list_files": false, "mode": null, "original_basename": "file.tgz", "owner": null, "regexp": null, "remote_src": false, "selevel": null, "serole": null, "setype": null, "seuser": null, "src": "https://some/file.tgz", "validate_certs": true}}, "mode": "0755", "owner": "root", "secontext": "system_u:object_r:usr_t:s0", "size": 74, "src": "/tmp/ansible_cMM8V5/file.tgz", "state": "directory", "uid": 0}
```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @lucascbeyeler. To the current maintainers, @dagwieers, @pileofrogs please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by ramondg** [comment]
Can this be merged? This seems to fix the issue.

**Comment by linusgg** [comment]
ping @dagwieers, @pileofrogs

**Comment by linusgg** [comment]
Hi, @slmingol 
I couldn't get my sub-modules to the latest state using 

```
$ git pull --rebase
$ git submodule update --init --recursive
```

Can you tell me how you did it? Thanks!

**Comment by slmingol** [comment]
@linusgg - that's what I did, it just worked for me when I did it.

**Comment by linusgg** [comment]
@slmingol Thanks for the reply, I'll just clone a fresh one.

**Comment by brucellino** [comment]
I also confirm that this works.

**Comment by lucascbeyeler** [comment]
ping @dagwieers, @pileofrogs

Is it possible to merge the branch? A lot of people already proved that this change worked...

**Comment by dagwieers** [comment]
Are maintainers allowed to go on holiday during the summer ? ;-)

@lucascbeyeler Thanks for the contribution !
shipit

**Comment by gregdek** [comment]
Thanks again to @lucascbeyeler for this PR, and thanks @dagwieers, @pileofrogs for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by nitzmahone** [comment]
cherry-picked to stable-2.1

**Pull request merged**
