### PR TITLE
Add module to manage Digital Ocean DNS records with Ansible.

### PR DESCRIPTION
**Pull request by dopry**
This creates a digital_ocean_domain_record module which allows developers to manage DNS records on digital ocean.

This was https://github.com/ansible/ansible/pull/8509, but it seems ansible has move forward since the original pull request was made. The upstream issues in dopy that were holding up the original pull request have been resolved.

### CODE REVIEW

**Comment by fabian** [comment]
Great idea, would love to see this being added!

**Comment by gregdek** [comment]
Hmm, new module in Core. @zbal @mgregson can you guys review this module according to our new module guidelines? 

http://docs.ansible.com/developing_modules.html#module-checklist

If we get +1s from each of you, we will consider merging this.

**Comment by gregdek** [comment]
@dopry -- I'm going to recommend that you refile this excellent new module under the Extras repo, for a couple of reasons:
1. The process for having a module included in Extras is simpler and allows for easier review by more potential reviewers.
2. It's highly unlikely that we'll have the time to evaluate this as a new core module before the 2.0 release.

Therefore I'm going to close this PR. Please feel free to refile under Extras.

When you do, you should let @fabian know so he can test it. :)

**Comment by dopry** [comment]
@gregdek, @fabian, I'd recommend one of you rebase it and submit it to extras if you have any interest in the feature. As long as you preserve my attribution I won't mind.

**Comment by davisonio** [comment]
@dopry / @gregdek / @fabian Are you going to submit this into the extras repository? I think that this module would be a great addition.

**Comment by pogotech** [comment]
@dopry / @gregdek / @fabian this is a great feature. Can I help facilitate this migration in anyway?

**Comment by dopry** [comment]
@pogotech, I re-submitted it as is at https://github.com/ansible/ansible-modules-extras/pull/1744

We stopped using ansible a while back in favor of other tools, so any updates it needs to work with a current version of ansible or backports I'll leave in your capable hands.

**Pull request closed without merging**
