### PR TITLE
handle list of lists - python-apt < 0.7.9 compatibility

### PR DESCRIPTION
**Pull request by FabioBatSilva**
See : https://github.com/ansible/ansible-modules-core/pull/564

### CODE REVIEW

**Comment by abadger** [comment]
For the first portion of the change, I think that itertools.chain would be more readable:

``` python
        pkg_cache_list = (p for p in pkg_cache.Packages if p.Name == pkgname)
        pkg_versions = (p.VersionList for p in pkg_cache_list)
        versions = set(p.VerStr for p in itertools.chain(pkg_versions))
```

(and an appropriate import itertools earlier in the file)

For the second part, I had to read the code a few times but I think this is what the original code is doing:  When we are asked to install a pkgname and the pkgname isn't a real package we try to detect whether there's a virtual package that can satisfy the requirement.  If we successfully detect a virtual package we return a value that tells the install() function that the package is upgradable (may be a slight lie... the package may already be at the desired version.  That will cause a false positive for check mode and possibly a little extra work but shouldn't cause other issues.)  

If the pkgname is not a virtual provide then we return an error to the user that the pkgname is invalid.

If that's a correct reading of the code then I think for that portion if get_providing_packages() does not exist we need to return an error instead of passing.  Maybe something like this:

``` python
try:
    if cache.get_providing_packages(pkgname):
        return False, True, False
except AttributeError:
    # older python-apt providing packages cannot be used
    m.fail_json(msg="No package matching '%s' is available (python-apt version too old to detect virtual packages)" % pkgname)
```

**Comment by FabioBatSilva** [comment]
@abadger I've done the changes you suggested,  
But i was wondering if we should just mark the package as upgradable and let `apt-get install foo=1.0.0` deal with it.

something like : 

``` python
try:
    if cache.get_providing_packages(pkgname):
        return False, True, False
    m.fail_json(msg="No package matching '%s' is available" % pkgname)
except AttributeError:
    # older python-apt providing packages cannot be used
    # mark as upgradable and let apt-get install deal with it
    return False, True, False
```

**Comment by abadger** [comment]
@FabioBatSilva Hmm... I don't generally like making the function return something that isn't quite true because future changes to the code or features that we don't always think about (for instance, checkmode) may be impacted by the slight lie.

But AFAICS, your proposal to have apt-get install deal with this problem would work for all of the existing locations in the code which use package_status().  Additionally, this will only be triggered for older python-apt versions which we don't support anymore -- it doesn't touch the code path for recent python-apt.

So I'd be okay with your proposal if you still like it better.  Just be aware that you might have to propose more python-apt<0.7.x  fixes in the future if the module code changes and there's more places that use package_status() :-)  Maybe just add the python-apt version that we're hardcoding this return value for to the proposed comment as well so that people know in what circumstance that code will be invoked.

**Comment by FabioBatSilva** [comment]
@abadger Done !!

**Comment by abadger** [comment]
Merged!   Thanks!

# Merged

Hi!

This has been merged in, and will also be included in the next major release.

If you or anyone else has any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Pull request merged**
