### PR TITLE
Be able to find all contents of a directory

### PR DESCRIPTION
**Pull request by opoplawski**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

find
##### ANSIBLE VERSION

```
<!--- Paste verbatim output from “ansible --version” between quotes -->
ansible 2.0.2.0
  config file = /root/ansible-boulder/ansible.cfg
  configured module search path = /usr/share/ansible/
```
##### SUMMARY

I want to be able to remove all of the contents of a directory, files and directories.  The only method I've found is:

```
- find: paths="/var/cache/conda/pkgs" file_type=any
  register: conda_cache
- file: path={{ item.path }} state=absent
  with_items: "{{conda_cache.files}}"
```

```
TASK [science-runtime : find] **************************************************
Thursday 19 May 2016  12:09:50 -0600 (0:00:00.101)       0:00:04.723 **********
ok: [barry.cora.nwra.com]

TASK [science-runtime : Clean conda cache] *************************************
Thursday 19 May 2016  12:09:50 -0600 (0:00:00.582)       0:00:05.305 **********
changed: [barry.cora.nwra.com] => (item={u'uid': 0, u'woth': False, u'mtime': 1463681373.171626, u'inode': 813090536, u'isgid': False, u'size': 0, u'roth': True, u'isuid': False, u'isreg': True, u'gid': 0, u'ischr': False, u'wusr': True, u'xoth': False, u'rusr': True, u'nlink': 1, u'issock': False, u'rgrp': True, u'path': u'/var/cache/conda/pkgs/blah', u'xusr': False, u'atime': 1463681373.171626, u'isdir': False, u'ctime': 1463681373.171626, u'isblk': False, u'xgrp': False, u'dev': 2050, u'wgrp': False, u'isfifo': False, u'mode': u'0644', u'islnk': False})
changed: [barry.cora.nwra.com] => (item={u'uid': 0, u'woth': False, u'mtime': 1463681377.9396195, u'inode': 540898840, u'isgid': False, u'size': 6, u'roth': True, u'isuid': False, u'isreg': False, u'gid': 0, u'ischr': False, u'wusr': True, u'xoth': True, u'rusr': True, u'nlink': 2, u'issock': False, u'rgrp': True, u'path': u'/var/cache/conda/pkgs/blah2', u'xusr': True, u'atime': 1463681377.9396195, u'isdir': True, u'ctime': 1463681377.9396195, u'isblk': False, u'xgrp': True, u'dev': 2050, u'wgrp': False, u'isfifo': False, u'mode': u'0755', u'islnk': False})
```

Output is rather ugly.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @opoplawski for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by opoplawski** [comment]
I have no idea what needs fixing here.

**Comment by gregdek** [comment]
@opoplawski A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by opoplawski** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @opoplawski for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @opoplawski for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by opoplawski** [comment]
Rebased

**Pull request merged**
