### PR TITLE
Support 'buildargs' parameter for docker 1.9.

### PR DESCRIPTION
**Pull request by leonty**
This implements #2408 (ARG docker keyword support) for Ansible v2.0

### CODE REVIEW

**Comment by robynbergeron** [comment]
Thanks @leonty. @softzilla please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by robynbergeron** [comment]
@softzilla This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
@softzilla still waiting on your review.  Please comment with text 'shipit' or 'needs_revision' as appropriate. If we don't hear from you within 14 days, we will start to look for additional maintainers for this module.

**Comment by gregdek** [comment]
@leonty now moving this to @ansible/core team for review. Thanks for your patience.

**Comment by henry0312** [comment]
Any progress?

**Comment by gregdek** [comment]
Thanks @leonty for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@leonty A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by leonty** [comment]
@gregdek I give up on the 1.9 version, close this PR. Thank you for reminding.

**Comment by gregdek** [comment]
Thanks for the heads up, @leonty -- sorry we couldn't get it in.

**Pull request closed without merging**
