### PR TITLE
Adds tmp_dest option to get_url module.

### PR DESCRIPTION
**Pull request by sysadmin75**
Addresses the issue in ansible/ansible#9512

### CODE REVIEW

**Comment by manicminer** [comment]
I've tested this change with the `tmp_dest` option set for a 14GB file download and it works as expected.

**Comment by manicminer** [comment]
One suggestion from what I've observed, it would be great if the temporary file could be moved, rather than copied, to the final destination. This should probably only happen if the temporary path and destination path are on the same volume, which might be hard to determine. Maybe it could be moved in the event that `tmp_dest` is specified?

**Comment by muffl0n** [comment]
Maybe shutil.copyfile() in [Line 347](https://github.com/sysadmin75/ansible-modules-core/blob/9512_get_url_tmp_option2/network/basics/get_url.py#L347) should be replaced with [shutil.move()](https://docs.python.org/2/library/shutil.html#shutil.move):
`If the destination is on the current filesystem, then os.rename() is used. Otherwise, src is copied (using shutil.copy2()) to dst and then removed.`

So that's basicly the same behaviour as we have now (shutil.copy() then os.remove) but with the benefit of faster operation if tmp_src and dst are on the same fs.

**Comment by robynbergeron** [comment]
@sysadmin75 -- thanks for this PR, and thanks to @tombamford and @muffl0n for your comments. :)

@jpmens -- Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.
If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by jpmens** [comment]
shipit

**Pull request merged**
