### PR TITLE
Update mysql_db.py

### PR DESCRIPTION
**Pull request by aioue**
##### ISSUE TYPE

Docs Pull Request
##### COMPONENT NAME

mysql_db
##### ANSIBLE VERSION

2.1.0
##### SUMMARY

Resubmission of https://github.com/ansible/ansible-modules-core/pull/2961 in single commit.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @aioue. To the current maintainers, @Jmainguy please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by Jmainguy** [comment]
@aioue Looks great, thank you for taking the time to create this.

@gregdek :shipit:

**Comment by gregdek** [comment]
Thanks again to @aioue for this PR, and thanks @Jmainguy for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by resmo** [comment]
needs_revision

@aioue there are unneeded prefixed `+` IMHO. could you remove these?

**Comment by Jmainguy** [comment]
@resmo What do you mean uneeded prefixed `+`?

**Comment by aioue** [comment]
@resmo removed

**Comment by Jmainguy** [comment]
ah I see now, I am an idiot, nice work @aioue and @resmo

**Comment by gregdek** [comment]
Back to shipit. Thanks all.

**Pull request merged**
