### PR TITLE
Copy: default to user's home directory when dest is filename

### LINKED ISSUE #5268: copy: dest=filename fails with "Destination directory  does not exist"
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

copy
##### ANSIBLE VERSION

```
ansible 2.1.2.0
  config file = 
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

Linux
##### SUMMARY

When I try to copy a file into the current working directory on the remote end, Ansible fails because it tries to check for the existence of the (empty string) directory.
##### STEPS TO REPRODUCE

```
$ ansible localhost -m copy -a "src=/dev/null dest=file.txt"
```
##### EXPECTED RESULTS

I expect an empty file `file.txt` to show up in my home directory
##### ACTUAL RESULTS

```
localhost | FAILED! => {
    "changed": false, 
    "checksum": "da39a3ee5e6b4b0d3255bfef95601890afd80709", 
    "failed": true, 
    "msg": "Destination directory  does not exist"
}
```

### PR DESCRIPTION
**Pull request by rcutmore**
##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

Copy
##### ANSIBLE VERSION

```
ansible 2.3.0 (copy-filename-dest-test 8a1e9c02d5) last updated 2016/11/24 08:15:00 (GMT -400)
  lib/ansible/modules/core: (copy-filename-dest 532ba3ed51) last updated 2016/11/23 20:35:53 (GMT -400)
  lib/ansible/modules/extras: (devel 9511de1e3d) last updated 2016/11/18 19:36:23 (GMT -400)
  config file = 
  configured module search path = Default w/o overrides
```

##### SUMMARY

Currently when the dest parameter is set to a filename and not a filepath an error is raised. This changes the behavior to default to the user's home directory when only a filename is specified as the dest. Fixes #5268 

Command:
```
ansible localhost -m copy -a "src=/dev/null dest=file.txt"
```
Output (Before):
```
localhost | FAILED! => {
    "changed": false, 
    "checksum": "da39a3ee5e6b4b0d3255bfef95601890afd80709", 
    "failed": true, 
    "msg": "Destination directory  does not exist"
}
```
Output (After):
```
localhost | SUCCESS => {
    "changed": true, 
    "checksum": "da39a3ee5e6b4b0d3255bfef95601890afd80709", 
    "dest": "/home/rcutmore/file.txt", 
    "gid": 1000, 
    "group": "rcutmore", 
    "md5sum": "d41d8cd98f00b204e9800998ecf8427e", 
    "mode": "0664", 
    "owner": "rcutmore", 
    "secontext": "unconfined_u:object_r:user_home_t:s0", 
    "size": 0, 
    "src": "/home/rcutmore/.ansible/tmp/ansible-tmp-1479995036.83-136457098768885/source", 
    "state": "file", 
    "uid": 1000
}
```

### CODE REVIEW

**Comment by rcutmore** [comment]
Associated test added [here](https://github.com/ansible/ansible/pull/18610).

**Comment by gundalow** [comment]
Original bug was filed against `2.1.2.0` so suggesting we backport this

**Comment by gundalow** [comment]
Thank you for the test :)

**Comment by gundalow** [comment]
Closing as not a bug for reasons detailed in https://github.com/ansible/ansible-modules-core/issues/5268

To avoid discussion fragmentation please put any replies on https://github.com/ansible/ansible-modules-core/issues/5268

**Review by gundalow — CHANGES_REQUESTED** [review]
Rejected

**Comment by gundalow** [comment]
Closing as not a bug for reasons detailed in https://github.com/ansible/ansible-modules-core/issues/5268

To avoid discussion fragmentation please put any replies on https://github.com/ansible/ansible-modules-core/issues/5268

**Pull request closed without merging**
