### PR TITLE
Fix git failure for use of depth with version

### LINKED ISSUE #5108: git module: fatal: A branch named 'STABLE' already exists.
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

Module: git
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel b427818f02) last updated 2016/09/30 19:29:28 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 537a7eb924) last updated 2016/09/30 19:29:49 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD a58e1d59c0) last updated 2016/09/30 19:29:49 (GMT +200)
  config file = 
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

No customisation.
##### OS / ENVIRONMENT

N/A
##### SUMMARY

"msg": "Failed to checkout STABLE"
"stderr": "fatal: A branch named 'STABLE' already exists.\n"

On first run only.
##### STEPS TO REPRODUCE

Run:

```
hacking/test-module -m lib/ansible/modules/core/source_control/git.py -a 'repo=https://github.com/phpmyadmin/phpmyadmin.git dest=/tmp/pma depth=1 version=STABLE force=yes'
```

Output:

```
PARSED OUTPUT
{
    "cmd": "/usr/bin/git checkout --track -b STABLE origin/STABLE", 
    "failed": true, 
    "invocation": {
        "module_args": {
            "accept_hostkey": false, 
            "bare": false, 
            "clone": true, 
            "depth": 1, 
            "dest": "/tmp/pma", 
            "executable": null, 
            "force": true, 
            "key_file": null, 
            "recursive": true, 
            "reference": null, 
            "refspec": null, 
            "remote": "origin", 
            "repo": "https://github.com/phpmyadmin/phpmyadmin.git", 
            "ssh_opts": null, 
            "track_submodules": false, 
            "umask": null, 
            "update": true, 
            "verify_commit": false, 
            "version": "STABLE"
        }
    }, 
    "msg": "Failed to checkout STABLE", 
    "rc": 128, 
    "stderr": "fatal: A branch named 'STABLE' already exists.\n", 
    "stdout": ""
}
```

On second run the task succeeds, so to reproduce again one needs to delete the repo:

```
rm -rf /tpm/pma
```
##### EXPECTED RESULTS

Task succeeds on first run.
##### ACTUAL RESULTS

Task fails on first run:

```
* including generated source, if any, saving to: /home/riaan/.ansible_module_generated
* ansiballz module detected; extracted module source to: /home/riaan/debug_dir
***********************************
RAW OUTPUT

{"stdout": "", "cmd": "/usr/bin/git checkout --track -b STABLE origin/STABLE", "failed": true, "stderr": "fatal: A branch named 'STABLE' already exists.\n", "rc": 128, "invocation": {"module_args": {"executable": null, "force": true, "refspec": null, "reference": null, "dest": "/tmp/pma", "verify_commit": false, "clone": true, "accept_hostkey": false, "update": true, "umask": null, "repo": "https://github.com/phpmyadmin/phpmyadmin.git", "depth": 1, "version": "STABLE", "bare": false, "recursive": true, "remote": "origin", "key_file": null, "ssh_opts": null, "track_submodules": false}}, "msg": "Failed to checkout STABLE"}


***********************************
PARSED OUTPUT
{
    "cmd": "/usr/bin/git checkout --track -b STABLE origin/STABLE", 
    "failed": true, 
    "invocation": {
        "module_args": {
            "accept_hostkey": false, 
            "bare": false, 
            "clone": true, 
            "depth": 1, 
            "dest": "/tmp/pma", 
            "executable": null, 
            "force": true, 
            "key_file": null, 
            "recursive": true, 
            "reference": null, 
            "refspec": null, 
            "remote": "origin", 
            "repo": "https://github.com/phpmyadmin/phpmyadmin.git", 
            "ssh_opts": null, 
            "track_submodules": false, 
            "umask": null, 
            "update": true, 
            "verify_commit": false, 
            "version": "STABLE"
        }
    }, 
    "msg": "Failed to checkout STABLE", 
    "rc": 128, 
    "stderr": "fatal: A branch named 'STABLE' already exists.\n", 
    "stdout": ""
}

```

### PR DESCRIPTION
**Pull request by robinro**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

source_control/git.py
##### ANSIBLE VERSION

2.2.0rc1
##### SUMMARY
- Fixes #5108
- before module fails with "fatal: A branch named 'STABLE' already
  exists." when depth is used on a fresh clone with a non-HEAD branch

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @robinro for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by robinro** [comment]
@gregdek The test failure is unrelated (python3), please put bot_broken.

**Comment by RiaanBurger** [comment]
Thank you @robinro - works (tested).

Both the test case I presented and the real world instance in my playbook works with this patch. I don't see a "tested by the community" tag I can add for the Ansibot. Do you have any further need from the test on my side?

Apologies for the delay.

**Comment by robinro** [comment]
@RiaanBurger Thanks for testing!

If you want to contribute, you could try to create a minimal testcase and open a PR against the integration tests in ansible/ansible: https://github.com/ansible/ansible/blob/devel/test/integration/roles/test_git/tasks/main.yml. 
phpmyadmin is not useable as a test repo since it's big and takes a ridiculous amount of time to clone. One of the test-repos already used should also work.
For documentation on how to run the integration tests see http://docs.ansible.com/ansible/dev_guide/developing_test_pr.html or the documentation in the code.

**Pull request merged**
