### PR TITLE
1-line fix Darwin group_mod in system/group module by adding **kwargs

### PR DESCRIPTION
**Pull request by rmgrimm**
This also contains two tiny spacing/indentation changes, contained in a second commit.

### CODE REVIEW

**Comment by bcoca** [comment]
what does this fix? the method does not seem to use anything except self

**Comment by rmgrimm** [comment]
To recreate the issue, I ran the following command twice on an OSX machine:

``` bash
ansible localhost -i inventory -b -m group -a "name=test gid=101010 state=present" --ask-become-pass
```

The first time worked; it created the group:

```
SUDO password: 
localhost | success >> {
    "changed": true, 
    "name": "test", 
    "state": "present"
}
```

Then second time, it resulted with this error (I scrubbed username from paths listed):

```
localhost | FAILED >> {
    "failed": true, 
    "msg": "BECOME-SUCCESS-tpibfewffffscclbvauxtqfvpqeokwxj\nTraceback (most recent call last):\n  File \"/Users/username/.ansible/tmp/ansible-tmp-1428008091.91-50497227698351/group\", line 2045, in <module>\n    main()\n  File \"/Users/username/.ansible/tmp/ansible-tmp-1428008091.91-50497227698351/group\", line 423, in main\n    (rc, out, err) = group.group_mod(gid=group.gid)\nTypeError: group_mod() got an unexpected keyword argument 'gid'\n", 
    "parsed": false
}
```

Note that the group_add for Darwin requires the gid parameter in order to complete successfully. That is a separate issue.

Please let me know if there is additional info I can provide.

**Comment by gregdek** [comment]
@rmgrimm Thanks for submitting this pull request. Please accept our apologies for taking so long to review it.

Unfortunately, due to this delay, it appears that the underlying code has changed, and this PR needs to be rebased. If you believe that this PR still applies, please rebase and we will then put it into our (new, faster) community review process as soon as possible.  Again, apologies for the delay and the extra work.

**Comment by bcoca** [comment]
closing this in favor of the fix in #1086

**Pull request closed without merging**
