### PR TITLE
add unrar support to files/unarchive.py

### PR DESCRIPTION
**Pull request by vadikgo**
Need unrar version >= 5.2.3

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @vadikgo. @pileofrogs please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
@pileofrogs This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
@pileofrogs still waiting on your review.  Please comment with text 'shipit' or 'needs_revision' as appropriate. If we don't hear from you within 14 days, we will start to look for additional maintainers for this module.

**Comment by gregdek** [comment]
Moving to core review.

Thanks @vadikgo for your patience here.

**Comment by dagwieers** [comment]
@gregdek We are planning to reimplement unarchive (using native python modules) to make it idempotent and have check-mode support. See #3307 for the details. The same is possible using the python rarfile module. The upside of doing a native reimplementation is that it can become truly idempotent, but it also means it becomes easier to have a single unarchive module with additional options (like exclude and keep_newer) that works cross the various archive formats.

**Comment by dagwieers** [comment]
So I would not merge this patch on the ground that it always extracts the files, and that is the wrong approach IMHO.

**Comment by gregdek** [comment]
Thanks @vadikgo for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@vadikgo A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by vadikgo** [comment]
I'm use unrar return code 10 "No files to extract" to make it idempotent.

**Comment by dagwieers** [comment]
As long as we cannot enable check-mode in unarchive, none of the functionality is really idempotent IMO. Sure the implementation of some of the tools allow to be "smart", the gtar implementation basically makes check-mode impossible. Frustrating because the zip-support could be idempotent as well, but either everything supports check-mode, or none will.

**Comment by gregdek** [comment]
@vadikgo Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
