### PR TITLE
Add dhcp_options to VPC creation in cloud/amazon

### PR DESCRIPTION
**Pull request by ghost**
Add ability to create/associate dhcp_options

### CODE REVIEW

**Comment by bennojoy** [comment]
@michal-jora  could you please add version_added to the new paramter in the doc string.

**Comment by mpisanko** [comment]
@bennojoy done

**Comment by bennojoy** [comment]
@michal-jora  can you please make version_added: 2.0 as 1.9 is already released

**Comment by bennojoy** [comment]
@michal-jora  seems like you are deleting the dhcpoptions after the vpc is deleted , shouldn't this be done before deleting the vpc ? vpc_conn.delete_vpc(vpc.id)

**Comment by bcoca** [comment]
cc @defionscode , does it make sense to keep adding to this module since there is a push to deprecate it in favor of several smaller more specialized modules?

**Comment by juliedavila** [comment]
@bcoca good call, I think only bug fixes should be added to this now, feature type PRs should go to the new ones. @michal-jora this would be the `ec2_vpc_net` module which is now in devel for core. I believe DHCP options is already supported there.

**Comment by gregdek** [comment]
So should we close this one then?

**Comment by juliedavila** [comment]
I would recommend a close

**Pull request closed without merging**
