### PR TITLE
Fix git shallow update

### PR DESCRIPTION
**Pull request by robinro**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

source_control/git.py
##### ANSIBLE VERSION

devel, 2.2
##### SUMMARY

This is a follow-up to  #3794.
Compared to #3794 I raised the requires git version for use of depth from 1.8.2 to 1.9.1. This excludes centos7 (which failed the example test to shallow-fetch updates from a repo) but still allows ubuntu14.04 which passes those.

It is meant to be merged together with ansible/ansible#16224, which includes the test that only pass in combination with this fix.

### CODE REVIEW

**Comment by robinro** [comment]
So this still fails on centos7. Now (with depth disabled) another test complains.

@abadger I would appreciate if you or someone else could take this over and clean it up. For me testing simultaneous changes to ansible and ansible-core-modules in docker is quite time-consuming and struggling with old git versions that break in undocumented ways is not much fun. While I generally like to help out this bug takes more time than I can invest at the moment.

The split into separate repos for tests and code really hurts here, btw.

**Comment by gregdek** [comment]
Thanks @robinro for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by abadger** [comment]
Yeah, I never use docker for testing locally... always checkout onto a vm and run the integration tests from the checkout.

**Comment by gregdek** [comment]
Thanks @robinro for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by robinro** [comment]
This is now fixed and tested with all distros currently running in shippable, i.e. it passes 

```
for distro in centos6 centos7 fedora-rawhide fedora23 opensuseleap ubuntu1204 ubuntu1404 ubuntu1604; do IMAGE=ansible/ansible:$distro TARGET=non_destructive TEST_FLAGS="--tags test_git" test/utils/shippable/integration.sh; done
```

@abadger please merge this together with the updated tests in https://github.com/ansible/ansible/pull/16224

Both should also make it into 2.1-stable since without it `ansible-pull -U foo` (usage without -C version) does not update when the repo changes.

**Pull request merged**
