### PR TITLE
Make add ip_floating_ip idempotent

### LINKED ISSUE #1858: os_floating_ip errors if an ip is attached.
##### Issue Type:

Regression (so inevitably a feature idea).
##### Ansible Version:

ansible 2.0.0
##### Ansible Configuration:

```
< lookup_plugins = ./lookup_plugins:~/.ansible/plugins/lookup_plugins/:/usr/share/ansible_plugins/
< timeout = 120

---
> timeout = 10
```
##### Environment:

OSX -> Ubuntu
##### Summary:

If you add an ip with os_floating_ip to a server, when you rerun your play, it errors.
##### Steps To Reproduce:

```
- os_floating_ip:
    cloud: envvars
    state: present
    reuse: yes
    server: cwp-goserver-1
    network: vlan3320
    fixed_address: "{{ lookup('os_private_ip', 'cwp-goserver-1') }}"
    wait: true
    timeout: 180
```
##### Expected Results:

If the server already has a floating ip from the network, expect the task to pass, as unchanged.
##### Actual Results:

```
unable to bind a floating ip to server f23ce73c-82ad-490a-bf0e-7e3d23dce449: Cannot associate floating IP 10.12.71.112 (57a5b6e0-2843-4ec5-9388-408a098cdcc7) with port f2c6e8bb-b500-4ea0-abc8-980b34fc200f using fixed IP 192.168.101.36, as that fixed IP already has a floating IP on external network 8b3e1a76-f16c-461b-a5b5-f5987936426d
```

### PR DESCRIPTION
**Pull request by GheRivero**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

cloud/openstack/os_floating_ip
##### ANSIBLE VERSION

```
2.0.2.0
```
##### SUMMARY

Makes adding os_floating_ip idempotent

Fixes #1858

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @GheRivero. To the current maintainers, @emonty, @shrews, @juliakreger, @j2sol, @rcarrillocruz please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by omgjlk** [comment]
So this takes a very simplistic approach. it just looks to see if any floating IP address exists on the server. But a a server could need multiple floating IPs, one for every fixed IP. So, I think it's a good start, but it may miss some cases.

Testing it now.

**Comment by omgjlk** [comment]
Tests out okay.  shipit

**Comment by gregdek** [comment]
Thanks again to @GheRivero for this PR, and thanks @emonty, @shrews, @juliakreger, @j2sol, @rcarrillocruz for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by rcarrillocruz** [comment]
shipit

**Pull request merged**
