### PR TITLE
nova_compute: indicate argument type

### PR DESCRIPTION
**Pull request by puiterwijk**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

nova_compute
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/srv/web/infra/ansible/library', '/usr/share/ansible']
```
##### SUMMARY

This makes sure that the arguments are parsed as list or dict, rather than str.
Otherwise, the module will fail because it's trying to loop over the characters in the str represntation
of nics instead if the entries in it for example.

Output with the bug:

```
fatal: [graphite.fedorainfracloud.org -> localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Error in creating instance: 'str' object has no attribute 'get' "}
```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @puiterwijk. To the current maintainers, @emonty, @shrews, @juliakreger, @j2sol, @rcarrillocruz please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by Shrews** [comment]
This module is deprecated and we do not maintain these. Please use the newer os_\* modules.

**Comment by Shrews** [comment]
Since this is a bug fix, I'll recommend to merge. However, I did not test this.

shipit

**Comment by gregdek** [comment]
Thanks again to @puiterwijk for this PR, and thanks @emonty, @shrews, @juliakreger, @j2sol, @rcarrillocruz for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request merged**
