### PR TITLE
Support altering the virtual cdrom when state == reconfigured

### PR DESCRIPTION
**Pull request by fennm**
This allows a user to modify the state of the virtual cdrom in a VM
by using the state == reconfigured action.  This is useful for
provisioning VMs from templates which do not have ISO images connected.

### CODE REVIEW

**Comment by gregdek** [comment]
@rhoop Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by rhoop** [comment]
@gregdek @fennm => Code looks good but I can not test this until probably Friday when I am back in the office.

**Comment by fennm** [comment]
Sounds good, thanks!

**Comment by rhoop** [comment]
LGTM. Test passed on my end.

**Comment by gregdek** [comment]
Thanks @fennm for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

**Comment by fennm** [comment]
ready_for_review

**Comment by fennm** [comment]
Sure thing, I updated the pr with a change which resolves the merge conflict

**Comment by gregdek** [comment]
Thanks @fennm. @chrrrles @rhoop please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
So this one got a LGTM from maintainer, was properly rebased, and looks like the bot missed it. Marking "shipit" -- thanks @rhoop for the review and thanks @fennm for the PR.

**Pull request merged**
