### PR TITLE
Add validate_certs option to vsphere_guest module

### PR DESCRIPTION
**Pull request by lvasiliev**
```
Hi!
I added validate_certs option to vsphere_guest module. We using  vcenter_hostname which has self-signed certificate. Without this options we cautch Exceptions when executed viserver.connect(vcenter_hostname, username, password).
```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @lvasiliev. @chrrrles @rhoop please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
Thanks @lvasiliev for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

**Comment by gregdek** [comment]
@chrrrles @rhoop This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
@lvasiliev Thanks for submitting this pull request. Unfortunately, it appears that the underlying code has changed since your submission, and this PR now needs to be rebased. 

If you believe that this PR still applies, please rebase and we will put it into our community review process as soon as possible. 

Once you have rebased this PR, please add a comment with the text "ready_for_review" and we will continue with the review process.  Thanks!

**Comment by lvasiliev** [comment]
Hi. I see that commit c24f758 from @sterutkb added validate_certs options.

**Comment by lvasiliev** [comment]
Please, close it pull because this options already present.

**Pull request closed without merging**
