### PR TITLE
add extra options to unarchive module

### PR DESCRIPTION
**Pull request by gesquive**
This patch allows users to specify command line options for the underlying unarchivers in the unarchive module.

Example:

``` yaml
- name: Unpack an archive
  unarchive:
    src=/path/to/archive
    dest=/path/to/unpack
    extra_opts='--strip-components=1'
```

This option seems more flexible and usable than PR #2491

### CODE REVIEW

**Comment by Jmainguy** [comment]
@gesquive Did you mean to remove import os, seems like some other lines in this file use os

**Comment by gesquive** [comment]
Nope, that wasn't on purpose. Added the import back in.

**Comment by pileofrogs** [comment]
I'm working on refactoring unarchive into three separate modules.  A generic unarchive similar to the one we have now, a tar specific module and a zip specific module.  I hope to support many options and also a catchall extra-args type option.

I don't have a lot of time to do it though, so if you want to help work on that, I could use it.  Let me know if you're interested.

**Comment by gregdek** [comment]
Thanks @gesquive. @pileofrogs please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
@pileofrogs This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
@pileofrogs still waiting on your review.  Please comment with text 'shipit' or 'needs_revision' as appropriate. If we don't hear from you within 14 days, we will start to look for additional maintainers for this module.

**Comment by Jmainguy** [comment]
@pileofrogs I believe it was your intention not to accept this PR, not based on the quality of it (Which looks quite good), but rather that there has been extensive talks about this feature before the PR was opened, and you are working on breaking this module into a few smaller tar/zip/etc specific modules. 

Can you confirm or comment some other way on here to give @gregdek and @gesquive an idea on when this PR can be resolved?

**Comment by pileofrogs** [comment]
Sorry!

I had submitted a PR with an initial attempt to break unarchive into
unatchive, untar and unzip.  I was waiting for a response to that PR before
deciding what to do about this PR.

Because unarchive has an action plugin element as well as a module element,
it's a PR for both
ansible and ansible-modules-core.

Here's my PRs:

https://github.com/ansible/ansible/pull/13869
https://github.com/ansible/ansible-modules-core/pull/2806

I'd love to accept the PR for adding extra options to unarchive module, but
I don't want to do that until the refactor has been settled.  I really
should have been more fussy demanding a response to my PRs.

**Comment by gregdek** [comment]
Thanks @gesquive for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

**Comment by gregdek** [comment]
@ansible This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gesquive** [comment]
rebase is complete

ready_for_review

**Comment by pileofrogs** [comment]
shipit !

Several tar args that I tried didn't work because the module tries to check if the archive is unpacked.  
--skip-components blew up and --numeric-owner did nothing.  I found an arg that worked, however, '--skip-old-files' worked.  So, this patch works as expected, but the extra stuff in the module gets in the way of most functionality.  

I think this PR should go ahead and we should fix the problems in another PR.

**Comment by gregdek** [comment]
Thanks again to @gesquive for this PR, and thanks @pileofrogs for reviewing. Marking for inclusion.

**Comment by dagwieers** [comment]
@gregdek Please consider the approach in #3307 (not the actual implementation, but the fact that we don't want to rely on external programs in most cases).

**Comment by Jmainguy** [comment]
@gregdek @dagwieers Looks like this, and #3307 are marked for inclusion, but they both contain adding extra_opts. Could be an issue with the order in which these two are merged, if #3307 is merged first, than this PR becomes redundant, where as if this gets merged first, both add value still.

**Comment by gregdek** [comment]
Thanks @gesquive for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by Jmainguy** [comment]
@gregdek because #3307 was merged (and contained many multiple fixes in one merge) this PR has now been made redundant, which is unfortunate.

**Comment by gesquive** [comment]
I haven't had a chance to test it myself, but It looks like #3307 includes similar extra_opts functionality. Closing this PR.

**Pull request closed without merging**
