### PR TITLE
Command: Remove whitespace at start of new lines

### LINKED ISSUE #5607: Shell module does not respect indentation with multiline command
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

shell

##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

Ubuntu 16.04.1

##### SUMMARY

Shell module does not respect indentation with multiline command.

##### STEPS TO REPRODUCE

Run the play below:

```yaml
- shell: |
    print 'Hello world!'
    print 'Hello again!'
    print 'Okay, enough already.'
  args:
    executable: /usr/bin/python
```

##### EXPECTED RESULTS

Produce and execute the following python script:
```python
print 'Hello world!'
print 'Hello again!'
print 'Okay, enough already.'
```

##### ACTUAL RESULTS

The generated script is:
```python
print 'Hello world!'
 print 'Hello again!'
 print 'Okay, enough already.'
```
and it fails with indentation error on line 2

```
fatal: [default]: FAILED! => {"changed": true, "cmd": "print 'Hello world!'\n print 'Hello again!'\n print 'Okay, enough already.'", "delta": "0:00:00.020710", "end": "2016-11-14 16:18:24.251756", "failed": true, "rc": 1, "start": "2016-11-14 16:18:24.231046", "stderr": "  File \"<string>\", line 2\n    print 'Hello again!'\n    ^\nIndentationError: unexpected indent", "stdout": "", "stdout_lines": [], "warnings": []}
```

P.S. passing the same block to `debug` module works as expected, so it is definitely problem with `shell`.

### PR DESCRIPTION
**Pull request by rcutmore**
##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

Command
##### ANSIBLE VERSION

```
ansible 2.3.0 (devel a757a77159) last updated 2016/11/27 13:24:31 (GMT -400)
  lib/ansible/modules/core: (devel e1e64c5aef) last updated 2016/11/26 12:09:06 (GMT -400)
  lib/ansible/modules/extras: (devel 9511de1e3d) last updated 2016/11/18 19:36:23 (GMT -400)
  config file = 
  configured module search path = Default w/o overrides
```

##### SUMMARY

This updates the command module to remove any spaces after a newline if they exist. These extra spaces caused issues when running commands where whitespace matters, such as Python.

Fixes #5607 

Command:
```
- shell: |
    print 'Hello world!'
    print 'Hello again!'
    print 'Okay, enough already.'
  args:
    executable: /usr/bin/python
```
Before:
```
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "print 'Hello world!'\n print 'Hello again!'\n print 'Okay, enough already.'", "delta": "0:00:00.012131", "end": "2016-11-27 16:00:54.209884", "failed": true, "rc": 1, "start": "2016-11-27 16:00:54.197753", "stderr": "  File \"<string>\", line 2\n    print 'Hello again!'\n    ^\nIndentationError: unexpected indent", "stdout": "", "stdout_lines": [], "warnings": []}
```
After:
```
changed: [localhost] => {"changed": true, "cmd": "print 'Hello world!'\nprint 'Hello again!'\nprint 'Okay, enough already.'", "delta": "0:00:00.011881", "end": "2016-11-27 16:00:12.457329", "rc": 0, "start": "2016-11-27 16:00:12.445448", "stderr": "", "stdout": "Hello world!\nHello again!\nOkay, enough already.", "stdout_lines": ["Hello world!", "Hello again!", "Okay, enough already."], "warnings": []}
```

### CODE REVIEW

**Comment by rcutmore** [comment]
I'm not sure if this is the best approach, any feedback is welcome. I added a test for this change [here](https://github.com/ansible/ansible/pull/18641).

**Comment by gregdek** [comment]
Thanks @rcutmore for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @rcutmore for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by agaffney** [comment]
The example issue is with the `shell` module, but this fix is against the `command` module. Am I missing something here?

**Comment by jctanner** [comment]
Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us that you've taken time to contribute.

Unfortunately, we're not sure if we want this feature in the program, and I don't want this to seem confrontational.  Our reasons were stated in https://github.com/ansible/ansible-modules-core/issues/5607#issuecomment-263381771

However, we're absolutely always up for discussion.  Since this is a really busy project, we don't always see comments on closed tickets, but want to encourage
open dialog.  You can stop by the development list, and we'd be glad to talk about it - and we might even be persuaded otherwise!

   * https://groups.google.com/forum/#!forum/ansible-devel

In the future, sometimes starting a discussion on the development list prior to implementing a feature can make getting things included a little easier, but it's not always necessary.

Thank you once again for this and your interest in Ansible!

**Comment by rcutmore** [comment]
@jctanner No worries, thanks for reviewing.

**Pull request closed without merging**
