### PR TITLE
Revert "Reset all locale environment variables before running svn commands"

### PR DESCRIPTION
**Pull request by mullnerz**
This reverts commit 99456fbc9851209f4482cdf6c246806ba1e9fbff.
#4178

### CODE REVIEW

**Comment by bcoca** [comment]
So this just brings back the other bug, is there a solution that fixes both? like just setting LC_MESSAGES instead of all the vars?

**Comment by mullnerz** [comment]
I can confirm that setting only LANG and LC_MESSAGES to 'C' doesn't break subversion with UTF-8 files in a repository. So if only setting these variables fixes the original bug, then this could be the deal:

`module.run_command_environ_update = dict(LANG='C', LC_MESSAGES='C')`

**Comment by bcoca** [comment]
update this PR with that and I'll merge

**Comment by mullnerz** [comment]
Ok, thank you!

**Comment by ghost** [comment]
Please also merge this fix to stable-2.1.

**Pull request merged**
