### PR TITLE
Pull SSL certificate IDs from existing ELBs

### LINKED ISSUE #9073: ec2_elb_lb always reports a changed state when specifying a https listener with certificate
##### Issue Type:

When using the ec2_elb_lb module to create an ELB with a HTTPS listener with a SSL certificate, the module always reports the status as changed even when no changes are made.
##### Ansible Version:

1.7.1
##### Environment:

Management Machine: Mac OS X 10.9.4, ansible 1.7.1 installed via homebrew
Target Machine: EC2 ELB
##### Summary:

When using the ec2_elb_lb module to create an ELB with a HTTPS listener with a SSL certificate, the module always reports the status as changed even when no changes are made.  If I remove the HTTPS listener and only specify HTTP, the status is reported correctly.
##### Steps To Reproduce:
1. Create an ELB with the ec2_elb_lb module with a HTTP and HTTPS (with SSL certificate) listener.  The ELB will be provisioned.
2. Rerun the same task.  The status will report as changed even though no changes were made.
##### Expected Results:

Status should be ok on subsequent runs of the same task
##### Actual Results:

Status always shows as changed.

### PR DESCRIPTION
**Pull request by teamdoug**
Fixes ansible/ansible#9073 and fixes #22
The root cause of that issue is that boto's "get_complex_tuple()" doesn't include the ssl_certificate_id for some unknown reason. I'm following up on this upstream, but a workaround for now would be nice :)

### CODE REVIEW

**Comment by bcoca** [comment]
# Rebase Request

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us. 

It looks like the code underneath has changed since this was submitted.  Can you take care of rebasing this for us?
- You should be able to run "git rebase" against this branch to bring it up to date
- Resolve any merge conflicts and test changes
- Push to the same branch and github should update the pull request automatically.

Just as a quick reminder of things, this is a really busy project.  We have over 800 contributors and to manage the queue effectively
we assign things a priority between P1 (highest) and P5.  We'd like to thank you very much for your time!  
We'll work things in priority order, so just wanted you to be aware of the queue and know we haven't forgotten about you!

We will definitely see your comments on this issue when reading this ticket, but may not be able to reply promptly.  You may also wish to join one of our two mailing lists
which are very active:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Thank you once again for this and your interest in Ansible!

**Comment by endzyme** [comment]
Poke

**Comment by juliedavila** [comment]
fixes https://github.com/ansible/ansible-modules-core/issues/23

**Comment by endzyme** [comment]
Thanks!!!

**Comment by hackndoes** [comment]
I am on ansible 2.2.0.0 and it still happens to me.
here is my code:

```
ec2_elb_lb:
    name: "name"
    region: '{{ region }}'
    state: present
    subnets: "{{ subnet_list }}"
    instance_ids: "{{ instance_id_list }}"
    security_group_names: [group1, group2]
    scheme: "internet-facing"
    cross_az_load_balancing: yes
    wait: yes
    tags:
      Name: "name"
      environment: '{{ env }}'
    stickiness:
      type: "{{ sticki_type}}"
      enabled: "{{ sticki_enabled }}"
      expiration: "{{ sticki_expiration }}"

    health_check:
      ping_protocol: "https"
      ping_port: "443"
      ping_path: "/"
      response_timeout: "300"
      interval: "5"
      unhealthy_threshold: "10"
      healthy_threshold: "3"

    listeners:
      - protocol: https
        load_balancer_port: 443
        instance_protocol: "8080"
        instance_port: "{{ item.instance_port }}"
        # proxy_protocol: True
        ssl_certificate_id: "{{ ssl_certificate_arn }}"

```

**Comment by willthames** [comment]
Please raise a new issue in ansible/ansible. This repo is no longer used, and this PR is closed.

**Pull request merged**
