### PR TITLE
iam: added assume_role_policy_document support to create_role

### PR DESCRIPTION
**Pull request by captainkerk**
An alternative to: https://github.com/ansible/ansible-modules-core/pull/2657

This seeks to create the same result as the PR above. However, it differs in using straight YAML to pass assume_role_policy_document. Here's how the task definition would look:

```
- name: test
  iam:
    iam_type: role
    name: test5
    state: present
    assume_role_policy:
      Version: "2012-10-17"
      Statement:
        - Sid: test1
          Effect: Allow
          Principal: {'AWS': 'arn:aws:iam::xyz:root'}
          Action: 'sts:AssumeRole'
```

Thoughts?

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @captainkerk. @defionscode @seiffert please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
@defionscode @seiffert This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
@defionscode @seiffert still waiting on your review.  Please comment with text 'shipit' or 'needs_revision' as appropriate. If we don't hear from you within 14 days, we will start to look for additional maintainers for this module.

**Comment by gregdek** [comment]
Thanks @captainkerk. @seiffert please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by juliedavila** [comment]
@captainkerk I like the idea of being able to use YAML, how open are you to also adding support for JSON? Basically copying the functionality of #2657 and adding the proper logic?

**Comment by captainkerk** [comment]
I'm ok with that. If you want to merge #2657, I'll pull those changes in and add the proper logic?

**Comment by juliedavila** [comment]
Sounds good, I'll add a new msg here when that part is ready. Thanks a lot!

**Comment by bcoca** [comment]
@defionscode if you support yaml that is automatically supporting json as it is a subset of yaml

**Comment by captainkerk** [comment]
Good point, I'm also just taking advantage of the options parser to convert the value of 'assume_role_policy' to json for me. So you can probably just pass JSON in as well. I'll test this later tonight.

**Comment by captainkerk** [comment]
You are right, giving assume_role_policy a json string works. Also, Jinja has the lookup filter, meaning it can get the policy from a file without the module having to read it.

the authorized key module is an example: http://docs.ansible.com/ansible/authorized_key_module.html

This PR accomplishes all 3 things (yaml formatted, json formatted and json formatted from file) already. 

```
- name: test_role1
  iam:
    iam_type: role
    name: test1
    state: present
    assume_role_policy:
      Version: "2012-10-17"
      Statement:
        - Sid: test1sid
          Effect: Allow
          Principal: {'AWS': 'arn:aws:iam::xyz:root'}
          Action: 'sts:AssumeRole'

- name: test_role2
  iam:
    iam_type: role
    name: test2
    state: present
    assume_role_policy: {"Version": "2008-10-17","Statement": [{"Effect": "Allow","Principal": {"AWS": "arn:aws:iam::xyz:root"},"Action": "sts:AssumeRole"}]}

- name: test_role3
  iam:
    iam_type: role
    name: test3
    state: present
    assume_role_policy: "{{ lookup('file', '/tmp/policy.json') }}"
```

**Comment by defionscode** [comment]
that totally skipped my mind. 

ship_it 

and then we should close #2657

**Comment by captainkerk** [comment]
Errr. Let me make a change to the option description.

**Comment by captainkerk** [comment]
Ok. Updated the description. @defionscode Maybe another shipit for good measure?

**Comment by defionscode** [comment]
shipit

**Comment by captainkerk** [comment]
Ping?

**Comment by gregdek** [comment]
Thanks @captainkerk for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

**Comment by juliedavila** [comment]
Going to do one more round of quick testing

**Comment by juliedavila** [comment]
Hmm doesnt seem to work when I use any of your examples. I get 

```
fatal: [localhost]: FAILED! => {"changed": true, "failed": true, "msg": "BotoServerError: 400 Bad Request\n<ErrorResponse xmlns=\"https://iam.amazonaws.com/doc/2010-05-08/\">\n  <Error>\n    <Type>Sender</Type>\n    <Code>MalformedPolicyDocument</Code>\n    <Message>Unknown field Principal    </Message>\n  </Error>\n  <RequestId>f276dca1-f064-11e5-9b14-8b0032fa7a40</RequestId>\n</ErrorResponse>\n"}
```

I'm going to try and get a basic policy from AWS to test again

**Comment by juliedavila** [comment]
Also tried with the following structure and got the same error:

``` yml
          Version: "2012-10-17"
          Statement: 
            - 
              Effect: "Allow"
              Action: 
                - "execute-api:Invoke"
              Resource: "arn:aws:execute-api:*:*:*"
```

I just did a simple json to yaml conversion from a stock policy on AWS.

Note, I am on the latest checkout

```
ansible 2.1.0 (devel a60cb570aa) last updated 2016/03/22 15:15:56 (GMT -400)
  lib/ansible/modules/core: (captainkerk-devel c803a4c046) last updated 2016/03/22 15:16:36 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 317654dba5) last updated 2016/03/11 13:12:24 (GMT -400)
  config file =
  configured module search path = Default w/o overrides
```

**Comment by captainkerk** [comment]
```
Unknown field Principal
```

My examples do not have a valid Principal

Principal: {'AWS': 'arn:aws:iam::xyz:root'}

'xyz' needs to be a valid account number, most likely your account number.

I omitted mine because well, no one needs to know that.

**Comment by juliedavila** [comment]
Ah, gotcha, retesting, thanks

**Comment by captainkerk** [comment]
For your second example, it appears you are conflating Trust Relationships with the Role's actual permissions.

assume_role_policy is for managing the 'Trust Relationship' on a IAM Role. This translates to who/what can assume the role. Be it the EC2 service, or IAM user/group or whatever. 

http://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_manage_modify.html

**Comment by juliedavila** [comment]
Yep, good catch.

Retried with 

``` yml
    - name: test_role1
      iam:
        iam_type: role
        name: testing2864-1 
        state: present
        assume_role_policy:
          Version: "2012-10-17"
          Statement: 
            - Sid: ""
              Effect: "Allow"
              Principal: 
                Service: "lambda.amazonaws.com"
              Action: "sts:AssumeRole"
```

Received an invalid json error
fatal: [localhost]: FAILED! => {"changed": true, "failed": true, "msg": "BotoServerError: 400 Bad Request\n<ErrorResponse xmlns=\"https://iam.amazonaws.com/doc/2010-05-08/\">\n  <Error>\n    <Type>Sender</Type>\n    <Code>MalformedPolicyDocument</Code>\n    <Message>This policy contains invalid Json</Message>\n  </Error>\n  <RequestId>4ff6a543-f067-11e5-82a4-07b351704ece</RequestId>\n</ErrorResponse>\n"}

**Comment by captainkerk** [comment]
Yikes... that works for me...

I just did a straight copy/paste... as far as i can tell your example is formatted correctly?

I also put that in json:

```
assume_role_policy: {"Version": "2012-10-17","Statement": [{"Sid": "","Effect": "Allow","Principal": {"Service": "lambda.amazonaws.com"},"Action": "sts:AssumeRole"}]}
```

and that worked too. 

I'm not sure where to go from here?

**Comment by juliedavila** [comment]
Are you on the latest devel checkout? If so I'll double check I'm not doing anything funky on my end.

**Comment by captainkerk** [comment]
Just tried again from latest devel, it's still working for me.

**Comment by captainkerk** [comment]
ping?

**Comment by gregdek** [comment]
@captainkerk sorry, sometimes PRs in core review can take a while. @defionscode does this need revision?

**Comment by gregdek** [comment]
Thanks @captainkerk for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by captainkerk** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @captainkerk for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by elnur** [comment]
Come on, guys. Need this.

TBH, as soon as I started using Ansible for AWS, I became very disappointed to find it lacks so many things only to find that there's a ton of open PRs that solve those issues and some of them don't get merged for longer than half a year. That sucks, guys. :angry: It has to change.

**Comment by bcoca** [comment]
@elnur testing and debugging these PRs would help get them merged sooner.

**Comment by gregdek** [comment]
Thanks @captainkerk for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@captainkerk A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@captainkerk Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by captainkerk** [comment]
So https://github.com/ansible/ansible-modules-core/pull/3885/ does the same thing.

It was merged (in about a day).

Thanks for a really disappointing first experience with contributing to Ansible.

**Pull request closed without merging**
