### PR TITLE
cron module: add enviroment variables management

### PR DESCRIPTION
**Pull request by lberruti**
Creates an entry like "PATH=/opt/bin":
- cron: name="set PATH environment" special_time=env job="PATH=/opt/bin"

see closed pr #8772 on ansible project.

### CODE REVIEW

**Comment by AnneTheAgile** [comment]
Cross-refs;
[1] The item referenced above, https://github.com/ansible/ansible/pull/8772
[2] Similar/related #50 
// AnneTheAgile

**Comment by Jared-Prime** [comment]
@mpdehaan what is the status of this feature? I ran into a situation where it might have been useful.

**Comment by bcoca** [comment]
after looking at the implementation, I don't like the hijacking of the special_time argument, it makes sense to have it's own env= that takes a dictionary as an argument (key: values).

**Comment by Jared-Prime** [comment]
@bcoca I see what you mean. I'll have to study the code to fully grok how to pass in a set key:value for this setting. Thanks! This is a good answer to my question, and a nice dive into Ansible internals

**Comment by lberruti** [comment]
First retry: moved "env" logic outside special_time.

```
# Creates an entry like "PATH=/opt/bin"
- cron: name="set PATH environment" env=yes job="PATH=/opt/bin"
```

**Comment by dougluce** [comment]
I needed a little more functionality: https://github.com/ansible/ansible-modules-core/pull/923

**Comment by gregdek** [comment]
So the question is: does the functionality here:

https://github.com/ansible/ansible-modules-extras/pull/416

...supersede the functionality included in this PR? 

@dsummersl as author here, do you have an opinion about whether we should close this PR in favor of extras/416?

**Comment by bcoca** [comment]
IMHO this was always a better solution

**Comment by gregdek** [comment]
@bcoca "this" meaning the extras module?

**Comment by bcoca** [comment]
no, this PR

**Comment by gregdek** [comment]
OK. After a bit more discussion, although there's some functionality in Extras to do some of this, we'd like to see this module completed. @bcoca will review the latest for inclusion as he has time.

**Comment by dsummersl** [comment]
My sentiments align with @bcoca.

**Comment by allenluce** [comment]
Combining variable and job management into a single module would be nice.

The current approach in this PR is clunky as variables are considered peer to jobs but don't fit well into the same syntax as jobs (most parameters are disallowed for vars).

It would be way better to have the syntax be an add-on to jobs. Instead of having:

```
- cron: name="set PATH environment" env=yes job="PATH=/opt/bin"
- cron: name="set DIR environment" env=yes job="MAILTO=/etc"
- cron: name="check dirs" hour="5,2" job="ls -alh > /dev/null"
- cron: name="find files" hour="12" job="find $DIR"
```

Combine into:

```
- cron:
    name: check dirs
    hour: 5,2
    job: ls -alh > /dev/null
    job_env:
        PATH: /opt/bin
- cron:
    name: find files
    hour: 12
    job: find $DIR
    job_env:
        DIR: /etc
        PATH: /opt/bin
```

(I wouldn't use plain env for the variable specifier, it's semantically overloaded for environment variables at execution time.)

It should also do the other things that my PR does:
1. Allow for ordering of variables so vars can be safely defined in terms of other vars
2. Key on variable name alone.  The current PR does not allow for updating of variable values.  If you specify a new value, it'll add the entire definition.
3. Don't mark the variable entry with a comment as is done for a job.

**Comment by tersmitten** [comment]
Great feature!

**Comment by lberruti** [comment]
I can change the behaviour as:

```
# create PATH at top of crontab
- cron: name="PATH" env="/opt/bin"
# create DIR at top of crontab
- cron: name="DIR" env="/etc"
# Normal cronjobs
- cron: name="check dirs" hour="5,2" job="ls -alh > /dev/null"
- cron: name="find files" hour="12" job="find $DIR"
```
1. job and env params are mutually exclusive
2. when using env, name is also the name of the environment variable, env is the value

After this, I can also work on variable ordering (something like insert_after="job name")

Let me know what you think/like

**Comment by gregdek** [comment]
Honestly, it would probably be best to wait on more changes until we can get this one PR resolved, as it's been open quite a long time. Will wait on @bcoca to make a judgement call here (be patient, he's at a conference, it may take a few days more yet.)

**Comment by bcoca** [comment]
@iberruti sorry to do this soo late in the game, but @allenluce's proposal does seam much a cleaner interface, your rework comes close enough but changing env to job_env also sounds like the better option.

**Comment by gregdek** [comment]
So for clarity, @bcoca -- are you asking for a rewrite of this PR to adhere to @allenluce proposal?

**Comment by lberruti** [comment]
I left approach with "name and env as variable and value" because it is not consistent when state=absent: are we managing jobs or variables?

With this new commit the behavior differs when managing variables or jobs:
- When crontab jobs are managed: the module works as usual (comment + job entry)
- When environment variables are managed: no comment line is added, but, when the module needs to find/check the state, it uses the "name" parameter to find the environmentvariable definition line (such as the proposal made by @allenluce).

I've also added insertafter/insertbefore params.

**Comment by gregdek** [comment]
OK, this PR has undergone quite a bit of analysis / churn -- putting back into core_review to figure out how we should proceed with it.

**Comment by gregdek** [comment]
ping @ansible/core

**Comment by lberruti** [comment]
I rebased and submitted this as #2010, this PR can now be closed.

**Comment by AnneTheAgile** [comment]
Very exciting! looking forward to the merge.

**Pull request closed without merging**
