### PR TITLE
decode run_command bytes out to native text

### PR DESCRIPTION
**Pull request by alikins**
##### ISSUE TYPE

- Bugfix Pull Request
##### COMPONENT NAME

file/synchronize.py
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel 5bc3cb278c) last updated 2016/10/03 08:42:50 (GMT -400)
  lib/ansible/modules/core: (detached HEAD e4c5a13a7a) last updated 2016/10/03 08:42:50 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD df35d324d6) last updated 2016/10/03 08:42:50 (GMT -400)
  config file = /home/adrian/ansible/ansible.cfg
  configured module search path = Default w/o overrides

``
```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @alikins for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by tima** [comment]
I trust you know what you're doing @alikins. ;)

shipit

**Comment by gregdek** [comment]
Thanks again to @alikins for this PR. This PR was reviewed by an Ansible member. Marking for inclusion.

However, we would still appreciate if the maintainer(s) @ansible could look over it.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by alikins** [comment]
Going to close this, as it's no longer necessary with https://github.com/ansible/ansible/commit/ddd20627a4f554eef16d89de2f7c9e4162a5af5f

**Pull request closed without merging**
