### PR TITLE
Do instance update before get_instance_info.

### PR DESCRIPTION
**Pull request by wangqiang8511**
Fix issue 1302.
Do update before get_instance_info to get instance tags.

### CODE REVIEW

**Comment by bennojoy** [comment]
@wangqiang8511 Could you please resolve the conflicts .. thanks

**Comment by wangqiang8511** [comment]
The conflicts are resolved.

**Comment by bennojoy** [comment]
@wangqiang8511 sorry could you also please sqash it into a single commit,.. thanks

**Comment by wangqiang8511** [comment]
Hi, resubmit pull request #1414 .
Please ignore this one.

**Pull request closed without merging**
