### PR TITLE
Remove redundant code in command module

### PR DESCRIPTION
**Pull request by dagwieers**
##### ISSUE TYPE

- Feature Pull Request
##### COMPONENT NAME

command / shell
##### ANSIBLE VERSION

v2.2

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @dagwieers for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by dagwieers** [comment]
@gregdek This is a quick cleanup. Should be easy to determine if this is wanted or not. (redundant unused code)

**Comment by gregdek** [comment]
Ping @ansible/core team -- maybe you can make this determination quickly.

**Comment by gregdek** [comment]
Thanks @dagwieers for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by dagwieers** [comment]
Rebasing since #4526 stole half of my thunder :-)

**Comment by dagwieers** [comment]
@abadger Can you merge the second half of the original patch (i.e. these remaining bits).

**Comment by dagwieers** [comment]
That was quick ! Thanks.

**Pull request merged**
