### PR TITLE
ansible-modules-core Issue #1252

### LINKED ISSUE #464: mount documentation does not match code
I'm reopening issue [#7791 from the main ansible repo](https://github.com/ansible/ansible/issues/7791) by @mpdehaan's instructions.
I'll paste the original issue as is - I hope that's ok with @shaunbrady (who opened the original issue).

---

There seems to be a mismatch with regard to the documentation/behavior of the mount modules.

**Issue Type:**

“Bug Report”, “Documentation Report”

**Ansible Version:**

$ ansible --version
ansible 1.6.1 _[@ozkatz: also true in 1.8.2]_

**Environment:**

N/A

**Summary:**

Looking from line https://github.com/ansible/ansible-modules-core/blob/devel/system/mount.py#L277
we see that "absent" is suppose to "remove from fstab and unmounted", and the code appears to reflect this. As well "unmount" is suppose to "not change fstab state, but unmount" and the code appears to reflect this.

On the documentation page http://docs.ansible.com/mount_module.html we read:

"If mounted or unmounted, the device will be actively mounted or unmounted as well as just configured in fstab. absent and present only deal with fstab. mounted will also automatically create the mount point directory if it doesn't exist. If absent changes anything, it will remove the mount point directory."

The code and documentation for "unmount" and "absent" are in contention.

**Steps To Reproduce:**

Review code/documentation at provided links.

**Expected Results:**

I expect that the documentation would be the correct way for the software to behave. It seems to be the most extensible. Either way, consistency is more important.

**Actual Results:**

The code and documentation for "unmount" and "absent" are in contention.

I would be happy to provide a pull request for documentation or for code, but I wanted to see which (or both) were to be changed.

Thank you.

SB

### LINKED ISSUE #1252: mount module creates fstab entry even if it cannot mount a volume
`mount` module creates a new entry in `/etc/fstab` even if it cannot mount that particular volume. For me this doesn't make any sense. The module should first try to mount the passed mount point and only if it succeeds should update fstab.

### PR DESCRIPTION
**Pull request by blackreed9**
Refactored the code and documentation to match the following criteria:

absent = remove from fstab
present = add to fstab
mounted = add to fstab, create mount point (if needed), mount (remount is existing and changed)
unmounted = remove from fstab, unmount, remove mount point

The code will now remove added fstab entries on failure to mount. ( Fixes #1252  )

By aligning the documentation with the code this would also fixes #464

As a side effect of refactoring the mounted files system detection it will now unmount bind mount file systems

### CODE REVIEW

**Comment by bcoca** [comment]
Future note: at one point I think we should move mounted/unmounted to an enabled=yes/no and have them not touch fstab, but do create mount point if needed or make that an extra flag. This would give the user fine grained control and be more in line with other ansible modules.

@blackreed9 ignroe the above for this PR, it will probably be added 'as is' but i wanted to record my thoughts about this.

**Comment by blackreed9** [comment]
I was thinking about something very similar.  This would allow user's to unmount clients while they did server maintenance and avoid things like stale NFS handles.  Let me know and I can add a feature request, if that helps.

**Comment by gregdek** [comment]
@blackreed9 Thanks for submitting this pull request. Please accept our apologies for taking so long to review it.

Unfortunately, due to this delay, it appears that the underlying code has changed, and this PR needs to be rebased. If you believe that this PR still applies, please rebase and we will then put it into our (new, faster) community review process as soon as possible.  Again, apologies for the delay and the extra work.

**Comment by kustodian** [comment]
I would be happy to test this one out, since I welcome the changes made. It would be awesome if you could rebase, so that I can start playing with it.

Also as @bcoca mentioned, it would be awesome if we split the mounting/umounting and updating fstab. Wouldn't it be more inline with other Ansible modules if `state=mounted/unmounted` would just mount/unmount, while a second paramter e.g. `update_fstab=yes/no` for manipulating fstab (or it could be `enabled=yes/no` so it's similar to the `service` module).

**Comment by gregdek** [comment]
@blackreed A friendly reminder: this pull request has been marked as needing your action, and it hasn't been updated in the last month. 

If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we'll keep it open pending your changes.

If we receive no indication from you within a week, we will close this pull request.

**Comment by gregdek** [comment]
Closed due to inactivity.

**Pull request closed without merging**
