### PR TITLE
Detect gnu versus bsd tar and act accordingly

### PR DESCRIPTION
**Pull request by jctanner**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

unarchive.py
##### ANSIBLE VERSION

```
2.2
```
##### SUMMARY

Detect if tar is gnu or bsd and then set the appropriate commands.

### CODE REVIEW

**Comment by jctanner** [comment]
@dagwieers any thoughts here? Were you already working on this?

**Comment by dagwieers** [comment]
Not working on this. The solution is pure-python, not more incompatible utilities to scrape output from IMO...

**Comment by dagwieers** [comment]
Problem with this implementation is also that it doesn't support extra_opts or exclude, and always seems to extract...

**Comment by gregdek** [comment]
Thanks @jctanner. To the current maintainers, @dagwieers, @pileofrogs please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by jctanner** [comment]
@dagwieers yep, still working on it.

**Comment by jctanner** [comment]
backing this out.

**Pull request closed without merging**
