### PR TITLE
Add master_data param to mysql_db state=dump

### PR DESCRIPTION
**Pull request by AlessandroLorenzi**
##### ISSUE TYPE

- Feature Pull Request
##### ANSIBLE VERSION

```
ansible 1.5.4
```
##### SUMMARY

```
Add the feature to add master data into a dump, usefull to create a slave server.

For more infos: man mysqldump, line 344
```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @AlessandroLorenzi for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by AlessandroLorenzi** [comment]
hi @gregdek , I don't understand the error. Actually i don't find the error, it's the first time I use shippable or this kind of tools. Can you help me? 

thanks
Alessandro

**Comment by gregdek** [comment]
Hi @AlessandroLorenzi -- I can't see the shippable bug for some reason, but I'm going to guess it's because you've added a new feature without adding the version in which it's being added. In order to make sure people know which versions new features appear in, we ask you to document the version in which it appears. For this PR, the version should be 2.3, since that's the earliest we'll get this change in.  See line 70 for an example.

**Comment by AlessandroLorenzi** [comment]
hi @gregdek , it seems that i don't recive notifications mail. 

so, we are ready_for_review :)

**Comment by gregdek** [comment]
Thanks @AlessandroLorenzi. To the current maintainers, @Jmainguy please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by AlessandroLorenzi** [comment]
hello @Jmainguy ,

can you merge this?

**Pull request closed without merging**
