### PR TITLE
add correct SELinux file context for crontabs (#4511)

### PR DESCRIPTION
**Pull request by LukeShortCloud**
##### ISSUE TYPE

- Bugfix Pull Request
##### COMPONENT NAME

cron
##### ANSIBLE VERSION

```

```
##### SUMMARY

Before, if a user used the "cron" module, a file is manually created (not using the crontab command) leading to no SELinux permissions being applied. This would lead to the crontab not working with SELinux enabled.

A user's crontab file will now have the correct SELinux  file context of "unconfined_u:object_r:user_cron_spool_t:s0" applied.
https://github.com/ansible/ansible-modules-core/issues/4511

```

```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @ekultails. To the current maintainers, @dsummersl, @EvanK please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by mscherer** [comment]
Wouldn't it fail if selinux is not enabled ?

**Comment by LukeShortCloud** [comment]
I followed the same convention from the SELinux module to detect if the SELinux Python library is available. Source: [ https://github.com/ansible/ansible-modules-core/blob/devel/system/selinux.py ]. Only if the "selinux" class can be imported, then the permissions are corrected.

Also, I noticed I had accidentally used the wrong variable for the cron's file name/path. I pushed commit c3e1e97 to correct that. I tested with the root user and a non privileged user on a CentOS 7.2 box with SELinux enabled and disabled and it appears to be working.

```
# ls -lahZ /var/spool/cron/
drwx------. root root system_u:object_r:user_cron_spool_t:s0 .
drwxr-xr-x. root root system_u:object_r:var_spool_t:s0 ..
-rw-------. root root unconfined_u:object_r:user_cron_spool_t:s0 cloud-user
-rw-------. root root unconfined_u:object_r:user_cron_spool_t:s0 root
```

On a related note, I noticed that Ansible writes the cron file with the user and group being owned to root. As a user using "crontab -e", the file created will have the same permissions of 0600 but the user and group reflects their own (i.e., the cloud-user cron would be owned to the user and group cloud-user). This shouldn't cause any issues with the cron service (since it's run as root) but might be a low priority issue to match up Ansible to follow the cron standards.

**Comment by gregdek** [comment]
Thanks @ekultails for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by LukeShortCloud** [comment]
When looking at the shippable logs [ https://app.shippable.com/runs/57cc7d19ba8c190e00683979/summary ] it is 757.11 through 757.14 that appear to be in the red. Most of them said "No running build container to stop" in the "pull_job_image" section. I believe this was a temporary problem with being able to deploy Docker images to test the new code. Is there any way for me to retry the shippable tests?

**Comment by EvanK** [comment]
@ekultails You could squash these two commits into one, and force push the resulting commit...that should restart the build checks, I think?

**Comment by gregdek** [comment]
@ekultails A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by LukeShortCloud** [comment]
I had accidentally added a rogue tab on a blank line. I removed that and committed the code and it's finally deploying the docker nodes correctly this time around! 

@EvanK Your help is much appreciated. This is my first time contributing back to a project and I hope to become more active within the Ansible community. This is truly a great piece of software. Let me know if there's anything else I need to do from my end for this pull request.

**Comment by EvanK** [comment]
Looks good to me

@ansibot shipit

**Comment by gregdek** [comment]
Thanks again to @ekultails for this PR, and thanks @dsummersl, @EvanK for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by mscherer** [comment]
So I would be happy to merge, but reading the patch again, I think hardcoding the context is wrong.

And it should rather use the selinux.selinux_lsetfilecon_default function to restore the default context on the file, since this will then work with whatever policy we have.

**Comment by gregdek** [comment]
@ekultails A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by LukeShortCloud** [comment]
I am sorry for the long response, I did not realize that the patch needed another revision. 

I pulled the latest source code, adjusted my patch to simply have SELinux set the cron file back to the default fcontext permissions, verified it's working on a CentOS 7 box, and have pushed the changes.

**Comment by LukeShortCloud** [comment]
The latest patch is ready_for_review.

**Comment by dsummersl** [comment]
Looks good.
@ansibot shipit

**Comment by mscherer** [comment]
We can't, there is conflict :/

And the bot do not yet do automatic merging.

**Comment by dsummersl** [comment]
@ekultails, can you resolve the conflicts?

**Comment by LukeShortCloud** [comment]
I have been having difficulty with merging the latest updates from the upstream devel branch. I was able to finally pull the latest cron.py file from Git and added the SELinux crontab patch. This is now ready_for_review again.

**Comment by gregdek** [comment]
Thanks @ekultails. To the current maintainers, @dsummersl, @EvanK please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by EvanK** [comment]
shipit

**Comment by gregdek** [comment]
Thanks again to @ekultails for this PR, and thanks @dsummersl, @EvanK for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request merged**
