### PR TITLE
fixes to iam group variables and delete group fixes

### PR DESCRIPTION
**Pull request by toninog**
please have a look @defionscode 

The group --> groups is already merge in the devel branch.  So it is just these changes that are needed.

Thanks

### CODE REVIEW

**Comment by bcoca** [comment]
you are just changing the functions to named params from positional?

**Comment by toninog** [comment]
Yes.  Else you get errors related to number of parameters fed to the function.  I had to re-submit the PR at the request of @defionscode

**Comment by toninog** [comment]
@defionscode this ok ?

**Comment by toninog** [comment]
@bennojoy could you please review this ?

Thanks

**Comment by toninog** [comment]
@bennojoy could you please review this ?

**Comment by bennojoy** [comment]
@toninog  sure. will have a look shortly

**Comment by bennojoy** [comment]
@toninog  merged thanks

**Pull request merged**
