### PR TITLE
Add evaluate taget health for alias based records

### PR DESCRIPTION
**Pull request by jimbydamonk**

### CODE REVIEW

**Comment by gregdek** [comment]
@jimbydamonk Thanks for submitting this pull request. Unfortunately, it appears that the underlying code has changed since your submission, and this PR now needs to be rebased. 

If you believe that this PR still applies, please rebase and we will put it into our community review process as soon as possible. 

Once you have rebased this PR, please add a comment with the text "ready_for_review" and we will continue with the review process.  Thanks!

**Comment by jimbydamonk** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @jimbydamonk. @bpennypacker please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
@bpennypacker This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by robynbergeron** [comment]
@bpennypacker still waiting on your review.  Please comment with text 'shipit' or 'needs_revision' as appropriate. If we don't hear from you within 14 days, we will start to look for additional maintainers for this module.

**Comment by bpennypacker** [comment]
shipit

**Comment by gregdek** [comment]
Thanks again to @jimbydamonk for this PR, and thanks @bpennypacker for reviewing. Marking for inclusion.

**Pull request merged**
