### PR TITLE
dnos9_config (New Module)

### PR DESCRIPTION
**Pull request by skg-net**
##### ISSUE TYPE
- New Module Pull Request
##### COMPONENT NAME
- modules/core/network/dnos9/dnos9_config.py
  ##### ANSIBLE VERSION
  ansible 2.2.0 (devel a1947401ba) last updated 2016/09/08 17:44:28 (GMT -700)
  lib/ansible/modules/core: (detached HEAD db38f0c876) last updated 2016/09/08 17:44:58 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD 8bfdcfcab2) last updated 2016/09/08 17:44:58 (GMT -700)
  config file = /home/skg/lothlorien/ansible.cfg
  configured module search path = Default w/o overrides
##### SUMMARY
- Added support for dnos9_config module to support Dell Networking OS9 devices.

### CODE REVIEW

**Comment by skg-net** [comment]
@privateip @gundalow , please take a look at it.

Ansible PR: https://github.com/ansible/ansible/pull/17546

Test PR: https://github.com/ansible/test-network-modules/pull/14

**Comment by gregdek** [comment]
Thanks @skg-net for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gundalow** [comment]
Please apply the same fixes as in mentioned in https://github.com/ansible/ansible-modules-core/pull/4824

needs_revision

**Comment by skg-net** [comment]
ready_for_review

**Comment by gundalow** [comment]
shipit

**Comment by gregdek** [comment]
Thanks again to @skg-net for this PR, and thanks @ansible/core for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gundalow** [comment]
Merged, thanks

**Pull request merged**
