### PR TITLE
Fixes: #2408 Add docker image buildargs

### LINKED ISSUE #2408: docker_image: support --build-arg parameter (docker 1.9)
Docker 1.9 offers a new command line parameter to customize the Dockerfile at the build time:

> The ARG instruction defines a variable that users can pass at build-time to the builder with the docker build command using the --build-arg <varname>=<value> flag.
> https://docs.docker.com/engine/reference/builder/#arg

### PR DESCRIPTION
**Pull request by hcpss-banderson**
##### ISSUE TYPE

- Feature Pull Request
##### COMPONENT NAME

docker_image
##### ANSIBLE VERSION

```
"ansible 2.2.0 (devel 8680cc7156) last updated 2016/05/16 14:29:58 (GMT +000)
  lib/ansible/modules/core: (add_docker_buildargs 40602fbc57) last updated 2016/05/16 18:16:35 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD f953d5dc0c) last updated 2016/05/16 14:31:36 (GMT +000)
  config file = 
  configured module search path = Default w/o overrides"
```
##### SUMMARY

Fixes #2408 feature idea to add support for build arguments which are now supported by [docker](https://docs.docker.com/engine/reference/builder/#arg) and [docker-py](https://github.com/docker/docker-py/commit/5571d1af76fe5c6a446b73024c07bc4c66661c05#diff-e1d542dae5b9c86ba6a8242ebd3f5df6) option to docker_image.

This is based on the work of @leonty in #2699 that is closed.

### CODE REVIEW

**Comment by chouseknecht** [comment]
This looks to be the same as https://github.com/ansible/ansible-modules-core/pull/3665

**Comment by gregdek** [comment]
Thanks @hcpss-banderson for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @hcpss-banderson for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by hcpss-banderson** [comment]
Duplicate of #3665

**Pull request closed without merging**
