### PR TITLE
Updated 'stat' module examples to use 'failed_when' syntax

### PR DESCRIPTION
**Pull request by jeffwidman**
Just made the examples a little cleaner using the newer syntax

### CODE REVIEW

**Comment by bcoca** [comment]
not that these examples were made for displaying error conditions, the debug is just to show the info, the fail allows for custom failure message. I would add a example with failed when but not remove the existing ones.

**Comment by gregdek** [comment]
@jeffwidman Please make the suggested revisions, and when you're done, please add a comment with the text "ready_for_review" and we will continue with the review process.  Thanks!

**Comment by gregdek** [comment]
@jeffwidman A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes.

**Comment by jeffwidman** [comment]
Thanks for the reminder. 

After looking at this a little more, I'm not too excited about keeping the existing error messages as I think the `failed_when` is what most people should use if they're writing a `stat` task. 

The custom error messages are a little more advanced and don't need to be documented here as they're a separate `fail` task and anyone who wants them can just search for 'how to produce custom error message ansible'. 

Not a big deal, just my personal opinion. Go ahead and close this PR if you prefer to keep existing examples.

**Comment by bcoca** [comment]
they are just very simple examples on how to use the stat module with other modules,

**Pull request closed without merging**
