### PR TITLE
Fixed delete statement for juniper_config.py #4007

### PR DESCRIPTION
**Pull request by stianvi**
##### ISSUE TYPE

- Bugfix Pull Request
##### COMPONENT NAME

network/junos/junos_config.py
##### ANSIBLE VERSION

```
ansible 2.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

Changed if-loop so it checks towards current configuration correctly.

Before:

```
PLAY [Create vlan] *************************************************************

TASK [Delete vlan on Juniper Junos] ********************************************
ok: [netlab-sw01-a.osl.basefarm.net]

PLAY RECAP *********************************************************************
netlab-sw01-a.osl.basefarm.net : ok=1    changed=0    unreachable=0    failed=0   
```

After:

```
PLAY [Create vlan] *************************************************************

TASK [Delete vlan on Juniper Junos] ********************************************
changed: [netlab-sw01-a.osl.basefarm.net]

PLAY RECAP *********************************************************************
netlab-sw01-a.osl.basefarm.net : ok=1    changed=1    unreachable=0    failed=0  
```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @stianvi. To the current maintainers, @privateip please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by privateip** [comment]
This doesn't quite solve the bug.   Delete statements are slightly different from set statements in that they should account for partials lines.  Consider the following stanza:

```
system {
    name-server {
        8.8.8.8;
        8.8.4.4;
    }
```

Handling of the delete line must satisfy the each of the following (all valid):

```
delete system name-server 8.8.8.8
delete system name-server
```

The first deleting a single name server, the second deleting all name servers.   This fix does not address the second use case.

**Comment by stianvi** [comment]
My test it did accept partial lines. I only check if the content match some parts of the lines, not the beginning or the start. 

`
lines:
- delete system name-server 8.8.8.8
- delete system name-server
  `

Before:

```
{master:0}
stianv@netlab-sw01-a> show configuration | match name-server | display set
set system name-server 8.8.8.8
set system name-server 8.8.4.4
```

After:

```
{master:0}
stianv@netlab-sw01-a> show configuration | match name-server | display set
```

If you want to use startswith then you'll need to remove "set " away from cfg. I can't see a nice way to do this..

```
-if cfg[4:].startswith(cfgline):
-    updates.add(cfgline)
```

**Comment by privateip** [comment]
Partial tests have to be done from the beginning of the the line otherwise you will have false positives.  Add the change as above to remove the "set " and the fix should be valid then.

**Comment by Royce92** [comment]
You are using ansible tower 2.2, this bug is still being reported on ansible v2.1

**Comment by rromanyak** [comment]
I'm running ansible 2.1.2.0 and delete command wasn't working for me. I looked a the code an saw the typo in 'delete' elif line. After correcting it, delete commands work:

Before:

```
    elif action == 'delete' and not config:
        updates.add(line)
```

After:

```
    elif action == 'delete' and cfgline not in config:
        updates.add(line)
```

**Comment by stianvi** [comment]
@rromanyak could you give me an example on what you are trying to delete?
Seems to me the elif isn't needed, since if it isn't in the config - then what is the point of adding the delete statement?
I'll look into this when I get more info - or you could create a PR and the ansible team would probably push the change pretty quick.

**Comment by rromanyak** [comment]
I was just trying to delete a static route or anything else (tried also to delete a term in a policy). The playbook didn't give any error but also didn't change anything. 

This is the playbook:

---
- hosts: test_routers
  connection: local
  gather_facts: no
  
  tasks:
  - name: Run set command
    junos_config:
      host: "{{ inventory_hostname }}"
      username: automation
      confirm: "{{confirm}}"
      lines: ["{{CLI}}"]

**Pull request closed without merging**
