### PR TITLE
Don't assume ExposedPorts exists (bug #2257)

### PR DESCRIPTION
**Pull request by ghost**
A recent change [1] in docker between v1.8.2 and v1.8.3 changed what
is returned in the json when inspecting an image. Five variables which
could have been expected before will now be omited when empty. Only
one of those variables is being addressed in the docker, ExposedPorts.

Unfortunately there was also no API version change on this so this
can't be easily corrected with pinning the API to the older version.

This does a get() which will return None if the variable is not in the
dict formed from the json that was returned. Everything else works the
same way.

[1] https://github.com/docker/docker/commit/9098628b2901ae8585ba4c66ee6e14759d2119da

### CODE REVIEW

**Comment by brk3** [comment]
+1

**Comment by nhlfr** [comment]
+1

**Comment by robynbergeron** [comment]
Greetings, @SamYaple :)  Thanks for filing this PR, and for filing the initial bug report.  #2257 

@cove @smashwilson @softzilla @joshuaconner -- Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by robynbergeron** [comment]
Also -- @brk3 @nihilifer @magnars @Glueon -- thanks for confirming that this fix is helping you out, much appreciated!

**Comment by mandre** [comment]
I was just hit by this bug, I'm going to stick with docker 1.8.2 for now.

Like @SamYaple said, it's a safe change that ensures consistent behavior between different versions of docker.

**Pull request merged**
