### PR TITLE
Rackspace: Add wait and wait_timeout options for provisioning servers to Auto Scale

### PR DESCRIPTION
**Pull request by jamiehannaford**
We support the `wait` param in provisioning servers, but not currently for auto scale groups. This PR introduces it, by waiting for the `pendingCapacity` attr to reach zero.

### CODE REVIEW

**Comment by sivel** [comment]
@jamiehannaford this PR needs a rebase.  The `author` line in `DOCUMENTATION` changed which is throwing off the diff.

I now have a full set of integration tests for this module, which should help me test more quickly now.

**Comment by jamiehannaford** [comment]
@sivel I've rebased; sorry this took such a long time!

**Comment by gregdek** [comment]
@sivel any time to review here?

**Comment by sivel** [comment]
Merged, thanks!

**Pull request merged**
