### PR TITLE
replace_batch_wait parameter for ec2_asg module. a wait between batches

### PR DESCRIPTION
**Pull request by ferrants**
We ran into an scenario, specific to our set up, where we wanted extra time between each batch, to make sure everything had stabilized. Adding this wait between batches gave us the stability we were looking for.

### CODE REVIEW

**Comment by jsmartin** [comment]
Can you describe what you mean by stabilized?  If you are using it in conjunction with an ELB healthcheck, you could use that as the indicator the instance is healthy.

**Comment by ferrants** [comment]
We are using it with ELB health checks, and the instances come online and they are ready. The instance's cache takes a little while to warm up, so it was desired that we have a wait between batches so only one batch is warming up at a time. We could add a wait to the instances before they report healthy, but we want them to start serving traffic immediately.

**Comment by gregdek** [comment]
@ferrants Thanks for submitting this pull request. Please accept our apologies for taking so long to review it.

Unfortunately, due to this delay, it appears that the underlying code has changed, and this PR needs to be rebased. If you believe that this PR still applies, please rebase and we will then put it into our (new, faster) community review process as soon as possible.  Again, apologies for the delay and the extra work.

**Comment by ferrants** [comment]
I will update this and https://github.com/ansible/ansible-modules-core/pull/534 next week

**Comment by ferrants** [comment]
@gregdek - rebased. my editor also did some whitespace cleanup. let me know if that cleanup should be reverted and I'll pull it out.

**Comment by gregdek** [comment]
Thanks @ferrants!

@garethr Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please give it a +1; at that point, we will add the “priority_reviewed” flag to this PR, which will move it to the top of our queue for potential inclusion.

**Comment by OlegIakovlev** [comment]
:+1:

**Comment by pbuckley** [comment]
:+1:

**Comment by gregdek** [comment]
Sigh. Sorry @ferrants but it looks like this needs rebasing again.

If you believe that this PR still applies, please rebase and we will put it into our community review process as soon as possible. 

Once you have rebased this PR, please add a comment with the text "ready_for_review" and we will continue with the review process.  Thanks!

**Comment by ferrants** [comment]
@gregdek rebased and ready_for_review. I see the addition of the `default_cooldown` option and though I think there are some similarities to the `replace_batch_wait` option, the `replace_batch_wait` option is specific to use during the deployment, not for regular autoscaling use.

**Comment by gregdek** [comment]
Thanks @ferrants. 

@garethr Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by jsmartin** [comment]
I think we'll need to change the "added in 1.9" to "added in 2.0".  After that, +1 from me.

**Comment by ferrants** [comment]
@jsmartin made it 2.0

**Comment by jsmartin** [comment]
+1

**Comment by ferrants** [comment]
@jsmartin - trying to do some PR cleanup. Is this waiting on anything to be merged?

**Comment by gregdek** [comment]
Thanks @ferrants for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

**Comment by ferrants** [comment]
@gregdek rebased

ready_for_review

**Comment by gregdek** [comment]
Thanks @ferrants. @garethr please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
Thanks @ferrants. @garethr please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by ferrants** [comment]
@garethr @gregdek any chance I can get this merged? Happy New Year!

**Comment by gregdek** [comment]
Reassigning to @ansible/core for their review. Sorry @ferrants for the delay.

**Comment by ferrants** [comment]
@ansible/core could i get a review/merge?

**Comment by gregdek** [comment]
Thanks @ferrants for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by ferrants** [comment]
Idk, it's been open for a long time. I'm just going to give up on this PR, and contributing features to ansible in general. I really like working with ansible, but you guys are very slow to get new features merged, no offense. Bug fixes are merged in a more reasonable timeline.

**Pull request closed without merging**
