### PR TITLE
fix type issue

### LINKED ISSUE #3078: cloud/docker: creation of containers not possible because of "Could not convert 0 to integer" exception
##### Issue Type:
- Bug Report
##### Plugin Name:

cloud/docker
##### Ansible Version:

```
ansible 2.1.0
```
##### Environment:

Fedora 23
##### Summary:

Trying to create a Docker container fails with the following exception:

```
FAILED! => {"changed": false, "failed": true, "msg": "Could not convert 0 to integer"}
```

Issue is in method `_human_to_bytes` (https://github.com/ansible/ansible-modules-core/blob/devel/cloud/docker/docker.py#L531-L545).

Explicitly setting `memory_limit` parameter does not solve the issue. 
##### Steps To Reproduce:

```
- name: start a hello world container
  docker:
    name: container
    image: hello-world
```
##### Expected Results:

A running container.
##### Actual Results:

```
FAILED! => {"changed": false, "failed": true, "msg": "Could not convert 0 to integer"}
```

### PR DESCRIPTION
**Pull request by ThomasSteinbach**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

cloud/docker
##### ANSIBLE VERSION

```
ansible 2.1.0 (docker_module_type_fix 2cb24987e1) last updated 2016/04/20 01:05:06 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 98322a777f) last updated 2016/04/20 00:36:48 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 1aecfc1e19) last updated 2016/04/20 00:36:48 (GMT +200)
```
##### SUMMARY

Fixes #3078 

Wrong types for a couple of variables defaults lead to an type conversion error (python says: "Could not convert '0' to integer")

### CODE REVIEW

**Comment by ThomasSteinbach** [comment]
This PR will not only fix Issue #3078 but also parts of Issue #1130 

However the changes are trivial but the bugs solved are severe and make the current state of the docker module practically unusable. I hope the changes are reviewed and shipped soon :)

**Comment by gregdek** [comment]
Thanks again to @ThomasSteinbach. This module is going into community review.

We notice that you are one of the maintainers (@cove, @softzilla, @smashwilson, @zfil, @ThomasSteinbach) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by ThomasSteinbach** [comment]
As it is a trivial change, not affecting the logic nor the documentation, I would say you can

shipit :shipit:

**Comment by gregdek** [comment]
Thanks @ThomasSteinbach. Since you are one of the maintainers (@cove, @softzilla, @smashwilson, @zfil, @ThomasSteinbach) of this module and you commented with "shipit", we are marking this PR for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by PikachuEXE** [comment]
So how do we specify `memory_limit` as human readable value alike `512MB`

**Pull request merged**
