### PR TITLE
Be explicit about specifying the ssh port if it was user specified

### LINKED ISSUE #3895: Synchronize: a problem with a non-standard ssh port
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

synchronize
##### ANSIBLE VERSION

```
<!--- Paste verbatim output from “ansible --version” between quotes -->
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

[defaults]
vault_password_file=.vault_pass.txt
##### OS / ENVIRONMENT

Ubuntu 16.04
##### SUMMARY

I have the following option in my /etc/ssh/ssh_config : 

```
 Port 2222
```

I want to sync some directory to a machine that has this address: 10.0.3.188:22.

I get an error 

```
 ssh: connect to host 10.0.3.188 port 2222: Connection refused
```

This [code](https://github.com/ansible/ansible-modules-core/blob/c52f475c64372042daab4ebc0660a2782b71d10d/files/synchronize.py#L414-L417) is responsible for this behavior. Why don't set port explicitly whatever its value is?

### PR DESCRIPTION
**Pull request by abadger**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

synchronize.py
##### ANSIBLE VERSION

```
devel

Probably affects all 2.x versions and possibly earlier
```
##### SUMMARY

Previously, if the port specified by the user or inventory was 22, then
the ssh client port would be used instead.

Fixes #3895

### CODE REVIEW

**Comment by abadger** [comment]
@tima, @dvzubarev see if this fixes the problem for you.

Note -- I changed the documentation to match what the code was doing when the dest_port is unspecified.  I didn't want to change the behaviour of the code too much because people might be relying on synchronize to pick up ssh client configuration when they didn't specify any port setting explicitly.

**Comment by gregdek** [comment]
Thanks @abadger. To the current maintainers, @tima please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by tima** [comment]
Looks right to me based on what we discussed. @dvzubarev?

**Comment by gregdek** [comment]
Thanks @abadger for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by tima** [comment]
@dvzubarev confirmed that this fixed the issue they reported in #3895. 

shipit

**Comment by abadger** [comment]
Merged to devel and cherry-picked to the stable-2.1 branch

**Pull request merged**
