### PR TITLE
Added 'backup' parameter to get_url module

### PR DESCRIPTION
**Pull request by techraf**
Cloned destination file **backup** functionality from **copy** module into **get_url**.

### CODE REVIEW

**Comment by robynbergeron** [comment]
Thanks @techraf. @jpmens please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by jpmens** [comment]
shipit

**Comment by robynbergeron** [comment]
Thanks again to @techraf for this PR, and thanks @jpmens for reviewing. Marking for inclusion.

**Comment by bcoca** [comment]
missing version added, but doing that after merge

**Pull request merged**
