### PR TITLE
Extend the htpasswd so it can use different hashes in addition to the 4 currently supported by Apache.

### PR DESCRIPTION
**Pull request by alexkingnz**
Extend hashes that can be specified by crypt_scheme beyond those understood by Apache/Nginx, without adding any extra module options.

### CODE REVIEW

**Comment by alexkingnz** [comment]
This PR is less intrusive and doesn't add an extra option to the module, sacrificing some functionality, copared with my other PR.

**Comment by abadger** [comment]
Previous PR https://github.com/ansible/ansible-modules-core/pull/459

**Comment by gregdek** [comment]
@lorin please review; if you give +1, we will tag P1_reviewed for faster inclusion.

**Comment by lorin** [comment]
+1

**Pull request merged**
