### PR TITLE
Remove the wide try/expect clause

### PR DESCRIPTION
**Pull request by mscherer**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

authorized_keys
##### SUMMARY

This doesn't catch anything precise, and none of the methods should
throw a expection for anything. This also hide python 3 errors.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @mscherer for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by mscherer** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @mscherer for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by abadger** [comment]
Merged to devel and stable-2.2

**Pull request merged**
