### PR TITLE
Updating nxos_interface

### PR DESCRIPTION
**Pull request by GGabriele**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

nxos_interface
##### ANSIBLE VERSION

```
ansible 2.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/share/ansible/']
```
##### SUMMARY

I've included a serie of python object to support both 2.1 and 2.2 and few more params: `interface_type`, `ip_forward` and `fabric_forwarding_anycast_gateway`.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks again to @GGabriele. This module is going into community review.

We notice that you are one of the maintainers (@privateip, @GGabriele, @gundalow) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @GGabriele for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by privateip** [comment]
needs_rebase

**Comment by GGabriele** [comment]
Closing this, reopened at #4850

**Pull request closed without merging**
