### PR TITLE
mount: Add option 'fail_when_not_empty', which prevents over mounting…

### PR DESCRIPTION
**Pull request by alxgu**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

mount.py
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel 3c65c03a67) last updated 2016/08/15 09:49:19 (GMT +200)
  lib/ansible/modules/core: (detached HEAD decb2ec9fa) last updated 2016/08/15 09:50:54 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 61d5fe148c) last updated 2016/08/15 09:51:04 (GMT +200)
  config file = /etc/ansible/ansible.cfg
```
##### SUMMARY

Add option which checks if the target mount point is empty. 

The fstab will be created when `state=mounted` but it won't mount it, when the target isn't empty.
The default value of the option is `false`

After change:

```
srv1 | FAILED! => {
    "changed": false,
    "failed": true,
    "msg": "Destination /tmp/ansible is not empty. Abort here to prevent over mounting."
}
```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @alxgu. To the current maintainers, @grossws please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by alxgu** [comment]
@grossws Could you have a look on the PR? Thanks in advance

**Comment by gregdek** [comment]
Thanks @alxgu for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by alxgu** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @alxgu. To the current maintainers, @grossws please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @alxgu for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@alxgu A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@alxgu Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by alxgu** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @alxgu for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @alxgu for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@alxgu A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
