### PR TITLE
Added support for deploying virtual machine from a virtual template

### PR DESCRIPTION
**Pull request by stewrutledge**
Added support for deploying guests from an existing template, including a bit of documentation on how it works.

### CODE REVIEW

**Comment by stewrutledge** [comment]
I'll get this fixed, it comes from an older version of the module that had the issue in it (this has come up in a few pull requests) but had been fixed since my original pull requests.

**Comment by bcoca** [comment]
also you'll need to rebase before I can merge

**Comment by stewrutledge** [comment]
Ah crap, my rebase didn't go so well apparently. I can kill this and make a new pull request.

**Comment by bcoca** [comment]
you can update the branch in github with --force, no need for a new PR

## 

Brian Coca

**Comment by stewrutledge** [comment]
I think the branch itself is updated, at least for the commit on this file, it's just that a lot of old commits seem to have come along instead of just my new commit.

I'm really new at the forking thing, so if I'm doing something wrong here I'd be more than happy to do it right!

**Comment by gnunchucks** [comment]
Is it necessary to force the use of a destination cluster when cloning from a template? It seems that the root resource pool always exists, but there are plenty of scenarios where someone would want to clone from template but not be utilizing a cluster.

**Comment by stewrutledge** [comment]
I would guess not no, I assume it can be done in a similar manner to the "create_vm" method (if resource_pool:).

I'll take a look at this next week when I have access to a vsphere instance.

**Comment by gnunchucks** [comment]
I just took a look at that section, that is exactly what I had in mind. Thanks for taking it into consideration.

**Comment by sebastienbonami** [comment]
@gnunchuks @stewrutledge I have a standalone ESXi host and I can't use the feature, because of the cluster parameter (that should be optional). Any updates?

**Pull request merged**
