### PR TITLE
posibility to change bootdevice on vsphere_guest

### LINKED ISSUE #2450: feature request - vmware boot device
##### ISSUE TYPE

Feature Idea
##### COMPONENT NAME

vsphere_guest
##### ANSIBLE VERSION

N/A
##### SUMMARY

Maybe is been asked before, but I could not find it.
We would have a good use for a boot device changing mechanism.
Scenario,
- we have automated way to create kickstart files
- we would like to reboot the machine to net booted and have it automatically installed.
- get a notification to Ansible the installation has finished and the machine would be rebooted in local disk

currently we can achieve this with a combination of vsphere_boot (custom edited) and pause featrure an watching the remote screen then after pause using again the vsphere_boot changes the boot device.
Thank you!

### PR DESCRIPTION
**Pull request by mihai-satmarean**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

ansible/ansible-modules-core/cloud/vmware/vsphere_guest
##### ANSIBLE VERSION

```
<!--- Paste verbatim output from “ansible 2.1.0.0” between quotes -->
```
##### SUMMARY

In our pxe boot environment we need to reinstall virtual machines and we need to set the boot device to **net** and then back to **hd**

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @mihai-satmarean for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@mihai-satmarean A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@mihai-satmarean Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by mihai-satmarean** [comment]
Hi, you just made me do my first PR rebase so thank you 
I hope I got it right and 'ready_for_review'

**Comment by gregdek** [comment]
Thanks @mihai-satmarean. To the current maintainers, @chrrrles, @rhoop please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @mihai-satmarean for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
