### PR TITLE
Fix issue #2721: os_object parameters and docs don't align (file/filename)

### PR DESCRIPTION
**Pull request by Labutin**
…name)

### CODE REVIEW

**Comment by j3p0uk** [comment]
As all of the other os_\* modules use "file", I think this should change the variable in the code rather than the documentation.

**Comment by Labutin** [comment]
os_image use "filename". Which module use "file" ?

**Comment by j3p0uk** [comment]
Sorry - my mistake. I thought I had seen file in use. Apologies.

Thanks,
JP ;-)

**Comment by robynbergeron** [comment]
Thanks @Labutin. @emonty @shrews @dguerri @juliakreger @j2sol @rcarrillocruz please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by juliakreger** [comment]
shipit

**Comment by robynbergeron** [comment]
Thanks again to @Labutin for this PR, and thanks @emonty @shrews @dguerri @juliakreger @j2sol @rcarrillocruz for reviewing. Marking for inclusion.

**Pull request merged**
