### PR TITLE
nxos module cleanup

### PR DESCRIPTION
**Pull request by Qalthos**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

nxos
##### ANSIBLE VERSION

```
2.2
```
##### SUMMARY

Addresses the nxos portion of #4860.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @Qalthos. To the current maintainers, @jedelman8, @GGabriele, @privateip, @gundalow please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by GGabriele** [comment]
@Qalthos , these modules are built in such a way to by fully compatible with both 2.1 and 2.2 . All the imports are needed.

**Comment by gregdek** [comment]
Thanks @Qalthos for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by GGabriele** [comment]
@Qalthos Have you tested these changes on both 2.1 and 2.2? As mentioned above, we need these modules compatible with 2.1 too. I've just tested one of these and it doesn't work on 2.1 .

@privateip @gundalow

**Comment by jedelman8** [comment]
This PR definitely needs to be reverted - sooner the better. Given tomorrow is Fest, anyway this can happen before it?

**Comment by Qalthos** [comment]
@GGabriele These changes are for 2.3, and should not be in the 2.2 branch, nor 2.1. A seperate changeset is being compiled for 2.2 and 2.1, but certain issues have proven more complicated to fix across the NetworkModule rewrite.

That said, if you truly need `devel` to remain compatible with 2.1 after we've branched 2.2... I'll see what can be done.

**Comment by gundalow** [comment]
2.2 has been branched

**Comment by privateip** [comment]
There is no reason to persist these changes beyond 2.2.  The 2.2 code has been branched into stable-2.2 and that should be working as we had agreed.  Changes committed to devel are now the beginning prep for the next release (2.3).  I see no reason to revert these changes.

**Comment by GGabriele** [comment]
This wasn't clear to me, my bad. We're good then.

**Comment by privateip** [comment]
No worries, all good :)  One thing to note though any bug fix PRs made in devel will need to be ported to stable-2.2 in a separate PR

**Pull request merged**
