### PR TITLE
Add a redhat_repos module to handle repos with subscription-manager

### PR DESCRIPTION
**Pull request by karmab**
##### ISSUE TYPE
- New Module Pull Request
##### COMPONENT NAME

redhat_repos
##### ANSIBLE VERSION

latest
##### SUMMARY

Add a redhat_repos module to handle repos with subscription-manager

```

```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @karmab for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by karmab** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @karmab for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by karmab** [comment]
anything more i can do to speed this up ?

**Comment by samdoran** [comment]
@karmab It looks like this module always returns a change. Is that the intent?

Also, I'm wondering if it would be better to enumerate the list of current repos with `subscription-manager repos --list-enabled` and then only add the ones that need to be added.

**Comment by samdoran** [comment]
Probably also worth looking at the `yum` module to see how it handles a list as input vs individual items via a loop efficiently. Currently, passing in a list of items via a loop results in multiple calls to `subscription-manager` and does not combine them together into a single operation. It takes ~11s per repository.

```
TASK [redhat-subscription : Configure repository subscriptions] ****************
Friday 11 November 2016  13:26:45 -0500 (0:00:02.468)       0:00:03.791 *******
changed: [rhel7] => (item={u'state': u'present', u'name': u'rhel-7-server-extras-rpms'})
changed: [rhel7] => (item={u'name': u'rhel-7-server-rh-common-rpms'})
changed: [rhel7] => (item={u'name': u'rhel-7-server-openstack-8-rpms'})

PLAY RECAP *********************************************************************
rhel7                      : ok=5    changed=1    unreachable=0    failed=0

Friday 11 November 2016  13:27:19 -0500 (0:00:34.679)       0:00:38.471 *******
===============================================================================
redhat-subscription : Configure repository subscriptions --------------- 34.68s
redhat-subscription : Manage Red Hat subscription ----------------------- 2.47s
redhat-subscription : Configure Red Hat subscirption manager ------------ 0.67s
setup ------------------------------------------------------------------- 0.59s
redhat-subscription : Check that this is Red Hat ------------------------ 0.03s
```

**Comment by karmab** [comment]
@samdoran actually no, there s a single call to subscription-manager
also speed is the reason why i dont check the current enabled repositories, hence changing every time the module is called.

**Comment by Fale** [comment]
I think that the fact of returning "ok" or "changed" in the proper way is more important than speed. my2cc

**Comment by evgeni** [comment]
Calling `subscription_manager` is quite expensive, as it will try to talk to whatever provides your subscriptions. But it also has an Python API (https://github.com/candlepin/subscription-manager/blob/master/src/subscription_manager/repolib.py#L707) which could be used here:

```python
>>> from subscription_manager.repolib import RepoFile
>>> x = RepoFile()
>>> x.read()
>>> x.get('rhel-7-server-satellite-6.2-rpms', 'enabled')
'0'
>>> x.get('rhel-7-server-satellite-6.1-rpms', 'enabled')
'1'
```

This would have the disadvantage that we do not update the list of *available* repos from our upstream distributor, but instead we're *a lot* quicker.

Thoughts?

**Comment by samdoran** [comment]
I think we need to take different approaches based on the combination of parameters passed to the module.

1) If `only: yes`, then list existing repos, diff with the list of declared repos, and create _one_ call to `subscription-manager` to enable and one to disable (or possible disable `*` how it is currently — not sure which is more expensive)

2) If a list of repos is passed without `only: yes`, either via a loop or directly as a list to the `repos` parameter, then construct a single call to `subscription-manager` (how it is currently).

Also need to account for passing multiple repos via a loop with differing state values as well as passing values that are regular expressions. Checking for a regexp is hopefully as straightforward as checking for a single repo via the API.

```yaml
- name: Add Red Hat repositories
  redhat_repository:
    repos: "{{ item.repo }}"
    state: "{{ item.state }}"
  with_items:
    - repo: rhel-7-server-extras-rpms
      state: present
    - repo: rhel-7-server-rpms
      state: absent
```

A loop like this currently results in one call to `subscription-manager` per item, making the execution time increase lineraly with the number of items.

**Pull request closed without merging**
