### PR TITLE
Add OpenStack Router Interface module

### PR DESCRIPTION
**Pull request by emonty**
Also deprecated the old quantum_router_interface module

### CODE REVIEW

**Comment by bcoca** [comment]
requires rebase

**Comment by emonty** [comment]
Let's hold on this one for a sec - I think we can make it and the other two router modules take better advantage of underlying library much better.

**Comment by gregdek** [comment]
@emonty ping -- where are we with this one?

**Comment by gregdek** [comment]
@emonty @shrews @dguerri @juliakreger @j2sol @rcarrillocruz can anyone give an update on the status of this one?

**Comment by Shrews** [comment]
After a quick glance at the code, i think keeping the needs_revision tag is appropriate. It definitely needs some cleanup.

**Comment by gregdek** [comment]
@emonty Please make the suggested revisions, and when you're done, please add a comment with the text "ready_for_review" and we will continue with the review process.  :)

**Pull request closed without merging**
