### PR TITLE
In cloudformation.py added state=outputs to only query stack outputs.

### PR DESCRIPTION
**Pull request by jnsaff**
In cloudformation.py added state=outputs to only query stack outputs without any changes. Removed duplicate and broken conditional for template source.

### CODE REVIEW

**Comment by jnsaff** [comment]
What's going to happen with this?

**Comment by diasjorge** [comment]
This addition would be great. Could you please consider it?

**Comment by gregdek** [comment]
Thanks @jnsaff for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

**Comment by jnsaff** [comment]
ready_for_review

**Comment by bcoca** [comment]
we are trying to move away from the state=list pattern in favor of dedicated _facts modules, I recommend splitting this into such a module, but still keeping this PR for the template fix.

**Comment by gregdek** [comment]
@jnsaff Please make the suggested revisions, and when you're done, please add a comment with the text "ready_for_review" and we will continue with the review process.  Thanks!

**Comment by robynbergeron** [comment]
@jnsaff A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes.

**Comment by gregdek** [comment]
@jnsaff Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If we don't hear from you within another 14 days, we will close this pull request.

**Comment by gregdek** [comment]
Closing due to contributor inactivity.

**Pull request closed without merging**
