### PR TITLE
OpenStack Identity (keystone) service module

### PR DESCRIPTION
**Pull request by berendt**
With this module it is possible to create and delete keystone services.
It is not possible to update keystone services because this is not supported
in version 2.0 of the keystone API.

### CODE REVIEW

**Comment by berendt** [comment]
For testing: a Vagrantbox including a basic Keystone service is available at https://vagrantcloud.com/berendt/boxes/keystone.

**Comment by jimi-c** [comment]
cc @emonty

**Comment by emonty** [comment]
Thanks! We're not taking new features into these modules at the moment - but I'm happy to either port your code to the new structure and give you credit, or point you in that direction if you feel personally interested in hacking on it yourself.

**Comment by berendt** [comment]
@emonty Please point me to the new structure.

**Comment by dguerri** [comment]
Referencing a different version with a slightly improved management of endpoints in PR #874
@emonty can I have that pointer to the new structure? :)

**Comment by gregdek** [comment]
@emonty looking for your guidance here.

**Comment by emonty** [comment]
@dguerri and I have this functionality coming soon based on the new OpenStack guidelines. I'm going to go ahead and close this one to save confusion.

**Pull request closed without merging**
