### PR TITLE
Improve FreeBSD service support.

### PR DESCRIPTION
**Pull request by koichirok**
FreeBSD's RC system supports several service configuration files as described in [rc.conf(5)](https://www.freebsd.org/cgi/man.cgi?rc.conf%285%29).
OTOH, ansible is aware /etc/rc.conf, /etc/rc.conf.local and /usr/local/etc/rc.conf as service configuraion files. 

This PR makes service module supports all possible service configuration files described in rc.conf(5).

For users want to specify their preferred configuration file other than selected by ansible, 
I've also added 'rcconf_file' option.

Since /usr/local/etc/rc.conf  is never supported by FreeBSD as default configuration file as far as I know, I've removed hard coded /usr/local/etc/rc.conf support from ansible. 

This change should have no effect for /usr/local/etc/rc.conf users because /usr/local/etc/rc.conf should be listed in 'rc_conf_files' if they want to use it for one of the config files and this PR supports rc_conf_files.

I've also fixed issue introduced at  cd0a194, leading (and trailing) whitespaces are removed even if these are required.
For example, FreeBSD's ifconfig_<interface>_aliases variable supports multiple lines like below:

```
ifconfig_ed0_aliases="\
             inet 127.0.0.251 netmask 0xffffffff \
             inet 127.0.0.252 netmask 0xffffffff \
             inet 127.0.0.253 netmask 0xffffffff \
             inet 127.0.0.254 netmask 0xffffffff"
```

In this case, leading whitespaces should not be removed. If there are no spaces after 0xffffffff, never
remove whitespaces.

---

Feel free to fix my broken english in my commits. English is not my native language ;)

### CODE REVIEW

**Comment by koichirok** [comment]
oops, i'll fix syntax error

**Comment by koichirok** [comment]
fixed syntax error.

**Comment by gregdek** [comment]
Thanks @koichirok for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

**Comment by gregdek** [comment]
Thanks @koichirok for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@koichirok A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@koichirok Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@koichirok A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@koichirok Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@koichirok A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@koichirok Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@koichirok A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@koichirok Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@koichirok A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
