### PR TITLE
Added 'easy_install' --no-deps and --find-links options.

### PR DESCRIPTION
**Pull request by jeansch**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

language/easy_install.py
##### ANSIBLE VERSION

ansible 2.0.0
##### SUMMARY

Exposes two usefull 'easy_install' options (--no-deps and --find-links)

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @jeansch for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by jeansch** [comment]
ready_for_review

**Comment by jeansch** [comment]
ready_for_review

**Comment by jeansch** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @jeansch. To the current maintainers, @mattupstate please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
