### PR TITLE
Add pull_latest, restart_policy, and insecure_registry parameters to Docker module

### PR DESCRIPTION
**Pull request by abevoelker**
This is a resubmission of @discordianfish's `ansible` repo pull request [#9095](https://github.com/ansible/ansible/pull/9095).  I did not split it into three separate PRs because if they would be accepted/merged separately it would cause merge conflicts.  Let me know if this is a problem and I will modify as needed.
- `insecure_registry` applies to `ansible` repo [#9095](https://github.com/ansible/ansible/pull/9095)
- `restart_policy` applies to `ansible` repo [#8815](https://github.com/ansible/ansible/pull/8815)
- `pull_latest` applies to `ansible` repo [#8805](https://github.com/ansible/ansible/pull/8805)

### CODE REVIEW

**Comment by discordianfish** [comment]
Cool! Thanks @abevoelker

**Comment by zalad** [comment]
great!
`restart_policy` is a must have.
for now i'm forced to create docker containers using `shell` to be able to specify restart policy

**Comment by fantapop** [comment]
I was having trouble with the pull_latest commit. I ended up changing:

```
--- a/libary/cloud/docker
+++ b/library/cloud/docker
@@ -657,13 +657,13 @@ class DockerManager:
         resource = self.module.params.get('image')
         image, tag = self.get_split_image_tag(resource)
         if self.module.params.get('pull_latest'):
-            do_pull(resource, tag)
+            do_pull(image, tag)

         try:
             containers = do_create(count, params)
         except:
             if not self.module.params.get('pull_latest'):
-                do_pull(resource, tag)
+                do_pull(image, tag)
                 containers = do_create(count, params)

         return containers
```

**Comment by discordianfish** [comment]
@fantapop Thanks, that looks right. That might be slipped in there when rebasing.

**Comment by abevoelker** [comment]
Applied @fantapop's patch and rebased into the `pull_latest` commit.

**Comment by ghost** [comment]
+1

**Comment by rojaro** [comment]
+1

**Comment by gottwald** [comment]
Sorry, I found this after I submitted a kind-of dupe PR #199 regarding restart_policy. 
@abevoelker are you aware that this PR breaks a lot of setups with docker-py==0.3.2 or with older docker APIs which are still very common (lts releases)?

Could you please cherry pick the version switches of my PR #199 to make sure we don't break other setups and also the "restart_policy_retry" option to get full docker restart_policy support. (MaximumRetryCount is only available when using "on-failure" restart-policy)

Also, the official docker API docs use an uppercase "Name" for the restart policy name key.
Works with lowercase as well but is kind of undocumented and could break in the future.

**Comment by mpdehaan** [comment]
Ultimately Docker's instability is the problem here.  It seems reasonable to just check for a newer docker-py and fail if it's not there.

I don't think we have to be compatible with previous versions and hope docker-py will learn it's lesson eventually after things start to stabilize and get production ready.

**Comment by gottwald** [comment]
A "version switch" with failing when using an old version of docker-py and this new option would also be fine for me.

**Comment by ghost** [comment]
yep, failing on old/unsupported `docker-py` version is reasonable enough

**Comment by shin-** [comment]
Hey guys, docker-py maintainer here. I'm not entirely sure of the context of the PR so pardon me in advance if I'm way off base. Is there something we could have done better on our front to advetise breaking changes? Feel free to get in touch any way you'd like, I don't want to hijack the conversation here.

**Comment by mpdehaan** [comment]
@abevoelker - if this has some checks to fail on older docker versions I'm ok with this.

@shin - just getting to the point where Docker API stability (i.e. what was promised to 1.0) also applies to language bindings is what I'd be after.   Adding new features is good, but do it in ways that don't break existing things - i.e. add new functions, add optional key=value parameters to existing functions, etc?  Others here may have more experience dealing with this with Docker library version issues, it's just been my experience that docker.py versions matter a whole lot than other libraries in the system, and it is constantly changing in ways that require us to spend a very high amount of time keeping Docker working, and people tend to take that out on the quality of our ansible modules.  I don't mean that to be a reflection on any work you guys have done, and I understand this is changing rapidly -- however, that's also a problem including something that is changing so rapidly in something that is seeking stable modules.

All being said, I would be quite interested in any fixes or comments on Docker/Ansible modules from Docker, very much so in fact - one change we have been thinking is removing the docker-image module as it is starting to feel a little redundant and just teach the 'docker' module what to do.

**Comment by gottwald** [comment]
@mpdehaan restart_policy is an optional key=value parameter in docker-py which is set to None as default. But this pull request always sets restart_policy, regardless whether the user specified it.
This breaks with docker-py versions that don't know this option, yet.

The simplest thing would be, to only set this param when the user actually specifys a restart policy => Old playbooks and setups don't break, new ones have to use a recent docker-py version.

**Comment by abevoelker** [comment]
I won't have any free time until the weekend to make the suggested improvements to this PR unless someone can give me some ready-to-go patches before then.  I would agree with the sentiment of putting all the docker-related functionality into the `docker` module and getting rid of `docker-image`.

**Comment by abevoelker** [comment]
Sorry I haven't got to the requested changes yet.  Unfortunately, I don't think I'll have much time to do it soon, either.  Anyone want to adopt?

**Comment by dkerwin** [comment]
Maybe i can help out. I'll take a look at the proposed changes

**Comment by danros** [comment]
Is anyone working on this? If not I might take it up.

**Comment by bonswouar** [comment]
@danros apparently not right now, I guess you can have a look at it.

**Comment by gottwald** [comment]
@danros You can ignore restart_policy and concentrate on the other two features because in PR #199 the restart_policy feature is already implemented, tested and ready to be merged.

**Comment by psviderski** [comment]
Because of lack of activity and my personal needs for this feature I've submitted a further work on it in PR #484.

**Comment by abadger** [comment]
I'm presently evaluating #484 to implement the pull_latest functionality and some related PR's (#510 for insecure_registry, and #199 for restart_policy) for merging.  If anyone think this PR has some features that should be added to one of the other PRs before merging, please speak up (preferably in those tickets).

Note that I'm not in anyway against the code here -- there's just a lot of duplicated information and work to evaluate.  #199 and #510 separate out individual features so they're easier to get a clear picture of the changes and evaluate them.  My impression is that this PR is not being updated while #484 is so that's why I'm choosing to try and evaluate pull_latest based on that PR.

Thanks for your help and sorry it's taken so long to get around to evaluating this!

**Comment by discordianfish** [comment]
@abadger Just to put this in context, I started with single feature PRs but the never got merged in time so that's why they pilled up. After I got so frustrated that I planned to migrate away from ansible, @abevoelker was so nice to put in the effort to migrate the PRs to the ansible-modules-core repo.

Anyways, I just tried the latest merged changes of ansible (after using my fork for some time) and it's still broken: You can't use volumes-from which makes me wondering who is using ansible to deploy docker container.. The problem is that the current module passes volumes_from to _both_ create and start (https://github.com/ansible/ansible-modules-core/blob/devel/cloud/docker/docker.py#L730) which makes docker-py raise a exception:

```
docker.errors.DockerException: 'volumes_from' parameter has no effect on create_container(). It has been moved to start()
```

So that "compatibility layer" is broken. Things like volumes_from where _moved_ from create to start. To fix that, either remove volumes_from completely from create or add something which checks the version of docker as the old module did.

**Comment by jwalton** [comment]
I wonder if maybe the Ansible module should have an "extra_args"
parameter.  Docker is a pretty fast moving target these days; it would be
nice if we could use new docker features without having to wait for Ansible.

**Comment by skipthelimit** [comment]
How can I install the newest working version of Ansible that includes the insecure_registry flag?

**Comment by gesellix** [comment]
@discordianfish the `volumes_from` removal from docker create would be fixed with PR #579 - though it wouldn't check for the minimal api version.

**Comment by abadger** [comment]
@discordianfish yeah, I hear you :-(  We've been working on giving more power to people a little farther away from the core team but it's been slow going at times.  There's some progress (we have a few more non-Ansible, Inc committers now and we're finally closing tickets faster than they're being opened) but there is a long way to go.  All I can do at the moment is apologize for the long periods waiting on us and say that we are slowly finding new ways to do better.  I'm very sorry.

As for the subject of this ticket, I think that with #502 merged, the last piece of this has been taken care of.  #510 for insecure_registry, #502 for pull_latest (pull=always in that PR) and restart_policy (state=reloaded).  You can take a look at the devel branch or the stable-1.9 branch to see if that works. 

volume_from is not fixed in those so if you need that I still have to figure out what's going on there.  The error is saying that specifying volume_from has moved from calling create_container() to calling start().  That probably means that we'll need to do a version check and then add volumes_from to create_container() on old versions of docker-py and add it to start() on newer versions.  I have to take a look at the pull requests for that to find out if any of them do the version check and if not, figure out the proper versions and add the code to do that.

**Comment by abadger** [comment]
Just an update on volumes_from: That may have already been fixed: https://github.com/ansible/ansible-modules-core/pull/730

Looking at the code, @lorin 's PR looked better so I cleaned that up and merged it.  Details in this comment: https://github.com/ansible/ansible-modules-core/pull/579#issuecomment-79363428

**Pull request closed without merging**
