### PR TITLE
New state on iam_cert module

### PR DESCRIPTION
**Pull request by Lujeni**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

cloud/amazon/iam_cert
##### ANSIBLE VERSION

```
ansible 2.1.0.0
```
##### SUMMARY

I added a new state: `ping`
Imho it's very useful to retrieve informations about a certificate without manipulation:
- check the expiration date and trigger something...
- retrieve the arn path to create an aws elb with https...
###### good

```
19:54 $ python ansible/hacking/test-module -m ./ansible-modules-core/cloud/amazon/iam_cert.py -a "name=xxx.com state='ping'"
***********************************
RAW OUTPUT

{"upload_date": "2015-03-16T09:36:04Z", "name": "xxx.com", "expiration_date": "2016-09-18T05:47:53Z", "changed": false, "cert_body": "-----BEGIN CERTIFICATE-----\n\nIwQYMBaAFGtpKwm\neO9Z9uifJ+JMspQ39UlTH+t2K+X9IseqwfNA\n-----END CERTIFICATE-----", "invocation": {"module_args": {"profile": null, "new_name": null, "dup_ok": null, "new_path": null, "name": "mmtro.com", "security_token": null, "state": "ping", "region": null, "aws_secret_key": null, "aws_access_key": null, "cert": null, "key": null, "ec2_url": null, "path": "/", "validate_certs": true, "cert_chain": null}}, "cert_path": "/cloudfront/xxx.com/", "arn": "arn:aws:iam::xxx:server-certificate/cloudfront/xxx.com/xxx.com"}


***********************************
PARSED OUTPUT
{
    "arn": "arn:aws:iam::xxxserver-certificate/cloudfront/xxx.com/xxx.com", 
    "cert_body": "-----BEGIN CERTIFICATE-----\/\n41W8XFek9i9WpbFROeqZaZEtIsnZ3c5iQq7kY5k4WkykQKDgpWSOqPLhjsZzAsfb\neO9Z9uifJ+JMspQ39UlTH+t2K+X9IseqwfNA\n-----END CERTIFICATE-----", 
    "cert_path": "/cloudfront/xxx.com/", 
    "changed": false, 
    "expiration_date": "2015-09-18T05:47:53Z", 
    "invocation": {
        "module_args": {
            "aws_access_key": null, 
            "aws_secret_key": null, 
            "cert": null, 
            "cert_chain": null, 
            "dup_ok": null, 
            "ec2_url": null, 
            "key": null, 
            "name": "xxx.com", 
            "new_name": null, 
            "new_path": null, 
            "path": "/", 
            "profile": null, 
            "region": null, 
            "security_token": null, 
            "state": "ping", 
            "validate_certs": true
        }
    }, 
    "name": "xxx.com", 
    "upload_date": "2015-03-16T09:36:04Z"
}
```
##### fail

```
19:54 $ python ansible/hacking/test-module -m ./ansible-modules-core-lujeni/cloud/amazon/iam_cert.py -a "name=ansible.com state='ping'"
***********************************
RAW OUTPUT

{"invocation": {"module_args": {"profile": null, "new_name": null, "dup_ok": null, "new_path": null, "name": "ansible.com", "security_token": null, "state": "ping", "region": null, "aws_secret_key": null, "aws_access_key": null, "cert": null, "key": null, "ec2_url": null, "path": "/", "validate_certs": true, "cert_chain": null}}, "message": "The Server Certificate with name ansible.com cannot be found.", "changed": false, "name": "ansible.com"}


***********************************
PARSED OUTPUT
{
    "changed": false, 
    "invocation": {
        "module_args": {
            "aws_access_key": null, 
            "aws_secret_key": null, 
            "cert": null, 
            "cert_chain": null, 
            "dup_ok": null, 
            "ec2_url": null, 
            "key": null, 
            "name": "ansible.com", 
            "new_name": null, 
            "new_path": null, 
            "path": "/", 
            "profile": null, 
            "region": null, 
            "security_token": null, 
            "state": "ping", 
            "validate_certs": true
        }
    }, 
    "message": "The Server Certificate with name ansible.com cannot be found.", 
    "name": "ansible.com"
}
```

Thanks

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @Lujeni for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by kwoodson** [comment]
@Lujeni, awesome.  This is exactly what I added to the current module.  :+1:

**Comment by Lujeni** [comment]
@gregdek Someone can review this code pls?

**Comment by gregdek** [comment]
@lujeni going to be more difficult to get new modules accepted directly into core moving forward. I might recommend submitting this as an extras module.

**Comment by gregdek** [comment]
@lujeni unlikely for this to get into 2.2 because of current feature freeze.

**Comment by Lujeni** [comment]
@gregdek Hello any news ?

**Comment by Lujeni** [comment]
migration ok.

**Pull request closed without merging**
