### PR TITLE
Ini file

### LINKED ISSUE #1788: ini_file fails --check when file doesn't exist
##### Issue Type:
- Bug Report
##### Ansible Version:

$ ansible --version
ansible 1.9.1
  configured module search path = None

$ ansible --version
ansible 2.0.0
  config file = 
  configured module search path = None

$ git log -n 1

```
commit 88e1ef8c9bc6434786ce10dbf0ed46a5b2448c1c
Author: Brian Coca <brian.coca+git@gmail.com>
Date:   Thu Jul 23 20:47:24 2015 -0400

    implemented --step in v2
```
##### Ansible Configuration:

<not used>
##### Environment:

running on:
Darwin xxxxxxxxxx.local 14.4.0 Darwin Kernel Version 14.4.0: Thu May 28 11:35:04 PDT 2015; root:xnu-2782.30.5~1/RELEASE_X86_64 x86_64

managing:
Linux ip-xxxxxxxxx-125 3.14.35-28.38.amzn1.x86_64 #1 SMP Wed Mar 11 22:50:37 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
##### Summary:

`ini_file` module fails `ansible-playbook --check` if file does not exist. This prevents any further checks for that host.
##### Steps To Reproduce:
1. Create a task to add a value to a not-yet-existing file on target
2. Run playbook with `--check` option (dry-run)
3. Run playbook without `--check` option (live-run)

Example of (1):

```
- name: install hgrc
  tags: test
  ini_file:
    dest: ~/.hgrc
    section: extensions
    option: bundleclone
    value: ~/.hgext/bundleclone.py
    state: present
```
##### Expected Results:

I expected both steps (2) & (3) to be successful.
In particular, I expected any selected tasks after (2) to also be evaluated by `--check` mode.
##### Actual Results:

(2) failed, and (3) was successful. Subsequent runs of (2) succeeded (once file existed).

Failure message from ansible v2.0:

```
TASK [install hgrc] *************************************************************
fatal: [xxxxxxxxxxxxx]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "msg": "BECOME-SUCCESS-qbihvwjllqutgqdveipfwrshmgihqpsn\r\nTraceback (most recent call last):\r\n  File \"/tmp/ansible-tmp-1437703308.32-120186831188640/ini_file\", line 1882, in <module>\r\n    main()\r\n  File \"/tmp/ansible-tmp-1437703308.32-120186831188640/ini_file\", line 209, in main\r\n    changed = module.set_fs_attributes_if_different(file_args, changed)\r\n  File \"/tmp/ansible-tmp-1437703308.32-120186831188640/ini_file\", line 1037, in set_fs_attributes_if_different\r\n    file_args['path'], file_args['mode'], changed\r\n  File \"/tmp/ansible-tmp-1437703308.32-120186831188640/ini_file\", line 875, in set_mode_if_different\r\n    path_stat = os.lstat(path)\r\nOSError: [Errno 2] No such file or directory: '/home/vcs2vcs/.hgrc'\r\n", 
    "parsed": false
}

PLAY RECAP **********************************************************************
xxxxxxxxxxxxx              : ok=4    changed=1    unreachable=0    failed=1   
```

### PR DESCRIPTION
**Pull request by lberruti**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

ini_file
##### ANSIBLE VERSION

```
ansible 2.2.0 (detached HEAD 35a3653dfc) last updated 2016/08/25 23:07:04 (GMT +200)
  lib/ansible/modules/core: (ini_file e707d68306) last updated 2016/08/25 23:19:27 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD f29efb5626) last updated 2016/08/25 23:07:11 (GMT +200)
  config file =
  configured module search path = Default w/o overrides
```
##### SUMMARY
- fixes #1788
- add create= option (similar to create= option of lineinfile module)
- add diff support
- return more infos on changes (inside msg)

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @lberruti. To the current maintainers, @jpmens, @noseka1 please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by jpmens** [comment]
shipit

**Comment by gregdek** [comment]
Thanks again to @lberruti for this PR, and thanks @jpmens, @noseka1 for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @lberruti for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by lberruti** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @lberruti. To the current maintainers, @jpmens, @noseka1 please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by jpmens** [comment]
shipit

**Comment by gregdek** [comment]
Thanks again to @lberruti for this PR, and thanks @jpmens, @noseka1 for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @lberruti for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by lberruti** [comment]
ready_for_review
@gregdek can you add also  bugfix_pull_request label, please? (see #1788)

**Comment by gregdek** [comment]
@lberruti if I did, the bot would just change it back. :) Edit the original and take "feature" out of the text.

**Comment by lberruti** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @lberruti. To the current maintainers, @jpmens, @noseka1 please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by jpmens** [comment]
shipit

**Comment by gregdek** [comment]
Thanks again to @lberruti for this PR, and thanks @jpmens, @noseka1 for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request merged**
