### PR TITLE
Feature/iam policy present state includes policy changes

### PR DESCRIPTION
**Pull request by bermudezjd**
This PR adds a minor change to the iam_policy module that allows existing policies to be updated without having to disable the `skip_duplicates` flag.  I introduced the idea on the devel boards here - https://groups.google.com/forum/#!topic/ansible-devel/sumBECXO4hY.  Please let me know whether this can remain part of the `present` state or whether an `updated` state is needed.

### CODE REVIEW

**Comment by gregdek** [comment]
@defionscode Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by gregdek** [comment]
@defionscode This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by robynbergeron** [comment]
@defionscode still waiting on your review.  Please comment with text 'shipit' or 'needs_revision' as appropriate. If we don't hear from you within 14 days, we will start to look for additional maintainers for this module.

**Comment by gregdek** [comment]
Thanks @bermudezjd for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

**Comment by bermudezjd** [comment]
ok, rebased and resolved merge conflicts so ready_for_review again... looks like folks are looking for this via #1855 so hoping that @defionscode will look at this soon.

**Comment by robynbergeron** [comment]
Thanks @bermudezjd. @defionscode please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by robynbergeron** [comment]
Thanks @bermudezjd. @defionscode please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by bermudezjd** [comment]
@robynbergeron just checking in on this since it's been well over 2 weeks since you had reached out to @defionscode to review this.  is there someone else who can take a look?

**Comment by waky79** [comment]
First I would like to say that great that someone has already fixing this. My only concern with the whole implementation is that what is the use of the do not skip duplicates flag. Now the new implementation will work better in case the policy changes. Still the new implementation will not update the policy name in case it has changed.

I am OK with the change but this will cause cases where you update the policy name but it stays as is, and if you allow duplicate, there will be two policies with the same name. The first one, in case you make ansible delete the policy, it does not find the one with name you have currently in your configuration. For the latter it leaves the older policy behind.

It would be, in my opinion, good to understand why the policy name is even part of the configuration as the implementation does not bind it to the policy content.

Still I would like to say that I am waiting this fix to be merged as it fixes even bigger issue with policy updating.

**Comment by Jmainguy** [comment]
I am no familiar with the iam module at all. That being said, this change looks pretty minor. 6 total non comment lines being added. Slight refactor to make it a little easier to read. Looks good to me from my limited understanding. Only nitpitck comment would be to squash commits to make history easier to read when this does get merged. Nice work.

**Comment by abadger** [comment]
@defionscode @Jmainguy has reviewed the code for this and thinks it looks sane.  Are you able to review whether the feature itself makes sense?  With that out of the way I think we could merge this. https://groups.google.com/forum/#!topic/ansible-devel/sumBECXO4hY

**Comment by juliedavila** [comment]
This is fine with me, and as far as @waky79 s concern, I just verified, and it is not possible to have two IAM policies with the same name. Worst case, you'll have two policies with different names but with the same rules, which I think is an 'acceptable' scenario.

**Comment by abadger** [comment]
Thanks @defionscode @Jmainguy Merged to devel!

**Comment by waky79** [comment]
@defionscode yes true, it fails with same name. And like said I was fine with the fix. Just liked to know/debate what would be the desired optimal behavior, looks like I expressed myself badly.

**Pull request merged**
