### PR TITLE
Tell me what the igw id is if we created an igw.

### PR DESCRIPTION
**Pull request by feanil**
Right now if you create an internet gateway with your vpc.  There is no easy way to know what the ID of that gateway was.  This adds a new output that has the igw info if the gateway was created.

### CODE REVIEW

**Comment by feanil** [comment]
@carsongee

**Comment by bcoca** [comment]
i would avoid the function and just always return {gw_id: gwid} even if it is None it is OK to return that

**Comment by carsongee** [comment]
This looks good to me

**Comment by feanil** [comment]
@bcoca do you mean that it's ok if `id` is none or do you mean that it's ok if `igw` is `None`?  Would you like to always return `json_igw={id: (None or igw.id)}`?

**Comment by bcoca** [comment]
probably cleaner to just return:

`module.exit_json(changed=changed, vpc_id=new_vpc_id, vpc=vpc_dict, igw_id=igw_id, subnets=subnets_changed)`

**Comment by feanil** [comment]
@bcoca Updated as per your suggestion.

**Pull request merged**
