### PR TITLE
Improves command warnings for commands which require special arguments

### LINKED ISSUE #2266: Allow service module to run custom command
Some init scripts have an 'init' function, much like zookeeper's 'service zookeeper-server init'
It would be useful to let service module handle that instead of running previous mentioned command

### PR DESCRIPTION
**Pull request by kustodian**
This pull request improves how Ansible warns about specific commands. For commands like `service nginx restart`, or `systemctl restart nginx` it will only print a warning if those commands are called with arguments which are supported by the service module (`start`, `stop`, `restarted` or `reloaded`), for any other argument a warning wont be printed.

I tried to make it as generic as possible, so just editing the `commands_with_args` correctly should work for any future command.

It also fixes #2266

### CODE REVIEW

**Comment by gregdek** [comment]
@kustodian Thanks for your pull request. This module is critical to Ansible's functionality, so it's owned by the Core team, and it can take a while for patches to be reviewed. Thanks for your patience here.

**Comment by kustodian** [comment]
@gregdek Don't worry about it. It's a minor change to the module, since it only improves warnings.

**Comment by kustodian** [comment]
@TaiSHiNet if you are interested, take a look at the changes.

**Comment by robynbergeron** [comment]
Thanks @kustodian for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

**Comment by kustodian** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @kustodian for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

**Comment by gregdek** [comment]
Thanks @kustodian for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by kustodian** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @kustodian for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @kustodian for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@kustodian A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by kustodian** [comment]
I'll update the pull request in the next few days.

**Comment by kustodian** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @kustodian for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @kustodian for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by kustodian** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @kustodian for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by geoffreywiseman** [comment]
Is this dead? I'm getting a warning on `command service iptables save`. I understand the desire not to fold that into the service module, but I don't like the warning, and if the service module isn't intended to handle things like this, the warning should be more targeted. So if there's something I can do to nudge this along, then consider this a nudge.

**Comment by kustodian** [comment]
I just stopped carrying about it, because it is a small change which never managed to get merged, so I didn't even make a PR in the ansible repo when this repo was closed. You can remove errors from `command/shell` modules by adding a parameter `warn: no`.

Feel free to make a new PR with my changes if you want.

**Comment by geoffreywiseman** [comment]
Yeah, would be nice if your change had been accepted/merged any of the times it was up. :/

**Pull request closed without merging**
