### PR TITLE
Now correctly gzip/bzips file back up in case of import failure

### PR DESCRIPTION
**Pull request by Jmainguy**

### CODE REVIEW

**Comment by bcoca** [comment]
I thought i had fixed this with alternate approach, but not unziping the file but by piping the uncompressed stream directly to mysql.

**Comment by Jmainguy** [comment]
Do you mean the original implementation?

https://github.com/ansible/ansible/commit/bb73819c43bfb0069c5459924e26014ef0a4fe35

The original implementation worked, when everything worked. However it would hide some failures and report OK even when it failed, due to the return codes being swapped around when piping commands into each other.

**Comment by bcoca** [comment]
ah, probably, this is why pipefail is A killer feature in bash

**Comment by abadger** [comment]
Took a look, one minor thing to change:

Instead of looking for both gzip and gunzip (and having to use separate error messages if they aren't found), just use gzip_path with the -d option for decompressing.  same with bunzip2.

Other than that, this looks good to merge.

**Comment by Jmainguy** [comment]
@abadger updated to remove bunzip2 and gunzip dependency. Great suggestion.

**Comment by abadger** [comment]
Thanks @Jmainguy !

# Merged

Hi!

This has been merged in, and will also be included in the next major release.

If you or anyone else has any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Pull request merged**
