### PR TITLE
Fix unarchive screenscraping by selecting C locale

### LINKED ISSUE #3706: unarchive issue with ansible 2.1 rc3
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

unarchive
##### ANSIBLE VERSION

```
ansible-playbook 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/yannig/dev/ansible-conf/ansible/playbooks/library']
```
##### CONFIGURATION

None
##### OS / ENVIRONMENT

Nothing special
##### SUMMARY

When using unarchive with Ansible 2.1 rc3, I get an error. Using ansible devel or ansible 2.0 work.
##### STEPS TO REPRODUCE

Get unarchive.yml at the following location: https://github.com/Yannig/yannig-ansible-playbooks/blob/master/unarchive/unarchive.yml

And run it.

```
ansible-playbook unarchive.yml
```
##### EXPECTED RESULTS

```
PLAY [Unarchive problem] *******************************************************

TASK [file] ********************************************************************
changed: [localhost]

TASK [file] ********************************************************************
changed: [localhost]

TASK [get_url] *****************************************************************
changed: [localhost]

TASK [unarchive] ***************************************************************
changed: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=4    changed=4    unreachable=0    failed=0
```
##### ACTUAL RESULTS

```
PLAY [Unarchive problem] *******************************************************

TASK [file] ********************************************************************
changed: [localhost]

TASK [file] ********************************************************************
changed: [localhost]

TASK [get_url] *****************************************************************
ok: [localhost]

TASK [unarchive] ***************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Unexpected error when accessing exploded file: [Errno 2] Aucun fichier ou dossier de ce type: '/tmp/unarchive/apache-tomee-plus-1.7.4/webapps'"}

NO MORE HOSTS LEFT *************************************************************
        to retry, use: --limit @unarchive.retry

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=2    unreachable=0    failed=1
```

Note: the devel version is not concerned about this issue.

### PR DESCRIPTION
**Pull request by abadger**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

files/unarchive.py
##### ANSIBLE VERSION

```
2.1 and devel
```
##### SUMMARY

Fixes #3706

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @abadger. To the current maintainers, @dagwieers, @pileofrogs please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by dagwieers** [comment]
Ok, before we are going to implement fixes for specific use-cases (that may or may not break working cases) can we first establish the problem ? From the issue discussion I don't understand what the cause is. I can tell using LANG=C fixes it, but what is broken ?

(Mind you that I just reverted #3575 because we were fixing one thing, and broke another one)

**Comment by abadger** [comment]
I don't know how this solves @Yannig's issue either but after considering it for a while I realized that this is a correct change to the code, regardless.  We can't screenscrape without being explicit about our locale otherwise everything will seem to work when we test but a user with an odd-ball locale can experience breakage.  The C locale is unfortunately the only locale we can use in this way as OS's and distributions do not have any other common locales amongst them.

If we find new bugs because of this we'll have to fix those bugs.

**Comment by Yannig** [comment]
Hi,

My local machine is configured with french local. If you launch tar in this context, you'll get french messages. Here's an example running tar:

```
/bin/tar -C /tmp/unarchive -dz -f /tmp/apache-tomee-1.7.4-plus.tar.gz  | head 
```

```
apache-tomee-plus-1.7.4/webapps/docs/architecture/requestProcess/request-process.png: L'UID est différent.
apache-tomee-plus-1.7.4/webapps/docs/architecture/requestProcess/request-process.png: Le GID est différent.
apache-tomee-plus-1.7.4/webapps/docs/architecture/requestProcess/authentication-process.png: L'UID est différent.
apache-tomee-plus-1.7.4/webapps/docs/architecture/requestProcess/authentication-process.png: Le GID est différent.
apache-tomee-plus-1.7.4/webapps/docs/architecture/requestProcess.html: L'UID est différent.
apache-tomee-plus-1.7.4/webapps/docs/architecture/requestProcess.html: Le GID est différent.
apache-tomee-plus-1.7.4/webapps/docs/architecture/startup/serverStartup.pdf: L'UID est différent.
apache-tomee-plus-1.7.4/webapps/docs/architecture/startup/serverStartup.pdf: Le GID est différent.
apache-tomee-plus-1.7.4/webapps/docs/architecture/startup/serverStartup.txt: L'UID est différent.
apache-tomee-plus-1.7.4/webapps/docs/architecture/startup/serverStartup.txt: Le GID est différent.
```

Now, if I force LC_ALL=C, I get the following result:

```
LC_ALL=C /bin/tar -C /tmp/unarchive -dz -f /tmp/apache-tomee-1.7.4-plus.tar.gz | head
```

```
apache-tomee-plus-1.7.4/webapps/docs/architecture/requestProcess/request-process.png: Uid differs
apache-tomee-plus-1.7.4/webapps/docs/architecture/requestProcess/request-process.png: Gid differs
apache-tomee-plus-1.7.4/webapps/docs/architecture/requestProcess/authentication-process.png: Uid differs
apache-tomee-plus-1.7.4/webapps/docs/architecture/requestProcess/authentication-process.png: Gid differs
apache-tomee-plus-1.7.4/webapps/docs/architecture/requestProcess.html: Uid differs
apache-tomee-plus-1.7.4/webapps/docs/architecture/requestProcess.html: Gid differs
apache-tomee-plus-1.7.4/webapps/docs/architecture/startup/serverStartup.pdf: Uid differs
apache-tomee-plus-1.7.4/webapps/docs/architecture/startup/serverStartup.pdf: Gid differs
apache-tomee-plus-1.7.4/webapps/docs/architecture/startup/serverStartup.txt: Uid differs
apache-tomee-plus-1.7.4/webapps/docs/architecture/startup/serverStartup.txt: Gid differs
```

I totaly agreed with @abadger: LC_ALL=C is a good way to discard all this kind of problem.

**Comment by dagwieers** [comment]
I don't consider French messages a bug though. Is this what this fix is
about ? Because in that case we may want to make LANG=C the default for
everything we run, not just tar.

**Comment by abadger** [comment]
@dagwieers Cool.  I'll merge #3778 instead of this one then.

**Pull request closed without merging**
