### PR TITLE
nxos_ping support for 2.1 and 2.2

### PR DESCRIPTION
**Pull request by GGabriele**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

nxos_ping
##### ANSIBLE VERSION

```
ansible 2.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/share/ansible/']
```
##### SUMMARY

I've included a serie of python object to support both 2.1 and 2.2.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks again to @GGabriele. This module is going into community review.

We notice that you are one of the maintainers (@privateip, @GGabriele, @gundalow) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gundalow** [comment]
Why does the title for this PR say "for 2.1 and 2.2"?

Generally speaking we don't backport features, only certain bug fixes

**Comment by GGabriele** [comment]
We need these modules to work with both 2.1 and 2.2. That's why we are adding that "Common code"

**Comment by gundalow** [comment]
Does this work with 2.1

```
+try:
 +    from ansible.module_utils.nxos import get_module
 +except ImportError:
 +    from ansible.module_utils.nxos import NetworkModule
```

Have you testing this?

**Comment by GGabriele** [comment]
Yes.

**Pull request merged**
