### PR TITLE
Do not ignore the primary group if modifying the list of secondaries

### LINKED ISSUE #1118: user groups option always triggers changed
My ansible version is 1.8.2 and I'm managing an Arch Linux box from an Arch Linux box.

**Summary:**

For the user module, if the groups option is specified, it always triggers "changed" even if the group list doesn't change.

**Steps To Reproduce:**

```
- user: name={{user}} home=/srv/samba createhome=yes system=yes shell=/bin/nologin groups={{group}} group={{group}} append=yes
```

**Expected Results:**

```
TASK: [samba | Create samba user] ********************************************* 
ok: [prokyon]
```

**Actual Results:**

```
TASK: [samba | Create samba user] ********************************************* 
changed: [prokyon]
```

### PR DESCRIPTION
**Pull request by jctanner**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

modules/core/system/users.py
##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.1.0 (devel 9d5b4fe212) last updated 2016/05/02 20:58:19 (GMT -400)
  lib/ansible/modules/core: (FIX_1118_usergroups d3790c411a) last updated 2016/05/02 23:21:21 (GMT -400)
  lib/ansible/modules/extras: (devel e8391d6985) last updated 2016/05/02 20:58:34 (GMT -400)
  config file = 
  configured module search path = Default w/o overrides
```
##### SUMMARY

The secondary grouplist comparison was always excluding the user's primary group from the list of current groups. By ignoring the primary, and running with append=yes, a "usermod -a -G" would always be run and set changed=True for the primary group.  

Fixes #1118

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @jctanner. To the current maintainers, @grossws please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by grossws** [comment]
shipit

**Comment by grossws** [comment]
@jctanner, thank you, patch seems fine, works on cases like #1118 and there's no visible regressions found.

**Comment by gregdek** [comment]
Thanks again to @jctanner for this PR, and thanks @grossws for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by jctanner** [comment]
@grossws thanks for the review

**Pull request merged**
