### PR TITLE
Add tags support to ec2_group module

### PR DESCRIPTION
**Pull request by sheepkiller**
Code comes from vpc_subnet module, minus add only mode and tags refreshing.

### CODE REVIEW

**Comment by sheepkiller** [comment]
related to #445

**Comment by gregdek** [comment]
Thanks @sheepkiller for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

**Comment by brandond** [comment]
+1 to this, pending a PR to fix the tag spec for 2.2: https://github.com/sheepkiller/ansible-modules-core/pull/1

**Comment by Anislav** [comment]
+1

**Comment by stepanstipl** [comment]
+1 this has been missing for ages

**Comment by brandond** [comment]
Yeah I don't understand how this isn't done yet

**Comment by aioue** [comment]
+1

**Pull request closed without merging**
