### PR TITLE
adding disk_type option to choose from pd-ssd or pd-standard

### PR DESCRIPTION
**Pull request by pmoosh**
This pull request fixes issue #717 - with some help from Stan

### CODE REVIEW

**Comment by bcoca** [comment]
can we simplify the choices for the user by removing the requirement of the pd- prefix?

**Comment by erjohnso** [comment]
My preference is to retain the pd- prefix since that matches upstream API/docs [https://cloud.google.com/compute/docs/reference/latest/disks#type].  Next release of libcloud will have better DiskType support in the GCE driver, so we may refactor this bit, but I think it's good to go for now.

@bcoca - mind if I merge this?

**Comment by bcoca** [comment]
fine with me

**Comment by erjohnso** [comment]
Works for me!  Tested on `Ansible 1.9 devel`.  I verified this on Debian 7.

``` sh
$ ansible local -m gce_pd -a 'service_account_email=foo@developer.gserviceaccount.com pem_file=/home/erjohnso/pkey.pem project_id=myproj name=test-ssd disk_type=pd-ssd'
127.0.0.1 | success >> {
    "changed": true, 
    "disk_type": "pd-ssd", 
    "name": "test-ssd", 
    "size_gb": 10, 
    "state": "present", 
    "zone": "us-central1-b"
}
```

``` sh
$ ansible --version
ansible 1.9 (devel 2a04663255) last updated 2015/01/20 21:06:11 (GMT +000)
  lib/ansible/modules/core: (detached HEAD 396c399b54) last updated 2015/01/20 21:06:14 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD 2396f36f11) last updated 2015/01/20 21:06:17 (GMT +000)
  v2/ansible/modules/core: (detached HEAD 8ba8f5ef4d) last updated 2015/01/20 21:06:20 (GMT +000)
  v2/ansible/modules/extras: (detached HEAD 2396f36f11) last updated 2015/01/20 21:06:22 (GMT +000)
  configured module search path = /home/erjohnso/ansible-modules-core:/home/erjohnso/ansible-modules-extras
```

**Pull request merged**
