### PR TITLE
vyos: Docs fixes

### PR DESCRIPTION
**Pull request by gundalow**
##### ISSUE TYPE
- Docs Pull Request
##### COMPONENT NAME

vyos-*
##### ANSIBLE VERSION

Docs improvements

---

This change is [Reviewable](https://reviewable.io/reviews/ansible/ansible-modules-core/4341)

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks again to @gundalow. This module is going into community review.

We notice that you are one of the maintainers (@privateip, @gundalow) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by VanWade** [comment]
Hi,I installed ansible2.2 and tried to use vyos modules according the documents,but all failed.The failure message was 'Could not find imported module support code for vyos_facts.  Looked for either CommandRunner or netcmd'.My playbook was 
`- hosts: vyatta1
  remote_user: vyatta
  vars:
      cli:
        host: xxx
        username: xxx
        password: xxx
        transport: cli

  tasks:
    - name: collect all facts from the device
      vyos_facts: 
        gather_subset: all
` 
Could you guys help me? @gundalow @privateip

**Comment by gundalow** [comment]
@VanWade Hi

The networking modules in 2.2 (devel) are going though a major rewrite at the moment and will most likely be broken for the next few weeks during the code refactor.

Please don't mix topics and bugs. This PR isn't anything to do with your issue, commenting on here just confuses the issue.

Please wait till you see an announcement regarding 2.2 rc (release candidate). If you then hit issues please raise a fresh bug and mark it @gundalow.

Thanks

**Comment by VanWade** [comment]
Hi, @gundalow .I'm very sorry for that.By the way I found that the module netcmd had been renamed to netcli.So the references in vyos modules should be modified.

**Comment by gundalow** [comment]
@VanWade Correct, that's part of the large refactor I was talking about. We are going through appliance at a time and porting them to the new libraries.

**Pull request merged**
