### PR TITLE
Ignore untracked files in submodules

### PR DESCRIPTION
**Pull request by rchavik**
Similar to ansible/ansible#6582.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @rchavik for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

**Comment by gregdek** [comment]
Thanks @rchavik for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by rchavik** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @rchavik for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by jctanner** [comment]
@rchavik I'm not sure what the behavior might have been when you originally submitted this, but the behavior it attempts to fix is already correct in 2.1 via the force parameter. If untracked files exist, the module fails unless force=True.

Your patch, makes the module unaware of untracked files and then updates the checkout anyway. That is not the behavior we want. force=True is the correct way to bypass untracked files.

Thank you for the PR and sorry we didn't get around to proper review sooner.

**Comment by rchavik** [comment]
Understood. Thanks for the clarification.

**Pull request closed without merging**
