### PR TITLE
Add mode option to the list

### PR DESCRIPTION
**Pull request by bocharsky-bw**
##### ISSUE TYPE
- Docs Pull Request
##### COMPONENT NAME

`get_url` module
##### ANSIBLE VERSION

```
ansible 2.0.2.0
  config file =
  configured module search path = Default w/o overrides
```
##### SUMMARY

According to the example here https://github.com/bocharsky-bw/ansible-modules-core/blob/patch-1/network/basics/get_url.py#L176

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @bocharsky-bw. To the current maintainers, @jpmens please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @bocharsky-bw for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by bocharsky-bw** [comment]
ready_for_review

**Comment by jpmens** [comment]
@bocharsky-bw click on the Details for the Travis build and scroll to the bottom. ;-)

**Comment by bocharsky-bw** [comment]
@jpmens thanks! It was my first contribution to the Ansible docs and I'm not pretty well with Python

**Comment by gregdek** [comment]
Thanks @bocharsky-bw. To the current maintainers, @jpmens please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by jpmens** [comment]
shipit

**Comment by gregdek** [comment]
Thanks again to @bocharsky-bw for this PR, and thanks @jpmens for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by bcoca** [comment]
why only mode, no owner/group? this is really the purview of the file module.

**Comment by gregdek** [comment]
@bocharsky-bw A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by bocharsky-bw** [comment]
@bcoca So we need to add `owner`/`group` options in this PR too?

**Comment by gregdek** [comment]
@bocharsky-bw Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by bocharsky-bw** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @bocharsky-bw. To the current maintainers, @jpmens please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by jpmens** [comment]
shipit

**Comment by gregdek** [comment]
Thanks again to @bocharsky-bw for this PR, and thanks @jpmens for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request merged**
