### PR TITLE
apt: fix always changed when using deb file on Debian 8

### LINKED ISSUE #2430: apt: deb="file.deb" always changed
using ansible 1.9.4

### PR DESCRIPTION
**Pull request by resmo**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

 packaging/os/apt.py
##### ANSIBLE VERSION

```
2.1
```
##### SUMMARY

Running integration tests `make destructive TEST_FLAGS="--tags test_apt"` passes with this fix.

```
ok: [test-ubuntu-1404]
ok: [test-debian-7]
ok: [test-debian-8]
ok: [test-ubuntu-1204]
```

(tests has been modified to run on Debian 8, PR for it is in the works)

closes #2675, fixes #2430

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @resmo for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by robinro** [comment]
instead of explicitly checking the version, can't you just give the `.deb` to apt/dpkg and parse their output to see whether it was updated?
These explicit checks need a lot of maintenance when the api changes and also make an unnecessary number of calls to external programs.

In the zypper refactor https://github.com/ansible/ansible-modules-extras/pull/2108 I ensured that external programs are called a maximum of 2 times and the rest is done by parsing their output.

**Comment by resmo** [comment]
My intention was to make the current code work without much changed lines so the fix would be cherry-pickable to 2.1 as well. In 2.2 a refactor of the code would make sense.

**Comment by Jmainguy** [comment]
Looks solid

**Pull request merged**
