### PR TITLE
Update hostname.py

### PR DESCRIPTION
**Pull request by sinner-**
Added support for FreeBSD. (http://www.freebsd.org)

### CODE REVIEW

**Comment by robynbergeron** [comment]
Hi @sinner- -- thanks for submitting this PR.

@hnakamur & @saito-hideki -- 

Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.
If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by hnakamur** [comment]
Thanks for submitting this PR.
@robynbergeron Thanks for letting me know this PR. It looks good to me.

**Comment by sinner-** [comment]
shipit

**Comment by gregdek** [comment]
Thanks @hnakamur for the review and thanks @sinner- for the PR. Marking for inclusion.

**Pull request merged**
