### PR TITLE
Added usage examples for exclude and extra-opts

### PR DESCRIPTION
**Pull request by dharmabumstead**
##### ISSUE TYPE

- Feature Pull Request
- New Module Pull Request
- Bugfix Pull Request
- Docs Pull Request
##### ANSIBLE VERSION

```

```
##### SUMMARY

```

```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @dharmabumstead. To the current maintainers, @dagwieers, @pileofrogs please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by dharmabumstead** [comment]
I tested these and added them to the docs at the request of support. Can we get this merged soon? Thanks!

**Comment by dagwieers** [comment]
Thanks @dharmabumstead for your contribution.

Could you in the future fill out the default template as requested ? It should only take a few seconds to select the issue type, component. The version-section can be removed, and the summary would automatically be your commit message.

shipit

**Comment by gregdek** [comment]
Thanks again to @dharmabumstead for this PR, and thanks @dagwieers, @pileofrogs for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by dharmabumstead** [comment]
@dagwieers Will do. Thanks.

**Comment by gregdek** [comment]
Thanks @dharmabumstead for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by dharmabumstead** [comment]
ready_for_review

**Comment by dagwieers** [comment]
shipit

**Pull request closed without merging**
