### PR TITLE
Small code cleanup

### PR DESCRIPTION
**Pull request by abadger**
- isinstance instead of comparing types
- Change group_name to a list rather than having separate code paths if it's a string

### CODE REVIEW

**Comment by abadger** [comment]
@quodlibetor would you mind having a look at this?  It's a small cleanup to the same portion of code you just fixed.

**Comment by quodlibetor** [comment]
This looks much saner. :+1:

**Comment by abadger** [comment]
Thanks for the second pair of eyes :-)

**Comment by quodlibetor** [comment]
Glad to be of service!

**Pull request merged**
