### PR TITLE
Add support for 'single-branch' option in git module

### LINKED ISSUE #1463: Add a way to pass the --single-branch flag to the git module
##### ISSUE TYPE

Feature Idea
##### COMPONENT NAME

git module
##### ANSIBLE VERSION

N/A
##### SUMMARY

Didn't see it in the docs:
http://docs.ansible.com/git_module.html

This page has what it does:
ftp://www.kernel.org/pub/software/scm/git/docs/git-clone.html

I'd like to specify --single-branch but not specify depth.

### PR DESCRIPTION
**Pull request by vysinsky**
Closes #1463

I have no experience with Python. So I hope it is ok :)

We would like to have this option because we have huge repository where each machine works in own branch. So cloning with this option would really speed up a repository checkout.

### CODE REVIEW

**Comment by pajtai** [comment]
:+1: was looking for how to achieve this. Would be a nice add on.

**Comment by vojtech-dobes** [comment]
:+1: Would be of great help to me.

**Comment by gregdek** [comment]
Thanks @vysinsky for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

**Comment by aleemb** [comment]
Can this be merged please?

**Comment by gregdek** [comment]
Thanks @vysinsky for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by vysinsky** [comment]
ready_for_review

**Pull request closed without merging**
