### PR TITLE
os_router: Add ability to add port as router internal interface

### PR DESCRIPTION
**Pull request by alextricity25**
##### ISSUE TYPE
- Bugfix Pull Request:
  https://github.com/ansible/ansible-modules-core/issues/3517
  https://github.com/ansible/ansible-modules-core/issues/3518
- Feature Implementation:
  https://github.com/ansible/ansible-modules-core/issues/3390
##### COMPONENT NAME

os_router.py
##### ANSIBLE VERSION

```
ansible 2.0.1.0
```
##### SUMMARY

```
Add the ability to specifiy ports for router interfaces

Three notable changes have been made as part of this pull request.

1. "router_ha_interface" ports have been disregarded in all respects

The HA ports cause issues when deleting a router through this module.
Technically, these ports are suppose to be "hidden" any way.

2. Added the ability to add router interfaces through port name/id

There is now a slight change in syntax in the way internal router
interfaces are specified. This change allows the user to add
internal interfaces by subnet name/id and/or port name/id.
The old way of specifing interfaces has been kept for backwards
compatability.

3. Don't detach all interfaces then re-attach the new set of interfaces.

Previously, on a router update, all the of the interfaces would be detached,
then the new set would be attached. This caused issues with network stability
and required running expensive api calls for each port. It also caused issues
with environments running the l3 ha keepalived vrrp driver. Ports would be
detached then attached so fast that the keepalived driver couldn't keep up.
Now, the code checks to see what interfaces need to be attached or detached
by comparing the existing set of interfaces with the ones supplied.

Some doc changes are necessary here, but I'm not exactly sure what the process
for that is. If someone could point me in the right direction, that would be great.
```

### CODE REVIEW

**Comment by alextricity25** [comment]
@emonty @Shrews Could you guys take a look if you get the chance?

**Comment by gregdek** [comment]
Thanks @alextricity25. To the current maintainers, @emonty, @shrews, @juliakreger, @j2sol, @rcarrillocruz please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by mcameron** [comment]
+1

**Comment by gregdek** [comment]
Thanks @alextricity25 for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by alextricity25** [comment]
Maybe I'm trying to tackle too many problems at once here. I'm going to close and re-submit one PR for each bug report instead of solving all at once.

**Pull request closed without merging**
