### PR TITLE
support --disableplugin and --enableplugin YUM options

### PR DESCRIPTION
**Pull request by r1k0**
more details in https://github.com/ansible/ansible-modules-core/issues/2390

Let me know if it's "merge-able". If not how can I further help?
Thanks

### CODE REVIEW

**Comment by r1k0** [comment]
I'm now wondering if added parameters to install() shouldn't be passed as well to latest().
Let me know

**Comment by abadger** [comment]
yeas, we'd need it both for install and latest -- possibly to other subcommands as well.  I'm not sure if yum will shortciruit the repos if you do an erase or if it has to load that code no matter what, for instance.

Do these also need to be used with repoquery?  Can these be used to replace the repoquery code (which seems to exist because of exactly this error...)  What versions of RHEL are you testing this on (Need to make sure this works on rhel5 and above).

Instead of comma separated strings, use type=list in the argument spec.

**Comment by abadger** [comment]
And yes, this seems like a useful feature, so once we get questions answered and code tweaked we should be able to merge this.

I'm abadger1999 on irc.freenode.net in case this drops off my radar and you need to remind me to look at a new version.

**Comment by gregdek** [comment]
@r1k0 It looks as though @abadger has recommended some revisions. 

Please make the suggested revisions, and when you're done, please add a comment with the text "ready_for_review" and we will continue with the review process.  Thanks!

**Comment by gregdek** [comment]
@r1k0 A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes.

**Pull request closed without merging**
