### PR TITLE
Fixed an issue with unarchive with not found files

### PR DESCRIPTION
**Pull request by hryamzik**
Please see #3228 for details.

### CODE REVIEW

**Comment by dagwieers** [comment]
Similar fix as #2438, please discuss with @mmatuska for the best approach and a common description and solution.

**Comment by hryamzik** [comment]
@dagwieers wow, thanks, I think we can close this one.

**Comment by resmo** [comment]
Thanks @hryamzik for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

**Comment by vmindru** [comment]
bumping, can we review and ship this?

**Comment by abadger** [comment]
It looks like this was fixed by https://github.com/ansible/ansible-modules-core/pull/3307  Please feel free to open a new bug report referencing this one if that is not the case.

**Pull request closed without merging**
