### PR TITLE
ensure remote_head is defined before reference

### PR DESCRIPTION
**Pull request by sbussetti**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

source_control/git
##### ANSIBLE VERSION

```
ansible 2.3.0
```
##### SUMMARY

When doing a forced shallow git checkout, if local modifications exist, ansible throws an exception due to referencing remote_head before it's defined in the particular execution branch.

example play:

```

    - name: Deploy Source
      become: true
      become_user: "{{deploy_user}}"
      git:
        accept_hostkey=True
        depth=1
        force=True
        repo="{{repo_url}}"
        dest="{{www_root}}"
        remote="{{repo_remote}}"
        version="{{repo_branch}}"
        key_file="/home/{{deploy_user}}/.ssh/id_rsa"

```

Before:

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: UnboundLocalError: local variable 'remote_head' referenced before assignment
fatal: [10.11.255.38]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_DWVSvt/ansible_module_git.py\", line 1023, in <module>\n    main()\n  File \"/tmp/ansible_DWVSvt/ansible_module_git.py\", line 974, in main\n    result.update(changed=True, after=remote_head, msg='Local modifications exist')\nUnboundLocalError: local variable 'remote_head' referenced before assignment\n", "module_stdout": "", "msg": "MODULE FAILURE"}
```

After, no exception during a forced shallow checkout.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @sbussetti for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by ryansb** [comment]
Please rebase or reissue this PR without all the whitespace changes. Making a nonsemantic changes like that make it harder to use tools like git blame on the codebase.

**Comment by sbussetti** [comment]
Blah sorry, my editor does that automatically, will fix.

**Comment by sbussetti** [comment]
Okay @ryansb unintentional whitespace changes are cleaned up.

**Comment by cschroed** [comment]
Any chance this can be reviewed and merged?

This bug is present in Ansible 2.2.0.0 on Ubuntu 14.x and preventing my builds from completing.

Thank you for your consideration.

**Comment by hansbogert** [comment]
Is it me or are the whitespace  changes still present in the to-be-merged branch?

**Comment by sbussetti** [comment]
@hansbogert No.

The original  file was not pep8 compliant and had a lot of trailing whitespace.  I went back and undid the accidental whitespace cleanup in my branch.  Since then someone else must have fixed the trailing whitespace issues in devel.  I just pulled in those changes into my devel branch and updated.  Should be all clear now.

**Comment by gregdek** [comment]
Thanks @sbussetti for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by sbussetti** [comment]
@gregdek Just checked the logs and this test failure doesn't seem related to my change -- the actual shippable build job is complaining about:

```

2016-11-11 16:19:22 TASK [git : Import Jamie Evans GPG key] ****************************************
2016-11-11 16:19:54 fatal: [testhost]: FAILED! => {"changed": true, "cmd": ["gpg", "--keyserver", "pgp.mit.edu", "--recv-key", "61107C8E"], "delta": "0:00:31.742787", "end": "2016-11-11 16:19:54.850015", "failed": true, "rc": 2, "start": "2016-11-11 16:19:23.107228", "stderr": "gpg: directory `/root/.gnupg' created\ngpg: new configuration file `/root/.gnupg/gpg.conf' created\ngpg: WARNING: options in `/root/.gnupg/gpg.conf' are not yet active during this run\ngpg: keyring `/root/.gnupg/secring.gpg' created\ngpg: keyring `/root/.gnupg/pubring.gpg' created\ngpg: requesting key 61107C8E from hkp server pgp.mit.edu\ngpg: no valid OpenPGP data found.\ngpg: Total number processed: 0\ngpg: keyserver communications error: keyserver helper general error\ngpg: keyserver communications error: unknown pubkey algorithm\ngpg: keyserver receive failed: unknown pubkey algorithm", "stdout": "gpgkeys: key 61107C8E can't be retrieved", "stdout_lines": ["gpgkeys: key 61107C8E can't be retrieved"], "warnings": []}
```

**Comment by gregdek** [comment]
Thanks @sbussetti -- we'll look into it.

bot_broken

**Comment by ryansb** [comment]
Looks good to me :ship:

**Comment by gregdek** [comment]
@sbussetti A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by sbussetti** [comment]
@gregdek -- there was an error with shippable, but otherwise @ryansb said lgth

**Comment by gregdek** [comment]
Sigh -- why did this not pick up my bot_broken? Sorry...

**Comment by abadger** [comment]
I've migrated this into the ansible/ansible repo: https://github.com/ansible/ansible/pull/19257 since it has a shipit from ryansb already.  If it passes in shippable I'll merge to devel.

**Comment by abadger** [comment]
Discussed on https://github.com/ansible/ansible/pull/19057 and merged that alternative to devel

**Pull request closed without merging**
