### PR TITLE
Cloudformation - remove dead invoke_with_throttling_retries function

### PR DESCRIPTION
**Pull request by adamchainz**
Unused since f040d63403f6c459a278918fa48fa8cb87754506.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @adamchainz. To the current maintainers, @tedder, @ryansb please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by tedder** [comment]
Thanks Adam. Confirmed, `shipit`.

**Comment by gregdek** [comment]
Thanks again to @adamchainz for this PR, and thanks @tedder, @ryansb for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by adamchainz** [comment]
Thanks! 🎉

**Pull request merged**
