### PR TITLE
Fix #3119: elasticache module not idempotent: Fails if cluster alread…

### LINKED ISSUE #3119: elasticache module not idempotent: Fails if cluster already exists
##### Issue Type:
- Bug Report
##### Plugin Name:

elasticache
##### Ansible Version:

```
ansible 2.1.0
  config file =
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

Default
##### Environment:

N/A
##### Summary:

The elasticache module correctly creates an elasticache cluster, but running the same playbook again fails it if the cluster already exists.
##### Steps To Reproduce:

```
    - name: Create Elasticache node
      elasticache:
        name: "my-cluster"
        state: present
        engine: memcached
        node_type: cache.t2.small
        num_nodes: 1
        cache_port: 11112
        wait: no
        hard_modify: no
        region: "us-west-2"
        cache_subnet_group: "my-subnet-group"
        security_group_ids: ["sg-1234567"]
```
##### Expected Results:

Running the above repeatedly should succeed with the first execution creating the cluster and subsequent executions seeing that it exists and moving on
##### Actual Results:

Running the above twice fails with the error:

```
TASK [Create Elasticache node] *************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "msg": "Cache cluster already exists"}
```

### PR DESCRIPTION
**Pull request by njsaunders**
##### Issue Type:
- Bugfix Pull Request
##### Plugin Name:

elasticache
##### Summary:

Fixes #3119

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @njsaunders. @jsdalton please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by njsaunders** [comment]
Related: https://github.com/ansible/ansible-modules-core/pull/3133

**Comment by gregdek** [comment]
Thanks @njsaunders. To the current maintainers, @jsdalton, @alachaum please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by linuxdynasty** [comment]
@njsaunders this fix works well for me. :shipit: shipit

**Comment by fvant** [comment]
shipit

**Pull request closed without merging**
