### PR TITLE
Allow for multiple url to be specified in key parameter

### PR DESCRIPTION
**Pull request by giacomolozito**
Hi,
in the key parameter of the authorized_key module it is possible to specify multiple keys separated by newlines but it's only possible to specify a single URL to download keys from.

This small patch extends the logic to allow for usage of multiple newline-separated URLs to fetch keys from, in the same way of multiple keys. Incidentally, it's also possible to specify a combination of multiple URLs and keys.

I believe this to be important because the usage of the exclusive parameter rules out the possibility of doing the same thing using a loop.

With this I can have a variable with my keys from different URLs:

``` yaml
authkeys:
  - https://foo/bar/some.keys
  - https://github.com/somemore.keys
  - ...
```

and add them in a batch with

``` yaml
authorized_key: user=foo key={{ authkeys | join('\n') }} exclusive=yes
```

### CODE REVIEW

**Comment by mgedmin** [comment]
I don't know if this counts as a "community review", but I've looked at the diff, and it looks good to me.

The feature itself is something I naively expected to be supported, after reading the docs, exactly in the manner implemented here (one URL per line).  It's required in order to use `exclusive=yes` with multiple URL-supplied keys.

**Comment by gregdek** [comment]
@giacomolozito Thanks for your pull request. This module is currently owned by the Core team, and it can take a while for these patches to be reviewed. Thanks for your patience here.

**Comment by gregdek** [comment]
Thanks @giacomolozito for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@giacomolozito A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@giacomolozito Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
