### PR TITLE
New parameter supported in cloudformation: template_format.

### PR DESCRIPTION
**Pull request by JoseLuisMD**
Added support to a new parameter for cloudformation module: template_format. 

This parameter allows the user to choose the format of the template specified file: 'json' or 'yaml'. The parameter is not required, and it has 'json' as default value. 

If the 'yaml' option is chosen, the module loads the yaml file and converts it to .json format.

### CODE REVIEW

**Comment by adamchainz** [comment]
You might like https://github.com/cloudtools/troposphere which lets you define templates programatically in python with argument checking. You could even execute a troposphere script with an ansible `pipe` lookup: http://docs.ansible.com/playbooks_lookups.html#more-lookups .

**Comment by tedder** [comment]
I have a more nuanced version of this called "cloudformation_assemble". It uses yaml and allows a full directory/file structure to be compiled into a final template.

The other advantage of cloudformation_assemble is the output can be stuffed onto S3, which has a much larger template size limit.

**Comment by juliedavila** [comment]
@JoseLuisMD could you clean this up? Ideally there should not be any merge commits (184a9e896f4a89eb564367cbc9b8ffd9a38bf556). 

I'm not sure how I feel about this. Will think about it. Is it a common thing to write CFT in YAML?

**Comment by tedder** [comment]
> Is it a common thing to write CFT in YAML?

Writing CloudFormation in YAML is awesome. It's much less fussy.

**Comment by juliedavila** [comment]
@tedder cool, Im open to it. Do you have a PR for `cloudformation_assemble`? or did I misunderstand that?

**Comment by tedder** [comment]
@defionscode I will add a PR. I haven't been motivated since PRs sit around for so long.

**Comment by juliedavila** [comment]
@tedder cool, yeah sorry about that, I'm working on helping with all the AWS related backlog at the moment. Be sure to mention me on your PR so I can take look once you have it up.

**Comment by gregdek** [comment]
@JoseLuisMD apologies for letting this PR sit for so long. If you still believe it applies, please rebase this PR and we will put it into the community review process immediately.

**Comment by gregdek** [comment]
Closing due to contributor inactivity.

**Pull request closed without merging**
