### PR TITLE
Set os_server metadata on existing instances

### LINKED ISSUE #5500: os_server module not updating metadata on a running instance
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
os_server module

##### ANSIBLE VERSION
```
ansible 2.2.0.0 (stable-2.2 c5d4134f37) last updated 2016/10/27 16:10:22 (GMT +100)
  lib/ansible/modules/core: (detached HEAD 0881ba15c6) last updated 2016/10/27 16:10:37 (GMT +100)
  lib/ansible/modules/extras: (detached HEAD 47f4dd44f4) last updated 2016/10/27 16:10:37 (GMT +100)
  config file = /home/luisg/provision/boxes/test/openstack/ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT
Running ansible on Debian.
Targeting OpenStack instances with CentOS 7.2

##### SUMMARY
Module `os_server` does not add meta key/value pairs (using option `meta`) to a running OS instance. Using the same options while creating the OS instance in the first place does add the meta key/value pairs.

##### STEPS TO REPRODUCE

This is an example playbook (it assumes your openstack env is correctly set and the same playbook has been run before without the `meta` option):
```

---
- hosts: localhost
  tasks:
    - name: Create instance
      os_server:
        name: instance
        image: some-image
        state: present
        meta:
          groups: 'some-group'
      register: instance

    - debug: var=instance
```

##### EXPECTED RESULTS
The above playbook should return the metadata argument within the debug output (abbreviated here):
```
TASK [debug] *******************************************************************
ok: [localhost] => {
    "instance": {
        "changed": true,
        "openstack": {
            "metadata": {
                "groups": "some-group"
            },
        },
    }
}
```

##### ACTUAL RESULTS
In contrast, the following is obtained, where metadata is returned empty:
```
TASK [debug] *******************************************************************
ok: [localhost] => {
    "instance": {
        "changed": true,
        "openstack": {
            "metadata": {},
        },
    }
}
```

Note the task notifies it changed, but nothing happens to the metadata, nor to any other result provided by ansible-playbook's output (just did a diff of two consecutive runs).

### PR DESCRIPTION
**Pull request by manics**
##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY

At present `os_server` can modify the floating IP on an existing instance, but most other properties are unchanged since they may require a rebuild of the instance. However user properties (the `os_server` `meta` arg) can be updated easily.

New or existing metadata keys/values will be added/updated on an existing instance, no keys will be deleted. This follows the behaviour of `shade.openstackcloud.OpenStackCloud.set_server_metadata`.

Fixes #5500.

`test.yml`:
```
- hosts: localhost

  tasks:

  - os_server:
      flavor_ram: 1024
      image: CentOS7
      key: test-key
      name: test-1
    register: instance

  - debug: msg={{ instance.openstack.metadata }}
```
`ansible-playbook test.yml`
```
 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [os_server] ***************************************************************
changed: [localhost]

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": {}
}

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=1    unreachable=0    failed=0   
```

Add some metadata:
```
  - os_server:
      flavor_ram: 1024
      image: CentOS7
      key: test-key
      meta:
        groups: 'test-group'
      name: test-1
    register: instance
```

Rerun without this PR:
```
TASK [os_server] ***************************************************************
ok: [localhost]

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": {}
}

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0   
```
Rerun with this PR:
```
TASK [os_server] ***************************************************************
changed: [localhost]

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": {
        "groups": "test-group"
    }
}

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=1    unreachable=0    failed=0   
```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @manics. To the current maintainers, @emonty, @shrews, @juliakreger, @j2sol, @rcarrillocruz please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Review by omgjlk — APPROVED** [review]
I think this looks fine, but I haven't had a chance to test it. I'd like somebody else to also chime in before giving it a ship nod.

**Comment by gregdek** [comment]
Thanks @manics for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by manics** [comment]
ready_for_review

If it's useful here's a test playbook:

```
- hosts: localhost
  connection: local

  vars:
    - vm_image: CentOS 7
    - vm_flavour: m1.small
    - vm_keyname: test-key

  tasks:

  - os_server:
      name: "test-os_server"
      state: absent

  - os_server:
      name: "test-os_server"
      state: present
      image: "{{ vm_image }}"
      key_name: "{{ vm_keyname }}"
      flavor: "{{ vm_flavour }}"
      meta:
        k1: v1
    register: vm

  - assert:
      that: "vm.openstack.metadata == dict(k1='v1')"

  - os_server:
      name: "test-os_server"
      state: present
      image: "{{ vm_image }}"
      key_name: "{{ vm_keyname }}"
      flavor: "{{ vm_flavour }}"
      meta:
        # k1 unchanged
        k2: v2
    register: vm

  - assert:
      that: "vm.openstack.metadata == dict(k1='v1', k2='v2')"

  - os_server:
      name: "test-os_server"
      state: present
      image: "{{ vm_image }}"
      key_name: "{{ vm_keyname }}"
      flavor: "{{ vm_flavour }}"
      meta:
        # k1 modified, k2 unchanged
        k1: v3
    register: vm

  - assert:
      that: "vm.openstack.metadata == dict(k1='v3', k2='v2')"
```

**Comment by gregdek** [comment]
Thanks @manics. To the current maintainers, @emonty, @shrews, @juliakreger, @j2sol, @rcarrillocruz please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by Thingee** [comment]
Looks good, and thank you for the test playbook @manics!

@j2sol, I've tested things myself and reviewed the patches. Everything looks good to me! :+1:

**Comment by omgjlk** [comment]
shipit

**Comment by gregdek** [comment]
Thanks again to @manics for this PR, and thanks @emonty, @shrews, @juliakreger, @j2sol, @rcarrillocruz for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
