### PR TITLE
ec2_ami_find: set is_public to 'true' or 'false'

### LINKED ISSUE #5600: ec2_ami_find is_public broken
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ec2_ami_find

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file =
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT
N/A
##### SUMMARY
is_public does not work for 'yes', true, 'True', or 'true'

##### STEPS TO REPRODUCE
```
---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - ec2_ami_find:
      region: us-east-1
      architecture: x86_64
      hypervisor: xen
      is_public: yes
      name: amzn-ami-hvm*-gp2
      owner: amazon
      sort: creationDate
      sort_end: 1
      sort_order: descending
      state: available
      no_result_action: fail
    register: ec2_ami_find
  - debug:
      msg: 'AMI found: {{ ec2_ami_find.results[0].ami_id }}'
```
##### EXPECTED RESULTS
```
$ ansible-playbook -i localhost, -c local playbook.yml

PLAY [localhost] ***************************************************************

TASK [ec2_ami_find] ************************************************************
ok: [localhost]

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "AMI found: ami-b73b63a0"
}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0
```
##### ACTUAL RESULTS
```
$ ansible-playbook -i localhost, -c local playbook.yml

PLAY [localhost] ***************************************************************

TASK [ec2_ami_find] ************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "No AMIs matched the attributes: {\"hypervisor\": \"xen\", \"state\": \"available\", \"architecture\": \"x86_64\", \"name\": \"amzn-ami-hvm*-gp2\", \"is_public\": true}"}
	to retry, use: --limit @/etc/ansible/retry/plyabook.retry

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1
```

### PR DESCRIPTION
**Pull request by ssummer3**
##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
ec2_ami_find

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/etc/ansible/library']
```
##### SUMMARY
Allow documented is_public yaml values to work with boto, as per https://github.com/melta/boto/blob/master/boto/ec2/image.py (lines 60-71).

This is a workaround for a coding error in boto2, where a parameter is documented as a boolean, but treated as a string.

See #5600 for expected output.

fixes #5600 
---
Despite being a boolean property, https://github.com/melta/boto/blob/master/boto/ec2/image.py:63 sets is_public = True only if the argument is passed in as the string 'true'. Likewise for False/'false'.

This is a workaround for that bug in boto2, to allow the documented parameter to work with valid yaml values.

fixes #5600

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @ssummer3 for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by ssummer3** [comment]
Test fails due to @bcoca commit 88f1e67b1f4693a830e0f501efdcefb3aa9da0e8, #5610 by @simplesteph had to patch to files/stat.py to pass.

**Comment by ssummer3** [comment]
ready_for_review

**Comment by gregdek** [comment]
@ssummer3 A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by ssummer3** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @ssummer3. To the current maintainers, @tombamford please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
