### PR TITLE
ELB Proxy Protocol support for backends

### LINKED ISSUE #447: ec2_elb_lb to allow for setting policies
Issue Type:

Feature Idea

Ansible Version:

1.8.1

Environment:

Managing EC2 from generic.

Summary:

Boto allows for setting of ELB policies (i.e. create_lb_policy/delete_lb_policy, set_lb_policies_of_backend_server, set_lb_policies_of_listener).  This is in a similar vein of #386, but stickiness is set with a different api calls.  I would like the ability to define/set a policy with my ELB definition.  For example to be able to assign the proxypass to an ELB (http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/enable-proxy-protocol.html); if you use ELB in a HIPAA compliant setup you must use TCP pass through with https connection but to get the forwarded originating client IP you have to use proxypass.  

Steps To Reproduce:

I would expect it would be an option like:
- local_action:
  module: ec2_elb_lb
  name: "test-please-delete"
  state: present
  zones:
  - us-east-1d
    listeners:
  - protocol: http
    load_balancer_port: 80
    instance_port: 80
    policies:
  - name: EnableProxyProtocol
    type: ProxyProtocolPolicyType
    attributes:
    - ProxyProtocol: true
      port: 443 
      policy_type: backend # or listener if it was a listener policy

This should map to the API requirements.  The policy_port would be the backend policy this would be the instance_port and lb_port for the listener policy.

Expected Results:

Have backend policy added to my load balancer?

Actual Results:

Just the default policies are set...

### PR DESCRIPTION
**Pull request by nbrownus**
##### Issue Type:

Feature Pull Request
##### Plugin Name:

ec2_elb_lb
##### Summary:

Adds the following capabilities:
- Enable proxy protocol per listener
- Assert all instances registered with the elb instance

Fixes #447 
##### Example:

See PR, updated examples doc

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @nbrownus. @jsdalton @rickmendes please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by ghost** [comment]
@nbrownus Thanks for adding this. It has been a want in Ansible for awhile so it will make a lot of people happy to see it.

@gregdek Looks good to me. shipit

**Comment by gregdek** [comment]
Thanks again to @nbrownus for this PR, and thanks @jsdalton @rickmendes for reviewing. Marking for inclusion.

**Comment by Dmitry1987** [comment]
Hi, I think the documentation is outdated:
http://docs.ansible.com/ansible/ec2_elb_lb_module.html

says nothing about policies to attach that are 'required' and not optional now. so the module basically fails in any case, no matter what I do, if i follow documentation, it will fail anyway, with:

`fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/var/lib/rundeck/.ansible/tmp/ansible-tmp-1461167736.77-96919374549876/ec2_elb_lb\", line 3528, in <module>\n    main()\n  File \"/var/lib/rundeck/.ansible/tmp/ansible-tmp-1461167736.77-96919374549876/ec2_elb_lb\", line 1193, in main\n    elb_man.ensure_ok()\n  File \"/var/lib/rundeck/.ansible/tmp/ansible-tmp-1461167736.77-96919374549876/ec2_elb_lb\", line 432, in ensure_ok\n    self._set_backend_policies()\n  File \"/var/lib/rundeck/.ansible/tmp/ansible-tmp-1461167736.77-96919374549876/ec2_elb_lb\", line 1008, in _set_backend_policies\n    backend_policies = self._get_backend_policies()\n  File \"/var/lib/rundeck/.ansible/tmp/ansible-tmp-1461167736.77-96919374549876/ec2_elb_lb\", line 1000, in _get_backend_policies\n    str(backend.instance_port) + ':' + policy.policy_name for backend in self.elb.backends\nTypeError: 'NoneType' object is not iterable\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}`

can someone update documentation with required new parameter that it expects?  
thank you

**Comment by nbrownus** [comment]
I believe the logs are managed in another repo.

If you run that playbook again do you see the same error? I think it could be just on elb create and not update. You may be able to get around this by setting `proxy_protocol: False` on your listeners

```
listeners:
        - protocol: ...
          proxy_protocol: False
```

**Comment by Dmitry1987** [comment]
What i did for now is to run the same task of ELB creation twice ..  first one i set "ignore_errors" (it always fails) but 2nd one works...

i'll try your suggestion, thanks

**Comment by Dmitry1987** [comment]
unfortunately it had no effect :( , but thank you

**Pull request merged**
