### PR TITLE
win_file: fix error when creating an existing dir

### PR DESCRIPTION
**Pull request by ilpianista**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

win_file
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

Fix error when creating an existing dir.

If something else created the dir New-Item will throw an exception and the task will fail. Check the existing file and as long as it's a dir, we don't need to error out.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @ilpianista for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by ilpianista** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @ilpianista. To the current maintainers, @jhawkesworth please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Review by jhawkesworth — COMMENTED** [review]
Many thanks for this.

 I appreciate this is nitpicking, but I would prefer it if it did the test to see if the directory exists first, before attempting to create it, rather than the way the logic works now which is 'try to create and if it fails check if it already exists'.  

I understand the effect would be the same but generally I like ansible only to attempts changes when it needs to. 

Also it would be great if you could add to the existing integration tests to cover the directory case.  I assume you have an example of this as you must have encountered this problem while writing your own playbooks.  Right now the tests are in the main ansible fork, so you have to create a separate PR for them, but having tests makes it easier for reviewers to try out your changes.  Have a look in test/integration/roles/test_win_file/

You can run the tests by setting up some windows hosts in your inventory and doing the following (in a source checkout)
source hacking/env-setup
cd test/integration
export TEST_FLAGS='-t test_win_file -i <your inventory file>'
make test_winrm

if you have any questions about running integration tests or windows modules development, please ask on ansible-devel google group and I will do my best to help you.

If you can change the logic so it tests first and share a simple example playbook to demonstrate the effect of the change (as a comment on the PR would do, doesn't have to be in the integration tests), then I'd support merging this.

I know revising a PR can feel like a chore, and the changes I've requested are trivial, but I think its worth doing for core modules like this one that are going to get a lot of use.

needs_revision

**Comment by ilpianista** [comment]
Hi @jhawkesworth, the script already does a check [here](https://github.com/ilpianista/ansible-modules-core/blob/2e24e7be772de04629a3a37b07081c5ee4688909/windows/win_file.ps1#L66).

This cover the use case of two tasks running in parallel on the same host and creating the same dir. The Linux variant of this module (file) [does the same thing](https://github.com/ilpianista/ansible-modules-core/blob/devel/files/file.py#L316).

**Comment by jhawkesworth** [comment]
Sorry for delay replying.  I will test your PR and post back when I have tried it out.

**Comment by ilpianista** [comment]
Up!

**Comment by gregdek** [comment]
Thanks @ilpianista for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by ilpianista** [comment]
ready_for_review

**Comment by ilpianista** [comment]
ready_for_review

**Pull request closed without merging**
