### PR TITLE
Added support for reconfiguring network

### PR DESCRIPTION
**Pull request by stewrutledge**
Supports changing network settings (like which vswitch the vmware uses) on created virtual machines.

Useful if you have a specific net for staging deploys before moving them out to a different network.

A rebase from https://github.com/ansible/ansible-modules-core/pull/119

### CODE REVIEW

**Comment by gregdek** [comment]
@rhoop Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by stewrutledge** [comment]
shipit

**Comment by gregdek** [comment]
Sorry @stewrutledge -- only the owner of a module can give the "shipit" command.

**Comment by rhoop** [comment]
Code looks good. I will need to test this tomorrow.

**Comment by stewrutledge** [comment]
Sorry misunderstood!

**Comment by chrrrles** [comment]
Hello @rhoop  - Have you had a chance to test this PR yet?

**Comment by chrrrles** [comment]
This playbook ran succesfully, however the vm nic type did not change from vmxnet3 to vmxnet2 as expected.  Using VCenter Version 6.0.0 Build 2793784

```
- hosts: localhost
  connection: local
  vars_files: 
    - vars.yml
  tasks:
    - vsphere_guest:
        vcenter_hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        guest: newvm001
        state: powered_on
        vm_extra_config:
          vcpu.hotadd: yes
          mem.hotadd:  yes
          notes: This is a test VM
        vm_disk:
          disk1:
            size_gb: 10
            type: thin
            datastore: "{{ vm_ds }}"
        vm_nic:
          nic1:
            type: vmxnet3
            network: VM Network
            network_type: standard
        vm_hardware:
          memory_mb: 2048
          num_cpus: 2
          osid: centos64Guest
          scsi: paravirtual
        esxi:
          datacenter: "{{ vm_dc }}"
          hostname: "{{ esxi_host }}"

    - vsphere_guest:
        vcenter_hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        guest: newvm001
        state: reconfigured
        vm_extra_config:
          vcpu.hotadd: yes
          mem.hotadd:  yes
          notes: This is a test VM
        vm_disk:
          disk1:
            size_gb: 10
            type: thin
            datastore: "{{ vm_ds }}"
        vm_nic:
          nic1:
            type: vmxnet2
            network: VM Network
            network_type: standard
        vm_hardware:
          memory_mb: 2048
          num_cpus: 2
          osid: centos64Guest
          scsi: paravirtual
        esxi:
          datacenter: "{{ vm_dc }}"
          hostname: "{{ esxi_host }}"
```

**Comment by stewrutledge** [comment]
I didn't think of changing network type, only the network switch.

The case these changes covered was deploying a machine to a pxe deploy network then moving then to a productions network after the deploy is complete.

I can take a look at that bit, but what is the case for changing vmnic type?

**Comment by chrrrles** [comment]
Ahh - I see now that this is not meant to reconfigure the interface type.  The use cases for doing this are all edge cases, and I don't believe it is important.

**Comment by chrrrles** [comment]
Hello @stewrutledge - thanks for this PR.  Merging this feature into vsphere_guest for testing by the community.

**Comment by Xat59** [comment]
Hi guys !
Thank @stewrutledge for this commit . Unfortunately I'm not able to add a nic to an existing VM . Is this working well ?

Thank .

**Pull request merged**
