### PR TITLE
[GCE] named_ports support in Managed Instance Groups.

### PR DESCRIPTION
**Pull request by supertom**
##### ISSUE TYPE

- Feature Pull Request
##### COMPONENT NAME

gce_mig
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel 35a3653dfc) last updated 2016/08/25 18:59:53 (GMT +000)
  lib/ansible/modules/core: (gce-mig-namedports a36aa72803) last updated 2016/10/05 17:16:10 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD 101f9f5f46) last updated 2016/08/15 21:29:47 (GMT +000)
  config file = /home/supertom/.ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

[named_ports](https://cloud.google.com/compute/docs/reference/latest/instanceGroups/setNamedPorts) can now be set for Managed Instance Groups.  named_ports are a list of `{ 'name' : 'port' }` dictionaries that are used to direct traffic to a GCE Instance Group.  This is required in order to use MIGs with Backend Services (and load balancers).

Details about named_ports can be found [here](https://cloud.google.com/compute/docs/reference/latest/instanceGroups/setNamedPorts).

For output, a _set_named_ports_ and _updated_named_ports_ keys have been added to notify the user if the ports have changed.

A guard has been added to prevent this feature from being attempted with libcloud versions without this support (currently, you'll need to use the libcloud version in [trunk](apache/libcloud/trunk) to use this.)

Example Playbook

```
- name: Managed Instance Group Example
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Create MIG
      gce_mig:
        name: ansible-mig-example
        zone: us-central1-c
        state: present
        size: 1
        template: my-instance-template-1
        named_ports:
        - name: http
          port: 80
        - name: foobar
          port: 82
```

### CODE REVIEW

**Comment by gregdek** [comment]
maintainer unknown ping @gregdek @resmo @robynbergeron.

**Comment by supertom** [comment]
@ryansb PTAL, added named_ports to output and return documentation as you suggested.

**Comment by gregdek** [comment]
Thanks @supertom for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by supertom** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @supertom. To the current maintainers, @supertom please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by supertom** [comment]
shipit

**Comment by gregdek** [comment]
Thanks @supertom. Since you are one of the maintainers (@supertom) of this module and you commented with "shipit", we are marking this PR for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request merged**
