### PR TITLE
ec2_group with purge_rules will purge too many rules.

### LINKED ISSUE #697: ec2_group with purge_rules will purge too many rules.
##### Issue Type:

Bugfix Pull Request
##### Ansible Version:

develop
##### Environment:

N/A
##### Summary:

With purge_rules, if any grant in an EC2 rule needs to be purged, ec2_group purges multiple grants within that rule.
##### Steps To Reproduce:

Fill in the redacted info in this gist and run the playbook: https://gist.github.com/joelthompson/af072ded3c3627a3b557
##### Expected Results:

The EC2 security group should have grants that allow in 10.0.0.0/24 and 10.0.1.0/24.
##### Actual Results:

The EC2 SG has grants that only allow 10.0.1.0/24

### PR DESCRIPTION
**Pull request by joelthompson**
##### Issue Type:

Bugfix Pull Request
##### Ansible Version:

develop
##### Environment:

N/A
##### Summary:

With purge_rules, if any grant in an EC2 rule needs to be purged, ec2_group purges multiple grants within that rule.
##### Steps To Reproduce:

Fill in the redacted info in this gist and run the playbook: https://gist.github.com/joelthompson/af072ded3c3627a3b557
##### Expected Results:

The EC2 security group should have grants that allow in 10.0.0.0/24 and 10.0.1.0/24.
##### Actual Results:

The EC2 SG has grants that only allow 10.0.1.0/24

### CODE REVIEW

**Comment by abadger** [comment]
Review of the code looks good.  I don't use ec2_group so if someone who does would like to review and +1 this that would make me feel more comfortable with merging. :-)

**Comment by tgerla** [comment]
Is this the same as #748?

**Comment by joelthompson** [comment]
@tgerla -- #748 has slightly different symptoms than I noticed, but I was able to reproduce the new symptoms reported and validated that my PR will also resolve that symptom.

**Comment by abadger** [comment]
Thanks @joelthompson for the fix and thanks @tgerla for getting some testing on this!

# Merged

Hi!

This has been merged in, and will also be included in the next major release.

If you or anyone else has any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Pull request merged**
