### PR TITLE
ec2_lc: allow use of security group names (via module_utils/ec2.py)

### PR DESCRIPTION
**Pull request by brandond**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

cloud/amazon/ec2_lc
##### ANSIBLE VERSION

```
ansible 2.2.0
  config file = /home/ec2-user/repos/infosec-ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

Use `get_ec2_security_group_ids_from_names` from `module_utils/ec2.py` to allow use of Security Group names, in addition to IDs.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @brandond for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @brandond for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by brandond** [comment]
rebased ready_for_review

**Comment by gregdek** [comment]
Thanks @brandond for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @brandond for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by brandond** [comment]
ready_for_review again...

**Comment by gregdek** [comment]
Thanks @brandond for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
