### PR TITLE
ec2_key.py - Added RETURN structure and minor exception handling

### PR DESCRIPTION
**Pull request by Constantin07**
This PR just adds RETURN structure and minor exception handling for boto calls.

### CODE REVIEW

**Comment by gregdek** [comment]
@zbal Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by gregdek** [comment]
@zbal This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by robynbergeron** [comment]
@zbal still waiting on your review.  Please comment with text 'shipit' or 'needs_revision' as appropriate. If we don't hear from you within 14 days, we will start to look for additional maintainers for this module.

**Comment by gregdek** [comment]
@zbal This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by Constantin07** [comment]
When this PR will be reviewed?

**Comment by Constantin07** [comment]
Any updates?

**Comment by gregdek** [comment]
Thanks @Constantin07 for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

**Pull request closed without merging**
