### PR TITLE
[git] Fix shallow cloning a tag (Fixes #3817)

### LINKED ISSUE #3817: git - in Ansible 2.1 switching a shallow clone from tag to branch fails
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

git module
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file =
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

Vanilla
##### OS / ENVIRONMENT

Happens on both OS X and Ubuntu with different versions of git (1.8 and 1.9)
##### SUMMARY

Updating a shallow clone based on a tag to one based on a branch fails
##### STEPS TO REPRODUCE

Run this with `ansible-playbook -i 127.0.0.1, ~/tmp/test.yml; rm /tmp/testclone`

```
- hosts: 127.0.0.1
  connection: local
  gather_facts: no
  tasks:
    - name: initial clone from tag
      git:
        repo: git@github.com:adamchainz/nose-randomly.git
        dest: /tmp/testclone
        version: 1.2.0
        depth: 1

    - name: update to branch
      git:
        repo: git@github.com:adamchainz/nose-randomly.git
        dest: /tmp/testclone
        version: master
        depth: 1
```
##### EXPECTED RESULTS

On Ansible 2.0.2.0, it works fine:

```
PLAY [127.0.0.1] ***************************************************************

TASK [initial clone from tag] **************************************************
changed: [127.0.0.1]

TASK [update to branch] ********************************************************
changed: [127.0.0.1]

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=2    changed=2    unreachable=0    failed=0
```
##### ACTUAL RESULTS

On Ansible 2.1.0.0, I get:

```
PLAY [127.0.0.1] ***************************************************************

TASK [initial clone from tag] **************************************************
changed: [127.0.0.1]

TASK [update to branch] ********************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: IOError: [Errno 2] No such file or directory: '/tmp/testclone/.git/refs/remotes/origin/HEAD'
fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/_z/wpddpg7d5hd6fd2zjn_fct7m0000gn/T/ansible_vBeq0g/ansible_module_git.py\", line 877, in <module>\n    main()\n  File \"/var/folders/_z/wpddpg7d5hd6fd2zjn_fct7m0000gn/T/ansible_vBeq0g/ansible_module_git.py\", line 832, in main\n    fetch(git_path, module, repo, dest, version, remote, depth, bare, refspec)\n  File \"/var/folders/_z/wpddpg7d5hd6fd2zjn_fct7m0000gn/T/ansible_vBeq0g/ansible_module_git.py\", line 530, in fetch\n    currenthead = get_head_branch(git_path, module, dest, remote)\n  File \"/var/folders/_z/wpddpg7d5hd6fd2zjn_fct7m0000gn/T/ansible_vBeq0g/ansible_module_git.py\", line 498, in get_head_branch\n    f = open(os.path.join(repo_path, 'refs', 'remotes', remote, 'HEAD'))\nIOError: [Errno 2] No such file or directory: '/tmp/testclone/.git/refs/remotes/origin/HEAD'\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}

NO MORE HOSTS LEFT *************************************************************
    to retry, use: --limit @/Users/adamj/tmp/test.retry

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=1    changed=1    unreachable=0    failed=1
```

It looks like `fetch` has started assuming that if we're updating to a remote branch, we must currently be on a branch, as per lines 530-532:

``` py
        elif is_remote_branch(git_path, module, dest, repo, version):
            currenthead = get_head_branch(git_path, module, dest, remote)
            if currenthead != version:
```

or that `get_head_branch` should work, but doesn't, when we're on a tag. N.B. this is the contents of the `.git` directory after the clone from tag:

```
$ tree /tmp/testclone/.git/refs
/tmp/testclone/.git/refs
├── heads
└── tags

2 directories, 0 files
```

### PR DESCRIPTION
**Pull request by veger**
##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME
git

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY
While trying to reproduce #3817 using Ubuntu1604 test container., I noticed that the initial clone of a tag failed (the issue describes that the update to a branch should fail).

```
TASK [git : initial clone from tag] ********************************************
fatal: [testhost]: FAILED! => {"changed": false, "cmd": "/usr/bin/git checkout --force 1.2.0", "failed": true, "msg": "Failed to checkout 1.2.0", "rc": 1, "stderr": "error: pathspec '1.2.0' did not match any file(s) known to git.\n", "stdout": "", "stdout_lines": []}
```

The error suggests that the tag is not present, when explicitly fetching the tag with `--branch 1.2.0` the clone/test works (which is what this PR adds)

### CODE REVIEW

**Comment by veger** [comment]
@robinro can you lend your Ansible test git repo for the test of https://github.com/ansible/ansible/issues/18730 ?

**Comment by gregdek** [comment]
Thanks @veger for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by veger** [comment]
What to do with the timeout of the freebsd test? (the console output is absent, so I do not know what is happening here)

**Comment by gregdek** [comment]
Thanks @veger for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Review by robinro — COMMENTED** [review]
Thanks @veger for this PR.

This change is only needed for shallow clones, so the codepath should be in the `if depth` section, right?

Also please be aware that is_remote_branch and is_remote_tag call `git ls-remote` operations and are thus slow. I'd recommend to add some caching code to those routines, so we don't call `ls-remote` more often than absolutely necessary.

**Comment by robinro** [comment]
You can ignore the freebsd issue, since it's unrelated to your change.

**Comment by robinro** [comment]
@gregdek bot_broken (more like: test breakage unrelated, but this should be core_review now)

**Comment by robinro** [comment]
You can add `Fixes #3817` to your pull request description to autoclose that issue once this is merged.

**Comment by veger** [comment]
Removed the additional `is_remote_branch` and `is_remote_tag` calls to prevent performance issues. As a result `cmd.extend([ '--depth', str(depth) ])` is now twice in the code. Otherwise things would become (even more) messy.

The code is now in the 'depth' branch as well.

**Comment by veger** [comment]
An additional change is that only for tags the `--branch` parameter is added. For branches this breaks the 'shallow test' (noticed when adding a shallow test to https://github.com/ansible/ansible/pull/18728 ), so I guess this is managed by git itself

**Comment by veger** [comment]
Merged this PR with https://github.com/ansible/ansible/pull/18730

**Pull request closed without merging**
