### PR TITLE
adding parameter group option

### PR DESCRIPTION
**Pull request by awesomescot-zz**
This is almost the same as this PR, which never got merged due to a typo...  https://github.com/ansible/ansible-modules-core/pull/781/files

So trying again with fixed typo.  This would be very helpful for managing elasticache in Ansible.

### CODE REVIEW

**Comment by gregdek** [comment]
@jsdalton Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please give it a +1; at that point, we will add the “priority_reviewed” flag to this PR, which will move it to the top of our queue for potential inclusion.

**Comment by gregdek** [comment]
@awesomescot apologies, but looks like this PR has become outdated while waiting for review and needs to be rebased.

**Comment by awesomescot-zz** [comment]
I have updated the PR by merging in the current devel, and you can now merge it.  But this PR is over 2 months old, I don't remember any of the details of this PR anymore and don't have time to get comfortable and test it again.

**Comment by gregdek** [comment]
@awesomescot thanks. It does look like a pretty simple patch.

@jsdalton can you review?

Please make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by jsdalton** [comment]
:+1:

**Comment by robynbergeron** [comment]
Translating :+1: as shipit :) Thanks @jsdalton for the review, and @awesomescot for the PR. 

Marking for inclusion, cc: @ansible/core team.

**Comment by bcoca** [comment]
was missing version_added

**Pull request merged**
