### PR TITLE
Fix replace

### PR DESCRIPTION
**Pull request by mscherer**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

replace
##### SUMMARY

code was broken after last merge ( cf comment on https://github.com/ansible/ansible-modules-core/commit/5728ef89f0764be9066fc1bf0fbbf7785e60f4cb )

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @mscherer. To the current maintainers, @EvanK please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by EvanK** [comment]
Should be resolved by #4646 
close_me

**Comment by gregdek** [comment]
Thanks @mscherer. One of the current maintainers, @EvanK requested to close this PR.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by bcoca** [comment]
closing via merged  #4646

**Pull request closed without merging**
