### PR TITLE
git: fix change testing when version is HEAD

### LINKED ISSUE #3024: [v2.1] git module always reports changed --check mode when version= is not explicitly specified
**Ansible Version**

ansible 2.1.0 (devel c485981d1a) last updated 2016/02/12 08:50:29 (GMT +300)
  lib/ansible/modules/core: (detached HEAD 8d126bd877) last updated 2016/02/12 08:50:23 (GMT +300)
  lib/ansible/modules/extras: (detached HEAD f6c5ed987f) last updated 2016/02/12 08:50:23 (GMT +300)

**Summary**

This is my task:

``` yaml
- git: repo=git@fridge.pov.lt:/git/{{ item }}.git dest=/var/www/{{ item }}
  with_items:
    - zope3.pov.lt
```

When I run `ansible-playbook` with `--check`, this task always reports `changed`.  In verbose mode:

```
changed: [fridge] => (item=zope3.pov.lt) => {"after": "d9872a99c4b4b411b3a295b2606e2d7b5f757f93", "before": "d9872a99c4b4b411b3a295b2606e2d7b5f757f93", "changed": true, "item": "zope3.pov.lt"}
```

Note how `before` and `after` point to the same git commit!

If I run _without_ `--check`, Ansible correctly reports

```
ok: [fridge] => (item=zope3.pov.lt) => {"after": "d9872a99c4b4b411b3a295b2606e2d7b5f757f93", "before": "d9872a99c4b4b411b3a295b2606e2d7b5f757f93", "changed": false, "item": "zope3.pov.lt", "local_changes": false, "submodules_changed": false}
```

This is a regression since 2.0.0.2.

### PR DESCRIPTION
**Pull request by mgedmin**
When `version` is not specified, it defaults to "HEAD".  "HEAD" is not a
remote tag, and it's not listed in the output of get_branches(), so we'd
keep repo_updated at the default value (None) and then return early with
changed=True in --check mode, even when before == after.

Fixes #3024.

### CODE REVIEW

**Comment by robynbergeron** [comment]
Thanks @mgedmin for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

**Comment by robinro** [comment]
While this fixes you problem, it might be time to clean up the whole check_mode implementation in the git module. I believe most of the checks leading up to repo_updated could be removed. I'd be happy to test/check some larger PR if you submit one.

**Comment by mgedmin** [comment]
That sounds like a good idea, but I don't know when I can find the time to take another look at the git module.

**Comment by gregdek** [comment]
Thanks @mgedmin for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by mgedmin** [comment]
Rebased.

ready_for_review

**Comment by gregdek** [comment]
Thanks @mgedmin for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by abadger** [comment]
Thanks @mgedmin !  merged to devel and stable-2.1.

**Comment by willthames** [comment]
@abadger @jimi-c looks like this was merged just after 2.1.1 RC1 was created - can we get it into RC2?

**Comment by willthames** [comment]
This change is confirmed as being in RC2

**Pull request merged**
