### PR TITLE
docker: support polling image by digest

### PR DESCRIPTION
**Pull request by awasilyev**
fix for #2917

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @awasilyev. @cove @joshuaconner @softzilla @smashwilson @zfil @ThomasSteinbach please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by smashwilson** [comment]
At first glance I thought this would discard the digest - but looking at the [Docker API endpoint](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#create-an-image), digests are actually accepted in the `tag` parameter anyway! Weird.

:+1: shipit

**Comment by gregdek** [comment]
Thanks again to @awasilyev for this PR, and thanks @cove @joshuaconner @softzilla @smashwilson @zfil @ThomasSteinbach for reviewing. Marking for inclusion.

**Comment by gregdek** [comment]
@awasilyev A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes.

**Comment by awasilyev** [comment]
thank you.
rebased.

**Comment by gregdek** [comment]
Thanks @awasilyev. @cove @joshuaconner @softzilla @smashwilson @zfil @ThomasSteinbach please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by awasilyev** [comment]
do we need anything else to review and merge this?

**Comment by gregdek** [comment]
I'll go ahead and interpret @smashwilson shipit as valid, since only a rebase was needed. Back into shipit.

**Pull request merged**
