### PR TITLE
Elasticache Module: changing default cache_security_group to none

### PR DESCRIPTION
**Pull request by noqcks**
I have been running into an error with the elasticache module, that I believe is tied to the `cache_security_groups` default value not being valid.

Here is the output

```
***********************************
RAW OUTPUT

Traceback (most recent call last):
  File "/Users/benvisser/.ansible_module_generated", line 2719, in <module>
    main()
  File "/Users/benvisser/.ansible_module_generated", line 505, in main
    argument_spec=argument_spec,
  File "/Users/benvisser/.ansible_module_generated", line 1128, in __init__
    self._check_required_arguments()
  File "/Users/benvisser/.ansible_module_generated", line 1709, in _check_required_arguments
    self.fail_json(msg="missing required arguments: %s" % ",".join(missing))
  File "/Users/benvisser/.ansible_module_generated", line 2103, in fail_json
    kwargs = remove_values(kwargs, self.no_log_values)
  File "/Users/benvisser/.ansible_module_generated", line 981, in remove_values
    return dict((k, remove_values(v, no_log_strings)) for k, v in value.items())
  File "/Users/benvisser/.ansible_module_generated", line 981, in <genexpr>
    return dict((k, remove_values(v, no_log_strings)) for k, v in value.items())
  File "/Users/benvisser/.ansible_module_generated", line 981, in remove_values
    return dict((k, remove_values(v, no_log_strings)) for k, v in value.items())
  File "/Users/benvisser/.ansible_module_generated", line 981, in <genexpr>
    return dict((k, remove_values(v, no_log_strings)) for k, v in value.items())
  File "/Users/benvisser/.ansible_module_generated", line 979, in remove_values
    return [remove_values(elem, no_log_strings) for elem in value]
  File "/Users/benvisser/.ansible_module_generated", line 990, in remove_values
    raise TypeError('Value of unknown type: %s, %s' % (type(value), value))
TypeError: Value of unknown type: <type 'object'>, <object object at 0x103e85120>

***********************************
INVALID OUTPUT FORMAT

Traceback (most recent call last):
  File "ansible/hacking/test-module", line 167, in runtest
    results = json.loads(out)
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

In this pull request, I want to set the default value of `cache_security_groups` to None.

### CODE REVIEW

**Comment by noqcks** [comment]
@jsdalton plz review

**Comment by robynbergeron** [comment]
Thanks @noqcks. @jsdalton please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by jsdalton** [comment]
needs_revision

Hm. In reviewing that error it looks like it might be an artifact related to this change:

https://github.com/ansible/ansible-modules-core/commit/efa4d0428482998a93533ee73a77f67830ff2256

Where the security groups are set to a "default" object as some sort of sentinel value. I think the behavior you're seeing is a bug related to that change.

I don't entirely disagree with your solution but I think any change to this feature should take the rest of the module's behavior into account. There are also one or two spots where the ['default'] value is documented that were missed.

As a workaround in the meantime, can you not explicitly set the cache security group to None if the playbook you're trying to use?

**Comment by robynbergeron** [comment]
Thanks @noqcks for this PR. A maintainer of this module has asked for revisions to this PR. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

**Comment by noqcks** [comment]
@jsdalton ready_for_review

I cleaned up the checks that had been created around efa4d04 for `default` object. I had to recommit some things because I accidentally merged devel commits into my branch. lmk what you think.

**Comment by jsdalton** [comment]
:+1: for the code and fixes.

Can you squash your changes down to a single commit? Should be good to go then.

**Comment by noqcks** [comment]
@jsdalton alright, squashed the changes, I believe...

Let me know if I need to do anything else. Cheers :beers:

**Comment by jsdalton** [comment]
ship_it

Looks good! I haven't run this code but it looks like it's in solid shape.

**Comment by gregdek** [comment]
Thanks @noqcks for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

**Comment by noqcks** [comment]
ready_for_review

:100:

**Comment by gregdek** [comment]
Thanks @noqcks. @jsdalton please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
Thanks @noqcks. @jsdalton please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
@jsdalton This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by jimi-c** [comment]
Merged, thanks!

**Pull request merged**
