### PR TITLE
amazon/ec2: add user_data_gzip boolean

### PR DESCRIPTION
**Pull request by dlamotte**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

core/cloud/amazon/ec2
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file =
  configured module search path = Default w/o overrides
```
##### SUMMARY

Allow users to specify if they'd like their user_data gzip'd.
Unfortunately, it's rather difficult to implement this as a filter due
to the resulting binary data and the handling of it at that level.

Futher, most people end up wanting to base64 the result of the gzip'd
user_data, but boto ends up doing that for you so there isn't room for a
gzip_and_base64 filter (which would work perfectly in ansible).

This option strikes a nice balance between the options.

Ubuntu and CoreOS are example AMIs that support gzip'd data.  When the size of `user_data` grows, it becomes required.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @dlamotte for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@dlamotte A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by jesselang** [comment]
In looking at the build results, it appears that the build failure was due to a syntax error in an unrelated module. Perhaps rebasing to current HEAD on master would offer better results.

**Comment by dlamotte** [comment]
Rebased.  We'll see what happens.

**Comment by jesselang** [comment]
ready_for_review

**Comment by gregdek** [comment]
@dlamotte Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by jesselang** [comment]
@dlamotte apparently you have to reply with ready_for_review?

**Comment by dlamotte** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @dlamotte for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
