### PR TITLE
add tar options to unarchive module

### PR DESCRIPTION
**Pull request by gesquive**
This patch allows users to specify command line options for the tar command in the unarchive module.

Example:

``` yaml
- name: Unpack an archive
  unarchive: src=/path/to/archive
             dest=/path/to/unpack
             tar_opts='--strip-components=1'
```

This is a feature I use frequently, and I have seen requests for it in closed tickets like [#2097](https://github.com/ansible/ansible/issues/2097)

### CODE REVIEW

**Comment by gregdek** [comment]
@pileofrogs Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by pileofrogs** [comment]
I was just about to do something similar but more generic.  IE extra options, but not only tar options.  See #2037 for some discussion on that.  Could you change your patch to support extra options that could be applied to any unarchive tool?  I'd be happy to do that myself, if you like.  There might be complexities in how pick_handler works and how is_unarchived works.  

Does anyone else have an opinion about this?

**Comment by gesquive** [comment]
@pileofrogs It looks like I should be able to modify my code without much work to have the options apply to all of the unarchive tools.

Did you want me to create a new pull request, or just modify this one?

**Comment by gesquive** [comment]
Personally, I like the flexibility of being able to apply the options to all of the unarchive tools.

I just created PR #2772 and prefer that option over this one.

**Comment by yeukhon** [comment]
Can I chime in? I feel like the option to archive should be independent of unarchive. The module name is not intuitive at first glance. "unarchive" but support archive seems pretty weird.

Since we normally want to support backward compatibility, I wonder if it makes sense to actually make a separate module, and then merge unarchive into archive through alias (if that's even possible but should be capable by basic python import), or just leave unarchive where it is.

cc: @gesquive  @pileofrogs

**Comment by gregdek** [comment]
Thanks @gesquive for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

**Comment by fgimian** [comment]
Would really love to see this across all the supported archivers, this would significantly improve usefulness of the unarchive module :smile:

**Comment by gesquive** [comment]
@fgimian I felt the same way. Take a look at PR #2772.

Since the other PR is going through, i'm going to close this one out.

**Pull request closed without merging**
