### PR TITLE
ignore_instances option + default value for min_size and max_size at autoscaling creation

### PR DESCRIPTION
**Pull request by galindro**
- https://github.com/ansible/ansible/issues/11070: ignore_instances option. List of instance_ids belonging to the named ASG that you would like to be ignored from replacement of the instances matching the current launch configuration.
- https://github.com/ansible/ansible-modules-core/issues/1445: Default value for min_size and max_size at autoscaling creation

### CODE REVIEW

**Comment by gregdek** [comment]
@galindro Thanks for submitting this pull request. Please accept our apologies for taking so long to review it.

Unfortunately, due to this delay, it appears that the underlying code has changed, and this PR needs to be rebased. If you believe that this PR still applies, please rebase and we will then put it into our (new, faster) community review process as soon as possible.  Again, apologies for the delay and the extra work.

**Comment by galindro** [comment]
Done

**Comment by gregdek** [comment]
Thanks @galindro.

@garethr Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please give it a +1; at that point, we will add the “priority_reviewed” flag to this PR, which will move it to the top of our queue for potential inclusion.

**Comment by galindro** [comment]
Guys, any return about this PR?

**Comment by bcoca** [comment]
ping @garethr for review

**Comment by galindro** [comment]
I've deleted my fork because nobody revised my PR. I'll try to make the changes again in another PR using a fresh repository. 

Who is responsible to view and test PRs? 3 months have passed and nobody merged it...

**Comment by galindro** [comment]
https://github.com/ansible/ansible-modules-core/pull/2203

**Pull request closed without merging**
