### PR TITLE
Allow os_server to delete FIP

### PR DESCRIPTION
**Pull request by Shrews**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

cloud/openstack/os_server.py
##### ANSIBLE VERSION

2.1
##### SUMMARY

The os_server module could automatically generate a floating IP for
the user with auto_ip=true, but we didn't allow for this FIP to be
automatically deleted when deleting the instance, which is a bug.
Add a new option called delete_fip that enables this.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks again to @Shrews. This module is going into community review.

We notice that you are one of the maintainers (@emonty, @shrews, @juliakreger, @j2sol, @rcarrillocruz) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by ghost** [comment]
LGTM

**Comment by rcarrillocruz** [comment]
shipit

**Comment by gregdek** [comment]
Thanks again to @Shrews for this PR, and thanks @emonty, @shrews, @juliakreger, @j2sol, @rcarrillocruz for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by resmo** [comment]
I am not sure how to handle this, the module is there since 2.0. 

This is a new argument so we need to add a `version_added`. Since this is called  a bug fix but has a new argument, should this be backported to 2.1? Then it would be `version_added: "2.1"`, if no backport is needed, we should add `version_added: "2.2".

**Comment by resmo** [comment]
merged to 2.2 for now, thanks!

**Pull request merged**
