### PR TITLE
Adding SNS notification support to ec2_asg module

### PR DESCRIPTION
**Pull request by shawnsi**
Addresses #1844

### CODE REVIEW

**Comment by robynbergeron** [comment]
Hi @shawnsi -- thanks for this PR, and the accompanying feature request issue (#1844).

@garethr -- Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by robynbergeron** [comment]
(Also, OMG @garethr, HAI! :sunny:)

**Comment by shawnsi** [comment]
@robynbergeron Anything I can do to help move the review process along?

**Comment by gregdek** [comment]
Thanks @shawnsi for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

**Comment by shawnsi** [comment]
@gregdek can a core reviewer look at this?  I think its a pretty straight forward update for AWS API compatibility.

**Comment by gregdek** [comment]
@shawnsi I'd recommend attending one of the Ansible Core team meetings on IRC:

https://github.com/ansible/community/blob/master/MEETINGS.md

**Comment by shawnsi** [comment]
@gregdek Ok. I don't really understand why a PR isn't sufficient for this but I'll pop in to the next one that fits my schedule.

**Comment by gregdek** [comment]
@shawnsi apologies. There are hundreds of PRs, and it can be challenging to prioritize.

**Comment by ryansb** [comment]
Merged as https://github.com/ansible/ansible-modules-core/commit/a29fb59a7224385e70239ffc007bb69beabfe268

**Comment by ryansb** [comment]
Merged as https://github.com/ansible/ansible-modules-core/commit/a29fb59a7224385e70239ffc007bb69beabfe268

**Pull request closed without merging**
