### PR TITLE
docker: fix failing in case of empty image tag

### LINKED ISSUE #2851: docker module: pull all version of images if version is null
In case of mistakenly specify 'null' as image version for docker module it tries to pull all versions of this image, wasting disk space. Reproduced both in 1.9.4 and 2.0

Steps to reproduce:
docker 1.9.1
ansible -m docker -a 'state=reloaded name=test net=bridge image=centos:' -c local localhost

Actual result:
docker tries to pull all existing centos image version

Expected result:
pulling only centos:latest or failing with 'image not found' error

### PR DESCRIPTION
**Pull request by awasilyev**
fixes #2851

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @awasilyev. @cove @joshuaconner @softzilla @smashwilson @zfil @ThomasSteinbach please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by smashwilson** [comment]
Interesting. The docker client accepts a terminating colon as an implicit `:` in version 1.9.1, but not in 1.10.1:

``` bash
$ dvm use 1.10.0
Now using Docker 1.10.0
$ docker pull postgres:
Error parsing reference: "postgres:" is not a valid repository/tag
$ dvm use 1.9.1
Now using Docker 1.9.1
$ docker pull postgres:
Using default tag: latest
latest: Pulling from library/postgres

Digest: sha256:0d8a3ffe9e4d8ef4245b9e529c6079382a96036ab62eba26d3231ae72dfddddc
Status: Image is up to date for postgres:latest
```

**Comment by smashwilson** [comment]
On reflection, I'm :+1: on allowing this in the docker module even if it's inconsistent with the new client, because it lets you do things like:

``` yaml
- name: docker things
  docker:
    image: my-image:{{ tag_var }}
```

And leave `tag_var` blank to default to `latest`.

:shipit: shipit

**Comment by gregdek** [comment]
Thanks again to @awasilyev for this PR, and thanks @cove @joshuaconner @softzilla @smashwilson @zfil @ThomasSteinbach for reviewing. Marking for inclusion.

**Comment by jimi-c** [comment]
Merged and cherry-picked to stable-2.0. Thanks!

**Comment by awasilyev** [comment]
May I backport this to the 1.9.x? Or 1.9.x releases no planned any more?

**Comment by jimi-c** [comment]
@awasilyev yes feel free.

**Pull request merged**
