### PR TITLE
Fixes bind mounts

### PR DESCRIPTION
**Pull request by Jmainguy**
This PR is to fix bind mounts. This is a bugfix

### CODE REVIEW

**Comment by Jmainguy** [comment]
Recreation of https://github.com/ansible/ansible/pull/8524

**Comment by rmetzler** [comment]
Very interested in seeing #86 closed, but this PR seems to be ill-indented. Seems like a mixed use of tabs and spaces.

**Comment by Jmainguy** [comment]
Yeah good call, I will try and clean it up tonight

**Comment by Jmainguy** [comment]
@rmetzler Fixed it I think, look it over and let me know if its nice or ugly.

**Comment by bcoca** [comment]
# Rebase Request

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us. 

It looks like the code underneath has changed since this was submitted.  Can you take care of rebasing this for us?
- You should be able to run "git rebase" against this branch to bring it up to date
- Resolve any merge conflicts and test changes
- Push to the same branch and github should update the pull request automatically.

Just as a quick reminder of things, this is a really busy project.  We have over 800 contributors and to manage the queue effectively
we assign things a priority between P1 (highest) and P5.  We'd like to thank you very much for your time!  
We'll work things in priority order, so just wanted you to be aware of the queue and know we haven't forgotten about you!

We will definitely see your comments on this issue when reading this ticket, but may not be able to reply promptly.  You may also wish to join one of our two mailing lists
which are very active:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Thank you once again for this and your interest in Ansible!

**Comment by Jmainguy** [comment]
@bcoca Rebased

**Comment by aleemb** [comment]
I just noticed today I have about half a dozen mounts for the same thing and ended up on this bug.

Can this PR be merged if possible?

**Comment by piotrplenik** [comment]
After investigation, I think problem is with Python method ``os.path.ismount()`. 
On Debian I discovered that this method does not return correct response. Test case: 

```
$ mkdir /tmp/a
$ mkdir /tmp/b
$ sudo mount --bind /tmp/a /tmp/b
$ python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.path.ismount('/tmp/a')
False
>>> os.path.ismount('/tmp/b')
False
```

Because, this method is used in mount.py in 5 times, I propose create new function, like `is_mount(path)`, that always return correct response, for bind and non bind mountpoints.

What do you think?

**Comment by AvtechScientific** [comment]
@bcoca, @Jmainguy,

I think parsing mount output doesn't always catch bind-mounted directories.

Here is my case: I'm on Debian9 (with btrfs), Ansible 2.2.1
Here is how I use the mount module:

```
- name: update /etc/fstab and mount /home/{{ user.username }}
  mount:
    src: /home/{{ user.username }}
    # ToDo: change name to path on v2.3
    name: /chroots/{{ user.username }}/home/{{ user.username }}
    fstype: bind
    opts: defaults,bind
    state: mounted
```

Here is how the mount excerpt ouptut looks like:

```
...
/dev/sda3 on /chroots/testuser3/home/testuser3 type btrfs (rw,relatime,space_cache,subvolid=258,subvol=/root_subvolume/home/testuser3)
/dev/sda3 on /chroots/testuser2/home/testuser2 type btrfs (rw,relatime,space_cache,subvolid=258,subvol=/root_subvolume/home/testuser2)
/dev/sda3 on /chroots/testuser1/home/testuser1 type btrfs (rw,relatime,space_cache,subvolid=258,subvol=/root_subvolume/home/testuser1)
/dev/sda2 on /boot type ext3 (rw,relatime,data=ordered)
tmpfs on /run/user/1000 type tmpfs (rw,nosuid,nodev,relatime,size=3281060k,mode=700,uid=1000,gid=1000)
```

It looks like `arguments[0] == args['src']` is false and so directories get mounted on each run...
I think the bug should be reopened...
Thank you!

**Pull request merged**
