### PR TITLE
Feature add ability to list elbs

### PR DESCRIPTION
**Pull request by alex-leonhardt**
This should allow people to get a list of ELBs available in a region, to then either remove them or add new hosts to these ELBs. I'm not 100% sure if this would break things, but asked for guidance on unit / integration testing this on ansible-project mailing list with little feedback.

### CODE REVIEW

**Comment by tedder** [comment]
Seems like a good combination to my #696.

**Comment by bcoca** [comment]
I'm pondering if we should just move both into an elb_facts module

**Comment by gregdek** [comment]
@alex-leonhardt Thanks for submitting this pull request. Please accept our apologies for taking so long to review it.

Unfortunately, due to this delay, it appears that the underlying code has changed, and this PR needs to be rebased. If you believe that this PR still applies, please rebase and we will then put it into our (new, faster) community review process as soon as possible.  Again, apologies for the delay and the extra work.

**Comment by gregdek** [comment]
A friendly reminder: this pull request has been marked as needing your action, and it hasn't been updated in the last month. 

If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we'll keep it open pending your changes.

If we receive no indication from you within a week, we will close this pull request.

**Comment by gregdek** [comment]
Closing due to inaction. @alex-leonhardt feel free to refile as a new PR.

**Pull request closed without merging**
