### PR TITLE
Fix EC2_EIP: don't try to associate an already-associated instance.

### PR DESCRIPTION
**Pull request by herbyg-axial**
Also stops it from allocating a new Elastic IP on every run.

### CODE REVIEW

**Comment by herbyg-axial** [comment]
This should resolve **ansible/ansible-modules-core#35**.

**Comment by herbyg-axial** [comment]
Additional changes to add a "state='allocated'" option, as well as correct the behavior when looking for unused elastic IPs.

Old behavior of allocating a new elastic IP when specified as just:
action: eip
..has been preserved.

**Comment by pguillebert** [comment]
This one bites me as well.

**Comment by juliedavila** [comment]
Could you elaborate what you mean by "don't try to associate an already-associated instance"

**Comment by pguillebert** [comment]
@nousdefions : The current behaviour of the plugin always allocate a new EIP ("creates" an IP) even if the EC2 instance is already happily associated with an EIP already. In other words, it breaks idempotence we expect from ansible.

**Comment by lamielle** [comment]
Any chance we can get this PR finished up and merged?  I'm running into the problem that this fixes.

**Comment by daniilyar** [comment]
Tested by including updated module as 'library' to my Ansible codebase. Works well, +1 to merge this one

**Comment by moorereason** [comment]
This bug is really annoying, but this PR could be tidied up a bit before merging.
- New `state` string should be an adjective, such as "allocated."
- Why define `allocate_eip()` [inside of main](https://github.com/axialops/ansible-modules-core/blob/c5d94ccac71273cf63d44c4f30698dc0e9b8c3f5/cloud/amazon/ec2_eip.py#L284)?  That function should probably be moved.

Looking forward to this PR being merged!!

**Comment by juliedavila** [comment]
@herbyg-axial 

I agree with @moorereason, the allocate_eip() should be moved out of main. Are you still working on this?

**Comment by theonlysinjin** [comment]
Has this not merged yet? I used this copy, it doesn't create new addresses on run, but it's still not associating with already existing, but free addresses

**Comment by herbyg-axial** [comment]
@moorereason @defionscode @sinjin I'll get this tidied up between today and tomorrow.  Thank you for taking a look :)

**Comment by juliedavila** [comment]
@herbyg-axial are you still working on this?

**Comment by jml** [comment]
I don't know if this is the done thing, but I really would like this fixed, so #1015 is a PR that's a clone of this one but with the recommended changes made.

**Comment by juliedavila** [comment]
@jml that looks good, just need the merge commit fixed.

**Comment by bendavies** [comment]
how are people working around this bug?

**Comment by moorereason** [comment]
@bendavies I've disabled the `ec2_eip` tasks in my playbooks until I know I have an instance that needs a new EIP.  Not much of a workaround.

**Comment by klj613** [comment]
any update on this?

**Comment by bennojoy** [comment]
@klj613  seems like #1015 fixes it , can you give the latest devel a try

**Comment by bennojoy** [comment]
closing, since fixed via #1015

**Pull request closed without merging**
