### PR TITLE
cloudformation updates tags

### PR DESCRIPTION
**Pull request by ferrants**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

cloudformation
##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.0.2.0
  config file = /Users/mferrante/code/dxansible/ansible.cfg
  configured module search path = Default w/o overrides

```
##### SUMMARY

In February, Amazon released support for updating cloudformation tags:
https://aws.amazon.com/about-aws/whats-new/2016/02/aws-cloudformation-adds-support-for-amazon-vpc-nat-gateway-amazon-ec2-container-registry-and-more/

This boto issue previously tracked the issue: https://github.com/boto/boto/issues/2032. i have suggested that this issue be closed. I tested with boto 2.40.0, though I do not know if this is a requirement for tags to work.

kwargs is only populated with tags, passing it to the update_stack function works. The update_stack function accepts tags:
http://boto.cloudhackers.com/en/latest/ref/cloudformation.html#boto.cloudformation.connection.CloudFormationConnection.update_stack

before changes:

```
changed: [localhost] => {"changed": true, "events": ["StackEvent AWS::CloudFormation::Stack qatools-mferrante-2016-05-12-13-11 UPDATE_COMPLETE", "StackEvent AWS::EC2::Instance mongodb DELETE_COMPLETE", "StackEvent AWS::AutoScaling::LaunchConfiguration qatoolsLc DELETE_COMPLETE", "StackEvent AWS::EC2::Instance mongodb DELETE_IN_PROGRESS", "StackEvent AWS::AutoScaling::LaunchConfiguration qatoolsLc DELETE_IN_PROGRESS", "StackEvent AWS::CloudFormation::Stack qatools-mferrante-2016-05-12-13-11 UPDATE_COMPLETE_CLEANUP_IN_PROGRESS", "StackEvent AWS::AutoScaling::AutoScalingGroup qatoolsAsg UPDATE_COMPLETE", "StackEvent AWS::AutoScaling::AutoScalingGroup qatoolsAsg UPDATE_IN_PROGRESS", "StackEvent AWS::AutoScaling::AutoScalingGroup qatoolsAsg UPDATE_IN_PROGRESS", "StackEvent AWS::AutoScaling::AutoScalingGroup qatoolsAsg UPDATE_IN_PROGRESS", "StackEvent AWS::AutoScaling::AutoScalingGroup qatoolsAsg UPDATE_IN_PROGRESS", "StackEvent AWS::AutoScaling::AutoScalingGroup qatoolsAsg UPDATE_IN_PROGRESS", "StackEvent AWS::EC2::Instance mongodb UPDATE_COMPLETE", "StackEvent AWS::EC2::Instance mongodb UPDATE_IN_PROGRESS", "StackEvent AWS::AutoScaling::LaunchConfiguration qatoolsLc UPDATE_COMPLETE", "StackEvent AWS::AutoScaling::LaunchConfiguration qatoolsLc UPDATE_IN_PROGRESS", "StackEvent AWS::EC2::Instance mongodb UPDATE_IN_PROGRESS", "StackEvent AWS::AutoScaling::LaunchConfiguration qatoolsLc UPDATE_IN_PROGRESS", "StackEvent AWS::CloudFormation::Stack qatools-mferrante-2016-05-12-13-11 UPDATE_IN_PROGRESS", "StackEvent AWS::CloudFormation::Stack qatools-mferrante-2016-05-12-13-11 CREATE_COMPLETE", "StackEvent AWS::AutoScaling::AutoScalingGroup qatoolsAsg CREATE_COMPLETE", "StackEvent AWS::AutoScaling::AutoScalingGroup qatoolsAsg CREATE_IN_PROGRESS", "StackEvent AWS::AutoScaling::AutoScalingGroup qatoolsAsg CREATE_IN_PROGRESS", "StackEvent AWS::EC2::Instance mongodb CREATE_COMPLETE", "StackEvent AWS::ElasticLoadBalancing::LoadBalancer qatoolsElb CREATE_COMPLETE", "StackEvent AWS::EC2::Instance mongodb CREATE_IN_PROGRESS", "StackEvent AWS::ElasticLoadBalancing::LoadBalancer qatoolsElb CREATE_IN_PROGRESS", "StackEvent AWS::AutoScaling::LaunchConfiguration qatoolsLc CREATE_COMPLETE", "StackEvent AWS::AutoScaling::LaunchConfiguration qatoolsLc CREATE_IN_PROGRESS", "StackEvent AWS::ElasticLoadBalancing::LoadBalancer qatoolsElb CREATE_IN_PROGRESS", "StackEvent AWS::EC2::Instance mongodb CREATE_IN_PROGRESS", "StackEvent AWS::AutoScaling::LaunchConfiguration qatoolsLc CREATE_IN_PROGRESS", "StackEvent AWS::CloudFormation::Stack qatools-mferrante-2016-05-12-13-11 CREATE_IN_PROGRESS"], "output": "Stack UPDATE complete", "stack_outputs": {"ansibleSshPrivateKeyFile": "/var/lib/jenkins/workspace/cloudformation-stack-dev/tmp/qatools-mferrante-2016-05-12-13-11-key.pem", "domain": "test.net", "environmentType": "qatools", "mongodbIp": "172.17.70.163", "qatoolsElbDnsName": "internal-qatools-m-qatoolsE-2ZFNCPLE10U8-1689238210.us-east-1.elb.amazonaws.com", "subnet": "172.17.64.0/19"}}
```

after changes:

```
changed: [localhost] => {"changed": true, "events": ["StackEvent AWS::CloudFormation::Stack qatools-mferrante-2016-05-12-13-11 UPDATE_COMPLETE", "StackEvent AWS::CloudFormation::Stack qatools-mferrante-2016-05-12-13-11 UPDATE_COMPLETE_CLEANUP_IN_PROGRESS", "StackEvent AWS::AutoScaling::AutoScalingGroup qatoolsAsg UPDATE_COMPLETE", "StackEvent AWS::AutoScaling::AutoScalingGroup qatoolsAsg UPDATE_IN_PROGRESS", "StackEvent AWS::EC2::Instance mongodb UPDATE_COMPLETE", "StackEvent AWS::ElasticLoadBalancing::LoadBalancer qatoolsElb UPDATE_COMPLETE", "StackEvent AWS::ElasticLoadBalancing::LoadBalancer qatoolsElb UPDATE_IN_PROGRESS", "StackEvent AWS::EC2::Instance mongodb UPDATE_IN_PROGRESS", "StackEvent AWS::CloudFormation::Stack qatools-mferrante-2016-05-12-13-11 UPDATE_IN_PROGRESS", "StackEvent AWS::CloudFormation::Stack qatools-mferrante-2016-05-12-13-11 UPDATE_COMPLETE", "StackEvent AWS::EC2::Instance mongodb DELETE_COMPLETE", "StackEvent AWS::AutoScaling::LaunchConfiguration qatoolsLc DELETE_COMPLETE", "StackEvent AWS::EC2::Instance mongodb DELETE_IN_PROGRESS", "StackEvent AWS::AutoScaling::LaunchConfiguration qatoolsLc DELETE_IN_PROGRESS", "StackEvent AWS::CloudFormation::Stack qatools-mferrante-2016-05-12-13-11 UPDATE_COMPLETE_CLEANUP_IN_PROGRESS", "StackEvent AWS::AutoScaling::AutoScalingGroup qatoolsAsg UPDATE_COMPLETE", "StackEvent AWS::AutoScaling::AutoScalingGroup qatoolsAsg UPDATE_IN_PROGRESS", "StackEvent AWS::AutoScaling::AutoScalingGroup qatoolsAsg UPDATE_IN_PROGRESS", "StackEvent AWS::AutoScaling::AutoScalingGroup qatoolsAsg UPDATE_IN_PROGRESS", "StackEvent AWS::AutoScaling::AutoScalingGroup qatoolsAsg UPDATE_IN_PROGRESS", "StackEvent AWS::AutoScaling::AutoScalingGroup qatoolsAsg UPDATE_IN_PROGRESS", "StackEvent AWS::EC2::Instance mongodb UPDATE_COMPLETE", "StackEvent AWS::EC2::Instance mongodb UPDATE_IN_PROGRESS", "StackEvent AWS::AutoScaling::LaunchConfiguration qatoolsLc UPDATE_COMPLETE", "StackEvent AWS::AutoScaling::LaunchConfiguration qatoolsLc UPDATE_IN_PROGRESS", "StackEvent AWS::EC2::Instance mongodb UPDATE_IN_PROGRESS", "StackEvent AWS::AutoScaling::LaunchConfiguration qatoolsLc UPDATE_IN_PROGRESS", "StackEvent AWS::CloudFormation::Stack qatools-mferrante-2016-05-12-13-11 UPDATE_IN_PROGRESS", "StackEvent AWS::CloudFormation::Stack qatools-mferrante-2016-05-12-13-11 CREATE_COMPLETE", "StackEvent AWS::AutoScaling::AutoScalingGroup qatoolsAsg CREATE_COMPLETE", "StackEvent AWS::AutoScaling::AutoScalingGroup qatoolsAsg CREATE_IN_PROGRESS", "StackEvent AWS::AutoScaling::AutoScalingGroup qatoolsAsg CREATE_IN_PROGRESS", "StackEvent AWS::EC2::Instance mongodb CREATE_COMPLETE", "StackEvent AWS::ElasticLoadBalancing::LoadBalancer qatoolsElb CREATE_COMPLETE", "StackEvent AWS::EC2::Instance mongodb CREATE_IN_PROGRESS", "StackEvent AWS::ElasticLoadBalancing::LoadBalancer qatoolsElb CREATE_IN_PROGRESS", "StackEvent AWS::AutoScaling::LaunchConfiguration qatoolsLc CREATE_COMPLETE", "StackEvent AWS::AutoScaling::LaunchConfiguration qatoolsLc CREATE_IN_PROGRESS", "StackEvent AWS::ElasticLoadBalancing::LoadBalancer qatoolsElb CREATE_IN_PROGRESS", "StackEvent AWS::EC2::Instance mongodb CREATE_IN_PROGRESS", "StackEvent AWS::AutoScaling::LaunchConfiguration qatoolsLc CREATE_IN_PROGRESS", "StackEvent AWS::CloudFormation::Stack qatools-mferrante-2016-05-12-13-11 CREATE_IN_PROGRESS"], "output": "Stack UPDATE complete", "stack_outputs": {"ansibleSshPrivateKeyFile": "/Users/mferrante/code/dxansible/tmp/qatools-mferrante-2016-05-12-13-11-key.pem", "domain": "test.net", "environmentType": "qatools", "mongodbIp": "172.17.70.163", "qatoolsElbDnsName": "internal-qatools-m-qatoolsE-2ZFNCPLE10U8-1689238210.us-east-1.elb.amazonaws.com", "subnet": "172.17.64.0/19"}}
```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @ferrants. To the current maintainers, @jsmartin please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by ferrants** [comment]
@jsmartin @gregdek could i get a review? this PR is super simple and i'm sure it would be welcome

**Comment by cewood** [comment]
Can this be merged now? if @jsmartin can't review shortly can someone else step in for him.

I've verified this fix works as expected for me.

This is a very common problem for people using Cloudformation, and it's quite easy to miss this issue; thus the longer it's open and not merged the more duplicate issues and PR's are going to pile up.

**Comment by ferrants** [comment]
@cewood, I know, right? @gregdek could you push on someone to get this in? It's a really small PR.

**Comment by gregdek** [comment]
Putting in shipit. Looks pretty simple. Sorry for the delay.

**Comment by ferrants** [comment]
@gregdek is there something else that needs to happen before the merge? who hits the merge button?

**Comment by gregdek** [comment]
Just waiting for the core team to get around to checking the "shipit" queue.

**Comment by gregdek** [comment]
Thanks @ferrants for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by ferrants** [comment]
rebased. ready_for_review

**Comment by gregdek** [comment]
Thanks @ferrants. To the current maintainers, @jsmartin please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by ferrants** [comment]
@gregdek you put in shipit last time, it's a small PR, would you mind doing it again? :)

**Comment by gregdek** [comment]
Agreed, putting into shipit

**Comment by ferrants** [comment]
@gregdek will someone ever get to hitting the merge button? It seems odd that this would be sitting with the shipit label for over a month

**Comment by gregdek** [comment]
Ping @ansible/core ...?

**Comment by ferrants** [comment]
Thanks!

**Pull request merged**
