### PR TITLE
Use aws connect calls that allow boto profile use

### PR DESCRIPTION
**Pull request by danielabel**
Coded with @tomwadley

### CODE REVIEW

**Comment by tedder** [comment]
@danielabel it looks like this may help with EC2/IAM Role usage. Have you tested that?

**Comment by juliedavila** [comment]
@danielabel can you rebase this plz?

**Comment by joerayme** [comment]
Done :)

**Comment by danielabel** [comment]
nice!

**Comment by micxer** [comment]
@danielabel @joerayme Did this fix work for you? I had to change the `boto.iam.connection.IAMConnection` call to make it work (see micxer/ansible-modules-core@d784e018025a7f0a0da9247cd1b6bdaa9819df2d)

**Comment by juliedavila** [comment]
Hmm..only importing `boto.ec2` is the fix?

**Comment by joerayme** [comment]
@micxer The IAM module is separate to the S3 module so that's probably why you had to change the connection method for that one and why this fix didn't work for you.

@defionscode Yes, see [the explanation for the SNS module](https://github.com/ansible/ansible-modules-extras/pull/367)

**Comment by micxer** [comment]
@joerayme true, I didn't read the filename this patch applies to :-/ Opened a new pull request as the issues with the iam module are still not completely fixed.

**Comment by gregdek** [comment]
@defionscode looks like the other one-line PR was merged. Any risk here? I'm inclined to promote this to the core team for quick review.

**Comment by juliedavila** [comment]
@gregdek I have no issues with it, I'll +1 this

**Comment by abadger** [comment]
Thanks everyone!

# Merged

Hi!

This has been merged in, and will also be included in the next major release.

If you or anyone else has any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Pull request merged**
