### PR TITLE
Add 'test' option for conditional execution

### PR DESCRIPTION
**Pull request by jaalzateolaya**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

command.py
##### ANSIBLE VERSION

```
ansible 2.1.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

This option gives us the possibility to check the return code of a
command for a conditional execution of the given task. This way, we
could run grep, or anything else, to test if we need the task to be run.

When the test command returns true, ie 0, we avoid task execution,
otherwise, we run the task.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @alexander-alzate for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by bcoca** [comment]
I'm not sure this is needed as 'shell' has this covered:

```
- shell: testcommand && command
```

**Comment by jaalzateolaya** [comment]
I think it is needed if you want to know if something has been changed by the task which is my actual case. `- shell: testcommand && command` will return `changed=True` always.

Perhaps we could use the same option for `shell` module.

**Comment by gregdek** [comment]
@alexander-alzate A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by jaalzateolaya** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @alexander-alzate for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by bcoca** [comment]
if you want to control 'changed' use `changed_when` directive

**Comment by jaalzateolaya** [comment]
@bcoca, Sorry, I didn't know `changed_wen` option and it does all the job. Hope to do something better next time.

**Comment by bcoca** [comment]
closing as per above

**Pull request closed without merging**
