### PR TITLE
ini_file: added option 'noextraspaces' to turn off inserting extra spaces around '=' symbol

### PR DESCRIPTION
**Pull request by yarick123**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

ini_file
##### ANSIBLE VERSION

```
ansible 2.0.1.0
```
##### SUMMARY

possibility not to add extra spaces around the '=' symbol into the ini-file.

In my case extra spaces in ini-file "key = value" strings are parsed incorrectly. I hope, that it would be a useful feature to control over inserting them.

Samples:
Before change - the same behaviour as without using the option 'no_extra_spaces':

```
- ini_file:
    dest="the-config.ini"
    section="auto_variables"
    option="created"
    value='{{ ansible_date_time.iso8601 }}'

-- Result in the-config.ini:
[auto_variables]
created = 2016-04-12T07:59:38Z
```

After change using the option 'no_extra_spaces':

```
- ini_file:
    dest="the-config.ini"
    section="auto_variables"
    option="created"
    value='{{ ansible_date_time.iso8601 }}'
    no_extra_spaces=true

-- Result in the-config.ini:
[auto_variables]
created=2016-04-12T08:02:12Z
```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @yarick123. To the current maintainers, @jpmens, @noseka1 please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by noseka1** [comment]
Thanks yarick123 for your contribution. It looks good to me.

**Comment by noseka1** [comment]
shipit

**Comment by jpmens** [comment]
shipit

**Comment by gregdek** [comment]
Thanks again to @yarick123 for this PR, and thanks @jpmens, @noseka1 for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by sivel** [comment]
The new option is missing a `version_added`

needs_revision

**Comment by sivel** [comment]
We have also recently decided to standardize on true/false instead of use of yes/no in documentation 

needs_revision

**Comment by resmo** [comment]
@yarick123 would you mind rename the arg to `no_extra_spaces` according the coding guidelines https://github.com/ansible/ansible/blob/devel/CODING_GUIDELINES.md#variables?

**Comment by yarick123** [comment]
@resmo no problem, I will push the new version (`noextraspaces`->`no_extra_spaces`) in several minutes

**Comment by yarick123** [comment]
thank you @resmo

**Pull request merged**
