### PR TITLE
Fix: Default ACL is not correctly handled

### PR DESCRIPTION
**Pull request by quoing**
"-d" and "-k" parameters should be prior "-m", otherwise these default ACL parameters are not correctly handled

Test system: Debian 8 (Jessie), getfacl 2.2.52

### CODE REVIEW

**Comment by hloeffler** [comment]
more problems with the acl-module:
https://github.com/ansible/ansible-modules-core/issues/2598
https://github.com/ansible/ansible/issues/13290

**Comment by quoing** [comment]
Updated to fix ansible/ansible#13290

Test playbook
[run_ansible-playbook_test_acl.yml.txt](https://github.com/ansible/ansible-modules-core/files/55271/run_ansible-playbook_test_acl.yml.txt)

**Comment by quoing** [comment]
Oh my.. ignore last commits to this. My fingers were too fast. only b32613e is valid commit.

ansible/ansible#13290 is documentation issue. entry="default:.." was removed in August.
#2598 seems to be solved by first "patch"

**Comment by bcoca** [comment]
if you want to correct and squash your commits, i'll give it a look again soon

**Comment by quoing** [comment]
@bcoca please could you cancel this pull request, I will and send new one as I messed up the previous repository and it is deleted

**Comment by quoing** [comment]
@bcoca New pull request: https://github.com/ansible/ansible-modules-core/pull/2649

Sorry again for destroying original repository.

**Comment by bcoca** [comment]
@quoing np, FYI you can close this PR yourself or you could have overwritten the branch `git push -f` and it would have 'fixed' it.

**Comment by hloeffler** [comment]
this seems not fixing my issue?
https://github.com/ansible/ansible-modules-core/issues/2598#issuecomment-163136405

**Pull request closed without merging**
