### PR TITLE
Update documentation to reflect need for mysql client

### PR DESCRIPTION
**Pull request by Jmainguy**
This is to answer https://github.com/ansible/ansible-modules-core/issues/2164. There is a requirement for the mysql command which was not made clear before.

### CODE REVIEW

**Comment by gregdek** [comment]
@marktheunissen Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by Jmainguy** [comment]
@gregdek we need to update the mysql module to make it clear @marktheunissen does not wish to be the maintainer (see other open mysql bugs and his responses there). Where should we do this?

**Comment by bcoca** [comment]
@Jmainguy i would specify 'mysql command line client' and also give a yum install example and I would probably add the 'mysql command line client' to the requirements field

**Comment by bcoca** [comment]
@Jmainguy as for the maintainer, just update the authors field (we can leave his name in the copyright by the license)

**Comment by Jmainguy** [comment]
@bcoca implemented changes requested.

**Comment by marktheunissen** [comment]
I am no longer the maintainer, as per https://github.com/ansible/ansible-modules-core/pull/2653

**Comment by Jmainguy** [comment]
@bcoca good to go ^^?

**Pull request merged**
