### PR TITLE
check mode added and fix for #644

### LINKED ISSUE #644: a2enmod/a2dismod print different status message on openSUSE
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.8.2
##### Environment:

Control host and managed host: openSUSE 13.2
##### Summary:

On openSUSE, `a2enmod`/`a2dismod` print the following messages, if the module in question was already enabled/disabled:

```
"suexec" not present
"suexec" already present
```

Ansible's `apache2_module` only recognizes `... already disabled` or `... already enabled`. Therefore, the tasks are unnecessarily treated as changed everytime they're run, and notifications are executed.

### LINKED ISSUE #2081: a2enmod/a2dismod multiline output
**Issue Type:** Bugfix Pull Request

**Ansible Version:** ansible 1.9.2

**Summary:**

In some cases a2enmod/a2dismod response message has multiple lines. E.g:

"Your MPM seems to be threaded. Selecting cgid instead of cgi.
Module cgid already enabled"

Because of that an item like
`- apache2_module name=cgi state=absent`
is always changed.

**Solution:** Additional multiline Option in the regular expression match.

```
--- apache2_module-orig.py      2015-09-15 12:34:03.448258630 +0200
+++ apache2_module.py   2015-09-15 12:34:40.888259142 +0200
@@ -56,7 +56,7 @@

     result, stdout, stderr = module.run_command("%s %s" % (a2dismod_binary, name))

-    if re.match(r'.*\b' + name + r' already disabled', stdout, re.S):
+    if re.match(r'.*\b' + name + r' already disabled', stdout, re.S|re.M):
         module.exit_json(changed = False, result = "Success")
     elif result != 0:
         module.fail_json(msg="Failed to disable module %s: %s" % (name, stdout))
@@ -71,7 +71,7 @@

     result, stdout, stderr = module.run_command("%s %s" % (a2enmod_binary, name))

-    if re.match(r'.*\b' + name + r' already enabled', stdout, re.S):
+    if re.match(r'.*\b' + name + r' already enabled', stdout, re.S|re.M):
         module.exit_json(changed = False, result = "Success")
     elif result != 0:
         module.fail_json(msg="Failed to enable module %s: %s" % (name, stdout))
```

### PR DESCRIPTION
**Pull request by n0trax**
This PR fixes #644, fixes #2091, fixes #2081, fixes #2082, closes #3063 and fixes #3406 .

I added a check for actions on module cgi if apache runs threaded. In this case 2enmod/a2dismod 
changes the module from cgi to cgid and the task on module cgi is always changed. I'm not sure if the 
error message is the best solution for this problem.

I tested it with OpenSuSE 13.2, Debian 7/8 and Ubuntu 14.04 LTS
On Fedora22 and CentOS7 only the check mode is working, because of missing a2enmod/a2dismod.

### CODE REVIEW

**Comment by gregdek** [comment]
@n0trax Thanks for submitting this pull request. Unfortunately, it appears that the underlying code has changed since your submission, and this PR now needs to be rebased. 

If you believe that this PR still applies, please rebase and we will put it into our community review process as soon as possible. 

Once you have rebased this PR, please add a comment with the text "ready_for_review" and we will continue with the review process.  Thanks!

**Comment by n0trax** [comment]
@gregdek i'm not sure if i did the rebase in the right way. There are now to many commits and the file files/stat.py is not affected by my patch.
Please let me know if it's better to close this PR and start a new one.

**Comment by n0trax** [comment]
ready_for_review

**Comment by gregdek** [comment]
Patch looks ok. Thanks @n0trax.

@berendt Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by gregdek** [comment]
@berendt This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by robynbergeron** [comment]
@berendt still waiting on your review.  Please comment with text 'shipit' or 'needs_revision' as appropriate. If we don't hear from you within 14 days, we will start to look for additional maintainers for this module.

**Comment by robinro** [comment]
The fix does not work with the different a2enmod output from opensuse. It does not fix/replace #2091

**Comment by gregdek** [comment]
@berendt This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
@berendt still waiting on your review.  Please comment with text 'shipit' or 'needs_revision' as appropriate. If we don't hear from you within 14 days, we will start to look for additional maintainers for this module.

**Comment by gregdek** [comment]
Moving to review by @ansible/core team. Sorry @n0trax for the delay, and thanks for your patience.

**Comment by n0trax** [comment]
@gregdek no problem. Let me now if there is anything i can do.

**Comment by robinro** [comment]
@n0trax 

There are some cases not covered by this PR:
- httpd -M does not return the configured case, but the currently running case. So if you run this module twice, you get changed=True both times, breaking idempotency. To apply changes and make them appear one needs to restart apache, something this module should not do. Therefore I think the approach using `httpd -M` does not work
- relying on the return code of `a2enmod` is not sufficient. It is `0` (at least on opensuse and ubuntu), even if
  - the module is already enabled
  - the user has no permission to enable the module

needs_revision

**Comment by robinro** [comment]
Sadly I don't have a good idea how to enable checkmode otherwise. The only thing we can use somewhat relieably is the output of a2enmod, but this changes the system state.

**Comment by n0trax** [comment]
@robinro 
Could you please provide me some more information about your test scenario?

AFAIK the `apache2ctl -M` on ubuntu 14.04  returns the configured modules and not only the 
running ones. I'm not sure on the behavior of SUSE and RedHat at the moment.

On ubuntu 14.04 / debian 8.4 the return code of `a2enmod` is `13` if the user has no permission to enable modules. Only if the module is already enabled it return `0`, but in that case the module won't do anything.

I will check that later on RedHat and SUSE.

**Comment by gregdek** [comment]
Thanks @n0trax for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by robinro** [comment]
@n0trax 
The testsystem is used is OpenSuSE Leap 42.1 (docker run opensuse:latest).

I looked in a bit more detail what happens: `httpd -M` returns the **running** modules, `apachectl -M` returns the **enabled** modules. So to fix this problem you can just reorder the list that checks for those, assuming this doesn't break RHEL/...

This would be great as it would allow for a working checkmode!

On OpenSuSE a2enmod always returns 0, even when run by some random user with no write permissions at all:

```
>> ansible -i 'pc30,' pc30 -m apache2_module -a 'name=alias state=absent' -v                 
Using /etc/ansible/ansible.cfg as config file
pc30 | FAILED! => {
    "changed": false, 
    "failed": true, 
    "msg": "Failed to set module alias disabled.", 
    "rc": 0, 
    "stderr": "sed: couldn't open temporary file /etc/sysconfig/sedEKpkQK: Permission denied\n", 
    "stdout": "", 
    "stdout_lines": []
}
```

Checking for the Permission denied output has no negative side effects that I'm aware of. Maybe you can reuse the check on:
https://github.com/robinro/ansible-modules-core/blob/e85a4136fb66943296a2a3756f914ffdffd3e86f/web_infrastructure/apache2_module.py#L89-L107

That branch linked above is the result of me testing the outstanding pull requests for apache2_module, where I also cleaned up some duplicated code. If we get a version with working checkmode this would obviously be better.

Other approach to work around the permission denied situation and make the implementation more robust: Don't check any fail cases of a2enmod, but run `_module_is_enabled` a second time afterwards and see whether the module is in the correct state.

Please consider to run and extend the integration tests I started: https://github.com/ansible/ansible/pull/15380

**Comment by robinro** [comment]
Does any system actually have `a2enmod` but not `apachectl` or `apache2ctl`?
If not you can just remove the `httpd` reference in the `_module_is_enabled` function.

**Comment by n0trax** [comment]
Hi @robinro,

i added the `httpd` as control_binary only for REHL/Fedora/CentOS to support at least the 
check_mode, but i think this was not a good idea and i will remove it as control_binary.

The second run of `_module_enabled` sounds great, then we have no problems with return codes 
or script output on different distributions.

I will have a look at your integration tests. Please give me a few days to implement your suggestions 
and thanks for your input.

**Comment by sivel** [comment]
This PR appears to need rebased against the current version of devel.  At the moment this PR affects 183 files.

needs_rebase

**Comment by n0trax** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @n0trax. To the current maintainers, @robinro please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by robinro** [comment]
Thanks for the work and rebase @n0trax 
This PR is next in line on my agenda for apache2_module, so you hopefully won't need another rebase ;)

The integration tests run successfully on ubuntu and suse and the new structure is a lot more robust than the old regexp-parsing of output.
I would like to merge the enable and disable functions, to remove duplicated code as far as possible, see https://github.com/n0trax/ansible-modules-core/pull/6
With this integrated it's a green light for me. If you don't like the suggested change, let me know why.

**Comment by n0trax** [comment]
@robinro I just merged your code cleanup.

Sorry, I accidently missed to integrate it...

**Comment by robinro** [comment]
thanks!
@ansible/core shipit

**Comment by robinro** [comment]
@n0trax 
When you put 
fixes #644, fixes #2091, fixes #2081, fixes #2082
in the PR (first message in this thread) then it automatically closes those when this gets merged.
See https://help.github.com/articles/closing-issues-via-commit-messages/ and https://github.com/blog/1506-closing-issues-via-pull-requests

This also fixes #3406

**Comment by gregdek** [comment]
Thanks again to @n0trax for this PR, and thanks @robinro for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by robinro** [comment]
btw @ansible/core: this is first of all a bugfix_pull_request

**Comment by n0trax** [comment]
Thanks @robinro for the hint, i will keep that in mind for my next PR.

**Comment by robinro** [comment]
@n0trax you can still do it in this one, just edit :pencil2: the message

**Comment by bcoca** [comment]
@n0trax please cleanup the commit history, you have a merge in there

**Comment by gregdek** [comment]
Thanks @n0trax. To the current maintainers, @robinro please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by robinro** [comment]
next try: shipit

**Comment by gregdek** [comment]
Thanks again to @n0trax for this PR, and thanks @robinro for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by robinro** [comment]
this also closes #3063 
@n0trax maybe you can rebase/squash everything in one commit to cleanup the history?

**Comment by n0trax** [comment]
@robinro no problem, i will perform the rebase tonight.

**Comment by n0trax** [comment]
@robinro is this ok?
Sorry for the delay.

**Comment by robinro** [comment]
@n0trax looks good to me, thanks!

**Comment by robinro** [comment]
@bcoca please merge

**Pull request merged**
