### PR TITLE
get_url temporary destination option

### PR DESCRIPTION
**Pull request by sysadmin75**
Adds option for temporary destination directory for download file to address ansible/ansible#9512

### CODE REVIEW

**Comment by muffl0n** [comment]
Sounds like a nice idea. But you should not put "/tmp" as the default. `tempfile.mkstemp()` does not use /tmp in alle cases. See: https://docs.python.org/2/library/tempfile.html#tempfile.tempdir

For example, on Windows it might be something like c:\tmp or c:\temp.

Edit: Windows seems to be a bad example because there is an own module for that: `win_get_url`. But there is still a possibility that /tmp is not the system's tmpdir.

**Comment by sysadmin75** [comment]
Yep, very valid point.

**Comment by bcoca** [comment]
it defaults to TMPDIR, TEMP or TMP env variables or a platform specific

a default of 'temp dir' and a note in description pointing to the function for details is good enough

**Comment by sysadmin75** [comment]
@bcoca I think the problem @muffl0n is pointing out is that I hard code '/tmp' as the default destination dir.

**Comment by bcoca** [comment]
@sysadmin75 i got that, i was just making a note of what the docs should be when you change it to the default.

**Comment by sysadmin75** [comment]
Closing in preference to https://github.com/ansible/ansible-modules-core/pull/1887

**Pull request closed without merging**
