### PR TITLE
Make remote_group handle name and id in cloud/openstack/os_security_group_rule.py

### PR DESCRIPTION
**Pull request by donovan**
This pull request adds support for using the name of a remote security group when creating security group rules that reference other security groups rather than only supporting using the id. It addresses this todo:

 # TODO(mordred): Make remote_group handle name and id

I looked at fixing this in **create_security_group_rule** in **shade/openstackcloud.py** but I think its cleaner to leave that function alone. This means that the fix can happen only on the ansible side. It does mean that the shade function only supports ids but there is no reason that it could not be extended to support names as well at a later date.

I used the following playbook snippet for testing all the combinations of **security_group** and **remote_group** being ids or names:

``` yaml
    - name: Create web security group
      os_security_group:
        state: present
        name: web1
        description: web group
      register: web1_sg_info

    - name: Create db security group
      os_security_group:
        state: present
        name: db1
        description: db group
      register: db1_sg_info

    - name: Create a security group rule to allow the web group to access postgres
      os_security_group_rule:
        state: present
        #security_group: db1
        security_group: "{{ db1_sg_info.id }}"
        protocol: tcp
        port_range_min: 5432
        port_range_max: 5432
        remote_group: web1
        #remote_group: "{{ web1_sg_info.id }}"
```

Testing results are:

| sg and rules exist | yes | yes | yes | yes | no | no | no | no |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
| security_group | name | name | id | id | name | name | id | id |
| remote_group | name | id | name | id | name | id | name | id |
| Result | ok | ok | ok | ok | changed | changed | changed | changed |

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @donovan. @emonty @shrews @dguerri @juliakreger @j2sol @rcarrillocruz please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by robynbergeron** [comment]
@emonty @shrews @juliakreger @j2sol @rcarrillocruz This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by omgjlk** [comment]
I think this looks fine. I can't tell if the RETURN data is changed, it has at least in the check mode, but doesn't necessarily appear to in the real version.

shipit

**Comment by donovan** [comment]
Hi the previous comment prompted me to take another look at this. Seems my patch caused a regression when setting a os_security_group_rule without a remote group (ie with a remote_ip_prefix) causing a TypeError: 'NoneType' object has no attribute '**getitem**'.

I have addressed this regression and retested the matrix of 24 combinations with example playbooks that include remote_ip_prefix rules. Testing playbooks and bash scripts for iterating through the combinations available on request.

I also merged upstream/devel into my branch, so its up to date again.

**Comment by Shrews** [comment]
Ran the shade ansible test suite with the new version and passed successfully.

shipit

**Comment by rcarrillocruz** [comment]
shipit

**Comment by gregdek** [comment]
Thanks again to @donovan for this PR, and thanks @emonty, @shrews, @juliakreger, @j2sol, @rcarrillocruz for reviewing. Marking for inclusion.

**Pull request merged**
