### PR TITLE
make desired_capacity optional when replacing instances in ec2_asg

### LINKED ISSUE #3806: ASG replacing an instance
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

cloud/amazon/ec2_asg
##### ANSIBLE VERSION

```
ansible 2.0.2.0
  config file = snip
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

```
[defaults]
roles_path = galaxy
```
##### OS / ENVIRONMENT

```
 uname -a
Linux ip-10-10-10-89 3.13.0-74-generic #118-Ubuntu SMP Thu Dec 17 22:52:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```
##### SUMMARY

Difficulty (possibly documentation ambiguity) when using the ASG module to replace a single instance in an ASG.
##### STEPS TO REPRODUCE

The documentation for the ASG module around min, max and desired all say if they're not included ansible will assume the current ASG size settings. The larger context is I'm doing rolling upgrades where I check consul health checks between replacing instances.

playbook.yml

```
    - name: Gather list of running instances
      ec2_remote_facts:
        filters:
          instance-state-name: running
          "tag:App": snip
      register: current_instances

    - include: rolling_upgrade.yml
      with_items: "{{ current_instances.instances }}"
      when: current_instances.instances > 0
```

rolling_upgrade.yml

```
- name: Replace a single instance in the ASG
  ec2_asg:
    name: "snip"
    launch_config_name: "{{ lc.name }}"
    region: "{{ aws_region }}"
    replace_instances:
      - "{{ replace.id }}"
    wait_for_instances: 'yes'
    lc_check: false
    default_cooldown: 500
    vpc_zone_identifier:
      - "{{ vpc_subnet_id[0] }}"
    tags:
      - Name: snip
      - App: snip
```
##### EXPECTED RESULTS

the desired, min and max should stay the same with one EC2 instance being replaced
##### ACTUAL RESULTS

```
ansible-playbook -vvv --vault-password-file ../vaultpassword deploy.yml
TASK [Replace a single instance in the ASG] ************************************
task path: /home/ubuntu/on-premise/ansible/galileo-elasticsearch/rolling_upgrade.yml:17
ESTABLISH LOCAL CONNECTION FOR USER: ubuntu
127.0.0.1 EXEC /bin/sh -c '( umask 22 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1464719870.89-169618325026683 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1464719870.89-169618325026683 `" )'
127.0.0.1 PUT /tmp/tmpm3UoWX TO /home/ubuntu/.ansible/tmp/ansible-tmp-1464719870.89-169618325026683/ec2_asg
127.0.0.1 EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /home/ubuntu/.ansible/tmp/ansible-tmp-1464719870.89-169618325026683/ec2_asg'
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1464719870.89-169618325026683/ec2_asg", line 3044, in <module>
    main()
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1464719870.89-169618325026683/ec2_asg", line 3038, in main
    replace_changed, asg_properties=replace(connection, module)
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1464719870.89-169618325026683/ec2_asg", line 2778, in replace
    num_new_inst_needed = desired_capacity - len(new_instances)
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'

fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "ec2_asg"}, "module_stderr": "Traceback (most recent call last):\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1464719870.89-169618325026683/ec2_asg\", line 3044, in <module>\n    main()\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1464719870.89-169618325026683/ec2_asg\", line 3038, in main\n    replace_changed, asg_properties=replace(connection, module)\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1464719870.89-169618325026683/ec2_asg\", line 2778, in replace\n    num_new_inst_needed = desired_capacity - len(new_instances)\nTypeError: unsupported operand type(s) for -: 'NoneType' and 'int'\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}
    to retry, use: --limit @deploy.retry
```

### PR DESCRIPTION
**Pull request by orischwartz**
##### ISSUE TYPE

Bugfix Pull Request
##### COMPONENT NAME

cloud/amazon/ec2_asg
##### ANSIBLE VERSION

```
ansible 2.0.2.0
  config file = snip
  configured module search path = Default w/o overrides
```
##### SUMMARY

`desired_capacity` is not a required parameter for `ec2_asg` and docs state _if unspecified then the current group value will be used._

If desired_capacity is omitted and instances are replaced (either via `replace_all_instances` or `replace_instances`) then the following error appears:

```
num_new_inst_needed = desired_capacity - len(new_instances)
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
```

Fixes #3806

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @orischwartz for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @orischwartz for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@orischwartz A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by orischwartz** [comment]
Implemented in 8d1fe3b444737b26d6c634fc55010239ad342174

**Pull request closed without merging**
