### PR TITLE
Add support for SNS notification ARNs in CloudFormation

### PR DESCRIPTION
**Pull request by s0enke**
This adds the possibility to push stack events to SNS topics.

cc @bracki

### CODE REVIEW

**Comment by bennojoy** [comment]
@s0enke  could you please resolve the conflicts .. thanks

**Comment by s0enke** [comment]
@bennojoy Done! Would also be good to know if there is a place where I could add integration tests if wanted :)

**Comment by bennojoy** [comment]
@s0enke  thanks and sorry i should have mentioned this earlier ,can you please add version_added: 2.0 in the module doc for the new parameter and an emplty alias[] is not needed. and tests can be added in https://github.com/ansible/ansible/tree/devel/test it does need some work for all modules , it is in my todo list too

**Comment by s0enke** [comment]
> @s0enke thanks and sorry i should have mentioned this earlier ,can you please add version_added: 2.0 in the module doc for the new parameter and an emplty alias[] is not needed.

Ok, done!

**Comment by bennojoy** [comment]
merged thanks

**Pull request merged**
