### PR TITLE
Fix os_router to accept internal interfaces

### PR DESCRIPTION
**Pull request by Shrews**
Allow the 'interfaces' attribute to represent internal router
interfaces, composed of subnet names, and the 'external_fixed_ips'
attribute to represent external interface subnet/IP.

### CODE REVIEW

**Comment by Shrews** [comment]
attn: @emonty @j2sol 

This fixes a major bug where we just didn't accept internal interfaces. I've tested this myself but would love some testing by others.

**Comment by robynbergeron** [comment]
[module: cloud/openstack/os_router.py]

**Comment by robynbergeron** [comment]
Hi @Shrews -- thanks for this PR.

Marking this as owner_pr so we can ship it in a few days -- normally would just mark it for shipping right away but since you said reviews would be nice to have, i shall seek them :)

@dguerri @juliakreger @j2sol @rcarrillocruz @emonty --

Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by emonty** [comment]
shipt

**Pull request merged**
