### PR TITLE
update win_get_url.ps1

### PR DESCRIPTION
**Pull request by mwan2013**
If md5 is passed in, if will be compared with the md5 of the destination file, which is computed after the transferring process.

### CODE REVIEW

**Comment by cchurch** [comment]
Could you update `win_get_url.py` to add this new `md5` parameter to the module docs?

**Comment by bcoca** [comment]
instead of md5, which won't work in some environments, can you use sha? The parameter itself might be better as something more generically named (checksum?).

**Comment by gregdek** [comment]
@mwan2013 After some review, it looks as though this PR needs some revisions. 

Please make the suggested revisions, and when you're done, please add a comment with the text "ready_for_review" and we will continue with the review process.  Thanks!

**Comment by gregdek** [comment]
@mwan2013 A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes.

**Comment by robynbergeron** [comment]
@mwan2013 Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If we don't hear from you within another 14 days, we will close this pull request.

**Comment by gregdek** [comment]
Closing due to contributor inactivity.

**Pull request closed without merging**
