### PR TITLE
implement docker state=image_present

### PR DESCRIPTION
**Pull request by ibotty**
This pull request allows to only pull an image without creating a container. To be used e.g. with "--rm" containers.

### CODE REVIEW

**Comment by bennojoy** [comment]
@ibotty  this functionality is already available with the docker_image module, any reason you may not want to use that ?

**Comment by ibotty** [comment]
No, afaict it is not. Docker_image tries to **build** an image. I want it to be fetched from a registry.

edit:

```
> ansible -m docker_image -a 'name=fedora state=present' host
host | FAILED! => {
    "changed": false, 
    "failed": true, 
    "msg": "BECOME-SUCCESS-mudgyfwrqglwonlijqqqgcrmlvobhjbk\r\nTraceback (most recent call last):\r\n  File \"/home/tob/.ansible/tmp/ansible-tmp-1441693575.12-56104707654521/docker_image\", line 1999, in <module>\r\n    main()\r\n  File \"/home/tob/.ansible/tmp/ansible-tmp-1441693575.12-56104707654521/docker_image\", line 280, in main\r\n    image_id = manager.build()\r\n  File \"/home/tob/.ansible/tmp/ansible-tmp-1441693575.12-56104707654521/docker_image\", line 177, in build\r\n    stream = self.client.build(self.path, dockerfile=self.dockerfile, tag=':'.join([self.name, self.tag]), nocache=self.nocache, rm=True, stream=True)\r\n  File \"/usr/lib/python2.7/site-packages/docker/client.py\", line 307, in build\r\n    raise TypeError(\"Either path or fileobj needs to be provided.\")\r\nTypeError: Either path or fileobj needs to be provided.\r\n", 
    "parsed": false
}

```

**Comment by gregdek** [comment]
@cove @joshuaconner @softzilla @smashwilson Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by ibotty** [comment]
any updates?

**Comment by elouanKeryell-Even** [comment]
I would also be very interested to use an ansible module to pull docker images. However, it's true that it would fit better in docker_image module.

**Comment by ibotty** [comment]
As is, the 'docker_image' module is only about _building_ images. So imo it's misnamed. Implementing it in 'docker_image' would be duplicating _a lot_ of code from the 'docker' module.

**Comment by elouanKeryell-Even** [comment]
Ok ok, I didn't know "docker_image" was just about building. Also, I haven't looked the code of both modules, I was just speaking from an user point of view.

**Comment by smashwilson** [comment]
I really hesitate to add _more_ states to the Docker module; it's already kind of overwhelming, in my opinion. Also, conceptually, all of the other states here manage the lifecycle of Docker containers; this one manages the lifecycle of a Docker image instead.

Even if it's convenient to put it in this module in terms of source code, adding this here feels weird to me. I tend to prefer offering an intuitive experience for users over having conveniently organized source code, when I have to choose one or the other.

It would be more work, but maybe `docker_images` could use some refactoring, too. There _is_ a way to share code among Ansible modules via the [`module_utils` package](https://github.com/ansible/ansible/tree/devel/lib/ansible/module_utils) and the two already duplicate a lot of authentication logic. I'm not certain of `docker_image`'s future, though; it was marked deprecated for a while.

**Comment by ibotty** [comment]
So, what's the plan? I'd really like to get this in asap.

**Comment by ibotty** [comment]
Any updates?

**Comment by kevzettler** [comment]
+1 for this. I needed it recently. its basic docker functionality `docker pull remote-repo/image1`

**Comment by gregdek** [comment]
Per @smashwilson comment, going to close this one. Nevertheless, a sincere thanks @ibotty for the PR. 

NOTE: there is a rewrite effort for the Docker module underway. See: https://github.com/ansible/proposals/issues/1

Please take a look at those proposals and comment.

**Pull request closed without merging**
