### PR TITLE
docker_service: prevent non specified services from being launched

### LINKED ISSUE #4020: docker_service: wrong logic or processing services/scale
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

docker_service
##### ANSIBLE VERSION

```
ansible 2.1.0.0
```
##### CONFIGURATION

nothing special
##### OS / ENVIRONMENT

Centos 7, docker-1.11.2, docker-compose 1.7.1
##### SUMMARY

docker_service launches services, not mentioned in service parameter
##### STEPS TO REPRODUCE

```
[root@ba0 test]# cat docker-compose.yml
version: "2"

services:
  centos1:
    image: centos:centos7
    command: sleep 1d

  centos2:
    image: centos:centos7
    command: sleep 1d

  centos3:
    image: centos:centos7
    command: sleep 1d

ansible -m docker_service -c local localhost -a "project_src=/tmp/test/ services=centos2 scale={'centos1':2} state=present"
```
##### EXPECTED RESULTS

I expect that only 'centos2' service launched
##### ACTUAL RESULTS

Both centos2 and scaled centos1 launched.

```
localhost | SUCCESS => {
    "ansible_facts": {
        "centos1": {
            "test_centos1_1": {
                "cmd": [
                    "sleep",
                    "1d"
                ],
                "image": "centos:centos7",
                "labels": {
                    "build-date": "2016-06-02",
                    "com.docker.compose.config-hash": "0d0b17f36bed81ed3668740e739677660e8f65e393cb9c3f57c3d0887c16ecc0",
                    "com.docker.compose.container-number": "1",
                    "com.docker.compose.oneoff": "False",
                    "com.docker.compose.project": "test",
                    "com.docker.compose.service": "centos1",
                    "com.docker.compose.version": "1.7.1",
                    "license": "GPLv2",
                    "name": "CentOS Base Image",
                    "vendor": "CentOS"
                },
                "networks": {
                    "test_default": {
                        "IPAddress": "172.20.0.3",
                        "IPPrefixLen": 16,
                        "aliases": [
                            "centos1",
                            "cba992c086f6"
                        ],
                        "globalIPv6": "",
                        "globalIPv6PrefixLen": 0,
                        "links": null,
                        "macAddress": "02:42:ac:14:00:03"
                    }
                },
                "state": {
                    "running": true,
                    "status": "running"
                }
            },
            "test_centos1_2": {
                "cmd": [
                    "sleep",
                    "1d"
                ],
                "image": "centos:centos7",
                "labels": {
                    "build-date": "2016-06-02",
                    "com.docker.compose.config-hash": "0d0b17f36bed81ed3668740e739677660e8f65e393cb9c3f57c3d0887c16ecc0",
                    "com.docker.compose.container-number": "2",
                    "com.docker.compose.oneoff": "False",
                    "com.docker.compose.project": "test",
                    "com.docker.compose.service": "centos1",
                    "com.docker.compose.version": "1.7.1",
                    "license": "GPLv2",
                    "name": "CentOS Base Image",
                    "vendor": "CentOS"
                },
                "networks": {
                    "test_default": {
                        "IPAddress": "172.20.0.4",
                        "IPPrefixLen": 16,
                        "aliases": [
                            "30249f7e074e",
                            "centos1"
                        ],
                        "globalIPv6": "",
                        "globalIPv6PrefixLen": 0,
                        "links": null,
                        "macAddress": "02:42:ac:14:00:04"
                    }
                },
                "state": {
                    "running": true,
                    "status": "running"
                }
            }
        },
        "centos2": {
            "test_centos2_1": {
                "cmd": [
                    "sleep",
                    "1d"
                ],
                "image": "centos:centos7",
                "labels": {
                    "build-date": "2016-06-02",
                    "com.docker.compose.config-hash": "0d0b17f36bed81ed3668740e739677660e8f65e393cb9c3f57c3d0887c16ecc0",
                    "com.docker.compose.container-number": "1",
                    "com.docker.compose.oneoff": "False",
                    "com.docker.compose.project": "test",
                    "com.docker.compose.service": "centos2",
                    "com.docker.compose.version": "1.7.1",
                    "license": "GPLv2",
                    "name": "CentOS Base Image",
                    "vendor": "CentOS"
                },
                "networks": {
                    "test_default": {
                        "IPAddress": "172.20.0.2",
                        "IPPrefixLen": 16,
                        "aliases": [
                            "81c91cb6007b",
                            "centos2"
                        ],
                        "globalIPv6": "",
                        "globalIPv6PrefixLen": 0,
                        "links": null,
                        "macAddress": "02:42:ac:14:00:02"
                    }
                },
                "state": {
                    "running": true,
                    "status": "running"
                }
            }
        },
        "centos3": {}
    },
    "changed": true
}
```

### PR DESCRIPTION
**Pull request by awasilyev**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

docker_service
##### ANSIBLE VERSION

```
2.1.0.0
```
##### SUMMARY

Fixes #4020 

this will scale only services, mentioned in 'services' parameter, it present

### CODE REVIEW

**Comment by gregdek** [comment]
maintainer unknown ping @gregdek @resmo @robynbergeron.

**Comment by gregdek** [comment]
maintainer unknown ping @gregdek @resmo @robynbergeron.

**Comment by chouseknecht** [comment]
Don't think this is correct. The module should behave the same as docker-compose. What if I don't explicitly list services (as it's not a required parameter), and I just say scale: serviceX: 3? The module would do nothing. Docker compose on the other hand will start and scale serviceX.

**Comment by gregdek** [comment]
Thanks @awasilyev for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @awasilyev for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
