### PR TITLE
Add jinja2 way of specifying the md5'd password

### PR DESCRIPTION
**Pull request by tedder**
##### ISSUE TYPE
- Docs Pull Request
##### COMPONENT NAME

postgresql_user.py
##### ANSIBLE VERSION

```
1.9.5
```
##### SUMMARY

The md5 method given is not Ansibleonic. My way is nicer.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @tedder for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by tedder** [comment]
ready_for_review

and while I'm at it:

cat_facts

**Comment by gregdek** [comment]
Thanks @tedder for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by tedder** [comment]
Closing, I've had trouble getting it to actually work in testing.

**Pull request closed without merging**
