### PR TITLE
ec2_group: make group_name only match groups in specified VPC

### PR DESCRIPTION
**Pull request by bretmartin**
ec2_group allows specification of another group by name with group_name. However, it currently matches names against groups in all VPCs, even if the currently-being-managed security group has a vpc_id specified.

When referring to other security groups with group_name, it is only possible to reference those in the same VPC as the currently-being-managed group (or, for a non-VPC EC2 security group, another such group). This PR brings ec2_group in line with that restriction.

### CODE REVIEW

**Comment by bretmartin** [comment]
@bcoca I'm curious why this is classified as a feature request rather than a bug fix.

**Comment by bcoca** [comment]
sorry, i misunderstood and thought it was adding a new ability on how to group, not correcting existing one.

**Comment by bretmartin** [comment]
No problem; sorry I wasn't clear.

**Comment by bennojoy** [comment]
@bretmartin  do you think #1212  would fix this ? if not can you please rebase .. thanks

**Comment by gregdek** [comment]
Hi @bretmartin does this still apply? If so, please rebase and we'll get it into the community review process asap.

**Comment by gregdek** [comment]
@bretmartin A friendly reminder: this pull request has been marked as needing your action, and it hasn't been updated in the last month. 

If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we'll keep it open pending your changes.

If we receive no indication from you within a week, we will close this pull request.

**Comment by bretmartin** [comment]
@gregdek Sorry for my delayed response. It appears to me that #1212 is essentially equivalent to this PR.

**Pull request closed without merging**
