### PR TITLE
Make ec2_elb_lb respect VPCs when resolving groups

### PR DESCRIPTION
**Pull request by shaunbrady**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

cloud/amazon/ec2_elb_lb.py
##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.1.0.0
  config file = /home/sbrady/.ansible.cfg
  configured module search path = Default w/o overrides
$
```
##### SUMMARY

When resolving group names to group_ids, ec2_elb_lb can find the same name(s) in other VPCs.  Since an ELB is tied to a VPC (by the subnets provided) we should only consider group names in our VPC.  This avoids the below error.

```
boto.exception.BotoServerError: BotoServerError: 409 Conflict
<ErrorResponse xmlns="http://elasticloadbalancing.amazonaws.com/doc/2012-06-01/">
  <Error>
    <Type>Sender</Type>
    <Code>InvalidConfigurationRequest</Code>
    <Message>Security group &quot;sg-12db4676&quot; does not belong to VPC &quot;vpc-724a7a17&quot;</Message>
  </Error>
  <RequestId>dbcd7950-54ec-11e6-b41c-4d30340fdc1f</RequestId>
</ErrorResponse>
```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @shaunbrady for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by shaunbrady** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @shaunbrady. To the current maintainers, @jsdalton, @rickmendes please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by ghost** [comment]
@shaunbrady This looks good to me. Nice catch. shipit

**Comment by gregdek** [comment]
Thanks again to @shaunbrady for this PR, and thanks @jsdalton, @rickmendes for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request merged**
